Repository ec-europa/europa-component-library, pull requests merged in 2018-05, with the labels that each got.

#685 fix(inpage-nav): try with stickfilljs - INNO-943
  src/generic/generic-component-inpage-navigation/README.md
  src/generic/generic-component-inpage-navigation/data/demo.js
  src/generic/generic-component-inpage-navigation/generic-component-inpage-navigation.js
  src/generic/generic-component-inpage-navigation/generic-component-inpage-navigation.scss
  src/generic/generic-component-inpage-navigation/package.json
  src/systems/ec/_partials/_preview-inpage-navigation.twig
  src/systems/ec/ec-component/ec-component-navigation/ec-component-inpage-navigation/README.md
  src/systems/ec/ec-component/ec-component-navigation/ec-component-inpage-navigation/package.json
  src/systems/eu/_partials/_preview-inpage-navigation.twig
  src/systems/eu/eu-component/eu-component-navigation/eu-component-inpage-navigation/README.md
  src/systems/eu/eu-component/eu-component-navigation/eu-component-inpage-navigation/package.json
  yarn.lock
Labels: tag: bug fix

#686 fix(listing): remove extra padding - INNO-916
  .drone.yml
  src/generic/generic-component-list-item/generic-component-list-item.scss
  src/generic/generic-component-listing/generic-component-listing.scss
  src/systems/ec/ec-component/ec-component-list-item/test/spec/screenshots/reference/list-items/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-list-item/test/spec/screenshots/reference/list-items/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-list-item/test/spec/screenshots/reference/list-items/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-list-item/test/spec/screenshots/reference/list-items/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-listing/test/spec/screenshots/reference/listings/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-listing/test/spec/screenshots/reference/listings/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-listing/test/spec/screenshots/reference/listings/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-listing/test/spec/screenshots/reference/listings/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-template/ec-template-listing/test/spec/screenshots/reference/templates-listings/Windows 10_Chrome_v60.png
  src/systems/ec/ec-template/ec-template-listing/test/spec/screenshots/reference/templates-listings/Windows 7_Firefox_v54.png
  src/systems/ec/ec-template/ec-template-listing/test/spec/screenshots/reference/templates-listings/Windows 7_IE_v11.png
  src/systems/ec/ec-template/ec-template-listing/test/spec/screenshots/reference/templates-listings/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-list-item/test/spec/screenshots/reference/list-items/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-list-item/test/spec/screenshots/reference/list-items/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-list-item/test/spec/screenshots/reference/list-items/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-list-item/test/spec/screenshots/reference/list-items/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-listing/test/spec/screenshots/reference/listings/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-listing/test/spec/screenshots/reference/listings/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-listing/test/spec/screenshots/reference/listings/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-listing/test/spec/screenshots/reference/listings/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/macOS 10.12_Safari_v11.png
Labels: process: review needed, tag: enhancement

#687 fix(templates-search): correct usage of flex utility class - noissue
  src/systems/ec/ec-template/ec-template-search/ec-template-search.twig
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/desktop/Windows 10_Chrome_v60.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/desktop/Windows 7_Firefox_v54.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/desktop/Windows 7_IE_v11.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/desktop/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/mobile/Windows 10_Chrome_v60.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/mobile/Windows 7_Firefox_v54.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/mobile/Windows 7_IE_v11.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/mobile/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-template/ec-template-search/test/spec/templates-search.js
  src/systems/eu/eu-template/eu-template-search/eu-template-search.twig
Labels: tag: bug fix

#688 feat(eu-footer): apply latest design - INNO-1048
  src/systems/eu/eu-component/eu-component-footer/eu-component-footer.scss
  src/systems/eu/eu-component/eu-component-footer/eu-component-footer.twig
  src/systems/eu/eu-component/eu-component-footer/test/spec/screenshots/reference/footers/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-footer/test/spec/screenshots/reference/footers/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-footer/test/spec/screenshots/reference/footers/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-footer/test/spec/screenshots/reference/footers/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/simple/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/simple/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/simple/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/simple/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/with-menu/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/with-menu/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/with-menu/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/with-menu/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/macOS 10.12_Safari_v11.png
Labels: tag: enhancement

#695 fix(accordion): add class to paragraph - INNO-1080
  src/generic/generic-component-accordion/data/demo.js
  src/systems/ec/ec-component/ec-component-accordion/test/spec/screenshots/reference/accordions/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-accordion/test/spec/screenshots/reference/accordions/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-accordion/test/spec/screenshots/reference/accordions/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-accordion/test/spec/screenshots/reference/accordions/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-accordion/test/spec/screenshots/reference/accordions/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-accordion/test/spec/screenshots/reference/accordions/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-accordion/test/spec/screenshots/reference/accordions/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-accordion/test/spec/screenshots/reference/accordions/macOS 10.12_Safari_v11.png
Labels: tag: bug fix
