Repository ec-europa/europa-component-library, pull requests merged in 2018-04, with the labels that each got.

#619 fix(file): fix file component - INNO-910
  src/generic/generic-component-file/.npmignore
  src/generic/generic-component-file/generic-component-file.config.js
  src/generic/generic-component-file/generic-component-file.scss
  src/generic/generic-component-file/generic-component-file.twig
  src/systems/ec/ec-component/ec-component-file/ec-component-file.config.js
  src/systems/ec/ec-component/ec-component-file/ec-component-file.scss
  src/systems/ec/ec-component/ec-component-file/ec-component-file.twig
  src/systems/ec/ec-component/ec-component-file/package.json
  src/systems/ec/ec-component/ec-component-file/test/spec/screenshots/reference/files/default/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-file/test/spec/screenshots/reference/files/default/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-file/test/spec/screenshots/reference/files/default/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-file/test/spec/screenshots/reference/files/default/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-file/test/spec/screenshots/reference/files/images/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-file/test/spec/screenshots/reference/files/images/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-file/test/spec/screenshots/reference/files/images/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-file/test/spec/screenshots/reference/files/images/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-file/test/spec/screenshots/reference/files/links/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-file/test/spec/screenshots/reference/files/links/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-file/test/spec/screenshots/reference/files/links/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-file/test/spec/screenshots/reference/files/links/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-file/test/spec/screenshots/reference/files/translations/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-file/test/spec/screenshots/reference/files/translations/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-file/test/spec/screenshots/reference/files/translations/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-file/test/spec/screenshots/reference/files/translations/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-file/eu-component-file.config.js
  src/systems/eu/eu-component/eu-component-file/eu-component-file.scss
  src/systems/eu/eu-component/eu-component-file/eu-component-file.twig
  src/systems/eu/eu-component/eu-component-file/package.json
  src/systems/eu/eu-component/eu-component-file/test/spec/screenshots/reference/files/default/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-file/test/spec/screenshots/reference/files/default/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-file/test/spec/screenshots/reference/files/default/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-file/test/spec/screenshots/reference/files/default/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-file/test/spec/screenshots/reference/files/images/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-file/test/spec/screenshots/reference/files/images/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-file/test/spec/screenshots/reference/files/images/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-file/test/spec/screenshots/reference/files/images/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-file/test/spec/screenshots/reference/files/links/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-file/test/spec/screenshots/reference/files/links/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-file/test/spec/screenshots/reference/files/links/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-file/test/spec/screenshots/reference/files/links/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-file/test/spec/screenshots/reference/files/translations/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-file/test/spec/screenshots/reference/files/translations/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-file/test/spec/screenshots/reference/files/translations/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-file/test/spec/screenshots/reference/files/translations/macOS 10.12_Safari_v11.png
Labels: process: review needed, tag: bug fix

#628 chore(package): build presets independently - INNO-697
  netlify.toml
  package.json
  scripts/deploy.sh
  scripts/dist-presets.sh
  scripts/dist-styleguides.sh
  scripts/styleguide.sh
  src/systems/ec/_partials/_preview-breadcrumbs.twig
  src/systems/ec/_partials/_preview-center-transparent.twig
  src/systems/ec/_partials/_preview-datepickers.twig
  src/systems/ec/_partials/_preview-forms-file-uploads.twig
  src/systems/ec/_partials/_preview-full-page.twig
  src/systems/ec/_partials/_preview-inpage-navigation.twig
  src/systems/ec/_partials/_preview-palette.twig
  src/systems/ec/_partials/_preview-splash-page.twig
  src/systems/ec/_partials/_preview-tables.twig
  src/systems/ec/_partials/_preview-website.twig
  src/systems/ec/_partials/_preview.twig
  src/systems/ec/ec-preset/ec-preset-corporate/ec-preset-corporate.scss
  src/systems/ec/ec-preset/ec-preset-corporate/ecl-builder.config.js
  src/systems/ec/ec-preset/ec-preset-corporate/package.json
  src/systems/ec/ec-preset/ec-preset-full/ecl-builder.config.js
  src/systems/ec/ec-preset/ec-preset-full/package.json
  src/systems/eu/_partials/_preview-breadcrumbs.twig
  src/systems/eu/_partials/_preview-center-transparent.twig
  src/systems/eu/_partials/_preview-datepickers.twig
  src/systems/eu/_partials/_preview-forms-file-uploads.twig
  src/systems/eu/_partials/_preview-full-page.twig
  src/systems/eu/_partials/_preview-inpage-navigation.twig
  src/systems/eu/_partials/_preview-palette.twig
  src/systems/eu/_partials/_preview-splash-page.twig
  src/systems/eu/_partials/_preview-tables.twig
  src/systems/eu/_partials/_preview-website.twig
  src/systems/eu/_partials/_preview.twig
  src/systems/eu/eu-preset/eu-preset-corporate/ecl-builder.config.js
  src/systems/eu/eu-preset/eu-preset-corporate/eu-preset-corporate.scss
  src/systems/eu/eu-preset/eu-preset-corporate/package.json
  src/systems/eu/eu-preset/eu-preset-full/ecl-builder.config.js
  src/systems/eu/eu-preset/eu-preset-full/package.json
  test/functional/wdio.conf.js
  tools/ec-styleguide/.gitignore
  tools/ec-styleguide/fractal.js
  tools/ec-styleguide/package.json
  tools/ec-styleguide/static/.gitkeep
  tools/eu-styleguide/.gitignore
  tools/eu-styleguide/fractal.js
  tools/eu-styleguide/package.json
Labels: process: review needed, tag: enhancement

#626 chore(scss): compile SCSS independently - no issue
  .drone.yml
  examples/webpack3/package.json
  examples/webpack4/package.json
  package.json
  src/generic/generic-base/mixins/_import-once.scss
  src/generic/generic-component-file/generic-component-file.scss
  src/systems/eu/eu-base/mixins/index.scss
  src/systems/eu/eu-component/eu-component-button/eu-component-button.scss
  src/systems/eu/eu-component/eu-component-file/eu-component-file.scss
  src/systems/eu/eu-component/eu-component-file/package.json
  src/systems/eu/eu-preset/eu-preset-full/eu-preset-full.scss
  yarn.lock
Labels: POC, process: review needed, tag: internal

#629 fix(reset): remove typography rules from reset - INNO-949
  src/generic/generic-base/reset.scss
  src/generic/generic-style-typography/README.md
  src/generic/generic-style-typography/_mixins.scss
  src/generic/generic-style-typography/generic-style-typography.scss
  src/generic/generic-style-typography/package.json
  src/systems/ec/_partials/_preview-breadcrumbs.twig
  src/systems/ec/_partials/_preview-center-transparent.twig
  src/systems/ec/_partials/_preview-datepickers.twig
  src/systems/ec/_partials/_preview-forms-file-uploads.twig
  src/systems/ec/_partials/_preview-full-page.twig
  src/systems/ec/_partials/_preview-inpage-navigation.twig
  src/systems/ec/_partials/_preview-no-demo.twig
  src/systems/ec/_partials/_preview-palette.twig
  src/systems/ec/_partials/_preview-splash-page.twig
  src/systems/ec/_partials/_preview-tables.twig
  src/systems/ec/_partials/_preview-website.twig
  src/systems/ec/_partials/_preview.twig
  src/systems/ec/ec-base/reset.scss
  src/systems/ec/ec-preset/ec-preset-base/_imports.scss
  src/systems/ec/ec-preset/ec-preset-base/package.json
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography/README.md
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography/ec-style-typography.scss
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography/package.json
  src/systems/eu/_partials/_preview-breadcrumbs.twig
  src/systems/eu/_partials/_preview-center-transparent.twig
  src/systems/eu/_partials/_preview-datepickers.twig
  src/systems/eu/_partials/_preview-forms-file-uploads.twig
  src/systems/eu/_partials/_preview-full-page.twig
  src/systems/eu/_partials/_preview-inpage-navigation.twig
  src/systems/eu/_partials/_preview-no-demo.twig
  src/systems/eu/_partials/_preview-palette.twig
  src/systems/eu/_partials/_preview-splash-page.twig
  src/systems/eu/_partials/_preview-tables.twig
  src/systems/eu/_partials/_preview-website.twig
  src/systems/eu/_partials/_preview.twig
  src/systems/eu/eu-base/reset.scss
  src/systems/eu/eu-preset/eu-preset-base/_imports.scss
  src/systems/eu/eu-preset/eu-preset-base/package.json
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography/README.md
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography/eu-style-typography.scss
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography/package.json
  tools/fractal-theme/views/layouts/skeleton.nunj
  website/index.html
Labels: process: review needed, tag: enhancement

#632 fix(dialog): fix z-index issue - INNO-984
  src/generic/generic-component-dialog/generic-component-dialog.scss
Labels: process: review needed, tag: bug fix

#611 feat(global-navigation): add component - INNO-996
  src/systems/eu/eu-component/eu-component-global-navigation/.npmignore
  src/systems/eu/eu-component/eu-component-global-navigation/README.md
  src/systems/eu/eu-component/eu-component-global-navigation/eu-component-global-navigation.config.js
  src/systems/eu/eu-component/eu-component-global-navigation/eu-component-global-navigation.scss
  src/systems/eu/eu-component/eu-component-global-navigation/eu-component-global-navigation.twig
  src/systems/eu/eu-component/eu-component-global-navigation/package.json
  src/systems/eu/eu-component/eu-component-global-navigation/test/spec/.eslintrc
  src/systems/eu/eu-component/eu-component-global-navigation/test/spec/global-navigation.js
  src/systems/eu/eu-component/eu-component-global-navigation/test/spec/screenshots/reference/global-navigation/dark/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-global-navigation/test/spec/screenshots/reference/global-navigation/dark/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-global-navigation/test/spec/screenshots/reference/global-navigation/dark/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-global-navigation/test/spec/screenshots/reference/global-navigation/dark/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-global-navigation/test/spec/screenshots/reference/global-navigation/light/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-global-navigation/test/spec/screenshots/reference/global-navigation/light/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-global-navigation/test/spec/screenshots/reference/global-navigation/light/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-global-navigation/test/spec/screenshots/reference/global-navigation/light/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-preset/eu-preset-full/_imports.scss
Labels: dt: review needed, tag: new feature

#636 feat(preset): add webtools preset - INNO-1016
  scripts/dist-presets.sh
  src/systems/ec/ec-preset/ec-preset-webtools/_imports.scss
  src/systems/ec/ec-preset/ec-preset-webtools/ec-preset-webtools.js
  src/systems/ec/ec-preset/ec-preset-webtools/ec-preset-webtools.scss
  src/systems/ec/ec-preset/ec-preset-webtools/ecl-builder.config.js
  src/systems/ec/ec-preset/ec-preset-webtools/package.json
  src/systems/eu/eu-component/eu-component-global-navigation/images/logo.svg
  src/systems/eu/eu-preset/eu-preset-full/ecl-builder.config.js
  src/systems/eu/eu-preset/eu-preset-webtools/_imports.scss
  src/systems/eu/eu-preset/eu-preset-webtools/ecl-builder.config.js
  src/systems/eu/eu-preset/eu-preset-webtools/eu-preset-webtools.js
  src/systems/eu/eu-preset/eu-preset-webtools/eu-preset-webtools.scss
  src/systems/eu/eu-preset/eu-preset-webtools/package.json
Labels: tag: new feature

#635 fix(inpage-nav): fix inpage-nav - INNO-1011
  src/generic/generic-component-file/generic-component-file.scss
  src/generic/generic-component-inpage-navigation/README.md
  src/generic/generic-component-inpage-navigation/generic-component-inpage-navigation.js
  src/generic/generic-component-inpage-navigation/generic-component-inpage-navigation.scss
  src/generic/generic-component-inpage-navigation/generic-component-inpage-navigation.twig
  src/generic/generic-component-link/generic-component-link.scss
  src/generic/generic-component-navigation-menu/generic-component-navigation-menu.js
  src/systems/ec/_partials/_preview-inpage-navigation.twig
  src/systems/ec/ec-base/mixins/index.scss
  src/systems/ec/ec-component/ec-component-accordion/ec-component-accordion.config.js
  src/systems/ec/ec-component/ec-component-file/ec-component-file.scss
  src/systems/ec/ec-component/ec-component-file/package.json
  src/systems/ec/ec-component/ec-component-link/_editor-links.scss
  src/systems/ec/ec-component/ec-component-link/ec-component-link.scss
  src/systems/ec/ec-component/ec-component-link/package.json
  src/systems/ec/ec-component/ec-component-navigation/ec-component-inpage-navigation/README.md
  src/systems/ec/ec-component/ec-component-navigation/ec-component-inpage-navigation/ec-component-inpage-navigation.config.js
  src/systems/ec/ec-component/ec-component-navigation/ec-component-inpage-navigation/ec-component-inpage-navigation.scss
  src/systems/ec/ec-component/ec-component-navigation/ec-component-inpage-navigation/package.json
  src/systems/ec/ec-component/ec-component-navigation/ec-component-inpage-navigation/test/spec/screenshots/reference/ecl-inpage-navigation/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-navigation/ec-component-inpage-navigation/test/spec/screenshots/reference/ecl-inpage-navigation/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-navigation/ec-component-inpage-navigation/test/spec/screenshots/reference/ecl-inpage-navigation/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-navigation/ec-component-inpage-navigation/test/spec/screenshots/reference/ecl-inpage-navigation/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-preset/ec-preset-full/package.json
  src/systems/ec/ec-style/ec-style-icon/ec-style-icon.scss
  src/systems/ec/ec-style/ec-style-icon/package.json
  src/systems/eu/_partials/_preview-inpage-navigation.twig
  src/systems/eu/eu-component/eu-component-accordion/eu-component-accordion.config.js
  src/systems/eu/eu-component/eu-component-file/eu-component-file.scss
  src/systems/eu/eu-component/eu-component-link/_editor-links.scss
  src/systems/eu/eu-component/eu-component-link/eu-component-link.scss
  src/systems/eu/eu-component/eu-component-link/package.json
  src/systems/eu/eu-component/eu-component-navigation/eu-component-inpage-navigation/README.md
  src/systems/eu/eu-component/eu-component-navigation/eu-component-inpage-navigation/eu-component-inpage-navigation.config.js
  src/systems/eu/eu-component/eu-component-navigation/eu-component-inpage-navigation/eu-component-inpage-navigation.scss
  src/systems/eu/eu-component/eu-component-navigation/eu-component-inpage-navigation/package.json
  src/systems/eu/eu-component/eu-component-navigation/eu-component-inpage-navigation/test/spec/screenshots/reference/ecl-inpage-navigation/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-navigation/eu-component-inpage-navigation/test/spec/screenshots/reference/ecl-inpage-navigation/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-navigation/eu-component-inpage-navigation/test/spec/screenshots/reference/ecl-inpage-navigation/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-navigation/eu-component-inpage-navigation/test/spec/screenshots/reference/ecl-inpage-navigation/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-preset/eu-preset-full/package.json
  src/systems/eu/eu-style/eu-style-icon/eu-style-icon.scss
  src/systems/eu/eu-style/eu-style-icon/package.json
Labels: dt: review needed, process: review needed, tag: bug fix

#638 fix(preset): fix dependencies
  src/systems/ec/ec-preset/ec-preset-base/ec-preset-base.scss
  src/systems/ec/ec-preset/ec-preset-base/package.json
  src/systems/ec/ec-preset/ec-preset-corporate/ec-preset-corporate.scss
  src/systems/ec/ec-preset/ec-preset-corporate/package.json
  src/systems/ec/ec-preset/ec-preset-full/ec-preset-full.scss
  src/systems/ec/ec-preset/ec-preset-full/package.json
  src/systems/eu/eu-preset/eu-preset-base/eu-preset-base.scss
  src/systems/eu/eu-preset/eu-preset-base/package.json
  src/systems/eu/eu-preset/eu-preset-corporate/eu-preset-corporate.scss
  src/systems/eu/eu-preset/eu-preset-corporate/package.json
  src/systems/eu/eu-preset/eu-preset-full/package.json
  src/systems/eu/eu-preset/eu-preset-webtools/package.json
Labels: tag: bug fix

#637 feat(focus): add focus styles on links - INNO-1017
  src/generic/generic-component-link/_mixins.scss
  src/systems/ec/ec-component/ec-component-gallery/ec-component-gallery-dialog/test/spec/screenshots/reference/desktop/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-gallery/ec-component-gallery-dialog/test/spec/screenshots/reference/desktop/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-gallery/ec-component-gallery-dialog/test/spec/screenshots/reference/desktop/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-gallery/ec-component-gallery-dialog/test/spec/screenshots/reference/desktop/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-gallery/ec-component-gallery-dialog/test/spec/screenshots/reference/mobile/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-gallery/ec-component-gallery-dialog/test/spec/screenshots/reference/mobile/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-gallery/ec-component-gallery-dialog/test/spec/screenshots/reference/mobile/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-gallery/ec-component-gallery-dialog/test/spec/screenshots/reference/mobile/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-gallery/ec-component-gallery-dialog/test/spec/screenshots/reference/tablet/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-gallery/ec-component-gallery-dialog/test/spec/screenshots/reference/tablet/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-gallery/ec-component-gallery-dialog/test/spec/screenshots/reference/tablet/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-gallery/ec-component-gallery-dialog/test/spec/screenshots/reference/tablet/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-template/ec-template-listing/test/spec/screenshots/reference/templates-listings/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-gallery/eu-component-gallery-dialog/test/spec/screenshots/reference/desktop/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-gallery/eu-component-gallery-dialog/test/spec/screenshots/reference/desktop/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-gallery/eu-component-gallery-dialog/test/spec/screenshots/reference/desktop/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-gallery/eu-component-gallery-dialog/test/spec/screenshots/reference/desktop/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-gallery/eu-component-gallery-dialog/test/spec/screenshots/reference/mobile/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-gallery/eu-component-gallery-dialog/test/spec/screenshots/reference/mobile/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-gallery/eu-component-gallery-dialog/test/spec/screenshots/reference/mobile/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-gallery/eu-component-gallery-dialog/test/spec/screenshots/reference/mobile/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-gallery/eu-component-gallery-dialog/test/spec/screenshots/reference/tablet/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-gallery/eu-component-gallery-dialog/test/spec/screenshots/reference/tablet/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-gallery/eu-component-gallery-dialog/test/spec/screenshots/reference/tablet/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-gallery/eu-component-gallery-dialog/test/spec/screenshots/reference/tablet/macOS 10.12_Safari_v11.png
  test/functional/wdio.conf.js
Labels: process: review needed, tag: enhancement

#640 fix(comment-and-file): fix small glitches in components - no issue
  src/generic/generic-component-comment/generic-component-comment.scss
  src/generic/generic-component-file/generic-component-file.scss
  src/systems/ec/ec-component/ec-component-comment/test/spec/screenshots/reference/comments/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-comment/test/spec/screenshots/reference/comments/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-comment/test/spec/screenshots/reference/comments/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-comment/test/spec/screenshots/reference/comments/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-comment/test/spec/screenshots/reference/comments/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-comment/test/spec/screenshots/reference/comments/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-comment/test/spec/screenshots/reference/comments/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-comment/test/spec/screenshots/reference/comments/macOS 10.12_Safari_v11.png
Labels: process: review needed, tag: bug fix

#641 feat(banner): add banner to CSS and JS files - INNO-950
  examples/webpack3/package.json
  examples/webpack4/package.json
  lerna.json
  package.json
  src/generic/generic-component-inpage-navigation/package.json
  src/generic/generic-component-side-navigation/package.json
  src/systems/ec/ec-component/ec-component-navigation/ec-component-inpage-navigation/package.json
  src/systems/ec/ec-component/ec-component-navigation/ec-component-side-navigation/package.json
  src/systems/ec/ec-preset/ec-preset-base/ecl-builder.config.js
  src/systems/ec/ec-preset/ec-preset-base/package.json
  src/systems/ec/ec-preset/ec-preset-corporate/ecl-builder.config.js
  src/systems/ec/ec-preset/ec-preset-corporate/package.json
  src/systems/ec/ec-preset/ec-preset-full/ecl-builder.config.js
  src/systems/ec/ec-preset/ec-preset-full/package.json
  src/systems/ec/ec-preset/ec-preset-website/ecl-builder.config.js
  src/systems/ec/ec-preset/ec-preset-website/package.json
  src/systems/ec/ec-preset/ec-preset-webtools/ecl-builder.config.js
  src/systems/ec/ec-preset/ec-preset-webtools/package.json
  src/systems/eu/eu-component/eu-component-navigation/eu-component-inpage-navigation/package.json
  src/systems/eu/eu-component/eu-component-navigation/eu-component-side-navigation/package.json
  src/systems/eu/eu-preset/eu-preset-base/ecl-builder.config.js
  src/systems/eu/eu-preset/eu-preset-base/package.json
  src/systems/eu/eu-preset/eu-preset-corporate/ecl-builder.config.js
  src/systems/eu/eu-preset/eu-preset-corporate/package.json
  src/systems/eu/eu-preset/eu-preset-full/ecl-builder.config.js
  src/systems/eu/eu-preset/eu-preset-full/package.json
  src/systems/eu/eu-preset/eu-preset-website/ecl-builder.config.js
  src/systems/eu/eu-preset/eu-preset-website/package.json
  src/systems/eu/eu-preset/eu-preset-webtools/ecl-builder.config.js
  src/systems/eu/eu-preset/eu-preset-webtools/package.json
  tools/fractal-theme/package.json
  yarn.lock
Labels: process: review needed, tag: new feature

#642 docs(presets): add documentation about presets - INNO-809
  README.md
  src/systems/ec/ec-preset/ec-preset-base/README.md
  src/systems/ec/ec-preset/ec-preset-corporate/README.md
  src/systems/ec/ec-preset/ec-preset-full/README.md
  src/systems/ec/ec-preset/ec-preset-website/README.md
  src/systems/ec/ec-preset/ec-preset-webtools/README.md
  src/systems/eu/eu-preset/eu-preset-base/README.md
  src/systems/eu/eu-preset/eu-preset-corporate/README.md
  src/systems/eu/eu-preset/eu-preset-full/README.md
  src/systems/eu/eu-preset/eu-preset-website/README.md
  src/systems/eu/eu-preset/eu-preset-webtools/README.md
Labels: tag: documentation

#630 docs(components): add documentation - INNO-974
  docs/05-systems.md
  docs/conventions/component.md
  docs/conventions/twig.md
  tools/fractal-theme/assets/scss/components/index.scss
Labels: tag: documentation

#644 refactor(sass): improve all components (S01E01) - INNO-1020
  src/generic/generic-component-accordion/generic-component-accordion.scss
  src/generic/generic-component-banner/generic-component-banner.scss
  src/generic/generic-component-blockquote/generic-component-blockquote--editor.scss
  src/generic/generic-component-blockquote/generic-component-blockquote.scss
  src/generic/generic-component-breadcrumb/generic-component-breadcrumb.scss
  src/generic/generic-component-breadcrumb/generic-component-breadcrumb.twig
  src/systems/ec/ec-component/ec-component-accordion/ec-component-accordion.scss
  src/systems/ec/ec-component/ec-component-banner/ec-component-banner.scss
  src/systems/ec/ec-component/ec-component-blockquote/_editor-blockquotes.scss
  src/systems/ec/ec-component/ec-component-blockquote/ec-component-blockquote--editor.scss
  src/systems/ec/ec-component/ec-component-blockquote/ec-component-blockquote.scss
  src/systems/ec/ec-component/ec-component-breadcrumb/ec-component-breadcrumb.scss
  src/systems/ec/ec-component/ec-component-breadcrumb/ec-component-breadcrumb.twig
  src/systems/ec/ec-component/ec-component-breadcrumb/test/spec/breadcrumbs.js
  src/systems/ec/ec-component/ec-component-breadcrumb/test/spec/screenshots/reference/breadcrumb/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-breadcrumb/test/spec/screenshots/reference/breadcrumb/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-breadcrumb/test/spec/screenshots/reference/breadcrumb/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-breadcrumb/test/spec/screenshots/reference/breadcrumb/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-preset/ec-preset-full/_imports.scss
  src/systems/eu/eu-component/eu-component-accordion/eu-component-accordion.scss
  src/systems/eu/eu-component/eu-component-banner/eu-component-banner.scss
  src/systems/eu/eu-component/eu-component-blockquote/_editor-blockquotes.scss
  src/systems/eu/eu-component/eu-component-blockquote/eu-component-blockquote--editor.scss
  src/systems/eu/eu-component/eu-component-blockquote/eu-component-blockquote.scss
  src/systems/eu/eu-component/eu-component-breadcrumb/eu-component-breadcrumb.scss
  src/systems/eu/eu-component/eu-component-breadcrumb/eu-component-breadcrumb.twig
  src/systems/eu/eu-component/eu-component-breadcrumb/test/spec/breadcrumbs.js
  src/systems/eu/eu-component/eu-component-breadcrumb/test/spec/screenshots/reference/breadcrumb/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-breadcrumb/test/spec/screenshots/reference/breadcrumb/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-breadcrumb/test/spec/screenshots/reference/breadcrumb/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-breadcrumb/test/spec/screenshots/reference/breadcrumb/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-preset/eu-preset-full/_imports.scss
  tools/ec-styleguide/theme-overrides/partials/header_breadcrumb.nunj
  tools/eu-styleguide/theme-overrides/partials/header_breadcrumb.nunj
  tools/fractal-theme/views/partials/header.nunj
  tools/fractal-theme/views/partials/header_breadcrumb.nunj
  website/index.html
Labels: process: review needed, tag: bug fix

#646 refactor(sass): improve all components (S01E03) - INNO-1020
  src/generic/generic-component-datepicker/generic-component-datepicker.scss
  src/generic/generic-component-datepicker/generic-component-datepicker.twig
  src/generic/generic-component-dialog/generic-component-dialog.scss
  src/generic/generic-component-dropdown/generic-component-dropdown.scss
  src/generic/generic-component-expandable/generic-component-expandable.scss
  src/generic/generic-component-featured-item/generic-component-featured-item.scss
  src/systems/ec/ec-component/ec-component-datepicker/ec-component-datepicker.scss
  src/systems/ec/ec-component/ec-component-datepicker/test/spec/datepickers.js
  src/systems/ec/ec-component/ec-component-datepicker/test/spec/screenshots/reference/datepicker/default/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-datepicker/test/spec/screenshots/reference/datepicker/default/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-datepicker/test/spec/screenshots/reference/datepicker/default/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-datepicker/test/spec/screenshots/reference/datepicker/default/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-datepicker/test/spec/screenshots/reference/datepicker/open/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-dialog/ec-component-dialog.scss
  src/systems/ec/ec-component/ec-component-dropdown/ec-component-dropdown.scss
  src/systems/ec/ec-component/ec-component-expandable/ec-component-expandable.scss
  src/systems/ec/ec-component/ec-component-featured-item/ec-component-featured-item.scss
  src/systems/eu/eu-component/eu-component-datepicker/eu-component-datepicker.scss
  src/systems/eu/eu-component/eu-component-datepicker/test/spec/datepickers.js
  src/systems/eu/eu-component/eu-component-datepicker/test/spec/screenshots/reference/datepicker/default/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-datepicker/test/spec/screenshots/reference/datepicker/default/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-datepicker/test/spec/screenshots/reference/datepicker/default/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-datepicker/test/spec/screenshots/reference/datepicker/default/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-datepicker/test/spec/screenshots/reference/datepicker/open/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-dialog/eu-component-dialog.scss
  src/systems/eu/eu-component/eu-component-dropdown/eu-component-dropdown.scss
  src/systems/eu/eu-component/eu-component-expandable/eu-component-expandable.scss
  src/systems/eu/eu-component/eu-component-featured-item/eu-component-featured-item.scss
Labels: process: review needed, tag: enhancement

#650 fix(twig): normalize twig template, pt4 - INNO-1019
  src/generic/generic-component-form-select/generic-component-form-select.twig
  src/generic/generic-component-form-text-input/generic-component-form-text-input.twig
  src/generic/generic-component-form-textarea/generic-component-form-textarea.twig
  src/systems/ec/ec-component/ec-component-form/ec-component-form-select/ec-component-form-select.twig
  src/systems/ec/ec-component/ec-component-form/ec-component-form-text-input/ec-component-form-text-input.twig
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/ec-component-form-textarea.config.js
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/ec-component-form-textarea.twig
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/test/spec/screenshots/reference/forms/textarea/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/test/spec/screenshots/reference/forms/textarea/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/test/spec/screenshots/reference/forms/textarea/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/test/spec/screenshots/reference/forms/textarea/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/test/spec/screenshots/reference/forms/textareas/default/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/test/spec/screenshots/reference/forms/textareas/default/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/test/spec/screenshots/reference/forms/textareas/default/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/test/spec/screenshots/reference/forms/textareas/default/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/test/spec/screenshots/reference/forms/textareas/has-error/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/test/spec/screenshots/reference/forms/textareas/has-error/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/test/spec/screenshots/reference/forms/textareas/has-error/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/test/spec/screenshots/reference/forms/textareas/has-error/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/test/spec/screenshots/reference/forms/textareas/is-disabled/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/test/spec/screenshots/reference/forms/textareas/is-disabled/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/test/spec/screenshots/reference/forms/textareas/is-disabled/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/test/spec/screenshots/reference/forms/textareas/is-disabled/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/test/spec/textareas.js
  src/systems/ec/ec-template/ec-template-form/ec-template-form.twig
  src/systems/eu/eu-component/eu-component-form/eu-component-form-select/eu-component-form-select.twig
  src/systems/eu/eu-component/eu-component-form/eu-component-form-text-input/eu-component-form-text-input.twig
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/eu-component-form-textarea.config.js
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/eu-component-form-textarea.twig
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/test/spec/screenshots/reference/forms/textarea/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/test/spec/screenshots/reference/forms/textarea/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/test/spec/screenshots/reference/forms/textarea/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/test/spec/screenshots/reference/forms/textarea/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/test/spec/screenshots/reference/forms/textareas/default/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/test/spec/screenshots/reference/forms/textareas/default/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/test/spec/screenshots/reference/forms/textareas/default/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/test/spec/screenshots/reference/forms/textareas/default/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/test/spec/screenshots/reference/forms/textareas/has-error/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/test/spec/screenshots/reference/forms/textareas/has-error/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/test/spec/screenshots/reference/forms/textareas/has-error/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/test/spec/screenshots/reference/forms/textareas/has-error/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/test/spec/screenshots/reference/forms/textareas/is-disabled/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/test/spec/screenshots/reference/forms/textareas/is-disabled/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/test/spec/screenshots/reference/forms/textareas/is-disabled/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/test/spec/screenshots/reference/forms/textareas/is-disabled/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/test/spec/textareas.js
  src/systems/eu/eu-template/eu-template-form/eu-template-form.twig
Labels: process: review needed, tag: bug fix

#651 refactor(sass): improve all components (S01E05) - INNO-1020
  src/generic/generic-component-form-file-upload/generic-component-form-file-upload.scss
  src/generic/generic-component-form-form-group/generic-component-form-form-group.scss
  src/generic/generic-component-form-form/generic-component-form-form.scss
  src/generic/generic-component-form-help-block/generic-component-form-help-block.scss
  src/generic/generic-component-form-label/generic-component-form-label.scss
  src/generic/generic-component-form-legend/generic-component-form-legend.scss
  src/generic/generic-component-form-radio-group/generic-component-form-radio-group.scss
  src/generic/generic-component-form-radio/generic-component-form-radio.scss
  src/generic/generic-component-form-radio/package.json
  src/systems/ec/ec-component/ec-component-form/ec-component-form-file-upload/ec-component-form-file-upload.scss
  src/systems/ec/ec-component/ec-component-form/ec-component-form-form-group/ec-component-form-form-group.scss
  src/systems/ec/ec-component/ec-component-form/ec-component-form-form/ec-component-form-form.scss
  src/systems/ec/ec-component/ec-component-form/ec-component-form-help-block/ec-component-form-help-block.scss
  src/systems/ec/ec-component/ec-component-form/ec-component-form-label/ec-component-form-label.scss
  src/systems/ec/ec-component/ec-component-form/ec-component-form-legend/ec-component-form-legend.scss
  src/systems/ec/ec-component/ec-component-form/ec-component-form-radio-group/ec-component-form-radio-group.scss
  src/systems/ec/ec-component/ec-component-form/ec-component-form-radio/ec-component-form-radio.scss
  src/systems/ec/ec-component/ec-component-form/ec-component-form-radio/package.json
  src/systems/eu/eu-component/eu-component-form/eu-component-form-file-upload/eu-component-form-file-upload.scss
  src/systems/eu/eu-component/eu-component-form/eu-component-form-form-group/eu-component-form-form-group.scss
  src/systems/eu/eu-component/eu-component-form/eu-component-form-form/eu-component-form-form.scss
  src/systems/eu/eu-component/eu-component-form/eu-component-form-help-block/eu-component-form-help-block.scss
  src/systems/eu/eu-component/eu-component-form/eu-component-form-label/eu-component-form-label.scss
  src/systems/eu/eu-component/eu-component-form/eu-component-form-legend/eu-component-form-legend.scss
  src/systems/eu/eu-component/eu-component-form/eu-component-form-radio-group/eu-component-form-radio-group.scss
  src/systems/eu/eu-component/eu-component-form/eu-component-form-radio/eu-component-form-radio.scss
  src/systems/eu/eu-component/eu-component-form/eu-component-form-radio/package.json
Labels: process: review needed, tag: enhancement

#654 refactor(sass): improve all components (S01E07) - INNO-1020
  src/generic/generic-component-language-list/generic-component-language-list.scss
  src/generic/generic-component-link-block/generic-component-link-block.scss
  src/generic/generic-component-link/generic-component-link.scss
  src/generic/generic-component-list-item/generic-component-list-item.scss
  src/generic/generic-component-listing/generic-component-listing.scss
  src/generic/generic-component-logo/generic-component-logo.scss
  src/generic/generic-component-message/generic-component-message.scss
  src/systems/ec/ec-component/ec-component-language-list/ec-component-language-list.scss
  src/systems/ec/ec-component/ec-component-link-block/ec-component-link-block.scss
  src/systems/ec/ec-component/ec-component-link/ec-component-link.scss
  src/systems/ec/ec-component/ec-component-list-item/ec-component-list-item.scss
  src/systems/ec/ec-component/ec-component-listing/ec-component-listing.scss
  src/systems/ec/ec-component/ec-component-logo/ec-component-logo.scss
  src/systems/eu/eu-component/eu-component-language-list/eu-component-language-list.scss
  src/systems/eu/eu-component/eu-component-link-block/eu-component-link-block.scss
  src/systems/eu/eu-component/eu-component-link/eu-component-link.scss
  src/systems/eu/eu-component/eu-component-list-item/eu-component-list-item.scss
  src/systems/eu/eu-component/eu-component-listing/eu-component-listing.scss
  src/systems/eu/eu-component/eu-component-logo/eu-component-logo.scss
Labels: process: review needed, tag: enhancement

#652 refactor(sass): improve all components (S01E06) - INNO-1020
  src/generic/generic-component-form-select/___selects.scss
  src/generic/generic-component-form-select/_mixins.scss
  src/generic/generic-component-form-select/generic-component-form-select.scss
  src/generic/generic-component-form-text-input/generic-component-form-text-input.scss
  src/generic/generic-component-form-textarea/generic-component-form-textarea.scss
  src/generic/generic-component-inpage-navigation/generic-component-inpage-navigation.scss
  src/generic/generic-component-label/generic-component-label.scss
  src/generic/generic-component-lang-select-page/generic-component-lang-select-page.scss
  src/generic/generic-component-lang-select-site/generic-component-lang-select-site.scss
  src/systems/ec/ec-component/ec-component-form/ec-component-form-select/_mixins.scss
  src/systems/ec/ec-component/ec-component-form/ec-component-form-select/ec-component-form-select.scss
  src/systems/ec/ec-component/ec-component-form/ec-component-form-text-input/ec-component-form-text-input.scss
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/ec-component-form-textarea.scss
  src/systems/ec/ec-component/ec-component-label/ec-component-label.scss
  src/systems/ec/ec-component/ec-component-lang-select-page/ec-component-lang-select-page.scss
  src/systems/ec/ec-component/ec-component-lang-select-site/ec-component-lang-select-site.scss
  src/systems/ec/ec-component/ec-component-navigation/ec-component-inpage-navigation/ec-component-inpage-navigation.scss
  src/systems/eu/eu-component/eu-component-form/eu-component-form-select/_mixins.scss
  src/systems/eu/eu-component/eu-component-form/eu-component-form-select/eu-component-form-select.scss
  src/systems/eu/eu-component/eu-component-form/eu-component-form-text-input/eu-component-form-text-input.scss
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/eu-component-form-textarea.scss
  src/systems/eu/eu-component/eu-component-label/eu-component-label.scss
  src/systems/eu/eu-component/eu-component-lang-select-page/eu-component-lang-select-page.scss
  src/systems/eu/eu-component/eu-component-lang-select-site/eu-component-lang-select-site.scss
  src/systems/eu/eu-component/eu-component-navigation/eu-component-inpage-navigation/eu-component-inpage-navigation.scss
Labels: process: review needed, tag: enhancement

#655 refactor(sass): improve all components (S01E08) - INNO-1020
  src/generic/generic-component-message/generic-component-message.scss
  src/generic/generic-component-meta/generic-component-meta.scss
  src/generic/generic-component-navigation-list/generic-component-navigation-list.scss
  src/generic/generic-component-navigation-menu/generic-component-navigation-menu.scss
  src/generic/generic-component-page-header/generic-component-page-header.scss
  src/generic/generic-component-pager/generic-component-pager.scss
  src/generic/generic-component-pager/package.json
  src/systems/ec/ec-component/ec-component-message/ec-component-message.scss
  src/systems/ec/ec-component/ec-component-meta/ec-component-meta.scss
  src/systems/ec/ec-component/ec-component-navigation/ec-component-navigation-list/ec-component-navigation-list.scss
  src/systems/ec/ec-component/ec-component-navigation/ec-component-navigation-menu/ec-component-navigation-menu.scss
  src/systems/ec/ec-component/ec-component-page-header/ec-component-page-header.scss
  src/systems/ec/ec-component/ec-component-pager/ec-component-pager.scss
  src/systems/ec/ec-component/ec-component-pager/package.json
  src/systems/eu/eu-component/eu-component-message/eu-component-message.scss
  src/systems/eu/eu-component/eu-component-meta/eu-component-meta.scss
  src/systems/eu/eu-component/eu-component-navigation/eu-component-navigation-list/eu-component-navigation-list.scss
  src/systems/eu/eu-component/eu-component-navigation/eu-component-navigation-menu/eu-component-navigation-menu.scss
  src/systems/eu/eu-component/eu-component-page-header/eu-component-page-header.scss
  src/systems/eu/eu-component/eu-component-pager/eu-component-pager.scss
  src/systems/eu/eu-component/eu-component-pager/package.json
Labels: process: review needed, tag: enhancement

#658 fix(twig): normalize twig templates, pt6 - INNO-1019
  src/generic/generic-component-label/README.md
  src/generic/generic-component-label/generic-component-label.config.js
  src/generic/generic-component-label/generic-component-label.twig
  src/generic/generic-component-lang-select-page/generic-component-lang-select-page.config.js
  src/generic/generic-component-lang-select-page/generic-component-lang-select-page.twig
  src/generic/generic-component-lang-select-site/generic-component-lang-select-site.twig
  src/generic/generic-component-language-list/generic-component-language-list.twig
  src/generic/generic-component-language-list/languages.json
  src/systems/ec/ec-component/ec-component-label/README.md
  src/systems/ec/ec-component/ec-component-label/ec-component-label.config.js
  src/systems/ec/ec-component/ec-component-label/ec-component-label.twig
  src/systems/ec/ec-component/ec-component-label/package.json
  src/systems/ec/ec-component/ec-component-lang-select-page/ec-component-lang-select-page.config.js
  src/systems/ec/ec-component/ec-component-lang-select-page/ec-component-lang-select-page.twig
  src/systems/ec/ec-component/ec-component-lang-select-page/package.json
  src/systems/ec/ec-component/ec-component-lang-select-site/ec-component-lang-select-site.twig
  src/systems/ec/ec-component/ec-component-lang-select-site/package.json
  src/systems/ec/ec-component/ec-component-language-list/ec-component-language-list.twig
  src/systems/ec/ec-component/ec-component-language-list/languages.json
  src/systems/eu/eu-component/eu-component-label/README.md
  src/systems/eu/eu-component/eu-component-label/eu-component-label.config.js
  src/systems/eu/eu-component/eu-component-label/eu-component-label.twig
  src/systems/eu/eu-component/eu-component-label/package.json
  src/systems/eu/eu-component/eu-component-lang-select-page/eu-component-lang-select-page.config.js
  src/systems/eu/eu-component/eu-component-lang-select-page/eu-component-lang-select-page.twig
  src/systems/eu/eu-component/eu-component-lang-select-page/package.json
  src/systems/eu/eu-component/eu-component-lang-select-site/eu-component-lang-select-site.twig
  src/systems/eu/eu-component/eu-component-lang-select-site/package.json
  src/systems/eu/eu-component/eu-component-language-list/eu-component-language-list.twig
  src/systems/eu/eu-component/eu-component-language-list/languages.json
Labels: process: review needed, tag: bug fix

#659 fix(twig): normalize twig templates, pt7 - INNO-1019
  src/generic/generic-component-link-block/generic-component-link-block.twig
  src/generic/generic-component-link/generic-component-link.twig
  src/generic/generic-component-list-item/generic-component-list-item.twig
  src/generic/generic-component-listing/generic-component-listing.twig
  src/systems/ec/ec-component/ec-component-link-block/ec-component-link-block.twig
  src/systems/ec/ec-component/ec-component-link-block/package.json
  src/systems/ec/ec-component/ec-component-link/ec-component-link.twig
  src/systems/ec/ec-component/ec-component-list-item/ec-component-list-item.twig
  src/systems/ec/ec-component/ec-component-listing/ec-component-listing.twig
  src/systems/ec/ec-component/ec-component-listing/package.json
  src/systems/eu/eu-component/eu-component-link-block/eu-component-link-block.twig
  src/systems/eu/eu-component/eu-component-link-block/package.json
  src/systems/eu/eu-component/eu-component-link/eu-component-link.twig
  src/systems/eu/eu-component/eu-component-list-item/eu-component-list-item.twig
  src/systems/eu/eu-component/eu-component-listing/eu-component-listing.twig
  src/systems/eu/eu-component/eu-component-listing/package.json
Labels: process: review needed, tag: enhancement

#662 docs: update README.md - no issue
  README.md
Labels: process: review needed, tag: documentation

#660 fix(twig): normalize twig templates, pt8 - INNO-1019
  src/generic/generic-component-logo/README.md
  src/generic/generic-component-logo/generic-component-logo.config.js
  src/generic/generic-component-logo/generic-component-logo.twig
  src/generic/generic-component-message/generic-component-message.config.js
  src/generic/generic-component-message/generic-component-message.twig
  src/generic/generic-component-meta/generic-component-meta.twig
  src/generic/generic-component-site-header/generic-component-site-header.twig
  src/systems/ec/ec-component/ec-component-logo/README.md
  src/systems/ec/ec-component/ec-component-logo/ec-component-logo.config.js
  src/systems/ec/ec-component/ec-component-logo/ec-component-logo.twig
  src/systems/ec/ec-component/ec-component-logo/package.json
  src/systems/ec/ec-component/ec-component-message/ec-component-message.config.js
  src/systems/ec/ec-component/ec-component-message/ec-component-message.twig
  src/systems/ec/ec-component/ec-component-meta/ec-component-meta.twig
  src/systems/ec/ec-component/ec-component-meta/package.json
  src/systems/ec/ec-component/ec-component-site-header/ec-component-site-header.twig
  src/systems/eu/eu-component/eu-component-logo/README.md
  src/systems/eu/eu-component/eu-component-logo/eu-component-logo.config.js
  src/systems/eu/eu-component/eu-component-logo/eu-component-logo.twig
  src/systems/eu/eu-component/eu-component-logo/package.json
  src/systems/eu/eu-component/eu-component-message/eu-component-message.config.js
  src/systems/eu/eu-component/eu-component-message/eu-component-message.twig
  src/systems/eu/eu-component/eu-component-meta/eu-component-meta.twig
  src/systems/eu/eu-component/eu-component-meta/package.json
  src/systems/eu/eu-component/eu-component-site-header/eu-component-site-header.twig
Labels: process: review needed, tag: enhancement

#657 refactor(sass): improve all components (S01E09) - INNO-1020
  src/generic/generic-component-profile-topbar/generic-component-profile-topbar.scss
  src/generic/generic-component-rss-link/generic-component-rss-link.scss
  src/generic/generic-component-rss-link/generic-component-rss-link.twig
  src/generic/generic-component-search-form/generic-component-search-form.scss
  src/generic/generic-component-side-navigation/generic-component-side-navigation.scss
  src/generic/generic-component-site-header/generic-component-site-header.scss
  src/systems/ec/ec-component/ec-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-navigation/ec-component-side-navigation/ec-component-side-navigation.scss
  src/systems/ec/ec-component/ec-component-profile-topbar/ec-component-profile-topbar.scss
  src/systems/ec/ec-component/ec-component-rss-link/ec-component-rss-link.scss
  src/systems/ec/ec-component/ec-component-rss-link/ec-component-rss-link.twig
  src/systems/ec/ec-component/ec-component-rss-link/test/spec/rss-links.js
  src/systems/ec/ec-component/ec-component-search-form/ec-component-search-form.scss
  src/systems/ec/ec-component/ec-component-site-header/ec-component-site-header.scss
  src/systems/eu/eu-component/eu-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-navigation/eu-component-side-navigation/eu-component-side-navigation.scss
  src/systems/eu/eu-component/eu-component-profile-topbar/eu-component-profile-topbar.scss
  src/systems/eu/eu-component/eu-component-rss-link/eu-component-rss-link.scss
  src/systems/eu/eu-component/eu-component-rss-link/eu-component-rss-link.twig
  src/systems/eu/eu-component/eu-component-rss-link/test/spec/rss-links.js
  src/systems/eu/eu-component/eu-component-search-form/eu-component-search-form.scss
  src/systems/eu/eu-component/eu-component-site-header/eu-component-site-header.scss
Labels: process: review needed, tag: enhancement

#661 fix(twig): normalize twig templates, pt9 - INNO-1019
  src/generic/generic-component-navigation-list/generic-component-navigation-list.config.js
  src/generic/generic-component-navigation-list/generic-component-navigation-list.twig
  src/generic/generic-component-navigation-menu/generic-component-navigation-menu.twig
  src/generic/generic-component-side-navigation/generic-component-side-navigation.twig
  src/generic/generic-component-site-header/generic-component-site-header.twig
  src/systems/ec/ec-component/ec-component-navigation/ec-component-navigation-list/ec-component-navigation-list.config.js
  src/systems/ec/ec-component/ec-component-navigation/ec-component-navigation-list/ec-component-navigation-list.twig
  src/systems/ec/ec-component/ec-component-navigation/ec-component-navigation-list/package.json
  src/systems/ec/ec-component/ec-component-navigation/ec-component-navigation-menu/ec-component-navigation-menu.twig
  src/systems/ec/ec-component/ec-component-navigation/ec-component-side-navigation/ec-component-side-navigation.twig
  src/systems/ec/ec-component/ec-component-site-header/ec-component-site-header.twig
  src/systems/eu/eu-component/eu-component-navigation/eu-component-navigation-list/eu-component-navigation-list.config.js
  src/systems/eu/eu-component/eu-component-navigation/eu-component-navigation-list/eu-component-navigation-list.twig
  src/systems/eu/eu-component/eu-component-navigation/eu-component-navigation-list/package.json
  src/systems/eu/eu-component/eu-component-navigation/eu-component-navigation-menu/eu-component-navigation-menu.twig
  src/systems/eu/eu-component/eu-component-navigation/eu-component-side-navigation/eu-component-side-navigation.twig
Labels: process: review needed, tag: bug fix

#664 refactor(scss): normalize SCSS files S01E10 - INNO-1020
  src/generic/generic-component-site-switcher/generic-component-site-switcher.scss
  src/generic/generic-component-skip-link/generic-component-skip-link.scss
  src/generic/generic-component-social-icon/README.md
  src/generic/generic-component-social-icon/generic-component-social-icon.config.js
  src/generic/generic-component-social-icon/generic-component-social-icon.scss
  src/generic/generic-component-social-icon/generic-component-social-icon.twig
  src/generic/generic-component-social-media-link/generic-component-social-media-link.scss
  src/generic/generic-component-tab/generic-component-tab.scss
  src/systems/ec/ec-component/ec-component-site-switcher/ec-component-site-switcher.scss
  src/systems/ec/ec-component/ec-component-skip-link/ec-component-skip-link.scss
  src/systems/ec/ec-component/ec-component-social-icon/README.md
  src/systems/ec/ec-component/ec-component-social-icon/ec-component-social-icon.config.js
  src/systems/ec/ec-component/ec-component-social-icon/ec-component-social-icon.scss
  src/systems/ec/ec-component/ec-component-social-icon/ec-component-social-icon.twig
  src/systems/ec/ec-component/ec-component-social-icon/icons-list.scss
  src/systems/ec/ec-component/ec-component-social-media-link/ec-component-social-media-link.scss
  src/systems/ec/ec-component/ec-component-tab/ec-component-tab.scss
  src/systems/eu/eu-component/eu-component-site-switcher/eu-component-site-switcher.scss
  src/systems/eu/eu-component/eu-component-skip-link/eu-component-skip-link.scss
  src/systems/eu/eu-component/eu-component-social-icon/README.md
  src/systems/eu/eu-component/eu-component-social-icon/eu-component-social-icon.config.js
  src/systems/eu/eu-component/eu-component-social-icon/eu-component-social-icon.scss
  src/systems/eu/eu-component/eu-component-social-icon/eu-component-social-icon.twig
  src/systems/eu/eu-component/eu-component-social-icon/icons-list.scss
  src/systems/eu/eu-component/eu-component-social-media-link/eu-component-social-media-link.scss
  src/systems/eu/eu-component/eu-component-tab/eu-component-tab.scss
Labels: process: under review, tag: enhancement

#663 fix(twig): normalize twig templates, pt10 - INNO-1019
  src/generic/generic-component-page-header/generic-component-page-header.config.js
  src/generic/generic-component-page-header/generic-component-page-header.twig
  src/generic/generic-component-pager/generic-component-pager.scss
  src/generic/generic-component-pager/generic-component-pager.twig
  src/generic/generic-component-profile-topbar/generic-component-profile-topbar.twig
  src/systems/ec/ec-component/ec-component-page-header/ec-component-page-header.config.js
  src/systems/ec/ec-component/ec-component-page-header/ec-component-page-header.twig
  src/systems/ec/ec-component/ec-component-page-header/package.json
  src/systems/ec/ec-component/ec-component-pager/ec-component-pager.twig
  src/systems/ec/ec-component/ec-component-pager/package.json
  src/systems/ec/ec-component/ec-component-profile-topbar/ec-component-profile-topbar.twig
  src/systems/eu/eu-component/eu-component-page-header/eu-component-page-header.config.js
  src/systems/eu/eu-component/eu-component-page-header/eu-component-page-header.twig
  src/systems/eu/eu-component/eu-component-page-header/package.json
  src/systems/eu/eu-component/eu-component-pager/eu-component-pager.twig
  src/systems/eu/eu-component/eu-component-pager/package.json
  src/systems/eu/eu-component/eu-component-profile-topbar/eu-component-profile-topbar.twig
Labels: process: review needed, tag: bug fix

#665 fix(twig): normalize twig templates, pt11 - INNO-1019
  src/generic/generic-component-language-list/generic-component-language-list.twig
  src/generic/generic-component-rss-link/generic-component-rss-link.config.js
  src/generic/generic-component-rss-link/generic-component-rss-link.twig
  src/generic/generic-component-search-form/generic-component-search-form.twig
  src/generic/generic-component-site-header/generic-component-site-header.twig
  src/generic/generic-component-site-switcher/generic-component-site-switcher.twig
  src/systems/ec/ec-component/ec-component-language-list/ec-component-language-list.twig
  src/systems/ec/ec-component/ec-component-rss-link/ec-component-rss-link.config.js
  src/systems/ec/ec-component/ec-component-rss-link/ec-component-rss-link.twig
  src/systems/ec/ec-component/ec-component-rss-link/package.json
  src/systems/ec/ec-component/ec-component-search-form/ec-component-search-form.twig
  src/systems/ec/ec-component/ec-component-search-form/package.json
  src/systems/ec/ec-component/ec-component-site-header/ec-component-site-header.twig
  src/systems/ec/ec-component/ec-component-site-header/package.json
  src/systems/ec/ec-component/ec-component-site-switcher/ec-component-site-switcher.twig
  src/systems/ec/ec-component/ec-component-site-switcher/package.json
  src/systems/ec/ec-preset/ec-preset-website/package.json
  src/systems/ec/ec-template/ec-template-page/ec-template-page.twig
  src/systems/eu/_partials/_preview-full-page.twig
  src/systems/eu/eu-component/eu-component-language-list/eu-component-language-list.twig
  src/systems/eu/eu-component/eu-component-rss-link/eu-component-rss-link.twig
  src/systems/eu/eu-component/eu-component-rss-link/package.json
  src/systems/eu/eu-component/eu-component-search-form/eu-component-search-form.twig
  src/systems/eu/eu-component/eu-component-search-form/package.json
  src/systems/eu/eu-component/eu-component-site-header/eu-component-site-header.config.js
  src/systems/eu/eu-component/eu-component-site-header/eu-component-site-header.twig
  src/systems/eu/eu-component/eu-component-site-header/package.json
  src/systems/eu/eu-component/eu-component-site-switcher/eu-component-site-switcher.twig
  src/systems/eu/eu-component/eu-component-site-switcher/package.json
  src/systems/eu/eu-preset/eu-preset-website/package.json
  src/systems/eu/eu-template/eu-template-community/eu-template-community.config.js
  src/systems/eu/eu-template/eu-template-community/eu-template-community.twig
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-listing/eu-template-listing.config.js
  src/systems/eu/eu-template/eu-template-listing/eu-template-listing.twig
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-page/eu-template-page.twig
  src/systems/eu/eu-template/eu-template-search/eu-template-search.config.js
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/macOS 10.12_Safari_v11.png
Labels: process: review needed, tag: bug fix

#667 fix(twig): normalize twig templates, pt12 - INNO-1019
  src/generic/generic-component-rss-link/generic-component-rss-link.twig
  src/generic/generic-component-skip-link/generic-component-skip-link.twig
  src/generic/generic-component-social-icon/generic-component-social-icon.twig
  src/generic/generic-component-social-media-link/generic-component-social-media-link.config.js
  src/generic/generic-component-social-media-link/generic-component-social-media-link.twig
  src/systems/ec/ec-component/ec-component-skip-link/ec-component-skip-link.twig
  src/systems/ec/ec-component/ec-component-skip-link/package.json
  src/systems/ec/ec-component/ec-component-social-icon/ec-component-social-icon.twig
  src/systems/ec/ec-component/ec-component-social-icon/package.json
  src/systems/ec/ec-component/ec-component-social-media-link/ec-component-social-media-link.config.js
  src/systems/ec/ec-component/ec-component-social-media-link/ec-component-social-media-link.twig
  src/systems/eu/eu-component/eu-component-skip-link/eu-component-skip-link.twig
  src/systems/eu/eu-component/eu-component-skip-link/package.json
  src/systems/eu/eu-component/eu-component-social-icon/eu-component-social-icon.twig
  src/systems/eu/eu-component/eu-component-social-icon/package.json
  src/systems/eu/eu-component/eu-component-social-media-link/eu-component-social-media-link.config.js
  src/systems/eu/eu-component/eu-component-social-media-link/eu-component-social-media-link.twig
Labels: process: review needed, tag: bug fix

#669 refactor(scss): normalize SCSS files S01E12 - INNO-1020
  src/generic/generic-style-typography-heading/_editor-headings.scss
  src/generic/generic-style-typography-heading/_mixins.scss
  src/generic/generic-style-typography-heading/generic-style-typography-heading--editor.scss
  src/generic/generic-style-typography-heading/generic-style-typography-heading.scss
  src/generic/generic-style-typography-list/_editor-lists.scss
  src/generic/generic-style-typography-list/_mixins.scss
  src/generic/generic-style-typography-list/generic-style-typography-list--editor.scss
  src/generic/generic-style-typography-list/generic-style-typography-list.scss
  src/generic/generic-style-typography-paragraph/generic-style-typography-paragraph--editor.scss
  src/generic/generic-style-typography-paragraph/generic-style-typography-paragraph.scss
  src/systems/ec/ec-preset/ec-preset-full/_imports.scss
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography-heading/_editor-headings.scss
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography-heading/_headings-mixins.scss
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography-heading/ec-style-typography-heading--editor.scss
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography-heading/ec-style-typography-heading.scss
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography-list/_editor-lists.scss
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography-list/_lists-mixins.scss
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography-list/ec-style-typography-list--editor.scss
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography-list/ec-style-typography-list.scss
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography-paragraph/_editor-paragraphs.scss
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography-paragraph/_mixins.scss
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography-paragraph/ec-style-typography-paragraph--editor.scss
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography-paragraph/ec-style-typography-paragraph.scss
  src/systems/eu/eu-preset/eu-preset-full/_imports.scss
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography-heading/_editor-headings.scss
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography-heading/_headings-mixins.scss
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography-heading/eu-style-typography-heading--editor.scss
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography-heading/eu-style-typography-heading.scss
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography-list/_editor-lists.scss
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography-list/_lists-mixins.scss
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography-list/eu-style-typography-list--editor.scss
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography-list/eu-style-typography-list.scss
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography-paragraph/_editor-paragraphs.scss
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography-paragraph/_mixins.scss
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography-paragraph/eu-style-typography-paragraph--editor.scss
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography-paragraph/eu-style-typography-paragraph.scss
Labels: process: review needed, tag: enhancement

#672 fix(twig): normalize twig templates, pt13 - INNO-1019
  src/generic/generic-component-table/generic-component-table.twig
  src/generic/generic-component-tag/generic-component-tag.twig
  src/generic/generic-component-tag/package.json
  src/generic/generic-component-timeline/generic-component-timeline.twig
  src/systems/ec/ec-component/ec-component-table/ec-component-table.twig
  src/systems/ec/ec-component/ec-component-table/package.json
  src/systems/ec/ec-component/ec-component-tag/ec-component-tag.twig
  src/systems/ec/ec-component/ec-component-tag/package.json
  src/systems/ec/ec-component/ec-component-tag/test/spec/screenshots/reference/tags/facet-close/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-timeline/ec-component-timeline.twig
  src/systems/ec/ec-template/ec-template-filter/ec-template-filter.twig
  src/systems/ec/ec-template/ec-template-filter/test/spec/screenshots/reference/filters/Windows 10_Chrome_v60.png
  src/systems/ec/ec-template/ec-template-filter/test/spec/screenshots/reference/filters/Windows 7_Firefox_v54.png
  src/systems/ec/ec-template/ec-template-filter/test/spec/screenshots/reference/filters/Windows 7_IE_v11.png
  src/systems/ec/ec-template/ec-template-filter/test/spec/screenshots/reference/filters/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-template/ec-template-search/ec-template-search.twig
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/Windows 10_Chrome_v60.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/Windows 7_Firefox_v54.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/Windows 7_IE_v11.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-table/eu-component-table.twig
  src/systems/eu/eu-component/eu-component-table/package.json
  src/systems/eu/eu-component/eu-component-tag/eu-component-tag.twig
  src/systems/eu/eu-component/eu-component-tag/package.json
  src/systems/eu/eu-component/eu-component-tag/test/spec/screenshots/reference/tags/facet-close/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-timeline/eu-component-timeline.twig
  src/systems/eu/eu-template/eu-template-filter/eu-template-filter.twig
  src/systems/eu/eu-template/eu-template-filter/test/spec/screenshots/reference/filters/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-filter/test/spec/screenshots/reference/filters/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-filter/test/spec/screenshots/reference/filters/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-filter/test/spec/screenshots/reference/filters/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-search/eu-template-search.twig
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/macOS 10.12_Safari_v11.png
Labels: process: review needed, tag: bug fix

#666 refactor(config): harmonize config.js, pt.2 - INNO-1026
  src/generic/generic-component-label/data/demo--close.js
  src/generic/generic-component-label/data/demo--open.js
  src/generic/generic-component-label/data/demo--upcoming.js
  src/generic/generic-component-lang-select-site/data/demo.js
  src/generic/generic-component-link/data/demo--all.js
  src/generic/generic-component-link/data/demo--default.js
  src/generic/generic-component-link/data/demo--external.js
  src/generic/generic-component-link/data/demo--inverted.js
  src/generic/generic-component-link/data/demo--more.js
  src/generic/generic-component-link/data/demo--standalone.js
  src/generic/generic-component-list-item/data/demo--date.js
  src/generic/generic-component-list-item/data/demo--default.js
  src/generic/generic-component-list-item/data/demo--highlight.js
  src/generic/generic-component-list-item/data/demo--thumbnail.js
  src/generic/generic-component-listing/data/demo--one-column.js
  src/generic/generic-component-listing/data/demo--three-column.js
  src/generic/generic-component-listing/data/demo--two-column.js
  src/systems/ec/ec-component/ec-component-label/ec-component-label.config.js
  src/systems/ec/ec-component/ec-component-lang-select-site/ec-component-lang-select-site.config.js
  src/systems/ec/ec-component/ec-component-link/ec-component-link.config.js
  src/systems/ec/ec-component/ec-component-list-item/ec-component-list-item.config.js
  src/systems/ec/ec-component/ec-component-list-item/package.json
  src/systems/ec/ec-component/ec-component-listing/ec-component-listing.config.js
  src/systems/eu/eu-component/eu-component-label/eu-component-label.config.js
  src/systems/eu/eu-component/eu-component-lang-select-site/eu-component-lang-select-site.config.js
  src/systems/eu/eu-component/eu-component-link/eu-component-link.config.js
  src/systems/eu/eu-component/eu-component-list-item/eu-component-list-item.config.js
  src/systems/eu/eu-component/eu-component-list-item/package.json
  src/systems/eu/eu-component/eu-component-listing/eu-component-listing.config.js
Labels: process: review needed, tag: internal

#621 feat(fractal-theme): add side navigation - INNO-936
  src/generic/generic-component-side-navigation/generic-component-side-navigation.js
  src/generic/generic-component-side-navigation/generic-component-side-navigation.scss
  src/generic/generic-utility-padding/README.md
  src/generic/generic-utility-padding/generic-utility-padding.scss
  src/generic/generic-utility-padding/generic-utility-padding.twig
  src/systems/ec/ec-component/ec-component-navigation/ec-component-side-navigation/test/spec/screenshots/reference/ecl-side-navigation/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-navigation/ec-component-side-navigation/test/spec/screenshots/reference/ecl-side-navigation/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-navigation/ec-component-side-navigation/test/spec/screenshots/reference/ecl-side-navigation/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-navigation/ec-component-side-navigation/test/spec/screenshots/reference/ecl-side-navigation/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-utility/ec-utility-padding/README.md
  src/systems/ec/ec-utility/ec-utility-padding/ec-utility-padding.twig
  src/systems/eu/eu-component/eu-component-navigation/eu-component-side-navigation/test/spec/screenshots/reference/ecl-side-navigation/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-navigation/eu-component-side-navigation/test/spec/screenshots/reference/ecl-side-navigation/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-navigation/eu-component-side-navigation/test/spec/screenshots/reference/ecl-side-navigation/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-navigation/eu-component-side-navigation/test/spec/screenshots/reference/ecl-side-navigation/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-utility/eu-utility-padding/README.md
  src/systems/eu/eu-utility/eu-utility-padding/eu-utility-padding.twig
  tools/fractal-theme/assets/js/ecl-fractal-theme.js
  tools/fractal-theme/assets/js/search.js
  tools/fractal-theme/views/layouts/doc-frame.nunj
  tools/fractal-theme/views/layouts/pen-frame.nunj
  tools/fractal-theme/views/macros/navigation.nunj
  tools/fractal-theme/views/partials/navigation/components.nunj
Labels: process: review needed, tag: enhancement

#671 refactor(config): harmonize config.js, pt.3 - INNO-1026
  src/generic/generic-component-form-checkbox/data/demo--checked.js
  src/generic/generic-component-form-checkbox/data/demo--default.js
  src/generic/generic-component-form-checkbox/data/demo--disabled.js
  src/generic/generic-component-form-checkbox/data/demo--error.js
  src/generic/generic-component-form-file-upload/data/demo--default.js
  src/generic/generic-component-form-file-upload/data/demo--disabled.js
  src/generic/generic-component-form-file-upload/data/demo--error.js
  src/generic/generic-component-form-file-upload/data/demo--multiple.js
  src/generic/generic-component-form-help-block/data/demo--default.js
  src/generic/generic-component-form-help-block/data/demo--disabled.js
  src/generic/generic-component-form-help-block/data/demo--error.js
  src/generic/generic-component-form-label/data/demo.js
  src/generic/generic-component-form-legend/data/demo--level-1.js
  src/generic/generic-component-form-legend/data/demo--level-2.js
  src/generic/generic-component-form-radio-group/data/demo.js
  src/generic/generic-component-form-radio/data/demo--checked.js
  src/generic/generic-component-form-radio/data/demo--default.js
  src/generic/generic-component-form-radio/data/demo--disabled.js
  src/generic/generic-component-form-radio/data/demo--error.js
  src/generic/generic-component-form-select/data/demo--default.js
  src/generic/generic-component-form-select/data/demo--disabled.js
  src/generic/generic-component-form-select/data/demo--with-errors.js
  src/generic/generic-component-form-select/data/shared.js
  src/generic/generic-component-form-text-input/data/demo--default.js
  src/generic/generic-component-form-text-input/data/demo--disabled.js
  src/generic/generic-component-form-text-input/data/demo--with-error.js
  src/generic/generic-component-form-textarea/data/demo--default.js
  src/generic/generic-component-form-textarea/data/demo--has-error.js
  src/generic/generic-component-form-textarea/data/demo--is-disabled.js
  src/generic/generic-component-gallery/data/demo.js
  src/systems/ec/ec-component/ec-component-form/ec-component-form-checkbox/ec-component-form-checkbox.config.js
  src/systems/ec/ec-component/ec-component-form/ec-component-form-file-upload/ec-component-form-file-upload.config.js
  src/systems/ec/ec-component/ec-component-form/ec-component-form-help-block/ec-component-form-help-block.config.js
  src/systems/ec/ec-component/ec-component-form/ec-component-form-help-block/package.json
  src/systems/ec/ec-component/ec-component-form/ec-component-form-label/ec-component-form-label.config.js
  src/systems/ec/ec-component/ec-component-form/ec-component-form-label/package.json
  src/systems/ec/ec-component/ec-component-form/ec-component-form-legend/ec-component-form-legend.config.js
  src/systems/ec/ec-component/ec-component-form/ec-component-form-legend/package.json
  src/systems/ec/ec-component/ec-component-form/ec-component-form-radio-group/ec-component-form-radio-group.config.js
  src/systems/ec/ec-component/ec-component-form/ec-component-form-radio/ec-component-form-radio.config.js
  src/systems/ec/ec-component/ec-component-form/ec-component-form-select/ec-component-form-select.config.js
  src/systems/ec/ec-component/ec-component-form/ec-component-form-select/package.json
  src/systems/ec/ec-component/ec-component-form/ec-component-form-text-input/ec-component-form-text-input.config.js
  src/systems/ec/ec-component/ec-component-form/ec-component-form-textarea/ec-component-form-textarea.config.js
  src/systems/ec/ec-component/ec-component-gallery/ec-component-gallery.config.js
  src/systems/eu/eu-component/eu-component-form/eu-component-form-checkbox/eu-component-form-checkbox.config.js
  src/systems/eu/eu-component/eu-component-form/eu-component-form-file-upload/eu-component-form-file-upload.config.js
  src/systems/eu/eu-component/eu-component-form/eu-component-form-help-block/eu-component-form-help-block.config.js
  src/systems/eu/eu-component/eu-component-form/eu-component-form-help-block/package.json
  src/systems/eu/eu-component/eu-component-form/eu-component-form-label/eu-component-form-label.config.js
  src/systems/eu/eu-component/eu-component-form/eu-component-form-label/package.json
  src/systems/eu/eu-component/eu-component-form/eu-component-form-legend/eu-component-form-legend.config.js
  src/systems/eu/eu-component/eu-component-form/eu-component-form-legend/package.json
  src/systems/eu/eu-component/eu-component-form/eu-component-form-radio-group/eu-component-form-radio-group.config.js
  src/systems/eu/eu-component/eu-component-form/eu-component-form-radio/eu-component-form-radio.config.js
  src/systems/eu/eu-component/eu-component-form/eu-component-form-select/eu-component-form-select.config.js
  src/systems/eu/eu-component/eu-component-form/eu-component-form-select/package.json
  src/systems/eu/eu-component/eu-component-form/eu-component-form-text-input/eu-component-form-text-input.config.js
  src/systems/eu/eu-component/eu-component-form/eu-component-form-textarea/eu-component-form-textarea.config.js
  src/systems/eu/eu-component/eu-component-gallery/eu-component-gallery.config.js
Labels: process: review needed, tag: internal

#673 refactor(config): harmonize config.js, pt.4 - INNO-1026
  src/generic/generic-component-datepicker/data/demo.js
  src/generic/generic-component-dialog/data/demo.js
  src/generic/generic-component-dropdown/data/demo.js
  src/generic/generic-component-featured-item/data/demo--default.js
  src/generic/generic-component-featured-item/data/demo--extended.js
  src/generic/generic-component-field/data/demo--aligned.js
  src/generic/generic-component-field/data/demo--default.js
  src/generic/generic-component-file/data/demo--default.js
  src/generic/generic-component-file/data/demo--images.js
  src/generic/generic-component-file/data/demo--links.js
  src/generic/generic-component-file/data/demo--translations.js
  src/generic/generic-component-file/data/demo--videos-iframe.js
  src/generic/generic-component-file/data/demo--videos-tag.js
  src/systems/ec/ec-component/ec-component-datepicker/ec-component-datepicker.config.js
  src/systems/ec/ec-component/ec-component-dialog/ec-component-dialog.config.js
  src/systems/ec/ec-component/ec-component-dropdown/ec-component-dropdown.config.js
  src/systems/ec/ec-component/ec-component-featured-item/ec-component-featured-item.config.js
  src/systems/ec/ec-component/ec-component-field/ec-component-field.config.js
  src/systems/ec/ec-component/ec-component-file/ec-component-file.config.js
  src/systems/eu/eu-component/eu-component-datepicker/eu-component-datepicker.config.js
  src/systems/eu/eu-component/eu-component-dialog/eu-component-dialog.config.js
  src/systems/eu/eu-component/eu-component-dropdown/eu-component-dropdown.config.js
  src/systems/eu/eu-component/eu-component-dropdown/package.json
  src/systems/eu/eu-component/eu-component-featured-item/eu-component-featured-item.config.js
  src/systems/eu/eu-component/eu-component-field/eu-component-field.config.js
  src/systems/eu/eu-component/eu-component-file/eu-component-file.config.js
Labels: process: review needed, tag: internal

#675 fix(ecl-editor): fix ecl-editor exports - no issue
  src/generic/generic-component-site-switcher/generic-component-site-switcher.twig
  src/generic/generic-component-social-media-link/data/demo--default-specific.js
  src/generic/generic-component-social-media-link/data/demo--default.js
  src/generic/generic-component-social-media-link/data/demo--horizontal-specific.js
  src/generic/generic-component-social-media-link/data/demo--horizontal.js
  src/generic/generic-component-social-media-link/data/shared.js
  src/generic/generic-component-table/data/demo--colspan-empty-enhanced.js
  src/generic/generic-component-table/data/demo--empty-enhanced.js
  src/generic/generic-style-typography-list/generic-style-typography-list--editor.scss
  src/systems/ec/ec-component/ec-component-blockquote/ec-component-blockquote--editor.scss
  src/systems/ec/ec-component/ec-component-link/ec-component-link--editor.scss
  src/systems/ec/ec-component/ec-component-site-switcher/test/spec/screenshots/reference/site-switchers/footer/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-site-switcher/test/spec/screenshots/reference/site-switchers/footer/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-site-switcher/test/spec/screenshots/reference/site-switchers/footer/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-site-switcher/test/spec/screenshots/reference/site-switchers/footer/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-social-icon/test/spec/screenshots/reference/social-icons/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-social-icon/test/spec/screenshots/reference/social-icons/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-social-icon/test/spec/screenshots/reference/social-icons/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-social-icon/test/spec/screenshots/reference/social-icons/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-table/ec-component-table--editor.scss
  src/systems/ec/ec-preset/ec-preset-corporate/_imports.scss
  src/systems/ec/ec-preset/ec-preset-full/_imports.scss
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography-heading/ec-style-typography-heading--editor.scss
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography-list/ec-style-typography-list--editor.scss
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography-paragraph/ec-style-typography-paragraph--editor.scss
  src/systems/eu/eu-component/eu-component-blockquote/eu-component-blockquote--editor.scss
  src/systems/eu/eu-component/eu-component-link/eu-component-link--editor.scss
  src/systems/eu/eu-component/eu-component-site-switcher/test/spec/screenshots/reference/site-switchers/footer/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-site-switcher/test/spec/screenshots/reference/site-switchers/footer/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-site-switcher/test/spec/screenshots/reference/site-switchers/footer/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-site-switcher/test/spec/screenshots/reference/site-switchers/footer/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-social-icon/test/spec/screenshots/reference/social-icons/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-social-icon/test/spec/screenshots/reference/social-icons/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-social-icon/test/spec/screenshots/reference/social-icons/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-social-icon/test/spec/screenshots/reference/social-icons/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-table/eu-component-table--editor.scss
  src/systems/eu/eu-preset/eu-preset-corporate/_imports.scss
  src/systems/eu/eu-preset/eu-preset-full/_imports.scss
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography-heading/eu-style-typography-heading--editor.scss
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography-list/eu-style-typography-list--editor.scss
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography-paragraph/eu-style-typography-paragraph--editor.scss
  tools/fractal-theme/views/partials/header.nunj
  website/index.html
Labels: process: review needed, tag: bug fix

#676 refactor(config): harmonize config.js, pt.5 - INNO-1026
  src/generic/generic-component-accordion/data/demo.js
  src/generic/generic-component-banner/data/demo--hero.js
  src/generic/generic-component-banner/data/demo--video.js
  src/generic/generic-component-blockquote/data/demo.js
  src/generic/generic-component-breadcrumb/data/demo.js
  src/generic/generic-component-button/data/demo.js
  src/generic/generic-component-carousel/data/demo.js
  src/generic/generic-component-comment/data/demo.js
  src/generic/generic-component-context-nav/data/demo.js
  src/generic/generic-component-date-block/data/demo--cancelled.js
  src/generic/generic-component-date-block/data/demo--default.js
  src/generic/generic-component-date-block/data/demo--ongoing.js
  src/generic/generic-component-date-block/data/demo--past.js
  src/systems/ec/ec-component/ec-component-accordion/ec-component-accordion.config.js
  src/systems/ec/ec-component/ec-component-accordion/package.json
  src/systems/ec/ec-component/ec-component-banner/ec-component-banner.config.js
  src/systems/ec/ec-component/ec-component-blockquote/ec-component-blockquote.config.js
  src/systems/ec/ec-component/ec-component-breadcrumb/ec-component-breadcrumb.config.js
  src/systems/ec/ec-component/ec-component-breadcrumb/package.json
  src/systems/ec/ec-component/ec-component-button/ec-component-button.config.js
  src/systems/ec/ec-component/ec-component-button/test/spec/buttons.js
  src/systems/ec/ec-component/ec-component-button/variants.json
  src/systems/ec/ec-component/ec-component-carousel/ec-component-carousel.config.js
  src/systems/ec/ec-component/ec-component-comment/ec-component-comment.config.js
  src/systems/ec/ec-component/ec-component-context-nav/ec-component-context-nav.config.js
  src/systems/ec/ec-component/ec-component-date-block/ec-component-date-block.config.js
  src/systems/eu/eu-component/eu-component-accordion/eu-component-accordion.config.js
  src/systems/eu/eu-component/eu-component-accordion/package.json
  src/systems/eu/eu-component/eu-component-banner/eu-component-banner.config.js
  src/systems/eu/eu-component/eu-component-blockquote/eu-component-blockquote.config.js
  src/systems/eu/eu-component/eu-component-breadcrumb/eu-component-breadcrumb.config.js
  src/systems/eu/eu-component/eu-component-breadcrumb/package.json
  src/systems/eu/eu-component/eu-component-button/eu-component-button.config.js
  src/systems/eu/eu-component/eu-component-button/test/spec/buttons.js
  src/systems/eu/eu-component/eu-component-button/variants.json
  src/systems/eu/eu-component/eu-component-carousel/eu-component-carousel.config.js
  src/systems/eu/eu-component/eu-component-comment/eu-component-comment.config.js
  src/systems/eu/eu-component/eu-component-context-nav/eu-component-context-nav.config.js
  src/systems/eu/eu-component/eu-component-date-block/eu-component-date-block.config.js
Labels: process: review needed, tag: internal

#677 fix(fractal-theme): correct template for docs - noissue
  tools/fractal-theme/views/partials/navigation/docs.nunj
Labels: process: review needed, tag: enhancement

#678 docs(typo): fix typo - no issue
  README.md
Labels: process: review needed, tag: documentation

#679 refactor(expandable): init function - INNO-1023
  src/generic/generic-component-dropdown/data/demo.js
  src/generic/generic-component-expandable/README.md
  src/generic/generic-component-expandable/data/demo.js
  src/generic/generic-component-expandable/generic-component-expandable.js
  src/generic/generic-component-profile-topbar/data/demo.js
  src/generic/generic-component-side-navigation/data/demo.js
  src/systems/ec/ec-component/ec-component-expandable/README.md
  src/systems/ec/ec-component/ec-component-expandable/ec-component-expandable.config.js
  src/systems/ec/ec-component/ec-component-expandable/ec-component-expandable.js
  src/systems/ec/ec-component/ec-component-expandable/package.json
  src/systems/ec/ec-template/ec-template-search/ec-template-search.config.js
  src/systems/eu/eu-component/eu-component-expandable/README.md
  src/systems/eu/eu-component/eu-component-expandable/eu-component-expandable.config.js
  src/systems/eu/eu-component/eu-component-expandable/eu-component-expandable.js
  src/systems/eu/eu-component/eu-component-expandable/package.json
  src/systems/eu/eu-template/eu-template-search/eu-template-search.config.js
  tools/fractal-theme/assets/js/ecl-fractal-theme.js
Labels: process: review needed

#683 feat(social-icon): update icons and fix display
  src/systems/ec/ec-component/ec-component-social-icon/ec-component-social-icon.config.js
  src/systems/ec/ec-component/ec-component-social-icon/images/social/gplus.svg
  src/systems/ec/ec-component/ec-component-social-icon/images/social/gplus_hover.svg
  src/systems/ec/ec-component/ec-component-social-icon/images/social/youtube.svg
  src/systems/ec/ec-component/ec-component-social-icon/images/social/youtube_hover.svg
  src/systems/ec/ec-component/ec-component-social-icon/test/spec/screenshots/reference/social-icons/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-social-icon/test/spec/screenshots/reference/social-icons/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-social-icon/test/spec/screenshots/reference/social-icons/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-social-icon/test/spec/screenshots/reference/social-icons/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-social-icon/eu-component-social-icon.config.js
  src/systems/eu/eu-component/eu-component-social-icon/images/social/gplus.svg
  src/systems/eu/eu-component/eu-component-social-icon/images/social/gplus_hover.svg
  src/systems/eu/eu-component/eu-component-social-icon/images/social/youtube.svg
  src/systems/eu/eu-component/eu-component-social-icon/images/social/youtube_hover.svg
  src/systems/eu/eu-component/eu-component-social-icon/test/spec/screenshots/reference/social-icons/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-social-icon/test/spec/screenshots/reference/social-icons/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-social-icon/test/spec/screenshots/reference/social-icons/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-social-icon/test/spec/screenshots/reference/social-icons/macOS 10.12_Safari_v11.png
Labels: process: review needed, tag: enhancement

#684 docs(ownership): add "Need help?" section - INNO-1022
  .drone.yml
  README.md
  docs/06-presets.md
  docs/07-developers.md
  website/index.html
Labels: tag: documentation
