Repository ec-europa/europa-component-library, pull requests merged in 2018-12, with the labels that each got.

#970 docs: update title on EU homepage
  src/website/src/pages/eu/index.md
Labels: tag: documentation

#974 chore: update dependencies - no issue
  .pullapprove.yml
  examples/webpack3/package.json
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/eu/implementations/react/storybook/package.json
  src/tools/website-components/package.json
  src/website/package.json
  yarn.lock
Labels: process: under review, tag: internal

#978 feat(website): add table styling - INNO-1294
  src/website/src/App.jsx
  src/website/src/components/DocPage/DocPage.jsx
  src/website/src/styles/markdown.scss
Labels: process: under review, tag: enhancement

#942 docs(developer): update developers documentation for v2 - INNO-1277
  TROUBLESHOOTING.md
  docs/07-developers.md
  docs/08-add-component.md
Labels: tag: documentation

#950 feat(social-media-share): add component - INNO-1264
  docs/04-documentation.md
  src/systems/ec/implementations/react/packages/social-media-share/SocialMediaShare.jsx
  src/systems/ec/implementations/react/packages/social-media-share/package.json
  src/systems/ec/implementations/react/packages/social-media-share/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-base/mixins/_icon-rollover.scss
  src/systems/ec/implementations/vanilla/packages/ec-base/mixins/_social-colors-map.scss
  src/systems/ec/implementations/vanilla/packages/ec-base/mixins/index.scss
  src/systems/ec/implementations/vanilla/packages/ec-base/variables/_social-media-list.scss
  src/systems/ec/implementations/vanilla/packages/ec-base/variables/index.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-social-media-share/README.md
  src/systems/ec/implementations/vanilla/packages/ec-component-social-media-share/ec-component-social-media-share.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-social-media-share/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.scss
  src/systems/ec/resources/social-icons/src/social/gplus.svg
  src/systems/ec/resources/social-icons/src/social/gplus_hover.svg
  src/systems/ec/specs/components/social-media-share/demo/data.js
  src/systems/ec/specs/components/social-media-share/package.json
  src/systems/eu/implementations/react/packages/social-media-share/SocialMediaShare.jsx
  src/systems/eu/implementations/react/packages/social-media-share/package.json
  src/systems/eu/implementations/react/packages/social-media-share/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-base/mixins/_icon-rollover.scss
  src/systems/eu/implementations/vanilla/packages/eu-base/mixins/_social-colors-map.scss
  src/systems/eu/implementations/vanilla/packages/eu-base/mixins/index.scss
  src/systems/eu/implementations/vanilla/packages/eu-base/variables/_social-media-list.scss
  src/systems/eu/implementations/vanilla/packages/eu-base/variables/index.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-social-media-share/README.md
  src/systems/eu/implementations/vanilla/packages/eu-component-social-media-share/eu-component-social-media-share.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-social-media-share/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev.scss
  src/systems/eu/resources/social-icons/src/social/gplus.svg
  src/systems/eu/resources/social-icons/src/social/gplus_hover.svg
  src/systems/eu/specs/components/social-media-share/demo/data.js
  src/systems/eu/specs/components/social-media-share/package.json
  src/website/src/components/DocPage/DocPage.scss
  src/website/src/pages/ec/components/navigation/contextual-navigation/docs/code.mdx
  src/website/src/pages/ec/components/social-media-share/docs/code.mdx
  src/website/src/pages/ec/components/social-media-share/docs/style.md
  src/website/src/pages/ec/components/social-media-share/docs/usage.md
  src/website/src/pages/ec/components/social-media-share/index.md
  src/website/src/pages/eu/components/navigation/contextual-navigation/docs/code.mdx
  src/website/src/pages/eu/components/social-media-share/docs/code.mdx
  src/website/src/pages/eu/components/social-media-share/docs/style.md
  src/website/src/pages/eu/components/social-media-share/docs/usage.md
  src/website/src/pages/eu/components/social-media-share/index.md
Labels: tag: new feature

#983 feat(back-to-top): apply specs - INNO-1244
  src/systems/ec/implementations/react/packages/footer/Footer.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-footer/ec-component-footer.scss
  src/systems/ec/specs/components/footer/demo/data--corporate.js
  src/systems/ec/specs/components/footer/demo/data--custom.js
  src/systems/eu/implementations/react/packages/footer/Footer.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-footer/eu-component-footer.scss
  src/systems/eu/specs/components/footer/demo/data--corporate.js
  src/systems/eu/specs/components/footer/demo/data--custom.js
Labels: tag: new feature

#959 feat(file): apply new specs - INNO-1245
  docs/08-add-component.md
  src/systems/ec/implementations/react/packages/file/FileDownload.jsx
  src/systems/ec/implementations/react/packages/file/package.json
  src/systems/ec/implementations/react/packages/file/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-file/README.md
  src/systems/ec/implementations/vanilla/packages/ec-component-file/ec-component-file.js
  src/systems/ec/implementations/vanilla/packages/ec-component-file/ec-component-file.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-file/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.js
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.scss
  src/systems/ec/specs/components/file/demo/data--with-translation.js
  src/systems/ec/specs/components/file/demo/data--without-translation.js
  src/systems/ec/specs/components/file/package.json
  src/systems/eu/implementations/react/packages/file/FileDownload.jsx
  src/systems/eu/implementations/react/packages/file/package.json
  src/systems/eu/implementations/react/packages/file/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-file/README.md
  src/systems/eu/implementations/vanilla/packages/eu-component-file/eu-component-file.js
  src/systems/eu/implementations/vanilla/packages/eu-component-file/eu-component-file.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-file/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev.js
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev.scss
  src/systems/eu/specs/components/file/demo/data--with-translation.js
  src/systems/eu/specs/components/file/demo/data--without-translation.js
  src/systems/eu/specs/components/file/package.json
  src/website/src/pages/ec/components/file/docs/code.mdx
  src/website/src/pages/ec/components/file/docs/usage.md
  src/website/src/pages/ec/components/file/index.md
  src/website/src/pages/ec/components/social-media-share/docs/code.mdx
  src/website/src/pages/eu/components/file/docs/code.mdx
  src/website/src/pages/eu/components/file/docs/usage.md
  src/website/src/pages/eu/components/file/index.md
Labels: process: review needed, tag: new feature

#980 fix(eu-footer): update content and styles - INNO-1309
  examples/webpack4-eu/src/index.html
  src/systems/eu/_partials/_preview-full-page.twig
  src/systems/eu/eu-component/eu-component-footer/README.md
  src/systems/eu/eu-component/eu-component-footer/eu-component-footer.config.js
  src/systems/eu/eu-component/eu-component-footer/eu-component-footer.scss
  src/systems/eu/eu-component/eu-component-footer/eu-component-footer.twig
  src/systems/eu/eu-component/eu-component-footer/test/spec/screenshots/reference/footers/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-footer/test/spec/screenshots/reference/footers/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-footer/test/spec/screenshots/reference/footers/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-footer/test/spec/screenshots/reference/footers/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-community/eu-template-community.twig
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-listing/eu-template-listing.twig
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-page/eu-template-page.twig
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/simple/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/simple/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/simple/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/simple/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/with-menu/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/with-menu/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/with-menu/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/with-menu/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/macOS 10.12_Safari_v11.png
Labels: tag: bug fix

#986 fix(eu-component-rss-link): fix cyclic dependency - no issue
  src/systems/eu/eu-component/eu-component-rss-link/package.json
Labels: tag: bug fix

#985 feat(button): add disable state - INNO-1293
  src/systems/ec/implementations/react/packages/button/Button.jsx
  src/systems/ec/implementations/react/packages/button/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-button/ec-component-button.scss
  src/systems/eu/implementations/react/packages/button/Button.jsx
  src/systems/eu/implementations/react/packages/button/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-button/eu-component-button.scss
Labels: tag: new feature
