Repository ec-europa/europa-component-library, pull requests merged in 2018-09, with the labels that each got.

#791 feat(text-fields): add label + helper + validation message - INNO-1192
  package.json
  src/systems/ec/implementations/react/packages/text-area/stories/index.jsx
  src/systems/ec/implementations/react/packages/text-area/stories/index.scss
  src/systems/ec/implementations/react/packages/text-input/stories/index.jsx
  src/systems/ec/implementations/react/packages/text-input/stories/index.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-full/_imports.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-website/package.json
  src/systems/ec/specs/components/card/docs/Annotation03.png
  src/systems/ec/specs/components/card/docs/style.md
  src/systems/ec/specs/components/text-area/demo/data--default.js
  src/systems/ec/specs/components/text-area/docs/code.mdx
  src/systems/ec/specs/components/text-input/demo/data--default.js
  src/systems/ec/specs/components/text-input/docs/code.mdx
  src/systems/ec/specs/style/image/docs/Annotation03.png
  src/systems/ec/specs/style/image/docs/style.md
  src/systems/eu/implementations/react/packages/text-area/stories/index.jsx
  src/systems/eu/implementations/react/packages/text-area/stories/index.scss
  src/systems/eu/implementations/react/packages/text-input/stories/index.jsx
  src/systems/eu/implementations/react/packages/text-input/stories/index.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-full/_imports.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-website/package.json
  src/systems/eu/specs/components/card/docs/Annotation03.png
  src/systems/eu/specs/components/card/docs/style.md
  src/systems/eu/specs/components/text-area/demo/data--default.js
  src/systems/eu/specs/components/text-area/docs/code.mdx
  src/systems/eu/specs/components/text-input/demo/data--default.js
  src/systems/eu/specs/components/text-input/docs/code.mdx
  src/systems/eu/specs/style/colors/docs/usage.md
  src/systems/eu/specs/style/image/docs/Annotation03.png
  src/systems/eu/specs/style/image/docs/style.md
  src/systems/generic/implementations/react/text-area/TextArea.jsx
  src/systems/generic/implementations/react/text-input/TextInput.jsx
  src/systems/generic/implementations/vanilla/generic-component-form-feedback-message/generic-component-form-feedback-message.scss
  src/systems/generic/implementations/vanilla/generic-component-form-form-group/generic-component-form-form-group.scss
  src/systems/generic/implementations/vanilla/generic-component-form-help-block/generic-component-form-help-block.scss
  src/systems/generic/implementations/vanilla/generic-component-form-label/generic-component-form-label.scss
  src/systems/generic/implementations/vanilla/generic-component-form-text-area/generic-component-form-text-area.scss
  src/systems/generic/implementations/vanilla/generic-component-form-text-input/generic-component-form-text-input.scss
  src/tools/website-components/DisplayTokens/Color.jsx
  src/tools/website-components/Playground.scss
  src/website/package.json
  src/website/src/App.jsx
  src/website/src/components/DocPage/DocPage.jsx
  src/website/src/components/Example/Example.jsx
  src/website/src/components/PageNotFound/PageNotFound.jsx
  src/website/src/components/ScrollToTopOnMount/ScrollToTopOnMount.jsx
  src/website/src/components/SplashPage/SplashPage.jsx
  src/website/src/components/TextContainer/TextContainer.jsx
  src/website/src/components/TextContainer/TextContainer.scss
  src/website/src/pages/ec/index.jsx
  src/website/src/pages/eu/index.jsx
  src/website/src/styles/markdown.scss
  yarn.lock
Labels: tag: enhancement

#794 fix(language-list): put spanish in second position - no-issue
  src/generic/generic-component-language-list/languages.json
  src/systems/ec/ec-component/ec-component-language-list/languages.json
  src/systems/ec/ec-component/ec-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-language-list/languages.json
  src/systems/eu/eu-component/eu-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/macOS 10.12_Safari_v11.png
Labels: tag: enhancement

#796 fix(text-fields): remove spacing and icon - INNO-1192
  src/systems/generic/implementations/react/text-area/TextArea.jsx
  src/systems/generic/implementations/react/text-input/TextInput.jsx
  src/systems/generic/implementations/vanilla/generic-component-form-feedback-message/generic-component-form-feedback-message.scss
  src/systems/generic/implementations/vanilla/generic-component-form-form-group/generic-component-form-form-group.scss
Labels: tag: bug fix

#799 First draft of Menu for EC
  src/systems/ec/specs/components/menu/docs/usage.md
  src/website/src/App.jsx
  src/website/src/styles/markdown.scss
Labels: tag: documentation

#784 feat(website): update splash page - no issue
  src/website/src/components/SplashPage/LogoLink.scss
  src/website/src/components/SplashPage/SplashPage.scss
  src/website/src/pages/index.md
  src/website/src/styles/markdown.scss
Labels: tag: enhancement

#806 docs(colors): improve docs presentation - INNO-1213
  examples/webpack3/package.json
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  src/systems/ec/implementations/react/packages/blockquote/package.json
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-side-navigation/package.json
  src/systems/ec/specs/style/colors/docs/usage.md
  src/systems/ec/themes/default/aliases/colors.yml
  src/systems/eu/implementations/react/packages/blockquote/package.json
  src/systems/eu/implementations/react/storybook/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-side-navigation/package.json
  src/systems/eu/specs/style/colors/docs/usage.md
  src/systems/eu/themes/default/aliases/colors.yml
  src/systems/generic/design-tokens/tokens/colors.yml
  src/systems/generic/implementations/react/blockquote/package.json
  src/systems/generic/implementations/vanilla/generic-component-side-navigation/package.json
  src/tools/website-components/Color/Card.jsx
  src/tools/website-components/Color/Card.scss
  src/tools/website-components/Color/Layout.jsx
  src/tools/website-components/Color/Palette.jsx
  src/tools/website-components/Color/Palette.scss
  src/tools/website-components/Color/PaletteItem.jsx
  src/tools/website-components/Color/PaletteItem.scss
  src/tools/website-components/DisplayTokens.jsx
  src/tools/website-components/DisplayTokens/Color.jsx
  src/tools/website-components/index.js
  src/tools/website-components/package.json
  src/website/package.json
  src/website/src/components/Grid/Col.jsx
  src/website/src/styles/markdown.scss
  src/website/src/styles/utilities.scss
  yarn.lock
Labels: tag: documentation

#798 feat(date-block): implement date block component - INNO-1204
  src/systems/ec/implementations/react/packages/date-block/DateBlock.jsx
  src/systems/ec/implementations/react/packages/date-block/package.json
  src/systems/ec/implementations/react/packages/date-block/stories/index.jsx
  src/systems/ec/specs/components/date-block/config.js
  src/systems/ec/specs/components/date-block/demo/data--cancelled.js
  src/systems/ec/specs/components/date-block/demo/data--default.js
  src/systems/ec/specs/components/date-block/demo/data--ongoing.js
  src/systems/ec/specs/components/date-block/demo/data--past.js
  src/systems/ec/specs/components/date-block/docs/code.md
  src/systems/ec/specs/components/date-block/docs/style.md
  src/systems/ec/specs/components/date-block/docs/usage.md
  src/systems/ec/specs/components/date-block/package.json
  src/systems/eu/implementations/react/packages/date-block/DateBlock.jsx
  src/systems/eu/implementations/react/packages/date-block/package.json
  src/systems/eu/implementations/react/packages/date-block/stories/index.jsx
  src/systems/eu/specs/components/date-block/config.js
  src/systems/eu/specs/components/date-block/demo/data--cancelled.js
  src/systems/eu/specs/components/date-block/demo/data--default.js
  src/systems/eu/specs/components/date-block/demo/data--ongoing.js
  src/systems/eu/specs/components/date-block/demo/data--past.js
  src/systems/eu/specs/components/date-block/docs/code.md
  src/systems/eu/specs/components/date-block/docs/style.md
  src/systems/eu/specs/components/date-block/docs/usage.md
  src/systems/eu/specs/components/date-block/package.json
  src/systems/generic/implementations/vanilla/generic-component-date-block/generic-component-date-block.scss
Labels: process: under review, tag: new feature

#811 feat(eu-header): apply new specs - INNO-1203
  src/systems/ec/implementations/react/packages/search-form/SearchForm.jsx
  src/systems/ec/specs/components/page-header/site-header/docs/code.md
  src/systems/ec/specs/components/page-header/site-header/package.json
  src/systems/eu/implementations/react/packages/search-form/SearchForm.jsx
  src/systems/eu/implementations/react/packages/site-header/SiteHeader.jsx
  src/systems/eu/implementations/react/packages/site-header/package.json
  src/systems/eu/implementations/react/packages/site-header/stories/index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-site-header/eu-component-site-header.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-site-header/package.json
  src/systems/eu/specs/components/page-header/site-header/config.js
  src/systems/eu/specs/components/page-header/site-header/docs/code.md
  src/systems/eu/specs/components/page-header/site-header/docs/style.md
  src/systems/eu/specs/components/page-header/site-header/docs/usage.md
  src/systems/eu/specs/components/site-header/config.js
  src/systems/eu/specs/components/site-header/demo/data.js
  src/systems/eu/specs/components/site-header/docs/code.mdx
  src/systems/eu/specs/components/site-header/docs/style.md
  src/systems/eu/specs/components/site-header/docs/usage.md
  src/systems/eu/specs/components/site-header/package.json
Labels: tag: new feature

#816 chore(dev-server): replace webpack-serve with webpack-dev-server
  src/website/package.json
  src/website/webpack.config.dev.js
  yarn.lock
Labels: process: under review, tag: internal

#818 refactor(website): use 12-columns grid - INNO-1231
  package.json
  src/systems/ec/implementations/react/packages/blockquote/package.json
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/specs/style/colors/docs/usage.md
  src/systems/eu/implementations/react/packages/blockquote/package.json
  src/systems/eu/implementations/react/storybook/package.json
  src/systems/eu/specs/style/colors/docs/usage.md
  src/systems/generic/implementations/react/blockquote/package.json
  src/tools/website-components/Color/Layout.jsx
  src/tools/website-components/package.json
  src/website/package.json
  src/website/src/components/Grid/Col.jsx
  src/website/src/components/Grid/Container.jsx
  src/website/src/components/Grid/Row.jsx
  src/website/src/components/Grid/grid.scss
  src/website/src/components/SplashPage/SplashPage.jsx
  yarn.lock
Labels: tag: enhancement

#817 feat(language-list): apply new specs - INNO-1186
  src/systems/ec/implementations/vanilla/packages/ec-component-language-list/ec-component-language-list.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-language-list/package.json
  src/systems/ec/specs/components/language-splash-page/config.js
  src/systems/ec/specs/components/language-splash-page/docs/code.md
  src/systems/eu/implementations/react/packages/language-list/LanguageList.jsx
  src/systems/eu/implementations/react/packages/language-list/LanguageListItem.jsx
  src/systems/eu/implementations/react/packages/language-list/LanguageListOverlay.jsx
  src/systems/eu/implementations/react/packages/language-list/LanguageListSplash.jsx
  src/systems/eu/implementations/react/packages/language-list/package.json
  src/systems/eu/implementations/react/packages/language-list/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-language-list/README.md
  src/systems/eu/implementations/vanilla/packages/eu-component-language-list/eu-component-language-list.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-language-list/languages.json
  src/systems/eu/implementations/vanilla/packages/eu-component-language-list/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-language-list/resources/logo-eu-mute.svg
  src/systems/eu/specs/components/language-list/config.js
  src/systems/eu/specs/components/language-list/demo/data--overlay.js
  src/systems/eu/specs/components/language-list/demo/data--splash.js
  src/systems/eu/specs/components/language-list/docs/code.mdx
  src/systems/eu/specs/components/language-list/docs/style.md
  src/systems/eu/specs/components/language-list/docs/usage.md
  src/systems/eu/specs/components/language-list/package.json
  src/systems/eu/specs/components/language-splash-page/docs/code.md
  src/systems/eu/specs/components/language-splash-page/docs/style.md
  src/systems/eu/specs/components/language-splash-page/docs/usage.md
  src/systems/eu/specs/components/language-splash-page/package.json
  src/systems/generic/implementations/vanilla/generic-component-language-list/README.md
  src/systems/generic/implementations/vanilla/generic-component-language-list/generic-component-language-list.scss
  src/systems/generic/implementations/vanilla/generic-component-language-list/languages.json
  src/systems/generic/implementations/vanilla/generic-component-language-list/package.json
  src/systems/generic/implementations/vanilla/generic-component-site-header/package.json
  src/systems/generic/implementations/vanilla/generic-layout-grid/mixins/_grid.scss
  src/website/src/components/Navigation/Navigation.jsx
Labels: process: under review, tag: new feature

#820 docs: add application
  src/website/src/pages/index.md
Labels: tag: documentation
