Repository ec-europa/europa-component-library, pull requests merged in 2018-07, with the labels that each got.

#716 fix(breadcrumb): add "expand all" behavior - INNO-1104
  src/generic/generic-component-breadcrumb/generic-component-breadcrumb.js
Labels: process: review needed, tag: bug fix

#711 feat(page-header): apply display of EU page header - INNO-1100
  src/generic/generic-component-page-header/generic-component-page-header.scss
  src/generic/generic-component-page-header/generic-component-page-header.twig
  src/systems/ec/ec-component/ec-component-page-header/ec-component-page-header.twig
  src/systems/eu/_partials/_preview-full-page.twig
  src/systems/eu/eu-component/eu-component-page-header/README.md
  src/systems/eu/eu-component/eu-component-page-header/eu-component-page-header.config.js
  src/systems/eu/eu-component/eu-component-page-header/eu-component-page-header.scss
  src/systems/eu/eu-component/eu-component-page-header/eu-component-page-header.twig
  src/systems/eu/eu-component/eu-component-page-header/test/spec/page-headers.js
  src/systems/eu/eu-component/eu-component-page-header/test/spec/screenshots/reference/page-headers/basic/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-page-header/test/spec/screenshots/reference/page-headers/basic/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-page-header/test/spec/screenshots/reference/page-headers/basic/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-page-header/test/spec/screenshots/reference/page-headers/basic/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-page-header/test/spec/screenshots/reference/page-headers/branded-homepage/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-page-header/test/spec/screenshots/reference/page-headers/branded-homepage/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-page-header/test/spec/screenshots/reference/page-headers/branded-homepage/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-page-header/test/spec/screenshots/reference/page-headers/branded-homepage/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-page-header/test/spec/screenshots/reference/page-headers/default/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-page-header/test/spec/screenshots/reference/page-headers/default/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-page-header/test/spec/screenshots/reference/page-headers/default/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-page-header/test/spec/screenshots/reference/page-headers/default/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-page-header/test/spec/screenshots/reference/page-headers/homepage/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-page-header/test/spec/screenshots/reference/page-headers/homepage/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-page-header/test/spec/screenshots/reference/page-headers/homepage/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-page-header/test/spec/screenshots/reference/page-headers/homepage/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-filter/test/spec/screenshots/reference/filters/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-filter/test/spec/screenshots/reference/filters/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-filter/test/spec/screenshots/reference/filters/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-filter/test/spec/screenshots/reference/filters/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-listing/eu-template-listing.config.js
  src/systems/eu/eu-template/eu-template-listing/eu-template-listing.twig
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-page/eu-template-page.config.js
  src/systems/eu/eu-template/eu-template-page/eu-template-page.twig
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/simple/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/simple/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/simple/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/simple/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/with-menu/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/with-menu/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/with-menu/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/with-menu/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/macOS 10.12_Safari_v11.png
  tools/eu-styleguide/static/assets/demo_images/pexels-photo-335393@2x.png
Labels: process: review needed, tag: new feature

#717 feat(language-list): update eu splash page design - INNO-1103
  src/generic/generic-component-language-list/generic-component-language-list.scss
  src/generic/generic-component-language-list/generic-component-language-list.twig
  src/generic/generic-component-logo/generic-component-logo.twig
  src/systems/ec/ec-component/ec-component-language-list/ec-component-language-list.twig
  src/systems/ec/ec-component/ec-component-logo/ec-component-logo.twig
  src/systems/eu/eu-component/eu-component-language-list/eu-component-language-list.config.js
  src/systems/eu/eu-component/eu-component-language-list/eu-component-language-list.scss
  src/systems/eu/eu-component/eu-component-language-list/eu-component-language-list.twig
  src/systems/eu/eu-component/eu-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-language-list/test/spec/screenshots/reference/ecl-language-list/open/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-logo/eu-component-logo.scss
  src/systems/eu/eu-component/eu-component-logo/eu-component-logo.twig
Labels: tag: new feature

#720 fix(checkbox): fix extra attributes - INNO-1108
  src/generic/generic-component-form-checkbox/generic-component-form-checkbox.twig
Labels: tag: bug fix

#721 feat(radio): add input attributes - INNO-1108
  src/generic/generic-component-form-checkbox/generic-component-form-checkbox.twig
  src/generic/generic-component-form-radio/generic-component-form-radio.twig
  src/systems/ec/ec-component/ec-component-form/ec-component-form-radio/ec-component-form-radio.twig
  src/systems/eu/eu-component/eu-component-form/eu-component-form-radio/eu-component-form-radio.twig
Labels: process: review needed, tag: new feature

#722 fix(logo): fix documentation and demo's HTML - INNO-1107
  src/generic/generic-component-logo/README.md
  src/generic/generic-component-logo/generic-component-logo.twig
  src/systems/ec/ec-component/ec-component-logo/README.md
  src/systems/ec/ec-component/ec-component-logo/ec-component-logo.config.js
  src/systems/ec/ec-component/ec-component-logo/test/spec/screenshots/reference/logos/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-logo/test/spec/screenshots/reference/logos/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-logo/test/spec/screenshots/reference/logos/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-logo/test/spec/screenshots/reference/logos/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-logo/README.md
  src/systems/eu/eu-component/eu-component-logo/eu-component-logo.config.js
  src/systems/eu/eu-component/eu-component-logo/test/spec/screenshots/reference/logos/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-logo/test/spec/screenshots/reference/logos/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-logo/test/spec/screenshots/reference/logos/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-logo/test/spec/screenshots/reference/logos/macOS 10.12_Safari_v11.png
Labels: tag: documentation

#724 chore(publish): republish v0 - no issue
  README.md
  netlify.toml
Labels: process: WIP

#725 docs(versions): add link to old version - no issue
  README.md
Labels: tag: documentation

#727 feat(design-tokens): tokenise spacing and color - INNO-1116
  src/generic/generic-component-button/generic-component-button.scss
  src/systems/ec/ec-component/ec-component-accordion/tokens.yml
  src/systems/ec/ec-component/ec-component-banner/tokens.yml
  src/systems/ec/ec-component/ec-component-blockquote/tokens.yml
  src/systems/ec/ec-component/ec-component-breadcrumb/tokens.yml
  src/systems/ec/ec-component/ec-component-button/tokens.yml
  src/systems/ec/ec-design-tokens/README.md
  src/systems/ec/ec-design-tokens/themes/default/aliases/colors.yml
  src/systems/ec/ec-design-tokens/themes/default/aliases/index.yml
  src/systems/ec/ec-design-tokens/themes/default/components/button.yml
  src/systems/ec/ec-design-tokens/themes/default/index.yml
  src/systems/ec/ec-design-tokens/themes/theme1/aliases/colors.yml
  src/systems/ec/ec-design-tokens/themes/theme1/aliases/index.yml
  src/systems/ec/ec-design-tokens/themes/theme1/components/button.yml
  src/systems/ec/ec-design-tokens/themes/theme1/index.yml
  src/systems/ec/ec-design-tokens/tokens/colors.yml
  src/systems/ec/ec-design-tokens/tokens/index.yml
  src/systems/ec/ec-design-tokens/tokens/spacing.yml
  src/systems/ec/ec-design-tokens/tokens/typography.yml
Labels: tag: enhancement

#738 fix(tags): support multiline tags - INNO-1140
  src/generic/generic-component-tag/generic-component-tag.scss
  src/systems/ec/ec-template/ec-template-filter/test/spec/screenshots/reference/filters/Windows 10_Chrome_v60.png
  src/systems/ec/ec-template/ec-template-filter/test/spec/screenshots/reference/filters/Windows 7_Firefox_v54.png
  src/systems/ec/ec-template/ec-template-filter/test/spec/screenshots/reference/filters/Windows 7_IE_v11.png
  src/systems/ec/ec-template/ec-template-filter/test/spec/screenshots/reference/filters/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/desktop/Windows 10_Chrome_v60.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/desktop/Windows 7_Firefox_v54.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/desktop/Windows 7_IE_v11.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/desktop/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/mobile/Windows 10_Chrome_v60.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/mobile/Windows 7_Firefox_v54.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/mobile/Windows 7_IE_v11.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/mobile/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-filter/test/spec/screenshots/reference/filters/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-filter/test/spec/screenshots/reference/filters/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-filter/test/spec/screenshots/reference/filters/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-filter/test/spec/screenshots/reference/filters/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/macOS 10.12_Safari_v11.png
Labels: tag: bug fix

#741 doc(how to): fix links
  docs/04-documentation.md
Labels: process: review needed, tag: documentation

#742 chore(dependencies): update dependencies - no issue
  examples/webpack3/package.json
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  src/generic/generic-component-side-navigation/package.json
  src/generic/generic-utility-margin/generic-utility-margin.scss
  src/generic/generic-utility-padding/generic-utility-padding.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-file/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-inpage-navigation/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-link/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-side-navigation/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-base/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-corporate/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-full/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-website/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-webtools/package.json
  src/systems/ec/implementations/vanilla/packages/ec-style-icon/package.json
  src/systems/ec/implementations/vanilla/styleguide/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-file/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-inpage-navigation/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-link/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-side-navigation/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-base/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-corporate/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-full/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-website/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-webtools/package.json
  src/systems/eu/implementations/vanilla/packages/eu-style-icon/package.json
  src/systems/eu/implementations/vanilla/styleguide/package.json
  website/src/App.js
  website/src/components/ComponentHeader.jsx
  website/src/components/ComponentPage.jsx
  website/src/components/Navigation.jsx
  website/src/hack.css
  website/src/pages/404.jsx
  website/src/pages/ec/index.jsx
  website/src/pages/eu/index.jsx
  website/src/pages/index.jsx
  website/src/styles/app.css
  website/src/styles/custom-grid.css
  yarn.lock
Labels: tag: internal
