Repository ec-europa/europa-component-library, pull requests merged in 2019-03, with the labels that each got.

#1021 fix: export classes correctly - INNO-1354
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/ec-component-gallery.js
  src/systems/ec/implementations/vanilla/packages/ec-component-message/ec-component-message.js
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.js
  src/systems/eu/implementations/vanilla/packages/eu-component-gallery/eu-component-gallery.js
  src/systems/eu/implementations/vanilla/packages/eu-component-message/eu-component-message.js
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev.js
Labels: tag: bug fix

#1022 fix: fix contextual-navigation's button - INNO-1377
  src/systems/ec/implementations/react/packages/contextual-navigation/src/ContextualNavigation.jsx
  src/systems/ec/implementations/react/packages/contextual-navigation/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-contextual-navigation/ec-component-contextual-navigation.scss
  src/systems/ec/specs/components/contextual-navigation/demo/data.js
  src/systems/eu/implementations/react/packages/contextual-navigation/src/ContextualNavigation.jsx
  src/systems/eu/implementations/react/packages/contextual-navigation/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-contextual-navigation/eu-component-contextual-navigation.scss
  src/systems/eu/specs/components/contextual-navigation/demo/data.js
Labels: tag: bug fix

#1025 fix(file): rotate icon on expand/collapse - INNO-1382
  src/systems/ec/implementations/vanilla/packages/ec-component-file/ec-component-file.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-file/eu-component-file.scss
Labels: process: under review, tag: bug fix

#1026 fix(accordion): fix display issue on IE 11 - INNO-1381
  src/systems/ec/implementations/vanilla/packages/ec-component-accordion/ec-component-accordion.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-accordion/eu-component-accordion.scss
Labels: process: under review, tag: bug fix

#1027 fix(search-form): fix layout issue - INNO-1380
  src/systems/ec/implementations/vanilla/packages/ec-component-search-form/ec-component-search-form.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-search-form/eu-component-search-form.scss
Labels: process: under review, tag: bug fix

#1028 fix(site-header): fix alignment in IE 11 - INNO-1388
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header/ec-component-site-header.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-site-header/eu-component-site-header.scss
Labels: process: under review, tag: bug fix

#1029 fix(status): prevent status shrinking - INNO-1387
  src/website/src/components/Navigation/SingleLink.scss
Labels: process: under review, tag: internal

#1030 fix: improve social-media-* on IE 11 - INNO-1386
  src/systems/ec/implementations/vanilla/packages/ec-component-social-media-follow/ec-component-social-media-follow.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-social-media-share/ec-component-social-media-share.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-social-media-follow/eu-component-social-media-follow.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-social-media-share/eu-component-social-media-share.scss
Labels: process: under review, tag: bug fix

#1031 fix(tag): fix React component for IE 11 - INNO-1385
  src/systems/ec/implementations/react/packages/tag/src/Tag.jsx
  src/systems/ec/implementations/vanilla/packages/ec-preset-full/ecl-builder.config.js
  src/systems/ec/implementations/vanilla/packages/ec-preset-website/ecl-builder.config.js
  src/systems/ec/resources/social-icons/README.md
  src/systems/eu/implementations/react/packages/tag/src/Tag.jsx
  src/systems/eu/implementations/vanilla/packages/eu-preset-full/ecl-builder.config.js
  src/systems/eu/implementations/vanilla/packages/eu-preset-website/ecl-builder.config.js
  src/systems/eu/resources/icons/.npmignore
  src/systems/eu/resources/icons/README.md
  src/systems/eu/resources/social-icons/.npmignore
  src/systems/eu/resources/social-icons/README.md
Labels: process: under review, tag: bug fix

#1032 docs: change ECL 1 version - no issue
  README.md
Labels: process: under review, tag: documentation

#1023 docs(whats-new): poc
  src/website/package.json
  src/website/src/pages/ec/whats-new/index.md
  src/website/webpack.config.dev.js
  src/website/webpack.config.prod.js
  yarn.lock
Labels: tag: documentation

#1035 fix(forms): remove space before hidden label - INNO-1391
  src/systems/ec/implementations/react/packages/select/stories/Index.jsx
  src/systems/ec/implementations/react/packages/text-area/src/TextArea.jsx
  src/systems/ec/implementations/react/packages/text-area/stories/Index.jsx
  src/systems/ec/implementations/react/packages/text-input/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-form-form-group/ec-component-form-form-group.scss
  src/systems/eu/implementations/react/packages/select/stories/Index.jsx
  src/systems/eu/implementations/react/packages/text-area/src/TextArea.jsx
  src/systems/eu/implementations/react/packages/text-area/stories/Index.jsx
  src/systems/eu/implementations/react/packages/text-input/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-form-form-group/eu-component-form-form-group.scss
Labels: tag: bug fix

#1036 fix(icons): remove g+ icon - INNO-1393
  src/systems/ec/implementations/vanilla/packages/ec-base/variables/_social-media-list.scss
  src/systems/ec/resources/icons/src/branded/google-plus.svg
  src/systems/ec/resources/social-icons/src/social/gplus.svg
  src/systems/ec/resources/social-icons/src/social/gplus_hover.svg
  src/systems/ec/specs/components/social-media-follow/demo/data.js
  src/systems/ec/specs/components/social-media-share/demo/data.js
  src/systems/eu/implementations/vanilla/packages/eu-base/variables/_social-media-list.scss
  src/systems/eu/resources/icons/src/branded/google-plus.svg
  src/systems/eu/resources/social-icons/src/social/gplus.svg
  src/systems/eu/resources/social-icons/src/social/gplus_hover.svg
  src/systems/eu/specs/components/footer/demo/data--custom.js
  src/systems/eu/specs/components/social-media-follow/demo/data.js
  src/systems/eu/specs/components/social-media-share/demo/data.js
Labels: process: under review, tag: bug fix

#1034 feat(template): add language list - INNO-1389
  src/systems/ec/implementations/react/packages/campaign-page/package.json
  src/systems/ec/implementations/react/packages/campaign-page/src/CampaignPage.jsx
  src/systems/ec/implementations/react/packages/campaign-page/stories/Index.jsx
  src/systems/ec/implementations/react/packages/language-list/src/LanguageListOverlay.jsx
  src/systems/ec/implementations/react/packages/site-header/src/SiteHeader.jsx
  src/systems/ec/implementations/react/packages/standard-page/examples/Default.jsx
  src/systems/ec/implementations/react/packages/standard-page/package.json
  src/systems/ec/implementations/react/packages/standard-page/src/StandardPage.jsx
  src/systems/ec/implementations/react/packages/standard-page/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-language-list/ec-component-language-list.scss
  src/systems/ec/specs/templates/campaign-page/demo/data.js
  src/systems/ec/specs/templates/campaign-page/package.json
  src/systems/eu/implementations/react/packages/campaign-page/package.json
  src/systems/eu/implementations/react/packages/campaign-page/src/CampaignPage.jsx
  src/systems/eu/implementations/react/packages/campaign-page/stories/Index.jsx
  src/systems/eu/implementations/react/packages/language-list/src/LanguageListOverlay.jsx
  src/systems/eu/implementations/react/packages/site-header/src/SiteHeader.jsx
  src/systems/eu/implementations/react/packages/standard-page/examples/Default.jsx
  src/systems/eu/implementations/react/packages/standard-page/package.json
  src/systems/eu/implementations/react/packages/standard-page/src/StandardPage.jsx
  src/systems/eu/implementations/react/packages/standard-page/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-language-list/eu-component-language-list.scss
  src/systems/eu/specs/templates/campaign-page/demo/data.js
  src/systems/eu/specs/templates/campaign-page/package.json
  src/tools/website-components/Playground.jsx
  src/tools/website-components/Showcase/Iframe.jsx
  src/website/src/pages/ec/page-structure/language-list/docs/code.mdx
  src/website/src/pages/eu/page-structure/language-list/docs/code.mdx
Labels: tag: enhancement

#1038 fix(templates): make sure "back to top" links to the top - INNO-1395
  package.json
  src/systems/ec/implementations/react/packages/footer/stories/Index.jsx
  src/systems/ec/implementations/react/storybook/.storybook/config.js
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/implementations/react/templates/campaign-page/examples/Default.jsx
  src/systems/ec/implementations/react/templates/campaign-page/index.js
  src/systems/ec/implementations/react/templates/campaign-page/package.json
  src/systems/ec/implementations/react/templates/campaign-page/src/CampaignPage.jsx
  src/systems/ec/implementations/react/templates/campaign-page/stories/Index.jsx
  src/systems/ec/implementations/react/templates/standard-page/examples/Default.jsx
  src/systems/ec/implementations/react/templates/standard-page/index.js
  src/systems/ec/implementations/react/templates/standard-page/package.json
  src/systems/ec/implementations/react/templates/standard-page/src/StandardPage.jsx
  src/systems/ec/implementations/react/templates/standard-page/stories/Index.jsx
  src/systems/eu/implementations/react/packages/footer/stories/Index.jsx
  src/systems/eu/implementations/react/storybook/.storybook/config.js
  src/systems/eu/implementations/react/storybook/package.json
  src/systems/eu/implementations/react/templates/campaign-page/examples/Default.jsx
  src/systems/eu/implementations/react/templates/campaign-page/index.js
  src/systems/eu/implementations/react/templates/campaign-page/package.json
  src/systems/eu/implementations/react/templates/campaign-page/src/CampaignPage.jsx
  src/systems/eu/implementations/react/templates/campaign-page/stories/Index.jsx
  src/systems/eu/implementations/react/templates/standard-page/examples/Default.jsx
  src/systems/eu/implementations/react/templates/standard-page/index.js
  src/systems/eu/implementations/react/templates/standard-page/package.json
  src/systems/eu/implementations/react/templates/standard-page/src/StandardPage.jsx
  src/systems/eu/implementations/react/templates/standard-page/stories/Index.jsx
  yarn.lock
Labels: process: under review, tag: bug fix

#1039 fix(accordion): fix accessibility - INNO-1394
  src/systems/ec/implementations/react/packages/accordion/src/Accordion.jsx
  src/systems/ec/implementations/react/packages/accordion/src/AccordionItem.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-accordion/ec-component-accordion.scss
  src/systems/eu/implementations/react/packages/accordion/src/Accordion.jsx
  src/systems/eu/implementations/react/packages/accordion/src/AccordionItem.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-accordion/eu-component-accordion.scss
Labels: tag: bug fix

#1040 fix(user-menu): fix mobile display - INNO-1400
  src/generic/generic-component-site-header/generic-component-site-header.scss
  src/generic/generic-component-site-header/generic-component-site-header.twig
  src/generic/generic-component-site-switcher/generic-component-site-switcher.scss
Labels: process: under review, tag: bug fix

#1042 fix(select): use same min/max widths as text input - INNO-1406
  README.md
  src/systems/ec/implementations/vanilla/packages/ec-component-form-select/ec-component-form-select.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-form-select/eu-component-form-select.scss
Labels: process: under review, tag: bug fix

#1043 refactor(banners): group banners - INNO-1402
  src/systems/ec/implementations/react/packages/hero-banner/stories/Index.jsx
  src/systems/ec/implementations/react/packages/page-banner/stories/Index.jsx
  src/systems/eu/implementations/react/packages/hero-banner/stories/Index.jsx
  src/systems/eu/implementations/react/packages/page-banner/stories/Index.jsx
  src/website/src/pages/ec/components/banners/hero-banner/docs/code.mdx
  src/website/src/pages/ec/components/banners/hero-banner/docs/usage.md
  src/website/src/pages/ec/components/banners/hero-banner/index.md
  src/website/src/pages/ec/components/banners/index.md
  src/website/src/pages/ec/components/banners/page-banner/docs/code.mdx
  src/website/src/pages/ec/components/banners/page-banner/docs/usage.md
  src/website/src/pages/ec/components/banners/page-banner/index.md
  src/website/src/pages/eu/components/banners/hero-banner/docs/code.mdx
  src/website/src/pages/eu/components/banners/hero-banner/docs/usage.md
  src/website/src/pages/eu/components/banners/hero-banner/index.md
  src/website/src/pages/eu/components/banners/index.md
  src/website/src/pages/eu/components/banners/page-banner/docs/code.mdx
  src/website/src/pages/eu/components/banners/page-banner/docs/usage.md
  src/website/src/pages/eu/components/banners/page-banner/index.md
Labels: tag: internal

#1041 fix(storybook): add images for local tests - INNO-1397
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/eu/implementations/react/storybook/package.json
Labels: tag: internal

#1044 refactor(expandable): rename expandable - INNO-1404
  src/systems/ec/implementations/react/packages/expandable/stories/Index.jsx
  src/systems/eu/implementations/react/packages/expandable/stories/Index.jsx
  src/website/src/pages/ec/components/expandable/docs/code.mdx
  src/website/src/pages/ec/components/expandable/index.md
  src/website/src/pages/eu/components/expandable/docs/code.mdx
  src/website/src/pages/eu/components/expandable/index.md
Labels: tag: internal

#1045 refactor(message): rename message - INNO-1405
  src/systems/ec/implementations/react/packages/message/stories/Index.jsx
  src/systems/eu/implementations/react/packages/message/stories/Index.jsx
  src/website/src/pages/ec/components/message/docs/code.mdx
  src/website/src/pages/ec/components/message/index.md
  src/website/src/pages/eu/components/message/docs/code.mdx
  src/website/src/pages/eu/components/message/index.md
Labels: tag: internal

#1046 chore: update dependencies - no issue
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/eu/implementations/react/storybook/package.json
  src/tools/builder/package.json
  src/tools/website-components/package.json
  src/website/config/babel.config.js
  src/website/package.json
  yarn.lock
Labels: process: under review, tag: internal

#1047 fix(components): hide components - INNO-1411
  src/systems/ec/implementations/react/packages/date-block/stories/Index.jsx
  src/systems/eu/implementations/react/packages/date-block/stories/Index.jsx
  src/website/src/pages/ec/components/navigation/menu/index.md
  src/website/src/pages/eu/components/navigation/menu/index.md
Labels: tag: internal

#1019 docs(site): add usage guidelines WO1
  src/website/src/pages/ec/components/button/docs/usage.mdx
  src/website/src/pages/ec/components/card/docs/usage.md
  src/website/src/pages/ec/components/card/docs/usage.mdx
  src/website/src/pages/ec/components/list/docs/usage.mdx
  src/website/src/pages/ec/components/list/index.md
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/usage.md
Labels: tag: documentation

#994 feat(template-search): add template - INNO-1315
  src/systems/ec/implementations/react/templates/search-page/examples/Default.jsx
  src/systems/ec/implementations/react/templates/search-page/index.js
  src/systems/ec/implementations/react/templates/search-page/package.json
  src/systems/ec/implementations/react/templates/search-page/src/SearchPage.jsx
  src/systems/ec/implementations/react/templates/search-page/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-utility-typography/ec-utility-typography.scss
  src/systems/ec/specs/templates/search-page/demo/data.js
  src/systems/ec/specs/templates/search-page/package.json
  src/website/src/pages/ec/templates/search-page/docs/code.mdx
  src/website/src/pages/ec/templates/search-page/docs/usage.md
  src/website/src/pages/ec/templates/search-page/index.md
Labels: process: under review, tag: new feature

#1054 feat(page-header): add language switcher - INNO-1417
  src/generic/generic-component-page-header/generic-component-page-header.twig
  src/generic/generic-component-page-header/package.json
  src/systems/ec/ec-component/ec-component-page-header/README.md
  src/systems/ec/ec-component/ec-component-page-header/ec-component-page-header.config.js
  src/systems/ec/ec-component/ec-component-page-header/ec-component-page-header.twig
  src/systems/ec/ec-component/ec-component-page-header/test/spec/screenshots/reference/page-headers/default/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-page-header/test/spec/screenshots/reference/page-headers/default/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-page-header/test/spec/screenshots/reference/page-headers/default/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-page-header/test/spec/screenshots/reference/page-headers/default/macOS 10.12_Safari_v11.png
Labels: tag: new feature
