Repository ec-europa/europa-component-library, pull requests merged in 2019-11, with the labels that each got.

#1392 fix(IE): provide fixes for IE 11 display issues - INNO-1935
  src/systems/ec/implementations/vanilla/packages/ec-component-media-container/ec-component-media-container.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-search-form/ec-component-search-form.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-media-container/eu-component-media-container.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-search-form/eu-component-search-form.scss
Labels: process: under review, tag: bug fix

#1393 fix(column-gap): fix Firefox 60 issue - INNO-1926
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  src/systems/ec/implementations/react/components/description-list/package.json
  src/systems/ec/implementations/react/components/dropdown-legacy/package.json
  src/systems/ec/implementations/react/components/ordered-list/package.json
  src/systems/ec/implementations/react/components/page-header-core/package.json
  src/systems/ec/implementations/react/components/page-header-harmonised/package.json
  src/systems/ec/implementations/react/components/page-header-standardised/package.json
  src/systems/ec/implementations/react/components/table/package.json
  src/systems/ec/implementations/react/components/timeline/package.json
  src/systems/ec/implementations/react/components/timeline2/package.json
  src/systems/ec/implementations/react/components/unordered-list/package.json
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-footer-core/ec-component-footer-core.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-footer-harmonised/ec-component-footer-harmonised.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-footer-standardised/ec-component-footer-standardised.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-core/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-harmonised/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-standardised/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-legacy-website/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-website/package.json
  src/systems/ec/resources/icons/package.json
  src/systems/ec/resources/social-icons/package.json
  src/systems/eu/implementations/react/components/description-list/package.json
  src/systems/eu/implementations/react/components/dropdown-legacy/package.json
  src/systems/eu/implementations/react/components/ordered-list/package.json
  src/systems/eu/implementations/react/components/table/package.json
  src/systems/eu/implementations/react/components/timeline/package.json
  src/systems/eu/implementations/react/components/timeline2/package.json
  src/systems/eu/implementations/react/components/unordered-list/package.json
  src/systems/eu/implementations/react/storybook/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-gallery/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-site-header/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-legacy-website/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-website/package.json
  src/systems/eu/resources/icons/package.json
  src/systems/eu/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: bug fix

#1397 chore: style 3rd-level nav - INNO-1895
  src/website/src/components/Navigation/LinkGroup.scss
  src/website/src/components/Navigation/SingleLink.scss
  src/website/src/pages/ec/content-types/events/index.md
Labels: tag: internal

#1398 chore(events-ct): update events CT - INNO-1944
  src/systems/ec/implementations/react/templates/pages/event-agenda/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/event-agenda/package.json
  src/systems/ec/implementations/react/templates/pages/event-detail/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/event-detail/package.json
  src/systems/ec/implementations/react/templates/pages/event-speaker/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/event-speaker/package.json
Labels: process: under review, tag: enhancement

#1394 docs(spacing): update doc - INNO-1924
  src/website/src/pages/ec/guidelines/spacing/index.md
  src/website/src/styles/markdown.scss
Labels: tag: documentation

#1391 feat(fact and figures): add component - INNO-1927
  .size-limit.json
  src/systems/ec/implementations/react/components/fact-figures/index.js
  src/systems/ec/implementations/react/components/fact-figures/package.json
  src/systems/ec/implementations/react/components/fact-figures/src/FactFigures.jsx
  src/systems/ec/implementations/react/components/fact-figures/src/FactFiguresItem.jsx
  src/systems/ec/implementations/react/components/fact-figures/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-fact-figures/README.md
  src/systems/ec/implementations/vanilla/packages/ec-component-fact-figures/ec-component-fact-figures-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-fact-figures/ec-component-fact-figures.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-fact-figures/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.scss
  src/systems/ec/specs/components/fact-figures/demo/data--3-col.js
  src/systems/ec/specs/components/fact-figures/demo/data--4-col.js
  src/systems/ec/specs/components/fact-figures/package.json
  src/website/src/pages/ec/components/fact-figures/docs/code.mdx
  src/website/src/pages/ec/components/fact-figures/docs/usage.mdx
  src/website/src/pages/ec/components/fact-figures/index.md
Labels: tag: new feature

#1396 feat(utilities): add dimension and box-sizing utilities - INNO-1940
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.scss
  src/systems/ec/implementations/vanilla/packages/ec-utility-dimension/README.md
  src/systems/ec/implementations/vanilla/packages/ec-utility-dimension/ec-utility-dimension-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-utility-dimension/ec-utility-dimension.scss
  src/systems/ec/implementations/vanilla/packages/ec-utility-dimension/package.json
  src/systems/ec/implementations/vanilla/packages/ec-utility-display/ec-utility-display-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-utility-display/ec-utility-display.scss
Labels: process: under review, tag: new feature

#1399 feat(funding-programme): add content type - INNO-1930
  src/systems/ec/implementations/react/templates/pages/funding-programme/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/funding-programme/index.js
  src/systems/ec/implementations/react/templates/pages/funding-programme/package.json
  src/systems/ec/implementations/react/templates/pages/funding-programme/src/FundingProgrammePage.jsx
  src/systems/ec/implementations/react/templates/pages/funding-programme/stories/Index.jsx
  src/systems/ec/specs/templates/funding-programme-page/demo/data.js
  src/systems/ec/specs/templates/funding-programme-page/package.json
  src/website/src/pages/ec/content-types/funding-programme/docs/code.mdx
  src/website/src/pages/ec/content-types/funding-programme/docs/usage.mdx
  src/website/src/pages/ec/content-types/funding-programme/index.md
Labels: tag: new feature

#1381 docs: add search content type - INNO-1897
  src/systems/ec/implementations/react/components/page-header-harmonised/src/PageHeaderHarmonised.jsx
  src/systems/ec/implementations/react/components/page-header-harmonised/stories/Index.jsx
  src/systems/ec/implementations/react/templates/pages/search/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/search/package.json
  src/systems/ec/implementations/react/templates/pages/search/src/SearchPage.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-page-header-harmonised/ec-component-page-header-harmonised.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-page-header-standardised/ec-component-page-header-standardised.scss
  src/systems/ec/specs/templates/search-page/demo/data.js
  src/website/src/components/ComponentStatus/ComponentStatus.jsx
  src/website/src/components/Navigation/SingleLink.jsx
  src/website/src/pages/ec/content-types/funding-programme/docs/usage.mdx
  src/website/src/pages/ec/content-types/search/docs/code.mdx
  src/website/src/pages/ec/content-types/search/docs/usage.md
  src/website/src/pages/ec/content-types/search/index.md
  src/website/src/pages/ec/core-template/pages/campaign/docs/code.mdx
  src/website/src/pages/ec/core-template/pages/campaign/docs/usage.md
  src/website/src/pages/ec/core-template/pages/campaign/index.md
  src/website/src/pages/ec/core-template/pages/index.md
  src/website/src/pages/ec/core-template/pages/standard/docs/code.mdx
  src/website/src/pages/ec/core-template/pages/standard/docs/usage.md
  src/website/src/pages/ec/core-template/pages/standard/index.md
Labels: tag: documentation

#1395 fix(file): amendments - INNO-1939
  src/systems/ec/implementations/vanilla/packages/ec-component-file/ec-component-file.scss
Labels: tag: enhancement

#1400 docs(blockquotes): update doc - INNO-1951
  src/website/src/pages/ec/components/blockquote/docs/usage.md
  src/website/src/pages/ec/components/blockquote/docs/usage.mdx
Labels: tag: documentation

#1366 feat(main-policy-awareness): add content type - INNO-1879
  src/systems/ec/implementations/react/templates/pages/main-policy-awareness/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-awareness/index.js
  src/systems/ec/implementations/react/templates/pages/main-policy-awareness/package.json
  src/systems/ec/implementations/react/templates/pages/main-policy-awareness/src/MainPolicyAwarenessPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-awareness/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-file/ec-component-file.scss
  src/systems/ec/specs/templates/main-policy-awareness-page/demo/data.js
  src/systems/ec/specs/templates/main-policy-awareness-page/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-file/eu-component-file.scss
  src/website/src/pages/ec/content-types/main-policy/awareness/docs/code.mdx
  src/website/src/pages/ec/content-types/main-policy/awareness/docs/usage.mdx
  src/website/src/pages/ec/content-types/main-policy/awareness/index.md
  src/website/src/pages/ec/content-types/main-policy/index.md
Labels: tag: new feature

#1376 feat(main-policy-evaluation): add content type - INNO-1879
  src/systems/ec/implementations/react/templates/pages/main-policy-evaluation/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-evaluation/index.js
  src/systems/ec/implementations/react/templates/pages/main-policy-evaluation/package.json
  src/systems/ec/implementations/react/templates/pages/main-policy-evaluation/src/MainPolicyEvaluationPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-evaluation/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-blockquote/_mixins.scss
  src/systems/ec/specs/templates/main-policy-evaluation-page/demo/data.js
  src/systems/ec/specs/templates/main-policy-evaluation-page/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-blockquote/_mixins.scss
  src/website/src/pages/ec/content-types/main-policy/evaluation/docs/code.mdx
  src/website/src/pages/ec/content-types/main-policy/evaluation/docs/usage.mdx
  src/website/src/pages/ec/content-types/main-policy/evaluation/index.md
Labels: tag: new feature

#1384 feat(main-policy-hub): add content type - INNO-1879
  .size-limit.json
  src/systems/ec/implementations/react/templates/pages/main-policy-hub/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-hub/index.js
  src/systems/ec/implementations/react/templates/pages/main-policy-hub/package.json
  src/systems/ec/implementations/react/templates/pages/main-policy-hub/src/MainPolicyHubPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-hub/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-utility-border/ec-utility-border-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-utility-border/ec-utility-border.scss
  src/systems/ec/specs/templates/main-policy-hub-page/demo/data.js
  src/systems/ec/specs/templates/main-policy-hub-page/package.json
  src/website/src/pages/ec/content-types/main-policy/hub/docs/code.mdx
  src/website/src/pages/ec/content-types/main-policy/hub/docs/usage.mdx
  src/website/src/pages/ec/content-types/main-policy/hub/index.md
Labels: tag: new feature

#1401 docs: document search CT - INNO-1952
  src/website/src/pages/ec/content-types/search/docs/usage.md
  src/website/src/pages/ec/content-types/search/docs/usage.mdx
Labels: tag: documentation

#1375 feat(main-policy-resources): add content type - INNO-1879
  src/systems/ec/implementations/react/templates/pages/main-policy-resources/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-resources/index.js
  src/systems/ec/implementations/react/templates/pages/main-policy-resources/package.json
  src/systems/ec/implementations/react/templates/pages/main-policy-resources/src/MainPolicyResourcesPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-resources/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-social-media-share/ec-component-social-media-share.scss
  src/systems/ec/specs/templates/main-policy-resources-page/demo/data.js
  src/systems/ec/specs/templates/main-policy-resources-page/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-social-media-share/eu-component-social-media-share.scss
  src/website/src/pages/ec/content-types/main-policy/resources/docs/code.mdx
  src/website/src/pages/ec/content-types/main-policy/resources/docs/usage.mdx
  src/website/src/pages/ec/content-types/main-policy/resources/index.md
Labels: tag: new feature

#1370 feat(main-policy-background): add content type - INNO-1879
  src/systems/ec/implementations/react/templates/pages/main-policy-background/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-background/index.js
  src/systems/ec/implementations/react/templates/pages/main-policy-background/package.json
  src/systems/ec/implementations/react/templates/pages/main-policy-background/src/MainPolicyBackgroundPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-background/stories/Index.jsx
  src/systems/ec/specs/templates/main-policy-background-page/demo/data.js
  src/systems/ec/specs/templates/main-policy-background-page/package.json
  src/website/src/pages/ec/content-types/main-policy/background/docs/code.mdx
  src/website/src/pages/ec/content-types/main-policy/background/docs/usage.mdx
  src/website/src/pages/ec/content-types/main-policy/background/index.md
Labels: tag: new feature

#1371 feat(main-policy-legislation): add content type - INNO-1879
  src/systems/ec/implementations/react/templates/pages/main-policy-legislation/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-legislation/index.js
  src/systems/ec/implementations/react/templates/pages/main-policy-legislation/package.json
  src/systems/ec/implementations/react/templates/pages/main-policy-legislation/src/MainPolicyLegislationPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-legislation/stories/Index.jsx
  src/systems/ec/specs/templates/main-policy-legislation-page/demo/data.js
  src/systems/ec/specs/templates/main-policy-legislation-page/package.json
  src/website/src/pages/ec/content-types/main-policy/index.md
  src/website/src/pages/ec/content-types/policy/awareness/docs/code.mdx
  src/website/src/pages/ec/content-types/policy/awareness/docs/usage.mdx
  src/website/src/pages/ec/content-types/policy/awareness/index.md
  src/website/src/pages/ec/content-types/policy/background/docs/code.mdx
  src/website/src/pages/ec/content-types/policy/background/docs/usage.mdx
  src/website/src/pages/ec/content-types/policy/background/index.md
  src/website/src/pages/ec/content-types/policy/evaluation/docs/code.mdx
  src/website/src/pages/ec/content-types/policy/evaluation/docs/usage.mdx
  src/website/src/pages/ec/content-types/policy/evaluation/index.md
  src/website/src/pages/ec/content-types/policy/hub/docs/code.mdx
  src/website/src/pages/ec/content-types/policy/hub/docs/usage.mdx
  src/website/src/pages/ec/content-types/policy/hub/index.md
  src/website/src/pages/ec/content-types/policy/index.md
  src/website/src/pages/ec/content-types/policy/legislation/docs/code.mdx
  src/website/src/pages/ec/content-types/policy/legislation/docs/usage.mdx
  src/website/src/pages/ec/content-types/policy/legislation/index.md
  src/website/src/pages/ec/content-types/policy/resources/docs/code.mdx
  src/website/src/pages/ec/content-types/policy/resources/docs/usage.mdx
  src/website/src/pages/ec/content-types/policy/resources/index.md
Labels: tag: new feature

#1403 fix(footers): set default rules - INNO -1955
  src/systems/ec/implementations/vanilla/packages/ec-component-footer-core/ec-component-footer-core.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-footer-harmonised/ec-component-footer-harmonised.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-footer-standardised/ec-component-footer-standardised.scss
Labels: tag: enhancement

#1404 fix(inpage-nav): remove sticky nav when out of viewport - INNO-…
  src/systems/ec/implementations/react/components/inpage-navigation/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/content-page/src/ContentPage.jsx
  src/systems/ec/implementations/react/templates/pages/funding-programme/src/FundingProgrammePage.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-inpage-navigation/ec-component-inpage-navigation.js
  src/systems/eu/implementations/react/components/inpage-navigation/examples/Default.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-inpage-navigation/eu-component-inpage-navigation.js
  src/website/src/pages/ec/components/navigation/inpage-navigation/docs/code.mdx
Labels: process: under review, tag: bug fix

#1409 docs(storybook): deprecate content page - INNO-1964
  src/systems/ec/implementations/react/templates/pages/content-page/stories/Index.jsx
Labels: tag: documentation

#1410 chore(deps): update dependencies - INNO-1811
  .prettierignore
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  patches/@storybook+addon-a11y+5.2.6.patch
  patches/@storybook+addon-cssresources+5.2.6.patch
  src/systems/ec/implementations/react/components/breadcrumb-harmonised/index.js
  src/systems/ec/implementations/react/components/breadcrumb-standardised/index.js
  src/systems/ec/implementations/react/components/description-list/package.json
  src/systems/ec/implementations/react/components/dropdown-legacy/package.json
  src/systems/ec/implementations/react/components/ordered-list/package.json
  src/systems/ec/implementations/react/components/page-header-core/package.json
  src/systems/ec/implementations/react/components/page-header-harmonised/package.json
  src/systems/ec/implementations/react/components/page-header-standardised/package.json
  src/systems/ec/implementations/react/components/table/package.json
  src/systems/ec/implementations/react/components/timeline/package.json
  src/systems/ec/implementations/react/components/timeline2/package.json
  src/systems/ec/implementations/react/components/unordered-list/package.json
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/eu/implementations/react/components/description-list/package.json
  src/systems/eu/implementations/react/components/dropdown-legacy/package.json
  src/systems/eu/implementations/react/components/ordered-list/package.json
  src/systems/eu/implementations/react/components/table/package.json
  src/systems/eu/implementations/react/components/timeline/package.json
  src/systems/eu/implementations/react/components/timeline2/package.json
  src/systems/eu/implementations/react/components/unordered-list/package.json
  src/systems/eu/implementations/react/storybook/package.json
  src/tools/builder/package.json
  src/tools/story-wrapper/package.json
  src/tools/storybook-addon-code/package.json
  src/website/package.json
  src/website/src/components/SplashPage/SplashPage.jsx
  src/website/src/pages/ec/components/message/docs/code.mdx
  src/website/src/website-components/Anatomy/Anatomy.jsx
  src/website/src/website-components/Playground.jsx
  yarn.lock
Labels: process: review needed, tag: internal

#1413 docs(utilities): dimension and display - INNO-1947
  src/systems/ec/implementations/react/utilities/dimension/stories/Index.jsx
  src/systems/ec/implementations/react/utilities/display/stories/Index.jsx
  src/website/src/pages/ec/utilities/border/docs/usage.mdx
  src/website/src/pages/ec/utilities/dimension/docs/usage.mdx
  src/website/src/pages/ec/utilities/dimension/index.md
  src/website/src/pages/ec/utilities/display/docs/usage.mdx
  src/website/src/pages/ec/utilities/display/index.md
Labels: process: under review, tag: documentation

#1405 feat(call-proposal): add content type - INNO-1956
  src/systems/ec/implementations/react/templates/pages/call-proposals/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/call-proposals/index.js
  src/systems/ec/implementations/react/templates/pages/call-proposals/package.json
  src/systems/ec/implementations/react/templates/pages/call-proposals/src/CallProposalsPage.jsx
  src/systems/ec/implementations/react/templates/pages/call-proposals/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-inpage-navigation/ec-component-inpage-navigation.js
  src/systems/ec/specs/templates/call-proposals-page/demo/data.js
  src/systems/ec/specs/templates/call-proposals-page/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-inpage-navigation/eu-component-inpage-navigation.js
  src/website/src/pages/ec/content-types/call/index.md
  src/website/src/pages/ec/content-types/call/proposals/docs/code.mdx
  src/website/src/pages/ec/content-types/call/proposals/docs/usage.mdx
  src/website/src/pages/ec/content-types/call/proposals/index.md
Labels: tag: new feature

#1406 feat(call-tenders): add content type - INNO-1957
  src/systems/ec/implementations/react/templates/pages/call-tenders/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/call-tenders/index.js
  src/systems/ec/implementations/react/templates/pages/call-tenders/package.json
  src/systems/ec/implementations/react/templates/pages/call-tenders/src/CallTendersPage.jsx
  src/systems/ec/implementations/react/templates/pages/call-tenders/stories/Index.jsx
  src/systems/ec/specs/templates/call-tenders-page/demo/data.js
  src/systems/ec/specs/templates/call-tenders-page/package.json
  src/website/src/pages/ec/content-types/call/tenders/docs/code.mdx
  src/website/src/pages/ec/content-types/call/tenders/docs/usage.mdx
  src/website/src/pages/ec/content-types/call/tenders/index.md
Labels: tag: new feature

#1360 feat(ecl-editor): add editor CSS rules - INNO-1846
  docs/decisions/003-editor.md
  scripts/dist-presets.sh
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/implementations/react/utilities/editor/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-blockquote/_mixins.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-blockquote/ec-component-blockquote--editor.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-blockquote/ec-component-blockquote.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-link/_mixins.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-link/ec-component-link--editor.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-link/ec-component-link-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-link/ec-component-link.scss
  src/systems/ec/implementations/vanilla/packages/ec-editor/README.md
  src/systems/ec/implementations/vanilla/packages/ec-editor/_ec-editor--blockquote.scss
  src/systems/ec/implementations/vanilla/packages/ec-editor/_ec-editor--button.scss
  src/systems/ec/implementations/vanilla/packages/ec-editor/_ec-editor--link.scss
  src/systems/ec/implementations/vanilla/packages/ec-editor/_ec-editor--list.scss
  src/systems/ec/implementations/vanilla/packages/ec-editor/_ec-editor--table.scss
  src/systems/ec/implementations/vanilla/packages/ec-editor/_ec-editor--typography.scss
  src/systems/ec/implementations/vanilla/packages/ec-editor/ec-editor.scss
  src/systems/ec/implementations/vanilla/packages/ec-editor/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-editor/.npmignore
  src/systems/ec/implementations/vanilla/packages/ec-preset-editor/README.md
  src/systems/ec/implementations/vanilla/packages/ec-preset-editor/ecl-builder.config.js
  src/systems/ec/implementations/vanilla/packages/ec-preset-editor/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-editor/src/ec-preset-editor.scss
  src/website/scripts/copy.sh
Labels: tag: new feature

#1411 chore(drone): deploy v1 to europa domain - INNO-1918
  .drone.yml
  package.json
  scripts/deploy.sh
  yarn.lock
Labels: tag: internal

#1416 fix(site-header): add separator - INNO-1965
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-harmonised/ec-component-site-header-harmonised.scss
Labels: tag: enhancement

#1414 chore(drone): update configuration - INNO-1918
  .drone.yml
  package.json
  scripts/set-netlify-deployment-status.js
  yarn.lock
Labels: tag: internal

#1418 chore(drone): update configuration - INNO-1918
  .drone.yml
Labels: tag: internal

#1419 chore(drone): use wget for website preparation - INNO-1918
  .drone.yml
Labels: tag: internal

#1407 docs(api): integrate JSDoc into website - INNO-1961
  .drone.yml
  .gitignore
  .prettierignore
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  scripts/audit.sh
  src/systems/ec/implementations/vanilla/packages/ec-component-accordion2/ec-component-accordion2.js
  src/systems/ec/implementations/vanilla/packages/ec-component-breadcrumb/ec-component-breadcrumb.js
  src/systems/ec/implementations/vanilla/packages/ec-component-contextual-navigation/ec-component-contextual-navigation.js
  src/systems/ec/implementations/vanilla/packages/ec-component-dropdown-legacy/ec-component-dropdown-legacy.js
  src/systems/ec/implementations/vanilla/packages/ec-component-expandable/ec-component-expandable.js
  src/systems/ec/implementations/vanilla/packages/ec-component-file/ec-component-file.js
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/ec-component-gallery.js
  src/systems/ec/implementations/vanilla/packages/ec-component-inpage-navigation/ec-component-inpage-navigation.js
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-legacy/ec-component-menu-legacy.js
  src/systems/ec/implementations/vanilla/packages/ec-component-message/ec-component-message.js
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-core/ec-component-site-header-core.js
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-standardised/ec-component-site-header-standardised.js
  src/systems/ec/implementations/vanilla/packages/ec-component-timeline2/ec-component-timeline2.js
  src/tools/builder/package.json
  src/website/package.json
  src/website/scripts/docs.js
  src/website/src/pages/ec/components/accordion/docs/api.mdx
  src/website/src/pages/ec/components/accordion/docs/code.mdx
  src/website/src/pages/ec/components/dropdown-legacy/docs/api.mdx
  src/website/src/pages/ec/components/dropdown-legacy/docs/code.mdx
  src/website/src/pages/ec/components/expandable/docs/api.mdx
  src/website/src/pages/ec/components/expandable/docs/code.mdx
  src/website/src/pages/ec/components/file/docs/api.mdx
  src/website/src/pages/ec/components/file/docs/code.mdx
  src/website/src/pages/ec/components/media/gallery/docs/api.mdx
  src/website/src/pages/ec/components/media/gallery/docs/code.mdx
  src/website/src/pages/ec/components/message/docs/api.mdx
  src/website/src/pages/ec/components/message/docs/code.mdx
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/api.mdx
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/code.mdx
  src/website/src/pages/ec/components/navigation/contextual-navigation/docs/api.mdx
  src/website/src/pages/ec/components/navigation/contextual-navigation/docs/code.mdx
  src/website/src/pages/ec/components/navigation/inpage-navigation/docs/api.mdx
  src/website/src/pages/ec/components/navigation/inpage-navigation/docs/code.mdx
  src/website/src/pages/ec/components/navigation/menu-legacy/docs/api.mdx
  src/website/src/pages/ec/components/timeline/docs/api.mdx
  src/website/src/pages/ec/components/timeline/docs/code.mdx
  src/website/src/pages/ec/core-template/site-header/docs/api.mdx
  src/website/src/pages/ec/standardised-template/site-header/docs/api.mdx
  src/website/src/preval/get-meta-ec.js
  yarn.lock
Labels: tag: documentation

#1412 feat(event): allow to select template - INNO-1963
  src/systems/ec/implementations/react/templates/pages/event-agenda/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/event-agenda/package.json
  src/systems/ec/implementations/react/templates/pages/event-agenda/src/EventAgendaPage.jsx
  src/systems/ec/implementations/react/templates/pages/event-agenda/stories/Index.jsx
  src/systems/ec/implementations/react/templates/pages/event-detail/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/event-detail/package.json
  src/systems/ec/implementations/react/templates/pages/event-detail/src/EventDetailPage.jsx
  src/systems/ec/implementations/react/templates/pages/event-detail/stories/Index.jsx
  src/systems/ec/implementations/react/templates/pages/event-speaker/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/event-speaker/package.json
  src/systems/ec/implementations/react/templates/pages/event-speaker/src/EventSpeakerPage.jsx
  src/systems/ec/implementations/react/templates/pages/event-speaker/stories/Index.jsx
  src/systems/ec/specs/templates/event-agenda-page/demo/data.js
  src/systems/ec/specs/templates/event-agenda-page/package.json
  src/systems/ec/specs/templates/event-detail-page/demo/data.js
  src/systems/ec/specs/templates/event-detail-page/package.json
  src/systems/ec/specs/templates/event-speaker-page/demo/data.js
  src/systems/ec/specs/templates/event-speaker-page/package.json
Labels: tag: enhancement

#1422 fix(site-header): fix spacing - INNO-1971
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-harmonised/ec-component-site-header-harmonised.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-standardised/ec-component-site-header-standardised.scss
Labels: tag: bug fix

#1424 chore(ci): use fetch --depth arg
  .drone.yml
Labels: process: under review, tag: internal

#1425 fix(content-types): fix for global rules - INNO-1954
  src/systems/ec/implementations/react/templates/pages/call-proposals/src/CallProposalsPage.jsx
  src/systems/ec/implementations/react/templates/pages/call-tenders/src/CallTendersPage.jsx
  src/systems/ec/implementations/react/templates/pages/event-agenda/src/EventAgendaPage.jsx
  src/systems/ec/implementations/react/templates/pages/event-detail/src/EventDetailPage.jsx
  src/systems/ec/implementations/react/templates/pages/event-speaker/src/EventSpeakerPage.jsx
  src/systems/ec/implementations/react/templates/pages/funding-programme/src/FundingProgrammePage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-awareness/src/MainPolicyAwarenessPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-background/src/MainPolicyBackgroundPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-evaluation/src/MainPolicyEvaluationPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-hub/src/MainPolicyHubPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-legislation/src/MainPolicyLegislationPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-resources/src/MainPolicyResourcesPage.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-hero-banner/ec-component-hero-banner.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-page-banner/ec-component-page-banner.scss
Labels: process: review needed, tag: enhancement

#1427 chore(website): attempt to solve infrastructure mishaps - INNO-1979
  .drone.yml
  package.json
  scripts/prepare-europa-hosting.js
  tools/ec-styleguide/theme-overrides/partials/footer_links.nunj
  tools/ec-styleguide/theme-overrides/partials/header_breadcrumb.nunj
  tools/eu-styleguide/theme-overrides/partials/footer_links.nunj
  tools/eu-styleguide/theme-overrides/partials/header_breadcrumb.nunj
  yarn.lock
Labels: process: review needed, tag: internal

#1429 fix(site-header-harmonised): update logo size and position - INNO-1980
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-harmonised/ec-component-site-header-harmonised.scss
Labels: process: review needed, tag: enhancement

#1423 refactor(drone): preview - INNO-1975
  .drone.yml
  scripts/set-netlify-deployment-status.js
Labels: tag: internal

#1421 feat(site-header-core): add login - INNO-1970
  src/systems/ec/implementations/react/components/site-header-core/package.json
  src/systems/ec/implementations/react/components/site-header-core/src/SiteHeaderCore.jsx
  src/systems/ec/implementations/react/components/site-header-core/stories/Index.jsx
  src/systems/ec/implementations/react/components/site-header-harmonised/src/SiteHeaderHarmonised.jsx
  src/systems/ec/implementations/react/components/site-header-standardised/src/SiteHeaderStandardised.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-core/ec-component-site-header-core.js
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-core/ec-component-site-header-core.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-standardised/ec-component-site-header-standardised.scss
  src/systems/ec/specs/components/site-header-core/demo/data--en.js
  src/systems/ec/specs/components/site-header-core/demo/data--fr.js
  src/website/src/pages/ec/core-template/index.mdx
  src/website/src/pages/ec/core-template/site-header/docs/code.mdx
  src/website/src/pages/ec/core-template/site-header/docs/usage.mdx
Labels: tag: new feature

#1431 feat(form-errors): add new colour on hover - INNO-1983
  src/systems/ec/design-tokens/tokens/colors.yml
  src/systems/ec/implementations/vanilla/packages/ec-component-form-checkbox/ec-component-form-checkbox.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-radio/ec-component-form-radio.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-select/ec-component-form-select.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-text-area/ec-component-form-text-area.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-text-input/ec-component-form-text-input.scss
  src/systems/ec/themes/default/aliases/colors.yml
  src/systems/eu/design-tokens/tokens/colors.yml
  src/systems/eu/implementations/vanilla/packages/eu-component-form-checkbox/eu-component-form-checkbox.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-form-radio/eu-component-form-radio.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-form-select/eu-component-form-select.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-form-text-area/eu-component-form-text-area.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-form-text-input/eu-component-form-text-input.scss
  src/systems/eu/themes/default/aliases/colors.yml
Labels: process: review needed, tag: enhancement

#1433 fix(site-headers): fix logo size on IE11
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-core/ec-component-site-header-core.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-harmonised/ec-component-site-header-harmonised.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-standardised/ec-component-site-header-standardised.scss
Labels: tag: bug fix

#1434 docs: rename contextual navigation - INNO-1986
  src/generic/generic-component-context-nav/README.md
  src/generic/generic-component-context-nav/data/demo.js
  src/generic/generic-component-context-nav/generic-component-context-nav.scss
  src/generic/generic-component-context-nav/package.json
  src/systems/ec/ec-component/ec-component-context-nav/README.md
  src/systems/ec/ec-component/ec-component-context-nav/ec-component-context-nav.config.js
  src/systems/ec/ec-component/ec-component-context-nav/ec-component-context-nav.js
  src/systems/ec/ec-component/ec-component-context-nav/ec-component-context-nav.scss
  src/systems/ec/ec-component/ec-component-context-nav/package.json
  src/systems/ec/ec-component/ec-component-context-nav/test/spec/screenshots/reference/context-navs/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-context-nav/test/spec/screenshots/reference/context-navs/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-context-nav/test/spec/screenshots/reference/context-navs/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-context-nav/test/spec/screenshots/reference/context-navs/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-context-nav/README.md
  src/systems/eu/eu-component/eu-component-context-nav/eu-component-context-nav.config.js
  src/systems/eu/eu-component/eu-component-context-nav/eu-component-context-nav.js
  src/systems/eu/eu-component/eu-component-context-nav/eu-component-context-nav.scss
  src/systems/eu/eu-component/eu-component-context-nav/package.json
  src/systems/eu/eu-component/eu-component-context-nav/test/spec/screenshots/reference/context-navs/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-context-nav/test/spec/screenshots/reference/context-navs/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-context-nav/test/spec/screenshots/reference/context-navs/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-context-nav/test/spec/screenshots/reference/context-navs/macOS 10.12_Safari_v11.png
Labels: process: review needed, tag: documentation

#1436 chore: setup internal redirects - INNO-1941
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  src/website/src/routes/MainRoutes.jsx
  src/website/src/routes/Redirects.jsx
Labels: tag: internal
