Repository ec-europa/europa-component-library, pull requests merged in 2019-04, with the labels that each got.

#1058 fix(label): fix width on mobile - INNO-1421
  src/generic/generic-component-field/generic-component-field.scss
Labels: tag: bug fix

#1060 refactor(table): set table-layout to auto - INNO-1425
  src/generic/generic-component-table/_mixins.scss
Labels: process: under review, tag: enhancement

#1062 feat(radio): add checked parameter - INNO-1430
  src/systems/ec/implementations/react/packages/radio/src/RadioButton.jsx
  src/systems/ec/specs/components/radio/demo/data--binary-invalid.js
  src/systems/ec/specs/components/radio/demo/data--binary.js
  src/systems/ec/specs/components/radio/demo/data--default.js
  src/systems/ec/specs/components/radio/demo/data--invalid.js
  src/systems/eu/implementations/react/packages/radio/src/RadioButton.jsx
  src/systems/eu/specs/components/radio/demo/data--binary-invalid.js
  src/systems/eu/specs/components/radio/demo/data--binary.js
  src/systems/eu/specs/components/radio/demo/data--default.js
  src/systems/eu/specs/components/radio/demo/data--invalid.js
Labels: process: review needed, tag: enhancement

#1061 refactor(table): update screenshots - INNO-1425
  .pullapprove.yml
  README.md
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/colspan-empty-enhanced/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/colspan-empty-enhanced/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/colspan-empty-enhanced/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/colspan-empty-enhanced/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/colspan-empty/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/colspan-empty/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/colspan-empty/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/colspan-empty/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/colspan-enhanced/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/colspan-enhanced/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/colspan-enhanced/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/colspan-enhanced/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/colspan/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/colspan/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/colspan/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/colspan/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/default-enhanced/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/default-enhanced/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/default-enhanced/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/default-enhanced/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/default/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/default/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/default/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/default/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/empty-enhanced/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/empty-enhanced/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/empty-enhanced/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/empty-enhanced/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/empty/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/empty/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/empty/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-table/test/spec/screenshots/reference/tables/desktop/empty/macOS 10.12_Safari_v11.png
Labels: tag: internal

#1065 docs(list): rephrase definition
  src/website/src/pages/ec/components/list/docs/usage.mdx
Labels: tag: documentation

#1064 feat(colors): add ECL Blue 5 - INNO-1431
  src/generic/generic-base/variables/_colors.scss
  src/systems/ec/ec-component/ec-component-navigation/ec-component-navigation-menu/test/spec/screenshots/reference/navigation/menus/mobile-open/Windows 7_Firefox_v54.png
  src/systems/ec/ec-style/ec-style-color/README.md
  src/systems/ec/ec-style/ec-style-color/colors.json
  src/systems/ec/ec-style/ec-style-color/test/spec/screenshots/reference/colors/Windows 10_Chrome_v60.png
  src/systems/ec/ec-style/ec-style-color/test/spec/screenshots/reference/colors/Windows 7_Firefox_v54.png
  src/systems/ec/ec-style/ec-style-color/test/spec/screenshots/reference/colors/Windows 7_IE_v11.png
  src/systems/ec/ec-style/ec-style-color/test/spec/screenshots/reference/colors/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/mobile/Windows 10_Chrome_v60.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/mobile/Windows 7_Firefox_v54.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/mobile/Windows 7_IE_v11.png
  src/systems/ec/ec-template/ec-template-search/test/spec/screenshots/reference/templates-search/mobile/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-utility/ec-utility-colorize/ec-utility-colorize.twig
  src/systems/ec/ec-utility/ec-utility-colorize/test/spec/screenshots/reference/colorize/Windows 10_Chrome_v60.png
  src/systems/ec/ec-utility/ec-utility-colorize/test/spec/screenshots/reference/colorize/Windows 7_Firefox_v54.png
  src/systems/ec/ec-utility/ec-utility-colorize/test/spec/screenshots/reference/colorize/Windows 7_IE_v11.png
  src/systems/ec/ec-utility/ec-utility-colorize/test/spec/screenshots/reference/colorize/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/colspan-empty-enhanced/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/colspan-empty-enhanced/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/colspan-empty-enhanced/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/colspan-empty-enhanced/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/colspan-empty/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/colspan-empty/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/colspan-empty/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/colspan-empty/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/colspan-enhanced/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/colspan-enhanced/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/colspan-enhanced/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/colspan-enhanced/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/colspan/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/colspan/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/colspan/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/colspan/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/default-enhanced/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/default-enhanced/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/default-enhanced/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/default-enhanced/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/default/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/default/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/default/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/default/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/empty-enhanced/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/empty-enhanced/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/empty-enhanced/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/empty-enhanced/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/empty/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/empty/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/empty/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-table/test/spec/screenshots/reference/tables/desktop/empty/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-style/eu-style-color/README.md
  src/systems/eu/eu-style/eu-style-color/colors.json
  src/systems/eu/eu-style/eu-style-color/test/spec/screenshots/reference/colors/Windows 10_Chrome_v60.png
  src/systems/eu/eu-style/eu-style-color/test/spec/screenshots/reference/colors/Windows 7_Firefox_v54.png
  src/systems/eu/eu-style/eu-style-color/test/spec/screenshots/reference/colors/Windows 7_IE_v11.png
  src/systems/eu/eu-style/eu-style-color/test/spec/screenshots/reference/colors/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-utility/eu-utility-colorize/eu-utility-colorize.twig
  src/systems/eu/eu-utility/eu-utility-colorize/test/spec/screenshots/reference/colorize/Windows 10_Chrome_v60.png
  src/systems/eu/eu-utility/eu-utility-colorize/test/spec/screenshots/reference/colorize/Windows 7_Firefox_v54.png
  src/systems/eu/eu-utility/eu-utility-colorize/test/spec/screenshots/reference/colorize/Windows 7_IE_v11.png
  src/systems/eu/eu-utility/eu-utility-colorize/test/spec/screenshots/reference/colorize/macOS 10.12_Safari_v11.png
Labels: process: under review, tag: new feature

#1063 fix(gallery): prevent body scroll - INNO-1428
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/ec-component-gallery.js
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/ec-component-gallery.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-gallery/eu-component-gallery.js
  src/systems/eu/implementations/vanilla/packages/eu-component-gallery/eu-component-gallery.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-gallery/package.json
Labels: tag: bug fix

#1066 fix(deps): fix cyclic dependencies - no issue
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography-paragraph/package.json
Labels: tag: bug fix

#1067 chore: update dependencies - no issue
  .eslintrc.js
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  src/systems/ec/implementations/react/.eslintrc.js
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/implementations/react/templates/campaign-page/package.json
  src/systems/ec/implementations/react/templates/standard-page/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/package.json
  src/systems/ec/specs/.eslintrc.js
  src/systems/eu/implementations/react/.eslintrc.js
  src/systems/eu/implementations/react/storybook/package.json
  src/systems/eu/implementations/react/templates/campaign-page/package.json
  src/systems/eu/implementations/react/templates/standard-page/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-gallery/package.json
  src/systems/eu/specs/.eslintrc.js
  src/tools/builder/package.json
  src/tools/story-wrapper/.eslintrc.js
  src/tools/story-wrapper/package.json
  src/tools/website-components/.eslintrc.js
  src/tools/website-components/package.json
  src/website/.eslintrc.js
  src/website/package.json
  src/website/src/routes/Ec.jsx
  src/website/src/routes/Eu.jsx
  yarn.lock
Labels: process: under review, tag: internal

#1069 refactor(browserslist): change browsers coverage - INNO-1434
  browserslist
  examples/webpack3/package.json
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  src/generic/generic-component-inpage-navigation/package.json
  src/generic/generic-component-side-navigation/package.json
  src/systems/ec/ec-component/ec-component-file/package.json
  src/systems/ec/ec-component/ec-component-link/package.json
  src/systems/ec/ec-component/ec-component-navigation/ec-component-inpage-navigation/package.json
  src/systems/ec/ec-component/ec-component-navigation/ec-component-side-navigation/package.json
  src/systems/ec/ec-preset/ec-preset-base/package.json
  src/systems/ec/ec-preset/ec-preset-corporate/package.json
  src/systems/ec/ec-preset/ec-preset-full/package.json
  src/systems/ec/ec-preset/ec-preset-website/package.json
  src/systems/ec/ec-preset/ec-preset-webtools/package.json
  src/systems/ec/ec-style/ec-style-icon/package.json
  src/systems/eu/eu-component/eu-component-file/package.json
  src/systems/eu/eu-component/eu-component-link/package.json
  src/systems/eu/eu-component/eu-component-navigation/eu-component-inpage-navigation/package.json
  src/systems/eu/eu-component/eu-component-navigation/eu-component-side-navigation/package.json
  src/systems/eu/eu-preset/eu-preset-base/package.json
  src/systems/eu/eu-preset/eu-preset-corporate/package.json
  src/systems/eu/eu-preset/eu-preset-full/package.json
  src/systems/eu/eu-preset/eu-preset-website/package.json
  src/systems/eu/eu-preset/eu-preset-webtools/package.json
  src/systems/eu/eu-style/eu-style-icon/package.json
  tools/ec-styleguide/package.json
  tools/eu-styleguide/package.json
  tools/fractal-theme/assets/scss/components/_pen.scss
  tools/fractal-theme/package.json
  tools/fractal-theme/src/theme.js
  tools/fractal-twig/package.json
  tools/fractal-twig/src/adapter.js
  yarn.lock
Labels: tag: enhancement

#1073 docs(usage-wo2): add documentation pages from v2 to v2-dev
  src/website/src/pages/ec/components/banners/hero-banner/docs/usage.md
  src/website/src/pages/ec/components/banners/hero-banner/docs/usage.mdx
  src/website/src/pages/ec/components/banners/page-banner/docs/usage.md
  src/website/src/pages/ec/components/banners/page-banner/docs/usage.mdx
  src/website/src/pages/ec/components/tag/docs/code.mdx
  src/website/src/pages/ec/components/tag/docs/usage.md
  src/website/src/pages/ec/components/tag/docs/usage.mdx
  src/website/src/pages/ec/page-structure/footer/docs/usage.md
  src/website/src/pages/ec/page-structure/footer/docs/usage.mdx
  src/website/src/pages/ec/page-structure/site-header/docs/usage.md
  src/website/src/pages/ec/page-structure/site-header/docs/usage.mdx
Labels: tag: documentation

#1074 fix(logo): fix typo in EU SV logo - INNO-1435
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--sv.svg
  src/systems/eu/eu-component/eu-component-logo/test/spec/screenshots/reference/logos/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-logo/test/spec/screenshots/reference/logos/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-logo/test/spec/screenshots/reference/logos/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-logo/test/spec/screenshots/reference/logos/macOS 10.12_Safari_v11.png
Labels: tag: bug fix

#1072 fix(logo): fix typo in EU SV logo - INNO-1435
  src/systems/eu/resources/logo/logo--sv.svg
Labels: tag: bug fix

#1077 fix(language-list): fix demo code and logo alt - no issue
  src/systems/eu/specs/components/language-list/demo/data--splash.js
  src/website/src/pages/ec/page-structure/language-list/docs/code.mdx
  src/website/src/pages/eu/page-structure/language-list/docs/code.mdx
Labels: tag: bug fix

#1079 fix(website): fix "getting started" display - INNO-1439
  src/website/src/components/DocPage/DocPage.jsx
  src/website/src/pages/ec/getting-started/index.md
Labels: tag: bug fix

#1081 refactor(eu-logo): use latest logo - INNO-1442
  scripts/utils/getUpdatedPackages.js
  src/systems/eu/eu-component/eu-component-logo/images/logo.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--bg.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--cs.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--da.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--de.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--el.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--en.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--es.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--et.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--fi.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--fr.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--ga.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--hr.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--hu.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--it.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--lt.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--lv.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--mt.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--nl.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--pl.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--pt.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--ro.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--sk.svg
  src/systems/eu/eu-component/eu-component-logo/images/logo/logo--sl.svg
  src/systems/eu/eu-component/eu-component-logo/test/spec/screenshots/reference/logos/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-logo/test/spec/screenshots/reference/logos/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-logo/test/spec/screenshots/reference/logos/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-logo/test/spec/screenshots/reference/logos/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-component/eu-component-site-header/test/spec/screenshots/reference/site-headers/Windows 10_Chrome_v60.png
  src/systems/eu/eu-component/eu-component-site-header/test/spec/screenshots/reference/site-headers/Windows 7_Firefox_v54.png
  src/systems/eu/eu-component/eu-component-site-header/test/spec/screenshots/reference/site-headers/Windows 7_IE_v11.png
  src/systems/eu/eu-component/eu-component-site-header/test/spec/screenshots/reference/site-headers/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-community/test/spec/screenshots/reference/community/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/simple/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/simple/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/simple/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/simple/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/with-menu/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/with-menu/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/with-menu/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-page/test/spec/screenshots/reference/pages/with-menu/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-search/test/spec/screenshots/reference/templates-search/macOS 10.12_Safari_v11.png
Labels: tag: enhancement

#1082 fix(footer): remove empty tags - INNO-1383
  src/systems/ec/ec-component/ec-component-footer/ec-component-footer.twig
  src/systems/eu/eu-component/eu-component-footer/eu-component-footer.twig
Labels: tag: bug fix

#1084 docs: remove wiki links - INNO-1441
  src/generic/generic-component-listing/README.md
  src/generic/generic-utility-font-size/README.md
  src/systems/ec/ec-component/ec-component-listing/README.md
  src/systems/ec/ec-utility/ec-utility-font-size/README.md
  src/systems/eu/eu-component/eu-component-listing/README.md
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/Windows 10_Chrome_v60.png
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/Windows 7_Firefox_v54.png
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/Windows 7_IE_v11.png
  src/systems/eu/eu-template/eu-template-listing/test/spec/screenshots/reference/templates-listings/macOS 10.12_Safari_v11.png
  src/systems/eu/eu-utility/eu-utility-font-size/README.md
Labels: tag: documentation

#1083 fix(buttons): remove "button" appearance - INNO-1280
  src/generic/generic-component-button/generic-component-button.scss
Labels: process: under review, tag: bug fix

#1085 fix(buttons): remove appearance - INNO-1280
  src/systems/ec/implementations/vanilla/packages/ec-component-button/ec-component-button.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-button/eu-component-button.scss
Labels: process: under review, tag: bug fix

#1086 chore: update dependencies - no issue
  docs/07-developers.md
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/resources/icons/package.json
  src/systems/ec/resources/social-icons/package.json
  src/systems/eu/implementations/react/storybook/package.json
  src/systems/eu/resources/icons/package.json
  src/systems/eu/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  src/website/src/App.jsx
  src/website/src/components/Navigation/LinkGroup.jsx
  src/website/src/components/Navigation/LinkList.jsx
  src/website/src/components/Navigation/LinkSection.jsx
  src/website/webpack.config.dev.js
  src/website/webpack.config.prod.js
  yarn.lock
Labels: process: under review, tag: internal

#1089 fix(dialog-wide): use overflow: auto by default - INNO-1447
  src/generic/generic-component-dialog/generic-component-dialog.scss
Labels: process: under review, tag: bug fix

#1090 chore: show how to use the CDN - INNO-1448
  .drone.yml
  README.md
  examples/cdn/README.md
  examples/cdn/package.json
  examples/cdn/www/index.html
Labels: tag: internal

#1091 feat(ecl-editor): enhance ECL Editor helper - INNO-1446
  src/generic/generic-component-blockquote/generic-component-blockquote--editor.scss
  src/generic/generic-component-table/generic-component-table--editor.scss
  src/generic/generic-style-image/generic-style-image--editor.scss
  src/generic/generic-style-typography-paragraph/generic-style-typography-paragraph--editor.scss
  src/systems/ec/ec-preset/ec-preset-full/_imports.scss
  src/systems/ec/ec-style/ec-style-image/ec-style-image--editor.scss
  src/systems/ec/ec-utility/ec-editor/README.md
  src/systems/ec/ec-utility/ec-editor/ec-editor.config.js
  src/systems/ec/ec-utility/ec-editor/ec-editor.twig
  src/systems/eu/eu-preset/eu-preset-full/_imports.scss
  src/systems/eu/eu-style/eu-style-image/eu-style-image--editor.scss
  src/systems/eu/eu-utility/eu-editor/README.md
  src/systems/eu/eu-utility/eu-editor/eu-editor.config.js
  src/systems/eu/eu-utility/eu-editor/eu-editor.twig
Labels: tag: enhancement

#1093 chore: update dependencies - no issue
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/resources/icons/package.json
  src/systems/ec/resources/social-icons/package.json
  src/systems/eu/implementations/react/storybook/package.json
  src/systems/eu/resources/icons/package.json
  src/systems/eu/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: process: under review, tag: internal

#1094 docs: update "getting started" - INNO-1449
  src/website/src/pages/ec/getting-started/index.md
  src/website/src/pages/eu/getting-started/index.md
Labels: process: under review, tag: documentation

#1068 feat(print): add print styles - INNO-1432
  src/systems/ec/design-tokens/tokens/icons.yml
  src/systems/ec/design-tokens/tokens/spacing.yml
  src/systems/ec/design-tokens/tokens/typography.yml
  src/systems/ec/implementations/react/storybook/.storybook/ECL.jsx
  src/systems/ec/implementations/react/storybook/.storybook/preview-head.html
  src/systems/ec/implementations/vanilla/packages/ec-base/mixins/_hidden-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-base/mixins/index.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-accordion/ec-component-accordion-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-breadcrumb/ec-component-breadcrumb-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-button/ec-component-button-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-card/ec-component-card-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-footer/ec-component-footer-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-icon/ec-component-icon-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-link/ec-component-link-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-media-container/ec-component-media-container-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-page-header/ec-component-page-header-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-search-form/ec-component-search-form-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header/ec-component-site-header-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-site-switcher/ec-component-site-switcher-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-site-switcher/ec-component-site-switcher.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-tag/ec-component-tag-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-full/ecl-builder.config.js
  src/systems/ec/implementations/vanilla/packages/ec-preset-full/src/ec-preset-full-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-website/ecl-builder.config.js
  src/systems/ec/implementations/vanilla/packages/ec-preset-website/src/ec-preset-website-print.scss
  src/systems/ec/themes/default/aliases/icons.yml
  src/systems/ec/themes/default/aliases/spacing.yml
  src/systems/ec/themes/default/aliases/typography.yml
  src/systems/eu/design-tokens/tokens/icons.yml
  src/systems/eu/design-tokens/tokens/spacing.yml
  src/systems/eu/design-tokens/tokens/typography.yml
  src/systems/eu/implementations/react/storybook/.storybook/ECL.jsx
  src/systems/eu/implementations/react/storybook/.storybook/preview-head.html
  src/systems/eu/implementations/vanilla/packages/eu-base/mixins/_hidden-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-base/mixins/index.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-accordion/eu-component-accordion-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-breadcrumb/eu-component-breadcrumb-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-button/eu-component-button-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-card/eu-component-card-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-footer/eu-component-footer-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-icon/eu-component-icon-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-link/eu-component-link-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-media-container/eu-component-media-container-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-page-header/eu-component-page-header-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-search-form/eu-component-search-form-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-site-header/eu-component-site-header-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-tag/eu-component-tag-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-full/ecl-builder.config.js
  src/systems/eu/implementations/vanilla/packages/eu-preset-full/src/eu-preset-full-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-website/ecl-builder.config.js
  src/systems/eu/implementations/vanilla/packages/eu-preset-website/src/eu-preset-website-print.scss
  src/systems/eu/themes/default/aliases/icons.yml
  src/systems/eu/themes/default/aliases/spacing.yml
  src/systems/eu/themes/default/aliases/typography.yml
  src/website/scripts/copy.sh
Labels: tag: enhancement

#1071 docs(print): how to handle print - INNO-1432
  docs/decisions/001-print.md
Labels: RFC, tag: documentation

#1095 feat(blockquote): add print css - INNO-1459
  src/systems/ec/implementations/vanilla/packages/ec-component-blockquote/ec-component-blockquote-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-blockquote/eu-component-blockquote-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev-print.scss
Labels: tag: enhancement

#1097 feat(expandable): add print css - INNO-1461
  src/systems/ec/implementations/vanilla/packages/ec-component-expandable/ec-component-expandable-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-utility-typography/ec-utility-typography-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-expandable/eu-component-expandable-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-utility-typography/eu-utility-typography-print.scss
Labels: tag: enhancement

#1096 feat(contextual-navigation): add print css - INNO-1460
  docs/decisions/001-print.md
  src/systems/ec/implementations/vanilla/packages/ec-component-contextual-navigation/ec-component-contextual-navigation-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-link/ec-component-link-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-contextual-navigation/eu-component-contextual-navigation-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-link/eu-component-link-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev-print.scss
Labels: tag: enhancement

#1098 feat(file): add print css - INNO-1462
  src/systems/ec/implementations/vanilla/packages/ec-component-file/ec-component-file-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-file/eu-component-file-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev-print.scss
Labels: tag: enhancement

#1100 feat(hero-banner): add print css - INNO-1464
  src/systems/ec/implementations/vanilla/packages/ec-component-hero-banner/ec-component-hero-banner-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-hero-banner/eu-component-hero-banner-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev-print.scss
Labels: tag: enhancement

#1099 feat(gallery): add print css - INNO-1463
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/ec-component-gallery-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-gallery/eu-component-gallery-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev-print.scss
Labels: tag: enhancement

#1101 feat(language-list): add print css - INNO-1465
  src/systems/ec/implementations/react/packages/language-list/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-language-list/ec-component-language-list-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-language-list/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-language-list/eu-component-language-list-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev-print.scss
Labels: tag: enhancement
