Repository ec-europa/europa-component-library, pull requests merged in 2019-07, with the labels that each got.

#1172 feat(gallery): add video management - INNO-1552
  src/systems/ec/implementations/react/components/gallery/src/Gallery.jsx
  src/systems/ec/implementations/react/components/gallery/src/GalleryItem.jsx
  src/systems/ec/implementations/react/components/gallery/src/GalleryOverlay.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/ec-component-gallery.js
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/ec-component-gallery.scss
  src/systems/ec/specs/components/gallery/demo/data.js
  src/systems/eu/implementations/react/components/gallery/src/Gallery.jsx
  src/systems/eu/implementations/react/components/gallery/src/GalleryItem.jsx
  src/systems/eu/implementations/react/components/gallery/src/GalleryOverlay.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-gallery/eu-component-gallery.js
  src/systems/eu/implementations/vanilla/packages/eu-component-gallery/eu-component-gallery.scss
  src/systems/eu/specs/components/gallery/demo/data.js
Labels: tag: enhancement

#1185 fix(preset-dev): add missing dependencies - INNO-1608
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/package.json
Labels: tag: bug fix

#1184 chore: integrate CCK into the website - INNO-1607
  src/systems/ec/implementations/react/storybook/.storybook/manager-head.html
  src/systems/eu/implementations/react/storybook/.storybook/manager-head.html
  src/website/public/index.html
  src/website/src/components/Navigation/Navigation.scss
  src/website/src/pages/ec/getting-started/index.md
  src/website/src/styles/app.scss
Labels: process: review needed, tag: internal

#1186 fix(inpage-nav): fix styles - INNO-1609
  src/systems/ec/implementations/react/components/inpage-navigation/examples/Default.jsx
  src/systems/ec/implementations/react/components/inpage-navigation/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-inpage-navigation/ec-component-inpage-navigation.js
  src/systems/ec/implementations/vanilla/packages/ec-component-inpage-navigation/ec-component-inpage-navigation.scss
  src/systems/eu/implementations/react/components/inpage-navigation/examples/Default.jsx
  src/systems/eu/implementations/react/components/inpage-navigation/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-inpage-navigation/eu-component-inpage-navigation.js
  src/systems/eu/implementations/vanilla/packages/eu-component-inpage-navigation/eu-component-inpage-navigation.scss
Labels: process: under review, tag: bug fix

#1178 chore: automate the deployment of ECL website - FPFISSUPP-4104
  .drone.yml
Labels: tag: internal

#1190 chore: hide back to top - INNO-1611
  src/systems/ec/implementations/react/page-structure/footer/src/Footer.jsx
  src/systems/eu/implementations/react/page-structure/footer/src/Footer.jsx
Labels: process: under review, tag: enhancement

#1193 docs(accordion): update thumbnail - INNO-1610
  src/website/src/pages/ec/components/accordion/ec_comp_accordion.svg
Labels: tag: documentation

#1192 refactor(preset): move deprecated into legacy - INNO-1605
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-legacy-website/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-legacy-website/src/ec-preset-legacy-website.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-legacy/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-legacy/src/ec-preset-legacy.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-legacy-website/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-legacy-website/src/eu-preset-legacy-website.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-legacy/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-legacy/src/eu-preset-legacy.scss
Labels: tag: internal

#1196 fix(inpage-nav): add missing polyfills for IE - INNO-1622
  src/systems/ec/implementations/vanilla/packages/ec-component-inpage-navigation/ec-component-inpage-navigation.js
  src/systems/eu/implementations/vanilla/packages/eu-component-inpage-navigation/eu-component-inpage-navigation.js
Labels: process: under review, tag: bug fix

#1198 docs: add a note about using external SVG sprite - INNO-1625
  src/website/src/pages/ec/getting-started/index.md
  src/website/src/pages/eu/getting-started/index.md
Labels: process: review needed, tag: documentation

#1202 chore: update dependencies - INNO-1650
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  src/systems/ec/implementations/react/components/accordion/src/AccordionItem.jsx
  src/systems/ec/implementations/react/components/accordion2/src/Accordion2Item.jsx
  src/systems/ec/implementations/react/components/description-list/package.json
  src/systems/ec/implementations/react/components/ordered-list/package.json
  src/systems/ec/implementations/react/components/timeline/package.json
  src/systems/ec/implementations/react/components/timeline2/package.json
  src/systems/ec/implementations/react/components/unordered-list/package.json
  src/systems/ec/implementations/react/page-structure/site-header/src/SiteHeader.jsx
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/resources/icons/package.json
  src/systems/ec/resources/social-icons/package.json
  src/systems/eu/implementations/react/components/accordion/src/AccordionItem.jsx
  src/systems/eu/implementations/react/components/accordion2/src/Accordion2Item.jsx
  src/systems/eu/implementations/react/components/description-list/package.json
  src/systems/eu/implementations/react/components/ordered-list/package.json
  src/systems/eu/implementations/react/components/timeline/package.json
  src/systems/eu/implementations/react/components/timeline2/package.json
  src/systems/eu/implementations/react/components/unordered-list/package.json
  src/systems/eu/implementations/react/page-structure/footer/src/Footer.jsx
  src/systems/eu/implementations/react/page-structure/site-header/src/SiteHeader.jsx
  src/systems/eu/implementations/react/storybook/package.json
  src/systems/eu/resources/icons/package.json
  src/systems/eu/resources/social-icons/package.json
  src/tools/builder/package.json
  src/tools/storybook-addon-code/components/CodeToggle.jsx
  src/tools/storybook-addon-code/components/PreviewWrapper.jsx
  src/website/package.json
  src/website/src/components/DocPage/Header.jsx
  src/website/src/components/Navigation/SingleLink.jsx
  yarn.lock
Labels: process: under review, tag: internal

#1199 docs(accordion): update accordion's doc - INNO-1629
  src/website/src/pages/ec/components/accordion/docs/usage.mdx
  src/website/src/pages/eu/components/accordion/docs/usage.mdx
Labels: process: under review, tag: documentation

#1201 docs(select): update select's documentation - INNO-1630
  src/website/src/pages/ec/components/forms/select/docs/usage.mdx
  src/website/src/pages/eu/components/forms/select/docs/usage.mdx
Labels: process: under review, tag: documentation

#1203 docs(expandable): update expandable's documentation - INNO-1631
  src/website/src/pages/ec/components/expandable/docs/usage.mdx
  src/website/src/pages/eu/components/expandable/docs/usage.mdx
Labels: process: under review, tag: documentation

#1200 feat(table): add table - INNO-1628
  src/systems/ec/implementations/react/components/table/examples/Table.jsx
  src/systems/ec/implementations/react/components/table/examples/TableMulti.jsx
  src/systems/ec/implementations/react/components/table/examples/TableZebra.jsx
  src/systems/ec/implementations/react/components/table/index.js
  src/systems/ec/implementations/react/components/table/package.json
  src/systems/ec/implementations/react/components/table/src/Table.jsx
  src/systems/ec/implementations/react/components/table/src/TableBody.jsx
  src/systems/ec/implementations/react/components/table/src/TableCell.jsx
  src/systems/ec/implementations/react/components/table/src/TableHead.jsx
  src/systems/ec/implementations/react/components/table/src/TableHeader.jsx
  src/systems/ec/implementations/react/components/table/src/TableRow.jsx
  src/systems/ec/implementations/react/components/table/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-table/README.md
  src/systems/ec/implementations/vanilla/packages/ec-component-table/ec-component-table-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-table/ec-component-table.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-table/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.js
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.scss
  src/systems/ec/specs/components/table/demo/data--default.js
  src/systems/ec/specs/components/table/demo/data--multi.js
  src/systems/ec/specs/components/table/package.json
  src/systems/eu/implementations/react/components/table/examples/Table.jsx
  src/systems/eu/implementations/react/components/table/examples/TableMulti.jsx
  src/systems/eu/implementations/react/components/table/examples/TableZebra.jsx
  src/systems/eu/implementations/react/components/table/index.js
  src/systems/eu/implementations/react/components/table/package.json
  src/systems/eu/implementations/react/components/table/src/Table.jsx
  src/systems/eu/implementations/react/components/table/src/TableBody.jsx
  src/systems/eu/implementations/react/components/table/src/TableCell.jsx
  src/systems/eu/implementations/react/components/table/src/TableHead.jsx
  src/systems/eu/implementations/react/components/table/src/TableHeader.jsx
  src/systems/eu/implementations/react/components/table/src/TableRow.jsx
  src/systems/eu/implementations/react/components/table/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-table/README.md
  src/systems/eu/implementations/vanilla/packages/eu-component-table/eu-component-table-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-table/eu-component-table.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-table/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev.js
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev.scss
  src/systems/eu/specs/components/table/demo/data--default.js
  src/systems/eu/specs/components/table/demo/data--multi.js
  src/systems/eu/specs/components/table/package.json
  src/website/src/pages/ec/components/table/docs/code.mdx
  src/website/src/pages/ec/components/table/docs/usage.mdx
  src/website/src/pages/ec/components/table/index.md
  src/website/src/pages/eu/components/table/docs/code.mdx
  src/website/src/pages/eu/components/table/docs/usage.mdx
  src/website/src/pages/eu/components/table/index.md
Labels: tag: new feature

#1205 docs(inpage-nav): update inpage-nav's documentation - INNO-1633
  src/website/src/pages/ec/components/navigation/inpage-navigation/docs/usage.mdx
  src/website/src/pages/eu/components/navigation/inpage-navigation/docs/usage.mdx
Labels: process: under review, tag: documentation

#1189 docs(grid): document grid and provide examples - INNO-1616
  package.json
  src/systems/ec/implementations/react/layout/grid/examples/234612.jsx
  src/systems/ec/implementations/react/layout/grid/examples/282.jsx
  src/systems/ec/implementations/react/layout/grid/examples/336.jsx
  src/systems/ec/implementations/react/layout/grid/examples/642.jsx
  src/systems/ec/implementations/react/layout/grid/examples/Box.jsx
  src/systems/ec/implementations/react/layout/grid/examples/Offset.jsx
  src/systems/ec/implementations/react/layout/grid/examples/Responsive.jsx
  src/systems/ec/implementations/react/layout/grid/package.json
  src/systems/ec/implementations/react/layout/grid/stories/Index.jsx
  src/systems/eu/implementations/react/layout/grid/examples/234612.jsx
  src/systems/eu/implementations/react/layout/grid/examples/282.jsx
  src/systems/eu/implementations/react/layout/grid/examples/336.jsx
  src/systems/eu/implementations/react/layout/grid/examples/642.jsx
  src/systems/eu/implementations/react/layout/grid/examples/Box.jsx
  src/systems/eu/implementations/react/layout/grid/examples/Offset.jsx
  src/systems/eu/implementations/react/layout/grid/examples/Responsive.jsx
  src/systems/eu/implementations/react/layout/grid/package.json
  src/systems/eu/implementations/react/layout/grid/stories/Index.jsx
  src/website/src/pages/ec/layout/grid/index.mdx
  src/website/src/pages/eu/layout/grid/index.mdx
Labels: process: review needed, tag: documentation

#1206 docs(language-list): update documentation of language list - INNO-1634
  src/website/src/pages/ec/page-structure/language-list/docs/usage.mdx
  src/website/src/pages/eu/page-structure/language-list/docs/usage.mdx
Labels: process: under review, tag: documentation

#1204 docs(file): update file download's documentation - INNO-1632
  src/website/src/pages/ec/components/file/docs/usage.mdx
  src/website/src/pages/eu/components/file/docs/usage.mdx
Labels: tag: documentation

#1209 docs(radio): update documentation of radio - INNO-1637
  src/website/src/pages/ec/components/forms/radio/docs/usage.mdx
  src/website/src/pages/eu/components/forms/radio/docs/usage.mdx
Labels: process: under review, tag: documentation

#1211 docs: add documentation about social media follow - INNO-1639
  src/website/src/pages/ec/components/social-media-follow/docs/usage.md
  src/website/src/pages/ec/components/social-media-follow/docs/usage.mdx
  src/website/src/pages/eu/components/social-media-follow/docs/usage.md
  src/website/src/pages/eu/components/social-media-follow/docs/usage.mdx
Labels: process: under review, tag: documentation

#1210 docs: add documentation about search form - INNO-1638
  src/website/src/pages/ec/components/forms/search-form/docs/usage.md
  src/website/src/pages/ec/components/forms/search-form/docs/usage.mdx
  src/website/src/pages/eu/components/forms/search-form/docs/usage.md
  src/website/src/pages/eu/components/forms/search-form/docs/usage.mdx
Labels: tag: documentation

#1214 docs(text-area): update documentation of text area - INNO-1642
  src/website/src/pages/ec/components/forms/text-area/docs/usage.mdx
  src/website/src/pages/eu/components/forms/text-area/docs/usage.mdx
Labels: process: under review, tag: documentation

#1212 docs: add documentation about social media share - INNO-1640
  src/website/src/pages/ec/components/social-media-share/docs/usage.md
  src/website/src/pages/ec/components/social-media-share/docs/usage.mdx
  src/website/src/pages/eu/components/social-media-share/docs/usage.md
  src/website/src/pages/eu/components/social-media-share/docs/usage.mdx
Labels: tag: documentation

#1208 docs(pagination): update documentation of pagination - INNO-1636
  src/website/src/pages/ec/components/navigation/pagination/docs/usage.mdx
  src/website/src/pages/eu/components/navigation/pagination/docs/usage.mdx
Labels: tag: documentation

#1207 docs(message): update documentation of messages - INNO-1635
  src/website/src/pages/ec/components/message/docs/usage.mdx
  src/website/src/pages/eu/components/message/docs/usage.mdx
Labels: tag: documentation

#1215 docs(timelines): update documentation of timeline - INNO-1643
  src/website/src/pages/ec/components/timeline/docs/usage.mdx
  src/website/src/pages/eu/components/timeline/docs/usage.mdx
Labels: process: under review, tag: documentation

#1216 docs: add playground tab to many pages - INNO-1644
  src/website/src/pages/ec/components/accordion/index.md
  src/website/src/pages/ec/components/blockquote/index.md
  src/website/src/pages/ec/components/expandable/index.md
  src/website/src/pages/ec/components/forms/search-form/index.md
  src/website/src/pages/ec/components/media/gallery/index.md
  src/website/src/pages/ec/components/navigation/inpage-navigation/index.md
  src/website/src/pages/ec/components/navigation/pagination/index.md
  src/website/src/pages/ec/components/social-media-share/index.md
  src/website/src/pages/ec/components/timeline/index.md
  src/website/src/pages/ec/templates/compositions/content-item/index.md
  src/website/src/pages/ec/templates/compositions/navigation-lists/index.md
  src/website/src/pages/ec/utilities/background/index.md
  src/website/src/pages/eu/components/accordion/index.md
  src/website/src/pages/eu/components/blockquote/index.md
  src/website/src/pages/eu/components/expandable/index.md
  src/website/src/pages/eu/components/forms/search-form/index.md
  src/website/src/pages/eu/components/media/gallery/index.md
  src/website/src/pages/eu/components/navigation/inpage-navigation/index.md
  src/website/src/pages/eu/components/navigation/pagination/index.md
  src/website/src/pages/eu/components/social-media-share/index.md
  src/website/src/pages/eu/components/timeline/index.md
  src/website/src/pages/eu/templates/compositions/content-item/index.md
  src/website/src/pages/eu/templates/compositions/navigation-lists/index.md
  src/website/src/pages/eu/utilities/background/index.md
Labels: process: under review, tag: documentation

#1213 docs(text-field): update documentation of text field - INNO-1641
  src/website/src/pages/ec/components/forms/text-field/docs/usage.mdx
  src/website/src/pages/eu/components/forms/text-field/docs/usage.mdx
Labels: tag: documentation

#1218 feat: add skip link component - INNO-1653
  src/systems/ec/implementations/react/components/skip-link/index.js
  src/systems/ec/implementations/react/components/skip-link/package.json
  src/systems/ec/implementations/react/components/skip-link/src/SkipLink.jsx
  src/systems/ec/implementations/react/components/skip-link/stories/Index.jsx
  src/systems/ec/implementations/react/templates/pages/campaign/package.json
  src/systems/ec/implementations/react/templates/pages/campaign/src/CampaignPage.jsx
  src/systems/ec/implementations/react/templates/pages/campaign/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-skip-link/README.md
  src/systems/ec/implementations/vanilla/packages/ec-component-skip-link/ec-component-skip-link-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-skip-link/ec-component-skip-link.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-skip-link/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-legacy-website/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-legacy-website/src/ec-preset-legacy-website-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-legacy-website/src/ec-preset-legacy-website.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-legacy/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-legacy/src/ec-preset-legacy-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-legacy/src/ec-preset-legacy.scss
  src/systems/ec/specs/components/skip-link/demo/data.js
  src/systems/ec/specs/components/skip-link/package.json
  src/systems/eu/implementations/react/components/skip-link/index.js
  src/systems/eu/implementations/react/components/skip-link/package.json
  src/systems/eu/implementations/react/components/skip-link/src/SkipLink.jsx
  src/systems/eu/implementations/react/components/skip-link/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-skip-link/README.md
  src/systems/eu/implementations/vanilla/packages/eu-component-skip-link/eu-component-skip-link-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-skip-link/eu-component-skip-link.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-skip-link/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-legacy-website/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-legacy-website/src/eu-preset-legacy-website-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-legacy-website/src/eu-preset-legacy-website.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-legacy/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-legacy/src/eu-preset-legacy-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-legacy/src/eu-preset-legacy.scss
  src/systems/eu/specs/components/skip-link/demo/data.js
  src/systems/eu/specs/components/skip-link/package.json
Labels: process: under review, tag: new feature

#1220 docs(skip-link): add and hide skip link's documentation - INNO-1653
  src/website/src/pages/ec/components/navigation/skip-link/docs/code.mdx
  src/website/src/pages/ec/components/navigation/skip-link/docs/usage.md
  src/website/src/pages/ec/components/navigation/skip-link/index.md
  src/website/src/pages/eu/components/navigation/skip-link/docs/code.mdx
  src/website/src/pages/eu/components/navigation/skip-link/docs/usage.md
  src/website/src/pages/eu/components/navigation/skip-link/index.md
Labels: process: under review, tag: documentation

#1223 chore(website): enhance sidebar behaviour - INNO-1659
  src/website/src/components/Navigation/Navigation.jsx
  src/website/src/components/Navigation/Navigation.scss
Labels: process: under review, tag: internal

#1224 fix(ecl-editor): revert changes on blockquote - INNO-1664
  .drone.yml
  .nvmrc
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  src/generic/generic-component-blockquote/generic-component-blockquote--editor.scss
  src/generic/generic-style-color/generic-style-color.config.js
  src/generic/generic-style-typography-paragraph/generic-style-typography-paragraph.config.js
  src/systems/ec/ec-component/ec-component-logo/ec-component-logo.config.js
  src/systems/ec/ec-component/ec-component-meta/ec-component-meta.config.js
  src/systems/ec/ec-component/ec-component-page-header/README.md
  src/systems/ec/ec-component/ec-component-social-icon/ec-component-social-icon.config.js
  src/systems/ec/ec-style/ec-style-color/ec-style-color.config.js
  src/systems/ec/ec-style/ec-style-icon/ec-style-icon.config.js
  src/systems/ec/ec-style/ec-style-typography/ec-style-typography-paragraph/ec-style-typography-paragraph.config.js
  src/systems/eu/eu-component/eu-component-logo/eu-component-logo.config.js
  src/systems/eu/eu-component/eu-component-meta/eu-component-meta.config.js
  src/systems/eu/eu-component/eu-component-social-icon/eu-component-social-icon.config.js
  src/systems/eu/eu-style/eu-style-color/eu-style-color.config.js
  src/systems/eu/eu-style/eu-style-icon/eu-style-icon.config.js
  src/systems/eu/eu-style/eu-style-typography/eu-style-typography-paragraph/eu-style-typography-paragraph.config.js
  test/functional/wdio.conf.js
  tools/ec-styleguide/package.json
  tools/eu-styleguide/package.json
  tools/fractal-theme/package.json
  tools/fractal-twig/package.json
  yarn.lock
Labels: process: under review, tag: bug fix

#1226 fix(table): use bold for headers - INNO-1666
  src/systems/ec/implementations/vanilla/packages/ec-component-table/ec-component-table.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-table/eu-component-table.scss
Labels: tag: bug fix

#1183 refactor(text-inputs): update styling of text inputs - INNO-1593
  src/systems/ec/implementations/react/components/search-form/src/SearchForm.jsx
  src/systems/ec/implementations/react/components/text-area/src/TextArea.jsx
  src/systems/ec/implementations/react/components/text-area/stories/Index.jsx
  src/systems/ec/implementations/react/components/text-input/src/TextInput.jsx
  src/systems/ec/implementations/react/components/text-input/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-form-feedback-message/ec-component-form-feedback-message.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-form-group/ec-component-form-form-group.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-help-block/ec-component-form-help-block.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-label/ec-component-form-label.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-text-area/ec-component-form-text-area.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-text-input/ec-component-form-text-input.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-search-form/ec-component-search-form.scss
  src/systems/ec/specs/components/text-area/demo/data--default.js
  src/systems/ec/specs/components/text-area/demo/data--has-error.js
  src/systems/ec/specs/components/text-area/demo/data--is-disabled.js
  src/systems/ec/specs/components/text-input/demo/data--default.js
  src/systems/ec/specs/components/text-input/demo/data--disabled.js
  src/systems/ec/specs/components/text-input/demo/data--with-error.js
  src/systems/eu/implementations/react/components/search-form/src/SearchForm.jsx
  src/systems/eu/implementations/react/components/text-area/src/TextArea.jsx
  src/systems/eu/implementations/react/components/text-area/stories/Index.jsx
  src/systems/eu/implementations/react/components/text-input/src/TextInput.jsx
  src/systems/eu/implementations/react/components/text-input/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-form-feedback-message/eu-component-form-feedback-message.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-form-form-group/eu-component-form-form-group.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-form-help-block/eu-component-form-help-block.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-form-label/eu-component-form-label.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-form-text-area/eu-component-form-text-area.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-form-text-input/eu-component-form-text-input.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-search-form/eu-component-search-form.scss
  src/systems/eu/specs/components/text-area/demo/data--default.js
  src/systems/eu/specs/components/text-area/demo/data--has-error.js
  src/systems/eu/specs/components/text-area/demo/data--is-disabled.js
  src/systems/eu/specs/components/text-input/demo/data--default.js
  src/systems/eu/specs/components/text-input/demo/data--disabled.js
  src/systems/eu/specs/components/text-input/demo/data--with-error.js
  src/website/src/pages/ec/components/forms/text-area/docs/code.mdx
  src/website/src/pages/ec/components/forms/text-field/docs/code.mdx
  src/website/src/pages/eu/_components/forms/text-area/docs/code.mdx
  src/website/src/pages/eu/_components/forms/text-field/docs/code.mdx
Labels: process: under review, tag: enhancement

#1229 fix(search-form): make input fluid - INNO-1687
  src/systems/ec/implementations/vanilla/packages/ec-component-search-form/ec-component-search-form.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-search-form/eu-component-search-form.scss
Labels: process: under review, tag: bug fix

#1228 refactor(select): update styling of select - INNO-1595
  src/systems/ec/implementations/react/components/select/src/Select.jsx
  src/systems/ec/implementations/react/components/select/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-form-form-group/ec-component-form-form-group.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-select/ec-component-form-select.scss
  src/systems/ec/specs/components/select/demo/data.js
  src/systems/eu/implementations/react/components/select/src/Select.jsx
  src/systems/eu/implementations/react/components/select/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-form-form-group/eu-component-form-form-group.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-form-select/eu-component-form-select.scss
  src/systems/eu/specs/components/select/demo/data.js
  src/website/src/pages/ec/components/forms/select/docs/code.mdx
  src/website/src/pages/eu/_components/forms/select/docs/code.mdx
Labels: process: under review, tag: enhancement

#1230 feat(timeline): improve logic for the button - INNO-1688
  src/generic/generic-component-timeline/generic-component-timeline.twig
Labels: tag: enhancement

#1232 chore(token): add tokens for form width - INNO-1692
  src/systems/ec/design-tokens/index.yml
  src/systems/ec/design-tokens/tokens/widths.yml
  src/systems/ec/implementations/vanilla/packages/ec-component-form-select/ec-component-form-select.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-text-area/ec-component-form-text-area.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-text-input/ec-component-form-text-input.scss
  src/systems/ec/themes/default/aliases/widths.yml
  src/systems/ec/themes/default/index.scss
  src/systems/ec/themes/default/index.yml
  src/systems/ec/themes/default/scripts/build-tokens.js
  src/systems/eu/design-tokens/index.yml
  src/systems/eu/design-tokens/tokens/widths.yml
  src/systems/eu/implementations/vanilla/packages/eu-component-form-select/eu-component-form-select.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-form-text-area/eu-component-form-text-area.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-form-text-input/eu-component-form-text-input.scss
  src/systems/eu/themes/default/aliases/widths.yml
  src/systems/eu/themes/default/index.scss
  src/systems/eu/themes/default/index.yml
  src/systems/eu/themes/default/scripts/build-tokens.js
Labels: tag: internal

#1227 feat: initialize JS components automatically (opt-in) - INNO-1680
  examples/auto-init/index.html
  src/systems/ec/implementations/vanilla/packages/ec-auto-init/README.md
  src/systems/ec/implementations/vanilla/packages/ec-auto-init/index.js
  src/systems/ec/implementations/vanilla/packages/ec-auto-init/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-accordion2/ec-component-accordion2.js
  src/systems/ec/implementations/vanilla/packages/ec-component-breadcrumb/ec-component-breadcrumb.js
  src/systems/ec/implementations/vanilla/packages/ec-component-contextual-navigation/ec-component-contextual-navigation.js
  src/systems/ec/implementations/vanilla/packages/ec-component-expandable/ec-component-expandable.js
  src/systems/ec/implementations/vanilla/packages/ec-component-file/ec-component-file.js
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/ec-component-gallery.js
  src/systems/ec/implementations/vanilla/packages/ec-component-inpage-navigation/ec-component-inpage-navigation.js
  src/systems/ec/implementations/vanilla/packages/ec-component-message/ec-component-message.js
  src/systems/ec/implementations/vanilla/packages/ec-component-timeline2/ec-component-timeline2.js
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.js
  src/systems/eu/implementations/vanilla/packages/eu-auto-init/README.md
  src/systems/eu/implementations/vanilla/packages/eu-auto-init/index.js
  src/systems/eu/implementations/vanilla/packages/eu-auto-init/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-accordion2/eu-component-accordion2.js
  src/systems/eu/implementations/vanilla/packages/eu-component-breadcrumb/eu-component-breadcrumb.js
  src/systems/eu/implementations/vanilla/packages/eu-component-contextual-navigation/eu-component-contextual-navigation.js
  src/systems/eu/implementations/vanilla/packages/eu-component-expandable/eu-component-expandable.js
  src/systems/eu/implementations/vanilla/packages/eu-component-file/eu-component-file.js
  src/systems/eu/implementations/vanilla/packages/eu-component-gallery/eu-component-gallery.js
  src/systems/eu/implementations/vanilla/packages/eu-component-inpage-navigation/eu-component-inpage-navigation.js
  src/systems/eu/implementations/vanilla/packages/eu-component-message/eu-component-message.js
  src/systems/eu/implementations/vanilla/packages/eu-component-timeline2/eu-component-timeline2.js
  src/website/src/pages/ec/components/accordion/docs/code.mdx
  src/website/src/pages/ec/components/expandable/docs/code.mdx
  src/website/src/pages/ec/components/file/docs/code.mdx
  src/website/src/pages/ec/components/media/gallery/docs/code.mdx
  src/website/src/pages/ec/components/message/docs/code.mdx
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/code.mdx
  src/website/src/pages/ec/components/navigation/contextual-navigation/docs/code.mdx
  src/website/src/pages/ec/components/navigation/inpage-navigation/docs/code.mdx
  src/website/src/pages/ec/components/timeline/docs/code.mdx
  src/website/src/pages/ec/getting-started/index.md
  src/website/src/pages/eu/_components/accordion/docs/code.mdx
  src/website/src/pages/eu/_components/expandable/docs/code.mdx
  src/website/src/pages/eu/_components/file/docs/code.mdx
  src/website/src/pages/eu/_components/media/gallery/docs/code.mdx
  src/website/src/pages/eu/_components/message/docs/code.mdx
  src/website/src/pages/eu/_components/navigation/breadcrumb/docs/code.mdx
  src/website/src/pages/eu/_components/navigation/contextual-navigation/docs/code.mdx
  src/website/src/pages/eu/_components/navigation/inpage-navigation/docs/code.mdx
  src/website/src/pages/eu/_components/timeline/docs/code.mdx
  src/website/src/pages/eu/_getting-started/index.md
Labels: process: under review, tag: new feature

#1233 feat(form-group): allow group classname - INNO-1702
  src/systems/ec/implementations/react/components/select/src/Select.jsx
  src/systems/ec/implementations/react/components/text-area/src/TextArea.jsx
  src/systems/ec/implementations/react/components/text-input/src/TextInput.jsx
  src/systems/eu/implementations/react/components/select/src/Select.jsx
  src/systems/eu/implementations/react/components/text-area/src/TextArea.jsx
  src/systems/eu/implementations/react/components/text-input/src/TextInput.jsx
Labels: tag: enhancement

#1234 fix(search-template): fix spacing - INNO-1703
  src/systems/ec/implementations/react/templates/pages/search/src/SearchPage.jsx
Labels: process: review needed, tag: bug fix
