Repository ec-europa/europa-component-library, pull requests merged in 2019-02, with the labels that each got.

#992 feat(accordion): add component - INNO-1232
  src/systems/ec/implementations/react/packages/accordion/index.js
  src/systems/ec/implementations/react/packages/accordion/package.json
  src/systems/ec/implementations/react/packages/accordion/src/Accordion.jsx
  src/systems/ec/implementations/react/packages/accordion/src/AccordionItem.jsx
  src/systems/ec/implementations/react/packages/accordion/stories/Index.jsx
  src/systems/ec/implementations/react/packages/button/Button.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-accordion/README.md
  src/systems/ec/implementations/vanilla/packages/ec-component-accordion/ec-component-accordion.js
  src/systems/ec/implementations/vanilla/packages/ec-component-accordion/ec-component-accordion.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-accordion/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-button/ec-component-button.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.js
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.scss
  src/systems/ec/specs/components/accordion/demo/data.js
  src/systems/ec/specs/components/accordion/package.json
  src/systems/eu/implementations/react/packages/accordion/index.js
  src/systems/eu/implementations/react/packages/accordion/package.json
  src/systems/eu/implementations/react/packages/accordion/src/Accordion.jsx
  src/systems/eu/implementations/react/packages/accordion/src/AccordionItem.jsx
  src/systems/eu/implementations/react/packages/accordion/stories/Index.jsx
  src/systems/eu/implementations/react/packages/button/Button.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-accordion/README.md
  src/systems/eu/implementations/vanilla/packages/eu-component-accordion/eu-component-accordion.js
  src/systems/eu/implementations/vanilla/packages/eu-component-accordion/eu-component-accordion.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-accordion/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-button/eu-component-button.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev.js
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev.scss
  src/systems/eu/specs/components/accordion/demo/data.js
  src/systems/eu/specs/components/accordion/package.json
  src/website/src/pages/ec/components/accordion/docs/code.mdx
  src/website/src/pages/ec/components/accordion/docs/usage.md
  src/website/src/pages/ec/components/accordion/index.md
  src/website/src/pages/eu/components/accordion/docs/code.mdx
  src/website/src/pages/eu/components/accordion/docs/usage.md
  src/website/src/pages/eu/components/accordion/index.md
Labels: tag: new feature

#1002 chore: update dependencies - no issue
  package.json
  src/website/package.json
  yarn.lock
Labels: process: under review, tag: internal

#1005 chore: setup v2-dev branch
  .drone.yml
  docs/04-documentation.md
  docs/06-presets.md
Labels: process: review needed, tag: internal

#1009 fix(ec-site-header): hide user menu
  src/systems/ec/ec-component/ec-component-site-header/ec-component-site-header.config.js
  src/systems/ec/ec-template/ec-template-community/ec-template-community.twig
Labels: process: review needed, tag: bug fix

#1006 refactor(file): improve markup - INNO-1320
  src/systems/ec/implementations/react/packages/file/FileDownload.jsx
  src/systems/ec/specs/components/file/demo/data--with-translation.js
  src/systems/eu/implementations/react/packages/file/FileDownload.jsx
  src/systems/eu/specs/components/file/demo/data--with-translation.js
Labels: tag: enhancement

#1007 refactor(language-list): improve markup - INNO-1321
  src/systems/ec/implementations/react/packages/language-list/LanguageList.jsx
  src/systems/ec/implementations/react/packages/language-list/LanguageListItem.jsx
  src/systems/ec/implementations/react/packages/language-list/LanguageListOverlay.jsx
  src/systems/ec/specs/components/language-list/demo/data--overlay.js
  src/systems/ec/specs/components/language-list/demo/data--splash.js
  src/systems/eu/implementations/react/packages/language-list/LanguageList.jsx
  src/systems/eu/implementations/react/packages/language-list/LanguageListItem.jsx
  src/systems/eu/implementations/react/packages/language-list/LanguageListOverlay.jsx
  src/systems/eu/specs/components/language-list/demo/data--overlay.js
  src/systems/eu/specs/components/language-list/demo/data--splash.js
Labels: tag: enhancement

#1013 fix(ecl-builder): update dependencies, fix scripts build - no issue
  examples/webpack3/package.json
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-accordion/ec-component-accordion.js
  src/systems/ec/implementations/vanilla/packages/ec-component-breadcrumb/ec-component-breadcrumb.js
  src/systems/ec/implementations/vanilla/packages/ec-component-contextual-navigation/ec-component-contextual-navigation.js
  src/systems/ec/implementations/vanilla/packages/ec-component-expandable/ec-component-expandable.js
  src/systems/ec/implementations/vanilla/packages/ec-component-file/ec-component-file.js
  src/systems/ec/implementations/vanilla/packages/ec-component-timeline/ec-component-timeline.js
  src/systems/ec/implementations/vanilla/packages/ec-preset-full/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-website/package.json
  src/systems/eu/implementations/react/storybook/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-accordion/eu-component-accordion.js
  src/systems/eu/implementations/vanilla/packages/eu-component-breadcrumb/eu-component-breadcrumb.js
  src/systems/eu/implementations/vanilla/packages/eu-component-contextual-navigation/eu-component-contextual-navigation.js
  src/systems/eu/implementations/vanilla/packages/eu-component-expandable/eu-component-expandable.js
  src/systems/eu/implementations/vanilla/packages/eu-component-file/eu-component-file.js
  src/systems/eu/implementations/vanilla/packages/eu-component-timeline/eu-component-timeline.js
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-full/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-website/package.json
  src/tools/builder/README.md
  src/tools/builder/bin/build.js
  src/tools/builder/package.json
  src/tools/builder/scripts/copy.js
  src/tools/builder/scripts/scripts.js
  src/tools/builder/scripts/styles.js
  src/tools/story-wrapper/package.json
  src/tools/website-components/package.json
  src/website/package.json
  yarn.lock
Labels: tag: bug fix

#1012 feat(website): display version number - INNO-1325
  src/website/src/components/Navigation/Navigation.jsx
  src/website/src/components/Navigation/Navigation.scss
  src/website/webpack.config.dev.js
  src/website/webpack.config.prod.js
Labels: tag: internal

#1018 chore: update dependencies - no issue
  examples/webpack3/package.json
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-website/package.json
  src/systems/eu/implementations/react/storybook/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-website/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: process: under review, tag: internal
