Repository ec-europa/europa-component-library, pull requests merged in 2019-09, with the labels that each got.

#1291 chore(release 2.11): finalize release v2 - INNO-1764
  README.md
Labels: tag: internal

#1292 chore(release 2.11): finalize release dev - INNO-1764
  README.md
  lerna.json
Labels: tag: internal

#1294 fix(content-item): fix image css - INNO-1761
  src/systems/ec/implementations/react/templates/compositions/content-item/examples/Default.jsx
  src/systems/eu/implementations/react/templates/compositions/content-item/examples/Default.jsx
Labels: process: under review, tag: enhancement

#1293 fix(timeline2): fix alignment - INNO-1763
  src/systems/ec/implementations/vanilla/packages/ec-component-timeline2/ec-component-timeline2.scss
  src/systems/ec/themes/default/aliases/typography.yml
  src/systems/eu/implementations/vanilla/packages/eu-component-timeline2/eu-component-timeline2.scss
  src/systems/eu/themes/default/aliases/typography.yml
Labels: tag: bug fix

#1296 docs(eu-about): eu-values and design principle - INNO-1766 - INNO-1767
  src/website/src/pages/eu/about/digital-design-principles/index.md
  src/website/src/pages/eu/about/digital-design-principles/index.mdx
  src/website/src/pages/eu/about/eu-values/index.md
  src/website/src/pages/eu/about/eu-values/index.mdx
Labels: process: under review, tag: documentation

#1298 fix(tag): fix markup for removable tags - INNO-1753
  src/systems/ec/implementations/react/components/tag/src/Tag.jsx
  src/systems/ec/implementations/react/components/tag/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-tag/ec-component-tag.scss
  src/systems/eu/implementations/react/components/tag/src/Tag.jsx
  src/systems/eu/implementations/react/components/tag/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-tag/eu-component-tag.scss
Labels: tag: bug fix

#1299 docs(link): fix typo - no issue
  src/website/src/pages/ec/components/navigation/link/docs/code.mdx
Labels: process: under review, tag: documentation

#1301 fix(print): add missing utilities - INNO-1773
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-utility-display/ec-utility-display-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-utility-flex/ec-utility-flex-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-dev/src/eu-preset-dev-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-utility-display/eu-utility-display-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-utility-flex/eu-utility-flex-print.scss
Labels: tag: bug fix

#1295 feat(media): improve media utilities - INNO-1765
  .size-limit.json
  src/systems/ec/implementations/react/utilities/media/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-utility-media/ec-utility-media-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-utility-media/ec-utility-media.scss
  src/systems/eu/implementations/react/utilities/media/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-utility-media/eu-utility-media-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-utility-media/eu-utility-media.scss
  src/website/src/pages/ec/utilities/media/docs/code.mdx
  src/website/src/pages/ec/utilities/media/docs/usage.md
  src/website/src/pages/ec/utilities/media/docs/usage.mdx
  src/website/src/pages/ec/utilities/media/index.md
  src/website/src/pages/eu/_utilities/media/docs/code.mdx
  src/website/src/pages/eu/_utilities/media/docs/usage.md
  src/website/src/pages/eu/_utilities/media/docs/usage.mdx
  src/website/src/pages/eu/_utilities/media/index.md
  src/website/src/website-components/Media/Media.scss
Labels: process: under review, tag: enhancement

#1305 docs: fix typo - no issue
  docs/07-developers.md
Labels: tag: documentation

#1303 fix(listing): fix focus on highlighted links - INNO-1814
  src/generic/generic-component-list-item/generic-component-list-item.scss
  src/generic/generic-component-listing/generic-component-listing.scss
Labels: process: under review, tag: bug fix

#1306 docs: add EU vision page - INNO-1775
  src/website/src/pages/eu/about/digital-design-principles/index.mdx
  src/website/src/pages/eu/about/eu-values/index.mdx
  src/website/src/pages/eu/about/vision-mission/index.md
  src/website/src/pages/eu/about/vision/index.mdx
Labels: tag: documentation

#1308 feat(footer-standardised): implement footer for standardised fa…
  src/systems/ec/ec-component/ec-component-footer-standardised/.npmignore
  src/systems/ec/ec-component/ec-component-footer-standardised/README.md
  src/systems/ec/ec-component/ec-component-footer-standardised/ec-component-footer-standardised.config.js
  src/systems/ec/ec-component/ec-component-footer-standardised/ec-component-footer-standardised.scss
  src/systems/ec/ec-component/ec-component-footer-standardised/ec-component-footer-standardised.twig
  src/systems/ec/ec-component/ec-component-footer-standardised/package.json
  src/systems/ec/ec-component/ec-component-footer-standardised/test/spec/.eslintrc
  src/systems/ec/ec-component/ec-component-footer-standardised/test/spec/footers.js
  src/systems/ec/ec-component/ec-component-footer-standardised/test/spec/screenshots/reference/footer-standardised/Windows 10_Chrome_v60.png
  src/systems/ec/ec-component/ec-component-footer-standardised/test/spec/screenshots/reference/footer-standardised/Windows 7_Firefox_v54.png
  src/systems/ec/ec-component/ec-component-footer-standardised/test/spec/screenshots/reference/footer-standardised/Windows 7_IE_v11.png
  src/systems/ec/ec-component/ec-component-footer-standardised/test/spec/screenshots/reference/footer-standardised/macOS 10.12_Safari_v11.png
  src/systems/ec/ec-preset/ec-preset-full/_imports.scss
  src/systems/ec/ec-preset/ec-preset-full/package.json
Labels: process: review needed, tag: new feature

#1309 feat(icons): update facebook icon - INNO-1825
  src/systems/ec/resources/icons/src/branded/facebook.svg
  src/systems/eu/resources/icons/src/branded/facebook.svg
Labels: process: under review, tag: enhancement

#1310 fix(breadcrumb): use ellipsis on long segments - INNO-1826
  src/systems/ec/implementations/vanilla/packages/ec-component-breadcrumb/ec-component-breadcrumb.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-breadcrumb/eu-component-breadcrumb.scss
Labels: process: under review, tag: enhancement

#1311 fix(menu-legacy): add z-index on overlay - INNO-1827
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-legacy/ec-component-menu-legacy.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-menu-legacy/eu-component-menu-legacy.scss
Labels: process: under review, tag: bug fix

#1304 refactor(table): apply latest specs - INNO-1793
  .size-limit.json
  src/systems/ec/implementations/vanilla/packages/ec-component-table/ec-component-table.scss
  src/systems/ec/specs/components/table/demo/data--default.js
  src/systems/ec/specs/components/table/demo/data--multi.js
  src/systems/eu/implementations/vanilla/packages/eu-component-table/eu-component-table.scss
  src/systems/eu/specs/components/table/demo/data--default.js
  src/systems/eu/specs/components/table/demo/data--multi.js
Labels: tag: enhancement
