Repository ec-europa/europa-component-library, pull requests merged in 2019-12, with the labels that each got.

#1437 fix(code-preview): unescape &nbsp - INNO-1756
  src/tools/storybook-addon-code/index.js
  src/website/src/website-components/Code.jsx
  src/website/src/website-components/Playground.jsx
Labels: process: under review, tag: bug fix

#1438 fix(ie11): fix js error - INNO-1988
  src/systems/ec/implementations/react/components/fact-figures/src/FactFigures.jsx
  src/systems/ec/implementations/react/components/fact-figures/src/FactFiguresItem.jsx
  src/systems/ec/implementations/react/components/site-header-core/src/SiteHeaderCore.jsx
  src/systems/ec/implementations/react/components/site-header-harmonised/src/SiteHeaderHarmonised.jsx
  src/systems/ec/implementations/react/components/site-header-standardised/src/SiteHeaderStandardised.jsx
Labels: tag: bug fix

#1439 refactor(tags): add specs - INNO-1968
  src/systems/ec/implementations/react/components/tag/stories/Index.jsx
  src/systems/ec/specs/components/tag/demo/data--button.js
  src/systems/ec/specs/components/tag/demo/data--link.js
  src/systems/ec/specs/components/tag/demo/data--removable.js
  src/systems/eu/implementations/react/components/tag/stories/Index.jsx
  src/systems/eu/specs/components/tag/demo/data--button.js
  src/systems/eu/specs/components/tag/demo/data--link.js
  src/systems/eu/specs/components/tag/demo/data--removable.js
  src/website/src/pages/ec/components/tag/docs/code.mdx
Labels: process: review needed, tag: enhancement

#1430 feat(menu): add component - INNO-1981
  .size-limit.json
  src/systems/ec/implementations/react/components/menu-harmonised/index.js
  src/systems/ec/implementations/react/components/menu-harmonised/package.json
  src/systems/ec/implementations/react/components/menu-harmonised/src/MenuHarmonised.jsx
  src/systems/ec/implementations/react/components/menu-harmonised/src/MenuHarmonisedItem.jsx
  src/systems/ec/implementations/react/components/menu-harmonised/stories/Index.jsx
  src/systems/ec/implementations/react/components/menu-standardised/index.js
  src/systems/ec/implementations/react/components/menu-standardised/package.json
  src/systems/ec/implementations/react/components/menu-standardised/src/MenuStandardised.jsx
  src/systems/ec/implementations/react/components/menu-standardised/src/MenuStandardisedItem.jsx
  src/systems/ec/implementations/react/components/menu-standardised/stories/Index.jsx
  src/systems/ec/implementations/react/components/site-header-harmonised/package.json
  src/systems/ec/implementations/react/components/site-header-harmonised/src/SiteHeaderHarmonised.jsx
  src/systems/ec/implementations/react/components/site-header-harmonised/stories/Index.jsx
  src/systems/ec/implementations/react/components/site-header-standardised/package.json
  src/systems/ec/implementations/react/components/site-header-standardised/src/SiteHeaderStandardised.jsx
  src/systems/ec/implementations/react/components/site-header-standardised/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-harmonised/README.md
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-harmonised/ec-component-menu-harmonised-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-harmonised/ec-component-menu-harmonised.js
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-harmonised/ec-component-menu-harmonised.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-harmonised/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-standardised/README.md
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-standardised/ec-component-menu-standardised-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-standardised/ec-component-menu-standardised.js
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-standardised/ec-component-menu-standardised.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-standardised/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-harmonised/ec-component-site-header-harmonised.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-standardised/ec-component-site-header-standardised.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.js
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.scss
  src/systems/ec/specs/components/menu-harmonised/demo/data.js
  src/systems/ec/specs/components/menu-harmonised/package.json
  src/systems/ec/specs/components/menu-standardised/demo/data--en.js
  src/systems/ec/specs/components/menu-standardised/demo/data--fr.js
  src/systems/ec/specs/components/menu-standardised/package.json
  src/systems/ec/specs/components/site-header-harmonised/demo/data--group1.js
  src/systems/ec/specs/components/site-header-standardised/demo/data--en.js
  src/systems/ec/specs/components/site-header-standardised/demo/data--fr.js
  src/website/src/routes/Redirects.jsx
Labels: tag: new feature

#1440 feat(department): add content type - INNO-1993
  src/systems/ec/implementations/react/templates/pages/department/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/department/index.js
  src/systems/ec/implementations/react/templates/pages/department/package.json
  src/systems/ec/implementations/react/templates/pages/department/src/DepartmentPage.jsx
  src/systems/ec/implementations/react/templates/pages/department/stories/Index.jsx
  src/systems/ec/specs/templates/department-page/demo/data.js
  src/systems/ec/specs/templates/department-page/package.json
  src/website/src/pages/ec/content-types/department/docs/code.mdx
  src/website/src/pages/ec/content-types/department/docs/usage.mdx
  src/website/src/pages/ec/content-types/department/index.md
Labels: process: review needed, tag: new feature

#1441 refactor(calls): split to 2 content types - INNO-1995
  src/website/src/pages/ec/content-types/call/index.md
  src/website/src/pages/ec/content-types/proposals/docs/code.mdx
  src/website/src/pages/ec/content-types/proposals/docs/usage.mdx
  src/website/src/pages/ec/content-types/proposals/index.md
  src/website/src/pages/ec/content-types/tenders/docs/code.mdx
  src/website/src/pages/ec/content-types/tenders/docs/usage.mdx
  src/website/src/pages/ec/content-types/tenders/index.md
Labels: tag: enhancement

#1444 docs(harmonised-group-2): Updates - INNO-1998
  src/website/src/pages/ec/harmonised-templates/docs/group2.mdx
Labels: process: review needed

#1443 feat(language-list): Removing icon in EC and EU - INNO-2001
  src/systems/ec/implementations/react/page-structure/language-list/package.json
  src/systems/ec/implementations/react/page-structure/language-list/src/LanguageListOverlay.jsx
  src/systems/eu/implementations/react/page-structure/language-list/package.json
  src/systems/eu/implementations/react/page-structure/language-list/src/LanguageListOverlay.jsx
Labels: process: review needed, tag: enhancement

#1447 docs(site-header-harmonised): update doc - INNO-2000
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group2.mdx
Labels: process: under review, tag: documentation

#1446 feat(menu): add harmonised group2 + small fixes - INNO-1999
  src/systems/ec/implementations/react/components/menu-harmonised/package.json
  src/systems/ec/implementations/react/components/menu-harmonised/src/MenuHarmonised.jsx
  src/systems/ec/implementations/react/components/menu-harmonised/src/MenuHarmonisedItem.jsx
  src/systems/ec/implementations/react/components/menu-harmonised/stories/Index.jsx
  src/systems/ec/implementations/react/components/menu-standardised/package.json
  src/systems/ec/implementations/react/components/menu-standardised/src/MenuStandardisedItem.jsx
  src/systems/ec/implementations/react/components/site-header-harmonised/src/SiteHeaderHarmonised.jsx
  src/systems/ec/implementations/react/components/site-header-harmonised/stories/Index.jsx
  src/systems/ec/implementations/react/components/site-header-standardised/src/SiteHeaderStandardised.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-harmonised/ec-component-menu-harmonised.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-standardised/ec-component-menu-standardised.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-harmonised/ec-component-site-header-harmonised.scss
  src/systems/ec/resources/icons/src/general/hamburger.svg
  src/systems/ec/specs/components/menu-harmonised/demo/data--group1.js
  src/systems/ec/specs/components/menu-harmonised/demo/data--group2.js
Labels: process: under review, tag: new feature

#1442 feat(content-types): add research areas - INNO-1994
  src/systems/ec/implementations/react/templates/pages/research-area-hub/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-hub/index.js
  src/systems/ec/implementations/react/templates/pages/research-area-hub/package.json
  src/systems/ec/implementations/react/templates/pages/research-area-hub/src/ResearchAreaHubPage.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-hub/stories/Index.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-spoke/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-spoke/index.js
  src/systems/ec/implementations/react/templates/pages/research-area-spoke/package.json
  src/systems/ec/implementations/react/templates/pages/research-area-spoke/src/ResearchAreaSpokePage.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-spoke/stories/Index.jsx
  src/systems/ec/specs/templates/research-area-hub-page/demo/data.js
  src/systems/ec/specs/templates/research-area-hub-page/package.json
  src/systems/ec/specs/templates/research-area-spoke-page/demo/data.js
  src/systems/ec/specs/templates/research-area-spoke-page/package.json
  src/website/src/pages/ec/content-types/research-area/hub/docs/code.mdx
  src/website/src/pages/ec/content-types/research-area/hub/docs/usage.mdx
  src/website/src/pages/ec/content-types/research-area/hub/index.md
  src/website/src/pages/ec/content-types/research-area/index.md
  src/website/src/pages/ec/content-types/research-area/spoke/docs/code.mdx
  src/website/src/pages/ec/content-types/research-area/spoke/docs/usage.mdx
  src/website/src/pages/ec/content-types/research-area/spoke/index.md
Labels: tag: new feature

#1445 fix(site-header-standardised): fix logo position - INNO-1980
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-standardised/ec-component-site-header-standardised.scss
Labels: process: under review, tag: enhancement

#1448 fix(site-headers): Add arrow icon to login link - INNO-1996
  src/systems/ec/implementations/react/components/site-header-core/src/SiteHeaderCore.jsx
  src/systems/ec/implementations/react/components/site-header-harmonised/src/SiteHeaderHarmonised.jsx
  src/systems/ec/implementations/react/components/site-header-standardised/src/SiteHeaderStandardised.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-core/ec-component-site-header-core.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-harmonised/ec-component-site-header-harmonised.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-standardised/ec-component-site-header-standardised.scss
Labels: process: review needed, tag: bug fix

#1451 refactor(menu): all to one - INNO-2007
  package.json
  src/systems/ec/implementations/react/components/menu-harmonised/index.js
  src/systems/ec/implementations/react/components/menu-harmonised/src/MenuHarmonisedItem.jsx
  src/systems/ec/implementations/react/components/menu-harmonised/stories/Index.jsx
  src/systems/ec/implementations/react/components/menu-standardised/index.js
  src/systems/ec/implementations/react/components/menu-standardised/package.json
  src/systems/ec/implementations/react/components/menu-standardised/src/MenuStandardised.jsx
  src/systems/ec/implementations/react/components/menu/index.js
  src/systems/ec/implementations/react/components/menu/package.json
  src/systems/ec/implementations/react/components/menu/src/Menu.jsx
  src/systems/ec/implementations/react/components/menu/src/MenuItem.jsx
  src/systems/ec/implementations/react/components/menu/stories/Index.jsx
  src/systems/ec/implementations/react/components/site-header-harmonised/package.json
  src/systems/ec/implementations/react/components/site-header-harmonised/src/SiteHeaderHarmonised.jsx
  src/systems/ec/implementations/react/components/site-header-harmonised/stories/Index.jsx
  src/systems/ec/implementations/react/components/site-header-standardised/package.json
  src/systems/ec/implementations/react/components/site-header-standardised/src/SiteHeaderStandardised.jsx
  src/systems/ec/implementations/react/components/site-header-standardised/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-harmonised/README.md
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-harmonised/ec-component-menu-harmonised-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-harmonised/ec-component-menu-harmonised.js
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-harmonised/ec-component-menu-harmonised.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-standardised/README.md
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-standardised/ec-component-menu-standardised-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/README.md
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/ec-component-menu-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/ec-component-menu.js
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/ec-component-menu.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.js
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.scss
  src/systems/ec/specs/components/menu-harmonised/package.json
  src/systems/ec/specs/components/menu-standardised/package.json
  src/systems/ec/specs/components/menu/demo/data--en.js
  src/systems/ec/specs/components/menu/demo/data--fr.js
  src/systems/ec/specs/components/menu/demo/data--group1.js
  src/systems/ec/specs/components/menu/demo/data--group2.js
  src/systems/ec/specs/components/menu/package.json
  src/tools/builder/package.json
  src/website/src/pages/ec/components/navigation/menu/docs/api.mdx
  src/website/src/pages/ec/components/navigation/menu/docs/code.mdx
  src/website/src/pages/ec/components/navigation/menu/docs/usage.md
  src/website/src/pages/ec/components/navigation/menu/index.md
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group2.mdx
  src/website/src/pages/ec/standardised-template/site-header/docs/usage.mdx
  src/website/src/routes/Redirects.jsx
  yarn.lock
Labels: tag: enhancement

#1450 refactor(content-types): update research CT - INNO-2010
  src/systems/ec/implementations/react/templates/pages/research-area-hub/src/ResearchAreaHubPage.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-spoke/src/ResearchAreaSpokePage.jsx
Labels: process: under review, tag: enhancement

#1452 feat(site-header-harmonised): add group 3 - INNO-2011
  src/systems/ec/implementations/react/components/site-header-harmonised/src/SiteHeaderHarmonised.jsx
  src/systems/ec/implementations/react/components/site-header-harmonised/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-harmonised/ec-component-site-header-harmonised.scss
  src/systems/ec/specs/components/site-header-harmonised/demo/data--group3.js
Labels: process: under review, tag: new feature

#1456 chore(deps): upgrade dependencies - noissue
  .eslintrc.js
  examples/webpack4-eu/package.json
  examples/webpack4-eu/webpack.config.js
  examples/webpack4/package.json
  examples/webpack4/webpack.config.js
  package.json
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/eu/implementations/react/storybook/package.json
  src/tools/builder/package.json
  src/tools/storybook-addon-code/package.json
  src/tools/storybook-addon-code/utils/codepen.js
  src/website/package.json
  yarn.lock
Labels: tag: internal

#1455 feat(commemorative-coin): add content type demo - INNO-2004
  src/systems/ec/implementations/react/templates/pages/commemorative-coin/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/commemorative-coin/index.js
  src/systems/ec/implementations/react/templates/pages/commemorative-coin/package.json
  src/systems/ec/implementations/react/templates/pages/commemorative-coin/src/CommemorativeCoinPage.jsx
  src/systems/ec/implementations/react/templates/pages/commemorative-coin/stories/Index.jsx
  src/systems/ec/specs/templates/commemorative-coin-page/demo/data.js
  src/systems/ec/specs/templates/commemorative-coin-page/package.json
Labels: process: under review, tag: new feature

#1457 fix(menu): Remove top margin for site-header-harmonised group 2 - INNO-2021
  src/systems/ec/implementations/react/components/menu/src/Menu.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/ec-component-menu.scss
Labels: process: review needed, tag: bug fix

#1460 fix(site-headers): logo alignment and search label on mobile - INNO-2022
  src/systems/ec/implementations/react/components/site-header-core/src/SiteHeaderCore.jsx
  src/systems/ec/implementations/react/components/site-header-standardised/src/SiteHeaderStandardised.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-core/ec-component-site-header-core.scss
Labels: process: under review, tag: bug fix

#1453 feat(footer-harmonised): add group 3 - INNO-2016
  src/systems/ec/implementations/react/components/footer-harmonised/src/FooterHarmonised.jsx
  src/systems/ec/implementations/react/components/footer-harmonised/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-footer-harmonised/ec-component-footer-harmonised.scss
  src/systems/ec/specs/components/footer-harmonised/demo/data--group3.js
  src/website/src/pages/ec/harmonised-templates/footer/docs/group3.mdx
Labels: Approved, tag: new feature

#1463 docs(website): decapitalise labels - INNO-2027
  src/website/src/pages/ec/components/accordion/docs/usage.mdx
  src/website/src/pages/ec/components/blockquote/docs/usage.mdx
  src/website/src/pages/ec/components/expandable/docs/usage.mdx
  src/website/src/pages/ec/components/file/docs/usage.mdx
  src/website/src/pages/ec/components/forms/checkbox/docs/usage.mdx
  src/website/src/pages/ec/components/forms/radio/docs/usage.mdx
  src/website/src/pages/ec/components/forms/search-form/docs/usage.mdx
  src/website/src/pages/ec/components/forms/select/docs/usage.mdx
  src/website/src/pages/ec/components/forms/text-area/docs/usage.mdx
  src/website/src/pages/ec/components/forms/text-field/docs/usage.mdx
  src/website/src/pages/ec/components/language-list/docs/usage.mdx
  src/website/src/pages/ec/components/media/gallery/docs/usage.mdx
  src/website/src/pages/ec/components/media/media-container/docs/usage.mdx
  src/website/src/pages/ec/components/message/docs/usage.mdx
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/usage.mdx
  src/website/src/pages/ec/components/navigation/inpage-navigation/docs/usage.mdx
  src/website/src/pages/ec/components/navigation/pagination/docs/usage.mdx
  src/website/src/pages/ec/components/social-media-follow/docs/usage.mdx
  src/website/src/pages/ec/components/social-media-share/docs/usage.mdx
  src/website/src/pages/ec/components/timeline/docs/usage.mdx
  src/website/src/pages/ec/compositions/content-item/docs/usage.mdx
  src/website/src/pages/ec/compositions/navigation-lists/docs/usage.mdx
  src/website/src/pages/ec/content-types/search/docs/usage.mdx
  src/website/src/pages/ec/core-template/footer/docs/usage.mdx
  src/website/src/pages/ec/core-template/index.mdx
  src/website/src/pages/ec/core-template/page-header/docs/usage.mdx
  src/website/src/pages/ec/core-template/site-header/docs/usage.mdx
  src/website/src/pages/ec/harmonised-templates/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/footer/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/footer/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/footer/docs/group3.mdx
  src/website/src/pages/ec/harmonised-templates/page-header/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/page-header/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group2.mdx
  src/website/src/pages/ec/standardised-template/footer/docs/usage.mdx
  src/website/src/pages/ec/standardised-template/index.mdx
  src/website/src/pages/ec/standardised-template/page-header/docs/usage.mdx
  src/website/src/pages/ec/standardised-template/site-header/docs/usage.mdx
Labels: process: under review, tag: documentation

#1461 docs(facts-figures): add documentation - INNO-2033
  src/website/src/pages/ec/components/fact-figures/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1464 docs(website): replace e.g. with such as - INNO-2028
  src/systems/ec/implementations/vanilla/packages/ec-utility-screen-reader/README.md
  src/systems/eu/implementations/vanilla/packages/eu-utility-screen-reader/README.md
  src/website/src/pages/ec/components/accordion/docs/usage.mdx
  src/website/src/pages/ec/components/blockquote/docs/usage.mdx
  src/website/src/pages/ec/components/forms/radio/docs/usage.mdx
  src/website/src/pages/ec/components/index.mdx
  src/website/src/pages/ec/components/media/gallery/docs/usage.mdx
  src/website/src/pages/ec/components/media/media-container/docs/usage.mdx
  src/website/src/pages/ec/components/navigation/inpage-navigation/docs/api.mdx
  src/website/src/pages/ec/content-types/search/docs/usage.mdx
  src/website/src/pages/ec/guidelines/spacing/index.md
  src/website/src/pages/ec/harmonised-templates/footer/docs/group1.mdx
  src/website/src/pages/ec/standardised-template/footer/docs/usage.mdx
  src/website/src/pages/ec/utilities/grid/index.mdx
Labels: process: under review, tag: documentation

#1466 docs(icon): add documentation - INNO-2036
  src/website/src/pages/ec/components/icon/docs/usage.md
  src/website/src/pages/ec/components/icon/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1465 docs(website): replace ensure with make sure - INNO-2029
  src/systems/ec/implementations/react/templates/pages/campaign/src/CampaignPage.jsx
  src/systems/ec/implementations/react/templates/pages/search/src/SearchPage.jsx
  src/systems/ec/implementations/vanilla/packages/ec-layout-grid/mixins/_grid.scss
  src/systems/ec/specs/components/blockquote/demo/data.js
  src/systems/ec/specs/components/expandable/demo/data.js
  src/systems/ec/specs/utilities/typography/demo/data--paragraph.js
  src/systems/eu/implementations/react/templates/pages/campaign/src/CampaignPage.jsx
  src/systems/eu/implementations/vanilla/packages/eu-layout-grid/mixins/_grid.scss
  src/systems/eu/specs/components/blockquote/demo/data.js
  src/systems/eu/specs/components/expandable/demo/data.js
  src/systems/eu/specs/utilities/typography/demo/data--paragraph.js
  src/website/src/pages/ec/components/blockquote/docs/code.mdx
  src/website/src/pages/ec/components/button/docs/usage.mdx
  src/website/src/pages/ec/components/media/gallery/docs/usage.mdx
  src/website/src/pages/ec/components/media/media-container/docs/usage.mdx
  src/website/src/pages/ec/core-template/footer/docs/usage.mdx
  src/website/src/pages/ec/core-template/index.mdx
  src/website/src/pages/ec/core-template/page-header/docs/usage.mdx
  src/website/src/pages/ec/core-template/site-header/docs/usage.mdx
  src/website/src/pages/ec/getting-started/index.mdx
  src/website/src/pages/ec/harmonised-templates/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/footer/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/footer/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/page-header/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/page-header/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group2.mdx
  src/website/src/pages/ec/standardised-template/footer/docs/usage.mdx
  src/website/src/pages/ec/standardised-template/page-header/docs/usage.mdx
  src/website/src/pages/ec/standardised-template/site-header/docs/usage.mdx
  src/website/src/pages/eu/about/digital-design-principles/index.mdx
Labels: process: under review, tag: documentation

#1467 docs(table): add documentation - INNO-2037
  src/website/src/pages/ec/components/table/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1472 docs(table): lowercasing in tables - INNO-2051
  src/website/src/pages/ec/components/accordion/docs/usage.mdx
  src/website/src/pages/ec/components/blockquote/docs/usage.mdx
  src/website/src/pages/ec/components/button/docs/usage.mdx
  src/website/src/pages/ec/components/expandable/docs/usage.mdx
  src/website/src/pages/ec/components/fact-figures/docs/usage.mdx
  src/website/src/pages/ec/components/file/docs/usage.mdx
  src/website/src/pages/ec/components/forms/checkbox/docs/usage.mdx
  src/website/src/pages/ec/components/forms/radio/docs/usage.mdx
  src/website/src/pages/ec/components/forms/search-form/docs/usage.mdx
  src/website/src/pages/ec/components/forms/select/docs/usage.mdx
  src/website/src/pages/ec/components/forms/text-area/docs/usage.mdx
  src/website/src/pages/ec/components/forms/text-field/docs/usage.mdx
  src/website/src/pages/ec/components/language-list/docs/usage.mdx
  src/website/src/pages/ec/components/media/gallery/docs/usage.mdx
  src/website/src/pages/ec/components/media/media-container/docs/usage.mdx
  src/website/src/pages/ec/components/message/docs/usage.mdx
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/usage.mdx
  src/website/src/pages/ec/components/navigation/inpage-navigation/docs/usage.mdx
  src/website/src/pages/ec/components/social-media-follow/docs/usage.mdx
  src/website/src/pages/ec/components/social-media-share/docs/usage.mdx
  src/website/src/pages/ec/components/tag/docs/usage.mdx
  src/website/src/pages/ec/components/timeline/docs/usage.mdx
  src/website/src/pages/ec/compositions/content-item/docs/usage.mdx
  src/website/src/pages/ec/compositions/navigation-lists/docs/usage.mdx
  src/website/src/pages/ec/content-types/search/docs/usage.mdx
  src/website/src/pages/ec/core-template/footer/docs/usage.mdx
  src/website/src/pages/ec/core-template/index.mdx
  src/website/src/pages/ec/core-template/page-header/docs/usage.mdx
  src/website/src/pages/ec/core-template/site-header/docs/usage.mdx
  src/website/src/pages/ec/guidelines/images/index.md
  src/website/src/pages/ec/harmonised-templates/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/footer/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/footer/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/page-header/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/page-header/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group2.mdx
  src/website/src/pages/ec/standardised-template/footer/docs/usage.mdx
  src/website/src/pages/ec/standardised-template/index.mdx
  src/website/src/pages/ec/standardised-template/page-header/docs/usage.mdx
  src/website/src/pages/ec/standardised-template/site-header/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1468 docs(hg3): add landing page - INNO-2031
  src/website/src/pages/ec/harmonised-templates/docs/group3.mdx
Labels: process: review needed, tag: documentation

#1469 docs(hg3): header + footer - INNO-2032
  src/website/src/pages/ec/harmonised-templates/footer/docs/group3.mdx
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group3.mdx
Labels: process: review needed, tag: documentation

#1470 docs(policy): Adding content - INNO-2039
  src/website/src/pages/ec/content-types/policy/index.md
  src/website/src/pages/ec/content-types/policy/index.mdx
Labels: process: review needed, tag: documentation

#1473 docs(policy): Awareness usage page - INNO-2040
  src/website/src/pages/ec/content-types/policy/awareness/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1481 docs(event): Agenda - INNO-2047
  src/website/src/pages/ec/content-types/events/agenda/docs/usage.md
  src/website/src/pages/ec/content-types/events/agenda/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1476 feat(docs): Legislation, Policy CT - INNO-2044
  src/website/src/pages/ec/content-types/policy/legislation/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1474 feat(docs): Evaluation, Policy CT - INNO-2042
  src/website/src/pages/ec/content-types/policy/evaluation/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1482 docs(events-detail): Adding content - INNO-2048
  src/website/src/pages/ec/content-types/events/detail/docs/usage.md
  src/website/src/pages/ec/content-types/events/detail/docs/usage.mdx
Labels: tag: documentation

#1475 feat(docs): Hub, Policy CT - INNO-2043
  src/website/src/pages/ec/content-types/policy/hub/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1479 docs(policy-resources): Adding content - INNO-2045
  src/website/src/pages/ec/content-types/policy/resources/docs/usage.mdx
Labels: process: under review, tag: documentation

#1478 feat(docs): Background, Policy CT - INNO-2041
  src/website/src/pages/ec/content-types/policy/background/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1483 docs(events-speaker): Adding content - INNO-2049
  src/website/src/pages/ec/content-types/events/speaker/docs/usage.md
  src/website/src/pages/ec/content-types/events/speaker/docs/usage.mdx
Labels: process: under review, tag: documentation

#1487 docs(call-for-proposals): add documentation - INNO-2059
  src/website/src/pages/ec/content-types/call-for-proposals/docs/usage.mdx
Labels: process: under review, tag: documentation

#1485 docs(funding-programme): add documentation - INNO-2056
  src/website/src/pages/ec/content-types/funding-programme/docs/usage.mdx
Labels: Approved, tag: documentation

#1480 docs(events): Adding content - INNO-2046
  .prettierignore
  src/website/src/pages/ec/content-types/events/index.md
  src/website/src/pages/ec/content-types/events/index.mdx
Labels: tag: documentation

#1484 docs(dateblock): add documentation - INNO-2033
  src/website/src/pages/ec/components/date-block/docs/usage.md
  src/website/src/pages/ec/components/date-block/docs/usage.mdx
Labels: tag: documentation

#1471 docs(button): update usage page - INNO-2038
  src/website/src/pages/ec/components/button/docs/usage.mdx
Labels: tag: documentation

#1486 docs(research-area): add documentation - INNO-2060
  src/website/src/pages/ec/content-types/research-area/hub/docs/usage.mdx
  src/website/src/pages/ec/content-types/research-area/spoke/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1488 docs(call-for-tenders): add documentation - INNO-2058
  src/website/src/pages/ec/content-types/call-for-tenders/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1489 docs(department): add documentation - INNO-2057
  src/website/src/pages/ec/content-types/department/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1477 docs(gallery-overlay): Adding content - INNO-2035
  src/website/src/pages/ec/components/media/gallery/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1491 docs(policy): Use links instead of native links - INNO-2039
  .prettierignore
  src/website/src/pages/ec/content-types/policy/index.mdx
Labels: process: review needed, tag: documentation
