Repository ec-europa/europa-component-library, pull requests merged in 2020-01, with the labels that each got.

#1493 docs(spacing): add documentation - INNO-2062
  src/website/src/pages/ec/guidelines/spacing/index.md
  src/website/src/pages/ec/utilities/spacing/docs/usage.md
  src/website/src/pages/ec/utilities/spacing/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1495 docs(website): remove caps - INNO-2025
  src/website/src/pages/ec/components/accordion/docs/usage.mdx
  src/website/src/pages/ec/components/banners/hero-banner/docs/usage.mdx
  src/website/src/pages/ec/components/banners/page-banner/docs/usage.mdx
  src/website/src/pages/ec/components/blockquote/docs/usage.mdx
  src/website/src/pages/ec/components/button/docs/usage.mdx
  src/website/src/pages/ec/components/card/docs/usage.mdx
  src/website/src/pages/ec/components/expandable/docs/usage.mdx
  src/website/src/pages/ec/components/fact-figures/docs/usage.mdx
  src/website/src/pages/ec/components/file/docs/usage.mdx
  src/website/src/pages/ec/components/forms/checkbox/docs/usage.mdx
  src/website/src/pages/ec/components/forms/radio/docs/usage.mdx
  src/website/src/pages/ec/components/forms/search-form/docs/usage.mdx
  src/website/src/pages/ec/components/forms/select/docs/usage.mdx
  src/website/src/pages/ec/components/forms/text-area/docs/usage.mdx
  src/website/src/pages/ec/components/forms/text-field/docs/usage.mdx
  src/website/src/pages/ec/components/language-list/docs/usage.mdx
  src/website/src/pages/ec/components/media/gallery/docs/usage.mdx
  src/website/src/pages/ec/components/media/media-container/docs/usage.mdx
  src/website/src/pages/ec/components/message/docs/usage.mdx
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/usage.mdx
  src/website/src/pages/ec/components/navigation/inpage-navigation/docs/usage.mdx
  src/website/src/pages/ec/components/navigation/pagination/docs/usage.mdx
  src/website/src/pages/ec/components/social-media-follow/docs/usage.mdx
  src/website/src/pages/ec/components/social-media-share/docs/usage.mdx
  src/website/src/pages/ec/components/table/docs/usage.mdx
  src/website/src/pages/ec/components/tag/docs/usage.mdx
  src/website/src/pages/ec/components/timeline/docs/usage.mdx
  src/website/src/pages/ec/compositions/content-item/docs/usage.mdx
  src/website/src/pages/ec/compositions/navigation-lists/docs/usage.mdx
  src/website/src/pages/ec/content-types/search/docs/usage.mdx
  src/website/src/pages/ec/core-template/footer/docs/usage.mdx
  src/website/src/pages/ec/core-template/index.mdx
  src/website/src/pages/ec/core-template/page-header/docs/usage.mdx
  src/website/src/pages/ec/core-template/site-header/docs/usage.mdx
  src/website/src/pages/ec/getting-started/index.mdx
  src/website/src/pages/ec/guidelines/images/index.md
  src/website/src/pages/ec/guidelines/index.md
  src/website/src/pages/ec/guidelines/typography/index.mdx
  src/website/src/pages/ec/harmonised-templates/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/docs/group3.mdx
  src/website/src/pages/ec/harmonised-templates/footer/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/footer/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/footer/docs/group3.mdx
  src/website/src/pages/ec/harmonised-templates/page-header/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/page-header/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group3.mdx
  src/website/src/pages/ec/resources/webtools/index.md
  src/website/src/pages/ec/standardised-template/footer/docs/usage.mdx
  src/website/src/pages/ec/standardised-template/index.mdx
  src/website/src/pages/ec/standardised-template/page-header/docs/usage.mdx
  src/website/src/pages/ec/standardised-template/site-header/docs/usage.mdx
  src/website/src/pages/ec/utilities/background/docs/usage.mdx
  src/website/src/pages/ec/utilities/grid/index.mdx
  src/website/src/pages/ec/utilities/spacing/docs/code.mdx
  src/website/src/pages/ec/utilities/stacks/docs/code.mdx
Labels: process: review needed, tag: documentation

#1494 fix(person-content-type): reorder element on website - INNO-2063
  src/systems/ec/implementations/react/templates/pages/job-person-biography/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-biography/index.js
  src/systems/ec/implementations/react/templates/pages/job-person-biography/package.json
  src/systems/ec/implementations/react/templates/pages/job-person-biography/src/PersonPage.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-biography/stories/Index.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-list/examples/Default.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-list/index.js
  src/systems/ec/implementations/react/templates/pages/job-person-list/package.json
  src/systems/ec/implementations/react/templates/pages/job-person-list/src/PersonListPage.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-list/stories/Index.jsx
  src/website/src/components/Navigation/LinkSection.scss
  src/website/src/components/Navigation/SingleLink.scss
  src/website/src/pages/ec/content-types/job-person/biography/docs/code.mdx
  src/website/src/pages/ec/content-types/job-person/biography/docs/usage.mdx
  src/website/src/pages/ec/content-types/job-person/biography/index.md
  src/website/src/pages/ec/content-types/job-person/index.mdx
  src/website/src/pages/ec/content-types/job-person/person-list/docs/code.mdx
  src/website/src/pages/ec/content-types/job-person/person-list/docs/usage.mdx
  src/website/src/pages/ec/content-types/job-person/person-list/index.md
  src/website/src/pages/ec/content-types/person/index.md
Labels: process: review needed, tag: documentation

#1500 docs(hg3): correction - noissue
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group3.mdx
Labels: tag: documentation

#1501 docs(storybook): group deprecated - INNO-1933
  package.json
  src/systems/ec/implementations/react/deprecated/accordion/index.js
  src/systems/ec/implementations/react/deprecated/accordion/package.json
  src/systems/ec/implementations/react/deprecated/accordion/src/Accordion.jsx
  src/systems/ec/implementations/react/deprecated/accordion/src/AccordionItem.jsx
  src/systems/ec/implementations/react/deprecated/accordion/stories/Index.jsx
  src/systems/ec/implementations/react/deprecated/content-page/examples/Default.jsx
  src/systems/ec/implementations/react/deprecated/content-page/index.js
  src/systems/ec/implementations/react/deprecated/content-page/package.json
  src/systems/ec/implementations/react/deprecated/content-page/src/ContentPage.jsx
  src/systems/ec/implementations/react/deprecated/content-page/stories/Index.jsx
  src/systems/ec/implementations/react/deprecated/footer/index.js
  src/systems/ec/implementations/react/deprecated/footer/package.json
  src/systems/ec/implementations/react/deprecated/footer/src/Footer.jsx
  src/systems/ec/implementations/react/deprecated/footer/stories/Index.jsx
  src/systems/ec/implementations/react/deprecated/menu-legacy/index.js
  src/systems/ec/implementations/react/deprecated/menu-legacy/package.json
  src/systems/ec/implementations/react/deprecated/menu-legacy/src/MenuLegacy.jsx
  src/systems/ec/implementations/react/deprecated/menu-legacy/src/MenuLegacyItem.jsx
  src/systems/ec/implementations/react/deprecated/menu-legacy/stories/Index.jsx
  src/systems/ec/implementations/react/deprecated/page-header/index.js
  src/systems/ec/implementations/react/deprecated/page-header/package.json
  src/systems/ec/implementations/react/deprecated/page-header/src/PageHeader.jsx
  src/systems/ec/implementations/react/deprecated/page-header/stories/Index.jsx
  src/systems/ec/implementations/react/deprecated/site-header/index.js
  src/systems/ec/implementations/react/deprecated/site-header/package.json
  src/systems/ec/implementations/react/deprecated/site-header/src/SiteHeader.jsx
  src/systems/ec/implementations/react/deprecated/site-header/stories/Index.jsx
  src/systems/ec/implementations/react/deprecated/standard/examples/Default.jsx
  src/systems/ec/implementations/react/deprecated/standard/index.js
  src/systems/ec/implementations/react/deprecated/standard/package.json
  src/systems/ec/implementations/react/deprecated/standard/src/StandardPage.jsx
  src/systems/ec/implementations/react/deprecated/standard/stories/Index.jsx
  src/systems/ec/implementations/react/deprecated/timeline/examples/Timeline.jsx
  src/systems/ec/implementations/react/deprecated/timeline/index.js
  src/systems/ec/implementations/react/deprecated/timeline/package.json
  src/systems/ec/implementations/react/deprecated/timeline/src/Timeline.jsx
  src/systems/ec/implementations/react/deprecated/timeline/src/TimelineItem.jsx
  src/systems/ec/implementations/react/deprecated/timeline/stories/Index.jsx
  src/systems/ec/implementations/react/storybook/.storybook/config.js
Labels: process: under review, tag: enhancement

#1496 refactor(content-item): use template - INNO-2019
  .vscode/launch.json
  src/systems/ec/implementations/react/templates/compositions/content-item/examples/Custom.jsx
  src/systems/ec/implementations/react/templates/compositions/content-item/examples/Date.jsx
  src/systems/ec/implementations/react/templates/compositions/content-item/examples/Default.jsx
  src/systems/ec/implementations/react/templates/compositions/content-item/examples/ImageLeft.jsx
  src/systems/ec/implementations/react/templates/compositions/content-item/examples/Simple.jsx
  src/systems/ec/implementations/react/templates/compositions/content-item/index.js
  src/systems/ec/implementations/react/templates/compositions/content-item/package.json
  src/systems/ec/implementations/react/templates/compositions/content-item/src/ContentItem.jsx
  src/systems/ec/implementations/react/templates/compositions/content-item/stories/Index.jsx
  src/systems/ec/implementations/react/templates/pages/commemorative-coin/package.json
  src/systems/ec/implementations/react/templates/pages/commemorative-coin/src/CommemorativeCoinPage.jsx
  src/systems/ec/implementations/react/templates/pages/department/package.json
  src/systems/ec/implementations/react/templates/pages/department/src/DepartmentPage.jsx
  src/systems/ec/implementations/react/templates/pages/event-detail/package.json
  src/systems/ec/implementations/react/templates/pages/event-detail/src/EventDetailPage.jsx
  src/systems/ec/implementations/react/templates/pages/event-speaker/package.json
  src/systems/ec/implementations/react/templates/pages/event-speaker/src/EventSpeakerPage.jsx
  src/systems/ec/implementations/react/templates/pages/funding-programme/package.json
  src/systems/ec/implementations/react/templates/pages/funding-programme/src/FundingProgrammePage.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-biography/package.json
  src/systems/ec/implementations/react/templates/pages/job-person-biography/src/PersonPage.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-list/package.json
  src/systems/ec/implementations/react/templates/pages/job-person-list/src/PersonListPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-awareness/package.json
  src/systems/ec/implementations/react/templates/pages/main-policy-awareness/src/MainPolicyAwarenessPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-evaluation/package.json
  src/systems/ec/implementations/react/templates/pages/main-policy-evaluation/src/MainPolicyEvaluationPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-hub/package.json
  src/systems/ec/implementations/react/templates/pages/main-policy-hub/src/MainPolicyHubPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-legislation/package.json
  src/systems/ec/implementations/react/templates/pages/main-policy-legislation/src/MainPolicyLegislationPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-resources/package.json
  src/systems/ec/implementations/react/templates/pages/main-policy-resources/src/MainPolicyResourcesPage.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-hub/package.json
  src/systems/ec/implementations/react/templates/pages/research-area-hub/src/ResearchAreaHubPage.jsx
  src/systems/ec/implementations/react/templates/pages/search/package.json
  src/systems/ec/implementations/react/templates/pages/search/src/SearchPage.jsx
  src/systems/ec/specs/templates/content-item/demo/data--custom.js
  src/systems/ec/specs/templates/content-item/demo/data--date.js
  src/systems/ec/specs/templates/content-item/demo/data--default.js
  src/systems/ec/specs/templates/content-item/demo/data--image-left.js
  src/systems/ec/specs/templates/content-item/demo/data--simple.js
  src/systems/ec/specs/templates/content-item/package.json
Labels: process: under review, tag: internal

#1502 fix(menus): Hide menu bullet lists for IE/Edge - INNO-2052
  src/systems/ec/implementations/vanilla/packages/ec-component-menu-legacy/ec-component-menu-legacy.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/ec-component-menu.scss
Labels: process: under review, tag: bug fix

#1504 fix(templates): add site name - INNO-2055
  src/systems/ec/specs/templates/call-proposals-page/demo/data.js
  src/systems/ec/specs/templates/call-tenders-page/demo/data.js
  src/systems/ec/specs/templates/commemorative-coin-page/demo/data.js
  src/systems/ec/specs/templates/department-page/demo/data.js
  src/systems/ec/specs/templates/event-agenda-page/demo/data.js
  src/systems/ec/specs/templates/event-detail-page/demo/data.js
  src/systems/ec/specs/templates/event-speaker-page/demo/data.js
  src/systems/ec/specs/templates/funding-programme-page/demo/data.js
  src/systems/ec/specs/templates/main-policy-awareness-page/demo/data.js
  src/systems/ec/specs/templates/main-policy-background-page/demo/data.js
  src/systems/ec/specs/templates/main-policy-evaluation-page/demo/data.js
  src/systems/ec/specs/templates/main-policy-hub-page/demo/data.js
  src/systems/ec/specs/templates/main-policy-legislation-page/demo/data.js
  src/systems/ec/specs/templates/main-policy-resources-page/demo/data.js
  src/systems/ec/specs/templates/person-list-page/demo/data.js
  src/systems/ec/specs/templates/person-page/demo/data.js
  src/systems/ec/specs/templates/research-area-hub-page/demo/data.js
  src/systems/ec/specs/templates/research-area-spoke-page/demo/data.js
  src/systems/ec/specs/templates/search-page/demo/data.js
Labels: process: under review, tag: bug fix

#1499 refactor(menu): menu improvements - INNO-2005
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/ec-component-menu.js
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/ec-component-menu.scss
  src/systems/ec/specs/components/menu/demo/data--en.js
Labels: tag: enhancement

#1509 fix(website): display image thumbnails for IE Edge - INNO-2085
  src/website/src/website-components/Thumbnail/Thumbnail.scss
Labels: process: under review, tag: bug fix

#1508 docs(commemorative-coin): add doc - INNO-2086
  src/website/src/pages/ec/content-types/commemorative-coin/docs/usage.mdx
Labels: process: under review, tag: documentation

#1510 docs(events): update doc - INNO-2087
  src/website/src/pages/ec/content-types/events/agenda/docs/usage.mdx
  src/website/src/pages/ec/content-types/events/detail/docs/usage.mdx
  src/website/src/pages/ec/content-types/events/index.mdx
  src/website/src/pages/ec/content-types/events/speaker/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1512 docs(research-area): update doc - INNO-2089
  src/website/src/pages/ec/content-types/research-area/index.md
  src/website/src/pages/ec/content-types/research-area/index.mdx
  src/website/src/pages/ec/content-types/research-area/spoke/docs/usage.mdx
Labels: process: under review, tag: documentation

#1514 fix(menu): improve booolean data management - INNO-2024
  src/systems/ec/implementations/react/components/menu/src/MenuItem.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/ec-component-menu.js
Labels: tag: bug fix

#1511 docs(job-person): update doc - INNO-2088
  .prettierignore
  src/website/src/pages/ec/content-types/job-person/biography/docs/usage.mdx
  src/website/src/pages/ec/content-types/job-person/index.mdx
  src/website/src/pages/ec/content-types/job-person/person-list/docs/usage.mdx
Labels: tag: documentation

#1515 docs(components): add missing components images - INNO-2074
  src/website/src/pages/ec/components/date-block/ec_comp_date_blocks.svg
  src/website/src/pages/ec/components/fact-figures/ec_comp_facts_and_figures.svg
  src/website/src/pages/ec/components/forms/checkbox/ec_comp_checkbox.svg
  src/website/src/pages/ec/components/forms/file-upload/ec_comp_file_upload.svg
  src/website/src/pages/ec/components/index.mdx
  src/website/src/pages/ec/components/language-list/ec_comp_language_list.svg
  src/website/src/pages/ec/components/navigation/menu/ec_comp_menu.svg
  src/website/src/pages/ec/components/table/ec_comp_table.svg
Labels: process: review needed, tag: documentation

#1513 fix(data): fix data file name - INNO-2081
  src/systems/ec/implementations/react/components/breadcrumb-core/stories/Index.jsx
  src/systems/ec/implementations/react/components/breadcrumb-harmonised/stories/Index.jsx
  src/systems/ec/implementations/react/components/breadcrumb-standardised/stories/Index.jsx
  src/systems/ec/implementations/react/components/breadcrumb/stories/Index.jsx
  src/systems/ec/implementations/react/components/inpage-navigation/examples/Default.jsx
  src/systems/ec/implementations/react/deprecated/content-page/examples/Default.jsx
  src/systems/ec/implementations/react/deprecated/page-header/stories/Index.jsx
  src/systems/ec/implementations/react/deprecated/standard/examples/Default.jsx
  src/systems/ec/specs/components/breadcrumb-core/demo/data--simple.js
  src/systems/ec/specs/components/breadcrumb-harmonised/demo/data--simple.js
  src/systems/ec/specs/components/breadcrumb-standardised/demo/data--simple.js
  src/systems/ec/specs/components/breadcrumb/demo/data--simple.js
  src/systems/ec/specs/components/page-header/demo/data--events-description.js
  src/systems/ec/specs/components/page-header/demo/data--events.js
  src/systems/ec/specs/components/page-header/demo/data--meta-title-description.js
  src/systems/ec/specs/components/page-header/demo/data--meta-title.js
  src/systems/ec/specs/components/page-header/demo/data--title-description.js
  src/systems/ec/specs/components/page-header/demo/data--title.js
  src/systems/eu/implementations/react/components/breadcrumb/stories/Index.jsx
  src/systems/eu/implementations/react/components/inpage-navigation/examples/Default.jsx
  src/systems/eu/implementations/react/page-structure/page-header/stories/Index.jsx
  src/systems/eu/implementations/react/templates/pages/standard/examples/Default.jsx
  src/systems/eu/specs/components/breadcrumb/demo/data--simple.js
  src/systems/eu/specs/components/page-header/demo/data--basic.js
  src/systems/eu/specs/components/page-header/demo/data--branded-homepage-image.js
  src/systems/eu/specs/components/page-header/demo/data--branded-homepage.js
  src/systems/eu/specs/components/page-header/demo/data--events-description.js
  src/systems/eu/specs/components/page-header/demo/data--events.js
  src/systems/eu/specs/components/page-header/demo/data--homepage-image.js
  src/systems/eu/specs/components/page-header/demo/data--homepage.js
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/code.mdx
Labels: tag: internal

#1426 feat(datepicker): Add component - INNO-1599
  .size-limit.json
  docs/decisions/004-datepicker.md
  src/systems/ec/implementations/react/components/datepicker/index.js
  src/systems/ec/implementations/react/components/datepicker/package.json
  src/systems/ec/implementations/react/components/datepicker/src/Datepicker.jsx
  src/systems/ec/implementations/react/components/datepicker/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-form-datepicker/README.md
  src/systems/ec/implementations/vanilla/packages/ec-component-form-datepicker/ec-component-form-datepicker-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-datepicker/ec-component-form-datepicker.js
  src/systems/ec/implementations/vanilla/packages/ec-component-form-datepicker/ec-component-form-datepicker.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-datepicker/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.js
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.scss
  src/systems/ec/specs/components/datepicker/demo/data.js
  src/systems/ec/specs/components/datepicker/package.json
  src/website/src/pages/ec/components/forms/datepicker/docs/api.mdx
  src/website/src/pages/ec/components/forms/datepicker/docs/code.mdx
  src/website/src/pages/ec/components/forms/datepicker/docs/usage.mdx
  src/website/src/pages/ec/components/forms/datepicker/ec_comp_text_field.svg
  src/website/src/pages/ec/components/forms/datepicker/index.md
  yarn.lock
Labels: process: review needed, tag: new feature

#1516 chore(deps): upgrade babel and other dependencies - INNO-2091
  .drone.yml
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  patches/@storybook+addon-a11y+5.2.6.patch
  patches/@storybook+addon-cssresources+5.2.6.patch
  src/systems/ec/implementations/react/storybook/.storybook/webpack.config.js
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/resources/icons/package.json
  src/systems/eu/implementations/react/storybook/.storybook/webpack.config.js
  src/systems/eu/implementations/react/storybook/package.json
  src/tools/builder/package.json
  src/tools/storybook-addon-code/package.json
  src/website/config/babel.config.js
  src/website/package.json
  yarn.lock
Labels: tag: internal

#1520 chore(storybook): upgrade to 5.3 - INNO-2075
  package.json
  src/systems/ec/implementations/react/components/card/stories/Index.jsx
  src/systems/ec/implementations/react/components/card/stories/Template.jsx
  src/systems/ec/implementations/react/storybook/.storybook/addons.js
  src/systems/ec/implementations/react/storybook/.storybook/main.js
  src/systems/ec/implementations/react/storybook/.storybook/manager.js
  src/systems/ec/implementations/react/storybook/.storybook/presets.js
  src/systems/ec/implementations/react/storybook/.storybook/preview.js
  src/systems/ec/implementations/react/storybook/.storybook/webpack.config.js
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/eu/implementations/react/components/card/stories/Index.jsx
  src/systems/eu/implementations/react/components/card/stories/Template.jsx
  src/systems/eu/implementations/react/storybook/.storybook/addons.js
  src/systems/eu/implementations/react/storybook/.storybook/main.js
  src/systems/eu/implementations/react/storybook/.storybook/manager-head.html
  src/systems/eu/implementations/react/storybook/.storybook/manager.js
  src/systems/eu/implementations/react/storybook/.storybook/presets.js
  src/systems/eu/implementations/react/storybook/.storybook/preview.js
  src/systems/eu/implementations/react/storybook/.storybook/webpack.config.js
  src/systems/eu/implementations/react/storybook/package.json
  src/tools/storybook-addon-code/package.json
  src/website/package.json
  yarn.lock
Labels: process: under review, tag: internal

#1527 fix(select): add required attribute - FRONT-11
  src/systems/ec/implementations/react/components/select/src/Select.jsx
Labels: process: review needed, tag: bug fix

#1528 docs(footer-harmonised-1): update doc - FRONT-148
  src/website/src/pages/ec/harmonised-templates/footer/docs/group1.mdx
Labels: process: review needed, tag: documentation

#1529 docs(page-header-harmonised-1): update doc - FRONT-144
  src/website/src/pages/ec/harmonised-templates/page-header/docs/group1.mdx
Labels: process: review needed, tag: documentation
