Repository ec-europa/europa-component-library, pull requests merged in 2020-06, with the labels that each got.

#1594 docs(menu): add usage page - FRONT-1164
  src/website/src/pages/ec/components/navigation/menu/docs/usage.md
  src/website/src/pages/ec/components/navigation/menu/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1596 feat(gallery): improve gallery - FRONT-1168
  src/systems/ec/implementations/react/components/gallery/src/Gallery.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/ec-component-gallery.js
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/ec-component-gallery.scss
  src/systems/ec/specs/components/gallery/demo/data.js
Labels: process: WIP, tag: enhancement

#1602 docs(hero-banner): update usage page - FRONT-1175
  src/website/src/pages/ec/components/banners/hero-banner/docs/usage.mdx
Labels: process: WIP, tag: documentation

#1601 chore(deps): upgrade deps with vulnerabilities - FRONT-1172
  package.json
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/eu/implementations/react/storybook/package.json
  src/tools/storybook-addon-code/package.json
  yarn.lock
Labels: process: under review, tag: internal

#1606 fix(inpage-navigation): fix hidden attribute - FRONT-1170
  src/systems/ec/implementations/react/components/inpage-navigation/src/InpageNavigation.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-inpage-navigation/ec-component-inpage-navigation.js
  src/systems/ec/implementations/vanilla/packages/ec-component-inpage-navigation/ec-component-inpage-navigation.scss
Labels: tag: bug fix

#1607 chore(node): upgrade to erbium - FRONT-1228
  .drone.yml
  .nvmrc
  package.json
  yarn.lock
Labels: process: under review, tag: internal

#1608 feat(link): adding aria-label to EC and EU link component-FRONT-1239
  src/systems/ec/implementations/react/components/link/src/Link.jsx
  src/systems/ec/implementations/react/components/link/stories/Index.jsx
  src/systems/ec/specs/components/link/demo/data--cta-icon.js
  src/systems/ec/specs/components/link/demo/data--cta.js
  src/systems/ec/specs/components/link/demo/data--default.js
  src/systems/ec/specs/components/link/demo/data--icon.js
  src/systems/ec/specs/components/link/demo/data--standalone.js
  src/systems/eu/implementations/react/components/link/src/Link.jsx
  src/systems/eu/implementations/react/components/link/stories/Index.jsx
  src/systems/eu/specs/components/link/demo/data--cta-icon.js
  src/systems/eu/specs/components/link/demo/data--cta.js
  src/systems/eu/specs/components/link/demo/data--default.js
  src/systems/eu/specs/components/link/demo/data--icon.js
  src/systems/eu/specs/components/link/demo/data--standalone.js
Labels: tag: enhancement

#1610 chore(ci): use github actions for building previews - FRONT-1250
  .github/workflows/ci.yml
Labels: tag: internal
