Repository ec-europa/europa-component-library, pull requests merged in 2020-12, with the labels that each got.

#1791 feat(gallery): Add embedded iframe video support - FRONT-1824
  src/implementations/twig/components/gallery/README.md
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/twig/components/gallery/gallery-item.html.twig
  src/implementations/twig/components/gallery/gallery.html.twig
  src/implementations/twig/components/gallery/gallery.test.js
  src/implementations/vanilla/components/gallery/gallery.js
  src/implementations/vanilla/components/gallery/gallery.scss
  src/implementations/vanilla/components/gallery/package.json
  src/implementations/vanilla/components/media-container/media-container.scss
  src/implementations/vanilla/components/media-container/package.json
  src/implementations/vanilla/utilities/media/media-print.scss
  src/implementations/vanilla/utilities/media/media.scss
  src/specs/components/gallery/demo/data.js
Labels: Approved, tag: enhancement

#1794 feat(storybook): Adding EU instance - FRONT-1684
  package.json
  scripts/dist-storybook.sh
  src/implementations/twig/components/site-header-harmonised/site-header-harmonised.story.js
  src/implementations/twig/storybook/ec/.storybook/ECL.jsx
  src/implementations/twig/storybook/ec/.storybook/environment.js
  src/implementations/twig/storybook/ec/.storybook/main.js
  src/implementations/twig/storybook/ec/.storybook/manager-head.html
  src/implementations/twig/storybook/ec/.storybook/manager.js
  src/implementations/twig/storybook/ec/.storybook/preview-head.html
  src/implementations/twig/storybook/ec/.storybook/preview.js
  src/implementations/twig/storybook/ec/package.json
  src/implementations/twig/storybook/eu/.storybook/ECL.jsx
  src/implementations/twig/storybook/eu/.storybook/environment.js
  src/implementations/twig/storybook/eu/.storybook/main.js
  src/implementations/twig/storybook/eu/.storybook/manager-head.html
  src/implementations/twig/storybook/eu/.storybook/manager.js
  src/implementations/twig/storybook/eu/.storybook/preview-head.html
  src/implementations/twig/storybook/eu/.storybook/preview.js
  src/implementations/twig/storybook/eu/package.json
  src/presets/ec-preset-website/package.json
  src/tools/test-utils/index.js
  src/website/package.json
  src/website/scripts/copy.sh
  src/website/webpack.config.dev.js
  src/website/webpack.config.prod.js
Labels: process: review needed, tag: new feature

#1796 docs(harmonised-templates): Add documentation landing page - FRONT-1827
  src/website/src/pages/ec/harmonised-templates/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/docs/group3.mdx
Labels: tag: documentation

#1798 docs(grid): Correct grid breakpoint column definition - FRONT-1831
  src/website/src/pages/ec/utilities/layout/grid/index.mdx
Labels: process: under review, tag: documentation

#1805 chore: fix responsive grid - FRONT-1831
  src/implementations/twig/layout/grid/examples/responsive.html
  src/website/src/pages/ec/components/navigation/inpage-navigation/examples/default.html
Labels: Approved, tag: bug fix

#1799 docs(checkbox): Fix checkbox which remains active in showcase - FRONT-1834
  src/website/src/pages/ec/components/forms/checkbox/docs/code.mdx
  src/website/src/pages/ec/components/forms/radio/docs/code.mdx
Labels: process: under review, tag: bug fix

#1797 docs(components): Add documentation landing page - FRONT-1828
  src/website/src/pages/ec/components/banners/page-banner/ec_comp_page_banner.svg
  src/website/src/pages/ec/components/index.mdx
  src/website/src/pages/ec/components/list/ec_comp_lists.svg
  src/website/src/pages/ec/components/media/media-container/ec_comp_media_container.svg
  src/website/src/pages/ec/components/navigation/inpage-navigation/ec_comp_inpage-navigation.svg
  src/website/src/pages/ec/components/social-media-follow/ec_comp_social_follow.svg
Labels: process: review needed, tag: documentation

#1801 fix(expandable): Add default paragraph tag in component data for spacing - FRONT-1837
  src/implementations/twig/components/expandable/README.md
  src/implementations/twig/components/expandable/__snapshots__/expandable.test.js.snap
  src/specs/components/expandable/demo/data.js
Labels: process: under review, tag: enhancement

#1802 docs(getting-started): Remove component status section - FRONT-1839
  src/website/src/components/Navigation/SingleLink.jsx
  src/website/src/pages/ec/getting-started/index.mdx
Labels: process: review needed, tag: documentation

#1806 fix(select): Align multiple select top margin with default select variant - FRONT-1843
  src/implementations/vanilla/components/form/form.scss
Labels: process: under review, tag: bug fix

#1807 fix(grid): Fix grid display example in documentation page - FRONT-1840
  src/website/src/pages/ec/utilities/grid/index.mdx
Labels: process: under review, tag: bug fix

#1800 docs(utilities): add missing docs - FRONT-1786
  src/implementations/twig/utilities/clearfix/index.story.js
  src/implementations/twig/utilities/dimension/index.story.js
  src/implementations/twig/utilities/disablescroll/index.story.js
  src/implementations/twig/utilities/display/index.story.js
  src/implementations/twig/utilities/float/index.story.js
  src/implementations/twig/utilities/z-index/index.story.js
  src/website/src/pages/ec/utilities/clearfix/docs/usage.mdx
  src/website/src/pages/ec/utilities/clearfix/index.md
  src/website/src/pages/ec/utilities/disablescroll/docs/usage.mdx
  src/website/src/pages/ec/utilities/disablescroll/index.md
  src/website/src/pages/ec/utilities/float/docs/usage.mdx
  src/website/src/pages/ec/utilities/float/index.md
  src/website/src/pages/ec/utilities/screen-reader/docs/usage.mdx
  src/website/src/pages/ec/utilities/screen-reader/index.md
  src/website/src/pages/ec/utilities/z-index/docs/usage.mdx
  src/website/src/pages/ec/utilities/z-index/index.md
  src/website/src/preval/get-meta-ec.js
Labels: process: under review, tag: documentation

#1811 docs(website): switch EC/EU logo - FRONT-1753
  src/website/src/components/Navigation/Navigation.jsx
  src/website/src/components/Navigation/Navigation.scss
Labels: tag: enhancement

#1808 docs: init migration notes - FRONT-1835
  docs/Migrating-v3.md
Labels: tag: documentation

#1790 feat(eu-footer): add eu footer - FRONT-1813
  src/implementations/twig/components/footer-core/__snapshots__/footer-core.test.js.snap
  src/implementations/twig/components/footer-core/footer-core.html.twig
  src/implementations/twig/components/footer-core/footer-core.story.js
  src/implementations/twig/components/footer-core/footer-core.test.js
  src/implementations/twig/components/footer-core/package.json
  src/implementations/vanilla/components/footer-core/footer-core-ec.scss
  src/implementations/vanilla/components/footer-core/footer-core-eu.scss
  src/presets/dev/src/dev.scss
  src/presets/ec-core/src/ec-core.scss
  src/presets/eu-core/src/eu-core.scss
  src/specs/components/footer-core/demo/data--ec.js
  src/specs/components/footer-core/demo/data--eu.js
  src/website/src/pages/ec/core-template/footer/demo/index.js
Labels: tag: new feature

#1816 fix(videos): Fix broken video url for media-container and gallery components - FRONT-1906
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/twig/components/media-container/__snapshots__/media-container.test.js.snap
  src/specs/components/gallery/demo/data.js
  src/specs/components/media-container/demo/data--video.js
Labels: process: under review, tag: bug fix

#1815 fix(campaign): Fix hero-banner and media-container video display - FRONT-1842
  src/systems/ec/implementations/react/templates/pages/campaign/stories/Index.jsx
  src/systems/ec/specs/components/gallery/demo/data.js
  src/systems/ec/specs/components/media-container/demo/data--video.js
  src/systems/eu/specs/components/gallery/demo/data.js
  src/systems/eu/specs/components/media-container/demo/data--video.js
Labels: process: under review, tag: bug fix

#1809 feat(storybook-system-switcher): Adding widget in the toolbar - FRONT-1836
  .eslintignore
  package.json
  src/implementations/twig/storybook/ec/.storybook/main.js
  src/implementations/twig/storybook/ec/.storybook/preview.js
  src/implementations/twig/storybook/eu/.storybook/main.js
  src/implementations/twig/storybook/eu/.storybook/preview.js
  src/playground/addons/.eslintrc.js
  src/playground/addons/story-utils/README.md
  src/playground/addons/story-utils/package.json
  src/playground/addons/story-utils/src/index.js
  src/playground/addons/story-wrapper/.eslintrc.js
  src/playground/addons/story-wrapper/StoryWrapper.jsx
  src/playground/addons/story-wrapper/package.json
  src/playground/addons/storybook-addon-code/README.md
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-code/src/index.js
  src/playground/addons/storybook-addon-code/src/register.jsx
  src/playground/addons/storybook-addon-notes/README.md
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-notes/src/index.js
  src/playground/addons/storybook-addon-notes/src/register.jsx
  src/playground/addons/storybook-addon-system-switcher/README.md
  src/playground/addons/storybook-addon-system-switcher/index.js
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/addons/storybook-addon-system-switcher/register.jsx
  src/playground/addons/storybook-addon-system-switcher/systemSwitcher.jsx
  src/tools/storybook-addon-code/package.json
  yarn.lock
Labels: process: under review, tag: new feature

#1804 fix(date-block): Fix sr-only date label display - FRONT-1841
  src/implementations/vanilla/components/date-block/date-block.scss
  src/implementations/vanilla/utilities/screen-reader/screen-reader.scss
Labels: process: review needed, tag: bug fix

#1795 feat: codepen storybook addon - FRONT-1785
  package.json
  scripts/dist-storybook.sh
  src/playground/addons/storybook-addon-code/.eslintrc.js
  src/playground/addons/storybook-addon-code/HTMLMarkup.jsx
  src/playground/addons/storybook-addon-code/README.md
  src/playground/addons/storybook-addon-code/codepen.js
  src/playground/addons/storybook-addon-code/constants.js
  src/playground/addons/storybook-addon-code/index.js
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-code/register.jsx
  src/playground/addons/storybook-addon-code/src/index.js
  src/playground/addons/storybook-addon-code/src/register.jsx
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/.storybook/ECL.jsx
  src/playground/ec/.storybook/environment.js
  src/playground/ec/.storybook/main.js
  src/playground/ec/.storybook/manager-head.html
  src/playground/ec/.storybook/manager.js
  src/playground/ec/.storybook/preview-head.html
  src/playground/ec/.storybook/preview.js
  src/playground/ec/package.json
  src/playground/eu/.storybook/ECL.jsx
  src/playground/eu/.storybook/environment.js
  src/playground/eu/.storybook/main.js
  src/playground/eu/.storybook/manager-head.html
  src/playground/eu/.storybook/manager.js
  src/playground/eu/.storybook/preview-head.html
  src/playground/eu/.storybook/preview.js
  src/playground/eu/package.json
  yarn.lock
Labels: tag: new feature

#1818 feat(controls): Button, migrate knobs to controls - FRONT-1857
  src/implementations/twig/components/button/button.story.js
  src/playground/ec/.storybook/main.js
  src/playground/ec/.storybook/preview.js
  src/playground/ec/package.json
  src/playground/eu/.storybook/main.js
  src/playground/eu/.storybook/preview.js
  src/playground/eu/package.json
  yarn.lock
Labels: process: review needed, tag: enhancement

#1814 feat(footer): add EU footer standardised - FRONT-1905
  docs/Migrating-v3.md
  src/implementations/twig/components/footer-core/README.md
  src/implementations/twig/components/footer-core/footer-core.html.twig
  src/implementations/twig/components/footer-standardised/README.md
  src/implementations/twig/components/footer-standardised/__snapshots__/footer-standardised.test.js.snap
  src/implementations/twig/components/footer-standardised/footer-standardised.html.twig
  src/implementations/twig/components/footer-standardised/footer-standardised.story.js
  src/implementations/twig/components/footer-standardised/footer-standardised.test.js
  src/implementations/vanilla/components/footer-core/footer-core-eu.scss
  src/implementations/vanilla/components/footer-standardised/footer-standardised-ec.scss
  src/implementations/vanilla/components/footer-standardised/footer-standardised-eu.scss
  src/presets/dev/src/dev.scss
  src/presets/ec-core/src/ec-core.scss
  src/presets/eu-core/src/eu-core.scss
  src/specs/components/footer-standardised/demo/data--ec.js
  src/specs/components/footer-standardised/demo/data--eu.js
  src/website/src/pages/ec/standardised-template/footer/demo/index.js
Labels: Approved, tag: new feature

#1823 feat(controls): Breadcrumb core, migrate knobs to controls - FRONT-1849
  src/implementations/twig/components/breadcrumb-core/breadcrumb-core.story.js
Labels: process: under review, tag: enhancement

#1824 feat(controls): Breadcrumb standardised, migrate knobs to controls - FRONT-1851
  src/implementations/twig/components/breadcrumb-standardised/breadcrumb-standardised.story.js
Labels: process: under review, tag: enhancement

#1825 feat(controls): Breadcrumb harmonised, migrate knobs to controls - FRONT-1850
  src/implementations/twig/components/breadcrumb-harmonised/breadcrumb-harmonised.story.js
Labels: process: under review, tag: enhancement

#1819 feat(controls): Blockquote, migrate knobs to controls - FRONT-1848
  src/implementations/twig/components/blockquote/blockquote.story.js
  src/playground/ec/package.json
  src/playground/eu/package.json
  yarn.lock
Labels: process: under review, tag: enhancement

#1820 feat(controls): Accordion, migrate knobs to controls - FRONT-1847
  src/implementations/twig/components/accordion/accordion.story.js
  src/playground/addons/storybook-addon-system-switcher/systemSwitcher.jsx
  yarn.lock
Labels: tag: enhancement

#1822 feat(controls): Link, migrate knobs to controls - FRONT-1853
  src/implementations/twig/components/link/link.html.twig
  src/implementations/twig/components/link/link.story.js
Labels: tag: enhancement

#1826 feat(date-block): add controls - FRONT-1867
  docs/Migrating-v3.md
  src/implementations/twig/components/date-block/date-block.story.js
  src/implementations/twig/components/date-block/package.json
Labels: tag: new feature

#1817 feat(footer): update EC footers - FRONT-1907
  src/implementations/twig/components/footer-core/__snapshots__/footer-core.test.js.snap
  src/implementations/twig/components/footer-harmonised/README.md
  src/implementations/twig/components/footer-harmonised/__snapshots__/footer-harmonised.test.js.snap
  src/implementations/twig/components/footer-harmonised/footer-harmonised.html.twig
  src/implementations/twig/components/footer-harmonised/footer-harmonised.story.js
  src/implementations/twig/components/footer-standardised/__snapshots__/footer-standardised.test.js.snap
  src/implementations/vanilla/components/footer-core/footer-core-ec.scss
  src/implementations/vanilla/components/footer-harmonised/footer-harmonised.scss
  src/implementations/vanilla/components/footer-standardised/footer-standardised-ec.scss
  src/specs/components/footer-core/demo/data--ec.js
  src/specs/components/footer-harmonised/demo/data--group1.js
  src/specs/components/footer-harmonised/demo/data--group2.js
  src/specs/components/footer-standardised/demo/data--ec.js
Labels: process: review needed, tag: enhancement

#1827 chore: global system context - FRONT-1838
  docs/Migrating-v3.md
  src/playground/addons/story-utils/index.js
  src/playground/addons/story-utils/package.json
  src/playground/addons/story-wrapper/.eslintrc.js
  src/playground/addons/story-wrapper/StoryWrapper.jsx
  src/playground/addons/story-wrapper/package.json
  src/playground/addons/storybook-addon-code/.eslintrc.js
  src/playground/addons/storybook-addon-code/codepen.js
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/index.js
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-notes/register.jsx
  src/playground/addons/storybook-addon-system-switcher/Switcher.jsx
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/addons/storybook-addon-system-switcher/register.jsx
  src/playground/ec/.storybook/main.js
  src/playground/eu/.storybook/main.js
  src/presets/ec-core/package.json
  src/presets/eu-core/package.json
  src/tools/builder/bin/build.js
  src/tools/builder/builder.test.js
  src/tools/builder/package.json
  src/tools/builder/scripts/copy.js
  src/tools/builder/scripts/styles.js
  src/tools/builder/utils/getSystem.js
  yarn.lock
Labels: process: under review, tag: internal

#1831 feat(skip-link): Add controls - FRONT-1856
  src/implementations/twig/components/skip-link/skip-link.story.js
Labels: process: under review, tag: enhancement

#1833 feat(controls): Card, replacing knobs with controls - FRONT-1858
  src/implementations/twig/components/card/card.story.js
Labels: process: under review, tag: enhancement

#1828 feat(inpage-navigation): Migrate knobs to controls - FRONT-1852
  src/implementations/twig/components/breadcrumb-core/breadcrumb-core.story.js
  src/implementations/twig/components/breadcrumb-harmonised/breadcrumb-harmonised.story.js
  src/implementations/twig/components/breadcrumb-standardised/breadcrumb-standardised.story.js
  src/implementations/twig/components/button/button.story.js
  src/implementations/twig/components/inpage-navigation/inpage-navigation.story.js
  src/implementations/twig/components/link/link.story.js
  src/playground/addons/story-utils/index.js
  src/playground/addons/story-utils/package.json
  yarn.lock
Labels: process: review needed, tag: enhancement

#1832 feat(preset): remove preset full - FRONT-1916
  docs/Migrating-v3.md
  scripts/dist-presets.sh
  src/presets/ec-preset-full/.npmignore
  src/presets/ec-preset-full/README.md
  src/presets/ec-preset-full/ecl-builder.config.js
  src/presets/ec-preset-full/package.json
  src/presets/ec-preset-full/src/ec-preset-full-print.scss
  src/presets/ec-preset-full/src/ec-preset-full.js
  src/presets/ec-preset-full/src/ec-preset-full.scss
  src/website/package.json
  src/website/scripts/copy.sh
Labels: process: review needed, tag: internal

#1830 feat(pagination): Remove knobs - FRONT-1855
  src/implementations/twig/components/accordion/accordion.story.js
  src/implementations/twig/components/pagination/__snapshots__/pagination.test.js.snap
  src/implementations/twig/components/pagination/pagination.html.twig
  src/implementations/twig/components/pagination/pagination.story.js
Labels: tag: enhancement

#1834 feat(checkbox): Migrate knobs to controls- FRONT- 1859
  src/implementations/twig/components/blockquote/blockquote.story.js
  src/implementations/twig/components/checkbox/checkbox.story.js
  src/implementations/twig/components/date-block/date-block.story.js
  src/playground/addons/story-utils/index.js
Labels: tag: enhancement

#1835 feat(controls): Datepicker, replacing knobs with controls - FRONT-1860
  src/implementations/twig/components/datepicker/datepicker.story.js
  src/playground/addons/story-utils/index.js
Labels: tag: enhancement

#1829 feat(menu): Remove knobs - FRONT-1854
  src/implementations/twig/components/menu/menu.story.js
Labels: process: under review, tag: enhancement

#1836 feat(radio): Add controls - FRONT-1862
  src/implementations/twig/components/radio/radio.story.js
Labels: process: under review, tag: enhancement

#1837 feat: ecl-builder watch task - FRONT-1735
  docs/Migrating-v3.md
  package.json
  src/playground/ec/package.json
  src/playground/ec/start.js
  src/playground/eu/package.json
  src/playground/eu/start.js
  src/presets/ec-core/.npmignore
  src/presets/ec-core/ecl-builder.config.js
  src/presets/ec-core/package.json
  src/presets/eu-core/.npmignore
  src/presets/eu-core/ecl-builder.config.js
  src/presets/eu-core/package.json
  src/tools/builder/README.md
  src/tools/builder/bin/build.js
  src/tools/builder/package.json
  src/tools/builder/scripts/watch.js
  yarn.lock
Labels: process: under review, tag: new feature

#1841 fix(link): remove unused parameter - FRONT-1919
  docs/Migrating-v3.md
  src/implementations/twig/components/link/link.html.twig
Labels: tag: enhancement

#1838 feat(controls): Expandable, adding controls - FRONT-1871
  src/implementations/twig/components/expandable/expandable.story.js
  src/specs/components/expandable/demo/data.js
Labels: process: review needed, tag: enhancement

#1839 feat(controls): Search form, replacing knobs with controls - front-1863
  src/implementations/twig/components/search-form/search-form.story.js
Labels: tag: enhancement

#1843 docs(date-block): update doc - FRONT-1910
  docs/Migrating-v3.md
  src/website/src/pages/ec/components/date-block/demo/index.js
Labels: process: review needed, tag: documentation

#1840 feat(file-upload): Add controls - FRONT-1861
  src/implementations/twig/components/file-upload/file-upload.story.js
Labels: process: under review, tag: enhancement

#1847 feat(ordered-list): Remove knobs - FRONT-1869
  src/implementations/twig/components/ordered-list/ordered-list.story.js
Labels: process: under review, tag: enhancement

#1848 feat(unordered-list): Remove knobs - FRONT-1870
  src/implementations/twig/components/unordered-list/unordered-list.story.js
Labels: process: under review, tag: enhancement

#1850 fix(file): Correct typo in image knobs option - FRONT-1926
  src/systems/ec/implementations/react/components/file/stories/Index.jsx
  src/systems/eu/implementations/react/components/file/stories/Index.jsx
Labels: process: under review, tag: bug fix

#1846 feat(description-list): Add controls - FRONT-1868
  src/implementations/twig/components/description-list/description-list.story.js
Labels: tag: enhancement

#1852 feat(gallery): update controls - FRONT-1877
  src/implementations/twig/components/gallery/gallery.story.js
Labels: tag: enhancement

#1842 feat(select): Add controls - FRONT-1864
  src/implementations/twig/components/select/select.story.js
  src/playground/addons/story-utils/index.js
  src/specs/components/select/demo/data--multiple.js
  src/specs/components/select/demo/data--single.js
Labels: tag: enhancement

#1851 feat(file): Add controls - FRONT-1873
  src/implementations/twig/components/file/file.story.js
  src/implementations/vanilla/components/file/file.scss
Labels: process: under review, tag: enhancement

#1845 feat(controls): Textarea, replacing knobs with controls - FRONT-1865
  src/implementations/twig/components/text-area/README.md
  src/implementations/twig/components/text-area/text-area.html.twig
  src/implementations/twig/components/text-area/text-area.story.js
Labels: process: under review, tag: enhancement

#1856 feat(label): add controls - FRONT-1881
  src/implementations/twig/components/label/label.story.js
  src/website/src/pages/ec/components/label/demo/index.js
  src/website/src/pages/ec/components/label/docs/code.mdx
Labels: tag: enhancement

#1849 fix(forms): update deprecated css - FRONT-1899
  docs/Migrating-v3.md
  src/implementations/vanilla/components/form/form.scss
Labels: process: review needed, tag: enhancement

#1857 feat(message): Add controls - FRONT-1884
  src/implementations/twig/components/message/message.story.js
Labels: process: under review, tag: enhancement
