Repository ec-europa/europa-component-library, pull requests merged in 2020-09, with the labels that each got.

#1658 fix(site-headers): aria-label typo - FRONT-1571
  src/systems/ec/implementations/react/components/site-header-core/src/SiteHeaderCore.jsx
  src/systems/ec/implementations/react/components/site-header-harmonised/src/SiteHeaderHarmonised.jsx
  src/systems/ec/implementations/react/components/site-header-standardised/src/SiteHeaderStandardised.jsx
Labels: process: review needed, tag: bug fix

#1659 fix(file): add aria-label - FRONT-1573
  src/systems/ec/implementations/react/components/file/src/FileDownload.jsx
  src/systems/ec/specs/components/file/demo/data--thumbnail.js
  src/systems/ec/specs/components/file/demo/data--with-translation.js
Labels: tag: bug fix

#1660 fix(page-headers): adding missing aria-label - FRONT-1575
  src/systems/ec/implementations/react/components/page-header-core/stories/Index.jsx
  src/systems/ec/implementations/react/components/page-header-harmonised/stories/Index.jsx
  src/systems/ec/implementations/react/components/page-header-standardised/stories/Index.jsx
  src/systems/eu/implementations/react/components/page-header-core/stories/Index.jsx
  src/systems/eu/implementations/react/components/page-header-harmonised/stories/Index.jsx
  src/systems/eu/implementations/react/components/page-header-standardised/stories/Index.jsx
  src/systems/eu/implementations/react/components/site-header-core/src/SiteHeaderCore.jsx
  src/systems/eu/implementations/react/components/site-header-harmonised/src/SiteHeaderHarmonised.jsx
  src/systems/eu/implementations/react/components/site-header-standardised/src/SiteHeaderStandardised.jsx
  src/website/src/pages/ec/core-template/page-header/docs/ShowcaseBreadcrumb.jsx
  src/website/src/pages/ec/standardised-template/page-header/docs/ShowcaseBreadcrumb.jsx
Labels: tag: bug fix

#1663 fix(select): options click handler - FRONT-1584
  src/systems/ec/implementations/vanilla/packages/ec-component-form-select/ec-component-form-select.js
  src/systems/eu/implementations/vanilla/packages/eu-component-form-select/eu-component-form-select.js
Labels: tag: bug fix

#1668 fix(menu): fix item display when switching from mobile to desktop - FRONT-1580
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/ec-component-menu.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-menu/eu-component-menu.scss
Labels: tag: bug fix

#1664 fix(footers): fix columns gap - FRONT-1477
  src/systems/ec/implementations/vanilla/packages/ec-component-footer-core/ec-component-footer-core.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-footer-harmonised/ec-component-footer-harmonised.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-footer-standardised/ec-component-footer-standardised.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-footer-core/eu-component-footer-core.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-footer-harmonised/eu-component-footer-harmonised.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-footer-standardised/eu-component-footer-standardised.scss
Labels: tag: enhancement

#1669 feat(icon): add tag icon - FRONT-1549
  src/systems/ec/resources/icons/src/general/tag.svg
  src/systems/eu/resources/icons/src/general/tag.svg
Labels: tag: new feature

#1666 fix(select): add disabled and selected parameters for options
  src/systems/ec/implementations/react/components/select/src/Select.jsx
  src/systems/ec/specs/components/select/demo/data--multiple.js
  src/systems/ec/specs/components/select/demo/data--single.js
  src/systems/eu/implementations/react/components/select/src/Select.jsx
  src/systems/eu/specs/components/select/demo/data--multiple.js
  src/systems/eu/specs/components/select/demo/data--single.js
Labels: tag: bug fix

#1670 refactor(logo): update fr logo - FRONT-1596
  src/systems/ec/resources/logo/logo--fr.svg
Labels: process: under review, tag: enhancement

#1667 fix(menu): use css class instead of data-attribute - FRONT-1563
  src/systems/ec/implementations/react/components/menu/src/MenuItem.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/ec-component-menu.scss
  src/systems/eu/implementations/react/components/menu/src/MenuItem.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-menu/eu-component-menu.scss
Labels: tag: enhancement

#1665 fix(forms-select--multiple): fix footer overlapping issue - FRONT-1578
  src/systems/ec/implementations/react/templates/pages/search/src/SearchPage.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-form-select/ec-component-form-select.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-form-select/eu-component-form-select.scss
Labels: tag: bug fix

#1672 fix(select-multiple): adding position relative to component container - FRONT-1601
  src/systems/ec/implementations/vanilla/packages/ec-component-form-select/ec-component-form-select.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-form-select/eu-component-form-select.scss
Labels: process: under review, tag: bug fix

#1671 fix(banners): update links in usage page - FRONT-1600
  src/website/src/pages/ec/components/banners/hero-banner/docs/usage.mdx
  src/website/src/pages/ec/components/banners/page-banner/docs/usage.mdx
  src/website/src/website-components/Anatomy/Anatomy.jsx
Labels: tag: documentation

#1674 chore(deps): treat security reports - FRONT-324
  package.json
  yarn.lock
Labels: process: under review, tag: internal

#1673 feat(select-multiple): support additional attributes - FRONT-1589
  src/systems/ec/implementations/vanilla/packages/ec-component-form-select/ec-component-form-select.js
  src/systems/eu/implementations/vanilla/packages/eu-component-form-select/eu-component-form-select.js
Labels: process: under review, tag: new feature

#1678 fix(select): allows several multiple select lists - FRONT-1579
  src/systems/ec/implementations/react/components/select/stories/Index.jsx
  src/systems/ec/implementations/react/templates/pages/search/src/SearchPage.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-form-select/ec-component-form-select.js
  src/systems/eu/implementations/react/components/select/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-form-select/eu-component-form-select.js
Labels: Approved, tag: bug fix

#1677 feat(page-header): add background image variant - FRONT-1333
  src/systems/ec/implementations/react/components/page-header-core/src/PageHeaderCore.jsx
  src/systems/ec/implementations/react/components/page-header-core/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-page-header-core/ec-component-page-header-core-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-page-header-core/ec-component-page-header-core.scss
  src/systems/ec/specs/components/page-header-core/demo/data--background-image.js
  src/systems/eu/implementations/react/components/page-header-core/src/PageHeaderCore.jsx
  src/systems/eu/implementations/react/components/page-header-core/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-page-header-core/eu-component-page-header-core-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-page-header-core/eu-component-page-header-core.scss
  src/systems/eu/specs/components/page-header-core/demo/data--background-image.js
  src/website/src/pages/ec/core-template/page-header/docs/code.mdx
Labels: tag: new feature

#1680 feat(tags): updat usage page and tag variants - FRONT-1334
  src/systems/ec/implementations/react/components/tag/src/Tag.jsx
  src/systems/ec/implementations/react/components/tag/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-tag/ec-component-tag.scss
  src/systems/ec/specs/components/tag/demo/data--display.js
  src/systems/eu/implementations/react/components/tag/src/Tag.jsx
  src/systems/eu/implementations/react/components/tag/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-tag/eu-component-tag.scss
  src/systems/eu/specs/components/tag/demo/data--display.js
  src/website/src/pages/ec/components/tag/docs/code.mdx
  src/website/src/pages/ec/components/tag/docs/usage.mdx
Labels: process: review needed, process: under review, tag: new feature

#1681 fix(inPageNavigation): menu overlaping headers - FRONT-1248
  src/systems/ec/implementations/vanilla/packages/ec-component-inpage-navigation/ec-component-inpage-navigation.js
  src/systems/ec/implementations/vanilla/packages/ec-component-inpage-navigation/ec-component-inpage-navigation.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-inpage-navigation/eu-component-inpage-navigation.js
  src/systems/eu/implementations/vanilla/packages/eu-component-inpage-navigation/eu-component-inpage-navigation.scss
Labels: tag: bug fix

#1684 fix(inpage-nav): remove unnecessary hidden attribute - FRONT-1690
  src/systems/ec/implementations/vanilla/packages/ec-component-inpage-navigation/ec-component-inpage-navigation.js
  src/systems/eu/implementations/vanilla/packages/eu-component-inpage-navigation/eu-component-inpage-navigation.js
Labels: process: review needed, tag: bug fix

#1686 feat(menu): add option to manually close the menu - FRONT-1581
  src/systems/ec/implementations/react/components/menu/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/ec-component-menu.scss
  src/systems/eu/implementations/react/components/menu/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-menu/eu-component-menu.scss
  src/website/src/pages/ec/components/navigation/menu/docs/api.mdx
Labels: process: under review, tag: new feature

#1688 Remove design tokens
  .gitignore
  .prettierignore
  .stylelintignore
  package.json
  src/design-tokens/README.md
  src/design-tokens/index.yml
  src/design-tokens/package.json
  src/design-tokens/props.yml
  src/design-tokens/props/breakpoints.yml
  src/design-tokens/props/grid.yml
  src/design-tokens/tokens/breakpoints.yml
  src/design-tokens/tokens/colors.yml
  src/design-tokens/tokens/grid.yml
  src/design-tokens/tokens/icons.yml
  src/design-tokens/tokens/media.yml
  src/design-tokens/tokens/spacing.yml
  src/design-tokens/tokens/typography.yml
  src/design-tokens/tokens/widths.yml
  src/design-tokens/tokens/z-index.yml
  src/implementations/react/storybook/package.json
  src/implementations/vanilla/packages/ec-preset-website/package.json
  src/specs/components/button/tokens.yml
  src/themes/default/README.md
  src/themes/default/aliases/colors-bg.yml
  src/themes/default/aliases/colors.yml
  src/themes/default/aliases/icons.yml
  src/themes/default/aliases/media.yml
  src/themes/default/aliases/spacing.yml
  src/themes/default/aliases/typography.yml
  src/themes/default/aliases/widths.yml
  src/themes/default/aliases/z-index.yml
  src/themes/default/components/button.yml
  src/themes/default/index.scss
  src/themes/default/index.yml
  src/themes/default/maps/colors-bg.scss
  src/themes/default/maps/colors.scss
  src/themes/default/maps/font-size-print.scss
  src/themes/default/maps/font-size.scss
  src/themes/default/maps/media.scss
  src/themes/default/maps/spacing-print.scss
  src/themes/default/maps/spacing.scss
  src/themes/default/maps/widths.scss
  src/themes/default/maps/z-index.scss
  src/themes/default/package.json
  src/themes/default/scripts/build-tokens.js
  src/themes/default/scripts/formats/scss-map.js
  src/themes/default/scripts/formats/scss.js
  src/themes/default/scripts/util.js
  src/themes/default/tokens.json
  src/themes/default/variables/index.scss
  src/website/src/pages/ec/guidelines/colours/index.md
  yarn.lock
Labels: tag: internal

#1691 feat(icon): remove deprecated icons - FRONT-1682
  src/resources/icons/src/general/_brochure.svg
  src/resources/icons/src/general/_budget.svg
  src/resources/icons/src/general/_data.svg
  src/resources/icons/src/general/_energy.svg
  src/resources/icons/src/general/_euro.svg
  src/resources/icons/src/general/_package.svg
  src/resources/icons/src/general/_presentation.svg
Labels: process: review needed, tag: internal
