Repository ec-europa/europa-component-library, pull requests merged in 2020-04, with the labels that each got.

#1564 feat(storybook): add knobs for optional elements - FRONT-983
  src/systems/ec/implementations/react/components/site-header-core/stories/Index.jsx
  src/systems/ec/implementations/react/components/site-header-harmonised/src/SiteHeaderHarmonised.jsx
  src/systems/ec/implementations/react/components/site-header-harmonised/stories/Index.jsx
  src/systems/ec/implementations/react/components/site-header-standardised/stories/Index.jsx
Labels: tag: enhancement

#1567 docs(page banner): update doc - FRONT-998
  src/website/src/pages/ec/components/banners/page-banner/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1569 chore(deps): upgrades - FRONT-1012
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: process: under review, tag: internal

#1566 fix(examples): update babel configuration in webpack - FRONT-974
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
Labels: process: under review, tag: bug fix

#1565 fix(inpage navigation): fix long label and design update - FRONT-899
  src/systems/ec/implementations/react/components/inpage-navigation/examples/Default.jsx
  src/systems/ec/implementations/react/components/inpage-navigation/package.json
  src/systems/ec/implementations/react/components/inpage-navigation/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-inpage-navigation/ec-component-inpage-navigation.scss
  src/systems/ec/specs/components/inpage-navigation/demo/data.js
  src/website/webpack.config.dev.js
  src/website/webpack.config.prod.js
Labels: process: changes requested, tag: bug fix

#1568 docs(images): add notes regarding SVGs
  src/website/src/pages/ec/getting-started/index.mdx
  src/website/src/pages/ec/guidelines/images/index.md
Labels: process: under review, tag: documentation

#1580 feat(label): add component - FRONT-1006
  src/systems/ec/implementations/react/components/label/index.js
  src/systems/ec/implementations/react/components/label/package.json
  src/systems/ec/implementations/react/components/label/src/Label.jsx
  src/systems/ec/implementations/react/components/label/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-label/README.md
  src/systems/ec/implementations/vanilla/packages/ec-component-label/ec-component-label-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-label/ec-component-label.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-label/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.scss
  src/systems/ec/specs/components/label/demo/data.js
  src/systems/ec/specs/components/label/package.json
  src/website/src/pages/ec/components/label/docs/code.mdx
  src/website/src/pages/ec/components/label/docs/usage.mdx
  src/website/src/pages/ec/components/label/index.md
  src/website/src/styles/markdown.scss
  yarn.lock
Labels: tag: new feature

#1582 fix(site-header-core): add tests for language switcher
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-core/ec-component-site-header-core.js
Labels: tag: bug fix

#1584 feat(legacy-page-header): add background image - FRONT-1130
  src/systems/ec/implementations/react/deprecated/page-header/src/PageHeader.jsx
  src/systems/ec/implementations/react/deprecated/page-header/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-page-header/ec-component-page-header.scss
  src/systems/ec/specs/components/page-header/demo/data--background-image.js
Labels: process: under review, tag: new feature

#1579 feat(print): update print css
  src/systems/ec/design-tokens/tokens/typography.yml
  src/systems/ec/implementations/react/templates/compositions/content-item/examples/Custom.jsx
  src/systems/ec/implementations/react/templates/compositions/content-item/src/ContentItem.jsx
  src/systems/ec/implementations/react/templates/compositions/navigation-lists/examples/Default.jsx
  src/systems/ec/implementations/react/utilities/print/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-accordion2/ec-component-accordion2-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-blockquote/ec-component-blockquote-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-button/ec-component-button-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-card/ec-component-card-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-date-block/ec-component-date-block-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-description-list/ec-component-description-list-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-expandable/ec-component-expandable-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-fact-figures/ec-component-fact-figures-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-file/ec-component-file-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-checkbox/ec-component-form-checkbox-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-datepicker/ec-component-form-datepicker-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-feedback-message/ec-component-form-feedback-message-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-file-upload/ec-component-form-file-upload-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-form-group/ec-component-form-form-group-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-help-block/ec-component-form-help-block-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-label/ec-component-form-label-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-radio/ec-component-form-radio-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-select/ec-component-form-select-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-text-area/ec-component-form-text-area-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-text-input/ec-component-form-text-input-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-hero-banner/ec-component-hero-banner-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-icon/ec-component-icon-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-label/ec-component-label-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-link/ec-component-link-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/ec-component-menu-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-message/ec-component-message-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-ordered-list/ec-component-ordered-list-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-page-banner/ec-component-page-banner-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-page-header-core/ec-component-page-header-core-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-page-header-harmonised/ec-component-page-header-harmonised-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-page-header-standardised/ec-component-page-header-standardised-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-core/ec-component-site-header-core-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-harmonised/ec-component-site-header-harmonised-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header-standardised/ec-component-site-header-standardised-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-social-media-follow/ec-component-social-media-follow-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-table/ec-component-table-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-tag/ec-component-tag-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-timeline2/ec-component-timeline2-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-unordered-list/ec-component-unordered-list-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-dev/src/ec-preset-dev.scss
  src/systems/ec/implementations/vanilla/packages/ec-utility-print/README.md
  src/systems/ec/implementations/vanilla/packages/ec-utility-print/ec-utility-print-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-utility-print/ec-utility-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-utility-print/package.json
  src/systems/ec/implementations/vanilla/packages/ec-utility-typography/ec-utility-typography-print.scss
  src/systems/ec/themes/default/aliases/typography.yml
  src/website/src/pages/ec/utilities/print/docs/code.mdx
  src/website/src/pages/ec/utilities/print/docs/usage.mdx
  src/website/src/pages/ec/utilities/print/index.md
Labels: tag: enhancement

#1585 fix(gallery): update z-index for overlay - FRONT-996
  src/systems/ec/design-tokens/tokens/z-index.yml
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/ec-component-gallery.scss
Labels: process: review needed, tag: bug fix
