Repository ec-europa/europa-component-library, pull requests merged in 2020-03, with the labels that each got.

#1550 feat(media-container): allows embedded videos - FRONT-836
  src/systems/ec/implementations/react/components/media-container/src/MediaContainer.jsx
  src/systems/ec/implementations/react/components/media-container/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-media-container/ec-component-media-container.scss
  src/systems/ec/specs/components/gallery/demo/data.js
  src/systems/ec/specs/components/media-container/demo/data--video.js
  src/website/src/pages/ec/components/media/media-container/docs/code.mdx
Labels: process: review needed, tag: new feature

#1553 fix(pages): Add correct harmonised G2 footer template for all pages - FRONT-889
  src/systems/ec/implementations/react/templates/pages/call-proposals/examples/CallProposalsHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/call-proposals/examples/CallProposalsHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/call-tenders/examples/CallTendersHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/call-tenders/examples/CallTendersHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/commemorative-coin/examples/CommemorativeCoinHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/commemorative-coin/examples/CommemorativeCoinHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/department/examples/DepartmentHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/department/examples/DepartmentHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/event-agenda/examples/EventAgendaHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/event-agenda/examples/EventAgendaHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/event-detail/examples/EventDetailHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/event-detail/examples/EventDetailHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/event-speaker/examples/EventSpeakerHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/event-speaker/examples/EventSpeakerHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/funding-programme/examples/FundingProgrammeHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/funding-programme/examples/FundingProgrammeHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-biography/examples/PersonHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-biography/examples/PersonHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-list/examples/PersonListHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-list/examples/PersonListHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-awareness/examples/MainPolicyAwarenessHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-awareness/examples/MainPolicyAwarenessHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-background/examples/MainPolicyBackgroundHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-background/examples/MainPolicyBackgroundHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-evaluation/examples/MainPolicyEvaluationHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-evaluation/examples/MainPolicyEvaluationHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-hub/examples/MainPolicyHubHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-hub/examples/MainPolicyHubHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-legislation/examples/MainPolicyLegislationHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-legislation/examples/MainPolicyLegislationHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-resources/examples/MainPolicyResourcesHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-resources/examples/MainPolicyResourcesHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-hub/examples/ResearchAreaHubHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-hub/examples/ResearchAreaHubHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-spoke/examples/ResearchAreaSpokeHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-spoke/examples/ResearchAreaSpokeHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/search/examples/SearchHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/search/examples/SearchHarmonisedG2.jsx
  yarn.lock
Labels: process: under review, tag: bug fix

#1554 fix(pages): Add pageHeader top padding if breadcrumb is not displayed - FRONT-890
  src/systems/ec/implementations/react/templates/pages/call-proposals/examples/CallProposalsHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/call-proposals/examples/CallProposalsHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/call-proposals/examples/CallProposalsStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/call-tenders/examples/CallTendersHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/call-tenders/examples/CallTendersHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/call-tenders/examples/CallTendersStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/commemorative-coin/examples/CommemorativeCoinHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/commemorative-coin/examples/CommemorativeCoinHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/commemorative-coin/examples/CommemorativeCoinStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/department/examples/DepartmentHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/department/examples/DepartmentHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/department/examples/DepartmentStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/event-agenda/examples/EventAgendaHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/event-agenda/examples/EventAgendaHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/event-agenda/examples/EventAgendaStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/event-detail/examples/EventDetailHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/event-detail/examples/EventDetailHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/event-detail/examples/EventDetailStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/event-speaker/examples/EventSpeakerHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/event-speaker/examples/EventSpeakerHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/event-speaker/examples/EventSpeakerStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/funding-programme/examples/FundingProgrammeHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/funding-programme/examples/FundingProgrammeHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/funding-programme/examples/FundingProgrammeStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-biography/examples/PersonHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-biography/examples/PersonHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-biography/examples/PersonStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-list/examples/PersonListHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-list/examples/PersonListHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-list/examples/PersonListStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-awareness/examples/MainPolicyAwarenessHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-awareness/examples/MainPolicyAwarenessHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-awareness/examples/MainPolicyAwarenessStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-background/examples/MainPolicyBackgroundHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-background/examples/MainPolicyBackgroundHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-background/examples/MainPolicyBackgroundStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-evaluation/examples/MainPolicyEvaluationHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-evaluation/examples/MainPolicyEvaluationHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-evaluation/examples/MainPolicyEvaluationStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-hub/examples/MainPolicyHubHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-hub/examples/MainPolicyHubHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-hub/examples/MainPolicyHubStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-legislation/examples/MainPolicyLegislationHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-legislation/examples/MainPolicyLegislationHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-legislation/examples/MainPolicyLegislationStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-resources/examples/MainPolicyResourcesHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-resources/examples/MainPolicyResourcesHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-resources/examples/MainPolicyResourcesStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-hub/examples/ResearchAreaHubHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-hub/examples/ResearchAreaHubHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-hub/examples/ResearchAreaHubStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-spoke/examples/ResearchAreaSpokeHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-spoke/examples/ResearchAreaSpokeHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-spoke/examples/ResearchAreaSpokeStandardised.jsx
  src/systems/ec/implementations/react/templates/pages/search/examples/SearchHarmonisedG1.jsx
  src/systems/ec/implementations/react/templates/pages/search/examples/SearchHarmonisedG2.jsx
  src/systems/ec/implementations/react/templates/pages/search/examples/SearchStandardised.jsx
Labels: process: under review, tag: bug fix

#1556 feat(content-media): add media container composition - FRONT-895
  .prettierignore
  src/systems/ec/implementations/react/templates/compositions/content-media/examples/Left.jsx
  src/systems/ec/implementations/react/templates/compositions/content-media/examples/LeftCta.jsx
  src/systems/ec/implementations/react/templates/compositions/content-media/examples/Right.jsx
  src/systems/ec/implementations/react/templates/compositions/content-media/examples/RightCta.jsx
  src/systems/ec/implementations/react/templates/compositions/content-media/index.js
  src/systems/ec/implementations/react/templates/compositions/content-media/package.json
  src/systems/ec/implementations/react/templates/compositions/content-media/src/ContentMedia.jsx
  src/systems/ec/implementations/react/templates/compositions/content-media/stories/Index.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-spoke/examples/ResearchAreaSpokeStandardised.jsx
  src/systems/ec/specs/templates/content-media/demo/data--left-cta.js
  src/systems/ec/specs/templates/content-media/demo/data--left.js
  src/systems/ec/specs/templates/content-media/demo/data--right-cta.js
  src/systems/ec/specs/templates/content-media/demo/data--right.js
  src/systems/ec/specs/templates/content-media/package.json
  src/tools/storybook-addon-code/utils/codepen.js
  src/website/src/pages/ec/compositions/content-media/docs/code.mdx
  src/website/src/pages/ec/compositions/content-media/docs/usage.mdx
  src/website/src/pages/ec/compositions/content-media/index.md
  yarn.lock
Labels: tag: new feature

#1557 feat(ecl): provide watch mode including website presets - FRONT-934
  docs/01-overview.md
  docs/README.md
  docs/atomic-design-patterns.md
  docs/conventions/README.md
  docs/create-new-component.md
  docs/developers-start-here.md
  docs/javascript.md
  docs/presets.md
  docs/update-documentation.md
  docs/working-with-systems.md
  package.json
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/eu/implementations/react/storybook/package.json
Labels: tag: internal

#1559 docs(release): improve release documentation - FRONT-940
  .github/CONTRIBUTING.md
Labels: process: review needed, tag: internal

#1551 feat(menu): implement menu v2 - FRONT-811
  .size-limit.json
  package.json
  src/systems/ec/implementations/react/components/button/src/Button.jsx
  src/systems/ec/implementations/react/components/menu/package.json
  src/systems/ec/implementations/react/components/menu/src/Menu.jsx
  src/systems/ec/implementations/react/components/menu/src/MenuItem.jsx
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/ec-component-menu-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/ec-component-menu.js
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/ec-component-menu.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/package.json
  src/systems/ec/specs/components/menu/demo/data--en.js
  src/systems/ec/specs/components/menu/demo/data--fr.js
  src/systems/ec/specs/components/menu/demo/data--group1.js
  src/systems/ec/specs/components/menu/demo/data--group2.js
  src/systems/eu/implementations/react/storybook/package.json
  yarn.lock
Labels: process: under review, tag: new feature

#1563 refactor(forms): cleanup forms markup - FRONT-933
  src/systems/ec/implementations/react/components/checkbox/src/Checkbox.jsx
  src/systems/ec/implementations/react/components/checkbox/src/CheckboxGroup.jsx
  src/systems/ec/implementations/react/components/datepicker/src/Datepicker.jsx
  src/systems/ec/implementations/react/components/file-upload/src/FileUpload.jsx
  src/systems/ec/implementations/react/components/radio/src/RadioButton.jsx
  src/systems/ec/implementations/react/components/radio/src/RadioGroup.jsx
  src/systems/ec/implementations/react/components/select/src/Select.jsx
  src/systems/ec/implementations/react/components/text-area/src/TextArea.jsx
  src/systems/ec/implementations/react/components/text-input/src/TextInput.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-form-checkbox/ec-component-form-checkbox.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-form-group/ec-component-form-form-group.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-form-radio/ec-component-form-radio.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-search-form/ec-component-search-form.scss
  yarn.lock
Labels: tag: enhancement
