Repository ec-europa/europa-component-library, pull requests merged in 2020-02, with the labels that each got.

#1525 fix(ec-editor): fix list and paragraph - INNO-2104
  src/systems/ec/implementations/vanilla/packages/ec-editor/_ec-editor--list.scss
Labels: process: review needed, tag: enhancement

#1506 fix(storybook): unset sidebar customization - INNO-2006
  src/systems/ec/implementations/react/storybook/.storybook/manager-head.html
  src/systems/eu/implementations/react/storybook/.storybook/manager-head.html
Labels: process: under review, tag: enhancement

#1519 docs(file-upload): update images - INNO-2090
  src/website/src/pages/ec/components/file/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1534 fix(ec-editor): update paragraph color - INNO-2104
  src/systems/ec/implementations/vanilla/packages/ec-editor/_ec-editor--typography.scss
Labels: process: review needed, tag: bug fix

#1537 fix(stroybook): fix storybook error - FRONT-464
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/specs/templates/call-proposals-page/package.json
  src/systems/ec/specs/templates/call-tenders-page/package.json
  src/systems/ec/specs/templates/commemorative-coin-page/package.json
  src/systems/ec/specs/templates/department-page/package.json
  src/systems/ec/specs/templates/event-agenda-page/package.json
  src/systems/ec/specs/templates/event-detail-page/package.json
  src/systems/ec/specs/templates/event-speaker-page/package.json
  src/systems/ec/specs/templates/funding-programme-page/package.json
  src/systems/ec/specs/templates/main-policy-awareness-page/package.json
  src/systems/ec/specs/templates/main-policy-background-page/package.json
  src/systems/ec/specs/templates/main-policy-evaluation-page/package.json
  src/systems/ec/specs/templates/main-policy-hub-page/package.json
  src/systems/ec/specs/templates/main-policy-legislation-page/package.json
  src/systems/ec/specs/templates/main-policy-resources-page/package.json
  src/systems/ec/specs/templates/person-list-page/package.json
  src/systems/ec/specs/templates/person-page/package.json
  src/systems/ec/specs/templates/research-area-hub-page/package.json
  src/systems/ec/specs/templates/research-area-spoke-page/package.json
  src/systems/ec/specs/templates/search-page/package.json
  yarn.lock
Labels: process: review needed, tag: internal

#1531 fix(site-header): check language switcher - FRONT-447
  src/systems/ec/implementations/vanilla/packages/ec-component-site-header/ec-component-site-header.js
Labels: process: under review, tag: bug fix

#1538 docs(gp2): add intro - FRONT-451
  src/website/src/pages/ec/harmonised-templates/footer/docs/group2.mdx
Labels: process: review needed, tag: documentation

#1540 fix(list): add max-width - FRONT-471
  src/systems/ec/implementations/vanilla/packages/ec-component-description-list/ec-component-description-list.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-ordered-list/ec-component-ordered-list.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-unordered-list/ec-component-unordered-list.scss
  src/systems/ec/implementations/vanilla/packages/ec-editor/_ec-editor--list.scss
Labels: process: under review, tag: enhancement

#1541 chore(deps): upgrade storybook to latest fixing knobs
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/eu/implementations/react/storybook/package.json
  src/tools/storybook-addon-code/package.json
  yarn.lock
Labels: process: under review, tag: internal

#1539 fix(content-types): update paragraph color - FONT-470
  src/systems/ec/implementations/react/templates/pages/call-proposals/src/CallProposalsPage.jsx
  src/systems/ec/implementations/react/templates/pages/call-tenders/src/CallTendersPage.jsx
  src/systems/ec/implementations/react/templates/pages/department/src/DepartmentPage.jsx
  src/systems/ec/implementations/react/templates/pages/event-detail/src/EventDetailPage.jsx
  src/systems/ec/implementations/react/templates/pages/funding-programme/src/FundingProgrammePage.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-biography/src/PersonPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-awareness/src/MainPolicyAwarenessPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-background/src/MainPolicyBackgroundPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-evaluation/src/MainPolicyEvaluationPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-hub/src/MainPolicyHubPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-legislation/src/MainPolicyLegislationPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-resources/src/MainPolicyResourcesPage.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-hub/src/ResearchAreaHubPage.jsx
  src/systems/ec/implementations/react/templates/pages/research-area-spoke/src/ResearchAreaSpokePage.jsx
Labels: tag: enhancement

#1532 feat(website): reintroduce status - FRONT-85
  src/website/src/components/Navigation/SingleLink.jsx
  src/website/src/pages/ec/getting-started/index.mdx
Labels: process: review needed, tag: internal

#1543 fix(footer): handle optional elements - FRONT-467
  src/systems/ec/implementations/react/components/footer-core/index.js
  src/systems/ec/implementations/react/components/footer-core/src/FooterCore.jsx
  src/systems/ec/implementations/react/components/footer-core/src/FooterCoreSection.jsx
  src/systems/ec/implementations/react/components/footer-core/stories/Index.jsx
  src/systems/ec/implementations/react/components/footer-harmonised/index.js
  src/systems/ec/implementations/react/components/footer-harmonised/src/FooterHarmonised.jsx
  src/systems/ec/implementations/react/components/footer-harmonised/src/FooterHarmonisedG1.jsx
  src/systems/ec/implementations/react/components/footer-harmonised/src/FooterHarmonisedG2.jsx
  src/systems/ec/implementations/react/components/footer-harmonised/src/FooterHarmonisedG3.jsx
  src/systems/ec/implementations/react/components/footer-harmonised/src/FooterHarmonisedSection.jsx
  src/systems/ec/implementations/react/components/footer-harmonised/stories/Index.jsx
  src/systems/ec/implementations/react/components/footer-standardised/index.js
  src/systems/ec/implementations/react/components/footer-standardised/src/FooterStandardised.jsx
  src/systems/ec/implementations/react/components/footer-standardised/src/FooterStandardisedSection.jsx
  src/systems/ec/implementations/react/components/footer-standardised/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-footer-harmonised/ec-component-footer-harmonised.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-footer-standardised/ec-component-footer-standardised.scss
  src/systems/ec/specs/components/footer-core/demo/data.js
  src/systems/ec/specs/components/footer-harmonised/demo/data--group1.js
  src/systems/ec/specs/components/footer-harmonised/demo/data--group2.js
  src/systems/ec/specs/components/footer-harmonised/demo/data--group3.js
  src/systems/ec/specs/components/footer-standardised/demo/data.js
Labels: process: WIP, tag: enhancement
