Repository ec-europa/europa-component-library, pull requests merged in 2020-11, with the labels that each got.

#1728 feat: migrate text field - FRONT-1742
  src/implementations/twig/components/text-input/.npmignore
  src/implementations/twig/components/text-input/README.md
  src/implementations/twig/components/text-input/__snapshots__/text-input.test.js.snap
  src/implementations/twig/components/text-input/package.json
  src/implementations/twig/components/text-input/text-input.html.twig
  src/implementations/twig/components/text-input/text-input.story.js
  src/implementations/twig/components/text-input/text-input.test.js
  src/implementations/vanilla/components/text-input/README.md
  src/implementations/vanilla/components/text-input/package.json
  src/implementations/vanilla/components/text-input/text-input-print.scss
  src/implementations/vanilla/components/text-input/text-input.scss
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/text-input/demo/data--default.js
  src/specs/components/text-input/demo/data--disabled.js
  src/specs/components/text-input/demo/data--with-error.js
  src/specs/components/text-input/package.json
  src/website/src/pages/ec/components/forms/text-field/demo/index.js
  src/website/src/pages/ec/components/forms/text-field/docs/code.mdx
  src/website/src/pages/ec/components/forms/text-field/docs/usage.mdx
  src/website/src/pages/ec/components/forms/text-field/ec_comp_text_field.svg
  src/website/src/pages/ec/components/forms/text-field/index.md
Labels: process: under review, tag: new feature

#1732 chore(storybook): ECL themes instead of cssresources
  src/implementations/twig/storybook/.storybook/main.js
  src/implementations/twig/storybook/.storybook/manager.js
  src/implementations/twig/storybook/.storybook/preview.js
Labels: process: review needed, tag: enhancement

#1730 feat(table): Migrate component - front-1741
  src/implementations/twig/components/table/.npmignore
  src/implementations/twig/components/table/README.md
  src/implementations/twig/components/table/__snapshots__/table.test.js.snap
  src/implementations/twig/components/table/package.json
  src/implementations/twig/components/table/table.html.twig
  src/implementations/twig/components/table/table.story.js
  src/implementations/twig/components/table/table.test.js
  src/implementations/twig/storybook/.storybook/preview-head.html
  src/implementations/vanilla/components/table/README.md
  src/implementations/vanilla/components/table/package.json
  src/implementations/vanilla/components/table/table-print.scss
  src/implementations/vanilla/components/table/table.js
  src/implementations/vanilla/components/table/table.scss
  src/implementations/vanilla/packages/auto-init/README.md
  src/implementations/vanilla/packages/auto-init/index.js
  src/implementations/vanilla/packages/auto-init/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/specs/components/table/demo/data--default.js
  src/specs/components/table/demo/data--multi.js
  src/specs/components/table/demo/data--sort-table.js
  src/specs/components/table/package.json
  src/tools/helpers/README.md
  src/tools/helpers/dom.js
  src/tools/helpers/package.json
  src/tools/helpers/utilities.js
  src/website/scripts/docs.js
  src/website/src/pages/ec/components/table/demo/index.js
  src/website/src/pages/ec/components/table/docs/api.mdx
  src/website/src/pages/ec/components/table/docs/code.mdx
  src/website/src/pages/ec/components/table/docs/usage.mdx
  src/website/src/pages/ec/components/table/ec_comp_table.svg
  src/website/src/pages/ec/components/table/index.md
Labels: process: WIP, tag: new feature

#1736 docs(colours): update text colour - FRONT-1764
  src/systems/ec/themes/default/aliases/colors.yml
Labels: tag: documentation

#1735 feat(fact-figures): Adding component - front-1760
  src/implementations/twig/components/fact-figures/.npmignore
  src/implementations/twig/components/fact-figures/README.md
  src/implementations/twig/components/fact-figures/__snapshots__/fact-figures.test.js.snap
  src/implementations/twig/components/fact-figures/fact-figures.html.twig
  src/implementations/twig/components/fact-figures/fact-figures.story.js
  src/implementations/twig/components/fact-figures/fact-figures.test.js
  src/implementations/twig/components/fact-figures/package.json
  src/implementations/vanilla/components/fact-figures/README.md
  src/implementations/vanilla/components/fact-figures/fact-figures-print.scss
  src/implementations/vanilla/components/fact-figures/fact-figures.scss
  src/implementations/vanilla/components/fact-figures/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/fact-figures/demo/data--3-col.js
  src/specs/components/fact-figures/demo/data--4-col.js
  src/specs/components/fact-figures/package.json
  src/website/src/pages/ec/components/fact-figures/demo/index.js
  src/website/src/pages/ec/components/fact-figures/docs/code.mdx
  src/website/src/pages/ec/components/fact-figures/docs/usage.mdx
  src/website/src/pages/ec/components/fact-figures/ec_comp_facts_and_figures.svg
  src/website/src/pages/ec/components/fact-figures/index.md
Labels: process: under review, tag: new feature

#1733 feat(date-block): Migrating component - front-1757
  src/implementations/twig/components/date-block/.npmignore
  src/implementations/twig/components/date-block/README.md
  src/implementations/twig/components/date-block/__snapshots__/date-block.test.js.snap
  src/implementations/twig/components/date-block/date-block.html.twig
  src/implementations/twig/components/date-block/date-block.story.js
  src/implementations/twig/components/date-block/date-block.test.js
  src/implementations/twig/components/date-block/package.json
  src/implementations/vanilla/components/date-block/README.md
  src/implementations/vanilla/components/date-block/date-block-print.scss
  src/implementations/vanilla/components/date-block/date-block.scss
  src/implementations/vanilla/components/date-block/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/date-block/demo/data.js
  src/specs/components/date-block/package.json
  src/website/src/pages/ec/components/date-block/demo/index.js
  src/website/src/pages/ec/components/date-block/docs/code.mdx
  src/website/src/pages/ec/components/date-block/docs/usage.mdx
  src/website/src/pages/ec/components/date-block/ec_comp_date_blocks.svg
  src/website/src/pages/ec/components/date-block/index.md
Labels: process: review needed, tag: new feature

#1739 feat(accordion): Adding component - front-1755
  src/implementations/twig/components/accordion/README.md
  src/implementations/twig/components/accordion/__snapshots__/accordion.test.js.snap
  src/implementations/twig/components/accordion/accordion.html.twig
  src/implementations/twig/components/accordion/accordion.story.js
  src/implementations/twig/components/accordion/accordion.test.js
  src/implementations/twig/components/accordion/package.json
  src/implementations/vanilla/components/accordion/README.md
  src/implementations/vanilla/components/accordion/accordion-print.scss
  src/implementations/vanilla/components/accordion/accordion.js
  src/implementations/vanilla/components/accordion/accordion.scss
  src/implementations/vanilla/components/accordion/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/specs/components/accordion/demo/data.js
  src/specs/components/accordion/package.json
  src/website/src/pages/ec/components/accordion/demo/index.js
  src/website/src/pages/ec/components/accordion/docs/api.mdx
  src/website/src/pages/ec/components/accordion/docs/code.mdx
  src/website/src/pages/ec/components/accordion/docs/usage.mdx
  src/website/src/pages/ec/components/accordion/ec_comp_accordion.svg
  src/website/src/pages/ec/components/accordion/index.md
Labels: process: under review, tag: new feature

#1741 chore: remove wrong comments
  src/implementations/vanilla/components/accordion/accordion-print.scss
  src/implementations/vanilla/components/accordion/accordion.scss
  src/implementations/vanilla/components/checkbox/checkbox.scss
  src/implementations/vanilla/components/date-block/date-block-print.scss
  src/implementations/vanilla/components/date-block/date-block.scss
  src/implementations/vanilla/components/description-list/description-list-print.scss
  src/implementations/vanilla/components/description-list/description-list.scss
  src/implementations/vanilla/components/fact-figures/fact-figures-print.scss
  src/implementations/vanilla/components/fact-figures/fact-figures.scss
  src/implementations/vanilla/components/ordered-list/ordered-list-print.scss
  src/implementations/vanilla/components/ordered-list/ordered-list.scss
  src/implementations/vanilla/components/table/table-print.scss
  src/implementations/vanilla/components/table/table.scss
  src/implementations/vanilla/components/unordered-list/unordered-list-print.scss
  src/implementations/vanilla/components/unordered-list/unordered-list.scss
Labels: tag: internal

#1738 chore: consolidate js utilities
  package.json
  src/implementations/vanilla/components/accordion/accordion.js
  src/implementations/vanilla/components/accordion/package.json
  src/implementations/vanilla/components/table/package.json
  src/implementations/vanilla/components/table/table.js
  src/polyfills/index.js
  src/polyfills/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev.js
  src/tools/dom-utils/.eslintrc.js
  src/tools/dom-utils/README.md
  src/tools/dom-utils/autoinit/README.md
  src/tools/dom-utils/autoinit/index.js
  src/tools/dom-utils/index.js
  src/tools/dom-utils/package.json
  src/tools/dom-utils/polyfills/closest.js
  src/tools/dom-utils/polyfills/index.js
  src/tools/helpers/README.md
  src/tools/helpers/dom.js
  src/tools/helpers/package.json
Labels: process: under review, tag: internal

#1737 feat: add select - FRONT-1740
  src/implementations/twig/components/select/.npmignore
  src/implementations/twig/components/select/README.md
  src/implementations/twig/components/select/__snapshots__/select.test.js.snap
  src/implementations/twig/components/select/package.json
  src/implementations/twig/components/select/select.html.twig
  src/implementations/twig/components/select/select.story.js
  src/implementations/twig/components/select/select.test.js
  src/implementations/vanilla/components/select/README.md
  src/implementations/vanilla/components/select/package.json
  src/implementations/vanilla/components/select/select-print.scss
  src/implementations/vanilla/components/select/select.js
  src/implementations/vanilla/components/select/select.scss
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/specs/components/select/demo/data--multiple.js
  src/specs/components/select/demo/data--single.js
  src/specs/components/select/package.json
  src/website/src/pages/ec/components/forms/select/demo/index.js
  src/website/src/pages/ec/components/forms/select/docs/api.mdx
  src/website/src/pages/ec/components/forms/select/docs/code.mdx
  src/website/src/pages/ec/components/forms/select/docs/usage.mdx
  src/website/src/pages/ec/components/forms/select/ec_comp_select.svg
  src/website/src/pages/ec/components/forms/select/index.md
Labels: tag: new feature

#1746 feat(file): Adding component - FRONT-1765
  src/implementations/twig/components/file/.npmignore
  src/implementations/twig/components/file/README.md
  src/implementations/twig/components/file/__snapshots__/file.test.js.snap
  src/implementations/twig/components/file/file.html.twig
  src/implementations/twig/components/file/file.story.js
  src/implementations/twig/components/file/file.test.js
  src/implementations/twig/components/file/package.json
  src/implementations/vanilla/components/file/README.md
  src/implementations/vanilla/components/file/file-print.scss
  src/implementations/vanilla/components/file/file.js
  src/implementations/vanilla/components/file/file.scss
  src/implementations/vanilla/components/file/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/specs/components/file/README.md
  src/specs/components/file/demo/data--thumbnail.js
  src/specs/components/file/demo/data--with-translation.js
  src/specs/components/file/demo/data--without-translation.js
  src/specs/components/file/package.json
  src/website/src/pages/ec/components/file/demo/index.js
  src/website/src/pages/ec/components/file/docs/api.mdx
  src/website/src/pages/ec/components/file/docs/code.mdx
  src/website/src/pages/ec/components/file/docs/usage.mdx
  src/website/src/pages/ec/components/file/ec_comp_file.svg
  src/website/src/pages/ec/components/file/index.md
Labels: process: under review, tag: new feature

#1747 chore: correct storybook iframe styles
  src/implementations/twig/storybook/.storybook/preview-head.html
Labels: process: under review, tag: bug fix

#1749 feat(label): Adding component - FRONT-1766
  src/implementations/twig/components/label/.npmignore
  src/implementations/twig/components/label/README.md
  src/implementations/twig/components/label/__snapshots__/label.test.js.snap
  src/implementations/twig/components/label/label.html.twig
  src/implementations/twig/components/label/label.story.js
  src/implementations/twig/components/label/label.test.js
  src/implementations/twig/components/label/package.json
  src/implementations/vanilla/components/label/README.md
  src/implementations/vanilla/components/label/label-print.scss
  src/implementations/vanilla/components/label/label.scss
  src/implementations/vanilla/components/label/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/label/demo/data.js
  src/specs/components/label/package.json
  src/website/src/pages/ec/components/label/demo/index.js
  src/website/src/pages/ec/components/label/docs/code.mdx
  src/website/src/pages/ec/components/label/docs/usage.mdx
  src/website/src/pages/ec/components/label/index.md
Labels: process: under review, tag: new feature

#1750 feat(timeline): migrate timeline component - FRONT-1770
  src/implementations/twig/components/timeline/.npmignore
  src/implementations/twig/components/timeline/README.md
  src/implementations/twig/components/timeline/__snapshots__/timeline.test.js.snap
  src/implementations/twig/components/timeline/package.json
  src/implementations/twig/components/timeline/timeline.html.twig
  src/implementations/twig/components/timeline/timeline.story.js
  src/implementations/twig/components/timeline/timeline.test.js
  src/implementations/vanilla/components/timeline/README.md
  src/implementations/vanilla/components/timeline/package.json
  src/implementations/vanilla/components/timeline/timeline-print.scss
  src/implementations/vanilla/components/timeline/timeline.js
  src/implementations/vanilla/components/timeline/timeline.scss
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/specs/components/timeline/demo/data.js
  src/specs/components/timeline/package.json
  src/website/src/pages/ec/components/timeline/demo/index.js
  src/website/src/pages/ec/components/timeline/docs/api.mdx
  src/website/src/pages/ec/components/timeline/docs/code.mdx
  src/website/src/pages/ec/components/timeline/docs/usage.mdx
  src/website/src/pages/ec/components/timeline/ec_comp_timeline.svg
  src/website/src/pages/ec/components/timeline/index.md
Labels: process: under review, tag: new feature

#1748 feat(message): migrate component message - FRONT-1767
  src/implementations/twig/components/message/.npmignore
  src/implementations/twig/components/message/README.md
  src/implementations/twig/components/message/__snapshots__/message.test.js.snap
  src/implementations/twig/components/message/message.html.twig
  src/implementations/twig/components/message/message.story.js
  src/implementations/twig/components/message/message.test.js
  src/implementations/twig/components/message/package.json
  src/implementations/vanilla/components/message/README.md
  src/implementations/vanilla/components/message/message-print.scss
  src/implementations/vanilla/components/message/message.js
  src/implementations/vanilla/components/message/message.scss
  src/implementations/vanilla/components/message/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/specs/components/message/demo/data--error.js
  src/specs/components/message/demo/data--info.js
  src/specs/components/message/demo/data--success.js
  src/specs/components/message/demo/data--warning.js
  src/specs/components/message/package.json
  src/website/src/pages/ec/components/message/demo/index.js
  src/website/src/pages/ec/components/message/docs/api.mdx
  src/website/src/pages/ec/components/message/docs/code.mdx
  src/website/src/pages/ec/components/message/docs/usage.mdx
  src/website/src/pages/ec/components/message/ec_comp_messages.svg
  src/website/src/pages/ec/components/message/index.md
Labels: tag: new feature

#1752 fix(scss): fix responsive mixins - FRONT-1762
  src/implementations/twig/storybook/.storybook/preview.js
  src/implementations/vanilla/components/blockquote/blockquote.scss
  src/implementations/vanilla/components/date-block/date-block.scss
  src/implementations/vanilla/components/description-list/description-list.scss
  src/implementations/vanilla/components/fact-figures/fact-figures.scss
  src/implementations/vanilla/components/file/file.scss
  src/implementations/vanilla/components/message/message.scss
  src/implementations/vanilla/components/select/select.scss
  src/implementations/vanilla/components/table/table.scss
  src/implementations/vanilla/components/text-area/text-area.scss
  src/implementations/vanilla/components/text-input/text-input.scss
  src/implementations/vanilla/components/timeline/timeline.scss
  src/implementations/vanilla/layout/grid/mixins/_breakpoints.scss
  src/implementations/vanilla/layout/grid/mixins/_grid-framework.scss
  src/implementations/vanilla/layout/grid/mixins/_grid.scss
  src/implementations/vanilla/utilities/border/border-print.scss
  src/implementations/vanilla/utilities/border/border.scss
  src/implementations/vanilla/utilities/display/display-print.scss
  src/implementations/vanilla/utilities/display/display.scss
  src/implementations/vanilla/utilities/flex/flex-print.scss
  src/implementations/vanilla/utilities/flex/flex.scss
  src/implementations/vanilla/utilities/media/media-print.scss
  src/implementations/vanilla/utilities/media/media.scss
  src/implementations/vanilla/utilities/spacing/spacing-print.scss
  src/implementations/vanilla/utilities/spacing/spacing.scss
  src/implementations/vanilla/utilities/typography/typography.scss
  src/themes/dev/maps/layout.scss
Labels: tag: bug fix

#1754 feat(social-media-share): migrate social media share - FRONT-1769
  src/implementations/twig/components/social-media-share/.npmignore
  src/implementations/twig/components/social-media-share/README.md
  src/implementations/twig/components/social-media-share/__snapshots__/social-media-share.test.js.snap
  src/implementations/twig/components/social-media-share/package.json
  src/implementations/twig/components/social-media-share/social-media-share.html.twig
  src/implementations/twig/components/social-media-share/social-media-share.story.js
  src/implementations/twig/components/social-media-share/social-media-share.test.js
  src/implementations/vanilla/components/social-media-share/README.md
  src/implementations/vanilla/components/social-media-share/package.json
  src/implementations/vanilla/components/social-media-share/social-media-share-print.scss
  src/implementations/vanilla/components/social-media-share/social-media-share.scss
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/social-media-share/demo/data.js
  src/specs/components/social-media-share/package.json
  src/themes/dev/_index.scss
  src/themes/dev/maps/social-media-list.scss
  src/website/src/pages/ec/components/social-media-share/demo/index.js
  src/website/src/pages/ec/components/social-media-share/docs/code.mdx
  src/website/src/pages/ec/components/social-media-share/docs/usage.mdx
  src/website/src/pages/ec/components/social-media-share/ec_comp_social_share.svg
  src/website/src/pages/ec/components/social-media-share/index.md
  src/website/src/utils/correctSvgPath.js
Labels: process: under review, tag: new feature

#1755 feat(media-container): Adding component - FRONT-1777
  src/implementations/twig/components/media-container/.npmignore
  src/implementations/twig/components/media-container/README.md
  src/implementations/twig/components/media-container/__snapshots__/media-container.test.js.snap
  src/implementations/twig/components/media-container/media-container.html.twig
  src/implementations/twig/components/media-container/media-container.story.js
  src/implementations/twig/components/media-container/media-container.test.js
  src/implementations/twig/components/media-container/package.json
  src/implementations/vanilla/components/media-container/README.md
  src/implementations/vanilla/components/media-container/media-container-print.scss
  src/implementations/vanilla/components/media-container/media-container.scss
  src/implementations/vanilla/components/media-container/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/media-container/demo/data--embed-video.js
  src/specs/components/media-container/demo/data--image.js
  src/specs/components/media-container/demo/data--video.js
  src/specs/components/media-container/package.json
  src/website/src/pages/ec/components/media/index.md
  src/website/src/pages/ec/components/media/media-container/demo/index.js
  src/website/src/pages/ec/components/media/media-container/docs/code.mdx
  src/website/src/pages/ec/components/media/media-container/docs/usage.mdx
  src/website/src/pages/ec/components/media/media-container/index.md
Labels: process: review needed, tag: new feature

#1751 feat(social-media-follow): Adding component - FRONT-1768
  src/implementations/twig/components/social-media-follow/.npmignore
  src/implementations/twig/components/social-media-follow/README.md
  src/implementations/twig/components/social-media-follow/__snapshots__/social-media-follow.test.js.snap
  src/implementations/twig/components/social-media-follow/package.json
  src/implementations/twig/components/social-media-follow/social-media-follow.html.twig
  src/implementations/twig/components/social-media-follow/social-media-follow.story.js
  src/implementations/twig/components/social-media-follow/social-media-follow.test.js
  src/implementations/vanilla/components/social-media-follow/README.md
  src/implementations/vanilla/components/social-media-follow/package.json
  src/implementations/vanilla/components/social-media-follow/social-media-follow-print.scss
  src/implementations/vanilla/components/social-media-follow/social-media-follow.scss
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/social-media-follow/demo/data.js
  src/specs/components/social-media-follow/package.json
  src/website/src/pages/ec/components/social-media-follow/demo/index.js
  src/website/src/pages/ec/components/social-media-follow/docs/code.mdx
  src/website/src/pages/ec/components/social-media-follow/docs/usage.mdx
  src/website/src/pages/ec/components/social-media-follow/index.md
Labels: process: review needed, tag: new feature

#1758 feat(file-upload): Adding component - FRONT-1774
  src/implementations/twig/components/file-upload/.npmignore
  src/implementations/twig/components/file-upload/README.md
  src/implementations/twig/components/file-upload/__snapshots__/file-upload.test.js.snap
  src/implementations/twig/components/file-upload/file-upload.html.twig
  src/implementations/twig/components/file-upload/file-upload.story.js
  src/implementations/twig/components/file-upload/file-upload.test.js
  src/implementations/twig/components/file-upload/package.json
  src/implementations/twig/components/select/select.story.js
  src/implementations/vanilla/components/file-upload/README.md
  src/implementations/vanilla/components/file-upload/file-upload-print.scss
  src/implementations/vanilla/components/file-upload/file-upload.js
  src/implementations/vanilla/components/file-upload/file-upload.scss
  src/implementations/vanilla/components/file-upload/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/specs/components/file-upload/demo/data--multiple.js
  src/specs/components/file-upload/demo/data.js
  src/specs/components/file-upload/package.json
  src/tools/story-utils/src/index.js
  src/website/src/pages/ec/components/forms/file-upload/demo/index.js
  src/website/src/pages/ec/components/forms/file-upload/docs/code.mdx
  src/website/src/pages/ec/components/forms/file-upload/docs/usage.mdx
  src/website/src/pages/ec/components/forms/file-upload/ec_comp_file_upload.svg
  src/website/src/pages/ec/components/forms/file-upload/index.md
Labels: tag: new feature

#1756 feat(page-banner): Adding component - FRONT-1772
  src/implementations/twig/components/page-banner/.npmignore
  src/implementations/twig/components/page-banner/README.md
  src/implementations/twig/components/page-banner/__snapshots__/page-banner.test.js.snap
  src/implementations/twig/components/page-banner/package.json
  src/implementations/twig/components/page-banner/page-banner.html.twig
  src/implementations/twig/components/page-banner/page-banner.story.js
  src/implementations/twig/components/page-banner/page-banner.test.js
  src/implementations/vanilla/components/page-banner/README.md
  src/implementations/vanilla/components/page-banner/package.json
  src/implementations/vanilla/components/page-banner/page-banner-print.scss
  src/implementations/vanilla/components/page-banner/page-banner.scss
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/page-banner/demo/data--image-box.js
  src/specs/components/page-banner/demo/data--image-gradient.js
  src/specs/components/page-banner/demo/data--image-shade.js
  src/specs/components/page-banner/demo/data--simple-grey.js
  src/specs/components/page-banner/demo/data--simple-primary.js
  src/specs/components/page-banner/demo/data--simple-white.js
  src/specs/components/page-banner/package.json
  src/website/src/pages/ec/components/banners/index.md
  src/website/src/pages/ec/components/banners/page-banner/demo/index.js
  src/website/src/pages/ec/components/banners/page-banner/docs/code.mdx
  src/website/src/pages/ec/components/banners/page-banner/docs/usage.mdx
  src/website/src/pages/ec/components/banners/page-banner/index.md
Labels: process: under review, tag: new feature

#1763 feat(menu): migrate component menu - FRONT-1780
  src/implementations/twig/components/menu/.npmignore
  src/implementations/twig/components/menu/README.md
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/menu-item.html.twig
  src/implementations/twig/components/menu/menu.html.twig
  src/implementations/twig/components/menu/menu.story.js
  src/implementations/twig/components/menu/menu.test.js
  src/implementations/twig/components/menu/package.json
  src/implementations/vanilla/components/menu/README.md
  src/implementations/vanilla/components/menu/menu-print.scss
  src/implementations/vanilla/components/menu/menu.js
  src/implementations/vanilla/components/menu/menu.scss
  src/implementations/vanilla/components/menu/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/specs/components/menu/demo/data--en.js
  src/specs/components/menu/demo/data--fr.js
  src/specs/components/menu/demo/data--group1.js
  src/specs/components/menu/demo/data--group2.js
  src/specs/components/menu/package.json
  src/website/src/pages/ec/components/navigation/menu/demo/index.js
  src/website/src/pages/ec/components/navigation/menu/docs/api.mdx
  src/website/src/pages/ec/components/navigation/menu/docs/code.mdx
  src/website/src/pages/ec/components/navigation/menu/docs/usage.mdx
  src/website/src/pages/ec/components/navigation/menu/ec_comp_menu.svg
  src/website/src/pages/ec/components/navigation/menu/index.md
  yarn.lock
Labels: Approved, tag: new feature

#1762 feat(gallery): Adding component -FRONT-1776
  src/implementations/twig/components/gallery/.npmignore
  src/implementations/twig/components/gallery/README.md
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/twig/components/gallery/gallery-item.html.twig
  src/implementations/twig/components/gallery/gallery-overlay.html.twig
  src/implementations/twig/components/gallery/gallery-video.html.twig
  src/implementations/twig/components/gallery/gallery.html.twig
  src/implementations/twig/components/gallery/gallery.story.js
  src/implementations/twig/components/gallery/gallery.test.js
  src/implementations/twig/components/gallery/package.json
  src/implementations/vanilla/components/gallery/README.md
  src/implementations/vanilla/components/gallery/gallery-print.scss
  src/implementations/vanilla/components/gallery/gallery.js
  src/implementations/vanilla/components/gallery/gallery.scss
  src/implementations/vanilla/components/gallery/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/specs/components/gallery/demo/data.js
  src/specs/components/gallery/package.json
  src/website/src/pages/ec/components/media/gallery/demo/index.js
  src/website/src/pages/ec/components/media/gallery/docs/api.mdx
  src/website/src/pages/ec/components/media/gallery/docs/code.mdx
  src/website/src/pages/ec/components/media/gallery/docs/usage.mdx
  src/website/src/pages/ec/components/media/gallery/ec_comp_gallery.svg
  src/website/src/pages/ec/components/media/gallery/index.md
  yarn.lock
Labels: Approved, tag: new feature

#1753 feat: migrate hero banner - FRONT-1771
  src/implementations/twig/components/hero-banner/.npmignore
  src/implementations/twig/components/hero-banner/README.md
  src/implementations/twig/components/hero-banner/__snapshots__/hero-banner.test.js.snap
  src/implementations/twig/components/hero-banner/hero-banner.html.twig
  src/implementations/twig/components/hero-banner/hero-banner.story.js
  src/implementations/twig/components/hero-banner/hero-banner.test.js
  src/implementations/twig/components/hero-banner/package.json
  src/implementations/vanilla/components/hero-banner/README.md
  src/implementations/vanilla/components/hero-banner/hero-banner-print.scss
  src/implementations/vanilla/components/hero-banner/hero-banner.scss
  src/implementations/vanilla/components/hero-banner/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/hero-banner/demo/data--image-box.js
  src/specs/components/hero-banner/demo/data--image-gradient.js
  src/specs/components/hero-banner/demo/data--image-shade.js
  src/specs/components/hero-banner/demo/data--simple-grey.js
  src/specs/components/hero-banner/demo/data--simple-primary.js
  src/specs/components/hero-banner/demo/data--simple-white.js
  src/specs/components/hero-banner/package.json
  src/website/src/pages/ec/components/banners/hero-banner/demo/index.js
  src/website/src/pages/ec/components/banners/hero-banner/docs/code.mdx
  src/website/src/pages/ec/components/banners/hero-banner/docs/usage.mdx
  src/website/src/pages/ec/components/banners/hero-banner/ec_comp_hero_banner.svg
  src/website/src/pages/ec/components/banners/hero-banner/index.md
Labels: process: review needed, tag: new feature

#1761 feat(breadcrumb): Adding components - FRONT-1778
  src/implementations/twig/components/breadcrumb-core/.npmignore
  src/implementations/twig/components/breadcrumb-core/README.md
  src/implementations/twig/components/breadcrumb-core/__snapshots__/breadcrumb-core.test.js.snap
  src/implementations/twig/components/breadcrumb-core/breadcrumb-core.html.twig
  src/implementations/twig/components/breadcrumb-core/breadcrumb-core.story.js
  src/implementations/twig/components/breadcrumb-core/breadcrumb-core.test.js
  src/implementations/twig/components/breadcrumb-core/package.json
  src/implementations/twig/components/breadcrumb-harmonised/.npmignore
  src/implementations/twig/components/breadcrumb-harmonised/README.md
  src/implementations/twig/components/breadcrumb-harmonised/__snapshots__/breadcrumb-harmonised.test.js.snap
  src/implementations/twig/components/breadcrumb-harmonised/breadcrumb-harmonised.html.twig
  src/implementations/twig/components/breadcrumb-harmonised/breadcrumb-harmonised.story.js
  src/implementations/twig/components/breadcrumb-harmonised/breadcrumb-harmonised.test.js
  src/implementations/twig/components/breadcrumb-harmonised/package.json
  src/implementations/twig/components/breadcrumb-standardised/.npmignore
  src/implementations/twig/components/breadcrumb-standardised/README.md
  src/implementations/twig/components/breadcrumb-standardised/__snapshots__/breadcrumb-standardised.test.js.snap
  src/implementations/twig/components/breadcrumb-standardised/breadcrumb-standardised.html.twig
  src/implementations/twig/components/breadcrumb-standardised/breadcrumb-standardised.story.js
  src/implementations/twig/components/breadcrumb-standardised/breadcrumb-standardised.test.js
  src/implementations/twig/components/breadcrumb-standardised/package.json
  src/implementations/vanilla/components/breadcrumb-core/README.md
  src/implementations/vanilla/components/breadcrumb-core/breadcrumb-core-print.scss
  src/implementations/vanilla/components/breadcrumb-core/breadcrumb-core.js
  src/implementations/vanilla/components/breadcrumb-core/breadcrumb-core.scss
  src/implementations/vanilla/components/breadcrumb-core/package.json
  src/implementations/vanilla/components/breadcrumb-harmonised/README.md
  src/implementations/vanilla/components/breadcrumb-harmonised/breadcrumb-harmonised-print.scss
  src/implementations/vanilla/components/breadcrumb-harmonised/breadcrumb-harmonised.js
  src/implementations/vanilla/components/breadcrumb-harmonised/breadcrumb-harmonised.scss
  src/implementations/vanilla/components/breadcrumb-harmonised/package.json
  src/implementations/vanilla/components/breadcrumb-standardised/README.md
  src/implementations/vanilla/components/breadcrumb-standardised/breadcrumb-standardised-print.scss
  src/implementations/vanilla/components/breadcrumb-standardised/breadcrumb-standardised.js
  src/implementations/vanilla/components/breadcrumb-standardised/breadcrumb-standardised.scss
  src/implementations/vanilla/components/breadcrumb-standardised/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/specs/components/breadcrumb/demo/data--simple.js
  src/specs/components/breadcrumb/demo/data.js
  src/specs/components/breadcrumb/package.json
  src/website/src/pages/ec/components/navigation/breadcrumb/demo/core.js
  src/website/src/pages/ec/components/navigation/breadcrumb/demo/harmonised.js
  src/website/src/pages/ec/components/navigation/breadcrumb/demo/standardised.js
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/api.mdx
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/code.mdx
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/usage.mdx
  src/website/src/pages/ec/components/navigation/breadcrumb/ec_comp_breadcrumb.svg
  src/website/src/pages/ec/components/navigation/breadcrumb/index.md
Labels: process: under review, tag: new feature

#1759 feat(pagination): Adding component - FRONT-1781
  src/implementations/twig/components/pagination/.npmignore
  src/implementations/twig/components/pagination/README.md
  src/implementations/twig/components/pagination/__snapshots__/pagination.test.js.snap
  src/implementations/twig/components/pagination/package.json
  src/implementations/twig/components/pagination/pagination.html.twig
  src/implementations/twig/components/pagination/pagination.story.js
  src/implementations/twig/components/pagination/pagination.test.js
  src/implementations/vanilla/components/pagination/README.md
  src/implementations/vanilla/components/pagination/package.json
  src/implementations/vanilla/components/pagination/pagination-print.scss
  src/implementations/vanilla/components/pagination/pagination.scss
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/pagination/demo/data.js
  src/specs/components/pagination/package.json
  src/website/src/pages/ec/components/navigation/pagination/demo/index.js
  src/website/src/pages/ec/components/navigation/pagination/docs/code.mdx
  src/website/src/pages/ec/components/navigation/pagination/docs/usage.mdx
  src/website/src/pages/ec/components/navigation/pagination/ec_comp_pagination.svg
  src/website/src/pages/ec/components/navigation/pagination/index.md
Labels: process: review needed, tag: new feature

#1760 feat(search-form): migrate component search form - FRONT-1775
  src/implementations/twig/components/search-form/.npmignore
  src/implementations/twig/components/search-form/README.md
  src/implementations/twig/components/search-form/__snapshots__/search-form.test.js.snap
  src/implementations/twig/components/search-form/package.json
  src/implementations/twig/components/search-form/search-form.html.twig
  src/implementations/twig/components/search-form/search-form.story.js
  src/implementations/twig/components/search-form/search-form.test.js
  src/implementations/vanilla/components/search-form/README.md
  src/implementations/vanilla/components/search-form/package.json
  src/implementations/vanilla/components/search-form/search-form-print.scss
  src/implementations/vanilla/components/search-form/search-form.scss
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/search-form/demo/data.js
  src/specs/components/search-form/package.json
  src/website/src/pages/ec/components/forms/search-form/demo/index.js
  src/website/src/pages/ec/components/forms/search-form/docs/code.mdx
  src/website/src/pages/ec/components/forms/search-form/docs/usage.mdx
  src/website/src/pages/ec/components/forms/search-form/ec_comp_search.svg
  src/website/src/pages/ec/components/forms/search-form/index.md
Labels: Question, tag: new feature

#1757 feat: migrate date picker - FRONT-1773
  package.json
  src/implementations/twig/components/datepicker/.npmignore
  src/implementations/twig/components/datepicker/README.md
  src/implementations/twig/components/datepicker/__snapshots__/datepicker.test.js.snap
  src/implementations/twig/components/datepicker/datepicker.html.twig
  src/implementations/twig/components/datepicker/datepicker.story.js
  src/implementations/twig/components/datepicker/datepicker.test.js
  src/implementations/twig/components/datepicker/package.json
  src/implementations/twig/storybook/.storybook/preview-head.html
  src/implementations/vanilla/components/datepicker/README.md
  src/implementations/vanilla/components/datepicker/datepicker-print.scss
  src/implementations/vanilla/components/datepicker/datepicker.js
  src/implementations/vanilla/components/datepicker/datepicker.scss
  src/implementations/vanilla/components/datepicker/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/presets/ec-core/package.json
  src/presets/eu-core/package.json
  src/specs/components/datepicker/demo/data.js
  src/specs/components/datepicker/package.json
  src/tools/builder/scripts/scripts.js
  src/website/.eslintrc.js
  src/website/src/pages/ec/components/forms/datepicker/demo/index.js
  src/website/src/pages/ec/components/forms/datepicker/docs/api.mdx
  src/website/src/pages/ec/components/forms/datepicker/docs/code.mdx
  src/website/src/pages/ec/components/forms/datepicker/docs/usage.mdx
  src/website/src/pages/ec/components/forms/datepicker/index.md
  yarn.lock
Labels: tag: new feature

#1765 feat(language-list): Adding component - FRONT-1782
  src/implementations/twig/components/language-list/.npmignore
  src/implementations/twig/components/language-list/README.md
  src/implementations/twig/components/language-list/__snapshots__/language-list.test.js.snap
  src/implementations/twig/components/language-list/language-list-grid.html.twig
  src/implementations/twig/components/language-list/language-list-item.html.twig
  src/implementations/twig/components/language-list/language-list.html.twig
  src/implementations/twig/components/language-list/language-list.story.js
  src/implementations/twig/components/language-list/language-list.test.js
  src/implementations/twig/components/language-list/package.json
  src/implementations/vanilla/components/language-list/README.md
  src/implementations/vanilla/components/language-list/language-list-print.scss
  src/implementations/vanilla/components/language-list/language-list.scss
  src/implementations/vanilla/components/language-list/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/language-list/demo/data--overlay.js
  src/specs/components/language-list/demo/data--splash.js
  src/specs/components/language-list/package.json
  src/website/src/pages/ec/components/language-list/demo/index.js
  src/website/src/pages/ec/components/language-list/docs/code.mdx
  src/website/src/pages/ec/components/language-list/docs/usage.mdx
  src/website/src/pages/ec/components/language-list/ec_comp_language_list.svg
  src/website/src/pages/ec/components/language-list/index.md
Labels: process: review needed, tag: new feature

#1767 feat(footer-core): Adding component - FRONT-1795
  src/implementations/twig/components/footer-core/README.md
  src/implementations/twig/components/footer-core/__snapshots__/footer-core.test.js.snap
  src/implementations/twig/components/footer-core/footer-core.html.twig
  src/implementations/twig/components/footer-core/footer-core.story.js
  src/implementations/twig/components/footer-core/footer-core.test.js
  src/implementations/twig/components/footer-core/package.json
  src/implementations/vanilla/components/footer-core/README.md
  src/implementations/vanilla/components/footer-core/footer-core-print.scss
  src/implementations/vanilla/components/footer-core/footer-core.scss
  src/implementations/vanilla/components/footer-core/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/footer-core/demo/data.js
  src/specs/components/footer-core/package.json
  src/website/.eslintrc.js
  src/website/src/pages/ec/core-template/footer/demo/index.js
  src/website/src/pages/ec/core-template/footer/docs/code.mdx
  src/website/src/pages/ec/core-template/footer/docs/usage.mdx
  src/website/src/pages/ec/core-template/footer/index.md
  src/website/src/pages/ec/core-template/index.md
Labels: process: review needed, process: under review, tag: new feature

#1768 feat(skip-link): Adding component - FRONT-1806
  src/implementations/twig/components/skip-link/README.md
  src/implementations/twig/components/skip-link/__snapshots__/skip-link.test.js.snap
  src/implementations/twig/components/skip-link/package.json
  src/implementations/twig/components/skip-link/skip-link.html.twig
  src/implementations/twig/components/skip-link/skip-link.story.js
  src/implementations/twig/components/skip-link/skip-link.test.js
  src/implementations/vanilla/components/skip-link/README.md
  src/implementations/vanilla/components/skip-link/package.json
  src/implementations/vanilla/components/skip-link/skip-link-print.scss
  src/implementations/vanilla/components/skip-link/skip-link.scss
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/skip-link/demo/data.js
  src/specs/components/skip-link/package.json
  src/website/src/pages/ec/components/navigation/skip-link/demo/index.js
  src/website/src/pages/ec/components/navigation/skip-link/docs/code.mdx
  src/website/src/pages/ec/components/navigation/skip-link/docs/usage.md
  src/website/src/pages/ec/components/navigation/skip-link/index.md
Labels: process: review needed, process: under review, tag: new feature

#1764 feat(inpage-navigation): Adding component - FRONT-1779
  src/implementations/twig/components/inpage-navigation/.npmignore
  src/implementations/twig/components/inpage-navigation/README.md
  src/implementations/twig/components/inpage-navigation/__snapshots__/inpage-navigation.test.js.snap
  src/implementations/twig/components/inpage-navigation/inpage-navigation.html.twig
  src/implementations/twig/components/inpage-navigation/inpage-navigation.story.js
  src/implementations/twig/components/inpage-navigation/inpage-navigation.test.js
  src/implementations/twig/components/inpage-navigation/package.json
  src/implementations/twig/components/media-container/media-container.story.js
  src/implementations/vanilla/components/inpage-navigation/README.md
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation-print.scss
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation.js
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation.scss
  src/implementations/vanilla/components/inpage-navigation/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/specs/components/inpage-navigation/demo/data.js
  src/specs/components/inpage-navigation/package.json
  src/website/src/pages/ec/components/navigation/inpage-navigation/demo/index.js
  src/website/src/pages/ec/components/navigation/inpage-navigation/docs/api.mdx
  src/website/src/pages/ec/components/navigation/inpage-navigation/docs/code.mdx
  src/website/src/pages/ec/components/navigation/inpage-navigation/docs/usage.mdx
  src/website/src/pages/ec/components/navigation/inpage-navigation/examples/default.html
  src/website/src/pages/ec/components/navigation/inpage-navigation/index.md
  yarn.lock
Labels: process: review needed, process: under review, tag: new feature

#1769 feat(footer-standardised) - Adding component - FRONT-1796
  src/implementations/twig/components/footer-standardised/README.md
  src/implementations/twig/components/footer-standardised/__snapshots__/footer-standardised.test.js.snap
  src/implementations/twig/components/footer-standardised/footer-standardised.html.twig
  src/implementations/twig/components/footer-standardised/footer-standardised.story.js
  src/implementations/twig/components/footer-standardised/footer-standardised.test.js
  src/implementations/twig/components/footer-standardised/package.json
  src/implementations/vanilla/components/footer-standardised/README.md
  src/implementations/vanilla/components/footer-standardised/footer-standardised-print.scss
  src/implementations/vanilla/components/footer-standardised/footer-standardised.scss
  src/implementations/vanilla/components/footer-standardised/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/footer-standardised/demo/data.js
  src/specs/components/footer-standardised/package.json
  src/website/src/pages/ec/standardised-template/footer/demo/index.js
  src/website/src/pages/ec/standardised-template/footer/docs/code.mdx
  src/website/src/pages/ec/standardised-template/footer/docs/usage.mdx
  src/website/src/pages/ec/standardised-template/footer/index.md
  src/website/src/pages/ec/standardised-template/index.mdx
Labels: process: under review, tag: new feature

#1766 feat(menu): update menu display and behavior - FRONT-1790
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/ec-component-menu.js
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/ec-component-menu.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-menu/eu-component-menu.js
  src/systems/eu/implementations/vanilla/packages/eu-component-menu/eu-component-menu.scss
Labels: tag: enhancement

#1770 chore: V3 branch fixes
  src/implementations/vanilla/components/gallery/gallery.js
  src/implementations/vanilla/components/radio/radio.scss
  src/website/src/pages/ec/components/timeline/docs/api.mdx
Labels: tag: internal

#1771 feat(footer-harmonised): Adding component - FRONT-1797
  src/implementations/twig/components/footer-harmonised/README.md
  src/implementations/twig/components/footer-harmonised/__snapshots__/footer-harmonised.test.js.snap
  src/implementations/twig/components/footer-harmonised/footer-harmonised.html.twig
  src/implementations/twig/components/footer-harmonised/footer-harmonised.story.js
  src/implementations/twig/components/footer-harmonised/footer-harmonised.test.js
  src/implementations/twig/components/footer-harmonised/package.json
  src/implementations/vanilla/components/footer-harmonised/README.md
  src/implementations/vanilla/components/footer-harmonised/footer-harmonised-print.scss
  src/implementations/vanilla/components/footer-harmonised/footer-harmonised.scss
  src/implementations/vanilla/components/footer-harmonised/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/footer-harmonised/demo/data--group1.js
  src/specs/components/footer-harmonised/demo/data--group2.js
  src/specs/components/footer-harmonised/demo/data--group3.js
  src/specs/components/footer-harmonised/package.json
  src/website/src/pages/ec/harmonised-templates/footer/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/footer/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/footer/docs/group3.mdx
  src/website/src/pages/ec/harmonised-templates/footer/index.md
  src/website/src/pages/ec/harmonised-templates/index.mdx
Labels: process: review needed, tag: new feature

#1773 fix(footers): remove reference to Brexit - FRONT-1794
  src/systems/ec/specs/components/footer-core/demo/data.js
  src/systems/ec/specs/components/footer-harmonised/demo/data--group1.js
  src/systems/ec/specs/components/footer-harmonised/demo/data--group2.js
  src/systems/ec/specs/components/footer-standardised/demo/data.js
  src/systems/eu/specs/components/footer-core/demo/data.js
  src/systems/eu/specs/components/footer-harmonised/demo/data.js
  src/systems/eu/specs/components/footer-standardised/demo/data.js
Labels: process: review needed, tag: documentation

#1774 fix(logo): update mt logo - FRONT-1793
  src/systems/ec/resources/logo/logo--mt.svg
Labels: process: review needed, tag: enhancement

#1776 docs(highlight): update usage page - FRONT-1792
  src/systems/ec/implementations/react/templates/compositions/highlight/stories/Index.jsx
  src/website/src/pages/ec/compositions/highlight/docs/code.mdx
  src/website/src/pages/ec/compositions/highlight/docs/usage.mdx
  src/website/src/pages/ec/compositions/highlight/index.md
Labels: process: under review, tag: documentation

#1778 docs: update footer-harmonised
  src/implementations/twig/components/footer-harmonised/README.md
Labels: process: review needed, tag: documentation

#1777 fix: correct breakpoints
  src/implementations/vanilla/components/message/message.scss
  src/implementations/vanilla/utilities/typography/typography.scss
Labels: process: review needed, tag: bug fix

#1779 fix(website): fix link style - FRONT-1788
  src/website/src/website-components/Link/Link.scss
Labels: process: review needed, tag: bug fix

#1780 chore: remove public flag
  src/implementations/twig/components/file-upload/package.json
Labels: process: under review, tag: internal

#1775 feat(site-header-standardised): Adding component - FRONT-1799
  src/implementations/twig/components/site-header-standardised/.npmignore
  src/implementations/twig/components/site-header-standardised/README.md
  src/implementations/twig/components/site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/implementations/twig/components/site-header-standardised/package.json
  src/implementations/twig/components/site-header-standardised/site-header-standardised.html.twig
  src/implementations/twig/components/site-header-standardised/site-header-standardised.story.js
  src/implementations/twig/components/site-header-standardised/site-header-standardised.test.js
  src/implementations/vanilla/components/site-header-standardised/README.md
  src/implementations/vanilla/components/site-header-standardised/package.json
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised-print.scss
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised.js
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised.scss
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/specs/components/site-header-standardised/demo/data--fr.js
  src/specs/components/site-header-standardised/demo/data.js
  src/specs/components/site-header-standardised/package.json
  src/website/src/pages/ec/standardised-template/site-header/demo/index.js
  src/website/src/pages/ec/standardised-template/site-header/docs/api.mdx
  src/website/src/pages/ec/standardised-template/site-header/docs/code.mdx
  src/website/src/pages/ec/standardised-template/site-header/docs/usage.mdx
  src/website/src/pages/ec/standardised-template/site-header/index.md
Labels: process: under review, tag: new feature

#1772 feat(site-header-core): Adding component, FRONT-1798
  src/implementations/twig/components/site-header-core/.npmignore
  src/implementations/twig/components/site-header-core/README.md
  src/implementations/twig/components/site-header-core/__snapshots__/site-header-core.test.js.snap
  src/implementations/twig/components/site-header-core/package.json
  src/implementations/twig/components/site-header-core/site-header-core.html.twig
  src/implementations/twig/components/site-header-core/site-header-core.story.js
  src/implementations/twig/components/site-header-core/site-header-core.test.js
  src/implementations/vanilla/components/site-header-core/README.md
  src/implementations/vanilla/components/site-header-core/package.json
  src/implementations/vanilla/components/site-header-core/site-header-core-print.scss
  src/implementations/vanilla/components/site-header-core/site-header-core.js
  src/implementations/vanilla/components/site-header-core/site-header-core.scss
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/specs/components/site-header-core/demo/data--fr.js
  src/specs/components/site-header-core/demo/data.js
  src/specs/components/site-header-core/package.json
  src/website/src/pages/ec/core-template/site-header/demo/index.js
  src/website/src/pages/ec/core-template/site-header/docs/api.mdx
  src/website/src/pages/ec/core-template/site-header/docs/code.mdx
  src/website/src/pages/ec/core-template/site-header/docs/usage.mdx
  src/website/src/pages/ec/core-template/site-header/index.md
Labels: tag: new feature

#1781 feat: add site header harmonised - FRONT-1800
  src/implementations/twig/components/site-header-harmonised/.npmignore
  src/implementations/twig/components/site-header-harmonised/README.md
  src/implementations/twig/components/site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/implementations/twig/components/site-header-harmonised/package.json
  src/implementations/twig/components/site-header-harmonised/site-header-harmonised.html.twig
  src/implementations/twig/components/site-header-harmonised/site-header-harmonised.story.js
  src/implementations/twig/components/site-header-harmonised/site-header-harmonised.test.js
  src/implementations/vanilla/components/site-header-harmonised/README.md
  src/implementations/vanilla/components/site-header-harmonised/package.json
  src/implementations/vanilla/components/site-header-harmonised/site-header-harmonised-print.scss
  src/implementations/vanilla/components/site-header-harmonised/site-header-harmonised.js
  src/implementations/vanilla/components/site-header-harmonised/site-header-harmonised.scss
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/specs/components/site-header-harmonised/demo/data--group1.js
  src/specs/components/site-header-harmonised/demo/data--group2.js
  src/specs/components/site-header-harmonised/demo/data--group3.js
  src/specs/components/site-header-harmonised/package.json
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group3.mdx
  src/website/src/pages/ec/harmonised-templates/site-header/index.md
Labels: process: review needed, tag: new feature

#1782 feat(page-header-standardised): Adding component - FRONT-1802
  src/implementations/twig/components/page-header-standardised/.npmignore
  src/implementations/twig/components/page-header-standardised/README.md
  src/implementations/twig/components/page-header-standardised/__snapshots__/page-header-standardised.test.js.snap
  src/implementations/twig/components/page-header-standardised/package.json
  src/implementations/twig/components/page-header-standardised/page-header-standardised.html.twig
  src/implementations/twig/components/page-header-standardised/page-header-standardised.story.js
  src/implementations/twig/components/page-header-standardised/page-header-standardised.test.js
  src/implementations/vanilla/components/page-header-standardised/README.md
  src/implementations/vanilla/components/page-header-standardised/package.json
  src/implementations/vanilla/components/page-header-standardised/page-header-standardised-print.scss
  src/implementations/vanilla/components/page-header-standardised/page-header-standardised.scss
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/page-header-standardised/demo/data--meta-title-description.js
  src/specs/components/page-header-standardised/demo/data--meta-title.js
  src/specs/components/page-header-standardised/demo/data--title.js
  src/specs/components/page-header-standardised/package.json
  src/website/src/pages/ec/standardised-template/page-header/demo/index.js
  src/website/src/pages/ec/standardised-template/page-header/docs/code.mdx
  src/website/src/pages/ec/standardised-template/page-header/docs/usage.mdx
  src/website/src/pages/ec/standardised-template/page-header/index.md
Labels: process: review needed, tag: new feature

#1784 feat(page-header-harmonised): Adding component - FRONT-1803
  src/implementations/twig/components/page-header-harmonised/.npmignore
  src/implementations/twig/components/page-header-harmonised/README.md
  src/implementations/twig/components/page-header-harmonised/__snapshots__/page-header-harmonised.test.js.snap
  src/implementations/twig/components/page-header-harmonised/package.json
  src/implementations/twig/components/page-header-harmonised/page-header-harmonised.html.twig
  src/implementations/twig/components/page-header-harmonised/page-header-harmonised.story.js
  src/implementations/twig/components/page-header-harmonised/page-header-harmonised.test.js
  src/implementations/vanilla/components/page-header-harmonised/README.md
  src/implementations/vanilla/components/page-header-harmonised/package.json
  src/implementations/vanilla/components/page-header-harmonised/page-header-harmonised-print.scss
  src/implementations/vanilla/components/page-header-harmonised/page-header-harmonised.scss
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/page-header-harmonised/demo/data--meta-title-description.js
  src/specs/components/page-header-harmonised/demo/data--meta-title.js
  src/specs/components/page-header-harmonised/demo/data--title.js
  src/specs/components/page-header-harmonised/package.json
  src/website/src/pages/ec/harmonised-templates/page-header/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/page-header/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/page-header/index.md
Labels: tag: new feature

#1787 feat(sync): apply latest v2 modifications - FRONT-1811
  src/implementations/vanilla/components/menu/menu.js
  src/implementations/vanilla/components/menu/menu.scss
  src/resources/logo-ec/logo--mt.svg
Labels: process: under review, tag: enhancement

#1783 feat(token): add eu tokens - FRONT-1814
  src/implementations/vanilla/utilities/background/background-print.scss
  src/implementations/vanilla/utilities/background/background.scss
  src/presets/ec-preset-full/src/ec-preset-full-print.scss
  src/presets/ec-preset-full/src/ec-preset-full.scss
  src/presets/ec-preset-website/src/ec-preset-website-print.scss
  src/presets/ec-preset-website/src/ec-preset-website.scss
  src/themes/dev/maps/color.scss
  src/themes/eu-core/_index.scss
Labels: tag: new feature

#1788 chore: upgrade dependencies - FRONT-324
  package.json
  src/implementations/twig/layout/grid/examples/234612.html
  src/implementations/twig/layout/grid/examples/282.html
  src/implementations/twig/layout/grid/examples/336.html
  src/implementations/twig/layout/grid/examples/642.html
  src/implementations/twig/layout/grid/examples/offset.html
  src/implementations/twig/layout/grid/examples/responsive.html
  src/implementations/twig/storybook/package.json
  src/implementations/vanilla/components/gallery/gallery.js
  src/implementations/vanilla/components/gallery/package.json
  src/implementations/vanilla/components/menu/package.json
  src/implementations/vanilla/components/site-header-core/package.json
  src/implementations/vanilla/components/site-header-core/site-header-core.js
  src/implementations/vanilla/components/site-header-harmonised/package.json
  src/implementations/vanilla/components/site-header-harmonised/site-header-harmonised.js
  src/implementations/vanilla/components/site-header-standardised/package.json
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised.js
  src/tools/builder/package.json
  src/tools/story-wrapper/package.json
  src/tools/storybook-addon-code/package.json
  src/tools/storybook-addon-notes/package.json
  src/website/package.json
  src/website/src/pages/ec/components/file/docs/api.mdx
  src/website/src/pages/ec/components/navigation/menu/docs/api.mdx
  src/website/webpack.config.dev.js
  src/website/webpack.config.prod.js
  yarn.lock
Labels: process: under review, tag: internal

#1785 feat(page-header-core): Adding component - FRONT-1801
  src/implementations/twig/components/page-header-core/.npmignore
  src/implementations/twig/components/page-header-core/README.md
  src/implementations/twig/components/page-header-core/__snapshots__/page-header-core.test.js.snap
  src/implementations/twig/components/page-header-core/package.json
  src/implementations/twig/components/page-header-core/page-header-core.html.twig
  src/implementations/twig/components/page-header-core/page-header-core.story.js
  src/implementations/twig/components/page-header-core/page-header-core.test.js
  src/implementations/vanilla/components/page-header-core/README.md
  src/implementations/vanilla/components/page-header-core/package.json
  src/implementations/vanilla/components/page-header-core/page-header-core-print.scss
  src/implementations/vanilla/components/page-header-core/page-header-core.scss
  src/presets/dev/package.json
  src/presets/dev/src/dev-print.scss
  src/presets/dev/src/dev.scss
  src/specs/components/page-header-core/demo/data--background-image.js
  src/specs/components/page-header-core/demo/data--meta-title-description.js
  src/specs/components/page-header-core/demo/data--meta-title.js
  src/specs/components/page-header-core/demo/data--title.js
  src/specs/components/page-header-core/package.json
  src/website/src/pages/ec/core-template/page-header/demo/index.js
  src/website/src/pages/ec/core-template/page-header/docs/code.mdx
  src/website/src/pages/ec/core-template/page-header/docs/usage.mdx
  src/website/src/pages/ec/core-template/page-header/index.md
Labels: tag: new feature
