Repository ec-europa/europa-component-library, pull requests merged in 2021-06, with the labels that each got.

#2086 feat(inpage-nav): update EC and add EU - FRONT-2203
  src/implementations/twig/components/inpage-navigation/__snapshots__/inpage-navigation.test.js.snap
  src/implementations/twig/components/inpage-navigation/inpage-navigation.html.twig
  src/implementations/twig/components/inpage-navigation/inpage-navigation.story.js
  src/implementations/vanilla/components/inpage-navigation/_inpage-navigation.scss
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation-ec.scss
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation-eu.scss
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation.js
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
Labels: tag: new feature

#2071 feat(tags): Adding EU styles, revamping EC - FRONT-2124
  docs/Migrating-v3.md
  src/implementations/twig/components/tag/__snapshots__/tag.test.js.snap
  src/implementations/twig/components/tag/tag.html.twig
  src/implementations/vanilla/components/tag/_tag.scss
  src/implementations/vanilla/components/tag/tag-ec.scss
  src/implementations/vanilla/components/tag/tag-eu.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
Labels: tag: new feature

#2084 feat(stories): Set padding by default for all stories and make some fullscreen - FRONT-2211
  src/implementations/twig/components/breadcrumb-core/breadcrumb-core.story.js
  src/implementations/twig/components/breadcrumb-harmonised/breadcrumb-harmonised.story.js
  src/implementations/twig/components/breadcrumb-standardised/breadcrumb-standardised.story.js
  src/implementations/twig/components/footer-core/footer-core.story.js
  src/implementations/twig/components/footer-harmonised/ec-footer-harmonised.story.js
  src/implementations/twig/components/footer-harmonised/eu-footer-harmonised.story.js
  src/implementations/twig/components/footer-standardised/footer-standardised.story.js
  src/implementations/twig/components/gallery/gallery.story.js
  src/implementations/twig/components/hero-banner/hero-banner.story.js
  src/implementations/twig/components/inpage-navigation/inpage-navigation.story.js
  src/implementations/twig/components/language-list/language-list.story.js
  src/implementations/twig/components/menu/menu.story.js
  src/implementations/twig/components/page-banner/page-banner.story.js
  src/implementations/twig/components/page-header-core/page-header-core.story.js
  src/implementations/twig/components/page-header-harmonised/page-header-harmonised.story.js
  src/implementations/twig/components/page-header-standardised/page-header-standardised.story.js
  src/implementations/twig/components/pagination/pagination.story.js
  src/implementations/twig/components/site-header-core/site-header-core.story.js
  src/implementations/twig/components/site-header-harmonised/ec-site-header-harmonised.story.js
  src/implementations/twig/components/site-header-harmonised/eu-site-header-harmonised.story.js
  src/implementations/twig/components/site-header-standardised/site-header-standardised.story.js
  src/playground/ec/.storybook/preview.js
  src/playground/eu/.storybook/preview.js
Labels: process: review needed, tag: new feature

#2087 fix(icons/toolchain): Fixing svg icons, setting right system in Js via rollup - front-2187
  src/presets/ec/package.json
  src/presets/eu/package.json
  src/resources/icons-ec/scripts/config/svgo.js
  src/resources/icons-eu/scripts/config/svgo.js
  src/tools/builder/package.json
  src/tools/builder/scripts/scripts.js
  yarn.lock
Labels: process: under review, tag: enhancement

#2090 chore(deps): Safe updates
  package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2085 feat(datepicker): Adding EU styles, revamping EC - FRONT-2249
  src/implementations/vanilla/components/datepicker/_datepicker.scss
  src/implementations/vanilla/components/datepicker/datepicker-ec.scss
  src/implementations/vanilla/components/datepicker/datepicker-eu.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
Labels: tag: new feature

#2093 fix(gallery): Pause video on overlay closing - FRONT-2273
  src/implementations/vanilla/components/gallery/gallery.js
Labels: tag: bug fix

#2092 fix(gallery): Pause video on overlay closing - FRONT-2273
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/ec-component-gallery.js
  src/systems/eu/implementations/vanilla/packages/eu-component-gallery/eu-component-gallery.js
Labels: tag: bug fix

#2081 feat(lists): Adding EU styles, revamping EC - FRONT-2253
  src/implementations/vanilla/components/description-list/_description-list.scss
  src/implementations/vanilla/components/description-list/description-list-ec.scss
  src/implementations/vanilla/components/description-list/description-list-eu.scss
  src/implementations/vanilla/components/ordered-list/_ordered-list.scss
  src/implementations/vanilla/components/ordered-list/ordered-list-ec.scss
  src/implementations/vanilla/components/ordered-list/ordered-list-eu.scss
  src/implementations/vanilla/components/unordered-list/_unordered-list.scss
  src/implementations/vanilla/components/unordered-list/unordered-list-ec.scss
  src/implementations/vanilla/components/unordered-list/unordered-list-eu.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  yarn.lock
Labels: tag: new feature

#2089 feat(language-list): Revamping EC and EU - FRONT-2250
  docs/Migrating-v3.md
  src/implementations/twig/components/language-list/__snapshots__/language-list.test.js.snap
  src/implementations/twig/components/language-list/language-list.html.twig
  src/implementations/twig/components/site-header-core/__snapshots__/site-header-core.test.js.snap
  src/implementations/twig/components/site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/implementations/twig/components/site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/implementations/vanilla/components/language-list/_language-list.scss
  src/implementations/vanilla/components/language-list/language-list-ec.scss
  src/implementations/vanilla/components/language-list/language-list-eu.scss
Labels: process: review needed, tag: enhancement

#2094 chore(deps): safe updates - 07.06.21
  package.json
  src/tools/builder/package.json
  src/tools/storybook-addon-code/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2096 fix(icons): Icons not displaying on footer standardised - FRONT-2328
  src/implementations/twig/components/footer-harmonised/__snapshots__/footer-harmonised.test.js.snap
  src/implementations/twig/components/footer-standardised/__snapshots__/footer-standardised.test.js.snap
  src/playground/addons/story-utils/index.js
  src/playground/addons/story-utils/package.json
  src/specs/components/footer-harmonised/demo/data--group1.js
  src/specs/components/footer-standardised/demo/data--ec.js
Labels: tag: bug fix

#2099 feat(Europa family for EU): update Europa family for EU “eu_core_template”
  src/website/src/pages/eu/core-template/index.md
Labels: netlify-cms/pending_publish

#2097 style(color): Added the EC grey 3% in the EC color palette - FRONT-2232
  src/themes/dev/maps/color.scss
  src/themes/dev/tokens.json
  src/themes/eu/_index.scss
Labels: process: under review, tag: enhancement

#2102 feat(EU Usage pages for components): update EU Usage pages for components “eu_page_header_core”
  cms-images/eu_core_page_header.png
  src/website/src/pages/eu/core-template/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2103 feat(EU Usage pages for components): update EU Usage pages for components “eu_footer_core”
  src/website/src/pages/eu/core-template/footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2104 feat(EU Usage pages for components): update EU Usage pages for components “eu_site_header_core”
  src/website/src/pages/eu/core-template/site-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2105 feat(Europa family for EU): update Europa family for EU “eu_standardised_template”
  src/website/src/pages/eu/standardised-template/index.md
Labels: netlify-cms/pending_publish

#2106 feat(EU Usage pages for components): update EU Usage pages for components “eu_site_header_standardised”
  src/website/src/pages/eu/standardised-template/site-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2107 feat(EU Usage pages for components): update EU Usage pages for components “eu_page_header_standardised”
  src/website/src/pages/eu/standardised-template/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2108 feat(EU Usage pages for components): update EU Usage pages for components “eu_footer_standardised”
  src/website/src/pages/eu/standardised-template/footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2101 feat(Europa family for EU): update Europa family for EU “eu_core_template”
  src/website/src/pages/eu/core-template/index.md
Labels: netlify-cms/pending_publish

#2109 feat(Europa family for EC): update Europa family for EC “ec_core_template”
  src/website/src/pages/ec/core-template/index.md
Labels: netlify-cms/pending_publish

#2110 feat(Europa family for EC): update Europa family for EC “ec_standardised_template”
  src/website/src/pages/ec/standardised-template/index.md
Labels: netlify-cms/pending_publish

#2111 feat(EU Guidelines): update EU Guidelines “eu_guidelines_index”
  src/website/src/pages/eu/guidelines/index.md
Labels: netlify-cms/pending_publish

#2100 feat(example): add sorry page - FRONT-2329
  examples/sorry-page/sorry.html
Labels: tag: new feature

#2115 feat(EC Usage pages for components): update EC Usage pages for components “ec_footer_core”
  src/website/src/pages/ec/core-template/footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2116 feat(EC Usage pages for components): update EC Usage pages for components “ec_site_header_core”
  src/website/src/pages/ec/core-template/site-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2117 feat(EC Usage pages for components): update EC Usage pages for components “ec_page_header_core”
  src/website/src/pages/ec/core-template/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2118 feat(EC Usage pages for components): update EC Usage pages for components “ec_footer_standardised”
  cms-images/standardised-footer.png
  src/website/src/pages/ec/standardised-template/footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2119 feat(EC Usage pages for components): update EC Usage pages for components “ec_page_header_standardised”
  src/website/src/pages/ec/standardised-template/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2120 feat(EC Usage pages for components): update EC Usage pages for components “ec_site_header_standardised”
  cms-images/standardised-site-header.png
  src/website/src/pages/ec/standardised-template/site-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2113 chore(deps): Updates, fixing audit issues - 21.06.21 - ECL-v2
  .github/workflows/ci.yml
  .size-limit.json
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  src/systems/ec/implementations/react/storybook/.storybook/.babelrc
  src/systems/ec/implementations/react/storybook/.storybook/main.js
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/implementations/react/templates/pages/commemorative-coin/src/CommemorativeCoinPage.jsx
  src/systems/ec/implementations/react/templates/pages/department/src/DepartmentPage.jsx
  src/systems/ec/implementations/react/templates/pages/event-speaker/src/EventSpeakerPage.jsx
  src/systems/ec/implementations/react/templates/pages/job-person-list/src/PersonListPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-hub/src/MainPolicyHubPage.jsx
  src/systems/ec/implementations/react/templates/pages/main-policy-resources/src/MainPolicyResourcesPage.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-form-datepicker/ec-component-form-datepicker.js
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/ec-component-gallery.js
  src/systems/ec/implementations/vanilla/packages/ec-component-inpage-navigation/ec-component-inpage-navigation.js
  src/systems/ec/specs/components/footer-harmonised/demo/data--group3.js
  src/systems/ec/specs/components/gallery/demo/data.js
  src/systems/ec/specs/templates/content-item/demo/data--custom.js
  src/systems/ec/specs/templates/content-item/demo/data--image-left.js
  src/systems/ec/specs/templates/highlight/demo/data--image.js
  src/systems/ec/themes/default/scripts/formats/scss-map.js
  src/systems/eu/implementations/react/storybook/.storybook/.babelrc
  src/systems/eu/implementations/react/storybook/.storybook/main.js
  src/systems/eu/implementations/react/storybook/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-form-datepicker/eu-component-form-datepicker.js
  src/systems/eu/implementations/vanilla/packages/eu-component-gallery/eu-component-gallery.js
  src/systems/eu/implementations/vanilla/packages/eu-component-inpage-navigation/eu-component-inpage-navigation.js
  src/systems/eu/specs/components/gallery/demo/data.js
  src/systems/eu/specs/templates/content-item/demo/data--custom.js
  src/systems/eu/specs/templates/content-item/demo/data--image-left.js
  src/systems/eu/specs/templates/highlight/demo/data--image.js
  src/systems/eu/themes/default/scripts/formats/scss-map.js
  src/tools/builder/package.json
  src/tools/storybook-addon-code/package.json
  src/website/config/polyfills.js
  src/website/package.json
  src/website/src/components/Navigation/NavigationLink.jsx
  yarn.lock
Labels: tag: internal

#2122 feat(EC Usage pages for components): update EC Usage pages for components “ec_hero_banner”
  src/website/src/pages/ec/components/banners/hero-banner/docs/usage.md
Labels: netlify-cms/pending_publish

#2124 feat(EU Usage pages for components): update EU Usage pages for components “eu_hero_banner”
  src/website/src/pages/eu/components/banners/hero-banner/docs/usage.md
Labels: netlify-cms/pending_publish

#2125 feat(EC Usage pages for components): update EC Usage pages for components “ec_footer_standardised”
  src/website/src/pages/ec/standardised-template/footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2126 feat(Europa family for EC): update Europa family for EC “ec_core_template”
  src/website/src/pages/ec/core-template/index.md
Labels: netlify-cms/pending_publish

#2112 chore(ci): Updating pipeline, publishing zip files, removing deployment
  .drone.yml
Labels: tag: internal

#2127 feat(select-multiple): ECL v3 - Dispatching change event on user selection - FRONT-2268
  src/implementations/vanilla/components/select/select.js
Labels: Question, tag: enhancement

#2121 feat(select-multiple): ECL v2 - dispatching change event on user selection - FRONT-2268
  src/systems/ec/implementations/vanilla/packages/ec-component-form-select/ec-component-form-select.js
  src/systems/eu/implementations/vanilla/packages/eu-component-form-select/eu-component-form-select.js
Labels: process: under review, tag: enhancement

#2129 fix(accordion): fix print css conflict - FRONT-2325
  src/implementations/vanilla/components/accordion/accordion-print.scss
Labels: tag: enhancement

#2130 feat(style): update background and border - FRONT-2338
  src/implementations/vanilla/components/accordion/accordion-ec.scss
  src/implementations/vanilla/components/card/card-ec.scss
  src/implementations/vanilla/components/file/_file.scss
  src/implementations/vanilla/components/file/file-ec.scss
  src/implementations/vanilla/components/file/file-eu.scss
  src/implementations/vanilla/components/label/_label-print.scss
  src/implementations/vanilla/components/label/_label.scss
  src/implementations/vanilla/components/label/label-ec.scss
  src/implementations/vanilla/components/label/label-eu.scss
  src/implementations/vanilla/components/label/label-print-ec.scss
  src/implementations/vanilla/components/label/label-print-eu.scss
  src/implementations/vanilla/components/media-container/_media-container.scss
  src/implementations/vanilla/components/media-container/media-container-ec.scss
  src/implementations/vanilla/components/media-container/media-container-eu.scss
  src/implementations/vanilla/components/social-media-follow/social-media-follow.scss
Labels: tag: enhancement

#2132 chore(deps): Storybook 6.3 and other updates
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2133 chore(deps): Storybook 6.3, other updates
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/eu/implementations/react/storybook/package.json
  src/tools/builder/package.json
  src/tools/storybook-addon-code/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2131 docs(eu-colors) - changed doc of eu colors - FRONT-2257
  src/themes/ec/tokens.json
  src/themes/eu/_index.scss
  src/themes/eu/tokens.json
  src/website/src/pages/ec/guidelines/colours/index.md
  src/website/src/pages/eu/guidelines/colours/index.md
Labels: process: under review, tag: documentation

#2135 fix(timeline): fix deprecated css - FRONT-2355
  src/implementations/vanilla/components/timeline/_timeline.scss
Labels: tag: enhancement

#2136 chore(website): Anatomy images full width
  src/website/package.json
  src/website/src/styles/markdown.scss
  src/website/webpack.config.dev.js
  src/website/webpack.config.prod.js
  yarn.lock
Labels: tag: internal

#2098 feat(EC Guidelines): update EC Guidelines “ec_guidelines_index”
  src/website/src/pages/ec/guidelines/index.md
Labels: netlify-cms/pending_publish

#2137 feat(EC Usage pages for components): update EC Usage pages for components “ec_card”
  src/website/src/pages/ec/components/card/docs/usage.md
Labels: netlify-cms/pending_publish

#2138 feat(EU Usage pages for components): update EU Usage pages for components “eu_card”
  src/website/src/pages/eu/components/card/docs/usage.md
Labels: netlify-cms/pending_publish
