Repository ec-europa/europa-component-library, pull requests merged in 2021-02, with the labels that each got.

#1903 feat(text-field): review text field and add eu version
  docs/Migrating-v3.md
  src/implementations/twig/components/text-input/README.md
  src/implementations/twig/components/text-input/__snapshots__/text-input.test.js.snap
  src/implementations/twig/components/text-input/package.json
  src/implementations/twig/components/text-input/text-input.html.twig
  src/implementations/twig/components/text-input/text-input.story.js
  src/implementations/twig/components/text-input/text-input.test.js
  src/implementations/vanilla/components/form/_form.scss
  src/implementations/vanilla/components/form/form-ec.scss
  src/implementations/vanilla/components/form/form-eu.scss
  src/implementations/vanilla/components/text-input/_text-input.scss
  src/implementations/vanilla/components/text-input/text-input-ec.scss
  src/implementations/vanilla/components/text-input/text-input-eu.scss
  src/playground/addons/story-utils/index.js
  src/presets/dev/src/dev.scss
  src/presets/ec-core/src/ec-core.scss
  src/presets/eu-core/src/eu-core.scss
  src/specs/components/text-input/demo/data--ec.js
  src/specs/components/text-input/demo/data--eu.js
  src/themes/eu-core/_index.scss
  src/website/src/pages/ec/components/forms/text-field/demo/index.js
  src/website/src/pages/ec/components/forms/text-field/docs/code.mdx
Labels: tag: new feature

#1906 fix(preset): prevent overflow
  src/systems/ec/implementations/vanilla/packages/ec-preset-legacy-website/src/_globals.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-legacy-website/src/_globals.scss
Labels: tag: bug fix

#1907 feat(docs): Update Core family index
  src/website/src/pages/ec/core-template/index.mdx
Labels: tag: internal

#1910 feat(docs): Update Standardise site header usage page
  src/website/src/pages/ec/standardised-template/site-header/docs/usage.mdx
Labels: process: review needed, tag: internal

#1908 feat(docs): Update Core site header usage page
  src/website/src/pages/ec/core-template/site-header/docs/usage.mdx
Labels: tag: documentation

#1909 feat(docs): Update standardised family index
  src/website/src/pages/ec/standardised-template/index.mdx
Labels: tag: documentation

#1913 feat(docs): Update harmonised group 1 index
  src/website/src/pages/ec/harmonised-templates/docs/group1.mdx
Labels: process: review needed, tag: documentation

#1917 feat(docs): Update harmonised group 2 index
  src/website/src/pages/ec/harmonised-templates/docs/group2.mdx
Labels: process: review needed, tag: documentation

#1914 feat(docs): Update harmonised group 1 site header usage page
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group1.mdx
Labels: tag: documentation

#1912 feat(docs): Update Standardised footer usage page
  src/website/src/pages/ec/standardised-template/footer/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1911 feat(docs): Update Standardised page header usage page
  src/website/src/pages/ec/standardised-template/page-header/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1915 feat(docs): Update harmonised group 1 page header usage page
  src/website/src/pages/ec/harmonised-templates/page-header/docs/group1.mdx
Labels: tag: documentation

#1916 feat(docs): Update harmonised group 1 footer usage page
  src/website/src/pages/ec/harmonised-templates/footer/docs/group1.mdx
Labels: tag: documentation

#1918 feat(docs): Update harmonised group 2 site header usage page
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group2.mdx
Labels: tag: documentation

#1919 feat(docs): Update harmonised group 2 page header usage page
  src/website/src/pages/ec/harmonised-templates/page-header/docs/group2.mdx
Labels: tag: documentation

#1920 feat(docs): Update harmonised group 3 index
  src/website/src/pages/ec/harmonised-templates/docs/group3.mdx
Labels: tag: documentation

#1928 feat(docs): Update Core page header usage page
  src/website/src/pages/ec/core-template/page-header/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1926 fix(page-headers): Update sass to have a padding-top if not breadcrumb - FRONT-1996
  src/implementations/vanilla/components/page-header-core/page-header-core.scss
  src/implementations/vanilla/components/page-header-harmonised/page-header-harmonised.scss
  src/implementations/vanilla/components/page-header-standardised/page-header-standardised.scss
Labels: tag: bug fix

#1901 feat(footer-standardised): Refactor markup - FRONT-494
  docs/Migrating-v3.md
  src/implementations/twig/components/footer-standardised/README.md
  src/implementations/twig/components/footer-standardised/__snapshots__/footer-standardised.test.js.snap
  src/implementations/twig/components/footer-standardised/footer-standardised.html.twig
  src/implementations/twig/components/footer-standardised/footer-standardised.story.js
  src/implementations/vanilla/components/footer-standardised/footer-standardised-ec.scss
  src/implementations/vanilla/components/footer-standardised/footer-standardised-eu.scss
  src/specs/components/footer-standardised/demo/data--ec.js
  src/specs/components/footer-standardised/demo/data--eu.js
Labels: tag: enhancement

#1929 fix(attributes): Escaping name and values, rendering with |raw - FRONT-2037
  src/implementations/twig/components/accordion/accordion.html.twig
  src/implementations/twig/components/blockquote/blockquote.html.twig
  src/implementations/twig/components/breadcrumb-core/breadcrumb-core.html.twig
  src/implementations/twig/components/breadcrumb-harmonised/breadcrumb-harmonised.html.twig
  src/implementations/twig/components/breadcrumb-standardised/breadcrumb-standardised.html.twig
  src/implementations/twig/components/button/button.html.twig
  src/implementations/twig/components/card/card.html.twig
  src/implementations/twig/components/checkbox/checkbox-group.html.twig
  src/implementations/twig/components/checkbox/checkbox-item.html.twig
  src/implementations/twig/components/date-block/date-block.html.twig
  src/implementations/twig/components/datepicker/datepicker.html.twig
  src/implementations/twig/components/description-list/description-list.html.twig
  src/implementations/twig/components/expandable/expandable.html.twig
  src/implementations/twig/components/fact-figures/fact-figures.html.twig
  src/implementations/twig/components/file-upload/file-upload.html.twig
  src/implementations/twig/components/file/file.html.twig
  src/implementations/twig/components/footer-core/footer-core.html.twig
  src/implementations/twig/components/footer-harmonised/footer-harmonised.html.twig
  src/implementations/twig/components/footer-standardised/footer-standardised.html.twig
  src/implementations/twig/components/gallery/gallery-item.html.twig
  src/implementations/twig/components/gallery/gallery-overlay.html.twig
  src/implementations/twig/components/gallery/gallery.html.twig
  src/implementations/twig/components/hero-banner/hero-banner.html.twig
  src/implementations/twig/components/icon/icon.html.twig
  src/implementations/twig/components/inpage-navigation/inpage-navigation.html.twig
  src/implementations/twig/components/label/label.html.twig
  src/implementations/twig/components/language-list/language-list.html.twig
  src/implementations/twig/components/link/link.html.twig
  src/implementations/twig/components/media-container/media-container.html.twig
  src/implementations/twig/components/menu/menu.html.twig
  src/implementations/twig/components/message/message.html.twig
  src/implementations/twig/components/ordered-list/ordered-list.html.twig
  src/implementations/twig/components/page-banner/page-banner.html.twig
  src/implementations/twig/components/page-header-core/page-header-core.html.twig
  src/implementations/twig/components/page-header-harmonised/page-header-harmonised.html.twig
  src/implementations/twig/components/page-header-standardised/page-header-standardised.html.twig
  src/implementations/twig/components/pagination/pagination.html.twig
  src/implementations/twig/components/radio/radio-button.html.twig
  src/implementations/twig/components/radio/radio-group.html.twig
  src/implementations/twig/components/search-form/search-form.html.twig
  src/implementations/twig/components/select/select.html.twig
  src/implementations/twig/components/site-header-core/site-header-core.html.twig
  src/implementations/twig/components/site-header-harmonised/site-header-harmonised.html.twig
  src/implementations/twig/components/site-header-standardised/site-header-standardised.html.twig
  src/implementations/twig/components/skip-link/skip-link.html.twig
  src/implementations/twig/components/social-media-follow/social-media-follow.html.twig
  src/implementations/twig/components/social-media-share/social-media-share.html.twig
  src/implementations/twig/components/table/table.html.twig
  src/implementations/twig/components/tag/tag.html.twig
  src/implementations/twig/components/text-area/text-area.html.twig
  src/implementations/twig/components/text-input/text-input.html.twig
  src/implementations/twig/components/timeline/timeline.html.twig
  src/implementations/twig/components/unordered-list/unordered-list.html.twig
Labels: process: under review, tag: bug fix

#1930 feat(taxonomies): Adding taxonomy variant in description list, including list in card and file - FRONT-2039
  src/implementations/twig/components/card/README.md
  src/implementations/twig/components/card/__snapshots__/card.test.js.snap
  src/implementations/twig/components/card/card.html.twig
  src/implementations/twig/components/card/card.story.js
  src/implementations/twig/components/card/card.test.js
  src/implementations/twig/components/description-list/README.md
  src/implementations/twig/components/description-list/__snapshots__/descrption-list.test.js.snap
  src/implementations/twig/components/description-list/description-list.html.twig
  src/implementations/twig/components/description-list/description-list.story.js
  src/implementations/twig/components/description-list/descrption-list.test.js
  src/implementations/twig/components/file/README.md
  src/implementations/twig/components/file/__snapshots__/file.test.js.snap
  src/implementations/twig/components/file/file.html.twig
  src/implementations/twig/components/file/file.story.js
  src/implementations/twig/components/file/file.test.js
  src/implementations/vanilla/components/card/card-print.scss
  src/implementations/vanilla/components/card/card.scss
  src/implementations/vanilla/components/description-list/description-list-print.scss
  src/implementations/vanilla/components/description-list/description-list.scss
  src/implementations/vanilla/components/file/file-print.scss
  src/implementations/vanilla/components/file/file.scss
  src/presets/dev/src/dev.scss
  src/specs/components/card/demo/data--card-taxonomy.js
  src/specs/components/card/demo/data--tile-taxonomy.js
  src/specs/components/description-list/demo/data--taxonomy.js
  src/specs/components/file/demo/data--taxonomy.js
  src/website/src/pages/ec/components/card/demo/index.js
  src/website/src/pages/ec/components/card/docs/code.mdx
  src/website/src/pages/ec/components/file/demo/index.js
  src/website/src/pages/ec/components/file/docs/code.mdx
  src/website/src/pages/ec/components/list/demo/index.js
  src/website/src/pages/ec/components/list/docs/code.mdx
Labels: process: under review, tag: new feature
