Repository ec-europa/europa-component-library, pull requests merged in 2021-12, with the labels that each got.

#2270 chore(website): Renaming standardised in harmonised for EU
  .github/workflows/ci.yml
  .stylelintrc.js
  src/implementations/twig/components/footer-harmonised/README-EU.md
  src/implementations/twig/components/footer-harmonised/eu-footer-harmonised.story.js
  src/implementations/twig/components/footer-standardised/ec-footer-standardised.story.js
  src/implementations/twig/components/page-header-harmonised/README-EU.md
  src/implementations/twig/components/page-header-harmonised/ec-page-header-harmonised.story.js
  src/implementations/twig/components/page-header-harmonised/eu-page-header-harmonised.story.js
  src/implementations/twig/components/page-header-standardised/ec-page-header-standardised.story.js
  src/implementations/twig/components/site-header-harmonised/README-EU.md
  src/implementations/twig/components/site-header-harmonised/eu-site-header-harmonised.story.js
  src/implementations/twig/components/site-header-standardised/ec-site-header-standardised.story.js
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised-ec.scss
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised-eu.scss
  src/website/public/admin/config.yml
  src/website/src/pages/eu/harmonised-template/footer/demo/index.js
  src/website/src/pages/eu/harmonised-template/footer/docs/code.mdx
  src/website/src/pages/eu/harmonised-template/footer/docs/usage.md
  src/website/src/pages/eu/harmonised-template/footer/index.md
  src/website/src/pages/eu/harmonised-template/index.md
  src/website/src/pages/eu/harmonised-template/page-header/demo/index.js
  src/website/src/pages/eu/harmonised-template/page-header/docs/code.mdx
  src/website/src/pages/eu/harmonised-template/page-header/docs/usage.md
  src/website/src/pages/eu/harmonised-template/page-header/index.md
  src/website/src/pages/eu/harmonised-template/site-header/demo/index.js
  src/website/src/pages/eu/harmonised-template/site-header/docs/api.mdx
  src/website/src/pages/eu/harmonised-template/site-header/docs/code.mdx
  src/website/src/pages/eu/harmonised-template/site-header/docs/usage.md
  src/website/src/pages/eu/harmonised-template/site-header/index.md
  src/website/src/pages/eu/standardised-template/site-header/docs/api.mdx
  yarn.lock
Labels: tag: internal

#2263 feat(tag): update EU style - FRONT-3422
  src/implementations/vanilla/components/tag/_tag.scss
  src/implementations/vanilla/components/tag/tag-ec.scss
  src/implementations/vanilla/components/tag/tag-eu.scss
Labels: tag: enhancement

#2255 feat(spinner): Adding component - FRONT-3223
  CHANGELOG.md
  README.md
  src/implementations/twig/components/spinner/.npmignore
  src/implementations/twig/components/spinner/README.md
  src/implementations/twig/components/spinner/__snapshots__/spinner.test.js.snap
  src/implementations/twig/components/spinner/package.json
  src/implementations/twig/components/spinner/spinner.html.twig
  src/implementations/twig/components/spinner/spinner.story.js
  src/implementations/twig/components/spinner/spinner.test.js
  src/implementations/vanilla/components/spinner/README.md
  src/implementations/vanilla/components/spinner/_spinner.scss
  src/implementations/vanilla/components/spinner/package.json
  src/implementations/vanilla/components/spinner/spinner-ec.scss
  src/implementations/vanilla/components/spinner/spinner-eu.scss
  src/presets/dev/package.json
  src/presets/dev/src/dev.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/specs/components/spinner/demo/data.js
  src/specs/components/spinner/package.json
  src/website/public/admin/config.yml
  src/website/src/pages/ec/components/index.mdx
  src/website/src/pages/ec/components/spinner/demo/index.js
  src/website/src/pages/ec/components/spinner/docs/code.mdx
  src/website/src/pages/ec/components/spinner/docs/usage.md
  src/website/src/pages/ec/components/spinner/ec_comp_loading_indicator.svg
  src/website/src/pages/ec/components/spinner/index.md
  src/website/src/pages/eu/components/index.mdx
  src/website/src/pages/eu/components/spinner/demo/index.js
  src/website/src/pages/eu/components/spinner/docs/code.mdx
  src/website/src/pages/eu/components/spinner/docs/usage.md
  src/website/src/pages/eu/components/spinner/eu_comp_loading_indicator.svg
  src/website/src/pages/eu/components/spinner/index.md
Labels: tag: new feature

#2266 feat(EU Usage pages for components): update EU Usage pages for components “eu_spinner”
  src/website/src/pages/eu/components/spinner/docs/usage.md
Labels: netlify-cms/pending_publish

#2271 fix(news-ticker): Fix showcase iframe resize issue - FRONT-3425
  src/website/src/pages/ec/components/news-ticker/docs/code.mdx
  src/website/src/website-components/Playground.jsx
  src/website/src/website-components/Showcase/Iframe.jsx
Labels: tag: bug fix, tag: new feature

#2265 feat(EC Usage pages for components): update EC Usage pages for components “ec_spinner”
  README.md
  src/website/src/pages/ec/components/spinner/docs/usage.md
Labels: netlify-cms/pending_publish

#2253 feat(menu): allows more menu items - FRONT-3354
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/menu-item.html.twig
  src/implementations/twig/components/site-header-core/__snapshots__/site-header-core.test.js.snap
  src/implementations/twig/components/site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/implementations/twig/components/site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/implementations/vanilla/components/menu/_menu.scss
  src/implementations/vanilla/components/menu/menu-ec.scss
  src/implementations/vanilla/components/menu/menu-eu.scss
  src/implementations/vanilla/components/menu/menu.js
  src/implementations/vanilla/components/text-area/_text-area.scss
  src/specs/components/menu/demo/data--en.js
  src/specs/components/menu/demo/data--fr.js
Labels: tag: enhancement

#2275 fix(banners): add wrapper around link - FRONT-3403
  src/implementations/twig/components/hero-banner/__snapshots__/hero-banner.test.js.snap
  src/implementations/twig/components/hero-banner/hero-banner.html.twig
  src/implementations/twig/components/page-banner/__snapshots__/page-banner.test.js.snap
  src/implementations/twig/components/page-banner/page-banner.html.twig
Labels: tag: enhancement

#2276 fix(gallery): fix visited link color - FRONT-3420
  src/implementations/vanilla/components/gallery/_gallery.scss
Labels: tag: bug fix, process: under review

#2278 fix(button): cleanup markup and css - FRONT-3464
  src/implementations/twig/components/button/button.html.twig
  src/implementations/twig/components/news-ticker/__snapshots__/news-ticker.test.js.snap
  src/implementations/vanilla/components/button/_button.scss
  src/implementations/vanilla/components/news-ticker/_news-ticker.scss
Labels: tag: enhancement, process: under review

#2260 feat(carousel): Add component - FRONT-2513
  src/implementations/twig/components/carousel/.npmignore
  src/implementations/twig/components/carousel/README.md
  src/implementations/twig/components/carousel/__snapshots__/carousel.test.js.snap
  src/implementations/twig/components/carousel/carousel.html.twig
  src/implementations/twig/components/carousel/carousel.story.js
  src/implementations/twig/components/carousel/carousel.test.js
  src/implementations/twig/components/carousel/package.json
  src/implementations/vanilla/components/carousel/README.md
  src/implementations/vanilla/components/carousel/_carousel.scss
  src/implementations/vanilla/components/carousel/carousel-ec.scss
  src/implementations/vanilla/components/carousel/carousel-eu.scss
  src/implementations/vanilla/components/carousel/carousel-print.scss
  src/implementations/vanilla/components/carousel/carousel.js
  src/implementations/vanilla/components/carousel/package.json
  src/presets/dev/package.json
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/specs/components/carousel/demo/data.js
  src/specs/components/carousel/package.json
  src/website/public/admin/config.yml
  src/website/src/pages/ec/components/carousel/demo/index.js
  src/website/src/pages/ec/components/carousel/docs/api.mdx
  src/website/src/pages/ec/components/carousel/docs/code.mdx
  src/website/src/pages/ec/components/carousel/docs/usage.md
  src/website/src/pages/ec/components/carousel/ec_comp_carousel.svg
  src/website/src/pages/ec/components/carousel/index.md
  src/website/src/pages/ec/components/index.mdx
  src/website/src/pages/eu/components/carousel/demo/index.js
  src/website/src/pages/eu/components/carousel/docs/api.mdx
  src/website/src/pages/eu/components/carousel/docs/code.mdx
  src/website/src/pages/eu/components/carousel/docs/usage.md
  src/website/src/pages/eu/components/carousel/eu_comp_carousel.svg
  src/website/src/pages/eu/components/carousel/index.md
  src/website/src/pages/eu/components/index.mdx
Labels: tag: new feature

#2277 feat(EC page-header): apply new style - FRONT-3423
  src/implementations/twig/components/page-header-standardised/ec-page-header-standardised.story.js
  src/implementations/vanilla/components/breadcrumb-harmonised/_breadcrumb-harmonised.scss
  src/implementations/vanilla/components/breadcrumb-harmonised/breadcrumb-harmonised-ec.scss
  src/implementations/vanilla/components/breadcrumb-harmonised/breadcrumb-harmonised-eu.scss
  src/implementations/vanilla/components/breadcrumb-standardised/_breadcrumb-standardised.scss
  src/implementations/vanilla/components/breadcrumb-standardised/breadcrumb-standardised-ec.scss
  src/implementations/vanilla/components/breadcrumb-standardised/breadcrumb-standardised-eu.scss
  src/implementations/vanilla/components/page-header-standardised/page-header-standardised-ec.scss
  src/implementations/vanilla/components/page-header-standardised/page-header-standardised-eu.scss
Labels: tag: enhancement

#2280 chore(storybook): Update to 6.4.8
  src/implementations/twig/components/icon/icon.story.js
  src/playground/addons/story-utils/index.js
  src/playground/ec/package.json
  src/playground/eu/package.json
  yarn.lock
Labels: tag: internal

#2279 feat(news-ticker): Add mobile version - FRONT-3502
  src/implementations/twig/components/news-ticker/__snapshots__/news-ticker.test.js.snap
  src/implementations/twig/components/news-ticker/news-ticker.html.twig
  src/implementations/vanilla/components/news-ticker/_news-ticker.scss
  src/implementations/vanilla/components/news-ticker/news-ticker.js
Labels: tag: enhancement

#2250 feat(content-item): add component - FRONT-2499
  README.md
  src/implementations/twig/components/card/__snapshots__/card.test.js.snap
  src/implementations/twig/components/content-item/.npmignore
  src/implementations/twig/components/content-item/README.md
  src/implementations/twig/components/content-item/__snapshots__/content-item.test.js.snap
  src/implementations/twig/components/content-item/content-item.html.twig
  src/implementations/twig/components/content-item/content-item.story.js
  src/implementations/twig/components/content-item/content-item.test.js
  src/implementations/twig/components/content-item/package.json
  src/implementations/vanilla/components/card/_card.scss
  src/implementations/vanilla/components/card/card-ec.scss
  src/implementations/vanilla/components/card/card-eu.scss
  src/implementations/vanilla/components/card/card-print.scss
  src/implementations/vanilla/components/content-item/README.md
  src/implementations/vanilla/components/content-item/_content-item.scss
  src/implementations/vanilla/components/content-item/content-item-ec.scss
  src/implementations/vanilla/components/content-item/content-item-eu.scss
  src/implementations/vanilla/components/content-item/content-item-print.scss
  src/implementations/vanilla/components/content-item/package.json
  src/implementations/vanilla/components/date-block/date-block-print.scss
  src/presets/dev/package.json
  src/presets/dev/src/dev.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/specs/components/card/demo/data--card-tag.js
  src/specs/components/card/demo/data--card-taxonomy.js
  src/specs/components/card/demo/data--card.js
  src/specs/components/content-item/demo/data--event.js
  src/specs/components/content-item/demo/data--image.js
  src/specs/components/content-item/package.json
  src/website/public/admin/config.yml
  src/website/src/pages/ec/components/content-item/demo/index.js
  src/website/src/pages/ec/components/content-item/docs/code.mdx
  src/website/src/pages/ec/components/content-item/docs/usage.md
  src/website/src/pages/ec/components/content-item/ec_comp_content_items.svg
  src/website/src/pages/ec/components/content-item/index.md
  src/website/src/pages/ec/components/index.mdx
  src/website/src/pages/eu/components/content-item/demo/index.js
  src/website/src/pages/eu/components/content-item/docs/code.mdx
  src/website/src/pages/eu/components/content-item/docs/usage.md
  src/website/src/pages/eu/components/content-item/eu_comp_content_items.svg
  src/website/src/pages/eu/components/content-item/index.md
  src/website/src/pages/eu/components/index.mdx
  yarn.lock
Labels: tag: new feature

#2281 fix(site-header): Mobile display of site-header harmonised without site_name - FRONT-3497
  src/implementations/twig/components/site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/implementations/twig/components/site-header-harmonised/site-header-harmonised.html.twig
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised-ec.scss
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised-eu.scss
Labels: tag: bug fix

#2284 fix(site header harmonised): Using ecl-buttons as in the other families - FRONT-3503
  src/implementations/twig/components/site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/implementations/twig/components/site-header-harmonised/site-header-harmonised.html.twig
  src/implementations/vanilla/components/site-header-harmonised/site-header-harmonised-ec.scss
Labels: tag: enhancement, process: under review

#2290 feat(stories): Refactoring form element stories - front-3512
  src/implementations/twig/components/checkbox/__snapshots__/checkbox.test.js.snap
  src/implementations/twig/components/checkbox/checkbox.story.js
  src/implementations/twig/components/file-upload/file-upload.story.js
  src/implementations/twig/components/radio/__snapshots__/radio.test.js.snap
  src/implementations/twig/components/radio/radio.story.js
  src/implementations/twig/components/search-form/search-form.story.js
  src/implementations/twig/components/select/select.story.js
  src/implementations/twig/components/text-area/text-area.story.js
  src/implementations/twig/components/text-input/text-input.story.js
  src/implementations/vanilla/components/form/_form.scss
  src/playground/addons/story-utils/index.js
  src/specs/components/checkbox/demo/data--ec.js
  src/specs/components/checkbox/demo/data--eu.js
  src/specs/components/radio/demo/data--default.js
  src/website/src/pages/ec/components/forms/checkbox/docs/code.mdx
  src/website/src/pages/ec/components/forms/file-upload/docs/code.mdx
  src/website/src/pages/ec/components/forms/radio/docs/code.mdx
  src/website/src/pages/ec/components/forms/text-area/docs/code.mdx
  src/website/src/pages/ec/components/forms/text-field/docs/code.mdx
  src/website/src/pages/eu/components/forms/checkbox/docs/code.mdx
  src/website/src/pages/eu/components/forms/file-upload/docs/code.mdx
  src/website/src/pages/eu/components/forms/radio/docs/code.mdx
  src/website/src/pages/eu/components/forms/text-area/docs/code.mdx
  src/website/src/pages/eu/components/forms/text-field/docs/code.mdx
Labels: tag: enhancement

#2291 chore(deps): Updates - 20-12-21
  package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2285 feat(icons): Add external-events icon - FRONT-3511
  src/implementations/twig/components/icon/__snapshots__/icon.test.js.snap
  src/implementations/vanilla/components/icon/_icon.scss
  src/implementations/vanilla/components/icon/icon-ec.scss
  src/implementations/vanilla/components/icon/icon-eu.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/resources/icons-ec/src/all/external-events.svg
  src/resources/icons-eu/src/all/external-events.svg
Labels: tag: new feature, process: review needed

#2288 fix(news-ticker): Fix EU showcase iframe resize issue - FRONT-3425
  src/website/src/pages/eu/components/news-ticker/docs/code.mdx
Labels: tag: bug fix

#2292 fix(site-header): Correctly rename the cta class in the standardised variant - FRONT-3519
  .size-limit.json
  src/implementations/twig/components/site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/implementations/twig/components/site-header-standardised/site-header-standardised.html.twig
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised-ec.scss
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised-eu.scss
Labels: tag: bug fix

#2293 feat(stories): refactoring, batch 2 - FRONT-3513
  src/implementations/twig/components/card/card.html.twig
  src/implementations/twig/components/card/card.story.js
  src/implementations/twig/components/hero-banner/hero-banner.story.js
  src/implementations/twig/components/list-illustration/list-illustration-item.html.twig
  src/implementations/twig/components/list-illustration/list-illustration.story.js
  src/implementations/twig/components/media-container/media-container.story.js
  src/implementations/twig/components/page-banner/page-banner.story.js
  src/implementations/vanilla/components/card/_card.scss
  src/website/src/pages/ec/components/card/docs/code.mdx
  src/website/src/pages/eu/components/card/docs/code.mdx
Labels: tag: enhancement, process: under review
