Repository ec-europa/europa-component-library, pull requests merged in 2021-05, with the labels that each got.

#2037 feat(timeline): Adding EU styles, revamping EC - FRONT-2151
  docs/Migrating-v3.md
  src/implementations/twig/components/timeline/__snapshots__/timeline.test.js.snap
  src/implementations/twig/components/timeline/timeline.html.twig
  src/implementations/twig/components/timeline/timeline.story.js
  src/implementations/twig/components/timeline/timeline.test.js
  src/implementations/vanilla/components/timeline/_timeline-print-ec.scss
  src/implementations/vanilla/components/timeline/_timeline-print-eu.scss
  src/implementations/vanilla/components/timeline/_timeline-print.scss
  src/implementations/vanilla/components/timeline/_timeline.scss
  src/implementations/vanilla/components/timeline/timeline-ec.scss
  src/implementations/vanilla/components/timeline/timeline-eu.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/specs/components/timeline/demo/data--ec.js
  src/specs/components/timeline/demo/data--eu.js
  src/website/src/pages/ec/components/timeline/demo/index.js
Labels: tag: new feature

#2052 fix(print): fix print css - FRONT-2210
  src/implementations/vanilla/components/button/_button-print.scss
  src/implementations/vanilla/components/card/card-print.scss
  src/implementations/vanilla/components/file/file-print.scss
  src/implementations/vanilla/components/hero-banner/hero-banner-print.scss
  src/implementations/vanilla/components/label/_label-print.scss
  src/implementations/vanilla/components/link/_link-print.scss
  src/implementations/vanilla/components/site-header-harmonised/site-header-harmonised-print.scss
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised-print.scss
  src/implementations/vanilla/utilities/typography/typography-print.scss
Labels: tag: bug fix

#2039 feat(media-container): Adding EU styles, revamping EC - FRONT-2177
  src/implementations/vanilla/components/media-container/_media-container.scss
  src/implementations/vanilla/components/media-container/media-container-ec.scss
  src/implementations/vanilla/components/media-container/media-container-eu.scss
  src/implementations/vanilla/components/media-container/media-container-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
Labels: process: business approval needed, tag: new feature

#2051 feat(media-container): add full screen feature - FRONT-2216
  src/systems/ec/implementations/react/components/media-container/src/MediaContainer.jsx
  src/systems/ec/implementations/react/components/media-container/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-media-container/ec-component-media-container.scss
  src/systems/eu/implementations/react/components/media-container/src/MediaContainer.jsx
  src/systems/eu/implementations/react/components/media-container/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-media-container/eu-component-media-container.scss
  src/website/src/pages/ec/components/banners/hero-banner/docs/code.mdx
  src/website/src/pages/ec/components/media/media-container/docs/code.mdx
Labels: tag: new feature

#2056 feat(Usage pages for components): update Usage pages for components “ec_page_header_standardised”
  src/website/src/pages/ec/standardised-template/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2057 feat(Usage pages for components): update Usage pages for components “ec_page_header_standardised”
  src/website/src/pages/ec/standardised-template/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2061 fix(website): fix icon - FRONT-2227
  src/website/src/components/Navigation/LinkSection.jsx
Labels: tag: bug fix

#2062 chore(deps): Some updates, fixing audit issues
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2066 fix(gallery): update gallery z-index (ECL2) - FRONT-2230
  src/systems/ec/design-tokens/tokens/z-index.yml
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/ec-component-gallery.scss
  src/systems/ec/themes/default/aliases/z-index.yml
  src/systems/eu/design-tokens/tokens/z-index.yml
  src/systems/eu/implementations/vanilla/packages/eu-component-gallery/eu-component-gallery.scss
  src/systems/eu/themes/default/aliases/z-index.yml
Labels: tag: bug fix

#2067 fix(gallery): update gallery z-index (ECL3) - FRONT-2230
  src/implementations/vanilla/components/gallery/gallery.scss
  src/themes/dev/maps/z-index.scss
Labels: tag: bug fix

#2064 fix(menu): Review menu spacings - FRONT-2156
  src/implementations/vanilla/components/menu/_menu.scss
  src/implementations/vanilla/components/menu/menu-ec.scss
Labels: tag: bug fix

#2069 chore(docs): Adding Js bundle section in migration docs
  docs/Migrating-v3.md
Labels: tag: documentation

#2074 feat(Europa family for EC): update Europa family for EC “ec_core_template”
  src/website/src/pages/ec/core-template/index.md
Labels: netlify-cms/pending_publish

#2075 feat(Europa family for EU): update Europa family for EU “eu_core_template”
  src/website/src/pages/eu/core-template/index.md
Labels: netlify-cms/pending_publish

#2079 feat(table): Adding EU styles, revamping EC - FRONT-2247
  src/implementations/vanilla/components/table/_table.scss
  src/implementations/vanilla/components/table/table-ec.scss
  src/implementations/vanilla/components/table/table-eu.scss
  src/implementations/vanilla/components/table/table.js
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
Labels: tag: new feature

#2072 feat(html tags): add default styling - FRONT-2213
  .stylelintrc.js
  docs/Migrating-v3.md
  docs/decisions/006-html-tag-style.md
  src/implementations/twig/utilities/html-tag/index.story.js
  src/implementations/vanilla/components/blockquote/_blockquote.scss
  src/implementations/vanilla/components/button/_button.scss
  src/implementations/vanilla/components/description-list/description-list.scss
  src/implementations/vanilla/components/link/_link.scss
  src/implementations/vanilla/components/ordered-list/ordered-list.scss
  src/implementations/vanilla/components/table/_table.scss
  src/implementations/vanilla/components/unordered-list/unordered-list.scss
  src/implementations/vanilla/utilities/typography/typography.scss
  src/playground/ec/.storybook/preview.js
  src/playground/eu/.storybook/preview.js
  src/presets/ec/ecl-builder.config.js
  src/presets/ec/src/ec-default.scss
  src/presets/eu/ecl-builder.config.js
  src/presets/eu/src/eu-default.scss
  src/presets/reset/ecl-builder.config.js
  src/themes/ec/_index.scss
  src/themes/eu/_index.scss
  src/website/public/admin/config.yml
  src/website/src/pages/ec/utilities/html-tag/docs/usage.md
  src/website/src/pages/ec/utilities/html-tag/index.md
  src/website/src/pages/eu/utilities/html-tag/docs/usage.md
  src/website/src/pages/eu/utilities/html-tag/index.md
Labels: tag: new feature

#2073 fix(toolchain): npm publish and sources for map files - FRONT-2238
  src/presets/ec/package.json
  src/presets/eu/package.json
  src/presets/reset/package.json
  src/tools/builder/scripts/styles.js
Labels: process: under review, tag: internal

#2055 feat(media-container): add full width - FRONT-2224
  src/implementations/twig/components/media-container/README.md
  src/implementations/twig/components/media-container/media-container.html.twig
  src/implementations/twig/components/media-container/media-container.story.js
  src/implementations/vanilla/components/media-container/_media-container.scss
  src/website/src/pages/ec/components/banners/hero-banner/docs/code.mdx
  src/website/src/pages/ec/components/banners/page-banner/docs/code.mdx
  src/website/src/pages/ec/components/media/media-container/docs/code.mdx
  src/website/src/pages/eu/components/media/media-container/docs/code.mdx
Labels: tag: new feature

#2076 feat(card): Adding EU styles, revamping EC - FRONT-2202
  docs/Migrating-v3.md
  src/implementations/twig/components/card/__snapshots__/card.test.js.snap
  src/implementations/twig/components/card/card.html.twig
  src/implementations/twig/components/card/card.story.js
  src/implementations/vanilla/components/card/_card.scss
  src/implementations/vanilla/components/card/card-ec.scss
  src/implementations/vanilla/components/card/card-eu.scss
  src/implementations/vanilla/components/card/card.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
Labels: tag: new feature

#2065 feat(file): Adding EU styles, revamping EC - FRONT-2178
  docs/Migrating-v3.md
  src/implementations/twig/components/file/__snapshots__/file.test.js.snap
  src/implementations/twig/components/file/file.html.twig
  src/implementations/twig/components/file/file.story.js
  src/implementations/vanilla/components/file/_file.scss
  src/implementations/vanilla/components/file/file-ec.scss
  src/implementations/vanilla/components/file/file-eu.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/specs/components/file/demo/data--taxonomy.js
  src/specs/components/file/demo/data--thumbnail.js
  src/specs/components/file/demo/data--with-translation.js
  src/specs/components/file/demo/data--without-translation.js
  yarn.lock
Labels: tag: new feature

#2082 feat(gallery): Adding EU styles, revamping EC - front-2255
  docs/Migrating-v3.md
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/twig/components/gallery/gallery-item.html.twig
  src/implementations/twig/components/gallery/gallery-overlay.html.twig
  src/implementations/twig/components/gallery/gallery.html.twig
  src/implementations/vanilla/components/gallery/_gallery.scss
  src/implementations/vanilla/components/gallery/gallery-ec.scss
  src/implementations/vanilla/components/gallery/gallery-eu.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/specs/components/gallery/demo/data.js
Labels: tag: new feature

#2077 feat(banners): update EC banners and add EU
  docs/Migrating-v3.md
  src/implementations/twig/components/hero-banner/README.md
  src/implementations/twig/components/hero-banner/__snapshots__/hero-banner.test.js.snap
  src/implementations/twig/components/hero-banner/hero-banner.html.twig
  src/implementations/twig/components/hero-banner/hero-banner.story.js
  src/implementations/twig/components/hero-banner/hero-banner.test.js
  src/implementations/twig/components/hero-banner/package.json
  src/implementations/twig/components/page-banner/README.md
  src/implementations/twig/components/page-banner/__snapshots__/page-banner.test.js.snap
  src/implementations/twig/components/page-banner/page-banner.html.twig
  src/implementations/twig/components/page-banner/page-banner.story.js
  src/implementations/twig/components/page-banner/page-banner.test.js
  src/implementations/vanilla/components/hero-banner/_hero-banner.scss
  src/implementations/vanilla/components/hero-banner/hero-banner-ec.scss
  src/implementations/vanilla/components/hero-banner/hero-banner-eu.scss
  src/implementations/vanilla/components/hero-banner/hero-banner.scss
  src/implementations/vanilla/components/page-banner/_page-banner.scss
  src/implementations/vanilla/components/page-banner/page-banner-ec.scss
  src/implementations/vanilla/components/page-banner/page-banner-eu.scss
  src/implementations/vanilla/components/page-banner/page-banner.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/specs/components/hero-banner/demo/data--image-box.js
  src/specs/components/hero-banner/demo/data--image-gradient.js
  src/specs/components/hero-banner/demo/data--image-shade.js
  src/specs/components/hero-banner/demo/data--simple-primary.js
  src/specs/components/hero-banner/demo/data--simple-secondary.js
  src/specs/components/hero-banner/demo/data--simple-white.js
  src/specs/components/page-banner/demo/data--image-box.js
  src/specs/components/page-banner/demo/data--image-gradient.js
  src/specs/components/page-banner/demo/data--image-shade.js
  src/specs/components/page-banner/demo/data--simple-primary.js
  src/specs/components/page-banner/demo/data--simple-secondary.js
  src/specs/components/page-banner/demo/data--simple-white.js
  src/website/src/pages/ec/components/banners/hero-banner/docs/code.mdx
  src/website/src/pages/ec/components/banners/page-banner/docs/code.mdx
  src/website/src/pages/eu/components/banners/hero-banner/docs/code.mdx
  src/website/src/pages/eu/components/banners/page-banner/docs/code.mdx
Labels: tag: new feature
