Repository ec-europa/europa-component-library, pull requests merged in 2021-03, with the labels that each got.

#1934 fix(gallery): fix gallery optional elements - FRONT-2060
  src/systems/ec/implementations/react/components/gallery/src/GalleryOverlay.jsx
  src/systems/ec/implementations/vanilla/packages/ec-component-card/ec-component-card-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-gallery/ec-component-gallery.js
  src/systems/eu/implementations/react/components/gallery/src/GalleryOverlay.jsx
  src/systems/eu/implementations/vanilla/packages/eu-component-card/eu-component-card-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-gallery/eu-component-gallery.js
Labels: tag: bug fix

#1924 feat(search-form): review search form and add eu version - FRONT-1943
  src/implementations/twig/components/search-form/__snapshots__/search-form.test.js.snap
  src/implementations/twig/components/search-form/search-form.story.js
  src/implementations/vanilla/components/search-form/_search-form.scss
  src/implementations/vanilla/components/search-form/search-form-ec.scss
  src/implementations/vanilla/components/search-form/search-form-eu.scss
  src/presets/dev/src/dev-print.scss
  src/specs/components/search-form/demo/data.js
Labels: tag: new feature

#1936 chore: libraries update, fixing audit issue - front-2077
  package.json
  src/playground/addons/story-utils/package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/presets/ec-core/package.json
  src/presets/eu-core/package.json
  src/presets/reset/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: process: under review, tag: internal

#1931 feat(menu): Restyling EC, adding EU version - FRONT-1946
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/menu.story.js
  src/implementations/vanilla/components/menu/_menu.scss
  src/implementations/vanilla/components/menu/menu-ec.scss
  src/implementations/vanilla/components/menu/menu-eu.scss
  src/presets/dev/src/dev.scss
  src/presets/ec-core/src/ec-core.scss
  src/presets/eu-core/src/eu-core.scss
  src/specs/components/menu/demo/data--en.js
  src/specs/components/menu/demo/data--fr.js
  src/specs/components/menu/demo/data--group1.js
  src/specs/components/menu/demo/data--group2.js
Labels: process: review needed, tag: new feature

#1942 chore(deps): Safe updates before 2.37.0
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  package.json
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-form-datepicker/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-hero-banner/ec-component-hero-banner.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-menu/package.json
  src/systems/ec/implementations/vanilla/packages/ec-component-page-banner/ec-component-page-banner.scss
  src/systems/ec/implementations/vanilla/packages/ec-preset-editor/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-full/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-legacy-website/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-legacy/package.json
  src/systems/ec/implementations/vanilla/packages/ec-preset-website/package.json
  src/systems/eu/implementations/react/storybook/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-form-datepicker/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-hero-banner/eu-component-hero-banner.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-menu/package.json
  src/systems/eu/implementations/vanilla/packages/eu-component-page-banner/eu-component-page-banner.scss
  src/systems/eu/implementations/vanilla/packages/eu-preset-editor/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-full/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-legacy-website/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-legacy/package.json
  src/systems/eu/implementations/vanilla/packages/eu-preset-website/package.json
  src/tools/builder/package.json
  src/tools/storybook-addon-code/package.json
  src/website/package.json
  src/website/src/pages/ec/components/file/docs/api.mdx
  src/website/src/pages/ec/components/navigation/menu/docs/api.mdx
  yarn.lock
Labels: tag: internal

#1933 docs(usage-pages): Aligning docs in v3 - FRONT-2043
  src/website/src/pages/ec/core-template/index.mdx
  src/website/src/pages/ec/core-template/page-header/docs/usage.mdx
  src/website/src/pages/ec/core-template/site-header/docs/usage.mdx
  src/website/src/pages/ec/harmonised-templates/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/docs/group3.mdx
  src/website/src/pages/ec/harmonised-templates/footer/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/page-header/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/page-header/docs/group2.mdx
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group1.mdx
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group2.mdx
  src/website/src/pages/ec/standardised-template/footer/docs/usage.mdx
  src/website/src/pages/ec/standardised-template/index.mdx
  src/website/src/pages/ec/standardised-template/page-header/docs/usage.mdx
  src/website/src/pages/ec/standardised-template/site-header/docs/usage.mdx
Labels: process: under review, tag: documentation

#1941 feat(footer-core): Review markup and add controls - FRONT-1874
  src/implementations/twig/components/footer-core/README.md
  src/implementations/twig/components/footer-core/__snapshots__/footer-core.test.js.snap
  src/implementations/twig/components/footer-core/footer-core.html.twig
  src/implementations/twig/components/footer-core/footer-core.story.js
  src/implementations/vanilla/components/footer-core/footer-core-ec.scss
  src/implementations/vanilla/components/footer-core/footer-core-eu.scss
  src/specs/components/footer-core/demo/data--ec.js
  src/specs/components/footer-core/demo/data--eu.js
Labels: process: under review, tag: enhancement

#1946 fix(card): Preventing text overflow - FRONT-2092
  src/systems/ec/implementations/vanilla/packages/ec-component-card/ec-component-card-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-card/ec-component-card.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-card/eu-component-card-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-card/eu-component-card.scss
Labels: tag: enhancement

#1950 chore(deps): Safe upgrades, bumping elliptic from 6.5.3 to 6.5.4 - FRONT-2093
  src/implementations/vanilla/components/gallery/package.json
  src/implementations/vanilla/components/site-header-core/package.json
  src/implementations/vanilla/components/site-header-harmonised/package.json
  src/implementations/vanilla/components/site-header-standardised/package.json
  src/playground/addons/story-utils/package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: process: under review, tag: internal

#1938 feat(footer-harmonised): Review markup and add controls - FRONT-1845
  src/implementations/twig/components/footer-harmonised/README.md
  src/implementations/twig/components/footer-harmonised/__snapshots__/footer-harmonised.test.js.snap
  src/implementations/twig/components/footer-harmonised/ec-footer-harmonised.story.js
  src/implementations/twig/components/footer-harmonised/eu-footer-harmonised.story.js
  src/implementations/twig/components/footer-harmonised/footer-harmonised.html.twig
  src/implementations/twig/components/footer-harmonised/footer-harmonised.story.js
  src/implementations/twig/components/footer-standardised/footer-standardised.html.twig
  src/implementations/vanilla/components/footer-harmonised/footer-harmonised-ec.scss
  src/implementations/vanilla/components/footer-harmonised/footer-harmonised-eu.scss
  src/presets/dev/src/dev.scss
  src/presets/ec-core/src/ec-core.scss
  src/presets/eu-core/src/eu-core.scss
  src/specs/components/footer-harmonised/demo/data--eu.js
  src/specs/components/footer-harmonised/demo/data--group1.js
  src/specs/components/footer-harmonised/demo/data--group2.js
  src/specs/components/footer-harmonised/demo/data--group3.js
Labels: tag: enhancement

#1951 fix(card): Prevent text overflow - FRONT-2094
  src/implementations/vanilla/components/card/card-print.scss
  src/implementations/vanilla/components/card/card.scss
Labels: process: under review, tag: enhancement

#1952 fix(description-list): Preventing text overflow in terms - FRONT-2096
  src/systems/ec/implementations/vanilla/packages/ec-component-description-list/ec-component-description-list-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-component-description-list/ec-component-description-list.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-description-list/eu-component-description-list-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-description-list/eu-component-description-list.scss
Labels: process: under review, tag: enhancement

#1953 fix(description-list): Preventing text-overflow on terms (v3) - front-2096
  src/implementations/vanilla/components/description-list/description-list-print.scss
  src/implementations/vanilla/components/description-list/description-list.scss
Labels: process: under review, tag: enhancement

#1940 feat(docs): New-date-picker-usage-page
  src/website/src/pages/ec/components/forms/datepicker/docs/usage.mdx
Labels: tag: internal

#1954 feat(docs): file-downloads-usage-page
  src/website/src/pages/ec/components/file/docs/usage.mdx
Labels: process: review needed, tag: documentation

#1949 fix(media-container): fix background (ECL3) - FRONT-2023
  src/implementations/vanilla/components/media-container/media-container.scss
Labels: process: review needed, tag: bug fix

#1948 fix(media-container): fix background (ECL2) - FRONT-2023
  src/systems/ec/implementations/vanilla/packages/ec-component-media-container/ec-component-media-container.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-media-container/eu-component-media-container.scss
Labels: tag: bug fix

#1955 feat(form): Form group elements - FRONT-2099
  src/implementations/twig/components/text-area/__snapshots__/text-area.test.js.snap
  src/implementations/twig/components/text-input/__snapshots__/text-input.test.js.snap
  src/implementations/vanilla/components/form/_form.scss
  src/implementations/vanilla/components/form/form-ec.scss
  src/implementations/vanilla/components/form/form-eu.scss
  src/specs/components/text-area/demo/data--eu.js
  src/specs/components/text-input/demo/data--eu.js
Labels: process: under review, tag: enhancement

#1956 feat(docs): Links usage page update
  src/website/src/pages/ec/components/navigation/link/docs/usage.md
Labels: tag: documentation

#1957 fix(ecl-editor): fix button override
  src/systems/ec/implementations/vanilla/packages/ec-editor/_ec-editor--button.scss
Labels: tag: bug fix

#1959 fix(print): hiding last element of social media follow only if it doesn't contain an icon - FRONT-2098
  src/systems/ec/implementations/vanilla/packages/ec-component-social-media-follow/ec-component-social-media-follow-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-component-social-media-follow/eu-component-social-media-follow-print.scss
Labels: tag: bug fix

#1960 chore(deps): fixing audit issues with resolutions - FRONT-2095
  package.json
  yarn.lock
Labels: process: under review, tag: internal

#1961 fix(print): Hiding last element in social media follow only if there is no icon - FRONT-2098
  src/implementations/vanilla/components/social-media-follow/social-media-follow-print.scss
Labels: tag: bug fix

#1935 feat(checkbox): Review EC, adding EU version - front-2054
  src/implementations/twig/components/checkbox/__snapshots__/checkbox.test.js.snap
  src/implementations/twig/components/checkbox/checkbox-group.html.twig
  src/implementations/twig/components/checkbox/checkbox-item.html.twig
  src/implementations/twig/components/checkbox/checkbox.story.js
  src/implementations/twig/components/checkbox/checkbox.test.js
  src/implementations/vanilla/components/checkbox/_checkbox.scss
  src/implementations/vanilla/components/checkbox/checkbox-ec.scss
  src/implementations/vanilla/components/checkbox/checkbox-eu.scss
  src/implementations/vanilla/components/form/_form.scss
  src/implementations/vanilla/components/form/form-ec.scss
  src/implementations/vanilla/components/form/form-eu.scss
  src/presets/dev/src/dev.scss
  src/presets/ec-core/src/ec-core.scss
  src/presets/eu-core/src/eu-core.scss
  src/specs/components/checkbox/demo/data--ec.js
  src/specs/components/checkbox/demo/data--eu.js
  src/website/src/pages/ec/components/forms/checkbox/demo/index.js
Labels: process: under review, tag: new feature

#1967 feat(docs): Harmon-g1-index
  src/website/src/pages/ec/harmonised-templates/docs/group1.mdx
Labels: tag: documentation

#1968 feat(docs): Harmon-g2-index
  src/website/src/pages/ec/harmonised-templates/docs/group2.mdx
Labels: tag: documentation

#1947 feat(select): Review EC, adding EU version - FRONT-2078
  src/implementations/twig/components/select/README.md
  src/implementations/twig/components/select/__snapshots__/select.test.js.snap
  src/implementations/twig/components/select/select.html.twig
  src/implementations/twig/components/select/select.story.js
  src/implementations/twig/components/select/select.test.js
  src/implementations/vanilla/components/select/_select.scss
  src/implementations/vanilla/components/select/select-ec.scss
  src/implementations/vanilla/components/select/select-eu.scss
  src/implementations/vanilla/components/select/select.js
  src/implementations/vanilla/components/select/select.scss
  src/presets/dev/src/dev.scss
  src/presets/ec-core/src/ec-core.scss
  src/presets/eu-core/src/eu-core.scss
  src/specs/components/select/demo/data-multiple--ec.js
  src/specs/components/select/demo/data-multiple--eu.js
  src/specs/components/select/demo/data-single--ec.js
  src/specs/components/select/demo/data-single--eu.js
  src/website/src/pages/ec/components/forms/select/demo/index.js
Labels: tag: new feature

#1972 feat(Usage pages for components): update Usage pages for components “ec_blockquote”
  src/website/src/pages/ec/components/blockquote/docs/usage.md
Labels: netlify-cms/pending_publish
