Repository ec-europa/europa-component-library, pull requests merged in 2021-08, with the labels that each got.

#2167 fix(pagination): fixed pagination current selection- FRONT-2698
  src/implementations/vanilla/components/pagination/_pagination.scss
Labels: tag: bug fix

#2169 chore(deps): Updates 02-08-21
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2171 chore(deps): Fixing audit issue
  package.json
  yarn.lock
Labels: tag: internal

#2170 fix(storybook): fixed css order - FRONT-2710
  src/playground/ec/.storybook/preview-head.html
  src/playground/ec/.storybook/preview.js
  src/playground/eu/.storybook/preview-head.html
  src/playground/eu/.storybook/preview.js
  src/website/src/pages/ec/getting-started/index.md
  src/website/src/pages/eu/getting-started/index.md
Labels: process: review needed, tag: bug fix

#2168 docs(colours): udpate EU colours doc - FRONT-2464
  src/website/src/pages/eu/guidelines/colours/index.md
  src/website/src/website-components/Color/Card.scss
Labels: tag: documentation

#2172 fix(cards): fix center display - FRONT-2708
  src/implementations/vanilla/components/card/_card.scss
  src/implementations/vanilla/components/card/card-eu.scss
Labels: tag: bug fix, Question

#2176 fix(storybook): Fixing switcher link urls to work also in production - FRONT-2791
  src/playground/addons/storybook-addon-system-switcher/Switcher.jsx
Labels: tag: bug fix, process: under review

#2175 fix(playground): Fixing optional css loading in EC and EU - FRONT-2792
  src/playground/ec/.storybook/preview-head.html
  src/playground/eu/.storybook/preview-head.html
Labels: tag: bug fix, Question

#2178 chore(deps): Updates 17-08-21
  lerna.json
  package.json
  src/implementations/vanilla/components/gallery/package.json
  src/implementations/vanilla/components/site-header-core/package.json
  src/implementations/vanilla/components/site-header-harmonised/package.json
  src/implementations/vanilla/components/site-header-standardised/package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/resources/icons-ec/package.json
  src/resources/icons-eu/package.json
  src/resources/icons-flag/package.json
  src/resources/icons-social-media/package.json
  src/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2179 chore(deps): Updates 17-08-21
  examples/webpack4-eu/package.json
  examples/webpack4/package.json
  lerna.json
  package.json
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/resources/icons/package.json
  src/systems/ec/resources/social-icons/package.json
  src/systems/eu/implementations/react/layout/grid/stories/Index.jsx
  src/systems/eu/implementations/react/layout/stacks/stories/Index.jsx
  src/systems/eu/implementations/react/page-structure/footer/stories/Index.jsx
  src/systems/eu/implementations/react/page-structure/language-list/stories/Index.jsx
  src/systems/eu/implementations/react/page-structure/page-header/stories/Index.jsx
  src/systems/eu/implementations/react/page-structure/site-header/stories/Index.jsx
  src/systems/eu/implementations/react/storybook/package.json
  src/systems/eu/implementations/react/templates/pages/campaign/stories/Index.jsx
  src/systems/eu/implementations/react/templates/pages/event-agenda/stories/Index.jsx
  src/systems/eu/implementations/react/templates/pages/event-detail/stories/Index.jsx
  src/systems/eu/implementations/react/templates/pages/event-speaker/stories/Index.jsx
  src/systems/eu/implementations/react/templates/pages/standard/stories/Index.jsx
  src/systems/eu/implementations/react/utilities/background/stories/Index.jsx
  src/systems/eu/implementations/react/utilities/border/stories/Index.jsx
  src/systems/eu/implementations/react/utilities/media/stories/Index.jsx
  src/systems/eu/implementations/react/utilities/spacing/stories/Index.jsx
  src/systems/eu/implementations/react/utilities/typography/stories/Index.jsx
  src/systems/eu/resources/icons/package.json
  src/systems/eu/resources/social-icons/package.json
  src/tools/builder/package.json
  src/tools/storybook-addon-code/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2180 feat(page-header): add overlay for background image - FRONT-2886
  src/implementations/twig/components/page-header-core/page-header-core.html.twig
  src/implementations/twig/components/page-header-core/page-header-core.story.js
  src/implementations/twig/components/page-header-standardised/page-header-standardised.html.twig
  src/implementations/twig/components/page-header-standardised/page-header-standardised.story.js
  src/implementations/vanilla/components/page-header-core/page-header-core-eu.scss
  src/implementations/vanilla/components/page-header-standardised/page-header-standardised-ec.scss
  src/implementations/vanilla/components/page-header-standardised/page-header-standardised-eu.scss
Labels: tag: enhancement

#2181 feat(EU Usage pages for components): update EU Usage pages for components “eu_page_header_core”
  cms-images/eu_core_page_header.png
  cms-images/eu_ph_c_dark_l_734px.png
  cms-images/eu_ph_c_image_l_734px.png
  cms-images/eu_ph_c_light_l_734px.png
  cms-images/eu_ph_c_thumb_l_734px.png
  src/website/src/pages/eu/core-template/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2182 feat(EU Usage pages for components): update EU Usage pages for components “eu_page_header_standardised”
  src/website/src/pages/eu/standardised-template/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2184 fix(page-header): center image - FRONT-2963
  src/implementations/vanilla/components/page-header-core/page-header-core-eu.scss
  src/implementations/vanilla/components/page-header-standardised/page-header-standardised-ec.scss
  src/implementations/vanilla/components/page-header-standardised/page-header-standardised-eu.scss
Labels: tag: enhancement

#2185 fix(page-header): fix padding and optional item - FRONT-2964
  src/implementations/twig/components/page-header-core/page-header-core.html.twig
  src/implementations/twig/components/page-header-standardised/page-header-standardised.html.twig
  src/implementations/vanilla/components/page-header-core/page-header-core-eu.scss
  src/implementations/vanilla/components/page-header-standardised/page-header-standardised-eu.scss
Labels: tag: enhancement

#2186 fix(typography): update headings and paragraphs - FRONT-2965
  src/implementations/twig/utilities/typography/index.story.js
  src/implementations/vanilla/utilities/typography/_typography.scss
  src/implementations/vanilla/utilities/typography/typography-ec.scss
  src/implementations/vanilla/utilities/typography/typography-eu.scss
  src/website/src/pages/ec/utilities/typography/docs/code.mdx
  src/website/src/pages/eu/utilities/typography/docs/code.mdx
Labels: tag: enhancement

#2187 fix(banners): remove border radius when full width - FRONT-2966
  src/implementations/twig/utilities/border/index.story.js
  src/implementations/vanilla/components/hero-banner/_hero-banner.scss
  src/implementations/vanilla/components/page-banner/_page-banner.scss
  src/implementations/vanilla/utilities/border/border.scss
  src/website/src/pages/ec/utilities/border/docs/code.mdx
  src/website/src/pages/ec/utilities/border/docs/usage.md
  src/website/src/pages/eu/utilities/border/docs/code.mdx
  src/website/src/pages/eu/utilities/border/docs/usage.md
Labels: process: WIP, tag: enhancement

#2191 chore(deps): Updates
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/resources/icons-ec/package.json
  src/resources/icons-eu/package.json
  src/resources/icons-flag/package.json
  src/resources/icons-social-media/package.json
  src/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2177 feat(menu): improve menu display - FRONT-2807
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/site-header-core/__snapshots__/site-header-core.test.js.snap
  src/implementations/twig/components/site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/implementations/vanilla/components/menu/_menu.scss
  src/implementations/vanilla/components/menu/menu-ec.scss
  src/implementations/vanilla/components/menu/menu-eu.scss
  src/specs/components/menu/demo/data--en.js
  src/specs/components/menu/demo/data--fr.js
Labels: tag: enhancement

#2192 chore(deps): Updates
  package.json
  src/systems/ec/implementations/react/storybook/package.json
  src/systems/ec/resources/icons/package.json
  src/systems/ec/resources/social-icons/package.json
  src/systems/eu/implementations/react/storybook/package.json
  src/systems/eu/resources/icons/package.json
  src/systems/eu/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal
