Repository ec-europa/europa-component-library, pull requests merged in 2021-04, with the labels that each got.

#1970 fix(controls): Adding none options for icons - FRONT-2154
  src/implementations/twig/components/button/button.story.js
  src/implementations/twig/components/link/link.story.js
Labels: process: under review, tag: internal

#1962 feat(site-header-core): Review EC, adding EU version - FRONT-1947
  src/implementations/twig/components/site-header-core/__snapshots__/site-header-core.test.js.snap
  src/implementations/twig/components/site-header-core/site-header-core.html.twig
  src/implementations/twig/components/site-header-core/site-header-core.story.js
  src/implementations/vanilla/components/site-header-core/site-header-core-ec.scss
  src/implementations/vanilla/components/site-header-core/site-header-core-eu.scss
  src/specs/components/site-header-core/demo/data--fr.js
  src/specs/components/site-header-core/demo/data.js
Labels: process: business approval, tag: new feature

#1976 feat(EC Guidelines): update EC Guidelines “ec_guidelines_typography”
  src/website/src/pages/ec/guidelines/typography/index.md
Labels: netlify-cms/pending_publish

#1977 feat(Usage pages for components): update Usage pages for components “ec_accordion”
  src/website/src/pages/ec/components/accordion/docs/usage.md
Labels: netlify-cms/pending_publish

#1978 feat(Usage pages for components): update Usage pages for components “ec_button”
  src/website/src/pages/ec/components/button/docs/usage.md
Labels: netlify-cms/pending_publish

#1979 feat(Usage pages for components): update Usage pages for components “ec_card”
  src/website/src/pages/ec/components/card/docs/usage.md
Labels: netlify-cms/pending_publish

#1980 feat(Usage pages for components): update Usage pages for components “ec_checkbox”
  src/website/src/pages/ec/components/forms/checkbox/docs/usage.md
Labels: netlify-cms/pending_publish

#1981 feat(Usage pages for components): update Usage pages for components “ec_date_block”
  src/website/src/pages/ec/components/date-block/docs/usage.md
Labels: netlify-cms/pending_publish

#1982 feat(Usage pages for components): update Usage pages for components “ec_datepicker”
  src/website/src/pages/ec/components/forms/datepicker/docs/usage.md
Labels: netlify-cms/pending_publish

#1983 feat(Usage pages for components): update Usage pages for components “ec_expandable”
  src/website/src/pages/ec/components/expandable/docs/usage.md
Labels: netlify-cms/pending_publish

#1984 feat(Usage pages for components): update Usage pages for components “ec_expandable”
  src/website/src/pages/ec/components/expandable/docs/usage.md
Labels: netlify-cms/pending_publish

#1985 feat(Usage pages for components): update Usage pages for components “ec_fact_figures”
  src/website/src/pages/ec/components/fact-figures/docs/usage.md
Labels: netlify-cms/pending_publish

#1986 feat(Usage pages for components): update Usage pages for components “ec_file”
  src/website/src/pages/ec/components/file/docs/usage.md
Labels: netlify-cms/pending_publish

#1987 feat(Usage pages for components): update Usage pages for components “ec_gallery”
  src/website/src/pages/ec/components/media/gallery/docs/usage.md
Labels: netlify-cms/pending_publish

#1988 feat(Usage pages for components): update Usage pages for components “ec_timeline”
  src/website/src/pages/ec/components/timeline/docs/usage.md
Labels: netlify-cms/pending_publish

#1989 feat(Usage pages for components): update Usage pages for components “ec_hero_banner”
  src/website/src/pages/ec/components/banners/hero-banner/docs/usage.md
Labels: netlify-cms/pending_publish

#1990 feat(Usage pages for components): update Usage pages for components “ec_icon”
  src/website/src/pages/ec/components/icon/docs/usage.md
Labels: netlify-cms/pending_publish

#1991 feat(Usage pages for components): update Usage pages for components “ec_inpage_navigation”
  src/website/src/pages/ec/components/navigation/inpage-navigation/docs/usage.md
Labels: netlify-cms/pending_publish

#1992 feat(Usage pages for components): update Usage pages for components “ec_label”
  src/website/src/pages/ec/components/label/docs/usage.md
Labels: netlify-cms/pending_publish

#1993 feat(Usage pages for components): update Usage pages for components “ec_language_list”
  src/website/src/pages/ec/components/language-list/docs/usage.md
Labels: netlify-cms/pending_publish

#1994 feat(Usage pages for components): update Usage pages for components “ec_link”
  src/website/src/pages/ec/components/navigation/link/docs/usage.md
Labels: netlify-cms/pending_publish

#1995 feat(Usage pages for components): update Usage pages for components “ec_list”
  src/website/src/pages/ec/components/list/docs/usage.md
Labels: netlify-cms/pending_publish

#1997 feat(Usage pages for components): update Usage pages for components “ec_list”
  src/website/src/pages/ec/components/list/docs/usage.md
Labels: netlify-cms/pending_publish

#1998 feat(Usage pages for components): update Usage pages for components “ec_media_container”
  src/website/src/pages/ec/components/media/media-container/docs/usage.md
Labels: netlify-cms/pending_publish

#1999 feat(Usage pages for components): update Usage pages for components “ec_menu”
  src/website/src/pages/ec/components/navigation/menu/docs/usage.md
Labels: netlify-cms/pending_publish

#2000 feat(Usage pages for components): update Usage pages for components “ec_message”
  src/website/src/pages/ec/components/message/docs/usage.md
Labels: netlify-cms/pending_publish

#1973 fix(preset): add missing css in eu preset - FRONT-2160
  src/systems/eu/implementations/vanilla/packages/eu-preset-website/src/_globals.scss
Labels: process: review needed, tag: bug fix

#2001 feat(Usage pages for components): update Usage pages for components “ec_page_banner”
  src/website/src/pages/ec/components/banners/page-banner/docs/usage.md
Labels: netlify-cms/pending_publish

#2002 feat(Usage pages for components): update Usage pages for components “ec_pagination”
  src/website/src/pages/ec/components/navigation/pagination/docs/usage.md
Labels: netlify-cms/pending_publish

#2003 feat(Usage pages for components): update Usage pages for components “ec_radio”
  src/website/src/pages/ec/components/forms/radio/docs/usage.md
Labels: netlify-cms/pending_publish

#2004 feat(Usage pages for components): update Usage pages for components “ec_select”
  src/website/src/pages/ec/components/forms/select/docs/usage.md
Labels: netlify-cms/pending_publish

#2005 feat(Usage pages for components): update Usage pages for components “ec_textarea”
  src/website/src/pages/ec/components/forms/text-area/docs/usage.md
Labels: netlify-cms/pending_publish

#1958 feat(breadcrumb): update EC breadcrumb and add EU
  docs/Migrating-v3.md
  src/implementations/twig/components/breadcrumb-core/README.md
  src/implementations/twig/components/breadcrumb-core/__snapshots__/breadcrumb-core.test.js.snap
  src/implementations/twig/components/breadcrumb-core/breadcrumb-core.html.twig
  src/implementations/twig/components/breadcrumb-core/breadcrumb-core.story.js
  src/implementations/twig/components/breadcrumb-core/package.json
  src/implementations/twig/components/breadcrumb-harmonised/README.md
  src/implementations/twig/components/breadcrumb-harmonised/__snapshots__/breadcrumb-harmonised.test.js.snap
  src/implementations/twig/components/breadcrumb-harmonised/breadcrumb-harmonised.html.twig
  src/implementations/twig/components/breadcrumb-harmonised/breadcrumb-harmonised.story.js
  src/implementations/twig/components/breadcrumb-harmonised/package.json
  src/implementations/twig/components/breadcrumb-standardised/README.md
  src/implementations/twig/components/breadcrumb-standardised/__snapshots__/breadcrumb-standardised.test.js.snap
  src/implementations/twig/components/breadcrumb-standardised/breadcrumb-standardised.html.twig
  src/implementations/twig/components/breadcrumb-standardised/breadcrumb-standardised.story.js
  src/implementations/twig/components/breadcrumb-standardised/package.json
  src/implementations/twig/components/link/README.md
  src/implementations/twig/components/link/link.html.twig
  src/implementations/twig/components/link/link.story.js
  src/implementations/twig/components/page-header-core/__snapshots__/page-header-core.test.js.snap
  src/implementations/twig/components/page-header-core/page-header-core.story.js
  src/implementations/twig/components/page-header-harmonised/__snapshots__/page-header-harmonised.test.js.snap
  src/implementations/twig/components/page-header-harmonised/page-header-harmonised.story.js
  src/implementations/twig/components/page-header-standardised/__snapshots__/page-header-standardised.test.js.snap
  src/implementations/twig/components/page-header-standardised/page-header-standardised.story.js
  src/implementations/vanilla/components/breadcrumb-core/_breadcrumb-core.scss
  src/implementations/vanilla/components/breadcrumb-core/breadcrumb-core-ec.scss
  src/implementations/vanilla/components/breadcrumb-core/breadcrumb-core-eu.scss
  src/implementations/vanilla/components/breadcrumb-harmonised/_breadcrumb-harmonised.scss
  src/implementations/vanilla/components/breadcrumb-harmonised/breadcrumb-harmonised-ec.scss
  src/implementations/vanilla/components/breadcrumb-harmonised/breadcrumb-harmonised-eu.scss
  src/implementations/vanilla/components/breadcrumb-standardised/_breadcrumb-standardised.scss
  src/implementations/vanilla/components/breadcrumb-standardised/breadcrumb-standardised-ec.scss
  src/implementations/vanilla/components/breadcrumb-standardised/breadcrumb-standardised-eu.scss
  src/implementations/vanilla/components/link/_link.scss
  src/presets/dev/src/dev.scss
  src/presets/ec-core/src/ec-core.scss
  src/presets/eu-core/src/eu-core.scss
  src/specs/components/breadcrumb/demo/data--eu.js
  src/specs/components/breadcrumb/demo/data-simple--eu.js
  src/themes/dev/maps/icon.scss
Labels: process: under review, tag: new feature

#2006 feat(Usage pages for components): update Usage pages for components “ec_text-field”
  src/website/src/pages/ec/components/forms/text-field/docs/usage.md
Labels: netlify-cms/pending_publish

#2007 feat(Usage pages for components): update Usage pages for components “ec_search_form”
  src/website/src/pages/ec/components/forms/search-form/docs/usage.md
Labels: netlify-cms/pending_publish

#2008 feat(Usage pages for components): update Usage pages for components “ec_social_media_follow”
  src/website/src/pages/ec/components/social-media-follow/docs/usage.md
Labels: netlify-cms/pending_publish

#2009 feat(Usage pages for components): update Usage pages for components “ec_social_media_share”
  src/website/src/pages/ec/components/social-media-share/docs/usage.md
Labels: netlify-cms/pending_publish

#2011 feat(Usage pages for components): update Usage pages for components “ec_breadcrumbs”
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/usage.md
Labels: netlify-cms/pending_publish

#1974 feat(label): add EU version and update EC - FRONT-2161
  src/implementations/vanilla/components/label/_label-print.scss
  src/implementations/vanilla/components/label/_label.scss
  src/implementations/vanilla/components/label/label-ec.scss
  src/implementations/vanilla/components/label/label-eu.scss
  src/implementations/vanilla/components/label/label-print-ec.scss
  src/implementations/vanilla/components/label/label-print-eu.scss
  src/implementations/vanilla/components/label/label-print.scss
  src/implementations/vanilla/components/label/label.scss
  src/presets/ec-core/src/ec-core-print.scss
  src/presets/ec-core/src/ec-core.scss
  src/presets/eu-core/src/eu-core-print.scss
  src/presets/eu-core/src/eu-core.scss
Labels: tag: new feature

#1975 feat(blockquote): Add EU blockquote and update EC - FRONT-2123
  src/implementations/vanilla/components/blockquote/_blockquote-print.scss
  src/implementations/vanilla/components/blockquote/_blockquote.scss
  src/implementations/vanilla/components/blockquote/blockquote-ec.scss
  src/implementations/vanilla/components/blockquote/blockquote-eu.scss
  src/implementations/vanilla/components/blockquote/blockquote-print-ec.scss
  src/implementations/vanilla/components/blockquote/blockquote-print-eu.scss
  src/implementations/vanilla/components/blockquote/blockquote-print.scss
  src/implementations/vanilla/components/blockquote/blockquote.scss
  src/presets/ec-core/src/ec-core-print.scss
  src/presets/ec-core/src/ec-core.scss
  src/presets/eu-core/src/eu-core-print.scss
  src/presets/eu-core/src/eu-core.scss
Labels: tag: new feature

#2012 feat(Usage pages for components): update Usage pages for components “ec_table”
  src/website/src/pages/ec/components/forms/table/docs/usage.md
Labels: netlify-cms/pending_publish

#2013 feat(Usage pages for components): update Usage pages for components “ec_tag”
  src/website/src/pages/ec/components/tag/docs/usage.md
Labels: netlify-cms/pending_publish

#2015 feat(EC Reources): update EC Reources “ec_resources_glossary”
  src/website/src/pages/ec/resources/glossary/index.md
Labels: netlify-cms/pending_publish

#2016 feat(Usage pages for components): update Usage pages for components “ec_table”
  src/website/src/pages/ec/components/table/docs/usage.md
Labels: netlify-cms/pending_publish

#2014 chore: updating storybook to 6.2.8
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  yarn.lock
Labels: tag: internal

#2010 docs(migration): update migration doc - FRONT-2180
  docs/Migrating-v3.md
Labels: process: review needed, tag: documentation

#2017 chore(deps): updates - 15-04-21 (v3)
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2018 chore(deps): using ssri > 6.0.1
  package.json
  yarn.lock
Labels: tag: internal

#1996 feat(pagination): Add EU pagination and update EC - FRONT-2123
  src/implementations/vanilla/components/pagination/_pagination.scss
  src/implementations/vanilla/components/pagination/pagination-ec.scss
  src/implementations/vanilla/components/pagination/pagination-eu.scss
  src/presets/ec-core/src/ec-core.scss
  src/presets/eu-core/src/eu-core.scss
Labels: process: business approval needed, tag: new feature

#2022 chore(deps): updates
  .github/workflows/ci.yml
  .size-limit.json
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2025 feat(expandable): Adding EU styles - FRONT-2167
  src/implementations/twig/components/expandable/__snapshots__/expandable.test.js.snap
  src/implementations/vanilla/components/expandable/_expandable.scss
  src/implementations/vanilla/components/expandable/expandable-ec.scss
  src/implementations/vanilla/components/expandable/expandable-eu.scss
  src/presets/ec-core/src/ec-core.scss
  src/presets/eu-core/src/eu-core.scss
  src/specs/components/expandable/demo/data.js
Labels: tag: new feature

#2027 feat(Usage pages for components): update Usage pages for components “ec_footer_core”
  cms-images/core-footer.jpg
  src/website/src/pages/ec/core-template/footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2020 feat(site-header-standardised): add EU site header standardised and update EC
  docs/Migrating-v3.md
  src/implementations/twig/components/menu/README.md
  src/implementations/twig/components/menu/menu.html.twig
  src/implementations/twig/components/menu/menu.story.js
  src/implementations/twig/components/site-header-core/README.md
  src/implementations/twig/components/site-header-core/site-header-core.html.twig
  src/implementations/twig/components/site-header-harmonised/README.md
  src/implementations/twig/components/site-header-harmonised/site-header-harmonised.html.twig
  src/implementations/twig/components/site-header-standardised/README.md
  src/implementations/twig/components/site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/implementations/twig/components/site-header-standardised/site-header-standardised.html.twig
  src/implementations/twig/components/site-header-standardised/site-header-standardised.story.js
  src/implementations/twig/components/site-header-standardised/site-header-standardised.test.js
  src/implementations/vanilla/components/menu/_menu.scss
  src/implementations/vanilla/components/menu/menu-ec.scss
  src/implementations/vanilla/components/menu/menu-eu.scss
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised-ec.scss
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised-eu.scss
  src/specs/components/site-header-harmonised/demo/data--fr.js
  src/specs/components/site-header-harmonised/demo/data--group1.js
  src/specs/components/site-header-harmonised/demo/data--group2.js
  src/specs/components/site-header-standardised/demo/data--fr.js
  src/specs/components/site-header-standardised/demo/data.js
Labels: process: business approval needed, tag: new feature

#2030 feat(Usage pages for components): update Usage pages for components “ec_footer_core”
  src/website/src/pages/ec/core-template/footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2031 feat(Usage pages for components): update Usage pages for components “ec_footer_core”
  src/website/src/pages/ec/core-template/footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2033 feat(Europa family for EC): update Europa family for EC “ec_core_template”
  src/website/src/pages/ec/core-template/index.md
Labels: netlify-cms/pending_publish

#2034 feat(Europa family for EC): update Europa family for EC “ec_core_template”
  src/website/src/pages/ec/core-template/index.md
Labels: netlify-cms/pending_publish

#2035 feat(Europa family for EC): update Europa family for EC “ec_standardised_template”
  src/website/src/pages/ec/standardised-template/index.md
Labels: netlify-cms/pending_publish

#2036 feat(Usage pages for components): update Usage pages for components “ec_site_header_standardised”
  src/website/src/pages/ec/standardised-template/site-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2021 feat(messages): Adding EU styles, revamping EC - FRONT-2152
  docs/Migrating-v3.md
  src/implementations/twig/components/message/__snapshots__/message.test.js.snap
  src/implementations/twig/components/message/message.html.twig
  src/implementations/twig/components/message/message.story.js
  src/implementations/twig/components/message/message.test.js
  src/implementations/vanilla/components/message/_message-print.scss
  src/implementations/vanilla/components/message/_message.scss
  src/implementations/vanilla/components/message/message-ec.scss
  src/implementations/vanilla/components/message/message-eu.scss
  src/implementations/vanilla/components/message/message-print-ec.scss
  src/implementations/vanilla/components/message/message-print-eu.scss
  src/implementations/vanilla/components/message/message-print.scss
  src/presets/ec-core/src/ec-core-print.scss
  src/presets/ec-core/src/ec-core.scss
  src/presets/eu-core/src/eu-core-print.scss
  src/presets/eu-core/src/eu-core.scss
  src/specs/components/message/demo/data--error.js
  src/specs/components/message/demo/data--info.js
  src/specs/components/message/demo/data--success.js
  src/specs/components/message/demo/data--warning.js
  src/themes/eu-core/_index.scss
Labels: process: review needed, tag: new feature

#2040 feat(Usage pages for components): update Usage pages for components “ec_page_header_core”
  src/website/src/pages/ec/core-template/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2032 feat(Usage pages for components): update Usage pages for components “ec_site_header_core”
  src/website/src/pages/ec/core-template/site-header/docs/usage.md
Labels: netlify-cms/draft

#2042 feat(Usage pages for components): update Usage pages for components “ec_page_header_standardised”
  src/website/src/pages/ec/standardised-template/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2043 feat(EC Reources): update EC Reources “ec_resources_eui”
  src/website/src/pages/ec/resources/eui/index.md
Labels: netlify-cms/pending_publish

#2045 feat(Usage pages for components): update Usage pages for components “ec_gallery”
  src/website/src/pages/ec/components/media/gallery/docs/usage.md
Labels: netlify-cms/pending_publish

#2046 feat(Usage pages for components): update Usage pages for components “ec_gallery”
  src/website/src/pages/ec/components/media/gallery/docs/usage.md
Labels: netlify-cms/pending_publish

#2026 feat(accordion): Adding EU styles, revamping EC - FRONT-2153
  docs/Migrating-v3.md
  src/implementations/twig/components/accordion/README.md
  src/implementations/twig/components/accordion/__snapshots__/accordion.test.js.snap
  src/implementations/twig/components/accordion/accordion.html.twig
  src/implementations/twig/components/accordion/accordion.story.js
  src/implementations/twig/components/expandable/README.md
  src/implementations/vanilla/components/accordion/accordion-ec.scss
  src/implementations/vanilla/components/accordion/accordion-eu.scss
  src/implementations/vanilla/components/accordion/accordion-print.scss
  src/implementations/vanilla/components/accordion/accordion.js
  src/presets/ec-core/src/ec-core.scss
  src/presets/eu-core/src/eu-core.scss
  src/specs/components/accordion/demo/data.js
Labels: tag: new feature

#2049 docs(footer): update EU footer links - FRONT-2215
  src/systems/eu/specs/components/footer-core/demo/data.js
  src/systems/eu/specs/components/footer-harmonised/demo/data.js
  src/systems/eu/specs/components/footer-standardised/demo/data.js
Labels: tag: documentation

#2041 feat(fact-figures): Adding EU styles, revamping EC - FRONT-2169
  docs/Migrating-v3.md
  src/implementations/twig/components/fact-figures/__snapshots__/fact-figures.test.js.snap
  src/implementations/twig/components/fact-figures/fact-figures.html.twig
  src/implementations/twig/components/fact-figures/fact-figures.story.js
  src/implementations/vanilla/components/fact-figures/_fact-figures.scss
  src/implementations/vanilla/components/fact-figures/fact-figures-ec.scss
  src/implementations/vanilla/components/fact-figures/fact-figures-eu.scss
  src/implementations/vanilla/components/fact-figures/fact-figures-print.scss
  src/implementations/vanilla/components/fact-figures/fact-figures.scss
  src/presets/ec-core/src/ec-core.scss
  src/presets/eu-core/src/eu-core.scss
  src/resources/icons-ec/src/all/growth.svg
  src/specs/components/fact-figures/demo/data--3-col.js
  src/specs/components/fact-figures/demo/data--4-col.js
Labels: tag: new feature

#2047 feat(utilities): improve dimension utilities (ECL2) - FRONT-2196
  src/systems/ec/implementations/react/utilities/dimension/stories/Index.jsx
  src/systems/ec/implementations/react/utilities/display/stories/Index.jsx
  src/systems/ec/implementations/vanilla/packages/ec-editor/_ec-editor--media.scss
  src/systems/ec/implementations/vanilla/packages/ec-editor/ec-editor.scss
  src/systems/ec/implementations/vanilla/packages/ec-utility-dimension/ec-utility-dimension-print.scss
  src/systems/ec/implementations/vanilla/packages/ec-utility-dimension/ec-utility-dimension.scss
  src/systems/eu/implementations/react/utilities/dimension/stories/Index.jsx
  src/systems/eu/implementations/react/utilities/display/stories/Index.jsx
  src/systems/eu/implementations/vanilla/packages/eu-editor/_eu-editor--media.scss
  src/systems/eu/implementations/vanilla/packages/eu-editor/eu-editor.scss
  src/systems/eu/implementations/vanilla/packages/eu-utility-dimension/eu-utility-dimension-print.scss
  src/systems/eu/implementations/vanilla/packages/eu-utility-dimension/eu-utility-dimension.scss
  src/website/src/pages/ec/utilities/dimension/docs/usage.mdx
Labels: tag: enhancement

#2044 refactor(preset): rename themes and presets - FRONT-2175
  .size-limit.json
  package.json
  scripts/dist-presets.sh
  src/playground/addons/storybook-addon-code/codepen.js
  src/playground/ec/.storybook/preview-head.html
  src/playground/ec/.storybook/preview.js
  src/playground/ec/start.js
  src/playground/eu/.storybook/preview-head.html
  src/playground/eu/.storybook/preview.js
  src/playground/eu/start.js
  src/presets/ec-core/README.md
  src/presets/ec/.npmignore
  src/presets/ec/README.md
  src/presets/ec/ecl-builder.config.js
  src/presets/ec/package.json
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.js
  src/presets/ec/src/ec.scss
  src/presets/eu-core/README.md
  src/presets/eu/.npmignore
  src/presets/eu/README.md
  src/presets/eu/ecl-builder.config.js
  src/presets/eu/package.json
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.js
  src/presets/eu/src/eu.scss
  src/presets/reset/ecl-builder.config.js
  src/presets/reset/package.json
  src/themes/ec-core/README.md
  src/themes/ec/README.md
  src/themes/ec/_index.scss
  src/themes/ec/package.json
  src/themes/eu-core/README.md
  src/themes/eu/README.md
  src/themes/eu/_index.scss
  src/themes/eu/package.json
  src/website/src/components/Navigation/Navigation.scss
  src/website/src/components/SplashPage/SplashPage.jsx
  src/website/src/routes/Skeleton.jsx
  src/website/webpack.config.prod.js
Labels: tag: enhancement

#2050 fix(footer): fix visited link color - FRONT-2217
  src/implementations/vanilla/components/footer-core/footer-core-ec.scss
  src/implementations/vanilla/components/footer-harmonised/footer-harmonised-ec.scss
  src/implementations/vanilla/components/footer-standardised/footer-standardised-ec.scss
Labels: tag: bug fix

#2048 feat(utilities): improve dimension utilities (ECL3) - FRONT-2196
  src/implementations/twig/utilities/dimension/index.story.js
  src/implementations/vanilla/utilities/dimension/dimension-print.scss
  src/implementations/vanilla/utilities/dimension/dimension.scss
  src/website/src/pages/ec/utilities/dimension/docs/usage.md
Labels: process: review needed, tag: enhancement
