Repository ec-europa/europa-component-library, pull requests merged in 2021-11, with the labels that each got.

#2251 fix(radio): Fixing opacity due to cssnano bug - FRONT-3345
  .stylelintrc.js
  src/implementations/vanilla/components/file-upload/file-upload.js
  src/implementations/vanilla/components/radio/_radio.scss
Labels: tag: bug fix, process: review needed

#2247 feat(file): add control option - FRONT-3305
  src/implementations/twig/components/file/file.story.js
Labels: tag: enhancement

#2243 feat(list): change list indent - FRONT-3282
  src/implementations/twig/components/ordered-list/ordered-list.story.js
  src/implementations/twig/components/unordered-list/unordered-list.story.js
  src/implementations/vanilla/components/ordered-list/_ordered-list.scss
  src/implementations/vanilla/components/unordered-list/_unordered-list.scss
Labels: tag: enhancement

#2257 chore(deps): Updates 16-11-21
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2254 feat(footers): Updating some link - FRONT-3225
  src/implementations/twig/components/footer-core/__snapshots__/footer-core.test.js.snap
  src/implementations/twig/components/footer-standardised/__snapshots__/footer-standardised.test.js.snap
  src/specs/components/footer-core/demo/data--ec.js
  src/specs/components/footer-core/demo/data--eu.js
  src/specs/components/footer-standardised/demo/data--ec.js
  src/specs/components/footer-standardised/demo/data--eu.js
Labels: tag: enhancement

#2252 feat(file): label(s) also in the default variant - FRONT-3350
  src/implementations/twig/components/file/README.md
  src/implementations/twig/components/file/__snapshots__/file.test.js.snap
  src/implementations/twig/components/file/file.html.twig
  src/implementations/twig/components/file/file.story.js
  src/implementations/twig/components/file/file.test.js
  src/implementations/vanilla/components/file/_file.scss
  src/implementations/vanilla/components/file/file-ec.scss
  src/implementations/vanilla/components/file/file-eu.scss
  yarn.lock
Labels: tag: enhancement

#2262 fix(site-header): fix call to action link on EU - FRONT-3414
  src/implementations/twig/components/site-header-standardised/site-header-standardised.story.js
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised-ec.scss
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised-eu.scss
Labels: tag: bug fix

#2261 fix(input-fields): EU input fields shadows clean up - FRONT-3304
  src/implementations/vanilla/components/datepicker/_datepicker.scss
  src/implementations/vanilla/components/datepicker/datepicker-ec.scss
  src/implementations/vanilla/components/datepicker/datepicker-eu.scss
  src/implementations/vanilla/components/select/_select.scss
  src/implementations/vanilla/components/select/select-eu.scss
  src/implementations/vanilla/components/text-area/_text-area.scss
  src/implementations/vanilla/components/text-input/_text-input.scss
Labels: tag: bug fix

#2268 chore(deps): updates - 29-11-2021
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal
