Repository ec-europa/europa-component-library, pull requests merged in 2022-10, with the labels that each got.

#2647 feat(multiselect): Adding toolbar and selection counter - FRONT-3746
  .size-limit.json
  src/implementations/twig/components/popover/popover.html.twig
  src/implementations/twig/components/select/__snapshots__/select.test.js.snap
  src/implementations/twig/components/select/select.html.twig
  src/implementations/vanilla/components/select/_select.scss
  src/implementations/vanilla/components/select/select-ec.scss
  src/implementations/vanilla/components/select/select-eu.scss
  src/implementations/vanilla/components/select/select.js
  src/playground/addons/storybook-addon-code/package.json
  src/specs/components/select/demo/data-multiple.js
Labels: tag: enhancement

#2650 fix(ordered-list): fix list alignment - FRONT-3744
  src/implementations/vanilla/components/ordered-list/_ordered-list.scss
Labels: tag: bug fix

#2661 feat(focus): New styles for checkboxes and radios - FRONT-3770
  src/implementations/vanilla/components/checkbox/_checkbox.scss
  src/implementations/vanilla/components/checkbox/checkbox-ec.scss
  src/implementations/vanilla/components/checkbox/checkbox-eu.scss
  src/implementations/vanilla/components/radio/_radio.scss
  src/implementations/vanilla/components/radio/radio-ec.scss
  src/implementations/vanilla/components/radio/radio-eu.scss
Labels: tag: enhancement

#2660 fix(print): fix display of default html tag for print - FRONT-3699
  src/implementations/twig/utilities/html-tag/index.story.js
  src/implementations/vanilla/components/blockquote/_blockquote-print.scss
  src/implementations/vanilla/components/button/_button-print.scss
  src/implementations/vanilla/components/description-list/_description-list-print.scss
  src/implementations/vanilla/components/link/_link-print.scss
  src/implementations/vanilla/components/ordered-list/ordered-list-print.scss
  src/implementations/vanilla/components/table/table-print.scss
  src/implementations/vanilla/components/unordered-list/unordered-list-print.scss
  src/implementations/vanilla/utilities/typography/_typography-print.scss
  src/playground/ec/.storybook/preview-head.html
  src/playground/ec/.storybook/preview.js
  src/playground/eu/.storybook/preview-head.html
  src/playground/eu/.storybook/preview.js
  src/presets/ec/ecl-builder.config.js
  src/presets/ec/src/ec-default-print.scss
  src/presets/eu/ecl-builder.config.js
  src/presets/eu/src/eu-default-print.scss
  src/website/src/pages/ec/getting-started/index.md
  src/website/src/pages/ec/utilities/html-tag/docs/usage.md
  src/website/src/pages/eu/getting-started/index.md
  src/website/src/pages/eu/utilities/html-tag/docs/usage.md
Labels: tag: enhancement

#2666 feat(content-block): update title font - FRONT-3777
  src/implementations/vanilla/components/content-block/_content-block.scss
  src/implementations/vanilla/components/content-block/content-block-ec.scss
  src/implementations/vanilla/components/content-block/content-block-eu.scss
Labels: tag: enhancement

#2667 chore(deps): Updates 17-10-22
  package.json
  yarn.lock
Labels: tag: internal

#2673 fix(content-block): fix stories control issue - FRONT-3786
  src/implementations/twig/components/card/card.story.js
  src/implementations/twig/components/content-block/content-block.story.js
  src/implementations/twig/components/content-item/content-item.story.js
Labels: tag: bug fix, process: review needed

#2674 fix(card): fix image display on firefox - FRONT-3788
  src/implementations/vanilla/components/card/_card.scss
Labels: tag: bug fix

#2676 chore(deps): Updates 27-10-22
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2675 fix(icons): Replacing greece square and slovakia square - FRONT-3779
  src/resources/icons-flag/src/flag/greece-square.svg
  src/resources/icons-flag/src/flag/slovakia-square.svg
Labels: tag: enhancement, process: review needed
