Repository ec-europa/europa-component-library, pull requests merged in 2022-05, with the labels that each got.

#2337 feat(page-header): add site-wide components - FRONT-3546
  .size-limit.json
  src/implementations/twig/components/page-header-harmonised/ec-page-header-harmonised.story.js
  src/implementations/twig/components/page-header/.npmignore
  src/implementations/twig/components/page-header/README.md
  src/implementations/twig/components/page-header/__snapshots__/page-header.test.js.snap
  src/implementations/twig/components/page-header/ec-page-header.story.js
  src/implementations/twig/components/page-header/eu-page-header.story.js
  src/implementations/twig/components/page-header/package.json
  src/implementations/twig/components/page-header/page-header.html.twig
  src/implementations/twig/components/page-header/page-header.test.js
  src/implementations/vanilla/components/breadcrumb-core/_breadcrumb-core.scss
  src/implementations/vanilla/components/breadcrumb-core/breadcrumb-core-ec.scss
  src/implementations/vanilla/components/breadcrumb-core/breadcrumb-core-eu.scss
  src/implementations/vanilla/components/breadcrumb-harmonised/_breadcrumb-harmonised.scss
  src/implementations/vanilla/components/breadcrumb-harmonised/breadcrumb-harmonised-ec.scss
  src/implementations/vanilla/components/breadcrumb-harmonised/breadcrumb-harmonised-eu.scss
  src/implementations/vanilla/components/breadcrumb-standardised/_breadcrumb-standardised.scss
  src/implementations/vanilla/components/breadcrumb-standardised/breadcrumb-standardised-ec.scss
  src/implementations/vanilla/components/breadcrumb-standardised/breadcrumb-standardised-eu.scss
  src/implementations/vanilla/components/page-header/README.md
  src/implementations/vanilla/components/page-header/package.json
  src/implementations/vanilla/components/page-header/page-header-ec.scss
  src/implementations/vanilla/components/page-header/page-header-eu.scss
  src/implementations/vanilla/components/page-header/page-header-print.scss
  src/presets/dev/src/dev.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/specs/components/page-header/demo/data.js
  src/specs/components/page-header/package.json
  src/website/public/admin/config.yml
  src/website/src/pages/ec/components/index.mdx
  src/website/src/pages/ec/components/site-wide/page-header/demo/index.js
  src/website/src/pages/ec/components/site-wide/page-header/docs/code.mdx
  src/website/src/pages/ec/components/site-wide/page-header/docs/usage.md
  src/website/src/pages/ec/components/site-wide/page-header/ec_comp_page-header.svg
  src/website/src/pages/ec/components/site-wide/page-header/index.md
  src/website/src/pages/eu/components/index.mdx
  src/website/src/pages/eu/components/site-wide/page-header/demo/index.js
  src/website/src/pages/eu/components/site-wide/page-header/docs/code.mdx
  src/website/src/pages/eu/components/site-wide/page-header/docs/usage.md
  src/website/src/pages/eu/components/site-wide/page-header/eu_comp_page-header.svg
  src/website/src/pages/eu/components/site-wide/page-header/index.md
Labels: tag: new feature, process: review needed

#2407 chore(deps): Updates 02-05-22 - audit check fix
  package.json
  src/implementations/vanilla/components/gallery/package.json
  src/implementations/vanilla/components/site-header-core/package.json
  src/implementations/vanilla/components/site-header-harmonised/package.json
  src/implementations/vanilla/components/site-header-standardised/package.json
  src/implementations/vanilla/components/site-header/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2372 feat(select): Correctly reset the multiselect on form reset - FRONT-3583
  src/implementations/vanilla/components/select/select.js
Labels: tag: enhancement

#2409 feat(EC Usage pages for components): update EC Usage pages for components “ec_news_ticker”
  src/website/src/pages/ec/components/news-ticker/docs/usage.md
Labels: netlify-cms/pending_publish

#2410 feat(EC Usage pages for components): update EC Usage pages for components “ec_list_illustration”
  src/website/src/pages/ec/components/list-illustration/docs/usage.md
Labels: netlify-cms/pending_publish

#2411 feat(Europa family for EU): update Europa family for EU “eu_core_template”
  src/website/src/pages/eu/core-template/index.md
Labels: netlify-cms/pending_publish

#2412 feat(Europa family for EU): update Europa family for EU “eu_harmonised_template”
  src/website/src/pages/eu/harmonised-template/index.md
Labels: netlify-cms/pending_publish

#2413 feat(EC Usage pages for components): update EC Usage pages for components “ec_news_ticker”
  src/website/src/pages/ec/components/news-ticker/docs/usage.md
Labels: netlify-cms/pending_publish

#2414 feat(EC Usage pages for components): update EC Usage pages for components “ec_list_illustration”
  src/website/src/pages/ec/components/list-illustration/docs/usage.md
Labels: netlify-cms/pending_publish

#2415 feat(EC Usage pages for components): update EC Usage pages for components “ec_featured_item”
  src/website/src/pages/ec/components/media/featured-item/docs/usage.md
Labels: netlify-cms/pending_publish

#2416 feat(EC Usage pages for components): update EC Usage pages for components “ec_tag”
  src/website/src/pages/ec/components/tag/docs/usage.md
Labels: netlify-cms/pending_publish

#2417 feat(EC Usage pages for components): update EC Usage pages for components “ec_search_form”
  src/website/src/pages/ec/components/forms/search-form/docs/usage.md
Labels: netlify-cms/pending_publish

#2418 feat(EC Usage pages for components): update EC Usage pages for components “ec_breadcrumbs”
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/usage.md
Labels: netlify-cms/pending_publish

#2419 feat(EC Usage pages for components): update EC Usage pages for components “ec_list”
  src/website/src/pages/ec/components/list/docs/usage.md
Labels: netlify-cms/pending_publish

#2420 feat(EC Usage pages for components): update EC Usage pages for components “ec_link”
  src/website/src/pages/ec/components/navigation/link/docs/usage.md
Labels: netlify-cms/pending_publish

#2421 feat(EU Usage pages for components): update EU Usage pages for components “eu_breadcrumbs”
  src/website/src/pages/eu/components/navigation/breadcrumb/docs/usage.md
Labels: netlify-cms/pending_publish

#2422 feat(EU Usage pages for components): update EU Usage pages for components “eu_news_ticker”
  src/website/src/pages/eu/components/news-ticker/docs/usage.md
Labels: netlify-cms/pending_publish

#2423 feat(EU Usage pages for components): update EU Usage pages for components “eu_news_ticker”
  src/website/src/pages/eu/components/news-ticker/docs/usage.md
Labels: netlify-cms/pending_publish

#2424 feat(EC Usage pages for components): update EC Usage pages for components “ec_list_illustration”
  src/website/src/pages/ec/components/list-illustration/docs/usage.md
Labels: netlify-cms/pending_publish

#2425 feat(EC Usage pages for components): update EC Usage pages for components “ec_news_ticker”
  src/website/src/pages/ec/components/news-ticker/docs/usage.md
Labels: netlify-cms/pending_publish

#2426 feat(EU Usage pages for components): update EU Usage pages for components “eu_list_illustration”
  src/website/src/pages/eu/components/list_illustration/docs/usage.md
Labels: netlify-cms/pending_publish

#2427 feat(EC Usage pages for components): update EC Usage pages for components “ec_list_illustration”
  src/website/src/pages/ec/components/list-illustration/docs/usage.md
Labels: netlify-cms/pending_publish

#2430 feat(EU Usage pages for components): update EU Usage pages for components “eu_tag”
  src/website/src/pages/eu/components/tag/docs/usage.md
Labels: netlify-cms/pending_publish

#2431 feat(EU Usage pages for components): update EU Usage pages for components “eu_search_form”
  src/website/src/pages/eu/components/forms/search-form/docs/usage.md
Labels: netlify-cms/pending_publish

#2432 feat(EU Usage pages for components): update EU Usage pages for components “eu_link”
  src/website/src/pages/eu/components/navigation/link/docs/usage.md
Labels: netlify-cms/pending_publish

#2433 feat(EU Usage pages for components): update EU Usage pages for components “eu_link”
  src/website/src/pages/eu/components/navigation/link/docs/usage.md
Labels: netlify-cms/pending_publish

#2434 feat(EU Usage pages for components): update EU Usage pages for components “eu_list”
  src/website/src/pages/eu/components/list/docs/usage.md
Labels: netlify-cms/pending_publish

#2435 feat(EC Usage pages for components): update EC Usage pages for components “ec_list”
  src/website/src/pages/ec/components/list/docs/usage.md
Labels: netlify-cms/pending_publish

#2436 feat(EC Usage pages for components): update EC Usage pages for components “ec_menu”
  src/website/src/pages/ec/components/navigation/menu/docs/usage.md
Labels: netlify-cms/pending_publish

#2437 feat(EU Usage pages for components): update EU Usage pages for components “eu_menu”
  src/website/src/pages/eu/components/navigation/menu/docs/usage.md
Labels: netlify-cms/pending_publish

#2438 feat(EC Usage pages for components): update EC Usage pages for components “ec_button”
  src/website/src/pages/ec/components/button/docs/usage.md
Labels: netlify-cms/pending_publish

#2439 feat(EU Usage pages for components): update EU Usage pages for components “eu_button”
  src/website/src/pages/eu/components/button/docs/usage.md
Labels: netlify-cms/pending_publish

#2440 fix(file): Fix website demo previews - FRONT-3620
  src/website/src/pages/ec/components/file/docs/code.mdx
  src/website/src/pages/eu/components/file/docs/code.mdx
Labels: tag: bug fix

#2441 chore: usage pages update
  src/website/public/admin/config.yml
  src/website/src/pages/ec/components/blockquote/docs/usage.md
  src/website/src/pages/ec/components/button/docs/usage.md
  src/website/src/pages/ec/components/expandable/docs/usage.md
  src/website/src/pages/ec/components/fact-figures/docs/usage.md
  src/website/src/pages/ec/components/forms/radio/docs/usage.md
  src/website/src/pages/ec/components/forms/search-form/docs/usage.md
  src/website/src/pages/ec/components/forms/select/docs/usage.md
  src/website/src/pages/ec/components/list-illustration/docs/usage.md
  src/website/src/pages/ec/components/list/docs/usage.md
  src/website/src/pages/ec/components/media/featured-item/docs/usage.md
  src/website/src/pages/ec/components/media/gallery/docs/usage.md
  src/website/src/pages/ec/components/message/docs/usage.md
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/usage.md
  src/website/src/pages/ec/components/navigation/link/docs/usage.md
  src/website/src/pages/ec/components/navigation/menu/docs/usage.md
  src/website/src/pages/ec/components/navigation/pagination/docs/usage.md
  src/website/src/pages/ec/components/site-wide/page-header/docs/usage.md
  src/website/src/pages/ec/components/site-wide/site-footer/docs/usage.md
  src/website/src/pages/ec/components/social-media-share/docs/usage.md
  src/website/src/pages/ec/components/spinner/docs/usage.md
  src/website/src/pages/ec/components/tag/docs/usage.md
  src/website/src/pages/ec/components/timeline/docs/usage.md
  src/website/src/pages/ec/core-template/page-header/docs/usage.md
  src/website/src/pages/ec/guidelines/typography/index.md
  src/website/src/pages/ec/resources/glossary/index.md
  src/website/src/pages/ec/standardised-template/footer/docs/usage.md
  src/website/src/pages/ec/standardised-template/page-header/docs/usage.md
  src/website/src/pages/eu/components/blockquote/docs/usage.md
  src/website/src/pages/eu/components/button/docs/usage.md
  src/website/src/pages/eu/components/expandable/docs/usage.md
  src/website/src/pages/eu/components/fact-figures/docs/usage.md
  src/website/src/pages/eu/components/forms/radio/docs/usage.md
  src/website/src/pages/eu/components/forms/search-form/docs/usage.md
  src/website/src/pages/eu/components/forms/select/docs/usage.md
  src/website/src/pages/eu/components/list-illustration/docs/usage.md
  src/website/src/pages/eu/components/list/docs/usage.md
  src/website/src/pages/eu/components/media/featured-item/docs/usage.md
  src/website/src/pages/eu/components/media/gallery/docs/usage.md
  src/website/src/pages/eu/components/message/docs/usage.md
  src/website/src/pages/eu/components/navigation/breadcrumb/docs/usage.md
  src/website/src/pages/eu/components/navigation/link/docs/usage.md
  src/website/src/pages/eu/components/navigation/menu/docs/usage.md
  src/website/src/pages/eu/components/navigation/pagination/docs/usage.md
  src/website/src/pages/eu/components/news-ticker/docs/usage.md
  src/website/src/pages/eu/components/site-wide/page-header/docs/usage.md
  src/website/src/pages/eu/components/site-wide/site-footer/docs/usage.md
  src/website/src/pages/eu/components/social-media-share/docs/usage.md
  src/website/src/pages/eu/components/spinner/docs/usage.md
  src/website/src/pages/eu/components/tag/docs/usage.md
  src/website/src/pages/eu/components/timeline/docs/usage.md
  src/website/src/pages/eu/core-template/footer/docs/usage.md
  src/website/src/pages/eu/core-template/page-header/docs/usage.md
  src/website/src/pages/eu/guidelines/typography/index.md
  src/website/src/pages/eu/harmonised-template/footer/docs/usage.md
  src/website/src/pages/eu/harmonised-template/page-header/docs/usage.md
  src/website/src/pages/eu/resources/glossary/index.md
Labels: tag: documentation

#2444 chore(deps): Updates 05-05-22
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2404 feat(banner): add coypright - FRONT-3616
  src/implementations/twig/components/carousel/__snapshots__/carousel.test.js.snap
  src/implementations/twig/components/hero-banner/README.md
  src/implementations/twig/components/hero-banner/__snapshots__/hero-banner.test.js.snap
  src/implementations/twig/components/hero-banner/hero-banner.html.twig
  src/implementations/twig/components/hero-banner/hero-banner.story.js
  src/implementations/twig/components/page-banner/README.md
  src/implementations/twig/components/page-banner/__snapshots__/page-banner.test.js.snap
  src/implementations/twig/components/page-banner/page-banner.html.twig
  src/implementations/twig/components/page-banner/page-banner.story.js
  src/implementations/vanilla/components/carousel/_carousel.scss
  src/implementations/vanilla/components/carousel/carousel-print.scss
  src/implementations/vanilla/components/hero-banner/_hero-banner.scss
  src/implementations/vanilla/components/hero-banner/hero-banner-ec.scss
  src/implementations/vanilla/components/hero-banner/hero-banner-eu.scss
  src/implementations/vanilla/components/hero-banner/hero-banner-print.scss
  src/implementations/vanilla/components/page-banner/_page-banner.scss
  src/implementations/vanilla/components/page-banner/page-banner-ec.scss
  src/implementations/vanilla/components/page-banner/page-banner-eu.scss
  src/implementations/vanilla/components/page-banner/page-banner-print.scss
  src/presets/rtl/src/rtl.scss
  src/specs/components/carousel/demo/data.js
  src/specs/components/hero-banner/demo/data--image-box.js
  src/specs/components/hero-banner/demo/data--image-gradient.js
  src/specs/components/hero-banner/demo/data--image-shade.js
  src/specs/components/page-banner/demo/data--image-box.js
  src/specs/components/page-banner/demo/data--image-gradient.js
  src/specs/components/page-banner/demo/data--image-shade.js
  src/website/src/pages/ec/components/banners/hero-banner/demo/index.js
  src/website/src/pages/ec/components/banners/hero-banner/docs/code.mdx
  src/website/src/pages/ec/components/banners/page-banner/demo/index.js
  src/website/src/pages/ec/components/banners/page-banner/docs/code.mdx
Labels: tag: new feature

#2408 fix(page-header): Fix metas RTL display - FRONT-3619
  src/implementations/vanilla/components/page-header/page-header-ec.scss
  src/implementations/vanilla/components/page-header/page-header-eu.scss
Labels: tag: bug fix, process: under review

#2445 chore(deps): Updates 10-05-22
  package.json
  src/implementations/vanilla/components/gallery/package.json
  src/implementations/vanilla/components/site-header-core/package.json
  src/implementations/vanilla/components/site-header-harmonised/package.json
  src/implementations/vanilla/components/site-header-standardised/package.json
  src/implementations/vanilla/components/site-header/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2443 feat(EU Usage pages for components): update EU Usage pages for components “eu_news_ticker”
  src/website/src/pages/eu/components/news-ticker/docs/usage.md
Labels: netlify-cms/pending_publish

#2347 feat(breadcrumb): add site-wide components - FRONT-3552
  src/implementations/twig/components/breadcrumb/.npmignore
  src/implementations/twig/components/breadcrumb/README.md
  src/implementations/twig/components/breadcrumb/__snapshots__/breadcrumb.test.js.snap
  src/implementations/twig/components/breadcrumb/breadcrumb.html.twig
  src/implementations/twig/components/breadcrumb/breadcrumb.test.js
  src/implementations/twig/components/breadcrumb/ec-breadcrumb.story.js
  src/implementations/twig/components/breadcrumb/eu-breadcrumb.story.js
  src/implementations/twig/components/breadcrumb/package.json
  src/implementations/twig/components/page-header/__snapshots__/page-header.test.js.snap
  src/implementations/twig/components/page-header/page-header.html.twig
  src/implementations/vanilla/components/breadcrumb/README.md
  src/implementations/vanilla/components/breadcrumb/_breadcrumb.scss
  src/implementations/vanilla/components/breadcrumb/breadcrumb-ec.scss
  src/implementations/vanilla/components/breadcrumb/breadcrumb-eu.scss
  src/implementations/vanilla/components/breadcrumb/breadcrumb-print.scss
  src/implementations/vanilla/components/breadcrumb/breadcrumb.js
  src/implementations/vanilla/components/breadcrumb/package.json
  src/implementations/vanilla/components/page-header/page-header-ec.scss
  src/implementations/vanilla/components/page-header/page-header-eu.scss
  src/presets/dev/src/dev.js
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/website/public/admin/config.yml
  src/website/src/pages/ec/components/navigation/breadcrumb/demo/core.js
  src/website/src/pages/ec/components/navigation/breadcrumb/demo/harmonised.js
  src/website/src/pages/ec/components/navigation/breadcrumb/demo/standardised.js
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/api.mdx
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/code.mdx
  src/website/src/pages/eu/components/navigation/breadcrumb/demo/core.js
  src/website/src/pages/eu/components/navigation/breadcrumb/demo/harmonised.js
  src/website/src/pages/eu/components/navigation/breadcrumb/demo/standardised.js
  src/website/src/pages/eu/components/navigation/breadcrumb/docs/api.mdx
  src/website/src/pages/eu/components/navigation/breadcrumb/docs/code.mdx
  yarn.lock
Labels: tag: new feature

#2453 feat(card): deprecate tile variant - FRONT-3611
  src/implementations/twig/components/card/README.md
  src/implementations/twig/components/card/__snapshots__/card.test.js.snap
  src/implementations/twig/components/card/card.html.twig
  src/implementations/twig/components/card/card.story.js
  src/implementations/twig/components/card/card.test.js
  src/implementations/vanilla/components/card/_card.scss
  src/specs/components/card/demo/data--tile.js
  src/website/src/pages/ec/components/card/demo/index.js
  src/website/src/pages/ec/components/card/docs/code.mdx
  src/website/src/pages/eu/components/card/demo/index.js
  src/website/src/pages/eu/components/card/docs/code.mdx
Labels: tag: enhancement

#2455 feat(EC Usage pages for components): update EC Usage pages for components “ec_category-filter”
  src/website/src/pages/ec/components/category-filter/docs/usage.md
Labels: netlify-cms/pending_publish

#2454 feat(EU Usage pages for components): update EU Usage pages for components “eu_news_ticker”
  src/website/src/pages/eu/components/news-ticker/docs/usage.md
Labels: netlify-cms/pending_publish

#2456 feat(EU Usage pages for components): update EU Usage pages for components “eu_category-filter”
  src/website/src/pages/eu/components/category-filter/docs/usage.md
Labels: netlify-cms/pending_publish

#2458 feat(EC Usage pages for components): update EC Usage pages for components “ec_tabs”
  src/website/src/pages/ec/components/navigation/tabs/docs/usage.md
Labels: netlify-cms/pending_publish

#2457 feat(EU Usage pages for components): update EU Usage pages for components “eu_tabs”
  src/website/src/pages/eu/components/navigation/tabs/docs/usage.md
Labels: netlify-cms/pending_publish

#2461 feat(EU Usage pages for components): update EU Usage pages for components “eu_card”
  src/website/src/pages/eu/components/card/docs/usage.md
Labels: netlify-cms/pending_publish

#2463 feat(EC Usage pages for components): update EC Usage pages for components “ec_navigation-list”
  src/website/public/admin/config.yml
  src/website/src/pages/ec/components/navigation/navigation-list/docs/usage.md
Labels: netlify-cms/pending_publish

#2460 feat(EU Usage pages for components): update EU Usage pages for components “eu_content-item”
  src/website/src/pages/eu/components/content-item/docs/usage.md
Labels: netlify-cms/pending_publish

#2466 feat(EC Usage pages for components): update EC Usage pages for components “ec_carousel”
  src/website/src/pages/ec/components/carousel/docs/usage.md
Labels: netlify-cms/pending_publish

#2478 chore(deps): Updates 13-05-22
  src/implementations/vanilla/components/gallery/package.json
  src/implementations/vanilla/components/site-header-core/package.json
  src/implementations/vanilla/components/site-header-harmonised/package.json
  src/implementations/vanilla/components/site-header-standardised/package.json
  src/implementations/vanilla/components/site-header/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2468 feat(navigation-list): Revamp using content-block component - FRONT-3607
  src/implementations/twig/components/navigation-list/README.md
  src/implementations/twig/components/navigation-list/__snapshots__/navigation-list.test.js.snap
  src/implementations/twig/components/navigation-list/navigation-list-item.html.twig
  src/implementations/twig/components/navigation-list/navigation-list.story.js
  src/implementations/twig/components/navigation-list/package.json
  src/implementations/vanilla/components/navigation-list/_navigation-list.scss
  src/implementations/vanilla/components/navigation-list/navigation-list-ec.scss
  src/implementations/vanilla/components/navigation-list/navigation-list-eu.scss
  src/implementations/vanilla/components/navigation-list/navigation-list-print.scss
  src/implementations/vanilla/components/navigation-list/package.json
  src/specs/components/navigation-list/demo/data.js
  src/specs/components/navigation-list/package.json
Labels: tag: enhancement

#2479 chore(deps): Updates 16-05-22
  package.json
  yarn.lock
Labels: tag: internal

#2482 feat(EC Usage pages for components): update EC Usage pages for components “ec_footer_core”
  src/website/src/pages/ec/core-template/footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2484 feat(EU Usage pages for components): update EU Usage pages for components “eu_file_upload”
  src/website/src/pages/eu/components/forms/file-upload/docs/usage.md
Labels: netlify-cms/pending_publish

#2469 feat(cards): refactor cards with content block - FRONT-3606
  src/implementations/twig/components/card/README.md
  src/implementations/twig/components/card/__snapshots__/card.test.js.snap
  src/implementations/twig/components/card/card.html.twig
  src/implementations/twig/components/card/card.story.js
  src/implementations/twig/components/card/card.test.js
  src/implementations/twig/components/card/package.json
  src/implementations/vanilla/components/card/_card.scss
  src/implementations/vanilla/components/card/card-ec.scss
  src/implementations/vanilla/components/card/card-eu.scss
  src/implementations/vanilla/components/card/card-print.scss
  src/implementations/vanilla/components/navigation-list/_navigation-list.scss
  src/implementations/vanilla/components/navigation-list/navigation-list-ec.scss
  src/implementations/vanilla/components/navigation-list/navigation-list-eu.scss
  src/specs/components/card/demo/data--card-event.js
  src/specs/components/card/demo/data--card-tag.js
  src/specs/components/card/demo/data--card.js
  src/specs/components/card/demo/data--tile-taxonomy.js
  src/specs/components/card/demo/data.js
  src/specs/components/card/demo/deprecated/data.js
  src/website/src/pages/ec/components/card/demo/index.js
  src/website/src/pages/ec/components/card/docs/code.mdx
  src/website/src/pages/eu/components/card/demo/index.js
  src/website/src/pages/eu/components/card/docs/code.mdx
Labels: tag: enhancement

#2490 feat(EU Usage pages for components): update EU Usage pages for components “eu_site_footer”
  cms-images/eu-footer-core.png
  cms-images/eu-footer-harmonised.png
  src/website/src/pages/eu/components/site-wide/site-footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2486 feat(EC Usage pages for components): update EC Usage pages for components “ec_site_header”
  cms-images/ec-page-header-core.png
  cms-images/ec-page-header-harmonised.png
  cms-images/ec-site-header-core.png
  cms-images/ec-site-header-harmonised.png
  cms-images/ec-site-header-standardised.png
  src/website/src/pages/ec/components/site-wide/site-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2485 feat(EC Usage pages for components): update EC Usage pages for components “ec_site_footer”
  cms-images/ec-footer-core.png
  cms-images/ec-footer-harmonised.png
  cms-images/ec-footer-standardised.png
  src/website/src/pages/ec/components/site-wide/site-footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2487 feat(EC Usage pages for components): update EC Usage pages for components “ec_page_header”
  src/website/src/pages/ec/components/site-wide/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2476 feat(Europa family for EU): update Europa family for EU “eu_core_template”
  cms-images/screenshot-2022-04-13-at-11.40.03.png
  src/website/src/pages/eu/core-template/index.md
Labels: netlify-cms/pending_publish

#2491 feat(EC Usage pages for components): update EC Usage pages for components “ec_footer_core”
  src/website/src/pages/ec/core-template/footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2473 feat(Europa family for EC): update Europa family for EC “ec_harmonised_template_g2”
  src/website/src/pages/ec/harmonised-templates/docs/group2.md
Labels: netlify-cms/pending_publish

#2495 feat(EC Usage pages for components): update EC Usage pages for components “ec_site_header_standardised”
  src/website/src/pages/ec/standardised-template/site-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2512 feat(EC Usage pages for components): update EC Usage pages for components “ec_footer_core”
  src/website/src/pages/ec/core-template/footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2511 feat(EU Usage pages for components): update EU Usage pages for components “eu_page_header”
  cms-images/eu-page-header-harmonised.png
  src/website/src/pages/eu/components/site-wide/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2510 feat(EU Usage pages for components): update EU Usage pages for components “eu_site_header_harmonised”
  src/website/src/pages/eu/harmonised-template/site-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2509 feat(EU Usage pages for components): update EU Usage pages for components “eu_page_header_harmonised”
  src/website/src/pages/eu/harmonised-template/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2508 feat(EU Usage pages for components): update EU Usage pages for components “eu_footer_harmonised”
  src/website/src/pages/eu/harmonised-template/footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2507 feat(EU Usage pages for components): update EU Usage pages for components “eu_site_header_core”
  src/website/src/pages/eu/core-template/site-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2505 feat(EU Usage pages for components): update EU Usage pages for components “eu_footer_core”
  src/website/src/pages/eu/core-template/footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2501 feat(EC Usage pages for components): update EC Usage pages for components “ec_page_header_harmonised_g2”
  src/website/src/pages/ec/harmonised-templates/page-header/docs/group2.md
Labels: netlify-cms/pending_publish

#2500 feat(EC Usage pages for components): update EC Usage pages for components “ec_page_header_harmonised_g1”
  src/website/src/pages/ec/harmonised-templates/page-header/docs/group1.md
Labels: netlify-cms/pending_publish

#2498 feat(EC Usage pages for components): update EC Usage pages for components “ec_site_header_harmonised_g1”
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group1.md
Labels: netlify-cms/pending_publish

#2497 feat(EC Usage pages for components): update EC Usage pages for components “ec_footer_harmonised_g2”
  src/website/src/pages/ec/harmonised-templates/footer/docs/group2.md
Labels: netlify-cms/pending_publish

#2496 feat(EC Usage pages for components): update EC Usage pages for components “ec_footer_harmonised_g1”
  src/website/src/pages/ec/harmonised-templates/footer/docs/group1.md
Labels: netlify-cms/pending_publish

#2475 feat(Europa family for EC): update Europa family for EC “ec_harmonised_template_g3”
  src/website/src/pages/ec/harmonised-templates/docs/group3.md
Labels: netlify-cms/pending_publish

#2514 feat(Europa family for EC): update Europa family for EC “ec_standardised_template”
  src/website/src/pages/ec/standardised-template/index.md
Labels: netlify-cms/pending_publish

#2515 feat(Europa family for EC): update Europa family for EC “ec_harmonised_template_g1”
  src/website/src/pages/ec/harmonised-templates/docs/group1.md
Labels: netlify-cms/pending_publish

#2513 feat(Europa family for EC): update Europa family for EC “ec_core_template”
  src/website/src/pages/ec/core-template/index.md
Labels: netlify-cms/draft

#2516 feat(Europa family for EC): update Europa family for EC “ec_harmonised_template_g2”
  src/website/src/pages/ec/harmonised-templates/docs/group2.md
Labels: netlify-cms/pending_publish

#2517 feat(Europa family for EC): update Europa family for EC “ec_harmonised_template_g3”
  src/website/src/pages/ec/harmonised-templates/docs/group3.md
Labels: netlify-cms/pending_publish

#2520 feat(EU Usage pages for components): update EU Usage pages for components “eu_page_header_harmonised”
  src/website/src/pages/eu/harmonised-template/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2522 feat(Europa family for EU): update Europa family for EU “eu_core_template”
  src/website/src/pages/eu/core-template/index.md
Labels: netlify-cms/pending_publish

#2521 feat(Europa family for EU): update Europa family for EU “eu_harmonised_template”
  src/website/src/pages/eu/harmonised-template/index.md
Labels: netlify-cms/pending_publish

#2525 feat(EC Usage pages for components): update EC Usage pages for components “ec_page_header_core”
  src/website/src/pages/ec/core-template/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2528 feat(EC Usage pages for components): update EC Usage pages for components “ec_footer_core”
  src/website/src/pages/ec/core-template/footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2527 feat(EC Usage pages for components): update EC Usage pages for components “ec_site_header_standardised”
  src/website/src/pages/ec/standardised-template/site-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2529 feat(EC Usage pages for components): update EC Usage pages for components “ec_footer_standardised”
  src/website/src/pages/ec/standardised-template/footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2530 feat(EC Usage pages for components): update EC Usage pages for components “ec_page_header_standardised”
  src/website/src/pages/ec/standardised-template/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2523 feat(Europa family for EC): update Europa family for EC “ec_harmonised_template_g1”
  src/website/src/pages/ec/harmonised-templates/docs/group1.md
Labels: netlify-cms/draft

#2533 feat(EC Usage pages for components): update EC Usage pages for components “ec_site_header_harmonised_g3”
  src/website/src/pages/ec/harmonised-templates/site-header/docs/group3.md
Labels: netlify-cms/draft

#2539 chore(storybook): Upgrade to 6.5.4
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-code/preset.js
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-notes/preset.js
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/addons/storybook-addon-system-switcher/preset.js
  src/playground/ec/.storybook/main.js
  src/playground/ec/.storybook/preview.js
  src/playground/ec/package.json
  src/playground/eu/.storybook/main.js
  src/playground/eu/.storybook/preview.js
  src/playground/eu/package.json
  src/resources/logo-ec/package.json
  src/resources/logo-eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2541 fix(content-block): remove meta uppercase - FRONT-3639
  src/implementations/vanilla/components/content-block/_content-block-print.scss
  src/implementations/vanilla/components/content-block/_content-block.scss
Labels: tag: bug fix

#2542 fix(card): allows simple title - FRONT-3627
  src/implementations/twig/components/card/README.md
  src/implementations/twig/components/card/card.html.twig
  src/implementations/twig/components/card/card.story.js
  src/implementations/twig/components/content-block/README.md
  src/implementations/twig/components/content-block/__snapshots__/content-block.test.js.snap
  src/implementations/twig/components/content-block/content-block.html.twig
  src/implementations/twig/components/content-block/content-block.story.js
  src/implementations/twig/components/content-block/content-block.test.js
  src/implementations/vanilla/components/content-block/_content-block-print.scss
  src/implementations/vanilla/components/content-block/_content-block.scss
  src/implementations/vanilla/components/content-block/content-block-ec.scss
  src/implementations/vanilla/components/content-block/content-block-eu.scss
  src/implementations/vanilla/components/content-block/content-block-print-ec.scss
  src/implementations/vanilla/components/content-block/content-block-print-eu.scss
  src/specs/components/card/demo/data.js
Labels: tag: bug fix

#2540 fix(carousel): Fix mobile copyright display - FRONT-3637
  src/implementations/vanilla/components/carousel/_carousel.scss
  src/implementations/vanilla/components/hero-banner/hero-banner-print.scss
  src/implementations/vanilla/components/page-banner/page-banner-print.scss
  src/presets/rtl/src/rtl.scss
Labels: tag: bug fix

#2546 fix(page header): add bottom margin - FRONT-3462
  src/implementations/vanilla/components/page-header/page-header-ec.scss
Labels: tag: bug fix, process: review needed

#2538 feat(EC Usage pages for components): update EC Usage pages for components “ec_carousel”
  src/website/src/pages/ec/components/carousel/docs/usage.md
Labels: netlify-cms/draft

#2537 feat(EU Usage pages for components): update EU Usage pages for components “eu_carousel”
  src/website/src/pages/eu/components/carousel/docs/usage.md
Labels: netlify-cms/draft

#2536 feat(EU Usage pages for components): update EU Usage pages for components “eu_content-item”
  src/website/src/pages/eu/components/content-item/docs/usage.md
Labels: netlify-cms/draft

#2535 feat(EC Usage pages for components): update EC Usage pages for components “ec_content-item”
  src/website/src/pages/ec/components/content-item/docs/usage.md
Labels: netlify-cms/draft

#2551 chore: Updates 30-05-22
  package.json
  src/implementations/vanilla/components/gallery/package.json
  src/implementations/vanilla/components/site-header-core/package.json
  src/implementations/vanilla/components/site-header-harmonised/package.json
  src/implementations/vanilla/components/site-header-standardised/package.json
  src/implementations/vanilla/components/site-header/package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2534 fix(news-ticker): Fix accessibility issues - FRONT-3634
  src/implementations/twig/components/news-ticker/__snapshots__/news-ticker.test.js.snap
  src/implementations/twig/components/news-ticker/news-ticker.html.twig
  src/implementations/vanilla/components/news-ticker/_news-ticker.scss
  src/implementations/vanilla/components/news-ticker/news-ticker.js
Labels: tag: enhancement, process: under review
