Repository ec-europa/europa-component-library, pull requests merged in 2022-09, with the labels that each got.

#2635 feat(content-block): Reducing font size for the title in EU - FRONT-3737
  src/implementations/vanilla/components/content-block/content-block-eu.scss
Labels: tag: enhancement

#2636 feat(logos): Adding Swahili logos for EU - FRONT-3738
  src/resources/logo-eu/src/condensed-version/negative/logo-eu--sw.svg
  src/resources/logo-eu/src/condensed-version/positive/logo-eu--sw.svg
  src/resources/logo-eu/src/standard-version/negative/logo-eu--sw.svg
  src/resources/logo-eu/src/standard-version/positive/logo-eu--sw.svg
Labels: tag: new feature

#2638 chore(deps): Updates 02-09-22
  package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2627 fix(print): Fix components print version - FRONT-3731
  src/implementations/vanilla/components/blockquote/_blockquote-print.scss
  src/implementations/vanilla/components/carousel/carousel-print.scss
  src/implementations/vanilla/components/description-list/_description-list-print.scss
  src/implementations/vanilla/components/language-list/language-list-print.scss
  src/implementations/vanilla/components/link/_link-print.scss
  src/implementations/vanilla/components/link/_link.scss
  src/implementations/vanilla/components/media-container/media-container-print.scss
  src/implementations/vanilla/components/site-header/site-header-print.scss
  src/implementations/vanilla/components/table/table-print.scss
Labels: tag: enhancement, process: under review

#2639 fix(gallery): Fix AV Portal video overlay display - FRONT-3741
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/vanilla/components/gallery/_gallery.scss
  src/specs/components/gallery/demo/data.js
Labels: tag: bug fix

#2640 chore(deps): Updates 12-09-22
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2641 fix(carousel): allow click on cta - FRONT-3747
  src/implementations/vanilla/components/carousel/carousel.js
Labels: tag: bug fix

#2642 chore(deps): Storybook 6.5.11
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2643 chore(deps): Storybook 6.5.12
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2646 chore(deps): Updates and audit fix
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2645 feat(content-block): Merging extra_classes for lists - FRONT-3751
  src/implementations/twig/components/content-block/__snapshots__/content-block.test.js.snap
  src/implementations/twig/components/content-block/content-block.html.twig
  src/implementations/twig/components/content-block/content-block.test.js
Labels: tag: enhancement, process: review needed

#2644 fix(social-media): Fixing and aligning variant selectors - FRONT-3749
  src/implementations/twig/components/social-media-follow/social-media-follow.html.twig
  src/implementations/twig/components/social-media-share/__snapshots__/social-media-share.test.js.snap
  src/implementations/twig/components/social-media-share/social-media-share.html.twig
Labels: tag: bug fix, process: review needed

#2615 feat(popover): add component - FRONT-3698
  .size-limit.json
  src/implementations/twig/components/popover/.npmignore
  src/implementations/twig/components/popover/README.md
  src/implementations/twig/components/popover/__snapshots__/popover.test.js.snap
  src/implementations/twig/components/popover/package.json
  src/implementations/twig/components/popover/popover.html.twig
  src/implementations/twig/components/popover/popover.story.js
  src/implementations/twig/components/popover/popover.test.js
  src/implementations/vanilla/components/popover/README.md
  src/implementations/vanilla/components/popover/_popover.scss
  src/implementations/vanilla/components/popover/package.json
  src/implementations/vanilla/components/popover/popover-ec.scss
  src/implementations/vanilla/components/popover/popover-eu.scss
  src/implementations/vanilla/components/popover/popover-print.scss
  src/implementations/vanilla/components/popover/popover.js
  src/presets/dev/package.json
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/specs/components/popover/demo/data.js
  src/specs/components/popover/package.json
  src/website/public/admin/config.yml
  src/website/src/pages/ec/components/index.mdx
  src/website/src/pages/ec/components/popover/demo/index.js
  src/website/src/pages/ec/components/popover/docs/api.mdx
  src/website/src/pages/ec/components/popover/docs/code.mdx
  src/website/src/pages/ec/components/popover/docs/usage.md
  src/website/src/pages/ec/components/popover/ec_comp_popover.svg
  src/website/src/pages/ec/components/popover/index.md
  src/website/src/pages/eu/components/index.mdx
  src/website/src/pages/eu/components/popover/demo/index.js
  src/website/src/pages/eu/components/popover/docs/api.mdx
  src/website/src/pages/eu/components/popover/docs/code.mdx
  src/website/src/pages/eu/components/popover/docs/usage.md
  src/website/src/pages/eu/components/popover/eu_comp_popover.svg
  src/website/src/pages/eu/components/popover/index.md
Labels: tag: new feature

#2649 docs(website): update webtools documentation - FRONT-3742
  src/website/src/pages/ec/resources/webtools/index.md
  src/website/src/pages/eu/resources/webtools/index.md
Labels: tag: documentation

#2651 chore(deps): Updates 23-09-22
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2654 chore(deps): Updates 29-09-22
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal
