Repository ec-europa/europa-component-library, pull requests merged in 2022-08, with the labels that each got.

#2603 chore(deps): Updates - 01-08-22
  package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2601 feat(menu): Revamp navigation and styles - FRONT-3697
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/menu-item.html.twig
  src/implementations/twig/components/menu/menu.html.twig
  src/implementations/twig/deprecated/site-header-core/__snapshots__/site-header-core.test.js.snap
  src/implementations/twig/deprecated/site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/implementations/twig/deprecated/site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/implementations/vanilla/components/menu/_menu.scss
  src/implementations/vanilla/components/menu/menu-ec.scss
  src/implementations/vanilla/components/menu/menu-eu.scss
  src/implementations/vanilla/components/menu/menu.js
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  yarn.lock
Labels: tag: enhancement

#2607 feat(EC Deprecated): update EC Deprecated “ec_deprecated_index”
  src/website/src/pages/ec/deprecated/index.md
Labels: netlify-cms/pending_publish

#2608 chore: Updates 08-08-22
  package.json
  src/implementations/twig/components/rating-field/package.json
  src/implementations/vanilla/components/menu/_menu.scss
  src/implementations/vanilla/components/rating-field/package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2614 chore(deps): Updates 17-08-22
  package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2612 fix(EU-footer): Changing the url for a link - FRONT-3721
  src/implementations/twig/components/site-footer/__snapshots__/site-footer.test.js.snap
  src/specs/components/site-footer/demo/data-core--eu.js
  src/specs/components/site-footer/demo/data-harmonised--eu.js
Labels: tag: internal, process: review needed

#2616 feat(tabs): Adding accessibility test - FRONT-3722
  src/implementations/twig/components/tabs/__snapshots__/tabs.test.js.snap
  src/implementations/twig/components/tabs/tabs.html.twig
  src/implementations/twig/components/tabs/tabs.test.js
Labels: tag: enhancement, process: review needed

#2620 chore(js): Updating focus-trap
  src/implementations/vanilla/components/gallery/package.json
  src/implementations/vanilla/components/site-header-core/package.json
  src/implementations/vanilla/components/site-header-harmonised/package.json
  src/implementations/vanilla/components/site-header-standardised/package.json
  src/implementations/vanilla/components/site-header/package.json
  yarn.lock
Labels: tag: internal

#2622 chore(deps): Updates 22-08-22
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2611 feat(links): Fixing display of links as buttons - FRONT-3713
  src/implementations/vanilla/components/link/_link.scss
Labels: tag: bug fix

#2619 fix(date-block): Fixing css classes - FRONT-3728
  src/implementations/twig/components/content-item/__snapshots__/content-item.test.js.snap
  src/implementations/twig/components/date-block/date-block.html.twig
  src/specs/components/content-item/demo/data--event.js
Labels: tag: bug fix

#2618 fix(date-block): Fixing template - FRONT-3727
  src/implementations/twig/components/date-block/date-block.html.twig
Labels: tag: bug fix

#2617 feat(content-block): Title supports link named object - FRONT-3726
  src/implementations/twig/components/content-block/__snapshots__/content-block.test.js.snap
  src/implementations/twig/components/content-block/content-block.html.twig
  src/implementations/twig/components/content-block/content-block.test.js
  src/specs/components/card/demo/data.js
  src/specs/components/card/demo/deprecated/data.js
  src/specs/components/content-block/demo/data.js
  src/specs/components/content-item/demo/data--default.js
  src/specs/components/content-item/demo/data--event.js
  src/specs/components/content-item/demo/data--image.js
  src/specs/components/navigation-list/demo/data.js
Labels: tag: enhancement

#2623 fix(carousel): Force navigation and pagination initialization - FRONT-3707
  src/implementations/vanilla/components/carousel/carousel.js
Labels: tag: bug fix

#2624 fix(rating-field): Fix focus for safari - FRONT-3706
  src/implementations/vanilla/components/rating-field/_rating-field.scss
Labels: tag: enhancement

#2628 feat(Docs): update Docs “eu_index”
  src/website/src/pages/eu/index.md
Labels: netlify-cms/pending_publish

#2613 fix(description-list): Aligning expected data for the taxonomy links use case - FRONT-3724
  src/implementations/twig/components/description-list/__snapshots__/descrption-list.test.js.snap
  src/implementations/twig/components/description-list/description-list.html.twig
  src/implementations/twig/components/description-list/descrption-list.test.js
  src/specs/components/description-list/demo/data--default.js
  src/specs/components/description-list/demo/data--horizontal.js
Labels: tag: enhancement

#2626 feat(logos): Add EC logo for SW - FRONT-3683
  src/resources/logo-ec/src/negative/logo-ec--is.svg
  src/resources/logo-ec/src/negative/logo-ec--jp.svg
  src/resources/logo-ec/src/negative/logo-ec--lb.svg
  src/resources/logo-ec/src/negative/logo-ec--ru.svg
  src/resources/logo-ec/src/negative/logo-ec--sw.svg
  src/resources/logo-ec/src/negative/logo-ec--tr.svg
  src/resources/logo-ec/src/negative/logo-ec--uk.svg
  src/resources/logo-ec/src/negative/logo-ec--zh.svg
  src/resources/logo-ec/src/positive/logo-ec--sw.svg
Labels: tag: enhancement

#2630 feat(content-block): Supporting simple strings in a list of links - FRONT-3711
  src/implementations/twig/components/content-block/content-block.html.twig
  src/implementations/twig/components/navigation-list/__snapshots__/navigation-list.test.js.snap
  src/implementations/vanilla/components/content-block/_content-block.scss
  src/specs/components/navigation-list/demo/data.js
Labels: tag: enhancement, process: under review

#2610 fix(inpage-navigation): fix z-index - FRONT-3708
  src/implementations/vanilla/components/site-header-core/site-header-core-ec.scss
  src/implementations/vanilla/components/site-header-core/site-header-core-eu.scss
  src/implementations/vanilla/components/site-header-harmonised/site-header-harmonised-ec.scss
  src/implementations/vanilla/components/site-header-harmonised/site-header-harmonised-eu.scss
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised-ec.scss
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised-eu.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
Labels: tag: bug fix

#2634 chore(deps): Updates 29-08-22
  package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal, process: review needed

#2629 feat(list-illustration): hardcoding the icon size in the template - FRONT-3734
  src/implementations/twig/components/list-illustration/list-illustration-item.html.twig
  src/specs/components/list-illustration/demo/data--icon.js
Labels: tag: enhancement

#2631 feat(featured-item): Supporting item without media - FRONT-3718
  src/implementations/twig/components/featured-item/__snapshots__/featured-item.test.js.snap
  src/implementations/twig/components/featured-item/featured-item.html.twig
  src/implementations/twig/components/featured-item/featured-item.story.js
  src/implementations/twig/components/featured-item/featured-item.test.js
  src/implementations/vanilla/components/featured-item/_featured-item.scss
Labels: tag: enhancement, process: under review
