Repository ec-europa/europa-component-library, pull requests merged in 2022-11, with the labels that each got.

#2677 fix(select multi): fix counter when resetting form
  src/implementations/vanilla/components/select/select.js
Labels: tag: bug fix

#2680 fix(multiselect): Fixing labels when searching - FRONT-3793
  .size-limit.json
  src/implementations/vanilla/components/select/select.js
Labels: tag: bug fix, process: review needed

#2681 chore(deps): updates 07-11-22
  package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2683 feat(icons): Adding email icons - FRONT-3771
  src/implementations/twig/components/icon/__snapshots__/icon.test.js.snap
  src/resources/icons-ec/src/all/email.svg
  src/resources/icons-eu/src/all/email.svg
  src/resources/icons-social-media/src/social-media/email-color.svg
  src/resources/icons-social-media/src/social-media/email-negative.svg
  src/resources/icons-social-media/src/social-media/email.svg
Labels: tag: new feature, process: review needed

#2691 fix(featured-item): fix demo on website - FRONT-3806
  src/website/src/pages/ec/components/media/featured-item/demo/index.js
Labels: tag: bug fix

#2685 feat(menu): update display - FRONT-3791
  src/implementations/vanilla/components/menu/_menu.scss
  src/implementations/vanilla/components/menu/menu-ec.scss
  src/implementations/vanilla/components/menu/menu-eu.scss
Labels: tag: enhancement

#2682 fix(storybook): Resetting static dirs when building - FRONT-3789
  src/playground/ec/.storybook/main.js
  src/playground/eu/.storybook/main.js
Labels: tag: internal, process: review needed

#2694 chore(deps): Updates 22-11-22
  package.json
  src/implementations/vanilla/components/gallery/package.json
  src/implementations/vanilla/components/site-header-core/package.json
  src/implementations/vanilla/components/site-header-harmonised/package.json
  src/implementations/vanilla/components/site-header-standardised/package.json
  src/implementations/vanilla/components/site-header/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2670 feat(media-container): use fluid ratio - FRONT-3776
  .size-limit.json
  src/implementations/twig/components/media-container/__snapshots__/media-container.test.js.snap
  src/implementations/twig/components/media-container/media-container.html.twig
  src/implementations/twig/components/media-container/media-container.story.js
  src/implementations/vanilla/components/media-container/_media-container.scss
  src/implementations/vanilla/components/media-container/media-container.js
  src/implementations/vanilla/components/media-container/package.json
  src/presets/dev/src/dev.js
  src/specs/components/media-container/demo/data--embed-video.js
  src/website/src/pages/ec/components/media/media-container/docs/code.mdx
  src/website/src/pages/eu/components/media/media-container/docs/code.mdx
Labels: tag: new feature

#2686 feat(range): add Range component - FRONT-3756
  src/implementations/twig/components/range/.npmignore
  src/implementations/twig/components/range/README.md
  src/implementations/twig/components/range/__snapshots__/range.test.js.snap
  src/implementations/twig/components/range/package.json
  src/implementations/twig/components/range/range.html.twig
  src/implementations/twig/components/range/range.story.js
  src/implementations/twig/components/range/range.test.js
  src/implementations/vanilla/components/range/README.md
  src/implementations/vanilla/components/range/_range.scss
  src/implementations/vanilla/components/range/package.json
  src/implementations/vanilla/components/range/range-ec.scss
  src/implementations/vanilla/components/range/range-eu.scss
  src/implementations/vanilla/components/range/range-print.scss
  src/implementations/vanilla/components/range/range.js
  src/playground/addons/story-utils/index.js
  src/presets/dev/package.json
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/specs/components/range/demo/data.js
  src/specs/components/range/package.json
  src/tools/builder/builder.test.js
  src/tools/builder/package.json
  src/tools/builder/scripts/styles.js
  src/website/public/admin/config.yml
  src/website/src/pages/ec/components/forms/range/demo/index.js
  src/website/src/pages/ec/components/forms/range/docs/api.mdx
  src/website/src/pages/ec/components/forms/range/docs/code.mdx
  src/website/src/pages/ec/components/forms/range/docs/usage.md
  src/website/src/pages/ec/components/forms/range/ec_comp_range.svg
  src/website/src/pages/ec/components/forms/range/index.md
  src/website/src/pages/ec/components/index.mdx
  src/website/src/pages/eu/components/forms/range/demo/index.js
  src/website/src/pages/eu/components/forms/range/docs/api.mdx
  src/website/src/pages/eu/components/forms/range/docs/code.mdx
  src/website/src/pages/eu/components/forms/range/docs/usage.md
  src/website/src/pages/eu/components/forms/range/eu_comp_range.svg
  src/website/src/pages/eu/components/forms/range/index.md
  src/website/src/pages/eu/components/index.mdx
  yarn.lock
Labels: tag: new feature

#2696 feat(file): Removing download attribute - FRONT-3808
  src/implementations/twig/components/file/__snapshots__/file.test.js.snap
  src/implementations/twig/components/file/file.html.twig
Labels: tag: enhancement, process: review needed

#2687 fix(rating field): use dynamic id and name - FRONT-3796
  src/implementations/twig/components/rating-field/README.md
  src/implementations/twig/components/rating-field/__snapshots__/rating-field.test.js.snap
  src/implementations/twig/components/rating-field/rating-field.html.twig
  src/specs/components/rating-field/demo/data.js
Labels: tag: enhancement

#2695 feat(inpage navigation): update design - FRONT-3805
  src/implementations/vanilla/components/inpage-navigation/_inpage-navigation.scss
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation-ec.scss
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation-eu.scss
Labels: tag: enhancement

#2698 feat(category-filter): update display - FRONT-3804
  src/implementations/vanilla/components/category-filter/_category-filter.scss
  src/implementations/vanilla/components/category-filter/category-filter-ec.scss
  src/implementations/vanilla/components/category-filter/category-filter-eu.scss
Labels: tag: enhancement, process: business approval needed

#2699 feat(rating-field): add read only
  src/implementations/twig/components/rating-field/rating-field.html.twig
  src/implementations/twig/components/rating-field/rating-field.story.js
  src/implementations/vanilla/components/rating-field/_rating-field.scss
  src/playground/addons/story-utils/index.js
  src/website/src/pages/ec/components/forms/rating-field/demo/index.js
  src/website/src/pages/ec/components/forms/rating-field/docs/code.mdx
  src/website/src/pages/eu/components/forms/rating-field/demo/index.js
  src/website/src/pages/eu/components/forms/rating-field/docs/code.mdx
Labels: tag: enhancement

#2701 feat(checkbox/radio): update focus display - FRONT-3800
  src/implementations/vanilla/components/checkbox/_checkbox.scss
  src/implementations/vanilla/components/checkbox/checkbox-ec.scss
  src/implementations/vanilla/components/checkbox/checkbox-eu.scss
  src/implementations/vanilla/components/radio/_radio.scss
  src/implementations/vanilla/components/radio/radio-ec.scss
  src/implementations/vanilla/components/radio/radio-eu.scss
Labels: tag: enhancement
