Repository ec-europa/europa-component-library, pull requests merged in 2022-07, with the labels that each got.

#2580 chore(deps): Updates 04-07-22
  package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2584 feat(icons): add reddit icons
  src/resources/icons-social-media/src/social-media/reddit-color.svg
  src/resources/icons-social-media/src/social-media/reddit-negative.svg
  src/resources/icons-social-media/src/social-media/reddit.svg
Labels: tag: enhancement

#2585 feat(social-media-follow): Revamp - FRONT-3679
  src/implementations/twig/components/social-media-follow/__snapshots__/social-media-follow.test.js.snap
  src/implementations/twig/components/social-media-follow/social-media-follow.story.js
  src/implementations/vanilla/components/social-media-follow/_social-media-follow.scss
  src/implementations/vanilla/components/social-media-follow/social-media-follow-ec.scss
  src/implementations/vanilla/components/social-media-follow/social-media-follow-eu.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/specs/components/social-media-follow/demo/data.js
  src/website/src/styles/markdown.scss
  src/website/src/utils/correctSvgPath.js
Labels: tag: enhancement

#2582 feat(list-illustrations): Reviewing spacing - FRONT-3681
  src/implementations/twig/components/list-illustration/__snapshots__/list-illustration.test.js.snap
  src/implementations/twig/components/list-illustration/list-illustration.story.js
  src/implementations/vanilla/components/list-illustration/_list-illustration.scss
  src/specs/components/list-illustration/demo/data--icon.js
Labels: tag: enhancement

#2581 feat(language-list): Revamp - FRONT-3678
  src/implementations/twig/components/language-list/__snapshots__/language-list.test.js.snap
  src/implementations/twig/components/language-list/language-list-grid.html.twig
  src/implementations/twig/components/language-list/language-list.html.twig
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/deprecated/site-header-core/__snapshots__/site-header-core.test.js.snap
  src/implementations/twig/deprecated/site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/implementations/twig/deprecated/site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/implementations/vanilla/components/language-list/_language-list.scss
  src/implementations/vanilla/components/language-list/language-list-ec.scss
  src/implementations/vanilla/components/language-list/language-list-eu.scss
  src/specs/components/language-list/demo/data--overlay.js
  src/specs/components/language-list/demo/data--splash.js
Labels: tag: enhancement

#2594 fix(link): Fix content display around link with icons - FRONT-3694
  src/implementations/vanilla/components/link/_link.scss
Labels: tag: bug fix

#2586 feat(social-media-share): Revamp - FRONT-3680
  src/implementations/twig/components/social-media-share/__snapshots__/social-media-share.test.js.snap
  src/implementations/twig/components/social-media-share/social-media-share.html.twig
  src/implementations/twig/components/social-media-share/social-media-share.story.js
  src/implementations/vanilla/components/social-media-share/_social-media-share.scss
  src/implementations/vanilla/components/social-media-share/social-media-share-ec.scss
  src/implementations/vanilla/components/social-media-share/social-media-share-eu.scss
  src/implementations/vanilla/components/social-media-share/social-media-share.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/specs/components/social-media-share/demo/data.js
  src/website/src/pages/ec/components/social-media-share/demo/index.js
  src/website/src/pages/ec/components/social-media-share/docs/code.mdx
  src/website/src/pages/ec/components/social-media-share/index.md
  src/website/src/pages/eu/components/social-media-share/demo/index.js
  src/website/src/pages/eu/components/social-media-share/docs/code.mdx
  src/website/src/pages/eu/components/social-media-share/index.md
Labels: tag: enhancement

#2552 feat(rating-field): Add component - FRONT-3543
  src/implementations/twig/components/icon/__snapshots__/icon.test.js.snap
  src/implementations/twig/components/rating-field/.npmignore
  src/implementations/twig/components/rating-field/README.md
  src/implementations/twig/components/rating-field/__snapshots__/rating-field.test.js.snap
  src/implementations/twig/components/rating-field/package.json
  src/implementations/twig/components/rating-field/rating-field.html.twig
  src/implementations/twig/components/rating-field/rating-field.story.js
  src/implementations/twig/components/rating-field/rating-field.test.js
  src/implementations/vanilla/components/rating-field/README.md
  src/implementations/vanilla/components/rating-field/_rating-field-ec.scss
  src/implementations/vanilla/components/rating-field/_rating-field-eu.scss
  src/implementations/vanilla/components/rating-field/_rating-field-print.scss
  src/implementations/vanilla/components/rating-field/_rating-field.scss
  src/implementations/vanilla/components/rating-field/package.json
  src/presets/dev/src/dev.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/resources/icons-ec/src/all/star-filled.svg
  src/resources/icons-ec/src/all/star-outline.svg
  src/resources/icons-eu/src/all/star-filled.svg
  src/resources/icons-eu/src/all/star-outline.svg
  src/specs/components/rating-field/demo/data.js
  src/specs/components/rating-field/package.json
  src/website/public/admin/config.yml
  src/website/src/pages/ec/components/forms/rating-field/demo/index.js
  src/website/src/pages/ec/components/forms/rating-field/docs/code.mdx
  src/website/src/pages/ec/components/forms/rating-field/docs/usage.md
  src/website/src/pages/ec/components/forms/rating-field/ec_comp_rating_field.svg
  src/website/src/pages/ec/components/forms/rating-field/index.md
  src/website/src/pages/ec/components/index.mdx
  src/website/src/pages/eu/components/forms/rating-field/demo/index.js
  src/website/src/pages/eu/components/forms/rating-field/docs/code.mdx
  src/website/src/pages/eu/components/forms/rating-field/docs/usage.md
  src/website/src/pages/eu/components/forms/rating-field/eu_comp_rating_field.svg
  src/website/src/pages/eu/components/forms/rating-field/index.md
  src/website/src/pages/eu/components/index.mdx
  yarn.lock
Labels: tag: new feature, process: business approval needed

#2576 fix(tabs): Improve accessibility - FRONT-3661
  src/implementations/twig/components/tabs/__snapshots__/tabs.test.js.snap
  src/implementations/twig/components/tabs/tabs.html.twig
  src/implementations/vanilla/components/tabs/tabs.js
Labels: tag: enhancement

#2593 feat(multiselect): Keyboard navigation with arrows - FRONT-3690
  src/implementations/vanilla/components/select/select.js
Labels: tag: enhancement

#2598 fix(icon): Removing default, unneded but harmful transformation - FRONT-3702
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/deprecated/site-header-core/__snapshots__/site-header-core.test.js.snap
  src/implementations/twig/deprecated/site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/implementations/vanilla/components/icon/_icon.scss
  src/specs/components/menu/demo/data--en.js
  src/specs/components/menu/demo/data--fr.js
Labels: tag: bug fix, process: under review

#2599 chore(deps): Updates 18-07-22
  package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2597 fix(table): Fix focus for table sort arrows - FRONT-3693
  src/implementations/vanilla/components/table/_table.scss
  src/implementations/vanilla/components/table/table-ec.scss
  src/implementations/vanilla/components/table/table-eu.scss
  src/implementations/vanilla/components/table/table.js
  src/playground/eu/.storybook/preview-head.html
Labels: tag: bug fix

#2591 fix(file-upload): Fix focus styles for the browse button - FRONT-3689
  src/implementations/twig/components/file-upload/__snapshots__/file-upload.test.js.snap
  src/implementations/twig/components/file-upload/file-upload.html.twig
  src/implementations/vanilla/components/file-upload/_file-upload.scss
  src/implementations/vanilla/components/file-upload/file-upload-ec.scss
  src/implementations/vanilla/components/file-upload/file-upload-eu.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
Labels: tag: bug fix

#2596 fix(gallery): Fix focus style on gallery items - FRONT-3691
  src/implementations/vanilla/components/gallery/_gallery.scss
Labels: tag: enhancement

#2587 feat(focus): Use focus-visible for all components - FRONT-3684
  src/implementations/vanilla/components/accordion/accordion-ec.scss
  src/implementations/vanilla/components/accordion/accordion-eu.scss
  src/implementations/vanilla/components/breadcrumb/_breadcrumb.scss
  src/implementations/vanilla/components/button/_button.scss
  src/implementations/vanilla/components/carousel/_carousel.scss
  src/implementations/vanilla/components/category-filter/_category-filter.scss
  src/implementations/vanilla/components/category-filter/category-filter.js
  src/implementations/vanilla/components/checkbox/_checkbox.scss
  src/implementations/vanilla/components/datepicker/_datepicker.scss
  src/implementations/vanilla/components/file-upload/_file-upload.scss
  src/implementations/vanilla/components/gallery/_gallery.scss
  src/implementations/vanilla/components/inpage-navigation/_inpage-navigation.scss
  src/implementations/vanilla/components/link/_link.scss
  src/implementations/vanilla/components/menu/_menu.scss
  src/implementations/vanilla/components/news-ticker/_news-ticker.scss
  src/implementations/vanilla/components/radio/_radio.scss
  src/implementations/vanilla/components/search-form/_search-form.scss
  src/implementations/vanilla/components/select/_select.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/implementations/vanilla/components/skip-link/skip-link.scss
  src/implementations/vanilla/components/tabs/_tabs.scss
  src/implementations/vanilla/components/text-area/_text-area.scss
  src/implementations/vanilla/components/text-input/_text-input.scss
Labels: tag: enhancement
