Repository ec-europa/europa-component-library, pull requests merged in 2022-12, with the labels that each got.

#2706 chore(deps): Updates 06-12-22
  package.json
  src/implementations/vanilla/components/gallery/package.json
  src/implementations/vanilla/components/site-header-core/package.json
  src/implementations/vanilla/components/site-header-harmonised/package.json
  src/implementations/vanilla/components/site-header-standardised/package.json
  src/implementations/vanilla/components/site-header/package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2653 feat(table): add parameter for enhanced mobile - FRONT-3754
  src/implementations/twig/components/table/README.md
  src/implementations/twig/components/table/__snapshots__/table.test.js.snap
  src/implementations/twig/components/table/table.html.twig
  src/implementations/twig/components/table/table.story.js
  src/implementations/twig/components/table/table.test.js
  src/implementations/vanilla/components/table/_table.scss
  src/website/src/pages/ec/components/table/docs/code.mdx
  src/website/src/pages/eu/components/table/docs/code.mdx
  src/website/src/website-components/Playground.jsx
  src/website/src/website-components/Showcase/Iframe.jsx
Labels: tag: enhancement

#2713 chore(deps): Small updates and audit fix
  package.json
  src/playground/addons/storybook-addon-notes/package.json
  yarn.lock
Labels: tag: internal

#2705 feat(icon): add laco icon - FRONT-3818
  src/implementations/twig/components/icon/__snapshots__/icon.test.js.snap
  src/resources/icons-ec/src/all/laco-filled.svg
  src/resources/icons-ec/src/all/laco.svg
  src/resources/icons-eu/src/all/laco-filled.svg
  src/resources/icons-eu/src/all/laco.svg
Labels: tag: new feature

#2710 feat(icon): add basket icon - FRONT-3783
  src/implementations/twig/components/icon/__snapshots__/icon.test.js.snap
  src/resources/icons-ec/src/all/basket.svg
  src/resources/icons-eu/src/all/basket.svg
Labels: tag: new feature

#2707 chore(changelog): Adding markup changes category
  lerna.json
Labels: tag: internal

#2704 fix(select): fix multi-select with long labels - FRONT-3817
  src/implementations/twig/components/select/__snapshots__/select.test.js.snap
  src/implementations/vanilla/components/select/select.js
  src/specs/components/select/demo/data-multiple.js
Labels: tag: bug fix, tag: markup changes

#2711 feat(icon): update file and edit icons - FRONT-3820
  src/resources/icons-ec/src/all/edit.svg
  src/resources/icons-ec/src/all/file.svg
Labels: tag: enhancement

#2709 feat(menu): improve keyboard navigation - FRONT-3798
  src/implementations/vanilla/components/menu/_menu.scss
  src/implementations/vanilla/components/menu/menu.js
Labels: tag: enhancement

#2714 feat(spinner): fix center alignment - FRONT-3821
  src/implementations/vanilla/components/spinner/_spinner.scss
Labels: tag: bug fix

#2719 fix(presets): Adding reset and rtl css to EC and EU presets - FRONT-3822
  src/presets/ec/ecl-builder.config.js
  src/presets/ec/package.json
  src/presets/eu/ecl-builder.config.js
  src/presets/eu/package.json
Labels: tag: bug fix

#2724 feat(EU Usage pages for components): update EU Usage pages for components “eu_rating_field”
  src/website/src/pages/eu/components/forms/rating-field/docs/usage.md
Labels: netlify-cms/pending_publish

#2723 feat(EU Usage pages for components): update EU Usage pages for components “eu_range”
  src/website/src/pages/eu/components/forms/range/docs/usage.md
Labels: netlify-cms/pending_publish

#2721 feat(EC Usage pages for components): update EC Usage pages for components “ec_rating_field”
  src/website/src/pages/ec/components/forms/rating-field/docs/usage.md
Labels: netlify-cms/pending_publish

#2722 feat(EC Usage pages for components): update EC Usage pages for components “ec_range”
  src/website/src/pages/ec/components/forms/range/docs/usage.md
Labels: netlify-cms/pending_publish
