Repository ec-europa/europa-component-library, pull requests merged in 2022-01, with the labels that each got.

#2289 fix(file): Review component spacings - FRONT-3424
  src/implementations/vanilla/components/file/_file.scss
  src/implementations/vanilla/components/file/file-ec.scss
  src/implementations/vanilla/components/file/file-eu.scss
Labels: tag: enhancement, process: under review

#2296 feat(stories): Third batch - FRONT-3514
  .eslintrc.js
  babel.config.js
  src/implementations/twig/components/blockquote/blockquote.story.js
  src/implementations/twig/components/breadcrumb-core/breadcrumb-core.story.js
  src/implementations/twig/components/breadcrumb-harmonised/breadcrumb-harmonised.story.js
  src/implementations/twig/components/breadcrumb-standardised/breadcrumb-standardised.story.js
  src/implementations/twig/components/datepicker/datepicker.story.js
  src/implementations/twig/components/fact-figures/fact-figures.story.js
  src/implementations/twig/components/file/file.story.js
  src/implementations/twig/components/label/label.story.js
  src/implementations/twig/components/spinner/spinner.story.js
  src/website/public/admin/markdown.css
  src/website/src/pages/ec/components/fact-figures/docs/code.mdx
  src/website/src/pages/ec/components/file/docs/code.mdx
  src/website/src/pages/ec/components/label/docs/code.mdx
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/code.mdx
  src/website/src/pages/eu/components/fact-figures/docs/code.mdx
  src/website/src/pages/eu/components/file/docs/code.mdx
  src/website/src/pages/eu/components/label/docs/code.mdx
  src/website/src/pages/eu/components/navigation/breadcrumb/docs/code.mdx
Labels: tag: enhancement, process: review needed

#2299 feat(EC Usage pages for components): update EC Usage pages for components “ec_page_header_standardised”
  cms-images/ec_ph_st_thumb_l_734px.png
  cms-images/ec_ph_stan_dark_l_734px.png
  cms-images/ec_ph_stan_image_l_734px.png
  cms-images/ec_ph_stan_light_l_734px.png
Labels: netlify-cms/pending_publish

#2298 chore(deps): updates 06-01-22
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2295 feat(icon): add 'trash' icon - FRONT-3521
  src/implementations/twig/components/icon/__snapshots__/icon.test.js.snap
  src/resources/icons-ec/src/all/trash.svg
  src/resources/icons-eu/src/all/trash.svg
Labels: tag: enhancement

#2287 fix(unordered-list): fix spacing - FRONT-3516
  src/implementations/vanilla/components/unordered-list/_unordered-list.scss
Labels: tag: bug fix

#2286 feat(tabs): Add component - FRONT-3292
  src/implementations/twig/components/tabs/.npmignore
  src/implementations/twig/components/tabs/README.md
  src/implementations/twig/components/tabs/__snapshots__/tabs.test.js.snap
  src/implementations/twig/components/tabs/package.json
  src/implementations/twig/components/tabs/tabs.html.twig
  src/implementations/twig/components/tabs/tabs.story.js
  src/implementations/twig/components/tabs/tabs.test.js
  src/implementations/vanilla/components/tabs/README.md
  src/implementations/vanilla/components/tabs/_tabs.scss
  src/implementations/vanilla/components/tabs/package.json
  src/implementations/vanilla/components/tabs/tabs-ec.scss
  src/implementations/vanilla/components/tabs/tabs-eu.scss
  src/implementations/vanilla/components/tabs/tabs-print.scss
  src/implementations/vanilla/components/tabs/tabs.js
  src/presets/dev/src/dev.js
  src/presets/dev/src/dev.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/specs/components/tabs/demo/data.js
  src/specs/components/tabs/package.json
  src/website/public/admin/config.yml
  src/website/src/pages/ec/components/index.mdx
  src/website/src/pages/ec/components/navigation/tabs/demo/index.js
  src/website/src/pages/ec/components/navigation/tabs/docs/api.mdx
  src/website/src/pages/ec/components/navigation/tabs/docs/code.mdx
  src/website/src/pages/ec/components/navigation/tabs/docs/usage.md
  src/website/src/pages/ec/components/navigation/tabs/ec_comp_tabs.svg
  src/website/src/pages/ec/components/navigation/tabs/index.md
  src/website/src/pages/eu/components/index.mdx
  src/website/src/pages/eu/components/navigation/tabs/demo/index.js
  src/website/src/pages/eu/components/navigation/tabs/docs/api.mdx
  src/website/src/pages/eu/components/navigation/tabs/docs/code.mdx
  src/website/src/pages/eu/components/navigation/tabs/docs/usage.md
  src/website/src/pages/eu/components/navigation/tabs/eu_comp_tabs.svg
  src/website/src/pages/eu/components/navigation/tabs/index.md
Labels: tag: new feature

#2300 feat(logo): add translated logos (EC/EU)
  src/resources/logo-ec/logo-ec--ar.svg
  src/resources/logo-ec/logo-ec--ca.svg
  src/resources/logo-ec/logo-ec--is.svg
  src/resources/logo-ec/logo-ec--no.svg
  src/resources/logo-ec/logo-ec--tu.svg
  src/resources/logo-ec/negative/logo-ec--ar.svg
  src/resources/logo-ec/negative/logo-ec--ca.svg
  src/resources/logo-ec/negative/logo-ec--is.svg
  src/resources/logo-ec/negative/logo-ec--no.svg
  src/resources/logo-ec/negative/logo-ec--tu.svg
  src/resources/logo-eu/condensed-version/positive/logo-eu--ar.svg
  src/resources/logo-eu/condensed-version/positive/logo-eu--ca.svg
  src/resources/logo-eu/condensed-version/positive/logo-eu--is.svg
  src/resources/logo-eu/condensed-version/positive/logo-eu--no.svg
  src/resources/logo-eu/condensed-version/positive/logo-eu--tu.svg
  src/resources/logo-eu/standard-version/positive/logo-eu--ar.svg
  src/resources/logo-eu/standard-version/positive/logo-eu--ca.svg
  src/resources/logo-eu/standard-version/positive/logo-eu--is.svg
  src/resources/logo-eu/standard-version/positive/logo-eu--no.svg
  src/resources/logo-eu/standard-version/positive/logo-eu--tu.svg
Labels: tag: enhancement

#2303 fix(utilities): fix paragraph utilities - FRONT-3523
  src/implementations/vanilla/utilities/typography/_typography.scss
  yarn.lock
Labels: tag: bug fix

#2304 feat(EC Usage pages for components): update EC Usage pages for components “ec_page_header_standardised”
  cms-images/standardised-page-header-1b.png
  src/website/src/pages/ec/standardised-template/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#2307 fix(file): fix file stories - FRONT-3303
  src/implementations/twig/components/file/file.story.js
Labels: tag: bug fix

#2302 chore(deps): Moving to fermium, libraries updated
  .github/workflows/ci.yml
  .nvmrc
  README.md
  package.json
  src/implementations/vanilla/components/gallery/package.json
  src/implementations/vanilla/components/site-header-core/package.json
  src/implementations/vanilla/components/site-header-harmonised/package.json
  src/implementations/vanilla/components/site-header-standardised/package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/index.js
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/resources/icons-ec/package.json
  src/resources/icons-ec/scripts/clean-svg.js
  src/resources/icons-eu/package.json
  src/resources/icons-eu/scripts/clean-svg.js
  src/resources/icons-flag/package.json
  src/resources/icons-flag/scripts/clean-svg.js
  src/resources/icons-social-media/package.json
  src/resources/icons-social-media/scripts/clean-svg.js
  src/resources/social-icons/package.json
  src/resources/social-icons/scripts/clean-svg.js
  src/tools/builder/builder.test.js
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2312 feat(site-header-standardised): add control for search
  src/implementations/twig/components/site-header-standardised/ec-site-header-standardised.story.js
  src/implementations/twig/components/site-header-standardised/site-header-standardised.html.twig
Labels: tag: enhancement

#2316 chore(deps): Updates - 24-01-22
  package.json
  src/implementations/vanilla/components/icon/_icon.scss
  src/implementations/vanilla/components/icon/icon-print.scss
  src/implementations/vanilla/components/link/_link-print.scss
  src/implementations/vanilla/components/link/_link.scss
  src/implementations/vanilla/components/search-form/_search-form.scss
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  src/website/src/website-components/Anatomy/Anatomy.scss
  src/website/src/website-components/DoDont/DoDont.scss
  src/website/src/website-components/Icon/IconCard.scss
  src/website/src/website-components/Link/Link.scss
  src/website/src/website-components/Playground.scss
  yarn.lock
Labels: tag: internal

#2320 fix(logo): rename turkish logo - FRONT-3533
  src/resources/logo-ec/logo-ec--tr.svg
  src/resources/logo-ec/negative/logo-ec--tr.svg
  src/resources/logo-eu/condensed-version/positive/logo-eu--tr.svg
  src/resources/logo-eu/standard-version/positive/logo-eu--tr.svg
Labels: tag: bug fix, process: review needed
