Repository ec-europa/europa-component-library, pull requests merged in 2023-01, with the labels that each got.

#2726 chore(deps): Updates - 03-01-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2725 feat(cursor): use hand cursor for different components - FRONT-3811
  src/implementations/vanilla/components/accordion/accordion-ec.scss
  src/implementations/vanilla/components/accordion/accordion-eu.scss
  src/implementations/vanilla/components/button/_button.scss
  src/implementations/vanilla/components/checkbox/_checkbox.scss
  src/implementations/vanilla/components/radio/_radio.scss
  src/implementations/vanilla/components/select/_select.scss
Labels: tag: enhancement

#2727 chore(file): Splitting in three templates, using similar approach in wc - FRONT-3815
  src/implementations/twig/components/file/file-translation-item.html.twig
  src/implementations/twig/components/file/file-translations.html.twig
  src/implementations/twig/components/file/file.html.twig
Labels: tag: enhancement, process: review needed

#2720 feat(icons): Updating 4 icons in EC - FRONT-3823
  src/resources/icons-ec/src/all/copy.svg
  src/resources/icons-ec/src/all/edit.svg
  src/resources/icons-ec/src/all/file.svg
  src/resources/icons-ec/src/all/multiple-files.svg
Labels: tag: enhancement

#2730 feat(icon-flag): update French flag - FRONT-3833
  src/resources/icons-flag/src/flag/france-square.svg
  src/resources/icons-flag/src/flag/france.svg
Labels: tag: enhancement

#2731 fix(link): fix underline of standalone link - FRONT-3834
  src/implementations/vanilla/components/link/_link.scss
Labels: tag: bug fix

#2733 chore(deps): Updates 16-01-23
  package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2716 feat(site-header): use popover for language list - FRONT-3761
  .size-limit.json
  src/implementations/twig/components/site-header/README.md
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/site-header/ec-site-header.story.js
  src/implementations/twig/components/site-header/eu-site-header.story.js
  src/implementations/twig/components/site-header/package.json
  src/implementations/twig/components/site-header/site-header-language-switcher.html.twig
  src/implementations/twig/components/site-header/site-header.html.twig
  src/implementations/twig/deprecated/language-list/.npmignore
  src/implementations/twig/deprecated/language-list/README.md
  src/implementations/twig/deprecated/language-list/__snapshots__/language-list.test.js.snap
  src/implementations/twig/deprecated/language-list/language-list-grid.html.twig
  src/implementations/twig/deprecated/language-list/language-list-item.html.twig
  src/implementations/twig/deprecated/language-list/language-list.html.twig
  src/implementations/twig/deprecated/language-list/language-list.story.js
  src/implementations/twig/deprecated/language-list/language-list.test.js
  src/implementations/twig/deprecated/language-list/package.json
  src/implementations/vanilla/components/popover/_popover.scss
  src/implementations/vanilla/components/popover/popover.js
  src/implementations/vanilla/components/site-header/_site-header-language-switcher.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/implementations/vanilla/components/site-header/site-header.js
  src/specs/components/site-header/demo/data--ec.js
  src/specs/components/site-header/demo/data--eu.js
  src/website/src/pages/ec/components/index.mdx
  src/website/src/pages/ec/components/language-list/ec_comp_language_list.svg
  src/website/src/pages/ec/deprecated/language-list/demo/index.js
  src/website/src/pages/ec/deprecated/language-list/docs/code.mdx
  src/website/src/pages/ec/deprecated/language-list/docs/usage.md
  src/website/src/pages/ec/deprecated/language-list/ec_comp_language_list.svg
  src/website/src/pages/ec/deprecated/language-list/index.md
  src/website/src/pages/eu/components/index.mdx
  src/website/src/pages/eu/components/language-list/eu_comp_language_list.svg
  src/website/src/pages/eu/deprecated/language-list/demo/index.js
  src/website/src/pages/eu/deprecated/language-list/docs/code.mdx
  src/website/src/pages/eu/deprecated/language-list/docs/usage.md
  src/website/src/pages/eu/deprecated/language-list/eu_comp_language_list.svg
  src/website/src/pages/eu/deprecated/language-list/index.md
Labels: tag: breaking change, tag: new feature

#2734 fix(site-header): fix mobile display of language popover - FRONT-3839
  src/implementations/vanilla/components/site-header/_site-header-language-switcher.scss
  src/implementations/vanilla/components/site-header/site-header.js
Labels: tag: bug fix, process: review needed

#2738 chore(deps): updates 25-01-23, audit fix
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/presets/ec/package.json
  src/presets/eu/package.json
  src/presets/reset/package.json
  src/presets/rtl/package.json
  src/resources/icons-ec/package.json
  src/resources/icons-eu/package.json
  src/resources/icons-flag/package.json
  src/resources/icons-social-media/package.json
  src/resources/logo-ec/package.json
  src/resources/logo-eu/package.json
  src/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2736 feat(message): make close button optional - FRONT-3837
  src/implementations/twig/components/message/README.md
  src/implementations/twig/components/message/message.html.twig
  src/implementations/twig/components/message/message.story.js
Labels: tag: enhancement

#2732 feat(shadow): harmonize shadows - FRONT-3828
  .size-limit.json
  src/implementations/twig/utilities/shadow/index.story.js
  src/implementations/vanilla/components/accordion/accordion-eu.scss
  src/implementations/vanilla/components/button/button-eu.scss
  src/implementations/vanilla/components/card/card-eu.scss
  src/implementations/vanilla/components/date-block/_date-block.scss
  src/implementations/vanilla/components/date-block/date-block-ec.scss
  src/implementations/vanilla/components/date-block/date-block-eu.scss
  src/implementations/vanilla/components/file-upload/file-upload-eu.scss
  src/implementations/vanilla/components/gallery/gallery-eu.scss
  src/implementations/vanilla/components/hero-banner/hero-banner-eu.scss
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation-eu.scss
  src/implementations/vanilla/components/link/link-eu.scss
  src/implementations/vanilla/components/media-container/media-container-eu.scss
  src/implementations/vanilla/components/menu/menu-ec.scss
  src/implementations/vanilla/components/menu/menu-eu.scss
  src/implementations/vanilla/components/navigation-list/navigation-list-eu.scss
  src/implementations/vanilla/components/page-banner/page-banner-eu.scss
  src/implementations/vanilla/components/popover/_popover.scss
  src/implementations/vanilla/components/popover/popover-ec.scss
  src/implementations/vanilla/components/popover/popover-eu.scss
  src/implementations/vanilla/components/select/select-eu.scss
  src/implementations/vanilla/components/site-footer/site-footer-eu.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/implementations/vanilla/components/tabs/tabs-eu.scss
  src/implementations/vanilla/components/text-area/text-area-eu.scss
  src/implementations/vanilla/components/text-input/text-input-eu.scss
  src/implementations/vanilla/components/timeline/timeline-eu.scss
  src/implementations/vanilla/utilities/shadow/README.md
  src/implementations/vanilla/utilities/shadow/package.json
  src/implementations/vanilla/utilities/shadow/shadow-print.scss
  src/implementations/vanilla/utilities/shadow/shadow.scss
  src/presets/dev/src/dev.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/themes/dev/_index.scss
  src/themes/dev/maps/shape.scss
  src/themes/eu/_index.scss
  src/website/src/pages/ec/utilities/shadow/docs/usage.md
  src/website/src/pages/ec/utilities/shadow/index.md
  src/website/src/pages/eu/utilities/shadow/docs/usage.md
  src/website/src/pages/eu/utilities/shadow/index.md
Labels: tag: enhancement

#2737 feat(fact and figures): update component display - FRONT-3840
  src/implementations/twig/components/fact-figures/README.md
  src/implementations/twig/components/fact-figures/__snapshots__/fact-figures.test.js.snap
  src/implementations/twig/components/fact-figures/fact-figures.html.twig
  src/implementations/twig/components/fact-figures/fact-figures.story.js
  src/implementations/twig/components/fact-figures/fact-figures.test.js
  src/implementations/vanilla/components/fact-figures/_fact-figures.scss
  src/implementations/vanilla/components/fact-figures/fact-figures-ec.scss
  src/implementations/vanilla/components/fact-figures/fact-figures-eu.scss
  src/specs/components/fact-figures/demo/data--3-col.js
  src/specs/components/fact-figures/demo/data.js
  src/website/src/pages/ec/components/fact-figures/demo/index.js
  src/website/src/pages/ec/components/fact-figures/docs/code.mdx
  src/website/src/pages/eu/components/fact-figures/demo/index.js
  src/website/src/pages/eu/components/fact-figures/docs/code.mdx
Labels: tag: enhancement

#2743 chore(deps): updates 30-01-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/test-utils/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2744 fix(carousel): fix bullet display on ipad (safari) - FRONT-3825
  src/implementations/vanilla/components/carousel/_carousel.scss
Labels: tag: bug fix
