Repository ec-europa/europa-component-library, pull requests merged in 2023-07, with the labels that each got.

#2930 chore(cms): Fixing base url, fixing path to deprecated pages - FRONT-4020
  netlify.toml
  src/website/public/admin/config.yml
Labels: tag: internal

#2932 fix(language switcher): js issue when no EU languages are defined - FRONT-4018
  src/implementations/vanilla/components/site-header/site-header.js
Labels: tag: bug fix

#2926 feat(spinner): ECL4 spinner - FRONT-3991
  docs/Migrating-v4.md
  src/implementations/twig/components/spinner/README.md
  src/implementations/twig/components/spinner/__snapshots__/spinner.test.js.snap
  src/implementations/twig/components/spinner/spinner.html.twig
  src/implementations/twig/components/spinner/spinner.story.js
  src/implementations/twig/components/spinner/spinner.test.js
  src/implementations/vanilla/components/spinner/_spinner-print.scss
  src/implementations/vanilla/components/spinner/_spinner.scss
  src/implementations/vanilla/components/spinner/package.json
  src/implementations/vanilla/components/spinner/spinner-ec.scss
  src/implementations/vanilla/components/spinner/spinner-eu.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/specs/components/spinner/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/index.mdx
  src/website/src/pages/ec/components/loading-indicator/demo/index.js
  src/website/src/pages/ec/components/loading-indicator/docs/code.mdx
  src/website/src/pages/ec/components/loading-indicator/docs/usage.md
  src/website/src/pages/ec/components/loading-indicator/ec_comp_loading_indicator.svg
  src/website/src/pages/ec/components/loading-indicator/index.md
  src/website/src/pages/ec/components/spinner/ec_comp_loading_indicator.svg
  src/website/src/pages/eu/components/index.mdx
  src/website/src/pages/eu/components/loading-indicator/demo/index.js
  src/website/src/pages/eu/components/loading-indicator/docs/code.mdx
  src/website/src/pages/eu/components/loading-indicator/docs/usage.md
  src/website/src/pages/eu/components/loading-indicator/eu_comp_loading_indicator.svg
  src/website/src/pages/eu/components/loading-indicator/index.md
  src/website/src/pages/eu/components/spinner/eu_comp_loading_indicator.svg
Labels: tag: enhancement

#2914 fix(forms): fix form elements width - FRONT-3993
  src/implementations/vanilla/components/datepicker/_datepicker.scss
  src/implementations/vanilla/components/range/_range.scss
  src/implementations/vanilla/components/select/_select.scss
  src/implementations/vanilla/components/text-area/_text-area.scss
  src/implementations/vanilla/components/text-input/_text-input.scss
  src/playground/addons/story-utils/index.js
Labels: tag: bug fix

#2934 feat(EU Usage pages for components): update EU Usage pages for components “eu_site_footer”
  cms-images/eu-harm.png
  src/website/src/pages/eu/components/site-wide/site-footer/docs/usage.md
Labels: netlify-cms/pending_publish

#2938 feat(EU Usage pages for components): update EU Usage pages for components “eu_banner”
  src/website/src/pages/ec/components/banner/docs/usage.md
Labels: netlify-cms/pending_publish

#2939 chore(docs): Adding modal usage page in the cms - FRONT-4022
  src/website/public/admin/config.yml
Labels: tag: internal

#2933 feat(language switcher): add resize event - FRONT-4013
  src/implementations/vanilla/components/site-header/site-header.js
Labels: tag: enhancement

#2945 chore(deps): Updates 07-07-23
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2940 feat(EC Usage pages for components): update EC Usage pages for components “ec_modal”
  src/website/src/pages/ec/components/modal/docs/usage.md
Labels: netlify-cms/pending_publish

#2907 feat(EU Usage pages for components): update EU Usage pages for components “eu_list”
  src/website/src/pages/eu/components/list/docs/usage.md
Labels: netlify-cms/pending_publish

#2906 feat(EC Usage pages for components): update EC Usage pages for components “ec_list”
  src/website/src/pages/ec/components/list/docs/usage.md
Labels: netlify-cms/pending_publish

#2947 feat(EU Usage pages for components): update EU Usage pages for components “eu_list”
  src/website/src/pages/eu/components/list/docs/usage.md
Labels: netlify-cms/pending_publish

#2927 feat(print): Iteration on banner, card, featured item, gallery, modal - FRONT-4006
  src/implementations/vanilla/components/banner/banner-print-ec.scss
  src/implementations/vanilla/components/banner/banner-print-eu.scss
  src/implementations/vanilla/components/banner/banner-print.scss
  src/implementations/vanilla/components/card/card-print.scss
  src/implementations/vanilla/components/featured-item/_featured-item-print.scss
  src/implementations/vanilla/components/gallery/gallery-print.scss
  src/implementations/vanilla/components/modal/modal-print-ec.scss
  src/implementations/vanilla/components/modal/modal-print-eu.scss
  src/implementations/vanilla/components/modal/modal-print.scss
  src/presets/ec/src/ec-print.scss
  src/presets/eu/src/eu-print.scss
Labels: tag: enhancement

#2943 feat(media-container): add expandable - FRONT-4017
  src/implementations/twig/components/banner/banner.story.js
  src/implementations/twig/components/banner/package.json
  src/implementations/twig/components/card/package.json
  src/implementations/twig/components/featured-item/__snapshots__/featured-item.test.js.snap
  src/implementations/twig/components/file/package.json
  src/implementations/twig/components/gallery/package.json
  src/implementations/twig/components/list-illustration/package.json
  src/implementations/twig/components/media-container/README.md
  src/implementations/twig/components/media-container/__snapshots__/media-container.test.js.snap
  src/implementations/twig/components/media-container/media-container.html.twig
  src/implementations/twig/components/media-container/media-container.story.js
  src/implementations/twig/components/media-container/media-container.test.js
  src/implementations/twig/components/media-container/package.json
  src/implementations/twig/components/page-header/package.json
  src/implementations/twig/components/site-footer/package.json
  src/implementations/twig/components/site-header/package.json
  src/implementations/vanilla/components/media-container/_media-container.scss
  src/specs/components/media-container/demo/data--infographic.js
  src/website/src/pages/ec/components/media/media-container/demo/index.js
  src/website/src/pages/ec/components/media/media-container/docs/code.mdx
  src/website/src/pages/eu/components/media/media-container/demo/index.js
  src/website/src/pages/eu/components/media/media-container/docs/code.mdx
  yarn.lock
Labels: tag: new feature, tag: markup changes

#2954 fix(banner): reducing z-index on the container - FRONT-4025
  src/implementations/vanilla/components/banner/_banner.scss
Labels: tag: bug fix

#2956 feat(list-illustration): Image fit - FRONT-4027
  src/implementations/vanilla/components/list-illustration/_list-illustration.scss
Labels: tag: enhancement

#2959 feat(fixes): apply fixes from 3.9
  src/implementations/vanilla/components/banner/_banner.scss
  src/implementations/vanilla/components/list-illustration/_list-illustration.scss
  yarn.lock
Labels: tag: bug fix

#2965 chore(deps): Updates 24-07-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/builder.test.js
  src/tools/builder/package.json
  src/website/.eslintrc.js
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2964 chore(npm): Adding script to unpublish package versions
  scripts/unpublish.js
Labels: tag: internal

#2963 feat(accessibility): menu, gallery and accordion - FRONT-4033
  src/implementations/twig/components/accordion/__snapshots__/accordion.test.js.snap
  src/implementations/twig/components/accordion/accordion.html.twig
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/vanilla/components/menu/menu.js
  src/specs/components/gallery/demo/data.js
  src/website/src/pages/ec/components/navigation/menu/docs/code.mdx
  src/website/src/pages/eu/components/navigation/menu/docs/code.mdx
Labels: tag: enhancement

#2961 fix(footer): fix accessibility and cookie links - FRONT-4031
  src/implementations/twig/components/site-footer/__snapshots__/site-footer.test.js.snap
  src/specs/components/site-footer/demo/data-core--eu.js
  src/specs/components/site-footer/demo/data-harmonised--eu.js
Labels: tag: bug fix

#2951 feat(styles): Apply new structure to EU - FRONT-4008
  .size-limit.json
  docs/Migrating-v4.md
  src/implementations/vanilla/components/content-block/content-block-eu.scss
  src/implementations/vanilla/components/file/file-eu.scss
  src/implementations/vanilla/components/social-media-follow/social-media-follow-eu.scss
  src/implementations/vanilla/components/social-media-share/social-media-share-eu.scss
  src/themes/eu/_variables.scss
  src/themes/eu/maps/color.scss
Labels: tag: internal

#2970 fix(icons): Removing remaining style tags from distributes icons - FRONT-4036
  src/resources/icons-ec/scripts/config/svgo.js
  src/resources/icons-eu/scripts/config/svgo.js
  src/resources/icons-flag/scripts/config/svgo.js
  src/resources/icons-flag/src/flag/greece-square.svg
  src/resources/icons-social-media/scripts/config/svgo.js
  src/resources/icons-social-media/src/social-media/sms.svg
  src/resources/icons-social-media/src/social-media/weibo.svg
  src/resources/icons-social-media/src/social-media/whatasapp.svg
  src/resources/icons-social-media/src/social-media/yahoomail.svg
  src/resources/social-icons/scripts/config/svgo.js
Labels: tag: enhancement

#2973 chore(deps): Updates 31-07-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/resources/icons-ec/package.json
  src/resources/icons-ec/scripts/build-lists.js
  src/resources/icons-ec/scripts/build-sprites.js
  src/resources/icons-ec/scripts/clean-svg.js
  src/resources/icons-ec/scripts/write-list.js
  src/resources/icons-ec/scripts/write-sprite.js
  src/resources/icons-eu/package.json
  src/resources/icons-eu/scripts/build-lists.js
  src/resources/icons-eu/scripts/build-sprites.js
  src/resources/icons-eu/scripts/clean-svg.js
  src/resources/icons-eu/scripts/write-list.js
  src/resources/icons-eu/scripts/write-sprite.js
  src/resources/icons-flag/package.json
  src/resources/icons-flag/scripts/build-lists.js
  src/resources/icons-flag/scripts/build-sprites.js
  src/resources/icons-flag/scripts/clean-svg.js
  src/resources/icons-flag/scripts/write-list.js
  src/resources/icons-flag/scripts/write-sprite.js
  src/resources/icons-social-media/package.json
  src/resources/icons-social-media/scripts/build-lists.js
  src/resources/icons-social-media/scripts/build-sprites.js
  src/resources/icons-social-media/scripts/clean-svg.js
  src/resources/icons-social-media/scripts/write-list.js
  src/resources/icons-social-media/scripts/write-sprite.js
  src/resources/social-icons/scripts/build-sprites.js
  src/resources/social-icons/scripts/clean-svg.js
  src/resources/social-icons/scripts/generate-lists.js
  src/tools/builder/package.json
  src/tools/builder/scripts/styles.js
  src/website/package.json
  src/website/src/preval/get-meta-ec.js
  src/website/src/preval/get-meta-eu.js
  yarn.lock
Labels: tag: internal
