Repository ec-europa/europa-component-library, pull requests merged in 2023-09, with the labels that each got.

#3010 chore(deps): Updates 04-09-23
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2998 feat(checkbox): EC revamp for V4 - FRONT-4069
  docs/Migrating-v4.md
  src/implementations/twig/components/checkbox/README.md
  src/implementations/twig/components/checkbox/__snapshots__/checkbox.test.js.snap
  src/implementations/twig/components/checkbox/checkbox-group.html.twig
  src/implementations/twig/components/checkbox/checkbox-item.html.twig
  src/implementations/twig/components/form-group/__snapshots__/form-group.test.js.snap
  src/implementations/twig/components/form-group/form-group.story.js
  src/implementations/twig/components/form-group/form-group.test.js
  src/implementations/vanilla/components/checkbox/_checkbox.scss
  src/implementations/vanilla/components/checkbox/checkbox-ec.scss
  src/implementations/vanilla/components/checkbox/checkbox-eu.scss
  src/implementations/vanilla/components/checkbox/package.json
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/resources/icons-ec/src/all/check.svg
  src/specs/components/checkbox/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/forms/checkbox/demo/index.js
  src/website/src/pages/ec/components/forms/checkbox/docs/code.mdx
  src/website/src/pages/eu/components/forms/checkbox/demo/index.js
  src/website/src/pages/eu/components/forms/checkbox/docs/code.mdx
Labels: tag: enhancement

#3013 fix(banner): Fixing mapping for size control - FRONT-4078
  src/implementations/twig/components/banner/banner.story.js
Labels: tag: bug fix

#3008 feat(expandable): ECL4 expandable - FRONT-4071
  docs/Migrating-v4.md
  src/implementations/twig/components/expandable/__snapshots__/expandable.test.js.snap
  src/implementations/twig/components/expandable/expandable.html.twig
  src/implementations/twig/components/media-container/__snapshots__/media-container.test.js.snap
  src/implementations/vanilla/components/expandable/_expandable.scss
  src/implementations/vanilla/components/expandable/expandable-ec.scss
  src/implementations/vanilla/components/expandable/expandable-eu.scss
  src/implementations/vanilla/components/expandable/expandable-print.scss
  src/implementations/vanilla/components/expandable/package.json
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/specs/components/expandable/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#3014 chore(icons): Revert x icon - FRONT-4077
  src/resources/icons-social-media/src/social-media/twitter-color.svg
  src/resources/icons-social-media/src/social-media/twitter-negative.svg
  src/resources/icons-social-media/src/social-media/twitter.svg
Labels: tag: internal

#3015 chore(deps): Updates 07-09-23
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3025 chore(deps): Green and orange updates - 11-09-23
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3023 feat(expandable): Tweaking expandable content, adding divider - FRONT-4080
  src/implementations/twig/components/media-container/__snapshots__/media-container.test.js.snap
  src/implementations/vanilla/components/expandable/_expandable.scss
  src/implementations/vanilla/components/expandable/expandable-print.scss
  src/specs/components/media-container/demo/data--infographic.js
Labels: tag: enhancement

#3000 feat(radio): EC revamp for v4 - FRONT-4068
  src/implementations/twig/components/form-group/__snapshots__/form-group.test.js.snap
  src/implementations/twig/components/radio/__snapshots__/radio.test.js.snap
  src/implementations/vanilla/components/radio/_radio.scss
  src/implementations/vanilla/components/radio/package.json
  src/implementations/vanilla/components/radio/radio-ec.scss
  src/implementations/vanilla/components/radio/radio-eu.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/specs/components/radio/demo/data--default.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/forms/radio/docs/code.mdx
Labels: tag: enhancement

#3024 fix(carousel): fix rtl full screen display - FRONT-4081
  src/implementations/twig/components/carousel/carousel.story.js
  src/presets/rtl/src/rtl.scss
Labels: tag: bug fix

#3027 fix(skip-link): Increasing z-index value - FRONT-4082
  src/implementations/vanilla/components/skip-link/skip-link.scss
Labels: tag: bug fix

#3005 chore(containers): Minimal changes, containers always 100% excluding xl breapoint
  src/implementations/twig/components/banner/banner.story.js
  src/themes/dev/maps/layout.scss
Labels: tag: enhancement

#3021 feat(EC Usage pages for components): update EC Usage pages for components “ec_page_header”
  src/website/src/pages/ec/components/site-wide/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#3019 feat(EC Usage pages for components): update EC Usage pages for components “ec_site_header”
  src/website/src/pages/ec/components/site-wide/site-header/docs/usage.md
Labels: netlify-cms/pending_publish

#3020 feat(EC Usage pages for components): update EC Usage pages for components “ec_site_footer”
  src/website/src/pages/ec/components/site-wide/site-footer/docs/usage.md
Labels: netlify-cms/pending_publish

#3018 feat(EU Usage pages for components): update EU Usage pages for components “eu_page_header”
  src/website/src/pages/eu/components/site-wide/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#3016 feat(EU Usage pages for components): update EU Usage pages for components “eu_site_header”
  src/website/src/pages/eu/components/site-wide/site-header/docs/usage.md
Labels: netlify-cms/pending_publish

#3017 feat(EU Usage pages for components): update EU Usage pages for components “eu_site_footer”
  src/website/src/pages/eu/components/site-wide/site-footer/docs/usage.md
Labels: netlify-cms/pending_publish

#3031 fix(table): Fixing row extra classes, removing buggy row extra_attributes - FRONT-4084
  src/implementations/twig/components/table/README.md
  src/implementations/twig/components/table/__snapshots__/table.test.js.snap
  src/implementations/twig/components/table/table.html.twig
  src/implementations/twig/components/table/table.test.js
Labels: tag: bug fix, process: review needed

#3030 chore(deps): Updates 12-09-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  yarn.lock
Labels: tag: internal

#3032 fix(news-ticker): Removing redundant aria-labels, fixing sr-only in buttons - FRONT-4083
  src/implementations/twig/components/news-ticker/__snapshots__/news-ticker.test.js.snap
  src/implementations/twig/components/news-ticker/news-ticker.html.twig
Labels: tag: bug fix

#3035 chore(deps): Updates 15-09-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3034 fix(navigation-list): Aligning website showcase - FRONT-4091
  src/implementations/twig/components/navigation-list/__snapshots__/navigation-list.test.js.snap
  src/implementations/twig/components/navigation-list/navigation-list.story.js
  src/implementations/twig/components/navigation-list/navigation-list.test.js
  src/specs/components/navigation-list/demo/data.js
Labels: tag: internal

#3011 feat(navigation-list): EC Revamp for v4 - FRONT-4058
  docs/Migrating-v4.md
  src/implementations/twig/components/navigation-list/README.md
  src/implementations/twig/components/navigation-list/__snapshots__/navigation-list.test.js.snap
  src/implementations/twig/components/navigation-list/navigation-list-item.html.twig
  src/implementations/twig/components/navigation-list/navigation-list.html.twig
  src/implementations/twig/components/navigation-list/navigation-list.story.js
  src/implementations/twig/components/navigation-list/navigation-list.test.js
  src/implementations/vanilla/components/navigation-list/_navigation-list.scss
  src/implementations/vanilla/components/navigation-list/navigation-list-ec.scss
  src/implementations/vanilla/components/navigation-list/navigation-list-eu.scss
  src/implementations/vanilla/components/navigation-list/navigation-list-print.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/specs/components/navigation-list/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/navigation/navigation-list/index.md
  src/website/src/pages/eu/components/navigation/navigation-list/index.md
Labels: tag: enhancement

#3022 feat(timeline): EC revamp for v4 - FRONT-4079
  src/implementations/twig/components/timeline/timeline.story.js
  src/implementations/vanilla/components/timeline/_timeline-print-ec.scss
  src/implementations/vanilla/components/timeline/_timeline-print-eu.scss
  src/implementations/vanilla/components/timeline/_timeline-print.scss
  src/implementations/vanilla/components/timeline/_timeline.scss
  src/implementations/vanilla/components/timeline/timeline-ec.scss
  src/implementations/vanilla/components/timeline/timeline-eu.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement, process: review needed

#3039 fix(menu): fix line display - FRONT-4093
  src/implementations/vanilla/components/menu/_menu.scss
Labels: tag: bug fix

#3037 feat(tag): ECL 4 tag - FRONT-4088
  docs/Migrating-v4.md
  src/implementations/twig/components/icon/__snapshots__/icon.test.js.snap
  src/implementations/twig/components/tag/__snapshots__/tag.test.js.snap
  src/implementations/twig/components/tag/tag.html.twig
  src/implementations/vanilla/components/tag/_tag.scss
  src/implementations/vanilla/components/tag/package.json
  src/implementations/vanilla/components/tag/tag-ec.scss
  src/implementations/vanilla/components/tag/tag-eu.scss
  src/implementations/vanilla/components/tag/tag-print.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/resources/icons-ec/src/all/close-outline.svg
  src/resources/icons-ec/src/all/hamburger.svg
  src/resources/icons-eu/src/all/close-outline.svg
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#3041 chore(deps): Updates 25-09-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3044 fix(banner): Fixing show credit control - FRONT-4100
  src/implementations/twig/components/banner/banner.story.js
Labels: tag: bug fix, process: review needed

#3045 feat(picture): Allow empty alt attribute for the image - FRONT-4099
  src/implementations/twig/components/picture/__snapshots__/picture.test.js.snap
  src/implementations/twig/components/picture/picture.html.twig
  src/implementations/twig/components/picture/picture.test.js
Labels: tag: enhancement

#3047 fix(site-header): Fixing handleResize method - FRONT-4076
  src/implementations/vanilla/components/site-header/site-header.js
Labels: tag: bug fix

#3048 chore(deps): Green and orange updates - 26-09-23
  package.json
  src/implementations/vanilla/components/gallery/package.json
  src/implementations/vanilla/components/modal/package.json
  src/implementations/vanilla/components/site-header-core/package.json
  src/implementations/vanilla/components/site-header-harmonised/package.json
  src/implementations/vanilla/components/site-header-standardised/package.json
  src/implementations/vanilla/components/site-header/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/presets/ec/package.json
  src/presets/eu/package.json
  src/presets/reset/package.json
  src/presets/rtl/package.json
  src/resources/icons-ec/package.json
  src/resources/icons-eu/package.json
  src/resources/icons-flag/package.json
  src/resources/icons-social-media/package.json
  src/resources/logo-ec/package.json
  src/resources/logo-eu/package.json
  src/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3040 feat(date block): Update display - FRONT-4095
  src/implementations/vanilla/components/date-block/_date-block.scss
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#3049 feat(expandable): update spacing - FRONT-4096
  src/implementations/vanilla/components/expandable/_expandable.scss
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#3043 feat(list): add indentation - FRONT-4059
  src/implementations/twig/components/carousel/carousel.story.js
  src/implementations/twig/components/ordered-list/__snapshots__/ordered-list.test.js.snap
  src/implementations/twig/components/ordered-list/ordered-list.story.js
  src/implementations/twig/components/unordered-list/__snapshots__/unordered-list.test.js.snap
  src/implementations/twig/components/unordered-list/unordered-list.story.js
  src/implementations/vanilla/components/ordered-list/_ordered-list.scss
  src/implementations/vanilla/components/unordered-list/_unordered-list.scss
  src/specs/components/ordered-list/demo/data--link.js
  src/specs/components/ordered-list/demo/data--no-marker.js
  src/specs/components/ordered-list/demo/data--text.js
  src/specs/components/ordered-list/demo/data--with-divider.js
  src/specs/components/unordered-list/demo/data--link.js
  src/specs/components/unordered-list/demo/data--no-bullet.js
  src/specs/components/unordered-list/demo/data--text.js
  src/specs/components/unordered-list/demo/data--with-divider.js
Labels: tag: enhancement

#3038 feat(file): Ec revamp for v4 - FRONT-4089
  docs/Migrating-v4.md
  src/implementations/twig/components/file/README.md
  src/implementations/twig/components/file/__snapshots__/file.test.js.snap
  src/implementations/twig/components/file/file-translation-item.html.twig
  src/implementations/twig/components/file/file-translations.html.twig
  src/implementations/twig/components/file/file.html.twig
  src/implementations/twig/components/file/file.story.js
  src/implementations/vanilla/components/file/_file.scss
  src/implementations/vanilla/components/file/file-ec.scss
  src/implementations/vanilla/components/file/file-eu.scss
  src/implementations/vanilla/components/file/file-print.scss
  src/implementations/vanilla/components/file/package.json
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/resources/icons-ec/src/all/file.svg
  src/specs/components/file/demo/data--taxonomy.js
  src/specs/components/file/demo/data--thumbnail.js
  src/specs/components/file/demo/data--with-translation.js
  src/specs/components/file/demo/data--without-translation.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement
