Repository ec-europa/europa-component-library, pull requests merged in 2023-03, with the labels that each got.

#2779 chore(footer): Adding accessibility link in footer core and harmonised - FRONT-3869
  src/implementations/twig/components/site-footer/__snapshots__/site-footer.test.js.snap
  src/specs/components/site-footer/demo/data-core--ec.js
  src/specs/components/site-footer/demo/data-harmonised--ec.js
Labels: tag: enhancement, process: review needed

#2781 feat: Improving keyboard navigation for carousel, updating EU styles for focus in radio - FRONT-3870
  src/implementations/twig/components/radio/__snapshots__/radio.test.js.snap
  src/implementations/vanilla/components/carousel/carousel.js
  src/implementations/vanilla/components/radio/radio-eu.scss
  src/specs/components/radio/demo/data--default.js
Labels: tag: enhancement, process: review needed

#2786 feat(icons): Adding new icons - FRONT-3888
  .size-limit.json
  src/resources/icons-flag/src/flag/iceland-square.svg
  src/resources/icons-flag/src/flag/iceland.svg
  src/resources/icons-flag/src/flag/norway-square.svg
  src/resources/icons-flag/src/flag/norway.svg
  src/resources/icons-flag/src/flag/switzerland-square.svg
  src/resources/icons-flag/src/flag/switzerland.svg
  src/resources/icons-social-media/src/social-media/gmail-color.svg
  src/resources/icons-social-media/src/social-media/messenger-color.svg
  src/resources/icons-social-media/src/social-media/messenger-negative.svg
  src/resources/icons-social-media/src/social-media/messenger.svg
  src/resources/icons-social-media/src/social-media/qzone-color.svg
  src/resources/icons-social-media/src/social-media/qzone-negative.svg
  src/resources/icons-social-media/src/social-media/qzone.svg
  src/resources/icons-social-media/src/social-media/sms-color.svg
  src/resources/icons-social-media/src/social-media/sms-negative.svg
  src/resources/icons-social-media/src/social-media/sms.svg
  src/resources/icons-social-media/src/social-media/typepad-color.svg
  src/resources/icons-social-media/src/social-media/typepad-negative.svg
  src/resources/icons-social-media/src/social-media/typepad.svg
  src/resources/icons-social-media/src/social-media/weibo-color.svg
  src/resources/icons-social-media/src/social-media/weibo-negative.svg
  src/resources/icons-social-media/src/social-media/weibo.svg
  src/resources/icons-social-media/src/social-media/whatasapp.svg
  src/resources/icons-social-media/src/social-media/whataspp-negative.svg
  src/resources/icons-social-media/src/social-media/whatsapp-color.svg
  src/resources/icons-social-media/src/social-media/yahoomail-color.svg
  src/resources/icons-social-media/src/social-media/yahoomail-negative.svg
  src/resources/icons-social-media/src/social-media/yahoomail.svg
Labels: tag: enhancement

#2785 chore(print): Global font-family set in default-print css - FRONT-3861
  src/presets/ec/src/ec-default-print.scss
  src/presets/ec/src/ec-print.scss
  src/presets/eu/src/eu-default-print.scss
  src/presets/eu/src/eu-print.scss
Labels: tag: enhancement

#2790 chore(deps): Updates 06-03-23
  package.json
  src/presets/ec/package.json
  src/presets/eu/package.json
  src/presets/reset/package.json
  src/presets/rtl/package.json
  src/resources/icons-ec/package.json
  src/resources/icons-eu/package.json
  src/resources/icons-flag/package.json
  src/resources/icons-social-media/package.json
  src/resources/logo-ec/package.json
  src/resources/logo-eu/package.json
  src/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2788 chore(icons): Using presentation attributes instead of inline styles - FRONT-3883
  src/resources/icons-ec/scripts/config/svgo.js
  src/resources/icons-ec/src/all/close-filled.svg
  src/resources/icons-eu/scripts/config/svgo.js
  src/resources/icons-eu/src/all/calendar.svg
  src/resources/icons-eu/src/all/check.svg
  src/resources/icons-flag/scripts/config/svgo.js
  src/resources/icons-social-media/scripts/config/svgo.js
  src/resources/social-icons/scripts/config/svgo.js
Labels: tag: enhancement

#2787 chore(content-block): Removing examples with tags - FRONT-3844
  src/implementations/twig/components/card/README.md
  src/implementations/twig/components/card/__snapshots__/card.test.js.snap
  src/implementations/twig/components/card/card.html.twig
  src/implementations/twig/components/card/card.story.js
  src/implementations/twig/components/content-block/README.md
  src/implementations/twig/components/content-block/__snapshots__/content-block.test.js.snap
  src/implementations/twig/components/content-block/content-block.html.twig
  src/specs/components/card/demo/data.js
  src/specs/components/content-block/demo/data.js
  src/website/src/pages/ec/components/card/docs/code.mdx
  src/website/src/pages/eu/components/card/docs/code.mdx
Labels: tag: enhancement

#2784 feat(blockquote): use picture tag - FRONT-3873
  src/implementations/twig/components/blockquote/README.md
  src/implementations/twig/components/blockquote/__snapshots__/blockquote.test.js.snap
  src/implementations/twig/components/blockquote/blockquote.html.twig
  src/implementations/twig/components/blockquote/blockquote.story.js
  src/implementations/twig/components/blockquote/blockquote.test.js
  src/implementations/twig/components/blockquote/package.json
  src/implementations/vanilla/components/blockquote/_blockquote-print.scss
  src/implementations/vanilla/components/blockquote/_blockquote.scss
  src/specs/components/blockquote/demo/data.js
Labels: tag: new feature, tag: markup changes

#2791 fix(link): fix underline for semantic links with icons - FRONT-3886
  src/implementations/vanilla/components/link/_link-print.scss
  src/implementations/vanilla/components/link/_link.scss
Labels: tag: bug fix

#2796 chore(deps): Updates 13-03-23 - using node 16.14.0
  .github/workflows/ci.yml
  .github/workflows/production.yml
  .nvmrc
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2797 fix(banner): fix right to left
  src/presets/rtl/src/rtl.scss
Labels: tag: bug fix

#2795 feat(language-list): accessibility improvements - FRONT-3890
  .size-limit.json
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/site-header/site-header-language-switcher.html.twig
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header.js
  src/specs/components/site-header/demo/data--ec.js
  src/specs/components/site-header/demo/data--eu.js
Labels: tag: enhancement, tag: markup changes

#2801 chore(deps): Updates 15-03-23
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2799 fix(banner): Fixing cta button icon when reaching the playground from the website - FRONT-3899
  src/implementations/twig/components/banner/banner.story.js
Labels: tag: bug fix

#2805 fix(banner): Fixing background for text-box variant - FRONT-3901
  src/implementations/vanilla/components/banner/_banner.scss
Labels: tag: bug fix, process: review needed

#2806 feat(site-header): Adding control for logged in user - FRONT-3902
  src/implementations/twig/components/site-header/ec-site-header.story.js
  src/implementations/twig/components/site-header/eu-site-header.story.js
Labels: tag: enhancement

#2809 feat(navigation-list): Using picture - FRONT-3879
  src/implementations/twig/components/navigation-list/README.md
  src/implementations/twig/components/navigation-list/__snapshots__/navigation-list.test.js.snap
  src/implementations/twig/components/navigation-list/navigation-list-item.html.twig
  src/implementations/twig/components/navigation-list/navigation-list.story.js
  src/implementations/twig/components/navigation-list/navigation-list.test.js
  src/implementations/vanilla/components/navigation-list/_navigation-list.scss
  src/specs/components/navigation-list/demo/data.js
Labels: tag: enhancement, process: review needed, tag: markup changes

#2804 feat(list-illustration): Using picture tag - FRONT-3877
  src/implementations/twig/components/list-illustration/README.md
  src/implementations/twig/components/list-illustration/__snapshots__/list-illustration.test.js.snap
  src/implementations/twig/components/list-illustration/list-illustration-item.html.twig
  src/implementations/twig/components/list-illustration/list-illustration.story.js
  src/implementations/twig/components/list-illustration/list-illustration.test.js
  src/implementations/vanilla/components/list-illustration/_list-illustration.scss
  src/specs/components/list-illustration/demo/data--image.js
  src/website/src/pages/ec/components/list-illustration/demo/index.js
  src/website/src/pages/eu/components/list-illustration/demo/index.js
Labels: tag: enhancement, tag: markup changes

#2800 feat(form-elements): Using generic sibling selector to allow slightly different markup - FRONT-3857
  src/implementations/vanilla/components/checkbox/_checkbox.scss
  src/implementations/vanilla/components/radio/_radio.scss
  src/implementations/vanilla/components/rating-field/_rating-field.scss
  src/implementations/vanilla/components/select/_select.scss
Labels: tag: enhancement, process: review needed

#2810 feat(site-header): Using picture, keeping data structure unchanged - FRONT-3882
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/site-header/site-header.html.twig
  src/implementations/vanilla/components/site-header/site-header-eu.scss
Labels: tag: enhancement, process: review needed, tag: markup changes

#2811 feat(footer): Picture in footer, data unchanged - FRONT-3881
  src/implementations/twig/components/site-footer/__snapshots__/site-footer.test.js.snap
  src/implementations/twig/components/site-footer/site-footer.html.twig
  src/implementations/vanilla/components/site-footer/site-footer-eu.scss
Labels: tag: enhancement, process: review needed, tag: markup changes

#2803 chore: Upgrading mdx to v2, React 18
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/website/package.json
  src/website/public/admin/config.yml
  src/website/src/pages/ec/guidelines/iconography/index.mdx
  src/website/src/pages/ec/guidelines/logo/index.mdx
  src/website/src/pages/ec/guidelines/spacing/index.mdx
  src/website/src/pages/ec/utilities/background/docs/usage.mdx
  src/website/src/pages/ec/utilities/border/docs/usage.mdx
  src/website/src/pages/ec/utilities/clearfix/docs/usage.mdx
  src/website/src/pages/ec/utilities/dimension/docs/usage.mdx
  src/website/src/pages/ec/utilities/disablescroll/docs/usage.mdx
  src/website/src/pages/ec/utilities/display/docs/usage.mdx
  src/website/src/pages/ec/utilities/float/docs/usage.md
  src/website/src/pages/ec/utilities/html-tag/docs/usage.mdx
  src/website/src/pages/ec/utilities/layout/grid/index.mdx
  src/website/src/pages/ec/utilities/layout/stacks/docs/usage.mdx
  src/website/src/pages/ec/utilities/media/docs/usage.mdx
  src/website/src/pages/ec/utilities/print/docs/usage.mdx
  src/website/src/pages/ec/utilities/screen-reader/docs/usage.mdx
  src/website/src/pages/ec/utilities/shadow/docs/usage.mdx
  src/website/src/pages/ec/utilities/spacing/docs/usage.mdx
  src/website/src/pages/ec/utilities/typography/docs/usage.mdx
  src/website/src/pages/ec/utilities/z-index/docs/usage.mdx
  src/website/src/pages/eu/guidelines/iconography/index.mdx
  src/website/src/pages/eu/guidelines/logo/index.mdx
  src/website/src/pages/eu/guidelines/spacing/index.mdx
  src/website/src/pages/eu/utilities/background/docs/usage.mdx
  src/website/src/pages/eu/utilities/border/docs/usage.mdx
  src/website/src/pages/eu/utilities/clearfix/docs/usage.mdx
  src/website/src/pages/eu/utilities/dimension/docs/usage.mdx
  src/website/src/pages/eu/utilities/disablescroll/docs/usage.mdx
  src/website/src/pages/eu/utilities/display/docs/usage.mdx
  src/website/src/pages/eu/utilities/float/docs/usage.md
  src/website/src/pages/eu/utilities/layout/grid/index.mdx
  src/website/src/pages/eu/utilities/layout/stacks/docs/usage.mdx
  src/website/src/pages/eu/utilities/media/docs/usage.mdx
  src/website/src/pages/eu/utilities/print/docs/usage.mdx
  src/website/src/pages/eu/utilities/screen-reader/docs/usage.mdx
  src/website/src/pages/eu/utilities/shadow/docs/usage.mdx
  src/website/src/pages/eu/utilities/spacing/docs/usage.mdx
  src/website/src/website-components/Logo/LogoCard.jsx
  src/website/webpack.config.dev.js
  src/website/webpack.config.prod.js
  yarn.lock
Labels: tag: internal, process: review needed

#2812 feat(timeline): Adding controls for the first item content - FRONT-3906
  src/implementations/twig/components/timeline/timeline.story.js
Labels: tag: enhancement, process: review needed

#2815 chore(deps): Updates 29-03-23
  package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/presets/ec/package.json
  src/presets/eu/package.json
  src/presets/reset/package.json
  src/presets/rtl/package.json
  src/resources/icons-ec/package.json
  src/resources/icons-eu/package.json
  src/resources/icons-flag/package.json
  src/resources/icons-social-media/package.json
  src/resources/logo-ec/package.json
  src/resources/logo-eu/package.json
  src/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2793 feat(gallery): Component updates, new video and audio icons - FRONT-3887
  .size-limit.json
  src/implementations/twig/components/gallery/README.md
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/twig/components/gallery/gallery-item.html.twig
  src/implementations/twig/components/gallery/gallery-overlay.html.twig
  src/implementations/twig/components/gallery/gallery.html.twig
  src/implementations/twig/components/gallery/gallery.story.js
  src/implementations/vanilla/components/gallery/_gallery.scss
  src/implementations/vanilla/components/gallery/gallery-ec.scss
  src/implementations/vanilla/components/gallery/gallery-eu.scss
  src/implementations/vanilla/components/gallery/gallery.js
  src/resources/icons-ec/src/all/audio.svg
  src/resources/icons-ec/src/all/calendar.svg
  src/resources/icons-ec/src/all/check.svg
  src/resources/icons-ec/src/all/video.svg
  src/resources/icons-eu/src/all/audio.svg
  src/resources/icons-eu/src/all/video.svg
  src/specs/components/gallery/demo/data.js
Labels: tag: enhancement, process: review needed, tag: markup changes
