Repository ec-europa/europa-component-library, pull requests merged in 2023-08, with the labels that each got.

#2950 feat(description-list): Revamp for v4 - FRONT-4024
  .size-limit.json
  docs/Migrating-v4.md
  src/implementations/twig/components/card/__snapshots__/card.test.js.snap
  src/implementations/twig/components/content-block/__snapshots__/content-block.test.js.snap
  src/implementations/twig/components/content-item/__snapshots__/content-item.test.js.snap
  src/implementations/twig/components/description-list/__snapshots__/description-list.test.js.snap
  src/implementations/twig/components/description-list/description-list.html.twig
  src/implementations/vanilla/components/description-list/_description-list-print.scss
  src/implementations/vanilla/components/description-list/_description-list.scss
  src/implementations/vanilla/components/description-list/description-list-ec.scss
  src/implementations/vanilla/components/description-list/description-list-eu.scss
  src/implementations/vanilla/components/description-list/description-list-print-ec.scss
  src/implementations/vanilla/components/description-list/description-list-print-eu.scss
  src/implementations/vanilla/components/description-list/description-list.js
  src/implementations/vanilla/components/description-list/package.json
  src/presets/ec/src/ec-default-print.scss
  src/presets/ec/src/ec-default.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-default-print.scss
  src/presets/eu/src/eu-default.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/specs/components/description-list/demo/data--default.js
  src/specs/components/description-list/demo/data--horizontal.js
  src/themes/dev/maps/typography.scss
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  yarn.lock
Labels: tag: enhancement

#2976 feat(accessibility): Improving external link accessibility - FRONT-4044
  src/implementations/twig/components/icon/icon.html.twig
  src/implementations/twig/components/link/__snapshots__/link.test.js.snap
  src/implementations/twig/components/link/link.html.twig
  src/implementations/twig/components/link/link.story.js
  src/implementations/twig/components/link/link.test.js
  src/specs/components/link/demo/data--icon.js
Labels: tag: enhancement

#2962 feat(page header): ECL4 page header - FRONT-4021
  docs/Migrating-v4.md
  src/implementations/twig/components/breadcrumb/breadcrumb.story.js
  src/implementations/twig/components/breadcrumb/ec-breadcrumb.story.js
  src/implementations/twig/components/page-header/README.md
  src/implementations/twig/components/page-header/__snapshots__/page-header.test.js.snap
  src/implementations/twig/components/page-header/eu-page-header.story.js
  src/implementations/twig/components/page-header/page-header.html.twig
  src/implementations/twig/components/page-header/page-header.story.js
  src/implementations/vanilla/components/breadcrumb/_breadcrumb.scss
  src/implementations/vanilla/components/page-header/package.json
  src/implementations/vanilla/components/page-header/page-header-ec.scss
  src/implementations/vanilla/components/page-header/page-header-eu.scss
  src/implementations/vanilla/components/page-header/page-header-print-ec.scss
  src/implementations/vanilla/components/page-header/page-header-print-eu.scss
  src/implementations/vanilla/components/page-header/page-header-print.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/specs/components/page-header/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/navigation/breadcrumb/demo/core.js
  src/website/src/pages/ec/components/navigation/breadcrumb/demo/harmonised.js
  src/website/src/pages/ec/components/navigation/breadcrumb/demo/index.js
  src/website/src/pages/ec/components/navigation/breadcrumb/demo/standardised.js
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/code.mdx
  src/website/src/pages/ec/components/site-wide/page-header/demo/index.js
  src/website/src/pages/ec/components/site-wide/page-header/docs/code.mdx
  src/website/src/pages/eu/components/navigation/breadcrumb/demo/core.js
  src/website/src/pages/eu/components/navigation/breadcrumb/demo/harmonised.js
  src/website/src/pages/eu/components/navigation/breadcrumb/demo/index.js
  src/website/src/pages/eu/components/navigation/breadcrumb/docs/code.mdx
  src/website/src/pages/eu/components/site-wide/page-header/demo/index.js
  src/website/src/pages/eu/components/site-wide/page-header/docs/code.mdx
Labels: tag: enhancement

#2971 feat(blockquote): ECL4 blockquote - FRONT-4035
  src/implementations/twig/components/blockquote/__snapshots__/blockquote.test.js.snap
  src/implementations/vanilla/components/blockquote/_blockquote-print.scss
  src/implementations/vanilla/components/blockquote/_blockquote.scss
  src/implementations/vanilla/components/blockquote/blockquote-ec.scss
  src/implementations/vanilla/components/blockquote/blockquote-eu.scss
  src/implementations/vanilla/components/blockquote/blockquote-print-ec.scss
  src/implementations/vanilla/components/blockquote/blockquote-print-eu.scss
  src/implementations/vanilla/components/blockquote/package.json
  src/presets/ec/src/ec-default-print.scss
  src/presets/ec/src/ec-default.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-default-print.scss
  src/presets/eu/src/eu-default.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/specs/components/blockquote/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#2966 feat(language-switcher): ECL4 language switcher - FRONT-3963
  docs/Migrating-v4.md
  src/implementations/twig/components/site-header/README.md
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/site-header/ec-site-header.story.js
  src/implementations/twig/components/site-header/eu-site-header.story.js
  src/implementations/twig/components/site-header/site-header-language-switcher.html.twig
  src/implementations/vanilla/components/site-header/_site-header-language-switcher.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/specs/components/site-header/demo/data--ec.js
  src/specs/components/site-header/demo/data--eu.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/site-wide/site-header/docs/code.mdx
  src/website/src/pages/eu/components/site-wide/site-header/docs/code.mdx
Labels: tag: enhancement

#2980 chore(deps): Updates 03-08-23
  .github/workflows/ci.yml
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/.storybook/manager-head.html
  src/playground/ec/package.json
  src/playground/eu/.storybook/manager-head.html
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2969 feat(site-header): update non-eu language list - FRONT-4039
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/site-header/ec-site-header.story.js
  src/implementations/twig/components/site-header/eu-site-header.story.js
  src/specs/components/site-header/demo/data--ec.js
  src/specs/components/site-header/demo/data--eu.js
Labels: tag: enhancement, Question

#2981 fix(site-header): fix close button - FRONT-4018
  src/implementations/twig/components/site-header/ec-site-header.story.js
  src/implementations/twig/components/site-header/eu-site-header.story.js
  src/implementations/vanilla/components/site-header/site-header.js
Labels: tag: bug fix

#2983 chore(deps): Updates 07-08-23
  package.json
  src/implementations/vanilla/components/file/file-ec.scss
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2979 fix(carousel): Handling shift+tab also in play button handler
  src/implementations/vanilla/components/carousel/carousel.js
Labels: tag: enhancement

#2972 feat(accordion): EC Revamp for v4 - FRONT-4030
  .size-limit.json
  docs/Migrating-v4.md
  src/implementations/twig/components/accordion/__snapshots__/accordion.test.js.snap
  src/implementations/twig/components/accordion/accordion.html.twig
  src/implementations/twig/components/accordion/accordion.story.js
  src/implementations/vanilla/components/accordion/accordion-ec.scss
  src/implementations/vanilla/components/accordion/accordion-eu.scss
  src/implementations/vanilla/components/accordion/accordion-print.scss
  src/implementations/vanilla/components/accordion/accordion.js
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/eu/components/accordion/demo/index.js
Labels: tag: enhancement

#2982 feat(colors): ECL4 rename colors - FRONT-4046
  .size-limit.json
  docs/Migrating-v4.md
  src/implementations/vanilla/components/page-header/page-header-ec.scss
  src/implementations/vanilla/components/page-header/page-header-print-ec.scss
  src/themes/ec/_variables.scss
  src/themes/ec/maps/color.scss
  src/themes/eu/_variables.scss
  src/themes/eu/maps/color.scss
Labels: tag: enhancement

#2987 chore(deps): Updates 11-08-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2990 chore(deps): Updates 16-08-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/builder.test.js
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2995 chore(deps): Updates 21-08-23
  package.json
  src/implementations/vanilla/components/news-ticker/_news-ticker.scss
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2993 feat(twitter): Replacing icon with X - FRONT-4061
  src/resources/icons-social-media/src/social-media/twitter-color.svg
  src/resources/icons-social-media/src/social-media/twitter-negative.svg
  src/resources/icons-social-media/src/social-media/twitter.svg
Labels: tag: enhancement

#2986 feat(site-header): EC site header, v4
  .size-limit.json
  docs/Migrating-v4.md
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/site-header/ec-site-header.story.js
  src/implementations/twig/components/site-header/site-header-language-switcher.html.twig
  src/implementations/twig/components/site-header/site-header.html.twig
  src/implementations/vanilla/components/search-form/_search-form.scss
  src/implementations/vanilla/components/site-header/_site-header-language-switcher.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/implementations/vanilla/components/site-header/site-header.js
  src/presets/ec/package.json
  src/resources/icons-ec/src/all/global.svg
  src/resources/icons-ec/src/all/hamburger.svg
  src/resources/icons-ec/src/all/log-in.svg
  src/resources/icons-ec/src/all/logged-in.svg
  src/resources/icons-ec/src/all/search.svg
  src/specs/components/site-header/demo/data--ec.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#2991 feat(content-block): V4 revamp for EC - FRONT-4055
  src/implementations/twig/components/content-block/__snapshots__/content-block.test.js.snap
  src/implementations/twig/components/content-block/content-block.html.twig
  src/implementations/vanilla/components/content-block/_content-block-print.scss
  src/implementations/vanilla/components/content-block/_content-block.scss
  src/implementations/vanilla/components/content-block/content-block-ec.scss
  src/implementations/vanilla/components/content-block/content-block-eu.scss
  src/implementations/vanilla/components/content-block/content-block-print-ec.scss
  src/implementations/vanilla/components/content-block/content-block-print-eu.scss
  src/implementations/vanilla/components/content-block/package.json
  src/implementations/vanilla/components/description-list/_description-list.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/specs/components/content-block/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/ec/maps/color.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#2988 chore(ci): Add ec and eu presets in release artifacts on github - FRONT-4054
  .github/workflows/production.yml
  scripts/packagesList.sh
Labels: tag: internal

#2974 docs(color): update color pages - FRONT-4029
  src/themes/ec/maps/color.scss
  src/themes/ec/tokens.json
  src/themes/eu/tokens.json
  src/website/src/pages/ec/guidelines/colours/index.mdx
  src/website/src/pages/eu/guidelines/colours/index.mdx
  src/website/src/website-components/Color/Card.jsx
  src/website/src/website-components/Color/Card.scss
  src/website/src/website-components/Color/Palette.jsx
  src/website/src/website-components/Color/PaletteItem.jsx
  src/website/src/website-components/Color/PaletteItem.scss
  src/website/src/website-components/index.js
Labels: tag: documentation

#2999 chore(deps): Updates - 24-08-23
  package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2992 feat(date-block): EC revamp for v4 - FRONT-4060
  src/implementations/twig/components/date-block/date-block.story.js
  src/implementations/vanilla/components/date-block/_date-block.scss
  src/implementations/vanilla/components/date-block/date-block-ec.scss
  src/implementations/vanilla/components/date-block/date-block-eu.scss
  src/implementations/vanilla/components/date-block/date-block-print.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/themes/dev/maps/shape.scss
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/themes/eu/maps/color.scss
  src/themes/eu/maps/shape.scss
  src/website/src/pages/ec/components/date-block/demo/index.js
  src/website/src/pages/ec/components/date-block/docs/code.mdx
  src/website/src/pages/eu/components/date-block/demo/index.js
  src/website/src/pages/eu/components/date-block/docs/code.mdx
Labels: tag: enhancement

#3001 chore(website): Clean up markdown.scss file - FRONT-4070
  src/website/public/admin/markdown.css
Labels: tag: internal

#2989 chore(docs): Getting started, revisited + cookie banner - FRONT-4053
  src/website/public/index.html
  src/website/src/pages/ec/getting-started/index.mdx
  src/website/src/pages/eu/getting-started/index.mdx
Labels: tag: documentation, tag: enhancement

#3004 chore(deps): Updates 29-08-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3002 feat(card): ECL4 Card - FRONT-4057
  src/implementations/twig/components/card/__snapshots__/card.test.js.snap
  src/implementations/twig/components/card/card.story.js
  src/implementations/vanilla/components/card/_card.scss
  src/implementations/vanilla/components/card/card-ec.scss
  src/implementations/vanilla/components/card/card-eu.scss
  src/implementations/vanilla/components/card/package.json
  src/implementations/vanilla/components/content-block/_content-block.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/specs/components/card/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/themes/eu/theme.scss
  src/website/src/pages/ec/components/card/demo/index.js
  src/website/src/pages/ec/components/card/docs/code.mdx
  src/website/src/pages/eu/components/card/demo/index.js
  src/website/src/pages/eu/components/card/docs/code.mdx
Labels: tag: enhancement

#2997 feat(content item): ECL4 content item - FRONT-4056
  src/implementations/twig/components/content-item/content-item.story.js
  src/implementations/vanilla/components/content-block/_content-block-print.scss
  src/implementations/vanilla/components/content-block/_content-block.scss
  src/implementations/vanilla/components/content-block/package.json
  src/implementations/vanilla/components/content-item/_content-item-print.scss
  src/implementations/vanilla/components/content-item/_content-item.scss
  src/implementations/vanilla/components/content-item/content-item-ec.scss
  src/implementations/vanilla/components/content-item/content-item-eu.scss
  src/implementations/vanilla/components/content-item/content-item-print-ec.scss
  src/implementations/vanilla/components/content-item/content-item-print-eu.scss
  src/implementations/vanilla/components/content-item/package.json
  src/implementations/vanilla/components/description-list/_description-list.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/resources/icons-ec/src/all/copy.svg
  src/resources/icons-ec/src/all/download.svg
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#2996 feat(textarea): EC revamp for v4 - FRONT-4064
  src/implementations/twig/components/form-group/__snapshots__/form-group.test.js.snap
  src/implementations/twig/components/form-group/form-group.html.twig
  src/implementations/twig/components/form-group/form-group.story.js
  src/implementations/vanilla/components/form-group/_form-group.scss
  src/implementations/vanilla/components/text-area/_text-area.scss
  src/implementations/vanilla/components/text-area/text-area-ec.scss
  src/implementations/vanilla/components/text-area/text-area-eu.scss
  src/implementations/vanilla/components/text-input/_text-input.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/themes/dev/mixins/mixins.scss
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#2985 feat(menu): ECL4 menu - FRONT-4032
  docs/Migrating-v4.md
  src/implementations/twig/components/link/link.html.twig
  src/implementations/twig/components/link/link.story.js
  src/implementations/twig/components/menu/README.md
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/menu-item.html.twig
  src/implementations/twig/components/menu/menu.html.twig
  src/implementations/twig/components/menu/menu.story.js
  src/implementations/twig/components/menu/menu.test.js
  src/implementations/twig/components/site-header/ec-site-header.story.js
  src/implementations/twig/components/site-header/eu-site-header.story.js
  src/implementations/vanilla/components/link/_link.scss
  src/implementations/vanilla/components/link/package.json
  src/implementations/vanilla/components/menu/_menu.scss
  src/implementations/vanilla/components/menu/menu-ec.scss
  src/implementations/vanilla/components/menu/menu-eu.scss
  src/implementations/vanilla/components/menu/menu.js
  src/implementations/vanilla/components/menu/package.json
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/specs/components/menu/demo/data--ec-long.js
  src/specs/components/menu/demo/data--ec.js
  src/specs/components/menu/demo/data--en.js
  src/specs/components/menu/demo/data--eu-long.js
  src/specs/components/menu/demo/data--eu.js
  src/specs/components/menu/demo/data--fr.js
  src/specs/components/notification/demo/data--error-ec.js
  src/specs/components/notification/demo/data--error-eu.js
  src/specs/components/notification/demo/data--info-ec.js
  src/specs/components/notification/demo/data--info-eu.js
  src/specs/components/notification/demo/data--success-ec.js
  src/specs/components/notification/demo/data--success-eu.js
  src/specs/components/notification/demo/data--warning-ec.js
  src/specs/components/notification/demo/data--warning-eu.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/navigation/menu/demo/index.js
  src/website/src/pages/eu/components/navigation/menu/demo/index.js
Labels: tag: enhancement
