Repository ec-europa/europa-component-library, pull requests merged in 2023-11, with the labels that each got.

#3089 feat(css): add variables for stroke and overlay - FRONT-4129
  .size-limit.json
  src/themes/ec/_variables.scss
  src/themes/ec/maps/color.scss
Labels: tag: enhancement, process: review needed

#3083 chore(js): Storing instances in their init() in a Map object - FRONT-4130
  .eslintrc.js
  .size-limit.json
  docs/javascript.md
  src/implementations/vanilla/components/accordion/accordion.js
  src/implementations/vanilla/components/breadcrumb-core/breadcrumb-core.js
  src/implementations/vanilla/components/breadcrumb-harmonised/breadcrumb-harmonised.js
  src/implementations/vanilla/components/breadcrumb-standardised/breadcrumb-standardised.js
  src/implementations/vanilla/components/breadcrumb/breadcrumb.js
  src/implementations/vanilla/components/carousel/carousel.js
  src/implementations/vanilla/components/category-filter/category-filter.js
  src/implementations/vanilla/components/content-block/content-block.js
  src/implementations/vanilla/components/datepicker/datepicker.js
  src/implementations/vanilla/components/description-list/description-list.js
  src/implementations/vanilla/components/expandable/expandable.js
  src/implementations/vanilla/components/file-upload/file-upload.js
  src/implementations/vanilla/components/file/file.js
  src/implementations/vanilla/components/gallery/gallery.js
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation.js
  src/implementations/vanilla/components/media-container/media-container.js
  src/implementations/vanilla/components/menu/menu.js
  src/implementations/vanilla/components/message/message.js
  src/implementations/vanilla/components/modal/modal.js
  src/implementations/vanilla/components/news-ticker/news-ticker.js
  src/implementations/vanilla/components/popover/popover.js
  src/implementations/vanilla/components/range/range.js
  src/implementations/vanilla/components/select/select.js
  src/implementations/vanilla/components/site-header-core/site-header-core.js
  src/implementations/vanilla/components/site-header-harmonised/site-header-harmonised.js
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised.js
  src/implementations/vanilla/components/site-header/site-header.js
  src/implementations/vanilla/components/table/table.js
  src/implementations/vanilla/components/tabs/tabs.js
  src/implementations/vanilla/components/timeline/timeline.js
  src/tools/dom-utils/autoinit/index.js
  src/website/src/pages/ec/components/accordion/docs/api.mdx
  src/website/src/pages/ec/components/carousel/docs/api.mdx
  src/website/src/pages/ec/components/category-filter/docs/api.mdx
  src/website/src/pages/ec/components/expandable/docs/api.mdx
  src/website/src/pages/ec/components/file/docs/api.mdx
  src/website/src/pages/ec/components/media/gallery/docs/api.mdx
  src/website/src/pages/ec/components/message/docs/api.mdx
  src/website/src/pages/ec/components/modal/docs/api.mdx
  src/website/src/pages/ec/components/news-ticker/docs/api.mdx
  src/website/src/pages/ec/components/popover/docs/api.mdx
  src/website/src/pages/ec/components/table/docs/api.mdx
  src/website/src/pages/ec/components/timeline/docs/api.mdx
  src/website/src/pages/eu/components/accordion/docs/api.mdx
  src/website/src/pages/eu/components/carousel/docs/api.mdx
  src/website/src/pages/eu/components/category-filter/docs/api.mdx
  src/website/src/pages/eu/components/expandable/docs/api.mdx
  src/website/src/pages/eu/components/file/docs/api.mdx
  src/website/src/pages/eu/components/media/gallery/docs/api.mdx
  src/website/src/pages/eu/components/message/docs/api.mdx
  src/website/src/pages/eu/components/modal/docs/api.mdx
  src/website/src/pages/eu/components/news-ticker/docs/api.mdx
  src/website/src/pages/eu/components/popover/docs/api.mdx
  src/website/src/pages/eu/components/table/docs/api.mdx
  src/website/src/pages/eu/components/timeline/docs/api.mdx
Labels: tag: enhancement

#3090 chore(deps): Updates 03-11-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3088 feat(utilities): use css variables - FRONT-4123
  .size-limit.json
  src/implementations/twig/utilities/border/index.story.js
  src/implementations/twig/utilities/dimension/index.story.js
  src/implementations/twig/utilities/display/index.story.js
  src/implementations/twig/utilities/media/index.story.js
  src/implementations/twig/utilities/shadow/index.story.js
  src/implementations/twig/utilities/typography/index.story.js
  src/implementations/vanilla/components/media-container/_media-container.scss
  src/implementations/vanilla/layout/grid/grid.scss
  src/implementations/vanilla/layout/grid/mixins/_breakpoints.scss
  src/implementations/vanilla/layout/grid/mixins/_grid-framework.scss
  src/implementations/vanilla/layout/grid/mixins/_grid.scss
  src/implementations/vanilla/layout/grid/package.json
  src/implementations/vanilla/utilities/background/background-print.scss
  src/implementations/vanilla/utilities/background/background.scss
  src/implementations/vanilla/utilities/background/package.json
  src/implementations/vanilla/utilities/border/border-print.scss
  src/implementations/vanilla/utilities/border/border.scss
  src/implementations/vanilla/utilities/border/package.json
  src/implementations/vanilla/utilities/display/display-print.scss
  src/implementations/vanilla/utilities/display/display.scss
  src/implementations/vanilla/utilities/display/package.json
  src/implementations/vanilla/utilities/flex/flex-print.scss
  src/implementations/vanilla/utilities/flex/flex.scss
  src/implementations/vanilla/utilities/flex/package.json
  src/implementations/vanilla/utilities/media/media-print.scss
  src/implementations/vanilla/utilities/media/media.scss
  src/implementations/vanilla/utilities/media/package.json
  src/implementations/vanilla/utilities/shadow/package.json
  src/implementations/vanilla/utilities/shadow/shadow-print.scss
  src/implementations/vanilla/utilities/shadow/shadow.scss
  src/implementations/vanilla/utilities/spacing/package.json
  src/implementations/vanilla/utilities/spacing/spacing-print.scss
  src/implementations/vanilla/utilities/spacing/spacing.scss
  src/implementations/vanilla/utilities/typography/_typography-print.scss
  src/implementations/vanilla/utilities/typography/_typography.scss
  src/implementations/vanilla/utilities/typography/package.json
  src/implementations/vanilla/utilities/typography/typography-ec.scss
  src/implementations/vanilla/utilities/typography/typography-eu.scss
  src/implementations/vanilla/utilities/typography/typography-print-ec.scss
  src/implementations/vanilla/utilities/typography/typography-print-eu.scss
  src/presets/ec/src/ec-default-print.scss
  src/presets/ec/src/ec-default.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-default-print.scss
  src/presets/eu/src/eu-default.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/themes/eu/theme.scss
  src/website/src/components/Grid/grid.scss
  src/website/src/pages/ec/guidelines/typography/index.mdx
  src/website/src/pages/ec/utilities/typography/docs/code.mdx
  src/website/src/pages/eu/utilities/typography/docs/code.mdx
  src/website/src/website-components/Spacing/Spacing.scss
Labels: tag: enhancement

#3093 feat(logo): Hebrew, adding logos in EC and EU - FRONT-4133
  src/resources/logo-ec/src/negative/logo-ec--he.svg
  src/resources/logo-ec/src/positive/logo-ec--he.svg
  src/resources/logo-eu/src/condensed-version/negative/logo-eu--he.svg
  src/resources/logo-eu/src/condensed-version/positive/logo-eu--he.svg
  src/resources/logo-eu/src/standard-version/negative/logo-eu--he.svg
  src/resources/logo-eu/src/standard-version/positive/logo-eu--he.svg
Labels: tag: new feature

#3075 feat(inpage-navigation): EC revamp for v4 - FRONT-4116
  docs/Migrating-v4.md
  src/implementations/twig/components/inpage-navigation/README.md
  src/implementations/twig/components/inpage-navigation/__snapshots__/inpage-navigation.test.js.snap
  src/implementations/twig/components/inpage-navigation/inpage-navigation.html.twig
  src/implementations/twig/components/inpage-navigation/inpage-navigation.story.js
  src/implementations/vanilla/components/inpage-navigation/_inpage-navigation.scss
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation-ec.scss
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation-eu.scss
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation.js
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/specs/components/inpage-navigation/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#3091 feat(modal): ECL4 modal - FRONT-4132
  docs/Migrating-v4.md
  src/implementations/twig/components/modal/README.md
  src/implementations/twig/components/modal/__snapshots__/modal.test.js.snap
  src/implementations/twig/components/modal/modal.html.twig
  src/implementations/twig/components/modal/modal.story.js
  src/implementations/twig/components/modal/modal.test.js
  src/implementations/vanilla/components/modal/_modal.scss
  src/implementations/vanilla/components/modal/modal-ec.scss
  src/implementations/vanilla/components/modal/modal-eu.scss
  src/implementations/vanilla/components/modal/package.json
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/specs/components/modal/demo/data-ec.js
  src/specs/components/modal/demo/data-eu.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/modal/demo/index.js
  src/website/src/pages/ec/components/modal/docs/code.mdx
  src/website/src/pages/eu/components/modal/demo/index.js
  src/website/src/pages/eu/components/modal/docs/code.mdx
Labels: tag: enhancement

#3096 chore(deps): Updates 08-11-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3098 fix(website): Fixing story utils setting the path to svgs - FRONT-4140
  src/playground/addons/story-utils/index.js
  src/website/src/utils/correctSvgPath.js
Labels: tag: bug fix

#3100 chore(deps): Updates - 10-11-23
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/resources/icons-ec/package.json
  src/resources/icons-eu/package.json
  src/resources/icons-flag/package.json
  src/resources/icons-social-media/package.json
  src/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3092 feat(print): Finalizing iteration - FRONT-4127
  src/implementations/vanilla/components/accordion/accordion-print.scss
  src/implementations/vanilla/components/fact-figures/fact-figures-print.scss
  src/implementations/vanilla/components/featured-item/_featured-item-print.scss
  src/implementations/vanilla/components/link/_link-print.scss
  src/implementations/vanilla/components/media-container/media-container-print.scss
Labels: tag: enhancement

#3095 feat(blockquote): Changing quotes signs basing on the language - FRONT-4135
  .size-limit.json
  package.json
  src/implementations/twig/components/blockquote/README.md
  src/implementations/twig/components/blockquote/__snapshots__/blockquote.test.js.snap
  src/implementations/twig/components/blockquote/blockquote.html.twig
  src/implementations/twig/components/blockquote/blockquote.story.js
  src/implementations/vanilla/components/blockquote/_blockquote-print.scss
  src/implementations/vanilla/components/blockquote/_blockquote.scss
  src/playground/addons/story-utils/index.js
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/resources/icons-ec/package.json
  src/resources/icons-eu/package.json
  src/resources/icons-flag/package.json
  src/resources/icons-social-media/package.json
  src/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  src/website/src/utils/correctSvgPath.js
  yarn.lock
Labels: tag: enhancement

#3097 feat(news-ticker): ECL4 news ticker - FRONT-4138
  src/implementations/twig/components/news-ticker/__snapshots__/news-ticker.test.js.snap
  src/implementations/twig/components/news-ticker/news-ticker.html.twig
  src/implementations/vanilla/components/news-ticker/_news-ticker.scss
  src/implementations/vanilla/components/news-ticker/news-ticker.js
  src/specs/components/news-ticker/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#3105 feat(skip link): ECL4 skip link - FRONT-4141
  src/implementations/twig/components/skip-link/__snapshots__/skip-link.test.js.snap
  src/implementations/twig/components/skip-link/package.json
  src/implementations/twig/components/skip-link/skip-link.html.twig
  src/implementations/twig/components/skip-link/skip-link.story.js
  src/implementations/vanilla/components/skip-link/package.json
  src/implementations/vanilla/components/skip-link/skip-link.scss
  src/implementations/vanilla/utilities/screen-reader/screen-reader.scss
Labels: tag: enhancement, process: review needed

#3099 feat(button): add tertiary and ghost-inverted variants - FRONT-4139
  src/implementations/twig/components/button/README.md
  src/implementations/twig/components/button/__snapshots__/button.test.js.snap
  src/implementations/twig/components/button/button.html.twig
  src/implementations/twig/components/button/button.story.js
  src/implementations/twig/components/button/button.test.js
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/menu.html.twig
  src/implementations/twig/components/modal/__snapshots__/modal.test.js.snap
  src/implementations/twig/components/modal/modal.html.twig
  src/implementations/twig/components/notification/__snapshots__/notification.test.js.snap
  src/implementations/twig/components/notification/notification.html.twig
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/site-header/site-header-language-switcher.html.twig
  src/implementations/twig/components/site-header/site-header.html.twig
  src/implementations/twig/compositions/etrans/__snapshots__/etrans.test.js.snap
  src/implementations/vanilla/components/button/_button.scss
  src/implementations/vanilla/components/modal/_modal.scss
  src/implementations/vanilla/components/site-header/_site-header-language-switcher.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/specs/components/button/demo/data--ghost-inverted.js
  src/specs/components/button/demo/data--tertiary.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/button/demo/index.js
  src/website/src/pages/ec/components/button/docs/code.mdx
  src/website/src/pages/eu/components/button/demo/index.js
  src/website/src/pages/eu/components/button/docs/code.mdx
  src/website/src/website-components/Html.jsx
Labels: tag: enhancement

#3101 feat(gallery): EC revamp for - FRONT-4137
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/twig/components/gallery/gallery-item.html.twig
  src/implementations/twig/components/gallery/gallery-overlay.html.twig
  src/implementations/twig/components/gallery/gallery.html.twig
  src/implementations/twig/components/icon/icon.story.js
  src/implementations/vanilla/components/gallery/_gallery.scss
  src/implementations/vanilla/components/gallery/gallery-print.scss
  src/implementations/vanilla/components/gallery/gallery.js
  src/implementations/vanilla/components/link/_link.scss
  src/resources/icons-ec/src/all/corner-arrow.svg
  src/resources/icons-ec/src/all/fullscreen.svg
  src/resources/icons-ec/src/all/share.svg
  src/specs/components/gallery/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/media/gallery/docs/code.mdx
  src/website/src/pages/eu/components/media/gallery/docs/code.mdx
Labels: tag: enhancement

#3107 fix(gallery): Safer code in updateOverlay() method - FRONT-4148
  src/implementations/vanilla/components/gallery/gallery.js
Labels: tag: bug fix

#3106 feat(pagination): EC revamp for v4 - FRONT-4144
  docs/Migrating-v4.md
  src/implementations/twig/components/pagination/README.md
  src/implementations/twig/components/pagination/__snapshots__/pagination.test.js.snap
  src/implementations/twig/components/pagination/pagination.html.twig
  src/implementations/twig/components/pagination/pagination.story.js
  src/implementations/vanilla/components/pagination/_pagination.scss
  src/specs/components/pagination/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#3102 feat(social media follow): ECL4 Social Media Follow - FRONT-4142
  docs/Migrating-v4.md
  src/implementations/twig/components/icon/__snapshots__/icon.test.js.snap
  src/implementations/twig/components/social-media-follow/README.md
  src/implementations/twig/components/social-media-follow/__snapshots__/social-media-follow.test.js.snap
  src/implementations/twig/components/social-media-follow/package.json
  src/implementations/twig/components/social-media-follow/social-media-follow.html.twig
  src/implementations/twig/components/social-media-follow/social-media-follow.story.js
  src/implementations/twig/components/social-media-follow/social-media-follow.test.js
  src/implementations/vanilla/components/banner/package.json
  src/implementations/vanilla/components/popover/_popover.scss
  src/implementations/vanilla/components/social-media-follow/_social-media-follow.scss
  src/implementations/vanilla/components/social-media-follow/social-media-follow-print.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/package.json
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/resources/icons-ec/src/all/chain.svg
  src/resources/icons-eu/src/all/chain.svg
  src/resources/icons-social-media/src/social-media/chain-color.svg
  src/resources/icons-social-media/src/social-media/chain-negative.svg
  src/resources/icons-social-media/src/social-media/chain.svg
  src/resources/icons-social-media/src/social-media/share-color.svg
  src/resources/icons-social-media/src/social-media/share-negative.svg
  src/resources/icons-social-media/src/social-media/share.svg
  src/specs/components/social-media-follow/demo/data--ec.js
  src/specs/components/social-media-follow/demo/data--eu.js
  src/specs/components/social-media-follow/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/social-media-follow/demo/index.js
  src/website/src/pages/ec/components/social-media-follow/docs/code.mdx
  src/website/src/pages/eu/components/social-media-follow/demo/index.js
  src/website/src/pages/eu/components/social-media-follow/docs/code.mdx
Labels: tag: enhancement

#3114 chore(deps): Updates - 24-11-23
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/resources/icons-ec/package.json
  src/resources/icons-eu/package.json
  src/resources/icons-flag/package.json
  src/resources/icons-social-media/package.json
  src/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3110 feat(styles): update active state display - FRONT-4143
  src/themes/ec/_variables.scss
Labels: tag: enhancement

#3115 fix(EU footer): fix section display for mobile/desktop
  src/implementations/twig/components/site-footer/__snapshots__/site-footer.test.js.snap
  src/specs/components/site-footer/demo/data-core--eu.js
  src/specs/components/site-footer/demo/data-harmonised--eu.js
Labels: tag: bug fix

#3103 chore(css): Separating utilities - FRONT-4134
  .size-limit.json
  docs/Migrating-v4.md
  src/playground/ec/.storybook/preview-head.html
  src/playground/ec/.storybook/preview.js
  src/playground/eu/.storybook/preview-head.html
  src/playground/eu/.storybook/preview.js
  src/presets/ec/ecl-builder.config.js
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec-utilities.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/ecl-builder.config.js
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu-utilities.scss
  src/presets/eu/src/eu.scss
  src/themes/ec/_custom-properties.scss
  src/themes/ec/_variables.scss
  src/themes/eu/_custom-properties.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/getting-started/index.mdx
  src/website/src/pages/eu/getting-started/index.mdx
  src/website/src/routes/Skeleton.jsx
  src/website/webpack.config.prod.js
Labels: tag: new feature

#3113 feat(content-item): add image top variant - FRONT-4155
  docs/Migrating-v4.md
  src/implementations/twig/components/content-item/README.md
  src/implementations/twig/components/content-item/__snapshots__/content-item.test.js.snap
  src/implementations/twig/components/content-item/content-item.html.twig
  src/implementations/twig/components/content-item/content-item.story.js
  src/implementations/vanilla/components/content-item/_content-item-print.scss
  src/implementations/vanilla/components/content-item/_content-item.scss
  src/specs/components/content-item/demo/data--image.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/content-item/demo/index.js
  src/website/src/pages/ec/components/content-item/docs/code.mdx
  src/website/src/pages/eu/components/content-item/demo/index.js
  src/website/src/pages/eu/components/content-item/docs/code.mdx
Labels: tag: enhancement

#3117 feat(accordion): ECL4 accordion refinement - FRONT-4157
  src/implementations/twig/components/accordion/__snapshots__/accordion.test.js.snap
  src/implementations/twig/components/accordion/accordion.html.twig
  src/implementations/vanilla/components/accordion/accordion-ec.scss
  src/implementations/vanilla/components/accordion/accordion-eu.scss
Labels: tag: enhancement

#3120 chore(markup): Replacing h1 with divs - FRONT-4160
  src/implementations/twig/components/card/__snapshots__/card.test.js.snap
  src/implementations/twig/components/content-block/__snapshots__/content-block.test.js.snap
  src/implementations/twig/components/content-block/content-block.html.twig
  src/implementations/twig/components/content-item/__snapshots__/content-item.test.js.snap
  src/implementations/twig/components/navigation-list/__snapshots__/navigation-list.test.js.snap
Labels: tag: enhancement

#3109 feat(splash-page): Add splash page component - FRONT-4146
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/site-header/site-header-language-switcher.html.twig
  src/implementations/twig/components/splash-page/.npmignore
  src/implementations/twig/components/splash-page/README.md
  src/implementations/twig/components/splash-page/__snapshots__/splash-page.test.js.snap
  src/implementations/twig/components/splash-page/package.json
  src/implementations/twig/components/splash-page/splash-page.html.twig
  src/implementations/twig/components/splash-page/splash-page.story.js
  src/implementations/twig/components/splash-page/splash-page.test.js
  src/implementations/vanilla/components/site-header/_site-header-language-switcher.scss
  src/implementations/vanilla/components/splash-page/README.md
  src/implementations/vanilla/components/splash-page/package.json
  src/implementations/vanilla/components/splash-page/splash-page-print.scss
  src/implementations/vanilla/components/splash-page/splash-page.scss
  src/presets/ec/package.json
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/package.json
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/specs/components/splash-page/demo/data--ec.js
  src/specs/components/splash-page/demo/data--eu.js
  src/specs/components/splash-page/package.json
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/index.mdx
  src/website/src/pages/ec/components/splash-page/demo/index.js
  src/website/src/pages/ec/components/splash-page/docs/code.mdx
  src/website/src/pages/ec/components/splash-page/docs/usage.md
  src/website/src/pages/ec/components/splash-page/ec_comp_splash-page.svg
  src/website/src/pages/ec/components/splash-page/index.md
  src/website/src/pages/eu/components/index.mdx
  src/website/src/pages/eu/components/splash-page/demo/index.js
  src/website/src/pages/eu/components/splash-page/docs/code.mdx
  src/website/src/pages/eu/components/splash-page/docs/usage.md
  src/website/src/pages/eu/components/splash-page/eu_comp_splash-page.svg
  src/website/src/pages/eu/components/splash-page/index.md
Labels: tag: new feature

#3125 chore(deps): Updates 28-11-23
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  yarn.lock
Labels: tag: internal

#3122 chore(css): Removing usage of start and end in flex context - FRONT-4163
  src/implementations/vanilla/components/accordion/accordion-ec.scss
  src/implementations/vanilla/components/accordion/accordion-eu.scss
  src/implementations/vanilla/components/banner/_banner.scss
  src/implementations/vanilla/components/blockquote/_blockquote-print.scss
  src/implementations/vanilla/components/blockquote/_blockquote.scss
  src/implementations/vanilla/components/carousel/_carousel.scss
  src/implementations/vanilla/components/hero-banner/_hero-banner.scss
  src/implementations/vanilla/components/message/_message.scss
  src/implementations/vanilla/components/page-banner/_page-banner.scss
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised-ec.scss
  src/implementations/vanilla/components/site-header-standardised/site-header-standardised-eu.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
Labels: tag: enhancement
