Repository ec-europa/europa-component-library, pull requests merged in 2023-02, with the labels that each got.

#2712 feat(select): Grouping capabilities for simple and multiple select - FRONT-3542
  src/implementations/twig/components/select/__snapshots__/select.test.js.snap
  src/implementations/twig/components/select/select.html.twig
  src/implementations/vanilla/components/select/_select.scss
  src/implementations/vanilla/components/select/select-ec.scss
  src/implementations/vanilla/components/select/select-eu.scss
  src/implementations/vanilla/components/select/select.js
  src/specs/components/select/demo/data-multiple.js
  src/specs/components/select/demo/data-single.js
Labels: tag: new feature

#2739 feat(popover): improve usability - FRONT-3841
  .size-limit.json
  src/implementations/vanilla/components/popover/_popover.scss
  src/implementations/vanilla/components/popover/popover.js
Labels: tag: enhancement

#2735 feat(social media share): add popover - FRONT-3830
  src/implementations/twig/components/popover/popover.html.twig
  src/implementations/twig/components/social-media-follow/README.md
  src/implementations/twig/components/social-media-follow/__snapshots__/social-media-follow.test.js.snap
  src/implementations/twig/components/social-media-follow/package.json
  src/implementations/twig/components/social-media-follow/social-media-follow.html.twig
  src/implementations/twig/components/social-media-follow/social-media-follow.story.js
  src/implementations/twig/components/social-media-share/README.md
  src/implementations/twig/components/social-media-share/__snapshots__/social-media-share.test.js.snap
  src/implementations/twig/components/social-media-share/package.json
  src/implementations/twig/components/social-media-share/social-media-share.html.twig
  src/implementations/twig/components/social-media-share/social-media-share.story.js
  src/implementations/vanilla/components/popover/_popover.scss
  src/implementations/vanilla/components/social-media-follow/_social-media-follow.scss
  src/implementations/vanilla/components/social-media-share/_social-media-share.scss
  src/specs/components/social-media-follow/demo/data.js
  src/specs/components/social-media-share/demo/data.js
Labels: tag: new feature, tag: markup changes

#2715 feat(site-header): add message box - FRONT-3760
  src/implementations/twig/components/site-header/README.md
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/site-header/ec-site-header.story.js
  src/implementations/twig/components/site-header/eu-site-header.story.js
  src/implementations/twig/components/site-header/package.json
  src/implementations/twig/components/site-header/site-header.html.twig
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/specs/components/site-header/demo/data--ec.js
  src/specs/components/site-header/demo/data--eu.js
Labels: tag: new feature, tag: markup changes

#2745 fix(list): fix nested bullet position - FRONT-3847
  src/implementations/vanilla/components/ordered-list/_ordered-list.scss
  src/implementations/vanilla/components/unordered-list/_unordered-list.scss
  src/presets/ec/src/ec-default-print.scss
  src/presets/ec/src/ec-default.scss
  src/presets/eu/src/eu-default-print.scss
  src/presets/eu/src/eu-default.scss
Labels: tag: bug fix

#2742 feat(carousel): add different sizes - FRONT-3842
  src/implementations/twig/components/carousel/__snapshots__/carousel.test.js.snap
  src/implementations/twig/components/carousel/carousel.html.twig
  src/implementations/twig/components/carousel/carousel.story.js
  src/implementations/twig/components/carousel/package.json
  src/implementations/vanilla/components/banner/_banner.scss
  src/implementations/vanilla/components/carousel/_carousel.scss
  src/implementations/vanilla/components/carousel/carousel.js
  src/website/src/pages/ec/components/carousel/docs/code.mdx
  src/website/src/pages/ec/components/carousel/index.md
  src/website/src/pages/eu/components/carousel/docs/code.mdx
  src/website/src/pages/eu/components/carousel/index.md
Labels: tag: new feature

#2747 feat(banner): Rename variants - FRONT-3845
  src/implementations/twig/components/banner/README.md
  src/implementations/twig/components/banner/__snapshots__/banner.test.js.snap
  src/implementations/twig/components/banner/banner.html.twig
  src/implementations/twig/components/banner/banner.story.js
  src/implementations/twig/components/banner/banner.test.js
  src/implementations/twig/components/carousel/README.md
  src/implementations/twig/components/carousel/__snapshots__/carousel.test.js.snap
  src/implementations/vanilla/components/banner/_banner.scss
  src/implementations/vanilla/components/banner/banner-ec.scss
  src/implementations/vanilla/components/banner/banner-eu.scss
  src/specs/components/banner/demo/data--image-overlay.js
  src/specs/components/banner/demo/data--plain-background.js
  src/specs/components/banner/demo/data--text-box.js
  src/specs/components/banner/demo/data--text-highlight.js
  src/specs/components/carousel/demo/data.js
  src/website/src/pages/ec/components/banner/demo/index.js
  src/website/src/pages/ec/components/banner/docs/code.mdx
  src/website/src/pages/eu/components/banner/demo/index.js
  src/website/src/pages/eu/components/banner/docs/code.mdx
Labels: tag: enhancement

#2746 feat(banner): update text background - FRONT-3843
  src/implementations/vanilla/components/banner/_banner.scss
Labels: tag: enhancement

#2748 chore(carousel): Changing default story
  src/implementations/twig/components/carousel/carousel.story.js
Labels: tag: internal

#2752 feat(EC Usage pages for components): update EC Usage pages for components “ec_carousel”
  src/website/src/pages/ec/components/carousel/docs/usage.md
Labels: netlify-cms/pending_publish

#2754 feat(EC Usage pages for components): update EC Usage pages for components “ec_select”
  src/website/src/pages/ec/components/forms/select/docs/usage.md
Labels: netlify-cms/pending_publish

#2753 feat(EU Usage pages for components): update EU Usage pages for components “eu_carousel”
  src/website/src/pages/eu/components/carousel/docs/usage.md
Labels: netlify-cms/pending_publish

#2755 feat(EU Usage pages for components): update EU Usage pages for components “eu_select”
  src/website/src/pages/eu/components/forms/select/docs/usage.md
Labels: netlify-cms/pending_publish

#2758 chore(deps): Updates 08-02-23
  package.json
  yarn.lock
Labels: tag: internal

#2760 feat(ci): Deploying every release branch, using node v16 in CI
  .github/workflows/ci.yml
  src/tools/builder/scripts/styles.js
Labels: tag: internal

#2763 chore(deps): Upgrading stylelint, no issue
  package.json
  yarn.lock
Labels: tag: internal

#2764 chore(deps): updates 09-02-23
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  yarn.lock
Labels: tag: internal

#2765 chore(svgo): Upgrading svgo and svg-sprite, minimal changes - FRONT-3855
  src/resources/icons-ec/package.json
  src/resources/icons-ec/scripts/clean-svg.js
  src/resources/icons-ec/scripts/config/svgo.js
  src/resources/icons-eu/package.json
  src/resources/icons-eu/scripts/clean-svg.js
  src/resources/icons-eu/scripts/config/svgo.js
  src/resources/icons-flag/package.json
  src/resources/icons-flag/scripts/clean-svg.js
  src/resources/icons-flag/scripts/config/svgo.js
  src/resources/icons-social-media/package.json
  src/resources/icons-social-media/scripts/clean-svg.js
  src/resources/icons-social-media/scripts/config/svgo.js
  src/resources/social-icons/package.json
  src/resources/social-icons/scripts/clean-svg.js
  src/resources/social-icons/scripts/config/svgo.js
  yarn.lock
Labels: tag: internal

#2761 fix(file): Using safer approach for label markup - FRONT-3854
  src/implementations/twig/components/file/file.html.twig
Labels: tag: bug fix

#2766 fix(print): fix logo duplicate - FRONT-3860
  src/implementations/vanilla/components/site-header/site-header-print.scss
Labels: tag: bug fix, process: review needed

#2762 chore(website): Fixing some errors in the website - FRONT-3853
  src/implementations/twig/components/popover/popover.story.js
  src/website/src/pages/ec/components/social-media-follow/docs/code.mdx
  src/website/src/pages/ec/components/social-media-share/docs/code.mdx
  src/website/src/pages/ec/deprecated/banners/hero-banner/docs/code.mdx
  src/website/src/pages/ec/deprecated/banners/page-banner/docs/code.mdx
  src/website/src/pages/eu/components/social-media-follow/docs/code.mdx
  src/website/src/pages/eu/components/social-media-share/docs/code.mdx
  src/website/src/pages/eu/deprecated/banners/hero-banner/docs/code.mdx
  src/website/src/pages/eu/deprecated/banners/page-banner/docs/code.mdx
Labels: tag: internal, process: review needed

#2770 chore(deps): Update 14-02-23
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#2769 fix(media-container): Better describing the way to use the ratio parameter - FRONT-3864
  src/implementations/twig/components/media-container/README.md
  src/implementations/twig/components/media-container/media-container.html.twig
  src/implementations/twig/components/media-container/media-container.story.js
Labels: tag: documentation, process: review needed

#2771 feat(colour): update utilities and doc - FRONT-3851
  src/implementations/vanilla/utilities/typography/_typography.scss
  src/themes/dev/maps/color.scss
  src/themes/eu/_index.scss
  src/website/src/pages/ec/guidelines/iconography/index.md
  src/website/src/pages/ec/utilities/typography/docs/usage.md
  src/website/src/pages/eu/guidelines/iconography/index.md
  src/website/src/pages/eu/utilities/typography/docs/usage.md
Labels: tag: enhancement

#2773 chore(deps): Updates 15-02-23
  package.json
  src/tools/builder/package.json
  yarn.lock
Labels: tag: internal

#2775 fix(footer): Updating links to the new commission website url - FRONT-3862
  src/implementations/twig/components/site-footer/__snapshots__/site-footer.test.js.snap
  src/specs/components/site-footer/demo/data-core--ec.js
  src/specs/components/site-footer/demo/data-harmonised--ec.js
  src/specs/components/site-footer/demo/data-standardised--ec.js
Labels: tag: enhancement, process: review needed

#2777 chore(node): Using gallium, locally and in CI (for deployments)
  .github/workflows/ci.yml
  .github/workflows/production.yml
  .nvmrc
Labels: tag: internal

#2778 fix(link): fix underline for link with icons - FRONT-3865
  src/implementations/vanilla/components/link/_link.scss
Labels: tag: bug fix

#2772 chore(icons): Replacing instagram-color icon with a plain color one
  .size-limit.json
  src/resources/icons-social-media/src/social-media/instagram-color.svg
  src/resources/icons-social-media/src/social-media/instagram.svg
  src/resources/icons-social-media/src/social-media/telegram-color.svg
Labels: tag: enhancement

#2768 chore(flags): Reducing icon sizes
  .size-limit.json
  src/resources/icons-flag/src/flag/croatia-square.svg
  src/resources/icons-flag/src/flag/croatia.svg
  src/resources/icons-flag/src/flag/cyprus-square.svg
  src/resources/icons-flag/src/flag/cyprus.svg
  src/resources/icons-flag/src/flag/malta-square.svg
  src/resources/icons-flag/src/flag/malta.svg
  src/resources/icons-flag/src/flag/portugal-square.svg
  src/resources/icons-flag/src/flag/portugal.svg
  src/resources/icons-flag/src/flag/slovenia-square.svg
  src/resources/icons-flag/src/flag/slovenia.svg
  src/resources/icons-flag/src/flag/spain-square.svg
  src/resources/icons-flag/src/flag/spain.svg
Labels: tag: enhancement

#2783 chore(deps): Updates 27-02-23
  package.json
  src/implementations/vanilla/components/gallery/package.json
  src/implementations/vanilla/components/site-header-core/package.json
  src/implementations/vanilla/components/site-header-harmonised/package.json
  src/implementations/vanilla/components/site-header-standardised/package.json
  src/implementations/vanilla/components/site-header/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal
