Repository ec-europa/europa-component-library, pull requests merged in 2023-12, with the labels that each got.

#3128 chore(deps): Updates 01-12-23
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/resources/icons-ec/package.json
  src/resources/icons-eu/package.json
  src/resources/icons-flag/package.json
  src/resources/icons-social-media/package.json
  src/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3074 feat(multi-select): improve accessiblity - FRONT-4114
  .size-limit.json
  src/implementations/twig/components/select/__snapshots__/select.test.js.snap
  src/implementations/twig/components/select/select.html.twig
  src/implementations/vanilla/components/select/_select.scss
  src/implementations/vanilla/components/select/package.json
  src/implementations/vanilla/components/select/select.js
  src/specs/components/select/demo/data-multiple.js
Labels: tag: enhancement, tag: markup changes

#3132 chore(deps): Updates 11-12-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/resources/icons-ec/package.json
  src/resources/icons-eu/package.json
  src/resources/icons-flag/package.json
  src/resources/icons-social-media/package.json
  src/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3112 feat(menu): improve accessibility - FRONT-4126
  src/implementations/twig/components/menu/README.md
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/menu-item.html.twig
  src/implementations/twig/components/menu/menu.html.twig
  src/implementations/twig/deprecated/site-header-core/__snapshots__/site-header-core.test.js.snap
  src/implementations/twig/deprecated/site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
  src/implementations/twig/deprecated/site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
  src/implementations/vanilla/components/menu/menu.js
  src/specs/components/menu/demo/data--en.js
  src/specs/components/menu/demo/data--fr.js
  src/specs/components/menu/demo/data--group1.js
  src/specs/components/menu/demo/data--group2.js
  src/specs/components/site-header-harmonised/demo/data--fr.js
  src/specs/components/site-header-harmonised/demo/data--group1.js
  src/specs/components/site-header-harmonised/demo/data--group2.js
Labels: tag: enhancement, tag: markup changes

#3133 chore(): Merge 3-dev in 4-dev
  package.json
  src/implementations/twig/components/select/select.html.twig
  src/implementations/vanilla/components/select/select.js
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/resources/icons-ec/package.json
  src/resources/icons-eu/package.json
  src/resources/icons-flag/package.json
  src/resources/icons-social-media/package.json
  src/resources/social-icons/package.json
  src/specs/components/select/demo/data-multiple.js
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3129 feat(language list): harmonize language list (splash page and site header) - FRONT-4164
  src/implementations/vanilla/components/site-header/_site-header-language-switcher.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/implementations/vanilla/components/splash-page/splash-page-print.scss
  src/implementations/vanilla/components/splash-page/splash-page.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#3131 feat(button): update EU button display - FRONT-4170
  src/implementations/vanilla/components/button/_button.scss
  src/implementations/vanilla/components/menu/_menu.scss
  src/specs/components/menu/demo/data--eu-long.js
  src/specs/components/menu/demo/data--eu.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#3139 fix(select): Using the id from the markup or adding a randomised one in the js - FRONT-4176
  src/implementations/vanilla/components/select/select.js
Labels: tag: bug fix

#3138 feat(blockquote): Moving the footer inside the blockquote element - FRONT-4175
  src/implementations/twig/components/blockquote/__snapshots__/blockquote.test.js.snap
  src/implementations/twig/components/blockquote/blockquote.html.twig
Labels: tag: enhancement

#3130 feat(tabs): ECL4 tabs - FRONT-4167
  docs/Migrating-v4.md
  src/implementations/twig/components/tabs/__snapshots__/tabs.test.js.snap
  src/implementations/twig/components/tabs/tabs.html.twig
  src/implementations/vanilla/components/tabs/_tabs.scss
  src/implementations/vanilla/components/tabs/tabs-print.scss
  src/implementations/vanilla/components/tabs/tabs.js
  src/presets/rtl/src/rtl.scss
  src/specs/components/tabs/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#3140 feat(banner): improve copyright markup
  src/implementations/twig/components/banner/__snapshots__/banner.test.js.snap
  src/implementations/twig/components/banner/banner.html.twig
  src/implementations/twig/components/carousel/__snapshots__/carousel.test.js.snap
  src/implementations/vanilla/components/banner/_banner.scss
Labels: tag: enhancement

#3142 chore(deps): v3, Updates 18-12-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3143 chore(deps): Updates 18-12-23, v4
  package.json
  src/implementations/twig/components/carousel/README.md
  src/implementations/twig/components/page-header/package.json
  src/implementations/twig/compositions/etrans/package.json
  src/implementations/vanilla/components/carousel/package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3123 feat(tag): Add tag set and wrapping - FRONT-4156
  docs/Migrating-v4.md
  src/implementations/twig/components/breadcrumb/README.md
  src/implementations/twig/components/breadcrumb/breadcrumb.html.twig
  src/implementations/twig/components/datepicker/README.md
  src/implementations/twig/components/datepicker/datepicker.html.twig
  src/implementations/twig/components/site-header/README.md
  src/implementations/twig/components/site-header/site-header-language-switcher.html.twig
  src/implementations/twig/components/site-header/site-header.html.twig
  src/implementations/twig/components/splash-page/README.md
  src/implementations/twig/components/splash-page/splash-page.html.twig
  src/implementations/twig/components/tag/README-tag-set.md
  src/implementations/twig/components/tag/README.md
  src/implementations/twig/components/tag/__snapshots__/tag.test.js.snap
  src/implementations/twig/components/tag/tag-set.html.twig
  src/implementations/twig/components/tag/tag-set.story.js
  src/implementations/twig/components/tag/tag.html.twig
  src/implementations/twig/components/tag/tag.story.js
  src/implementations/twig/components/tag/tag.test.js
  src/implementations/vanilla/components/tag/_tag.scss
  src/specs/components/breadcrumb/demo/data--long.js
  src/specs/components/breadcrumb/demo/data--simple.js
  src/specs/components/datepicker/demo/data.js
  src/specs/components/site-header/demo/data--ec.js
  src/specs/components/site-header/demo/data--eu.js
  src/specs/components/splash-page/demo/data--ec.js
  src/specs/components/splash-page/demo/data--eu.js
  src/specs/components/tag/demo/data--removable.js
  src/specs/components/tag/demo/data--set.js
  src/website/src/pages/ec/components/tag/demo/index.js
  src/website/src/pages/ec/components/tag/docs/code.mdx
  src/website/src/pages/eu/components/tag/demo/index.js
  src/website/src/pages/eu/components/tag/docs/code.mdx
Labels: tag: enhancement, process: review needed

#3146 feat(card): remove aria-label - FRONT-4180
  src/implementations/twig/components/card/__snapshots__/card.test.js.snap
  src/implementations/twig/components/card/card.html.twig
Labels: tag: enhancement

#3147 feat(labels): add aria-label to label areas (card, content-item) - FRONT-4181
  docs/Migrating-v4.md
  src/implementations/twig/components/card/README.md
  src/implementations/twig/components/card/__snapshots__/card.test.js.snap
  src/implementations/twig/components/card/card.html.twig
  src/implementations/twig/components/content-block/README.md
  src/implementations/twig/components/content-block/__snapshots__/content-block.test.js.snap
  src/implementations/twig/components/content-block/content-block.html.twig
  src/implementations/twig/components/content-item/README.md
  src/implementations/twig/components/content-item/__snapshots__/content-item.test.js.snap
  src/implementations/twig/components/content-item/content-item.html.twig
  src/specs/components/card/demo/data.js
  src/specs/components/content-block/demo/data.js
  src/specs/components/content-item/demo/data--default.js
  src/specs/components/content-item/demo/data--event.js
  src/specs/components/content-item/demo/data--image.js
Labels: tag: enhancement

#3145 feat(accordion): EU accordion refinement - FRONT-4179
  docs/Migrating-v4.md
  src/implementations/twig/components/accordion/README.md
  src/implementations/twig/components/accordion/__snapshots__/accordion.test.js.snap
  src/implementations/twig/components/accordion/accordion.html.twig
  src/implementations/twig/components/accordion/accordion.story.js
  src/implementations/vanilla/components/accordion/accordion-ec.scss
  src/implementations/vanilla/components/accordion/accordion-eu.scss
  src/implementations/vanilla/components/accordion/accordion-print.scss
  src/implementations/vanilla/components/accordion/accordion.js
  src/implementations/vanilla/components/accordion/package.json
  src/specs/components/accordion/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#3137 feat(form): improve accessibility - FRONT-4171
  docs/Migrating-v4.md
  src/implementations/twig/components/checkbox/README.md
  src/implementations/twig/components/checkbox/__snapshots__/checkbox.test.js.snap
  src/implementations/twig/components/checkbox/checkbox-group.html.twig
  src/implementations/twig/components/checkbox/checkbox-item.html.twig
  src/implementations/twig/components/datepicker/README.md
  src/implementations/twig/components/datepicker/__snapshots__/datepicker.test.js.snap
  src/implementations/twig/components/datepicker/datepicker.html.twig
  src/implementations/twig/components/form-group/README.md
  src/implementations/twig/components/form-group/__snapshots__/form-group.test.js.snap
  src/implementations/twig/components/form-group/form-group.html.twig
  src/implementations/twig/components/radio/README.md
  src/implementations/twig/components/radio/__snapshots__/radio.test.js.snap
  src/implementations/twig/components/radio/radio-button.html.twig
  src/implementations/twig/components/radio/radio-group.html.twig
  src/implementations/twig/components/rating-field/README.md
  src/implementations/twig/components/rating-field/rating-field.html.twig
  src/implementations/twig/components/select/__snapshots__/select.test.js.snap
  src/implementations/twig/components/select/select.html.twig
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/text-input/text-input.html.twig
  src/implementations/vanilla/components/select/_select.scss
  src/implementations/vanilla/components/select/select.js
  src/specs/components/checkbox/demo/data.js
  src/specs/components/datepicker/demo/data.js
  src/specs/components/file-upload/demo/data--multiple.js
  src/specs/components/file-upload/demo/data.js
  src/specs/components/radio/demo/data--binary.js
  src/specs/components/radio/demo/data--default.js
  src/specs/components/range/demo/data.js
  src/specs/components/rating-field/demo/data.js
  src/specs/components/select/demo/data-multiple.js
  src/specs/components/select/demo/data-single.js
  src/specs/components/text-area/demo/data.js
  src/specs/components/text-input/demo/data.js
Labels: tag: enhancement, process: review needed

#3151 feat(modal): add aria attributes - FRONT-4188
  src/implementations/twig/components/modal/__snapshots__/modal.test.js.snap
  src/implementations/twig/components/modal/modal.html.twig
Labels: tag: enhancement

#3149 feat(file): Moving aria-expanded attribute to the toggle button - FRONT-4185
  src/implementations/twig/components/file/__snapshots__/file.test.js.snap
  src/implementations/twig/components/file/file-translations.html.twig
  src/implementations/vanilla/components/file/_file.scss
  src/implementations/vanilla/components/file/file.js
Labels: tag: enhancement

#3150 feat(file): Setting aria-labelledby programmatically on download links - FRONT-4184
  docs/Migrating-v4.md
  src/implementations/twig/components/file/README.md
  src/implementations/twig/components/file/__snapshots__/file.test.js.snap
  src/implementations/twig/components/file/file-translation-item.html.twig
  src/implementations/twig/components/file/file-translations.html.twig
  src/implementations/twig/components/file/file.html.twig
  src/implementations/twig/components/file/file.test.js
  src/implementations/twig/components/link/link.html.twig
  src/specs/components/file/demo/data--taxonomy.js
  src/specs/components/file/demo/data--thumbnail.js
  src/specs/components/file/demo/data--with-translation.js
  src/specs/components/file/demo/data--without-translation.js
Labels: tag: enhancement, process: review needed

#3155 chore(deps): Updates 22-12-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal
