Repository ec-europa/europa-component-library, pull requests merged in 2023-10, with the labels that each got.

#3051 feat(logo): update AR logo - FRONT-4092
  src/resources/logo-eu/src/condensed-version/negative/logo-eu--ar.svg
  src/resources/logo-eu/src/condensed-version/positive/logo-eu--ar.svg
  src/resources/logo-eu/src/standard-version/negative/logo-eu--ar.svg
  src/resources/logo-eu/src/standard-version/positive/logo-eu--ar.svg
Labels: tag: enhancement

#3050 feat(eu-styles): Clean eu theme file - FRONT-4101
  src/implementations/vanilla/components/breadcrumb/_breadcrumb.scss
  src/implementations/vanilla/components/breadcrumb/package.json
  src/implementations/vanilla/components/button/_button.scss
  src/implementations/vanilla/components/card/_card.scss
  src/implementations/vanilla/components/link/_link.scss
  src/implementations/vanilla/components/notification/_notification.scss
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/themes/eu/theme.scss
Labels: tag: enhancement

#3028 feat(modal): add scrollable modal - FRONT-3994
  src/implementations/twig/components/modal/README.md
  src/implementations/twig/components/modal/__snapshots__/modal.test.js.snap
  src/implementations/twig/components/modal/modal.html.twig
  src/implementations/twig/components/modal/modal.story.js
  src/implementations/twig/components/modal/modal.test.js
  src/implementations/vanilla/components/modal/_modal.scss
  src/implementations/vanilla/components/modal/modal.js
  src/playground/addons/story-utils/index.js
  src/specs/components/modal/demo/data.js
Labels: tag: enhancement, tag: markup changes

#3009 feat(rating-field): EC Revamp for v4 - FRONT-4072
  docs/Migrating-v4.md
  src/implementations/twig/components/form-group/__snapshots__/form-group.test.js.snap
  src/implementations/twig/components/rating-field/__snapshots__/rating-field.test.js.snap
  src/implementations/twig/components/rating-field/rating-field.test.js
  src/implementations/vanilla/components/range/_range.scss
  src/implementations/vanilla/components/rating-field/_rating-field-print.scss
  src/implementations/vanilla/components/rating-field/_rating-field.scss
  src/implementations/vanilla/components/rating-field/package.json
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/resources/icons-ec/src/all/star-filled.svg
  src/resources/icons-ec/src/all/star-outline.svg
  src/specs/components/rating-field/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/ec/maps/color.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#3058 chore(deps): Updates 09-10-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/presets/ec/package.json
  src/presets/eu/package.json
  src/presets/reset/package.json
  src/presets/rtl/package.json
  src/resources/icons-ec/package.json
  src/resources/icons-eu/package.json
  src/resources/icons-flag/package.json
  src/resources/icons-social-media/package.json
  src/resources/logo-ec/package.json
  src/resources/logo-eu/package.json
  src/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3052 feat(shadow): update EC shadows - FRONT-4104
  src/implementations/twig/utilities/shadow/index.story.js
  src/implementations/vanilla/components/search-form/_search-form.scss
  src/implementations/vanilla/components/site-header/_site-header-language-switcher.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/themes/ec/_variables.scss
  src/themes/ec/maps/shape.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#3012 feat(banner): EC Revamp for v4 - FRONT-4073
  docs/Migrating-v4.md
  src/implementations/twig/components/banner/README.md
  src/implementations/twig/components/banner/__snapshots__/banner.test.js.snap
  src/implementations/twig/components/banner/banner.html.twig
  src/implementations/twig/components/banner/banner.story.js
  src/implementations/twig/components/banner/banner.test.js
  src/implementations/twig/components/carousel/__snapshots__/carousel.test.js.snap
  src/implementations/vanilla/components/banner/_banner.scss
  src/implementations/vanilla/components/banner/banner-ec.scss
  src/implementations/vanilla/components/banner/banner-eu.scss
  src/implementations/vanilla/components/banner/banner-print-ec.scss
  src/implementations/vanilla/components/banner/banner-print-eu.scss
  src/implementations/vanilla/components/banner/banner-print.scss
  src/implementations/vanilla/components/banner/banner.js
  src/implementations/vanilla/components/banner/package.json
  src/presets/dev/src/dev.js
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/specs/components/banner/demo/data--image-overlay.js
  src/specs/components/banner/demo/data--plain-background.js
  src/specs/components/banner/demo/data--text-highlight.js
  src/specs/components/banner/demo/data--text-overlay.js
  src/specs/components/carousel/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/banner/demo/index.js
  src/website/src/pages/ec/components/banner/docs/api.mdx
  src/website/src/pages/ec/components/banner/docs/code.mdx
  src/website/src/pages/eu/components/banner/demo/index.js
  src/website/src/pages/eu/components/banner/docs/api.mdx
  src/website/src/pages/eu/components/banner/docs/code.mdx
Labels: tag: enhancement, process: business approval needed

#3054 feat(datepicker): ECL4 datepicker - FRONT-4107
  src/implementations/twig/components/datepicker/__snapshots__/datepicker.test.js.snap
  src/implementations/twig/components/datepicker/datepicker.html.twig
  src/implementations/twig/components/form-group/__snapshots__/form-group.test.js.snap
  src/implementations/vanilla/components/datepicker/_datepicker.scss
  src/implementations/vanilla/components/datepicker/datepicker-ec.scss
  src/implementations/vanilla/components/datepicker/datepicker-eu.scss
  src/implementations/vanilla/components/datepicker/datepicker.js
  src/implementations/vanilla/components/datepicker/package.json
  src/implementations/vanilla/components/text-input/_text-input.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/specs/components/datepicker/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#3053 feat(file upload): ECL4 file upload - FRONT-4102
  src/implementations/twig/components/form-group/__snapshots__/form-group.test.js.snap
  src/implementations/twig/components/form-group/form-group.story.js
  src/implementations/twig/compositions/file-upload-status/__snapshots__/file-upload-status.test.js.snap
  src/implementations/twig/compositions/file-upload-status/file-upload-status.html.twig
  src/implementations/vanilla/components/file-upload/_file-upload.scss
  src/implementations/vanilla/components/file-upload/file-upload-ec.scss
  src/implementations/vanilla/components/file-upload/file-upload-eu.scss
  src/implementations/vanilla/components/file-upload/package.json
  src/implementations/vanilla/components/spinner/_spinner.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/resources/icons-ec/src/all/trash.svg
  src/specs/components/file-upload/demo/data--multiple.js
  src/specs/components/file-upload/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/forms/file-upload/index.md
  src/website/src/pages/eu/components/forms/file-upload/index.md
Labels: tag: enhancement

#3062 fix(accordion): update display - FRONT-4110
  src/themes/ec/_variables.scss
Labels: tag: bug fix

#3064 chore(deps): Updates 16-10-23
  package.json
  src/implementations/vanilla/components/gallery/package.json
  src/implementations/vanilla/components/modal/package.json
  src/implementations/vanilla/components/site-header-core/package.json
  src/implementations/vanilla/components/site-header-harmonised/package.json
  src/implementations/vanilla/components/site-header-standardised/package.json
  src/implementations/vanilla/components/site-header/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3059 feat(fact and figures): ECL4 fact and figures - FRONT-4108
  docs/Migrating-v4.md
  src/implementations/twig/components/fact-figures/__snapshots__/fact-figures.test.js.snap
  src/implementations/twig/components/fact-figures/fact-figures.html.twig
  src/implementations/vanilla/components/fact-figures/_fact-figures.scss
  src/implementations/vanilla/components/fact-figures/fact-figures-ec.scss
  src/implementations/vanilla/components/fact-figures/fact-figures-eu.scss
  src/implementations/vanilla/components/fact-figures/fact-figures-print.scss
  src/implementations/vanilla/components/fact-figures/package.json
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#3060 feat(css): add css variables - FRONT-4105
  .size-limit.json
  docs/Migrating-v4.md
  src/implementations/vanilla/components/accordion/accordion-ec.scss
  src/implementations/vanilla/components/accordion/accordion-eu.scss
  src/implementations/vanilla/components/banner/_banner.scss
  src/implementations/vanilla/components/breadcrumb/_breadcrumb.scss
  src/implementations/vanilla/components/button/_button.scss
  src/implementations/vanilla/components/card/_card.scss
  src/implementations/vanilla/components/checkbox/_checkbox.scss
  src/implementations/vanilla/components/content-block/_content-block-print.scss
  src/implementations/vanilla/components/content-block/_content-block.scss
  src/implementations/vanilla/components/content-item/_content-item.scss
  src/implementations/vanilla/components/date-block/_date-block.scss
  src/implementations/vanilla/components/date-block/date-block-print.scss
  src/implementations/vanilla/components/datepicker/_datepicker.scss
  src/implementations/vanilla/components/description-list/_description-list.scss
  src/implementations/vanilla/components/file-upload/_file-upload.scss
  src/implementations/vanilla/components/file/_file.scss
  src/implementations/vanilla/components/file/file-print.scss
  src/implementations/vanilla/components/form-group/_form-group.scss
  src/implementations/vanilla/components/label/_label.scss
  src/implementations/vanilla/components/link/_link.scss
  src/implementations/vanilla/components/media-container/_media-container.scss
  src/implementations/vanilla/components/media-container/media-container-print.scss
  src/implementations/vanilla/components/menu/_menu.scss
  src/implementations/vanilla/components/navigation-list/_navigation-list.scss
  src/implementations/vanilla/components/navigation-list/navigation-list-print.scss
  src/implementations/vanilla/components/notification/_notification.scss
  src/implementations/vanilla/components/ordered-list/_ordered-list.scss
  src/implementations/vanilla/components/page-header/page-header-ec.scss
  src/implementations/vanilla/components/page-header/page-header-eu.scss
  src/implementations/vanilla/components/page-header/page-header-print-ec.scss
  src/implementations/vanilla/components/page-header/page-header-print-eu.scss
  src/implementations/vanilla/components/radio/_radio.scss
  src/implementations/vanilla/components/range/_range.scss
  src/implementations/vanilla/components/search-form/_search-form.scss
  src/implementations/vanilla/components/site-footer/site-footer-ec.scss
  src/implementations/vanilla/components/site-footer/site-footer-eu.scss
  src/implementations/vanilla/components/site-header/_site-header-language-switcher.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/implementations/vanilla/components/spinner/_spinner.scss
  src/implementations/vanilla/components/tag/_tag.scss
  src/implementations/vanilla/components/text-area/_text-area.scss
  src/implementations/vanilla/components/text-input/_text-input.scss
  src/implementations/vanilla/components/timeline/_timeline.scss
  src/implementations/vanilla/components/unordered-list/_unordered-list.scss
  src/implementations/vanilla/utilities/shadow/shadow-print.scss
  src/implementations/vanilla/utilities/shadow/shadow.scss
  src/implementations/vanilla/utilities/spacing/spacing.scss
  src/implementations/vanilla/utilities/typography/_typography.scss
  src/implementations/vanilla/utilities/typography/typography-ec.scss
  src/implementations/vanilla/utilities/typography/typography-eu.scss
  src/themes/ec/_variables.scss
  src/themes/ec/maps/color.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#3063 feat(datepicker): Removing dependency from moment.js, removing pikaday from the bundled js - FRONT-4111
  README.md
  docs/Migrating-v4.md
  src/implementations/vanilla/components/datepicker/datepicker.js
  src/playground/ec/.storybook/preview-head.html
  src/playground/eu/.storybook/preview-head.html
  src/tools/builder/scripts/scripts.js
  src/website/src/pages/ec/components/forms/datepicker/docs/api.mdx
  src/website/src/pages/ec/getting-started/index.mdx
  src/website/src/pages/eu/components/forms/datepicker/docs/api.mdx
  src/website/src/pages/eu/getting-started/index.mdx
Labels: tag: documentation, tag: enhancement

#3070 chore(deps): Updates 19-10-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3069 feat(message): Allowing missing title or description - FRONT-4117
  src/implementations/twig/components/message/__snapshots__/message.test.js.snap
  src/implementations/twig/components/message/message.html.twig
  src/implementations/twig/components/message/message.story.js
  src/implementations/twig/components/message/message.test.js
  src/implementations/twig/compositions/etrans/__snapshots__/etrans.test.js.snap
Labels: tag: enhancement, process: review needed

#3073 fix(file-upload): Fixing display of optional text - FRONT-4120
  src/implementations/twig/components/file-upload/file-upload.html.twig
Labels: tag: bug fix

#3072 chore(controls): Adding conditions for toggable controls - FRONT-4118
  src/implementations/twig/components/banner/banner.story.js
  src/implementations/twig/components/button/button.story.js
  src/implementations/twig/components/card/card.story.js
  src/implementations/twig/components/checkbox/checkbox.story.js
  src/implementations/twig/components/content-block/content-block.story.js
  src/implementations/twig/components/content-item/content-item.story.js
  src/implementations/twig/components/datepicker/datepicker.story.js
  src/implementations/twig/components/fact-figures/fact-figures.story.js
  src/implementations/twig/components/featured-item/featured-item.story.js
  src/implementations/twig/components/file-upload/file-upload.story.js
  src/implementations/twig/components/file/file.story.js
  src/implementations/twig/components/gallery/gallery.story.js
  src/implementations/twig/components/link/link.story.js
  src/implementations/twig/components/list-illustration/list-illustration.story.js
  src/implementations/twig/components/media-container/media-container.story.js
  src/implementations/twig/components/radio/radio.story.js
  src/implementations/twig/components/range/range.story.js
  src/implementations/twig/components/rating-field/rating-field.story.js
  src/implementations/twig/components/select/select.story.js
  src/implementations/twig/components/site-header/ec-site-header.story.js
  src/implementations/twig/components/spinner/spinner.story.js
  src/implementations/twig/components/text-area/text-area.story.js
  src/implementations/twig/components/text-input/text-input.story.js
  src/playground/addons/story-utils/index.js
Labels: tag: enhancement, process: review needed

#3065 feat(featured-item): ECL4 featured item - FRONT-4109
  docs/Migrating-v4.md
  src/implementations/twig/components/featured-item/README.md
  src/implementations/twig/components/featured-item/__snapshots__/featured-item.test.js.snap
  src/implementations/twig/components/featured-item/featured-item.html.twig
  src/implementations/twig/components/featured-item/featured-item.story.js
  src/implementations/twig/components/featured-item/featured-item.test.js
  src/implementations/vanilla/components/featured-item/_featured-item-print.scss
  src/implementations/vanilla/components/featured-item/_featured-item.scss
  src/implementations/vanilla/components/featured-item/featured-item-ec.scss
  src/implementations/vanilla/components/featured-item/featured-item-eu.scss
  src/implementations/vanilla/components/featured-item/featured-item-print-ec.scss
  src/implementations/vanilla/components/featured-item/featured-item-print-eu.scss
  src/implementations/vanilla/components/featured-item/package.json
  src/implementations/vanilla/components/media-container/_media-container.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/specs/components/featured-item/demo/data--highlight.js
  src/specs/components/featured-item/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/media/featured-item/demo/index.js
  src/website/src/pages/ec/components/media/featured-item/docs/code.mdx
  src/website/src/pages/eu/components/media/featured-item/demo/index.js
  src/website/src/pages/eu/components/media/featured-item/docs/code.mdx
Labels: tag: enhancement, process: review needed

#3077 feat(footer): update news link - FRONT-4124
  src/implementations/twig/components/site-footer/__snapshots__/site-footer.test.js.snap
  src/specs/components/site-footer/demo/data-core--ec.js
Labels: tag: enhancement

#3078 chore(deps): Updates 24-10-23
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3061 feat(select): EC Revamp for V4 - FRONT-4106
  .size-limit.json
  docs/Migrating-v4.md
  src/implementations/twig/components/form-group/__snapshots__/form-group.test.js.snap
  src/implementations/twig/components/form-group/form-group.story.js
  src/implementations/twig/components/select/README.md
  src/implementations/twig/components/select/__snapshots__/select.test.js.snap
  src/implementations/twig/components/select/select.html.twig
  src/implementations/vanilla/components/select/_select.scss
  src/implementations/vanilla/components/select/package.json
  src/implementations/vanilla/components/select/select-ec.scss
  src/implementations/vanilla/components/select/select-eu.scss
  src/implementations/vanilla/components/select/select.js
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/specs/components/select/demo/data-multiple.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/forms/select/docs/code.mdx
  src/website/src/pages/eu/components/forms/select/docs/code.mdx
Labels: tag: enhancement

#3086 chore(deps): Updates 30-10-23
  package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3084 chore(showcase): Fix path to the default print css file - FRONT-4131
  src/playground/ec/.storybook/preview-head.html
  src/playground/eu/.storybook/preview-head.html
Labels: tag: bug fix

#3067 feat(list-illustration): EC revamp for v4 - FRONT-4112
  src/implementations/twig/components/list-illustration/list-illustration.story.js
  src/implementations/vanilla/components/list-illustration/_list-illustration-print.scss
  src/implementations/vanilla/components/list-illustration/_list-illustration.scss
  src/implementations/vanilla/components/list-illustration/list-illustration-ec.scss
  src/implementations/vanilla/components/list-illustration/list-illustration-eu.scss
  src/implementations/vanilla/components/list-illustration/list-illustration-print-ec.scss
  src/implementations/vanilla/components/list-illustration/list-illustration-print-eu.scss
  src/implementations/vanilla/components/list-illustration/package.json
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
  src/website/src/pages/ec/components/list-illustration/docs/code.mdx
  src/website/src/pages/ec/components/list-illustration/index.md
  src/website/src/pages/eu/components/list-illustration/docs/code.mdx
  src/website/src/pages/eu/components/list-illustration/index.md
Labels: tag: enhancement
