Repository ec-europa/europa-component-library, pull requests merged in 2024-05, with the labels that each got.

#3341 feat(mega-menu): 2 columns panel alignment - FRONT 4378
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/vanilla/components/mega-menu/mega-menu.js
  src/implementations/vanilla/components/mega-menu/mega-menu.scss
  src/specs/components/mega-menu/demo/data.js
Labels: tag: enhancement

#3375 chore(deps): Updates 02-05-24
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3366 feat(popover): EU styles - FRONT-4388
  src/implementations/vanilla/components/popover/popover.scss
  src/themes/ec/variables/_popover.scss
  src/themes/eu/variables/_popover.scss
Labels: tag: enhancement

#3371 feat(content-item): remove icons in demo - FRONT-4396
  src/implementations/twig/components/content-item/__snapshots__/content-item.test.js.snap
  src/specs/components/content-item/demo/data--default.js
  src/specs/components/content-item/demo/data--event.js
  src/specs/components/content-item/demo/data--image.js
Labels: tag: enhancement, process: review needed

#3367 feat(featured-item): add shadow - FRONT-4393
  src/implementations/vanilla/components/featured-item/featured-item.scss
  src/themes/ec/variables/_featured-item.scss
Labels: tag: enhancement

#3379 fix(range): Fixing display in firefox - FRONT-4414
  src/implementations/vanilla/components/range/range.scss
Labels: tag: bug fix

#3370 fix(menu): fix EU hamburger menu color and padding - FRONT-4401
  src/implementations/vanilla/components/menu/menu.scss
  src/themes/ec/variables/_menu.scss
  src/themes/eu/variables/_menu.scss
Labels: tag: bug fix

#3384 fix(color): fix website colors - FRONT-4423
  src/website/src/pages/ec/guidelines/colours/index.mdx
Labels: tag: documentation

#3378 feat(typography): update EC and EU text styles - FRONT-4392
  src/implementations/vanilla/utilities/typography/typography-print.scss
  src/implementations/vanilla/utilities/typography/typography.scss
  src/themes/ec/_custom-properties.scss
  src/themes/ec/maps/typography.scss
  src/themes/ec/variables/_typography.scss
  src/themes/eu/_custom-properties.scss
  src/themes/eu/maps/typography.scss
  src/themes/eu/variables/_typography.scss
  src/website/src/pages/ec/guidelines/typography/index.mdx
  src/website/src/pages/eu/guidelines/typography/index.mdx
Labels: tag: enhancement

#3298 fix(icon): rename whatsapp icons - FRONT-4315
  src/resources/icons-social-media/src/social-media/whatsapp-negative.svg
  src/resources/icons-social-media/src/social-media/whatsapp.svg
Labels: tag: bug fix

#3350 feat(footer): update links - FRONT-4375
  src/implementations/twig/components/site-footer/__snapshots__/site-footer.test.js.snap
  src/implementations/twig/components/site-footer/site-footer.html.twig
  src/implementations/vanilla/components/site-footer/site-footer-eu.scss
  src/specs/components/site-footer/demo/data-core--ec.js
  src/specs/components/site-footer/demo/data-core--eu.js
  src/specs/components/site-footer/demo/data-harmonised--ec.js
  src/specs/components/site-footer/demo/data-harmonised--eu.js
  src/specs/components/site-footer/demo/data-standardised--ec.js
Labels: tag: enhancement, tag: markup changes

#3354 feat(gallery): add item title for share link - FRONT-4369
  src/implementations/twig/components/gallery/README.md
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/twig/components/gallery/gallery-item.html.twig
  src/implementations/twig/components/gallery/gallery.html.twig
  src/implementations/vanilla/components/gallery/gallery-print.scss
  src/implementations/vanilla/components/gallery/gallery.js
  src/implementations/vanilla/components/gallery/gallery.scss
  src/specs/components/gallery/demo/data.js
Labels: tag: enhancement, tag: markup changes, tag: data change

#3388 chore(deps): Updates 14-05-24
  package.json
  src/presets/ec/package.json
  src/presets/eu/package.json
  src/presets/reset/package.json
  src/presets/rtl/package.json
  src/resources/icons-ec/package.json
  src/resources/icons-eu/package.json
  src/resources/icons-flag/package.json
  src/resources/icons-social-media/package.json
  src/resources/logo-ec/package.json
  src/resources/logo-eu/package.json
  src/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3369 feat(icon): add screen reader label for external icons - FRONT-4373
  src/implementations/twig/components/description-list/__snapshots__/description-list.test.js.snap
  src/implementations/twig/components/featured-item/__snapshots__/featured-item.test.js.snap
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/twig/components/gallery/gallery.html.twig
  src/implementations/twig/components/link/README.md
  src/implementations/twig/components/link/link.html.twig
  src/implementations/twig/components/link/link.story.js
  src/implementations/twig/components/link/link.test.js
  src/implementations/twig/components/mega-menu/README.md
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/twig/components/mega-menu/mega-menu-item.html.twig
  src/implementations/twig/components/mega-menu/mega-menu.html.twig
  src/implementations/twig/components/mega-menu/mega-menu.test.js
  src/implementations/twig/components/menu/README.md
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/menu-item.html.twig
  src/implementations/twig/components/menu/menu.html.twig
  src/implementations/twig/components/menu/menu.test.js
  src/implementations/twig/components/news-ticker/__snapshots__/news-ticker.test.js.snap
  src/implementations/twig/components/news-ticker/news-ticker.html.twig
  src/specs/components/description-list/demo/data--default.js
  src/specs/components/description-list/demo/data--horizontal.js
  src/specs/components/featured-item/demo/data--highlight.js
  src/specs/components/featured-item/demo/data--simple.js
  src/specs/components/featured-item/demo/data.js
  src/specs/components/gallery/demo/data.js
  src/specs/components/link/demo/data--cta.js
  src/specs/components/link/demo/data--default.js
  src/specs/components/link/demo/data--icon.js
  src/specs/components/link/demo/data--inverted.js
  src/specs/components/link/demo/data--primary.js
  src/specs/components/link/demo/data--secondary.js
  src/specs/components/link/demo/data--standalone.js
  src/specs/components/mega-menu/demo/data.js
  src/specs/components/menu/demo/data--ec-long.js
  src/specs/components/menu/demo/data--ec.js
  src/specs/components/menu/demo/data--eu-long.js
  src/specs/components/menu/demo/data--eu.js
  src/specs/components/news-ticker/demo/data.js
Labels: tag: enhancement, tag: markup changes, tag: data change

#3251 feat(table): add id and headers - FRONT-4260
  src/implementations/twig/components/table/README.md
  src/implementations/twig/components/table/__snapshots__/table.test.js.snap
  src/implementations/twig/components/table/table.html.twig
  src/specs/components/table/demo/data--default.js
  src/specs/components/table/demo/data--multi.js
  src/specs/components/table/demo/data--sort-table.js
Labels: tag: enhancement, process: review needed, tag: markup changes, tag: data change

#3386 fix(mega menu): fix accessibility issues - FRONT-4424
  src/implementations/twig/components/mega-menu/README.md
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/twig/components/mega-menu/mega-menu-item.html.twig
  src/implementations/twig/components/mega-menu/mega-menu.html.twig
  src/implementations/vanilla/components/mega-menu/mega-menu.js
  src/implementations/vanilla/components/mega-menu/mega-menu.scss
  src/specs/components/mega-menu/demo/data.js
Labels: tag: enhancement, process: review needed, tag: markup changes, tag: data change

#3391 feat(color): update neutral color - FRONT-4427
  src/themes/ec/maps/color.scss
  src/website/src/pages/ec/guidelines/colours/index.mdx
Labels: tag: enhancement

#3387 feat(footer): update eu footer links - FRONT-4394
  src/implementations/twig/components/site-footer/__snapshots__/site-footer.test.js.snap
  src/implementations/vanilla/components/site-footer/site-footer-ec.scss
  src/implementations/vanilla/components/site-footer/site-footer-eu.scss
  src/specs/components/site-footer/demo/data-core--eu.js
  src/specs/components/site-footer/demo/data-harmonised--eu.js
  src/themes/ec/variables/_site-footer.scss
  src/themes/eu/variables/_site-footer.scss
Labels: tag: enhancement, tag: markup changes, tag: data change

#3394 fix(carousel): remove unneeded fixed id - FRONT-4431
  src/implementations/twig/components/carousel/__snapshots__/carousel.test.js.snap
  src/implementations/twig/components/carousel/carousel.html.twig
Labels: tag: bug fix

#3399 feat(featured-item): update border radius - FRONT-4344
  src/implementations/twig/components/featured-item/featured-item.story.js
  src/themes/eu/variables/_featured-item.scss
Labels: tag: enhancement

#3401 feat(mega-menu): New version - FRONT-4426
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/twig/components/mega-menu/mega-menu-item.html.twig
  src/implementations/twig/components/mega-menu/mega-menu.html.twig
  src/implementations/twig/components/mega-menu/mega-menu.test.js
  src/implementations/vanilla/components/mega-menu/mega-menu.js
  src/implementations/vanilla/components/mega-menu/mega-menu.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/specs/components/mega-menu/demo/data.js
  src/themes/ec/variables/_mega-menu.scss
Labels: tag: enhancement, tag: markup changes, tag: data change

#3406 fix(file): improve file download rtl - FRONT-4434
  src/implementations/vanilla/components/file/file.scss
  src/presets/rtl/src/rtl.scss
Labels: tag: bug fix

#3398 feat(tag): update styles - FRONT-4418
  src/implementations/vanilla/components/tag/tag-print.scss
  src/implementations/vanilla/components/tag/tag.scss
  src/themes/eu/variables/_tag.scss
Labels: tag: enhancement

#3403 feat(notification): add border, update close - FRONT-4435
  src/implementations/twig/components/notification/__snapshots__/notification.test.js.snap
  src/implementations/vanilla/components/notification/notification-print.scss
  src/implementations/vanilla/components/notification/notification.scss
  src/specs/components/notification/demo/data--error-eu.js
  src/specs/components/notification/demo/data--info-eu.js
  src/specs/components/notification/demo/data--success-ec.js
  src/specs/components/notification/demo/data--success-eu.js
  src/specs/components/notification/demo/data--warning-eu.js
  src/themes/ec/variables/_notification.scss
  src/themes/eu/variables/_notification.scss
  src/website/src/pages/ec/components/notification/index.md
  src/website/src/pages/eu/components/notification/index.md
Labels: tag: enhancement, process: review needed

#3326 feat(link): update link styles - FRONT-4325
  src/implementations/twig/components/link/link.story.js
  src/implementations/vanilla/components/link/link-print.scss
  src/implementations/vanilla/components/link/link.scss
  src/themes/ec/variables/_link.scss
  src/themes/eu/variables/_link.scss
Labels: tag: enhancement

#3409 chore(deps): Updates 29-05-24
  package.json
  src/implementations/twig/components/link/link.story.js
  src/implementations/vanilla/components/breadcrumb/breadcrumb.scss
  src/implementations/vanilla/components/button/button.scss
  src/implementations/vanilla/components/card/card.scss
  src/implementations/vanilla/components/checkbox/checkbox.scss
  src/implementations/vanilla/components/file/file.scss
  src/implementations/vanilla/components/media-container/media-container.scss
  src/implementations/vanilla/components/mega-menu/mega-menu.scss
  src/implementations/vanilla/components/menu/menu.scss
  src/implementations/vanilla/components/navigation-list/navigation-list.scss
  src/implementations/vanilla/components/radio/radio.scss
  src/implementations/vanilla/components/select/select.scss
  src/implementations/vanilla/components/timeline/timeline.scss
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3395 feat(label): update display - FRONT-4416
  src/implementations/vanilla/components/label/label.scss
  src/themes/eu/variables/_label.scss
Labels: tag: enhancement

#3392 feat(fact and figures): improve center and print display - FRONT-4425
  src/implementations/vanilla/components/fact-figures/fact-figures-print.scss
  src/implementations/vanilla/components/fact-figures/fact-figures.scss
  src/presets/ec/src/ec-print.scss
  src/presets/eu/src/eu-print.scss
Labels: tag: enhancement

#3404 feat(EC Usage pages for components): update EC Usage pages for components “ec_button”
  src/website/src/pages/ec/components/button/docs/usage.md
Labels: netlify-cms/pending_publish

#3405 feat(EU Usage pages for components): update EU Usage pages for components “eu_button”
  src/website/src/pages/eu/components/button/docs/usage.md
Labels: netlify-cms/pending_publish

#3415 feat(EC Usage pages for components): update EC Usage pages for components “ec_media_container”
  src/website/src/pages/ec/components/media/media-container/docs/usage.md
Labels: netlify-cms/pending_publish

#3416 feat(EU Usage pages for components): update EU Usage pages for components “eu_media_container”
  src/website/src/pages/eu/components/media/media-container/docs/usage.md
Labels: netlify-cms/pending_publish
