Repository ec-europa/europa-component-library, pull requests merged in 2024-09, with the labels that each got.

#3595 fix(banner): Adding check for bannerContainer presence - FRONT-4591
  src/implementations/vanilla/components/banner/banner.js
Labels: tag: bug fix, process: review needed

#3597 feat(banner): Resetting padding for the content in no-box variant - FRONT-4592
  src/implementations/vanilla/components/banner/banner.scss
Labels: tag: enhancement

#3594 fix(video): Initializing the _extra_attributes variable - FRONT-4590
  src/implementations/twig/components/video/video.html.twig
Labels: tag: bug fix

#3596 feat(file-upload): Adding onSelection event - FRONT-4589
  src/implementations/vanilla/components/file-upload/file-upload.js
Labels: tag: enhancement

#3587 feat(table): improve border display - FRONT-4584
  src/implementations/vanilla/components/table/table.scss
Labels: tag: enhancement

#3600 chore(deps): Updates 03-09-24
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3599 fix(sorting): Adding sorting to glob.sync - FRONT-4594
  src/website/scripts/docs.js
  src/website/src/preval/get-meta-ec.js
  src/website/src/preval/get-meta-eu.js
Labels: tag: internal

#3583 feat(carousel): Styles update - FRONT-4571
  src/implementations/twig/components/carousel/__snapshots__/carousel.test.js.snap
  src/implementations/twig/components/carousel/carousel.html.twig
  src/implementations/twig/components/carousel/carousel.story.js
  src/implementations/vanilla/components/carousel/carousel.js
  src/implementations/vanilla/components/carousel/carousel.scss
  src/themes/ec/variables/_carousel.scss
Labels: tag: enhancement

#3601 fix(site-header): fix icon alignment - FRONT-4596
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
Labels: tag: bug fix

#3606 fix(range): fix bubble position when setting min value - FRONT-4603
  src/implementations/vanilla/components/range/range.js
Labels: tag: bug fix, process: review needed

#3614 chore(twig): Harmonising syntax when rendering classes and attributes -- FRONT-4609
  src/implementations/twig/components/accordion/accordion.html.twig
  src/implementations/twig/components/banner/banner.html.twig
  src/implementations/twig/components/blockquote/blockquote.html.twig
  src/implementations/twig/components/breadcrumb/breadcrumb.html.twig
  src/implementations/twig/components/button/button.html.twig
  src/implementations/twig/components/card/card.html.twig
  src/implementations/twig/components/category-filter/category-filter-items.html.twig
  src/implementations/twig/components/checkbox/checkbox-item.html.twig
  src/implementations/twig/components/date-block/date-block.html.twig
  src/implementations/twig/components/description-list/description-list.html.twig
  src/implementations/twig/components/expandable/expandable.html.twig
  src/implementations/twig/components/fact-figures/fact-figures.html.twig
  src/implementations/twig/components/featured-item/featured-item.html.twig
  src/implementations/twig/components/file/file.html.twig
  src/implementations/twig/components/gallery/gallery-item.html.twig
  src/implementations/twig/components/gallery/gallery-overlay.html.twig
  src/implementations/twig/components/gallery/gallery.html.twig
  src/implementations/twig/components/inpage-navigation/inpage-navigation.html.twig
  src/implementations/twig/components/list-illustration/list-illustration-item.html.twig
  src/implementations/twig/components/list-illustration/list-illustration.html.twig
  src/implementations/twig/components/media-container/media-container.html.twig
  src/implementations/twig/components/navigation-list/navigation-list-item.html.twig
  src/implementations/twig/components/navigation-list/navigation-list.html.twig
  src/implementations/twig/components/news-ticker/news-ticker.html.twig
  src/implementations/twig/components/notification/notification.html.twig
  src/implementations/twig/components/ordered-list/ordered-list.html.twig
  src/implementations/twig/components/page-header/page-header.html.twig
  src/implementations/twig/components/pagination/pagination.html.twig
  src/implementations/twig/components/picture/picture.html.twig
  src/implementations/twig/components/popover/popover.html.twig
  src/implementations/twig/components/radio/radio-button.html.twig
  src/implementations/twig/components/search-form/search-form.html.twig
  src/implementations/twig/components/site-footer/site-footer.html.twig
  src/implementations/twig/components/site-header/site-header.html.twig
  src/implementations/twig/components/social-media-follow/social-media-follow.html.twig
  src/implementations/twig/components/social-media-share/social-media-share.html.twig
  src/implementations/twig/components/spinner/spinner.html.twig
  src/implementations/twig/components/splash-page/splash-page.html.twig
  src/implementations/twig/components/table/table.html.twig
  src/implementations/twig/components/tabs/tabs.html.twig
  src/implementations/twig/components/tag/tag-set.html.twig
  src/implementations/twig/components/tag/tag.html.twig
  src/implementations/twig/components/timeline/timeline.html.twig
  src/implementations/twig/components/unordered-list/unordered-list.html.twig
Labels: tag: internal

#3605 feat(separator): Adding new component - FRONT-4597
  src/implementations/twig/components/separator/README.md
  src/implementations/twig/components/separator/__snapshots__/separator.test.js.snap
  src/implementations/twig/components/separator/package.json
  src/implementations/twig/components/separator/separator.html.twig
  src/implementations/twig/components/separator/separator.story.js
  src/implementations/twig/components/separator/separator.test.js
  src/implementations/twig/utilities/html-tag/index.story.js
  src/implementations/vanilla/components/separator/README.md
  src/implementations/vanilla/components/separator/package.json
  src/implementations/vanilla/components/separator/separator-print.scss
  src/implementations/vanilla/components/separator/separator.scss
  src/presets/ec/src/ec-default-print.scss
  src/presets/ec/src/ec-default.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu-default-print.scss
  src/presets/eu/src/eu-default.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/themes/ec/_variables.scss
  src/themes/ec/variables/_separator.scss
  src/themes/eu/_variables.scss
  src/themes/eu/variables/_separator.scss
  src/website/public/admin/config.yml
  src/website/src/pages/ec/components/separator/demo/index.js
  src/website/src/pages/ec/components/separator/docs/code.mdx
  src/website/src/pages/ec/components/separator/docs/usage.md
  src/website/src/pages/ec/components/separator/index.md
  src/website/src/pages/eu/components/separator/demo/index.js
  src/website/src/pages/eu/components/separator/docs/code.mdx
  src/website/src/pages/eu/components/separator/docs/usage.md
  src/website/src/pages/eu/components/separator/index.md
Labels: tag: new feature

#3616 chore(deps): Updates 10-09-24
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3620 feat(separator): update default css rules - FRONT-4611
  src/presets/ec/src/ec-default-print.scss
  src/presets/ec/src/ec-default.scss
  src/presets/eu/src/eu-default-print.scss
  src/presets/eu/src/eu-default.scss
Labels: tag: enhancement

#3611 fix(form): Fixing styles for the label - FRONT-4605
  src/implementations/vanilla/components/form-group/form-group.scss
Labels: tag: bug fix

#3622 feat(templates): Removing trailing slashes from void elements - FRONT-4612
  src/implementations/twig/components/checkbox/checkbox-item.html.twig
  src/implementations/twig/components/content-item/content-item.html.twig
  src/implementations/twig/components/file-upload/file-upload.html.twig
  src/implementations/twig/components/picture/picture.html.twig
  src/implementations/twig/components/radio/radio-button.html.twig
  src/implementations/twig/components/range/range.html.twig
  src/implementations/twig/components/rating-field/rating-field.html.twig
  src/implementations/twig/components/separator/separator.html.twig
  src/implementations/twig/components/text-input/text-input.html.twig
  src/implementations/twig/components/video/video.html.twig
  src/implementations/twig/utilities/background/index.story.js
  src/implementations/twig/utilities/html-tag/index.story.js
Labels: tag: enhancement

#3612 fix(banner): increasing padding bottom in L viewport using the credit's height - FRONT-4608
  src/implementations/vanilla/components/banner/banner.scss
Labels: tag: enhancement

#3623 chore(deps): Fixing audit issues
  package.json
  yarn.lock
Labels: tag: internal

#3621 fix(menu): fix focus color on EU menu - FRONT-4613
  src/implementations/vanilla/components/menu/menu.scss
  src/themes/ec/variables/_menu.scss
  src/themes/eu/variables/_menu.scss
Labels: tag: bug fix

#3618 feat(EC Usage pages for components): update EC Usage pages for components “ec_separator”
  src/website/src/pages/ec/components/separator/docs/usage.md
Labels: netlify-cms/pending_publish

#3610 fix(mega-menu): Showing the panels only when ready - FRONT-4604
  src/implementations/vanilla/components/mega-menu/mega-menu.js
Labels: tag: enhancement, process: business approval needed

#3613 feat(banner): add rounded corners on EU - FRONT-4607
  src/implementations/vanilla/components/banner/banner.scss
  src/themes/ec/variables/_banner.scss
  src/themes/eu/variables/_banner.scss
Labels: tag: enhancement

#3627 chore(deps): Updates 13-09-24
  package.json
  src/implementations/vanilla/components/gallery/package.json
  src/implementations/vanilla/components/inpage-navigation/package.json
  src/implementations/vanilla/components/modal/package.json
  src/implementations/vanilla/components/site-header/package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3628 feat(banner): Fixing styles for the text-overlay deprecated variant - FRONT-4618
  src/implementations/twig/components/banner/banner.story.js
  src/implementations/vanilla/components/banner/banner.scss
Labels: tag: bug fix

#3629 feat(inpage): Using the right element to determine the top position in mobile - FRONT-4620
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation.js
Labels: tag: enhancement

#3631 chore(deps): Updates - 17-09-24
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3603 feat(video): Adding support for muted, autoplay and loop - Media container adding autoplay video option - FRONT-4600
  src/implementations/twig/components/banner/__snapshots__/banner.test.js.snap
  src/implementations/twig/components/banner/banner.html.twig
  src/implementations/twig/components/banner/banner.test.js
  src/implementations/twig/components/media-container/README.md
  src/implementations/twig/components/media-container/__snapshots__/media-container.test.js.snap
  src/implementations/twig/components/media-container/media-container.html.twig
  src/implementations/twig/components/media-container/media-container.story.js
  src/implementations/twig/components/media-container/media-container.test.js
  src/implementations/twig/components/video/README.md
  src/implementations/twig/components/video/__snapshots__/video.test.js.snap
  src/implementations/twig/components/video/video.html.twig
  src/implementations/twig/components/video/video.test.js
  src/implementations/vanilla/components/media-container/media-container.js
  src/implementations/vanilla/components/media-container/media-container.scss
  src/specs/components/media-container/demo/data--video.js
Labels: tag: enhancement, tag: markup changes, tag: data change

#3632 feat(youtube): Removing disablekb parameter - FRONT-4616
  src/implementations/vanilla/components/gallery/gallery.js
  src/implementations/vanilla/components/media-container/media-container.js
Labels: tag: enhancement

#3633 fix(unordered-list): Setting list style position to outside also in print - FRONT-4602
  src/implementations/vanilla/components/ordered-list/ordered-list-print.scss
  src/implementations/vanilla/components/unordered-list/unordered-list-print.scss
Labels: tag: bug fix

#3639 fix(table): Fixing js for the sortable table - FRONT-4625
  src/implementations/vanilla/components/table/table.js
Labels: tag: bug fix

#3641 chore(storybook): Adding param to disable edit/create story from the interface
  src/playground/ec/.storybook/preview.js
  src/playground/eu/.storybook/preview.js
Labels: tag: internal

#3637 fix(table): fix rtl display on mobile - FRONT-4624
  src/implementations/vanilla/components/table/table-print.scss
  src/implementations/vanilla/components/table/table.scss
  src/themes/ec/variables/_table.scss
  src/themes/eu/variables/_table.scss
Labels: tag: bug fix, process: review needed

#3538 feat(gallery): grid templates - FRONT-4622
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/twig/components/gallery/gallery.html.twig
  src/implementations/twig/components/gallery/gallery.story.js
  src/implementations/vanilla/components/gallery/gallery-print.scss
  src/implementations/vanilla/components/gallery/gallery.scss
  src/specs/components/gallery/demo/data.js
Labels: tag: new feature, process: review needed, tag: markup changes, tag: data change

#3643 chore(deps): Updates - 24-09-24
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/tools/builder/scripts/styles.js
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3644 fix(file-download): fix transparent background - FRONT-4628
  src/implementations/vanilla/components/file/file.scss
  src/themes/eu/variables/_file.scss
Labels: tag: bug fix

#3646 chore(deps): Storybook 8.3.3
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  yarn.lock
Labels: tag: internal

#3577 feat(file-download): add preview link - FRONT-4574
  src/implementations/twig/components/file/README.md
  src/implementations/twig/components/file/__snapshots__/file.test.js.snap
  src/implementations/twig/components/file/file-translation-item.html.twig
  src/implementations/twig/components/file/file-translations.html.twig
  src/implementations/twig/components/file/file.html.twig
  src/implementations/twig/components/file/file.story.js
  src/implementations/twig/components/file/file.test.js
  src/implementations/vanilla/components/file/file-print.scss
  src/implementations/vanilla/components/file/file.scss
  src/specs/components/file/demo/data--taxonomy.js
  src/specs/components/file/demo/data--thumbnail.js
  src/specs/components/file/demo/data--with-translation.js
  src/themes/ec/variables/_file.scss
  src/themes/eu/variables/_file.scss
Labels: tag: new feature, tag: markup changes, tag: data change

#3638 feat(link): update EU inverted link color - FRONT-4629
  src/implementations/twig/components/link/link.story.js
  src/implementations/vanilla/components/gallery/gallery.scss
  src/themes/ec/variables/_gallery.scss
  src/themes/eu/variables/_gallery.scss
  src/themes/eu/variables/_link.scss
Labels: tag: enhancement

#3648 fix(mega-menu): Improving height calculations for the second panel - FRONT-4633
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/twig/components/mega-menu/mega-menu-item.html.twig
  src/implementations/vanilla/components/mega-menu/mega-menu.js
  src/specs/components/mega-menu/demo/data.js
Labels: tag: enhancement, tag: markup changes

#3636 fix(storybook): Fixing storybook for mobile devices
  patches/@storybook+addon-cssresources+6.2.9.patch
  src/playground/addons/storybook-addon-code/HTMLMarkup.jsx
  src/playground/addons/storybook-addon-code/index.js
  src/playground/addons/storybook-addon-code/register.jsx
  src/playground/addons/storybook-addon-notes/register.jsx
  src/playground/ec/.storybook/preview-head.html
  src/playground/eu/.storybook/preview-head.html
  yarn.lock
Labels: tag: internal

#3634 feat(easy-to-read): Adding optional "easy-to-read" css - FRONT-4598
  src/implementations/twig/utilities/easy-to-read/easy-to-read.story.js
  src/presets/ec/ecl-builder.config.js
  src/presets/ec/src/ec-easy-to-read.scss
  src/presets/eu/ecl-builder.config.js
  src/presets/eu/src/eu-easy-to-read.scss
Labels: tag: new feature

#3615 fix(mega-menu): Mega menu content position fix - FRONT-4606
  src/implementations/twig/components/site-header/ec-site-header.story.js
  src/implementations/twig/components/site-header/eu-site-header.story.js
  src/implementations/vanilla/components/mega-menu/mega-menu.js
  src/implementations/vanilla/components/mega-menu/mega-menu.scss
Labels: tag: enhancement, process: business approval needed

#3651 feat(apis): Adding api docs for media container - FRONT-4635
  src/website/package.json
  src/website/src/pages/ec/components/media/media-container/docs/api.mdx
  src/website/src/pages/eu/components/media/media-container/docs/api.mdx
Labels: tag: internal

#3645 feat(notification): Adding links, updating styles - FRONT-4630
  src/implementations/twig/components/notification/README.md
  src/implementations/twig/components/notification/__snapshots__/notification.test.js.snap
  src/implementations/twig/components/notification/notification.html.twig
  src/implementations/twig/components/notification/notification.story.js
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/site-header/ec-site-header.story.js
  src/implementations/twig/components/site-header/eu-site-header.story.js
  src/implementations/vanilla/components/notification/notification-print.scss
  src/implementations/vanilla/components/notification/notification.scss
  src/specs/components/notification/demo/data--error-eu.js
  src/specs/components/notification/demo/data--info-ec.js
  src/specs/components/notification/demo/data--info-eu.js
  src/specs/components/notification/demo/data--success-eu.js
  src/specs/components/notification/demo/data--warning-eu.js
  src/specs/components/site-header/demo/data--ec.js
  src/specs/components/site-header/demo/data--eu.js
  src/themes/ec/variables/_notification.scss
  src/themes/eu/variables/_notification.scss
Labels: tag: enhancement, tag: markup changes, tag: data change

#3649 fix(modal): fix close button position on rtl - FRONT-4623
  src/implementations/vanilla/components/modal/modal.scss
  src/themes/ec/variables/_modal.scss
  src/themes/eu/variables/_modal.scss
Labels: tag: bug fix

#3647 fix(menu): fix touch devices - FRONT-4632
  src/implementations/vanilla/components/menu/menu.js
Labels: tag: bug fix
