Repository ec-europa/europa-component-library, pull requests merged in 2024-06, with the labels that each got.

#3418 feat(mega-menu): update "discover more" link - FRONT-4446
  src/implementations/twig/components/mega-menu/README.md
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/twig/components/mega-menu/mega-menu-item.html.twig
  src/implementations/twig/components/mega-menu/mega-menu.html.twig
  src/specs/components/mega-menu/demo/data.js
Labels: tag: enhancement, tag: data change

#3417 fix(mega-menu): fix link not clickable - FRONT-4444
  src/implementations/vanilla/components/mega-menu/mega-menu.js
Labels: tag: bug fix

#3412 feat(icon): update example on website - FRONT-4439
  src/website/src/pages/ec/components/icon/demo/index.js
  src/website/src/pages/eu/components/icon/demo/index.js
Labels: tag: documentation

#3422 feat(date block): update styles - FRONT-4449
  src/implementations/vanilla/components/date-block/date-block.scss
  src/themes/ec/variables/_date-block.scss
  src/themes/eu/variables/_date-block.scss
Labels: tag: enhancement

#3428 feat(icons): add Bluesky icons - FRONT-4441
  src/resources/icons-social-media/src/social-media/bluesky-color.svg
  src/resources/icons-social-media/src/social-media/bluesky-negative.svg
  src/resources/icons-social-media/src/social-media/bluesky.svg
Labels: tag: enhancement

#3432 feat(mega-menu): Container content centered, fixes for EU
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/twig/components/mega-menu/mega-menu-item.html.twig
  src/implementations/vanilla/components/mega-menu/mega-menu.js
  src/implementations/vanilla/components/mega-menu/mega-menu.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/themes/ec/variables/_mega-menu.scss
  src/themes/eu/variables/_mega-menu.scss
Labels: tag: enhancement, tag: markup changes

#3390 feat(gallery): design update - FRONT-4387
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/twig/components/gallery/gallery-item.html.twig
  src/implementations/twig/components/gallery/gallery-overlay.html.twig
  src/implementations/twig/components/gallery/gallery.html.twig
  src/implementations/vanilla/components/button/button.scss
  src/implementations/vanilla/components/gallery/gallery-print.scss
  src/implementations/vanilla/components/gallery/gallery.js
  src/implementations/vanilla/components/gallery/gallery.scss
  src/implementations/vanilla/components/gallery/package.json
  src/themes/ec/theme.scss
  src/themes/ec/variables/_button.scss
  src/themes/ec/variables/_gallery.scss
  src/themes/eu/theme.scss
  src/themes/eu/variables/_button.scss
  src/themes/eu/variables/_gallery.scss
Labels: tag: enhancement, tag: markup changes

#3435 chore(deps): Updates 14 06 24
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  src/website/src/pages/ec/utilities/layout/grid/index.mdx
  src/website/src/pages/eu/utilities/layout/grid/index.mdx
  yarn.lock
Labels: tag: internal

#3430 feat(accordion): update styles - FRONT-4455
  src/implementations/twig/components/accordion/accordion.story.js
  src/implementations/vanilla/components/accordion/accordion-ec.scss
  src/implementations/vanilla/components/accordion/accordion.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/themes/ec/variables/_accordion.scss
  src/themes/eu/variables/_accordion.scss
Labels: tag: enhancement

#3393 feat(list with illustration): add center for vertical list (icons) and improve print - FRONT-4428
  .size-limit.json
  src/implementations/twig/components/list-illustration/list-illustration.story.js
  src/implementations/vanilla/components/list-illustration/list-illustration-print.scss
  src/implementations/vanilla/components/list-illustration/list-illustration.scss
Labels: tag: enhancement

#3397 feat(inpage-navigation): improve labels - FRONT-4398
  src/implementations/twig/components/inpage-navigation/__snapshots__/inpage-navigation.test.js.snap
  src/implementations/twig/components/inpage-navigation/inpage-navigation.html.twig
  src/specs/components/inpage-navigation/demo/data.js
Labels: tag: enhancement, tag: data change

#3396 feat(inpage-navigation): improve keyboard navigation - FRONT-4397
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation.js
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation.scss
  src/implementations/vanilla/components/inpage-navigation/package.json
Labels: tag: enhancement

#3424 feat(timeline): update style and example - FRONT-4452
  src/implementations/twig/components/timeline/__snapshots__/timeline.test.js.snap
  src/implementations/twig/components/timeline/timeline.story.js
  src/implementations/twig/components/timeline/timeline.test.js
  src/implementations/vanilla/components/timeline/timeline.scss
  src/specs/components/timeline/demo/data--ec.js
  src/specs/components/timeline/demo/data.js
  src/themes/ec/variables/_timeline.scss
  src/themes/eu/variables/_timeline.scss
  src/website/src/pages/ec/components/timeline/demo/index.js
  src/website/src/pages/eu/components/timeline/demo/index.js
Labels: tag: enhancement

#3425 feat(pagination): update styles - FRONT-4445
  src/implementations/vanilla/components/pagination/pagination.scss
  src/themes/ec/variables/_pagination.scss
  src/themes/eu/variables/_pagination.scss
Labels: tag: enhancement

#3400 feat(meta): update meta list display - FRONT-4419
  src/implementations/twig/components/file/__snapshots__/file.test.js.snap
  src/implementations/twig/components/file/file.html.twig
  src/implementations/twig/components/page-header/__snapshots__/page-header.test.js.snap
  src/implementations/twig/components/page-header/page-header.html.twig
  src/implementations/vanilla/components/content-block/content-block.scss
  src/implementations/vanilla/components/file/file-print.scss
  src/implementations/vanilla/components/file/file.scss
  src/implementations/vanilla/components/page-header/page-header-ec.scss
  src/implementations/vanilla/components/page-header/page-header-eu.scss
  src/implementations/vanilla/components/page-header/page-header-print-ec.scss
  src/implementations/vanilla/components/page-header/page-header-print-eu.scss
  src/themes/ec/variables/_page-header.scss
  src/themes/eu/variables/_page-header.scss
Labels: tag: enhancement, tag: markup changes

#3420 feat(range): add bubble for value - FRONT-4436
  .size-limit.json
  src/implementations/twig/components/form-group/__snapshots__/form-group.test.js.snap
  src/implementations/twig/components/range/__snapshots__/range.test.js.snap
  src/implementations/twig/components/range/range.html.twig
  src/implementations/vanilla/components/range/range.js
  src/implementations/vanilla/components/range/range.scss
  src/themes/eu/variables/_range.scss
Labels: tag: enhancement, tag: markup changes

#3437 chore(deps): Updates 18-06-24
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3407 feat(table): table without header - FRONT-4437
  src/implementations/twig/components/table/table.html.twig
  src/implementations/twig/components/table/table.story.js
  src/implementations/vanilla/components/table/table.scss
  src/presets/ec/src/ec-default-print.scss
  src/presets/ec/src/ec-default.scss
  src/presets/eu/src/eu-default-print.scss
  src/presets/eu/src/eu-default.scss
  src/themes/ec/variables/_table.scss
Labels: tag: enhancement

#3191 feat(website): update display - FRONT-4208
  src/implementations/twig/utilities/typography/index.story.js
  src/website/src/components/DocPage/Header.jsx
  src/website/src/components/DocPage/Header.scss
  src/website/src/components/Navigation/LinkList.scss
  src/website/src/components/Navigation/LinkSection.scss
  src/website/src/components/Navigation/Navigation.jsx
  src/website/src/components/Navigation/Navigation.scss
  src/website/src/components/Navigation/SingleLink.scss
  src/website/src/components/SplashPage/LogoLink.scss
  src/website/src/pages/ec/components/index.mdx
  src/website/src/pages/ec/components/loading-indicator/index.md
  src/website/src/pages/ec/guidelines/spacing/index.mdx
  src/website/src/pages/ec/index.md
  src/website/src/pages/ec/utilities/layout/grid/docs/usage.mdx
  src/website/src/pages/ec/utilities/layout/grid/index.md
  src/website/src/pages/ec/utilities/layout/stacks/docs/usage.mdx
  src/website/src/pages/ec/utilities/typography/docs/code.mdx
  src/website/src/pages/eu/components/index.mdx
  src/website/src/pages/eu/components/loading-indicator/index.md
  src/website/src/pages/eu/guidelines/spacing/index.mdx
  src/website/src/pages/eu/index.md
  src/website/src/pages/eu/utilities/layout/grid/docs/usage.mdx
  src/website/src/pages/eu/utilities/layout/grid/index.md
  src/website/src/pages/eu/utilities/layout/stacks/docs/usage.mdx
  src/website/src/pages/eu/utilities/typography/docs/code.mdx
  src/website/src/styles/app.scss
  src/website/src/styles/markdown.scss
  src/website/src/website-components/DoDont/Caution.jsx
  src/website/src/website-components/DoDont/Do.jsx
  src/website/src/website-components/DoDont/DoDont.jsx
  src/website/src/website-components/DoDont/DoDont.scss
  src/website/src/website-components/DoDont/Dont.jsx
  src/website/src/website-components/Icon/IconCard.jsx
  src/website/src/website-components/Icon/IconCard.scss
  src/website/src/website-components/Logo/LogoCard.jsx
  src/website/src/website-components/Logo/LogoCard.scss
  src/website/src/website-components/Playground.jsx
  src/website/src/website-components/Playground.scss
  src/website/src/website-components/Thumbnail/Thumbnail.scss
  src/website/src/website-components/index.js
Labels: tag: enhancement

#3438 feat(accordion): Removing outdated code in the js - FRONT-4465
  src/implementations/vanilla/components/accordion/accordion.js
Labels: tag: enhancement

#3414 feat(icon): add control for icon title - FRONT-4399
  src/implementations/twig/components/button/button.html.twig
  src/implementations/twig/components/button/button.story.js
  src/implementations/twig/components/icon/README.md
  src/implementations/twig/components/icon/icon.html.twig
  src/implementations/twig/components/icon/icon.story.js
  src/implementations/twig/components/link/link.html.twig
  src/implementations/twig/components/link/link.story.js
  src/playground/addons/story-utils/index.js
Labels: tag: enhancement

#3434 feat(gallery): add grid display - FRONT-4459
  src/implementations/twig/components/gallery/README.md
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/twig/components/gallery/gallery.html.twig
  src/implementations/twig/components/gallery/gallery.story.js
  src/implementations/twig/components/gallery/gallery.test.js
  src/implementations/vanilla/components/gallery/gallery-print.scss
  src/implementations/vanilla/components/gallery/gallery.js
  src/implementations/vanilla/components/gallery/gallery.scss
Labels: tag: enhancement, process: review needed, tag: data change

#3374 feat(site-header): Logo sizes and EU revamp - FRONT-4390
  src/implementations/twig/components/site-header/README.md
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/site-header/ec-site-header.story.js
  src/implementations/twig/components/site-header/eu-site-header.story.js
  src/implementations/twig/components/site-header/site-header.html.twig
  src/implementations/vanilla/components/menu/menu.scss
  src/implementations/vanilla/components/site-header/_site-header-language-switcher.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/specs/components/menu/demo/data--eu-long.js
  src/specs/components/menu/demo/data--eu.js
  src/specs/components/site-header/demo/data--ec.js
  src/specs/components/site-header/demo/data--eu.js
  src/themes/ec/variables/_site-header.scss
  src/themes/eu/variables/_site-header.scss
Labels: tag: enhancement, tag: markup changes, tag: data change

#3441 fix(utilities): Ratio for safari - FRONT-4408
  src/implementations/vanilla/utilities/media/media.scss
Labels: tag: bug fix

#3442 chore(storybook): Showing description for the controls - FRONT-4466
  src/playground/ec/.storybook/preview.js
  src/playground/eu/.storybook/preview.js
Labels: tag: internal

#3446 chore(deps): Updates 21-06-24
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3439 fix(breadcrumb): Returning a promise from computeVisibilityMap - FRONT-4314
  .size-limit.json
  src/implementations/twig/components/breadcrumb/__snapshots__/breadcrumb.test.js.snap
  src/implementations/twig/components/breadcrumb/breadcrumb.html.twig
  src/implementations/vanilla/components/breadcrumb/breadcrumb.js
  src/implementations/vanilla/components/breadcrumb/breadcrumb.scss
Labels: tag: enhancement, tag: markup changes

#3445 feat(menu): improve focus loop - FRONT-4402
  src/implementations/vanilla/components/mega-menu/mega-menu.js
  src/implementations/vanilla/components/menu/menu.js
Labels: tag: enhancement

#3427 feat(button): update font size - FRONT-4457
  src/implementations/vanilla/components/button/button-print.scss
  src/themes/ec/maps/typography.scss
  src/themes/ec/variables/_button.scss
  src/themes/eu/variables/_button.scss
Labels: tag: enhancement

#3444 feat(mega-menu): Fixing static position of the mega menu wrapper and toggle button - FRONT-4469
  src/implementations/vanilla/components/mega-menu/mega-menu.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/themes/eu/variables/_mega-menu.scss
Labels: tag: bug fix

#3443 feat(style): update typography - FRONT-4467
  src/implementations/vanilla/components/banner/banner.scss
  src/implementations/vanilla/components/page-header/page-header-ec.scss
  src/themes/ec/maps/typography.scss
  src/themes/ec/variables/_banner.scss
  src/themes/eu/maps/typography.scss
  src/themes/eu/variables/_banner.scss
  src/website/src/pages/ec/guidelines/typography/index.mdx
  src/website/src/pages/eu/guidelines/typography/index.mdx
Labels: tag: enhancement, tag: token change

#3402 feat(media-container, gallery): embedded video audio description information - FRONT-4362
  src/implementations/twig/components/gallery/README.md
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/twig/components/gallery/gallery-item.html.twig
  src/implementations/twig/components/gallery/gallery-video.html.twig
  src/implementations/twig/components/gallery/gallery.html.twig
  src/implementations/twig/components/media-container/README.md
  src/implementations/twig/components/media-container/media-container.html.twig
  src/implementations/twig/components/media-container/media-container.story.js
  src/implementations/vanilla/components/gallery/gallery-print.scss
  src/implementations/vanilla/components/gallery/gallery.js
  src/implementations/vanilla/components/gallery/gallery.scss
  src/implementations/vanilla/components/media-container/media-container-print.scss
  src/implementations/vanilla/components/media-container/media-container.scss
  src/implementations/vanilla/components/media-container/package.json
  src/specs/components/gallery/demo/data.js
Labels: tag: enhancement, tag: markup changes, tag: data change

#3454 feat(EC Usage pages for components): update EC Usage pages for components “ec_news_ticker”
  src/website/src/pages/ec/components/news-ticker/docs/usage.md
Labels: netlify-cms/pending_publish
