Repository ec-europa/europa-component-library, pull requests merged in 2024-07, with the labels that each got.

#3453 fix(multi-select): Fixing width in mobile - FRONT-4471
  src/implementations/vanilla/components/select/select.scss
Labels: tag: bug fix

#3455 chore(deps): Updates 27-06-24
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3457 feat(breadcrumb): Changing aria-label for the ellipsis in our demos - FRONT-4474
  src/specs/components/breadcrumb/demo/data--long.js
  src/specs/components/breadcrumb/demo/data--simple.js
Labels: tag: enhancement

#3436 feat(select): Making the select all and search field optional in the multiselect - FRONT-4462
  src/implementations/twig/components/form-group/form-group.story.js
  src/implementations/twig/components/select/README.md
  src/implementations/twig/components/select/select.html.twig
  src/implementations/vanilla/components/select/select.js
  src/implementations/vanilla/components/select/select.scss
Labels: tag: enhancement, tag: data change

#3458 feat(select): Removing unneeded aria-label - FRONT-4477
  src/implementations/twig/components/form-group/__snapshots__/form-group.test.js.snap
  src/implementations/twig/components/select/select.html.twig
  src/implementations/twig/components/select/select.test.js
Labels: tag: enhancement

#3459 feat(category-filter): Adding support for current item at init, extra attributes for the items - FRONT-4475
  src/implementations/twig/components/category-filter/README.md
  src/implementations/twig/components/category-filter/__snapshots__/category-filter.test.js.snap
  src/implementations/twig/components/category-filter/category-filter-items.html.twig
  src/implementations/twig/components/category-filter/category-filter.html.twig
  src/implementations/twig/components/category-filter/category-filter.test.js
  src/implementations/vanilla/components/category-filter/category-filter.js
  src/specs/components/category-fiter/demo/data.js
Labels: tag: enhancement, tag: data change

#3461 chore(deps): Updates - 03-07-24
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3460 feat(custom-properties): Adding custom props for font family, using them in the components - FRONT-4490
  src/implementations/vanilla/components/banner/banner-print.scss
  src/implementations/vanilla/components/date-block/date-block.scss
  src/implementations/vanilla/components/expandable/expandable-print.scss
  src/implementations/vanilla/components/expandable/expandable.scss
  src/implementations/vanilla/components/fact-figures/fact-figures-print.scss
  src/implementations/vanilla/components/file/file-print.scss
  src/implementations/vanilla/components/link/link-print.scss
  src/implementations/vanilla/components/link/link.scss
  src/implementations/vanilla/components/menu/menu-print.scss
  src/implementations/vanilla/components/ordered-list/ordered-list-print.scss
  src/implementations/vanilla/components/page-header/page-header-print-eu.scss
  src/implementations/vanilla/components/site-header/site-header-print.scss
  src/implementations/vanilla/components/unordered-list/unordered-list-print.scss
  src/themes/ec/_custom-properties.scss
  src/themes/ec/variables/_description-list.scss
  src/themes/eu/_custom-properties.scss
  src/themes/eu/variables/_description-list.scss
Labels: tag: enhancement

#3463 feat(typography): update line height - FRONT-4487
  src/themes/ec/maps/typography.scss
  src/website/src/pages/ec/guidelines/typography/index.mdx
Labels: tag: enhancement, tag: token change

#3447 feat(news-ticker): Icon or image for each item, iteration on styles for EC and EU - FRONT-4463
  src/implementations/twig/components/news-ticker/README.md
  src/implementations/twig/components/news-ticker/__snapshots__/news-ticker.test.js.snap
  src/implementations/twig/components/news-ticker/news-ticker.html.twig
  src/implementations/vanilla/components/news-ticker/news-ticker.js
  src/implementations/vanilla/components/news-ticker/news-ticker.scss
  src/specs/components/news-ticker/demo/data.js
  src/themes/ec/variables/_news-ticker.scss
  src/themes/eu/variables/_news-ticker.scss
Labels: tag: markup changes, tag: data change

#3462 feat(search-form): Removing aria label, adding support for extra classes for the button and the input - FRONT-4479
  src/implementations/twig/components/search-form/__snapshots__/search-form.test.js.snap
  src/implementations/twig/components/search-form/search-form.html.twig
  src/implementations/twig/components/search-form/search-form.test.js
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
Labels: tag: enhancement, tag: markup changes

#3467 feat(EC Usage pages for components): update EC Usage pages for components “ec_button”
  src/website/src/pages/ec/components/button/docs/usage.md
Labels: netlify-cms/pending_publish

#3468 feat(EU Usage pages for components): update EU Usage pages for components “eu_button”
  src/website/src/pages/eu/components/button/docs/usage.md
Labels: netlify-cms/pending_publish

#3469 feat(EC Usage pages for components): update EC Usage pages for components “ec_button”
  src/website/src/pages/ec/components/button/docs/usage.md
Labels: netlify-cms/pending_publish

#3470 feat(EU Usage pages for components): update EU Usage pages for components “eu_button”
  src/website/src/pages/eu/components/button/docs/usage.md
Labels: netlify-cms/pending_publish

#3465 feat(banner): new options and video - FRONT-4488
  .size-limit.json
  src/implementations/twig/components/banner/README.md
  src/implementations/twig/components/banner/__snapshots__/banner.test.js.snap
  src/implementations/twig/components/banner/banner.html.twig
  src/implementations/twig/components/banner/banner.story.js
  src/implementations/twig/components/banner/banner.test.js
  src/implementations/twig/components/banner/package.json
  src/implementations/twig/components/carousel/__snapshots__/carousel.test.js.snap
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/vanilla/components/banner/banner-print.scss
  src/implementations/vanilla/components/banner/banner.js
  src/implementations/vanilla/components/banner/banner.scss
  src/specs/components/banner/demo/data--image.js
  src/specs/components/banner/demo/data--plain-background.js
  src/specs/components/banner/demo/data--text-overlay.js
  src/specs/components/banner/demo/data--video.js
  src/specs/components/gallery/demo/data.js
  src/themes/ec/variables/_banner.scss
  src/themes/eu/variables/_banner.scss
  src/website/src/pages/ec/components/banner/demo/index.js
  src/website/src/pages/ec/components/banner/docs/code.mdx
  src/website/src/pages/ec/components/banner/index.md
  src/website/src/pages/eu/components/banner/demo/index.js
  src/website/src/pages/eu/components/banner/docs/code.mdx
  src/website/src/pages/eu/components/banner/index.md
Labels: tag: new feature, tag: markup changes, tag: data change

#3448 feat(list with illustration fact and figures): update styles - FRONT-4468
  src/implementations/twig/components/fact-figures/README.md
  src/implementations/twig/components/fact-figures/__snapshots__/fact-figures.test.js.snap
  src/implementations/twig/components/fact-figures/fact-figures.html.twig
  src/implementations/twig/components/fact-figures/fact-figures.story.js
  src/implementations/twig/components/list-illustration/README.md
  src/implementations/twig/components/list-illustration/list-illustration.html.twig
  src/implementations/twig/components/list-illustration/list-illustration.story.js
  src/implementations/vanilla/components/fact-figures/fact-figures-print.scss
  src/implementations/vanilla/components/fact-figures/fact-figures.scss
  src/implementations/vanilla/components/list-illustration/list-illustration-print.scss
  src/implementations/vanilla/components/list-illustration/list-illustration.scss
  src/specs/components/fact-figures/demo/data.js
  src/themes/ec/variables/_fact-figures.scss
  src/themes/ec/variables/_list-illustration.scss
  src/themes/eu/variables/_fact-figures.scss
  src/themes/eu/variables/_list-illustration.scss
Labels: tag: enhancement

#3372 feat(menu): add aria-current - FRONT-4405
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/menu-item.html.twig
Labels: tag: enhancement, tag: markup changes

#3471 feat(flags): Adding new non members flags - FRONT-4498
  .size-limit.json
  src/resources/icons-flag/src/non-members/armenia-square.svg
  src/resources/icons-flag/src/non-members/armenia.svg
  src/resources/icons-flag/src/non-members/israel-square.svg
  src/resources/icons-flag/src/non-members/israel.svg
  src/resources/icons-flag/src/non-members/liechtenstein-square.svg
  src/resources/icons-flag/src/non-members/liechtenstein.svg
  src/resources/icons-flag/src/non-members/united-kingdom-square.svg
  src/resources/icons-flag/src/non-members/united-kingdom.svg
Labels: tag: new feature

#3421 feat(form): update style of all form elements - FRONT-4432
  src/implementations/twig/components/checkbox/__snapshots__/checkbox.test.js.snap
  src/implementations/twig/components/checkbox/checkbox-group.html.twig
  src/implementations/twig/components/checkbox/checkbox-item.html.twig
  src/implementations/twig/components/form-group/__snapshots__/form-group.test.js.snap
  src/implementations/twig/components/form-group/form-group.html.twig
  src/implementations/twig/components/form-group/form-group.story.js
  src/implementations/twig/compositions/file-upload-status/__snapshots__/file-upload-status.test.js.snap
  src/implementations/twig/compositions/file-upload-status/file-upload-status.html.twig
  src/implementations/vanilla/components/checkbox/checkbox.scss
  src/implementations/vanilla/components/datepicker/datepicker.scss
  src/implementations/vanilla/components/file-upload/file-upload.scss
  src/implementations/vanilla/components/radio/radio.scss
  src/implementations/vanilla/components/rating-field/rating-field.scss
  src/implementations/vanilla/components/select/select.scss
  src/implementations/vanilla/components/text-area/text-area.scss
  src/implementations/vanilla/components/text-input/text-input.scss
  src/specs/components/checkbox/demo/data.js
  src/specs/components/datepicker/demo/data.js
  src/specs/components/file-upload/demo/data--multiple.js
  src/specs/components/file-upload/demo/data.js
  src/specs/components/radio/demo/data--binary.js
  src/specs/components/radio/demo/data--default.js
  src/specs/components/range/demo/data.js
  src/specs/components/rating-field/demo/data.js
  src/specs/components/select/demo/data-multiple.js
  src/specs/components/select/demo/data-single.js
  src/specs/components/text-area/demo/data.js
  src/specs/components/text-input/demo/data.js
  src/themes/ec/maps/form.scss
  src/themes/ec/variables/_checkbox.scss
  src/themes/ec/variables/_file-upload.scss
  src/themes/ec/variables/_radio.scss
  src/themes/ec/variables/_select.scss
  src/themes/eu/maps/form.scss
  src/themes/eu/variables/_checkbox.scss
  src/themes/eu/variables/_datepicker.scss
  src/themes/eu/variables/_file-upload.scss
  src/themes/eu/variables/_form-group.scss
  src/themes/eu/variables/_radio.scss
  src/themes/eu/variables/_range.scss
  src/themes/eu/variables/_rating-field.scss
  src/themes/eu/variables/_search-form.scss
  src/themes/eu/variables/_select.scss
  src/themes/eu/variables/_text-area.scss
  src/themes/eu/variables/_text-input.scss
  src/website/src/pages/ec/components/forms/text-field/index.md
Labels: tag: enhancement, tag: markup changes

#3456 feat(twig): cleanup and update parameters - FRONT-4438
  src/implementations/twig/components/banner/banner.story.js
  src/implementations/twig/components/carousel/README.md
  src/implementations/twig/components/carousel/carousel.html.twig
  src/implementations/twig/components/checkbox/README.md
  src/implementations/twig/components/checkbox/checkbox-item.html.twig
  src/implementations/twig/components/date-block/README.md
  src/implementations/twig/components/date-block/date-block.html.twig
  src/implementations/twig/components/datepicker/README.md
  src/implementations/twig/components/datepicker/datepicker.html.twig
  src/implementations/twig/components/expandable/README.md
  src/implementations/twig/components/expandable/expandable.html.twig
  src/implementations/twig/components/fact-figures/fact-figures.html.twig
  src/implementations/twig/components/file-upload/README.md
  src/implementations/twig/components/file-upload/file-upload.html.twig
  src/implementations/twig/components/file/file-translation-item.html.twig
  src/implementations/twig/components/gallery/README.md
  src/implementations/twig/components/gallery/gallery-overlay.html.twig
  src/implementations/twig/components/gallery/gallery.html.twig
  src/implementations/twig/components/inpage-navigation/README.md
  src/implementations/twig/components/inpage-navigation/inpage-navigation.html.twig
  src/implementations/twig/components/mega-menu/README.md
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/twig/components/mega-menu/mega-menu-item.html.twig
  src/implementations/twig/components/mega-menu/mega-menu.html.twig
  src/implementations/twig/components/menu/menu.html.twig
  src/implementations/twig/components/modal/README.md
  src/implementations/twig/components/modal/modal.html.twig
  src/implementations/twig/components/news-ticker/news-ticker.html.twig
  src/implementations/twig/components/notification/README.md
  src/implementations/twig/components/notification/notification.html.twig
  src/implementations/twig/components/popover/README.md
  src/implementations/twig/components/popover/popover.html.twig
  src/implementations/twig/components/radio/README.md
  src/implementations/twig/components/radio/radio-button.html.twig
  src/implementations/twig/components/range/README.md
  src/implementations/twig/components/range/range.html.twig
  src/implementations/twig/components/rating-field/README.md
  src/implementations/twig/components/rating-field/rating-field.html.twig
  src/implementations/twig/components/select/README.md
  src/implementations/twig/components/select/select.html.twig
  src/implementations/twig/components/splash-page/README.md
  src/implementations/twig/components/splash-page/splash-page.html.twig
  src/implementations/twig/components/table/__snapshots__/table.test.js.snap
  src/implementations/twig/components/table/table.html.twig
  src/implementations/twig/components/text-area/README.md
  src/implementations/twig/components/text-area/text-area.html.twig
  src/implementations/twig/components/text-input/README.md
  src/implementations/twig/components/text-input/text-input.html.twig
  src/implementations/twig/components/timeline/README.md
  src/implementations/twig/components/timeline/__snapshots__/timeline.test.js.snap
  src/implementations/twig/components/timeline/timeline.html.twig
  src/implementations/twig/components/timeline/timeline.test.js
  src/implementations/vanilla/components/tabs/tabs.js
  src/specs/components/gallery/demo/data.js
  src/specs/components/inpage-navigation/demo/data.js
  src/specs/components/mega-menu/demo/data.js
  src/specs/components/splash-page/demo/data--ec.js
  src/specs/components/splash-page/demo/data--eu.js
  src/specs/components/table/demo/data--sort-table.js
  src/specs/components/timeline/demo/data.js
Labels: tag: enhancement

#3475 feat(video): homogenize track name - FRONT-4503
  src/implementations/twig/components/banner/__snapshots__/banner.test.js.snap
  src/implementations/twig/components/media-container/__snapshots__/media-container.test.js.snap
  src/specs/components/banner/demo/data--video.js
  src/specs/components/media-container/demo/data--video.js
Labels: tag: enhancement

#3473 feat(inpage-nav): improve mobile keyboard navigation - FRONT-4501
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation.js
Labels: tag: enhancement

#3449 feat(tabs): EU styles - FRONT-4451
  src/implementations/vanilla/components/tabs/tabs.js
  src/implementations/vanilla/components/tabs/tabs.scss
  src/themes/ec/variables/_tabs.scss
  src/themes/eu/variables/_tabs.scss
Labels: tag: enhancement

#3353 feat(media container): disable Youtube shortcuts - FRONT-4363
  src/implementations/vanilla/components/gallery/gallery.js
  src/implementations/vanilla/components/media-container/media-container.js
Labels: tag: enhancement, process: review needed

#3431 feat(modal): update styles - FRONT-4453
  src/implementations/twig/components/modal/modal.html.twig
  src/implementations/twig/components/modal/modal.story.js
  src/implementations/twig/components/modal/modal.test.js
  src/implementations/vanilla/components/modal/modal.scss
  src/specs/components/modal/demo/data-eu.js
  src/specs/components/modal/demo/data.js
  src/themes/ec/variables/_modal.scss
  src/themes/eu/variables/_button.scss
  src/themes/eu/variables/_modal.scss
  src/website/src/pages/ec/components/modal/demo/index.js
  src/website/src/pages/eu/components/modal/demo/index.js
Labels: tag: enhancement, tag: data change

#3476 chore(deps): Updates 12-07-24
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3477 feat(input): Using outline for focus style - FRONT-4504
  src/implementations/vanilla/components/text-input/text-input.scss
  src/themes/ec/variables/_text-input.scss
  src/themes/eu/variables/_text-input.scss
Labels: tag: enhancement

#3478 fix(file-upload): Button only taking the needed space - FRONT-4493
  src/implementations/vanilla/components/file-upload/file-upload.scss
Labels: tag: enhancement

#3482 feat(mega-menu): Supporting aria-labels for nested lists - FRONT-4515
  src/implementations/twig/components/mega-menu/README.md
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/twig/components/mega-menu/mega-menu-item.html.twig
  src/implementations/twig/components/mega-menu/mega-menu.html.twig
  src/specs/components/mega-menu/demo/data.js
Labels: tag: enhancement, tag: markup changes, tag: data change

#3483 feat(mega-menu): Removing unneded aria-label - FRONT-4521
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/twig/components/mega-menu/mega-menu.html.twig
  src/specs/components/mega-menu/demo/data.js
Labels: tag: enhancement, tag: markup changes, tag: data change

#3474 feat(button): setting height, using same values for padding in default and hover - FRONT-4499
  src/implementations/vanilla/components/button/button.scss
  src/implementations/vanilla/components/mega-menu/mega-menu.scss
  src/implementations/vanilla/components/menu/menu.js
  src/implementations/vanilla/components/menu/menu.scss
  src/implementations/vanilla/components/search-form/search-form.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/themes/ec/variables/_button.scss
  src/themes/ec/variables/_mega-menu.scss
  src/themes/eu/variables/_button.scss
  src/themes/eu/variables/_mega-menu.scss
  src/themes/eu/variables/_menu.scss
Labels: tag: enhancement

#3484 feat(mega-menu): Aria-label on view all link - FONT-4516
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/specs/components/mega-menu/demo/data.js
Labels: tag: enhancement, tag: markup changes, tag: data change

#3487 feat(mega-menu): Aria-describedby on featured column title - FRONT-4522
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/twig/components/mega-menu/mega-menu-item.html.twig
  src/implementations/twig/components/mega-menu/mega-menu.html.twig
  src/implementations/vanilla/components/mega-menu/mega-menu.js
Labels: tag: enhancement, tag: markup changes

#3481 docs(website): update color page - FRONT-4506
  src/website/src/pages/ec/guidelines/colours/index.mdx
Labels: tag: enhancement

#3485 feat(mega-menu): Handling focus on Esc - FRONT-4517
  src/implementations/vanilla/components/mega-menu/mega-menu.js
  src/implementations/vanilla/components/mega-menu/mega-menu.scss
Labels: tag: enhancement

#3488 feat(mega-menu): Not moving the focus when opening the menu - FRONT-4518
  src/implementations/vanilla/components/mega-menu/mega-menu.js
Labels: tag: enhancement

#3480 feat(pagination): update EU display - FRONT-4509
  src/implementations/twig/components/pagination/__snapshots__/pagination.test.js.snap
  src/implementations/twig/components/pagination/pagination.story.js
  src/implementations/vanilla/components/pagination/pagination.scss
  src/specs/components/pagination/demo/data.js
  src/themes/ec/variables/_pagination.scss
  src/themes/eu/variables/_pagination.scss
Labels: tag: enhancement, tag: data change

#3490 feat(mega-menu): Making the hamburger a button with javascript - FRONT-4519
  src/implementations/vanilla/components/mega-menu/mega-menu.js
Labels: tag: enhancement

#3489 feat(social-media-follow): add position right - FRONT-4505
  src/implementations/twig/components/social-media-follow/README.md
  src/implementations/twig/components/social-media-follow/__snapshots__/social-media-follow.test.js.snap
  src/implementations/twig/components/social-media-follow/social-media-follow.html.twig
  src/implementations/twig/components/social-media-follow/social-media-follow.story.js
  src/implementations/twig/components/social-media-follow/social-media-follow.test.js
  src/implementations/vanilla/components/social-media-follow/social-media-follow-print.scss
  src/implementations/vanilla/components/social-media-follow/social-media-follow.scss
  src/website/src/pages/ec/components/social-media-follow/demo/index.js
  src/website/src/pages/ec/components/social-media-follow/docs/code.mdx
  src/website/src/pages/eu/components/social-media-follow/demo/index.js
  src/website/src/pages/eu/components/social-media-follow/docs/code.mdx
Labels: tag: enhancement, tag: data change

#3486 feat(mega-menu): Adding aria-describedby in info link - FRONT-4520
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/twig/components/mega-menu/mega-menu-item.html.twig
  src/implementations/twig/components/mega-menu/mega-menu.test.js
  src/implementations/vanilla/components/mega-menu/mega-menu.js
Labels: tag: enhancement, tag: markup changes

#3493 chore(deps): Updates - 16-07-24
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3479 feat(date-block): Small adjustments in the year block - FRONT-4510
  src/implementations/vanilla/components/date-block/date-block.scss
  src/themes/ec/variables/_date-block.scss
  src/themes/eu/variables/_date-block.scss
Labels: tag: enhancement

#3492 feat(social media follow): update icons size and spacing - FRONT-4523
  src/implementations/twig/components/social-media-follow/__snapshots__/social-media-follow.test.js.snap
  src/implementations/twig/components/social-media-follow/social-media-follow.html.twig
  src/implementations/vanilla/components/social-media-follow/social-media-follow-print.scss
  src/implementations/vanilla/components/social-media-follow/social-media-follow.scss
  src/presets/ec/src/ec-print.scss
  src/presets/eu/src/eu-print.scss
  src/specs/components/social-media-follow/demo/data--color.js
  src/specs/components/social-media-follow/demo/data--monochrome.js
  src/themes/ec/variables/_social-media-follow.scss
  src/themes/eu/variables/_social-media-follow.scss
Labels: tag: enhancement

#3500 fix(footer): fix accessibility issue in link - FRONT-4496
  src/implementations/twig/components/site-footer/__snapshots__/site-footer.test.js.snap
  src/implementations/vanilla/components/site-footer/site-footer-eu.scss
  src/specs/components/site-footer/demo/data-harmonised--eu.js
Labels: tag: enhancement, tag: markup changes, tag: data change

#3495 feat(textarea): Using outline for focus styles - FRONT-4512
  src/implementations/vanilla/components/text-area/text-area.scss
  src/themes/ec/variables/_text-area.scss
  src/themes/eu/variables/_text-area.scss
Labels: tag: enhancement

#3498 fix(range): fix aria label - FRONT-4524
  src/implementations/twig/components/form-group/__snapshots__/form-group.test.js.snap
  src/implementations/twig/components/range/__snapshots__/range.test.js.snap
  src/implementations/twig/components/range/range.html.twig
  src/implementations/twig/components/range/range.test.js
Labels: tag: markup changes

#3501 feat(inpage): Consistent border and padding in different states - FRONT-4508
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation.scss
  src/themes/ec/variables/_inpage-navigation.scss
  src/themes/eu/variables/_inpage-navigation.scss
Labels: tag: enhancement

#3505 feat(icons): Adding eye icon in the main sprite - FRONT-4528
  src/implementations/twig/components/icon/__snapshots__/icon.test.js.snap
  src/resources/icons/src/all/eye.svg
Labels: tag: new feature

#3509 fix(range): fix bubble position on rtl - FRONT-4531
  src/implementations/vanilla/components/range/range.js
  src/implementations/vanilla/components/range/range.scss
Labels: tag: bug fix

#3512 feat(max-width): Setting values for the --max-w variable in the utilities - FRONT-4532
  src/implementations/vanilla/utilities/dimension/dimension.scss
Labels: tag: enhancement

#3513 docs(typography): add accessibility warnings - FRONT-4507
  src/website/src/pages/ec/utilities/typography/docs/usage.mdx
  src/website/src/pages/eu/utilities/typography/docs/usage.md
Labels: tag: documentation

#3508 feat(banner): update control - FRONT-4530
  src/implementations/twig/components/banner/banner.story.js
Labels: tag: enhancement, process: review needed

#3511 feat(utilities): deprecate ecl-u-sr-only--focusable utilities - FRONT-4500
  src/implementations/vanilla/utilities/screen-reader/README.md
  src/implementations/vanilla/utilities/screen-reader/screen-reader.scss
  src/website/src/pages/ec/utilities/screen-reader/docs/usage.mdx
  src/website/src/pages/eu/utilities/screen-reader/docs/usage.mdx
Labels: tag: enhancement

#3514 feat(accordion): Rendering two icons, toggling them via css - FRONT-4529
  src/implementations/twig/components/accordion/README.md
  src/implementations/twig/components/accordion/__snapshots__/accordion.test.js.snap
  src/implementations/twig/components/accordion/accordion.html.twig
  src/implementations/twig/components/accordion/accordion.test.js
  src/implementations/vanilla/components/accordion/accordion.js
  src/implementations/vanilla/components/accordion/accordion.scss
  src/specs/components/accordion/demo/data.js
Labels: tag: enhancement, tag: markup changes, tag: data change

#3516 chore(deps): Updates - 27-07-24
  .husky/pre-commit
  package.json
  src/implementations/vanilla/components/datepicker/datepicker.scss
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  yarn.lock
Labels: tag: internal

#3510 feat(footer): 22px line height (from the standalone link) for all the links, EC and EU - FRONT-4511
  .husky/pre-commit
  src/implementations/vanilla/components/link/link.scss
  src/implementations/vanilla/components/mega-menu/mega-menu.scss
  src/implementations/vanilla/components/site-footer/site-footer-ec.scss
  src/implementations/vanilla/components/site-footer/site-footer-eu.scss
  src/themes/ec/variables/_mega-menu.scss
  src/themes/ec/variables/_site-footer.scss
  src/themes/eu/variables/_site-footer.scss
Labels: tag: enhancement

#3507 feat(logo): update logo markup - FRONT-4480
  src/implementations/twig/components/site-footer/README.md
  src/implementations/twig/components/site-footer/__snapshots__/site-footer.test.js.snap
  src/implementations/twig/components/site-footer/site-footer.html.twig
  src/implementations/twig/components/site-header/README.md
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/site-header/site-header.html.twig
  src/implementations/twig/components/splash-page/README.md
  src/implementations/twig/components/splash-page/__snapshots__/splash-page.test.js.snap
  src/implementations/twig/components/splash-page/splash-page.html.twig
  src/specs/components/site-footer/demo/data-core--ec.js
  src/specs/components/site-footer/demo/data-core--eu.js
  src/specs/components/site-footer/demo/data-harmonised--ec.js
  src/specs/components/site-footer/demo/data-harmonised--eu.js
  src/specs/components/site-footer/demo/data-standardised--ec.js
  src/specs/components/site-header/demo/data--ec.js
  src/specs/components/site-header/demo/data--eu.js
  src/specs/components/splash-page/demo/data--ec.js
  src/specs/components/splash-page/demo/data--eu.js
Labels: tag: enhancement, tag: markup changes

#3518 chore(deps): Storybook - 25-07-24
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  yarn.lock
Labels: tag: internal

#3517 feat(site-header): Adding language code to the button aria-label - FRONT-4483
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/site-header/site-header-language-switcher.html.twig
Labels: tag: enhancement

#3521 fix(social-media-follow): add missing tag - FRONT-4536
  src/implementations/twig/components/social-media-follow/social-media-follow.html.twig
Labels: tag: bug fix

#3520 fix(carousel): fix display issue on EU - FRONT-4534
  src/implementations/twig/components/carousel/__snapshots__/carousel.test.js.snap
  src/specs/components/carousel/demo/data.js
Labels: process: review needed

#3499 feat(form): update required fields - FRONT-4495
  src/implementations/vanilla/components/form-group/form-group.scss
  src/themes/ec/variables/_form-group.scss
  src/themes/eu/variables/_form-group.scss
Labels: tag: enhancement

#3503 feat(mega-menu): Adding style for the current sub-items in desktop - FRONT-4527
  src/implementations/vanilla/components/mega-menu/mega-menu.js
  src/implementations/vanilla/components/mega-menu/mega-menu.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
Labels: tag: enhancement, process: business approval needed

#3525 feat(site-header): add menu to core site header - FRONT-4535
  src/implementations/twig/components/site-header/ec-site-header.story.js
  src/implementations/twig/components/site-header/eu-site-header.story.js
Labels: tag: enhancement, process: review needed

#3494 feat(mega-menu): Using buttons for parent elements - FRONT-4514
  src/implementations/twig/components/mega-menu/README.md
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/twig/components/mega-menu/mega-menu-item.html.twig
  src/implementations/twig/components/mega-menu/mega-menu.html.twig
  src/implementations/vanilla/components/mega-menu/mega-menu.js
  src/implementations/vanilla/components/mega-menu/mega-menu.scss
  src/specs/components/mega-menu/demo/data.js
Labels: tag: enhancement, tag: markup changes, tag: data change

#3528 chore(deps): Updates 29-07-24
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3519 feat(splash-page): use headings - FRONT-4481
  src/implementations/twig/components/splash-page/__snapshots__/splash-page.test.js.snap
  src/implementations/twig/components/splash-page/splash-page.html.twig
  src/implementations/vanilla/components/splash-page/splash-page-print.scss
  src/implementations/vanilla/components/splash-page/splash-page.scss
Labels: tag: enhancement

#3527 chore(sass): Declarations before nested rules - FRONT-4540
  src/implementations/vanilla/components/pagination/pagination.scss
  src/implementations/vanilla/layout/grid/mixins/_grid-framework.scss
Labels: tag: internal, process: review needed

#3522 feat(banner): Description as a link, some fixes - FRONT-4353
  src/implementations/twig/components/banner/README.md
  src/implementations/twig/components/banner/__snapshots__/banner.test.js.snap
  src/implementations/twig/components/banner/banner.html.twig
  src/implementations/twig/components/banner/banner.story.js
  src/implementations/twig/components/banner/banner.test.js
  src/implementations/vanilla/components/banner/banner.scss
  src/specs/components/banner/demo/data--image.js
  src/specs/components/banner/demo/data--video.js
  src/website/src/pages/ec/components/banner/demo/index.js
  src/website/src/pages/eu/components/banner/demo/index.js
Labels: tag: enhancement, tag: markup changes, tag: data change

#3531 feat(mega-menu): Adding blur handler on featured links - FRONT-4544
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/twig/components/mega-menu/mega-menu-item.html.twig
  src/implementations/vanilla/components/mega-menu/mega-menu.js
Labels: tag: enhancement

#3523 chore(deps): Upgrading iframe-resizer, removing usage of svg4everybody - FRONT-4539
  src/playground/ec/.storybook/ECL.jsx
  src/playground/ec/package.json
  src/playground/eu/.storybook/ECL.jsx
  src/playground/eu/package.json
  src/website/package.json
  src/website/scripts/docs.js
  src/website/src/App.jsx
  src/website/src/pages/ec/components/icon/docs/code.mdx
  src/website/src/website-components/Playground.jsx
  src/website/src/website-components/Showcase/Iframe.jsx
  yarn.lock
Labels: tag: internal

#3515 feat(featured-item): change order - FRONT-4476
  src/implementations/twig/components/featured-item/__snapshots__/featured-item.test.js.snap
  src/implementations/twig/components/featured-item/featured-item.html.twig
  src/implementations/vanilla/components/featured-item/featured-item-print.scss
  src/implementations/vanilla/components/featured-item/featured-item.scss
Labels: tag: enhancement, tag: markup changes

#3504 feat(gallery, media container): add title to videos - FRONT-4526
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/twig/components/gallery/gallery-item.html.twig
  src/implementations/twig/components/gallery/gallery-video.html.twig
  src/implementations/twig/components/gallery/gallery.html.twig
  src/implementations/twig/components/media-container/README.md
  src/implementations/twig/components/media-container/__snapshots__/media-container.test.js.snap
  src/implementations/twig/components/media-container/media-container.html.twig
  src/implementations/vanilla/components/gallery/gallery.js
  src/implementations/vanilla/components/gallery/gallery.scss
  src/implementations/vanilla/components/media-container/media-container.js
  src/specs/components/media-container/demo/data--embed-video.js
  src/specs/components/media-container/demo/data--video.js
Labels: tag: enhancement, tag: markup changes, tag: data change

#3532 chore(website): Fixing height of the iframe for the popopver example - FRONT-4549
  src/website/src/pages/ec/components/popover/docs/code.mdx
  src/website/src/pages/eu/components/popover/docs/code.mdx
Labels: tag: internal

#3533 fix(site-header): Preventing rendering of an empty banner - FRONT-4550
  src/implementations/twig/components/site-header/site-header.html.twig
  src/implementations/vanilla/components/mega-menu/mega-menu.js
Labels: tag: bug fix

#3536 feat(page header): deprecate overlay - FRONT-4548
  src/implementations/twig/components/page-header/page-header.html.twig
  src/implementations/twig/components/page-header/page-header.story.js
  src/implementations/vanilla/components/page-header/page-header-ec.scss
  src/implementations/vanilla/components/page-header/page-header-eu.scss
Labels: tag: enhancement

#3534 feat(mega-menu): aria-labelledby for the featured links - FRONT-4543
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/twig/components/mega-menu/mega-menu-item.html.twig
Labels: process: review needed, tag: markup changes
