Repository ec-europa/europa-component-library, pull requests merged in 2024-08, with the labels that each got.

#3526 feat(mega-menu): Fixing styles in EU, adding demo in site header - FRONT-4541
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/twig/components/mega-menu/mega-menu.html.twig
  src/implementations/twig/components/site-header/eu-site-header.story.js
  src/implementations/vanilla/components/mega-menu/mega-menu.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/themes/ec/variables/_mega-menu.scss
  src/themes/eu/variables/_mega-menu.scss
  src/themes/eu/variables/_menu.scss
  src/website/src/pages/ec/components/site-wide/site-header/docs/code.mdx
  src/website/src/pages/eu/components/site-wide/site-header/docs/code.mdx
Labels: tag: enhancement

#3529 feat(splash-page): change markup for "lang" attribute
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/site-header/site-header-language-switcher.html.twig
  src/implementations/twig/components/splash-page/__snapshots__/splash-page.test.js.snap
  src/implementations/twig/components/splash-page/splash-page.html.twig
Labels: tag: enhancement, process: review needed, tag: markup changes

#3542 chore(deps): Updates 01-08-24
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3537 feat(timeline): improve focus after expand - FRONT-4484
  src/implementations/vanilla/components/timeline/timeline.js
Labels: tag: enhancement

#3539 feat(social-media-follow): update spacing - FRONT-4552
  src/implementations/vanilla/components/social-media-follow/social-media-follow.scss
Labels: tag: enhancement

#3547 fix(button): fix print css - FRONT-4561
  src/implementations/vanilla/components/button/button-print.scss
  src/presets/ec/src/ec-default-print.scss
  src/presets/ec/src/ec-print.scss
  src/presets/eu/src/eu-default-print.scss
  src/presets/eu/src/eu-print.scss
  src/themes/ec/theme.scss
  src/themes/ec/variables/_button.scss
  src/themes/eu/theme.scss
  src/themes/eu/variables/_button.scss
Labels: tag: bug fix

#3545 feat(link): increase underline offset - FRONT-4555
  src/implementations/vanilla/components/banner/banner.scss
  src/implementations/vanilla/components/link/link.scss
  src/implementations/vanilla/components/mega-menu/mega-menu.scss
  src/implementations/vanilla/components/tag/tag.scss
Labels: tag: enhancement

#3540 feat(menu): add aria-label on main nav - FRONT-4478
  src/implementations/twig/components/menu/README.md
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/menu.html.twig
  src/specs/components/menu/demo/data--ec-long.js
  src/specs/components/menu/demo/data--ec.js
  src/specs/components/menu/demo/data--eu-long.js
  src/specs/components/menu/demo/data--eu.js
Labels: tag: enhancement, tag: markup changes, tag: data change

#3530 feat(media-container): update control - FRONT-4546
  src/implementations/twig/components/media-container/media-container.story.js
Labels: tag: enhancement

#3551 feat(menu/mega-menu): remove aria-current=true - FRONT-4545
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/menu-item.html.twig
  src/implementations/vanilla/components/mega-menu/mega-menu.js
Labels: tag: enhancement, tag: markup changes

#3546 fix(breadcrumb): fix wrap when expanding - FRONT-4558
  src/implementations/vanilla/components/breadcrumb/breadcrumb.js
  src/implementations/vanilla/components/breadcrumb/breadcrumb.scss
Labels: tag: bug fix

#3550 chore(deps): Updates 07-08-24
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3554 feat(video): replace demo video - FRONT-4567
  src/implementations/twig/components/banner/__snapshots__/banner.test.js.snap
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/twig/components/media-container/__snapshots__/media-container.test.js.snap
  src/specs/components/banner/demo/data--video.js
  src/specs/components/gallery/demo/data.js
  src/specs/components/media-container/demo/data--video.js
Labels: tag: internal

#3558 chore(deps): Updates 12-08-24
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  yarn.lock
Labels: tag: internal

#3557 feat(language-list): Making the list scrollable - FRONT-4564
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/site-header/site-header-language-switcher.html.twig
  src/implementations/vanilla/components/site-header/_site-header-language-switcher.scss
  src/implementations/vanilla/components/site-header/site-header.js
Labels: tag: enhancement

#3556 feat(inpage): Making the list scrollable, moving scrollbar to the left in EC - FRONT-4563
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation.js
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation.scss
  src/themes/ec/variables/_inpage-navigation.scss
  src/themes/eu/variables/_inpage-navigation.scss
Labels: tag: enhancement

#3563 feat(mega-menu): Removing aria label from see all links - FRONT-4572
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/specs/components/mega-menu/demo/data.js
Labels: tag: enhancement, tag: markup changes

#3553 feat(gallery): add thumbnail - FRONT-4565
  .size-limit.json
  src/implementations/twig/components/gallery/README.md
  src/implementations/twig/components/gallery/__snapshots__/gallery.test.js.snap
  src/implementations/twig/components/gallery/gallery-item.html.twig
  src/implementations/twig/components/gallery/gallery.html.twig
  src/implementations/twig/components/picture/README.md
  src/implementations/twig/components/picture/picture.html.twig
  src/implementations/vanilla/components/gallery/gallery-print.scss
  src/implementations/vanilla/components/gallery/gallery.js
  src/implementations/vanilla/components/gallery/gallery.scss
  src/specs/components/gallery/demo/data.js
Labels: tag: new feature, tag: markup changes, tag: data change

#3561 fix(site-header): fixing language switcher in rtl - FRONT-4569
  .size-limit.json
  src/implementations/vanilla/components/site-header/_site-header-language-switcher.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/implementations/vanilla/components/site-header/site-header.js
  src/themes/ec/variables/_language-list.scss
  src/themes/eu/variables/_language-list.scss
  yarn.lock
Labels: tag: bug fix, tag: markup changes

#3559 feat(menus): Removing role application from the inner section of the menus - FRONT-4568
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/twig/components/mega-menu/mega-menu.html.twig
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/menu.html.twig
  src/implementations/vanilla/components/menu/menu.js
Labels: tag: enhancement, process: review needed, tag: markup changes

#3564 fix(site-header): Fixing margin reset for search button in EU - FRONT-4575
  src/implementations/vanilla/components/site-header/site-header-eu.scss
Labels: tag: bug fix

#3565 chore(deps): Fixing audit issue
  package.json
  yarn.lock
Labels: tag: internal

#3567 chore(deps): Updates 16-08-24
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3570 chore(deps): Upgrading sass-loader
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3568 feat(menu): Using button for the toggle - FRONT-4542
  src/implementations/twig/components/menu/README.md
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/menu.html.twig
  src/implementations/vanilla/components/menu/menu.js
  src/specs/components/mega-menu/demo/data.js
  src/specs/components/menu/demo/data--ec-long.js
  src/specs/components/menu/demo/data--ec.js
  src/specs/components/menu/demo/data--eu-long.js
  src/specs/components/menu/demo/data--eu.js
Labels: tag: enhancement, tag: markup changes, tag: data change

#3574 chore(deps): Updates - 21-08-24
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3569 feat(popover): Adding support for buttons as triggers - FRONT-4350
  src/implementations/twig/components/popover/README.md
  src/implementations/twig/components/popover/__snapshots__/popover.test.js.snap
  src/implementations/twig/components/popover/popover.html.twig
  src/implementations/twig/components/popover/popover.story.js
  src/implementations/twig/components/popover/popover.test.js
  src/specs/components/popover/demo/data.js
Labels: tag: enhancement

#3572 docs(website): update stack documentation - FRONT-4577
  src/website/src/pages/ec/utilities/layout/stacks/docs/code.mdx
  src/website/src/pages/ec/utilities/layout/stacks/docs/usage.mdx
  src/website/src/pages/ec/utilities/layout/stacks/index.md
  src/website/src/pages/eu/utilities/layout/stacks/docs/code.mdx
  src/website/src/pages/eu/utilities/layout/stacks/docs/usage.mdx
  src/website/src/pages/eu/utilities/layout/stacks/index.md
Labels: tag: documentation

#3576 chore(deps): Rollup
  src/playground/addons/storybook-addon-notes/package.json
  src/tools/builder/package.json
  yarn.lock
Labels: tag: internal

#3571 feat(banner): copyright position, background and image height - FRONT-4570
  src/implementations/twig/components/banner/__snapshots__/banner.test.js.snap
  src/implementations/twig/components/banner/banner.html.twig
  src/implementations/twig/components/banner/banner.story.js
  src/implementations/twig/components/carousel/__snapshots__/carousel.test.js.snap
  src/implementations/vanilla/components/banner/banner-print.scss
  src/implementations/vanilla/components/banner/banner.js
  src/implementations/vanilla/components/banner/banner.scss
  src/implementations/vanilla/components/carousel/carousel.scss
  src/implementations/vanilla/components/gallery/gallery.scss
  src/themes/ec/variables/_banner.scss
  src/themes/ec/variables/_carousel.scss
  src/themes/eu/variables/_banner.scss
  src/themes/eu/variables/_carousel.scss
Labels: tag: enhancement, tag: markup changes

#3552 feat(headings): set spacing - FRONT-4566
  src/implementations/vanilla/utilities/typography/typography-print.scss
  src/implementations/vanilla/utilities/typography/typography.scss
  src/themes/ec/variables/_typography.scss
  src/themes/eu/variables/_typography.scss
Labels: tag: enhancement

#3549 feat(icons): add and update icons - FRONT-4562
  src/implementations/twig/components/icon/__snapshots__/icon.test.js.snap
  src/resources/icons/src/all/global.svg
  src/resources/icons/src/all/log-in.svg
  src/resources/icons/src/all/logged-in.svg
  src/resources/icons/src/all/notification-active.svg
  src/resources/icons/src/all/notification.svg
  src/resources/icons/src/all/shopping-bag.svg
Labels: tag: enhancement

#3581 chore(deps): Updates 23-08-24
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3584 fix(banner): Fixing css for video banner size - FRONT-4583
  src/implementations/vanilla/components/banner/banner.scss
Labels: tag: bug fix

#3580 fix(content-block): Setting display: inline on the title link - FRONT-4557
  src/implementations/vanilla/components/content-block/content-block.scss
Labels: tag: enhancement

#3585 chore(deps): Fixing audit issue - 26-08-24
  package.json
  yarn.lock
Labels: tag: internal

#3548 feat(modal): additional sizes - FRONT-4559
  src/implementations/twig/components/modal/__snapshots__/modal.test.js.snap
  src/implementations/twig/components/modal/modal.html.twig
  src/implementations/twig/components/modal/modal.story.js
  src/implementations/vanilla/components/modal/modal.scss
  src/presets/rtl/src/rtl.scss
Labels: tag: enhancement, tag: markup changes

#3579 feat(social-media): change twitter label - FRONT-4582
  src/implementations/twig/components/site-footer/__snapshots__/site-footer.test.js.snap
  src/implementations/twig/components/social-media-follow/README.md
  src/implementations/twig/components/social-media-share/README.md
  src/implementations/twig/components/social-media-share/__snapshots__/social-media-share.test.js.snap
  src/implementations/vanilla/components/site-footer/site-footer-ec.scss
  src/implementations/vanilla/components/site-footer/site-footer-eu.scss
  src/specs/components/site-footer/demo/data-harmonised--ec.js
  src/specs/components/site-footer/demo/data-standardised--ec.js
  src/specs/components/social-media-share/demo/data.js
Labels: tag: enhancement, tag: data change

#3589 feat(site-header): wax-off EC - FRONT-4586
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/themes/ec/variables/_site-header.scss
Labels: tag: enhancement

#3586 chore: Node 20.9.0 and rimraf upgrade
  .github/workflows/ci.yml
  .github/workflows/production.yml
  .nvmrc
  README.md
  docs/developers-start-here.md
  package.json
  src/presets/ec/package.json
  src/presets/eu/package.json
  src/presets/reset/package.json
  src/presets/rtl/package.json
  src/resources/icons-flag/package.json
  src/resources/icons-flag/scripts/build-lists.js
  src/resources/icons-flag/scripts/build-sprites.js
  src/resources/icons-flag/scripts/clean-svg.js
  src/resources/icons-social-media/package.json
  src/resources/icons-social-media/scripts/build-lists.js
  src/resources/icons-social-media/scripts/build-sprites.js
  src/resources/icons-social-media/scripts/clean-svg.js
  src/resources/icons/package.json
  src/resources/icons/scripts/build-lists.js
  src/resources/icons/scripts/build-sprites.js
  src/resources/icons/scripts/clean-svg.js
  src/resources/logo-ec/package.json
  src/resources/logo-eu/package.json
  src/resources/social-icons/package.json
  src/resources/social-icons/scripts/build-sprites.js
  src/resources/social-icons/scripts/clean-svg.js
  src/resources/social-icons/scripts/generate-lists.js
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal
