Repository ec-europa/europa-component-library, pull requests merged in 2024-03, with the labels that each got.

#3257 fix(menu): Preventing page scrolling when opened in mobile, fixing position in mobile - FRONT-4283
  src/implementations/vanilla/components/menu/menu.js
  src/implementations/vanilla/components/menu/menu.scss
Labels: tag: bug fix

#3262 chore: Usage page updates for the site-wide components
  src/website/src/pages/ec/components/site-wide/page-header/docs/usage.md
  src/website/src/pages/ec/components/site-wide/site-footer/docs/usage.md
  src/website/src/pages/ec/components/site-wide/site-header/docs/usage.md
  src/website/src/pages/eu/components/site-wide/page-header/docs/usage.md
  src/website/src/pages/eu/components/site-wide/site-footer/docs/usage.md
  src/website/src/pages/eu/components/site-wide/site-header/docs/usage.md
Labels: tag: documentation

#3265 fix(language-list): Fixing color on :visited for the current item - FRONT-4290
  src/implementations/vanilla/components/site-header/_site-header-language-switcher.scss
Labels: tag: bug fix

#3266 fix(css): Not including the light variant for the menu in EU - FRONT-4287
  src/implementations/vanilla/components/menu/menu.scss
Labels: tag: bug fix

#3267 chore(website): Adding link to v3.13.0 - FRONT-4289
  src/website/src/pages/ec/index.md
  src/website/src/pages/eu/index.md
Labels: tag: documentation

#3272 feat(EU Usage pages for components): update EU Usage pages for components “eu_button”
  src/website/src/pages/eu/components/button/docs/usage.md
Labels: netlify-cms/pending_publish

#3271 feat(EC Usage pages for components): update EC Usage pages for components “ec_button”
  src/website/src/pages/ec/components/button/docs/usage.md
Labels: netlify-cms/pending_publish

#3273 fix(notification): Fixing position of the background element for the warning icon - FRONT-4294
  src/themes/ec/variables/_notification.scss
  src/themes/eu/variables/_notification.scss
Labels: tag: bug fix

#3268 feat(Docs): update Docs “ec_index”
  src/website/src/pages/ec/index.md
Labels: netlify-cms/pending_publish

#3269 feat(Docs): update Docs “eu_index”
  src/website/src/pages/eu/index.md
Labels: netlify-cms/pending_publish

#3270 feat(Docs): update Docs “ec_whats_new”
  src/website/src/pages/ec/whats-new/index.md
Labels: netlify-cms/pending_publish

#3209 feat(icon): Replacing twitter with X icons - FRONT-4061
  src/resources/icons-social-media/src/social-media/twitter-color.svg
  src/resources/icons-social-media/src/social-media/twitter-negative.svg
  src/resources/icons-social-media/src/social-media/twitter.svg
Labels: tag: new feature

#3284 feat(list): Revamp of unordered list - FRONT-4304
  src/implementations/vanilla/components/unordered-list/unordered-list.scss
Labels: tag: enhancement

#3283 feat(images): Removing borders, keeping them only in content-item - FRONT-4303
  src/implementations/vanilla/components/list-illustration/list-illustration.scss
  src/implementations/vanilla/components/media-container/media-container.scss
  src/implementations/vanilla/components/navigation-list/navigation-list.scss
  src/implementations/vanilla/components/page-header/page-header-ec.scss
  src/implementations/vanilla/components/page-header/page-header-eu.scss
  src/themes/ec/variables/_media-container.scss
  src/themes/ec/variables/_navigation-list.scss
  src/themes/eu/variables/_media-container.scss
  src/themes/eu/variables/_navigation-list.scss
Labels: tag: enhancement

#3280 feat(links): Removing color switch for visited links - FRONT-4302
  src/themes/ec/variables/_link.scss
  src/themes/eu/variables/_link.scss
Labels: tag: enhancement

#3282 feat(featured-item): Revamp of the default variant in EC - FRONT-4300
  src/implementations/vanilla/components/featured-item/featured-item-print.scss
  src/implementations/vanilla/components/featured-item/featured-item.scss
  src/themes/ec/variables/_featured-item.scss
  src/themes/eu/variables/_featured-item.scss
Labels: tag: enhancement

#3285 feat(navigation-list): Setting 100% height for the items - FRONT-4305
  src/implementations/vanilla/components/navigation-list/navigation-list.scss
Labels: tag: enhancement

#3281 feat(page-header): Removing padding bottom in EU, fixing no margin - FRONT-4301
  src/implementations/vanilla/components/page-header/page-header-eu.scss
Labels: tag: bug fix

#3286 chore(deps): green and orange updates 14-03-24
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3279 fix(list-illustration): Fixing center alignment - FRONT-4298
  src/implementations/twig/components/list-illustration/__snapshots__/list-illustration.test.js.snap
  src/implementations/twig/components/list-illustration/list-illustration-item.html.twig
  src/implementations/twig/components/list-illustration/list-illustration.test.js
  src/implementations/vanilla/components/list-illustration/list-illustration.scss
Labels: tag: bug fix

#3290 fix(blockquote): fix blockquote in wysiwyg - FRONT-4307
  src/implementations/twig/utilities/html-tag/index.story.js
  src/implementations/vanilla/components/blockquote/blockquote.scss
  src/presets/ec/src/ec-default.scss
  src/presets/eu/src/eu-default.scss
Labels: tag: bug fix

#3288 fix(blockquote): Fixing styles for the cite element - FRONT-4306
  src/implementations/vanilla/components/blockquote/blockquote.scss
Labels: tag: bug fix

#3292 feat(navigation-list): reduce spacing - FRONT-4308
  src/implementations/vanilla/components/content-block/content-block.scss
  src/themes/ec/variables/_content-block.scss
  src/themes/eu/variables/_content-block.scss
Labels: tag: enhancement

#3293 feat(navigation-list): remove background when there is no border - FRONT-4309
  src/implementations/vanilla/components/navigation-list/navigation-list.scss
Labels: tag: enhancement

#3295 fix(icon): update x/twitter icon size
  src/resources/icons-social-media/src/social-media/twitter-color.svg
  src/resources/icons-social-media/src/social-media/twitter-negative.svg
  src/resources/icons-social-media/src/social-media/twitter.svg
Labels: tag: bug fix

#3294 fix(featured-item): fix picture spacing - FRONT-4310
  src/implementations/vanilla/components/featured-item/featured-item.scss
  src/themes/ec/variables/_featured-item.scss
  src/themes/eu/variables/_featured-item.scss
Labels: tag: bug fix, process: review needed

#3276 fix(menu): Bring the user back to the open/close button when reaching the last item in mobile - FRONT-4288
  src/implementations/vanilla/components/menu/menu.js
Labels: tag: bug fix

#3291 feat(button): remove tertiary button background and update components using it - FRONT-4295
  src/implementations/twig/components/carousel/README.md
  src/implementations/twig/components/carousel/__snapshots__/carousel.test.js.snap
  src/implementations/twig/components/carousel/carousel.html.twig
  src/implementations/vanilla/components/carousel/carousel.js
  src/implementations/vanilla/components/gallery/gallery.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/themes/ec/variables/_button.scss
  src/themes/eu/variables/_button.scss
Labels: tag: enhancement, process: review needed

#3246 feat(tag-set): use html list markup - FRONT-4262
  src/implementations/twig/components/tag/__snapshots__/tag.test.js.snap
  src/implementations/twig/components/tag/tag-set.html.twig
  src/implementations/vanilla/components/tag/tag.scss
Labels: tag: enhancement, tag: markup changes

#3247 feat(table): add accessibility scope - FRONT-4259
  src/implementations/twig/components/table/__snapshots__/table.test.js.snap
  src/implementations/twig/components/table/table.html.twig
Labels: tag: enhancement, tag: markup changes

#3307 fix(checkbox): fix website demo - FRONT-4328
  src/website/src/pages/ec/components/forms/checkbox/docs/code.mdx
  src/website/src/pages/eu/components/forms/checkbox/docs/code.mdx
Labels: tag: bug fix

#3306 fix(menu): Fixing position in the site-header and inner styles for RTL support - FRONT-4327
  src/implementations/vanilla/components/menu/menu.js
  src/implementations/vanilla/components/menu/menu.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
Labels: tag: bug fix

#3304 feat(modal): add screen reader text to icon - FRONT-4320
  src/implementations/twig/components/modal/README.md
  src/implementations/twig/components/modal/__snapshots__/modal.test.js.snap
  src/implementations/twig/components/modal/modal.html.twig
  src/implementations/twig/components/modal/modal.story.js
  src/implementations/twig/components/modal/modal.test.js
  src/implementations/twig/components/notification/README.md
Labels: tag: enhancement, tag: data change

#3303 fix(file-upload): add focus styles - FRONT-4317
  src/implementations/vanilla/components/file-upload/file-upload.scss
Labels: tag: bug fix

#3302 feat(button): update EU button styles - FRONT-4323
  src/implementations/twig/components/button/button.story.js
  src/implementations/vanilla/components/button/button.scss
  src/themes/ec/variables/_button.scss
  src/themes/eu/maps/color.scss
  src/themes/eu/variables/_button.scss
  src/themes/eu/variables/_link.scss
Labels: tag: enhancement

#3253 feat(table): add optional caption - FRONT-4274
  src/implementations/twig/components/table/README.md
  src/implementations/twig/components/table/__snapshots__/table.test.js.snap
  src/implementations/twig/components/table/table.html.twig
  src/implementations/vanilla/components/table/table-print.scss
  src/implementations/vanilla/components/table/table.scss
  src/specs/components/table/demo/data--default.js
  src/specs/components/table/demo/data--multi.js
  src/specs/components/table/demo/data--sort-table.js
  src/themes/ec/variables/_table.scss
  src/themes/eu/variables/_table.scss
Labels: tag: enhancement, tag: data change
