Repository ec-europa/europa-component-library, pull requests merged in 2024-01, with the labels that each got.

#3148 feat(file): add empty alt - FRONT-4186
  src/implementations/twig/components/file/__snapshots__/file.test.js.snap
  src/implementations/twig/components/file/file.story.js
  src/implementations/twig/components/picture/picture.html.twig
  src/specs/components/file/demo/data--taxonomy.js
  src/specs/components/file/demo/data--thumbnail.js
  src/website/src/pages/ec/components/file/docs/code.mdx
  src/website/src/pages/eu/components/file/docs/code.mdx
Labels: tag: enhancement

#3153 feat(form): change feedback message position - FRONT-4189
  src/implementations/twig/components/form-group/__snapshots__/form-group.test.js.snap
  src/implementations/twig/components/form-group/form-group.html.twig
  src/implementations/twig/components/form-group/form-group.story.js
  src/implementations/vanilla/components/checkbox/_checkbox.scss
  src/implementations/vanilla/components/file-upload/_file-upload.scss
  src/implementations/vanilla/components/form-group/_form-group.scss
  src/implementations/vanilla/components/radio/_radio.scss
Labels: tag: enhancement

#3158 chore(deps): Updates 03-01-24 v4
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/resources/icons-ec/package.json
  src/resources/icons-eu/package.json
  src/resources/icons-flag/package.json
  src/resources/icons-social-media/package.json
  src/resources/social-icons/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3154 feat(components): homogenize max width - FRONT-4190
  src/implementations/vanilla/components/accordion/accordion-ec.scss
  src/implementations/vanilla/components/accordion/accordion-eu.scss
  src/implementations/vanilla/components/accordion/accordion-print.scss
  src/implementations/vanilla/components/blockquote/_blockquote-print.scss
  src/implementations/vanilla/components/blockquote/_blockquote.scss
  src/implementations/vanilla/components/checkbox/_checkbox.scss
  src/implementations/vanilla/components/content-block/_content-block-print.scss
  src/implementations/vanilla/components/content-block/_content-block.scss
  src/implementations/vanilla/components/content-item/_content-item-print.scss
  src/implementations/vanilla/components/content-item/_content-item.scss
  src/implementations/vanilla/components/description-list/_description-list-print.scss
  src/implementations/vanilla/components/description-list/_description-list.scss
  src/implementations/vanilla/components/fact-figures/_fact-figures.scss
  src/implementations/vanilla/components/fact-figures/fact-figures-print.scss
  src/implementations/vanilla/components/featured-item/_featured-item-print.scss
  src/implementations/vanilla/components/featured-item/_featured-item.scss
  src/implementations/vanilla/components/file-upload/_file-upload.scss
  src/implementations/vanilla/components/file/_file.scss
  src/implementations/vanilla/components/file/file-print.scss
  src/implementations/vanilla/components/form-group/_form-group.scss
  src/implementations/vanilla/components/gallery/_gallery.scss
  src/implementations/vanilla/components/list-illustration/_list-illustration-print.scss
  src/implementations/vanilla/components/list-illustration/_list-illustration.scss
  src/implementations/vanilla/components/media-container/_media-container.scss
  src/implementations/vanilla/components/media-container/media-container-print.scss
  src/implementations/vanilla/components/notification/_notification-print.scss
  src/implementations/vanilla/components/notification/_notification.scss
  src/implementations/vanilla/components/ordered-list/_ordered-list.scss
  src/implementations/vanilla/components/ordered-list/ordered-list-print.scss
  src/implementations/vanilla/components/radio/_radio.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/implementations/vanilla/components/timeline/_timeline-print.scss
  src/implementations/vanilla/components/timeline/_timeline.scss
  src/implementations/vanilla/components/unordered-list/_unordered-list.scss
  src/implementations/vanilla/components/unordered-list/unordered-list-print.scss
  src/implementations/vanilla/utilities/typography/_typography.scss
  src/themes/ec/_custom-properties.scss
  src/themes/ec/_variables.scss
  src/themes/ec/maps/layout.scss
  src/themes/eu/_custom-properties.scss
  src/themes/eu/_variables.scss
  src/themes/eu/maps/layout.scss
Labels: tag: enhancement

#3156 feat(social-icons): Adding Threads icons - FRONT-4191
  .size-limit.json
  src/resources/icons-social-media/src/social-media/threads-color.svg
  src/resources/icons-social-media/src/social-media/threads-negative.svg
  src/resources/icons-social-media/src/social-media/threads.svg
  src/website/src/website-components/Html.jsx
Labels: tag: new feature

#3159 feat(category-filter): ECL4 category-filter - FRONT-4178
  docs/Migrating-v4.md
  src/implementations/twig/components/category-filter/README.md
  src/implementations/twig/components/category-filter/__snapshots__/category-filter.test.js.snap
  src/implementations/twig/components/category-filter/category-filter-items.html.twig
  src/implementations/twig/components/category-filter/category-filter.html.twig
  src/implementations/vanilla/components/category-filter/_category-filter.scss
  src/implementations/vanilla/components/category-filter/category-filter-print.scss
  src/implementations/vanilla/components/category-filter/category-filter.js
  src/specs/components/category-fiter/demo/data.js
  src/themes/ec/_variables.scss
  src/themes/eu/_variables.scss
Labels: tag: enhancement

#3152 feat(description list): use list structure - FRONT-4183
  docs/Migrating-v4.md
  src/implementations/twig/components/card/__snapshots__/card.test.js.snap
  src/implementations/twig/components/content-block/__snapshots__/content-block.test.js.snap
  src/implementations/twig/components/content-item/__snapshots__/content-item.test.js.snap
  src/implementations/twig/components/description-list/__snapshots__/description-list.test.js.snap
  src/implementations/twig/components/description-list/description-list.html.twig
  src/implementations/twig/components/file/__snapshots__/file.test.js.snap
  src/implementations/vanilla/components/description-list/_description-list.scss
  src/implementations/vanilla/components/description-list/description-list.js
Labels: tag: enhancement

#3163 chore(storybook): Hiding notes tab for utilities - v4 - FRONT-4199
  src/implementations/twig/compositions/etrans/README.md
  src/implementations/twig/compositions/file-upload-status/file-upload-status.story.js
  src/implementations/twig/layout/grid/grid.story.js
  src/implementations/twig/layout/stacks/index.story.js
  src/implementations/twig/utilities/background/index.story.js
  src/implementations/twig/utilities/border/index.story.js
  src/implementations/twig/utilities/clearfix/index.story.js
  src/implementations/twig/utilities/dimension/index.story.js
  src/implementations/twig/utilities/disablescroll/index.story.js
  src/implementations/twig/utilities/display/index.story.js
  src/implementations/twig/utilities/float/index.story.js
  src/implementations/twig/utilities/html-tag/index.story.js
  src/implementations/twig/utilities/media/index.story.js
  src/implementations/twig/utilities/print/index.story.js
  src/implementations/twig/utilities/shadow/index.story.js
  src/implementations/twig/utilities/spacing/index.story.js
  src/implementations/twig/utilities/typography/index.story.js
  src/implementations/twig/utilities/z-index/index.story.js
  src/playground/addons/storybook-addon-notes/register.jsx
Labels: tag: internal, process: review needed

#3164 chore(storybook): Hiding notes tab for utilities - v3 - FRONT-4199
  src/implementations/twig/compositions/etrans/README.md
  src/implementations/twig/compositions/file-upload-status/file-upload-status.story.js
  src/implementations/twig/layout/grid/grid.story.js
  src/implementations/twig/layout/stacks/index.story.js
  src/implementations/twig/utilities/background/index.story.js
  src/implementations/twig/utilities/border/index.story.js
  src/implementations/twig/utilities/clearfix/index.story.js
  src/implementations/twig/utilities/dimension/index.story.js
  src/implementations/twig/utilities/disablescroll/index.story.js
  src/implementations/twig/utilities/display/index.story.js
  src/implementations/twig/utilities/float/index.story.js
  src/implementations/twig/utilities/html-tag/index.story.js
  src/implementations/twig/utilities/media/index.story.js
  src/implementations/twig/utilities/print/index.story.js
  src/implementations/twig/utilities/shadow/index.story.js
  src/implementations/twig/utilities/spacing/index.story.js
  src/implementations/twig/utilities/typography/index.story.js
  src/implementations/twig/utilities/z-index/index.story.js
  src/playground/addons/storybook-addon-notes/register.jsx
Labels: tag: internal

#3165 feat(icons): add threads and bluesky icons - FRONT-4200
  .size-limit.json
  src/resources/icons-social-media/src/social-media/bluesky-color.svg
  src/resources/icons-social-media/src/social-media/bluesky-negative.svg
  src/resources/icons-social-media/src/social-media/bluesky.svg
  src/resources/icons-social-media/src/social-media/threads-color.svg
  src/resources/icons-social-media/src/social-media/threads-negative.svg
  src/resources/icons-social-media/src/social-media/threads.svg
Labels: tag: enhancement

#3169 fix(menu): fix issue with menu overflow - FRONT-4166
  src/implementations/vanilla/components/menu/menu.js
Labels: tag: bug fix

#3171 fix(website): Fixing eUI link, v4 - FRONT-4204
  src/website/src/pages/ec/resources/eui/index.md
  src/website/src/pages/eu/resources/eui/index.md
Labels: tag: internal

#3172 fix(website): Fixing eUI link, v3 - FRONT-4204
  src/website/src/pages/ec/resources/eui/index.md
  src/website/src/pages/eu/resources/eui/index.md
Labels: tag: internal

#3176 chore(deps): Updates 15-01-24
  .stylelintrc.js
  package.json
  src/implementations/vanilla/components/banner/banner-print-ec.scss
  src/implementations/vanilla/components/banner/banner-print-eu.scss
  src/implementations/vanilla/components/breadcrumb-core/breadcrumb-core-ec.scss
  src/implementations/vanilla/components/breadcrumb-harmonised/breadcrumb-harmonised-ec.scss
  src/implementations/vanilla/components/breadcrumb-standardised/breadcrumb-standardised-ec.scss
  src/implementations/vanilla/components/breadcrumb/breadcrumb-ec.scss
  src/implementations/vanilla/components/page-header/page-header-ec.scss
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/presets/ec/src/ec-default-print.scss
  src/presets/ec/src/ec-default.scss
  src/presets/eu/src/eu-default-print.scss
  src/presets/eu/src/eu-default.scss
  src/tools/builder/package.json
  src/website/.stylelintrc.js
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3177 chore(deps): Updates 15-01-24 v4
  .stylelintrc.js
  package.json
  src/implementations/vanilla/components/carousel/package.json
  src/implementations/vanilla/layout/grid/grid.scss
  src/implementations/vanilla/layout/grid/mixins/_grid-framework.scss
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/presets/ec/src/ec-default-print.scss
  src/presets/ec/src/ec-default.scss
  src/presets/eu/src/eu-default-print.scss
  src/presets/eu/src/eu-default.scss
  src/tools/builder/package.json
  src/website/.stylelintrc.js
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3180 feat(carousel): improve accessibility - FRONT-4192
  docs/Migrating-v4.md
  src/implementations/twig/components/carousel/README.md
  src/implementations/twig/components/carousel/__snapshots__/carousel.test.js.snap
  src/implementations/twig/components/carousel/carousel.html.twig
  src/implementations/vanilla/components/carousel/_carousel.scss
  src/specs/components/carousel/demo/data.js
Labels: tag: enhancement

#3181 chore(banner): Updating variant docs - FRONT-4207
  src/implementations/twig/components/banner/README.md
  src/implementations/twig/components/banner/banner.html.twig
Labels: tag: documentation

#3183 chore(deps): Green updates - 17-01-24
  package.json
  yarn.lock
Labels: tag: internal

#3184 chore(deps): Updates 17-01-24, v4
  package.json
  yarn.lock
Labels: tag: internal

#3175 feat(featured-item): add footer - FRONT-4196
  docs/Migrating-v4.md
  src/implementations/twig/components/featured-item/README.md
  src/implementations/twig/components/featured-item/__snapshots__/featured-item.test.js.snap
  src/implementations/twig/components/featured-item/featured-item.html.twig
  src/implementations/twig/components/featured-item/featured-item.story.js
  src/implementations/vanilla/components/featured-item/_featured-item-print.scss
  src/implementations/vanilla/components/featured-item/_featured-item.scss
  src/specs/components/featured-item/demo/data--highlight.js
  src/specs/components/featured-item/demo/data.js
Labels: tag: enhancement

#3193 fix(language-selector): cleanup - FRONT-4212
  src/implementations/twig/components/site-header/README.md
  src/implementations/twig/components/site-header/site-header-language-switcher.html.twig
  src/specs/components/site-header/demo/data--ec.js
  src/specs/components/site-header/demo/data--eu.js
Labels: tag: documentation

#3192 feat(EU footer): add social media icons - FRONT-4209
  src/implementations/twig/components/site-footer/__snapshots__/site-footer.test.js.snap
  src/implementations/twig/components/site-footer/site-footer.test.js
  src/specs/components/site-footer/demo/data-harmonised--eu.js
Labels: tag: enhancement

#3196 feat(branding): update color - FRONT-4219
  src/implementations/vanilla/components/featured-item/_featured-item-print.scss
  src/implementations/vanilla/components/featured-item/_featured-item.scss
  src/themes/ec/maps/color.scss
  src/themes/ec/variables/_banner.scss
Labels: tag: enhancement

#3185 feat(EC Usage pages for components): update EC Usage pages for components “ec_site_header”
  src/website/src/pages/ec/components/site-wide/site-header/docs/usage.md
Labels: netlify-cms/pending_publish

#3186 feat(EC Usage pages for components): update EC Usage pages for components “ec_site_footer”
  src/website/src/pages/ec/components/site-wide/site-footer/docs/usage.md
Labels: netlify-cms/pending_publish

#3187 feat(EC Usage pages for components): update EC Usage pages for components “ec_page_header”
  src/website/src/pages/ec/components/site-wide/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#3190 feat(EU Usage pages for components): update EU Usage pages for components “eu_site_footer”
  src/website/src/pages/eu/components/site-wide/site-footer/docs/usage.md
Labels: netlify-cms/pending_publish

#3188 feat(EU Usage pages for components): update EU Usage pages for components “eu_page_header”
  src/website/src/pages/eu/components/site-wide/page-header/docs/usage.md
Labels: netlify-cms/pending_publish

#3200 fix(select): fixing keyboard navigation, fixing buttons generation, fixing moveFocus - FRONT-4225
  src/implementations/vanilla/components/select/select.js
Labels: tag: bug fix

#3201 fix(select): Initialising the _extra_attributes variable before using it - FRONT-4216
  src/implementations/twig/components/select/select.html.twig
Labels: tag: bug fix

#3203 chore(deps): Updates 29-01-24
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3204 chore(deps): Updates 29-01-24
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3197 feat(table): add rowspan and aria-label - FRONT-4222
  docs/Migrating-v4.md
  src/implementations/twig/components/table/README.md
  src/implementations/twig/components/table/__snapshots__/table.test.js.snap
  src/implementations/twig/components/table/table.html.twig
  src/implementations/vanilla/components/table/_table.scss
  src/implementations/vanilla/components/table/table-print.scss
  src/implementations/vanilla/components/table/table.js
  src/specs/components/table/demo/data--multi.js
  src/specs/components/table/demo/data--sort-table.js
Labels: tag: enhancement, process: review needed

#3199 fix(color): fix color contrast issue - FRONT-4224
  src/themes/ec/variables/_fact-figures.scss
  src/themes/ec/variables/_featured-item.scss
Labels: tag: enhancement, process: review needed

#3205 fix(select): not preventing default when using enter or space in a default select - FRONT-4230
  src/implementations/vanilla/components/select/select.js
Labels: tag: bug fix

#3198 feat(list): update example - FRONT-4223
  src/implementations/twig/components/description-list/__snapshots__/description-list.test.js.snap
  src/implementations/twig/components/ordered-list/__snapshots__/ordered-list.test.js.snap
  src/implementations/twig/components/ordered-list/ordered-list.story.js
  src/implementations/twig/components/ordered-list/ordered-list.test.js
  src/implementations/twig/components/unordered-list/__snapshots__/unordered-list.test.js.snap
  src/implementations/twig/components/unordered-list/unordered-list.story.js
  src/implementations/twig/components/unordered-list/unordered-list.test.js
  src/implementations/vanilla/components/description-list/description-list.scss
  src/specs/components/description-list/demo/data--default.js
  src/specs/components/description-list/demo/data--horizontal.js
  src/specs/components/ordered-list/demo/data--unstyled.js
  src/specs/components/unordered-list/demo/data--unstyled.js
  src/website/src/pages/ec/components/list/demo/index.js
  src/website/src/pages/ec/components/list/docs/code.mdx
  src/website/src/pages/eu/components/list/demo/index.js
  src/website/src/pages/eu/components/list/docs/code.mdx
Labels: tag: enhancement

#3179 chore(js): Adding EventManager, defining some custom events - FRONT-4205
  src/implementations/vanilla/components/accordion/accordion.js
  src/implementations/vanilla/components/banner/banner.js
  src/implementations/vanilla/components/expandable/expandable.js
  src/implementations/vanilla/components/inpage-navigation/inpage-navigation.js
  src/implementations/vanilla/components/menu/menu.js
  src/implementations/vanilla/components/select/select.js
  src/implementations/vanilla/components/tabs/tabs.js
  src/tools/event-manager/index.js
  src/tools/event-manager/package.json
  src/website/package.json
  src/website/src/pages/ec/components/forms/select/docs/api.mdx
  src/website/src/pages/eu/components/forms/select/docs/api.mdx
Labels: tag: new feature, process: review needed
