Repository ec-europa/europa-component-library, pull requests merged in 2024-10, with the labels that each got.

#3653 fix(tabs): fix icon position on mobile - FRONT-4321
  src/implementations/vanilla/components/tabs/tabs.scss
Labels: tag: bug fix

#3656 fix(site-header): Removing containers when removing notification - FRONT-4637
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/site-header/site-header.html.twig
  src/implementations/vanilla/components/notification/notification.js
  src/implementations/vanilla/components/site-header/site-header.js
Labels: tag: bug fix, tag: markup changes

#3657 feat(js): Adding version propery to the ECL object - FRONT-4638
  docs/javascript.md
  src/tools/builder/scripts/scripts.js
  src/website/src/pages/ec/getting-started/index.mdx
Labels: tag: enhancement

#3659 chore(deps): Updates 01-10-24
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3654 feat(content-item): set 100% height - FRONT-4627
  src/implementations/vanilla/components/content-item/content-item-print.scss
  src/implementations/vanilla/components/content-item/content-item.scss
Labels: tag: enhancement

#3593 docs(showcase): provide example of full pages - FRONT-4383
  src/implementations/twig/pages/page-home/.npmignore
  src/implementations/twig/pages/page-home/README.md
  src/implementations/twig/pages/page-home/package.json
  src/implementations/twig/pages/page-home/page-home.html.twig
  src/implementations/twig/pages/page-home/page-home.story.js
  src/implementations/twig/pages/page-inner/.npmignore
  src/implementations/twig/pages/page-inner/README.md
  src/implementations/twig/pages/page-inner/package.json
  src/implementations/twig/pages/page-inner/page-inner.html.twig
  src/implementations/twig/pages/page-inner/page-inner.story.js
  src/implementations/twig/pages/page-search/.npmignore
  src/implementations/twig/pages/page-search/README.md
  src/implementations/twig/pages/page-search/package.json
  src/implementations/twig/pages/page-search/page-search.html.twig
  src/implementations/twig/pages/page-search/page-search.story.js
  src/implementations/vanilla/components/file/file.scss
  src/playground/ec/.storybook/environment.js
  src/playground/eu/.storybook/environment.js
  src/specs/pages/page-home/demo/data.js
  src/specs/pages/page-home/package.json
  src/specs/pages/page-inner/demo/data.js
  src/specs/pages/page-inner/package.json
  src/specs/pages/page-search/demo/data.js
  src/specs/pages/page-search/package.json
Labels: tag: internal

#3661 fix(multiselect): Setting margin-top when there is a label and no helper text - FRONT-4640
  src/implementations/vanilla/components/select/select.scss
Labels: tag: bug fix

#3664 chore(deps): Updates - 07-10-24
  .size-limit.json
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3666 fix(content-item): revert height change - FRONT-4645
  src/implementations/vanilla/components/content-item/content-item.scss
Labels: tag: bug fix

#3660 fix(mega-menu): Setting opacity: 1 on the container when opened - FRONT-4641
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/vanilla/components/mega-menu/mega-menu.js
  src/specs/components/mega-menu/demo/data.js
Labels: tag: bug fix, process: review needed

#3670 fix(language-list): Fixing styles - FRONT-4647
  src/implementations/vanilla/components/site-header/_site-header-language-switcher.scss
  src/implementations/vanilla/components/splash-page/splash-page.scss
  src/themes/ec/variables/_language-list.scss
  src/themes/eu/variables/_language-list.scss
Labels: tag: bug fix

#3668 fix(datepicker): Parsing user input, use moment for custom formats, handle resize - FRONT-4643
  .size-limit.json
  src/implementations/vanilla/components/datepicker/datepicker.js
Labels: tag: bug fix

#3674 chore(deps): Updates 14-10-24
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3673 feat(featured-item): Deprecating footer - FRONT-4650
  src/implementations/twig/components/featured-item/README.md
  src/implementations/twig/components/featured-item/featured-item.html.twig
  src/implementations/twig/components/featured-item/featured-item.story.js
  src/website/src/pages/ec/components/media/featured-item/demo/index.js
  src/website/src/pages/eu/components/media/featured-item/demo/index.js
Labels: tag: internal

#3672 feat(featured-item): Fixing RTL display, fixing alignment - FRONT-4652
  src/implementations/vanilla/components/featured-item/featured-item.scss
  src/themes/ec/variables/_featured-item.scss
  src/themes/eu/variables/_featured-item.scss
Labels: tag: enhancement

#3680 feat(mega-menu): Improving calculations for the featured panel height - FRONT-4654
  src/implementations/twig/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/implementations/vanilla/components/mega-menu/mega-menu.js
  src/specs/components/mega-menu/demo/data.js
Labels: tag: enhancement

#3676 feat(EC Usage pages for components): update EC Usage pages for components “ec_radio”
  src/website/src/pages/ec/components/forms/radio/docs/usage.md
Labels: netlify-cms/pending_publish

#3677 feat(EU Usage pages for components): update EU Usage pages for components “eu_radio”
  src/website/src/pages/eu/components/forms/radio/docs/usage.md
Labels: netlify-cms/pending_publish

#3686 feat(link): dynamic underline offset
  src/implementations/vanilla/components/link/link.scss
Labels: tag: enhancement

#3693 chore(deps): Updates - 25-10-24
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3691 feat(language-list): update active state and spacing - FRONT-4661
  .size-limit.json
  src/implementations/vanilla/components/site-header/_site-header-language-switcher.scss
  src/implementations/vanilla/components/splash-page/splash-page-print.scss
  src/implementations/vanilla/components/splash-page/splash-page.scss
  src/themes/ec/variables/_language-list.scss
  src/themes/ec/variables/_site-header.scss
  src/themes/eu/variables/_language-list.scss
Labels: tag: enhancement

#3695 chore(sass): Removing warnings by updating the code
  src/implementations/vanilla/components/datepicker/datepicker.scss
  src/implementations/vanilla/layout/grid/mixins/_breakpoints.scss
  src/themes/ec/variables/_range.scss
Labels: tag: internal

#3692 feat(lists): Another round on unordered and ordered list in EC and EU - FRONT-4656
  src/implementations/vanilla/components/ordered-list/ordered-list.scss
  src/implementations/vanilla/components/unordered-list/unordered-list.scss
  src/themes/ec/variables/_list.scss
  src/themes/eu/variables/_list.scss
Labels: tag: enhancement

#3696 chore(deps): Updates 28-10-24
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3697 feat(featured-item): Styles adapted to support no title use case - FR…
  src/implementations/vanilla/components/featured-item/featured-item.scss
  src/themes/ec/variables/_featured-item.scss
  src/themes/eu/variables/_featured-item.scss
Labels: tag: enhancement

#3687 feat(splash-page): Column display whith a low amout of items, fixing EU styles - FRONT-4662
  src/implementations/twig/components/splash-page/splash-page.html.twig
  src/implementations/vanilla/components/site-header/_site-header-language-switcher.scss
  src/implementations/vanilla/components/splash-page/splash-page.scss
  src/themes/ec/variables/_language-list.scss
  src/themes/eu/variables/_language-list.scss
  src/themes/eu/variables/_splash-page.scss
  src/website/src/pages/ec/components/splash-page/index.md
  src/website/src/pages/eu/components/splash-page/index.md
Labels: tag: enhancement, tag: markup changes

#3694 feat(logos): Adding japanese logo files with correct file name, hiding the others - FRONT-4670
  src/resources/logo-ec/src/negative/logo-ec--ja.svg
  src/resources/logo-ec/src/positive/logo-ec--ja.svg
  src/resources/logo-eu/src/condensed-version/negative/logo-eu--ja.svg
  src/resources/logo-eu/src/condensed-version/positive/logo-eu--ja.svg
  src/resources/logo-eu/src/standard-version/negative/logo-eu--ja.svg
  src/resources/logo-eu/src/standard-version/positive/logo-eu--ja.svg
  src/website/src/website-components/Logo/LogoList.jsx
Labels: tag: bug fix
