Repository ec-europa/europa-component-library, pull requests merged in 2024-02, with the labels that each got.

#3174 feat(splash): One column full width - FRONT-4203
  src/implementations/vanilla/components/splash-page/splash-page.scss
Labels: tag: enhancement

#3207 feat(footer): remove external links - FRONT-4321
  src/implementations/twig/components/site-footer/__snapshots__/site-footer.test.js.snap
  src/specs/components/site-footer/demo/data-core--ec.js
  src/specs/components/site-footer/demo/data-harmonised--ec.js
  src/specs/components/site-footer/demo/data-standardised--ec.js
Labels: tag: enhancement

#3194 feat(tabs): fix accessibility issues - FRONT-4214
  docs/Migrating-v4.md
  src/implementations/twig/components/tabs/README.md
  src/implementations/twig/components/tabs/__snapshots__/tabs.test.js.snap
  src/implementations/twig/components/tabs/tabs.html.twig
  src/implementations/twig/components/tabs/tabs.test.js
  src/implementations/vanilla/components/tabs/package.json
  src/implementations/vanilla/components/tabs/tabs.js
  src/implementations/vanilla/components/tabs/tabs.scss
  src/presets/rtl/src/rtl.scss
Labels: tag: enhancement, process: review needed

#3202 feat(icons): Updating some icons in EC set - FRONT-4152
  .size-limit.json
  src/implementations/twig/components/icon/__snapshots__/icon.test.js.snap
  src/resources/icons-ec/src/all/audio.svg
  src/resources/icons-ec/src/all/back.svg
  src/resources/icons-ec/src/all/basket.svg
  src/resources/icons-ec/src/all/close-filled.svg
  src/resources/icons-ec/src/all/edit.svg
  src/resources/icons-ec/src/all/email.svg
  src/resources/icons-ec/src/all/euro.svg
  src/resources/icons-ec/src/all/faq.svg
  src/resources/icons-ec/src/all/feedback.svg
  src/resources/icons-ec/src/all/gear.svg
  src/resources/icons-ec/src/all/image.svg
  src/resources/icons-ec/src/all/laco-filled.svg
  src/resources/icons-ec/src/all/laco.svg
  src/resources/icons-ec/src/all/livestreaming.svg
  src/resources/icons-ec/src/all/multiple-files.svg
  src/resources/icons-ec/src/all/play-filled.svg
  src/resources/icons-ec/src/all/play-outline.svg
  src/resources/icons-ec/src/all/play.svg
  src/resources/icons-ec/src/all/print.svg
  src/resources/icons-ec/src/all/tag.svg
  src/resources/icons-eu/src/all/play-outline.svg
  src/resources/icons-eu/src/all/play.svg
Labels: tag: enhancement, process: review needed

#3212 fix(website): Fixing playground link in date block index - FRONT-4239
  src/website/src/pages/ec/components/date-block/index.md
  src/website/src/pages/eu/components/date-block/index.md
Labels: tag: bug fix, process: review needed

#3160 feat(naming): use "inverted" instead of "negative" - FRONT-4193
  docs/Migrating-v4.md
  src/implementations/twig/components/breadcrumb/README.md
  src/implementations/twig/components/breadcrumb/breadcrumb.html.twig
  src/implementations/twig/components/page-header/page-header.html.twig
  src/implementations/twig/components/spinner/README.md
  src/implementations/twig/components/spinner/__snapshots__/spinner.test.js.snap
  src/implementations/twig/components/spinner/spinner.html.twig
  src/implementations/twig/components/spinner/spinner.story.js
  src/implementations/twig/components/spinner/spinner.test.js
  src/implementations/twig/utilities/background/index.story.js
  src/implementations/vanilla/components/spinner/spinner.scss
  src/website/src/pages/ec/components/loading-indicator/demo/index.js
  src/website/src/pages/ec/components/loading-indicator/docs/code.mdx
  src/website/src/pages/eu/components/loading-indicator/demo/index.js
  src/website/src/pages/eu/components/loading-indicator/docs/code.mdx
Labels: tag: enhancement

#3214 chore(deps): v3 updates 05-02-24
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  yarn.lock
Labels: tag: internal

#3215 chore(deps): Updates 05-2-24 - v4
  .eslintrc.js
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/bin/build.js
  src/tools/builder/package.json
  src/website/.eslintrc.js
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3211 fix(menu): Enabling external icon for first level menu items - FRONT-4238
  src/implementations/twig/components/menu/README.md
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/menu-item.html.twig
  src/implementations/twig/components/menu/menu.html.twig
  src/implementations/twig/components/menu/menu.test.js
  src/implementations/vanilla/components/menu/menu.scss
Labels: tag: bug fix

#3216 fix(icons): Fixing three icons in the default set for EC - FRONT-4243
  src/resources/icons-ec/src/all/error.svg
  src/resources/icons-ec/src/all/information.svg
  src/resources/icons-ec/src/all/warning.svg
Labels: tag: bug fix

#3220 chore(apis): Using relative path to reach the html page to be included
  src/website/src/pages/ec/components/accordion/docs/api.mdx
  src/website/src/pages/ec/components/banner/docs/api.mdx
  src/website/src/pages/ec/components/carousel/docs/api.mdx
  src/website/src/pages/ec/components/category-filter/docs/api.mdx
  src/website/src/pages/ec/components/expandable/docs/api.mdx
  src/website/src/pages/ec/components/file/docs/api.mdx
  src/website/src/pages/ec/components/forms/datepicker/docs/api.mdx
  src/website/src/pages/ec/components/forms/file-upload/docs/api.mdx
  src/website/src/pages/ec/components/forms/range/docs/api.mdx
  src/website/src/pages/ec/components/forms/select/docs/api.mdx
  src/website/src/pages/ec/components/list/docs/api.mdx
  src/website/src/pages/ec/components/media/gallery/docs/api.mdx
  src/website/src/pages/ec/components/modal/docs/api.mdx
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/api.mdx
  src/website/src/pages/ec/components/navigation/inpage-navigation/docs/api.mdx
  src/website/src/pages/ec/components/navigation/menu/docs/api.mdx
  src/website/src/pages/ec/components/navigation/tabs/docs/api.mdx
  src/website/src/pages/ec/components/news-ticker/docs/api.mdx
  src/website/src/pages/ec/components/notification/docs/api.mdx
  src/website/src/pages/ec/components/popover/docs/api.mdx
  src/website/src/pages/ec/components/site-wide/site-header/docs/api.mdx
  src/website/src/pages/ec/components/table/docs/api.mdx
  src/website/src/pages/ec/components/timeline/docs/api.mdx
  src/website/src/pages/eu/components/accordion/docs/api.mdx
  src/website/src/pages/eu/components/banner/docs/api.mdx
  src/website/src/pages/eu/components/carousel/docs/api.mdx
  src/website/src/pages/eu/components/category-filter/docs/api.mdx
  src/website/src/pages/eu/components/expandable/docs/api.mdx
  src/website/src/pages/eu/components/file/docs/api.mdx
  src/website/src/pages/eu/components/forms/datepicker/docs/api.mdx
  src/website/src/pages/eu/components/forms/file-upload/docs/api.mdx
  src/website/src/pages/eu/components/forms/range/docs/api.mdx
  src/website/src/pages/eu/components/forms/select/docs/api.mdx
  src/website/src/pages/eu/components/list/docs/api.mdx
  src/website/src/pages/eu/components/media/gallery/docs/api.mdx
  src/website/src/pages/eu/components/modal/docs/api.mdx
  src/website/src/pages/eu/components/navigation/breadcrumb/docs/api.mdx
  src/website/src/pages/eu/components/navigation/inpage-navigation/docs/api.mdx
  src/website/src/pages/eu/components/navigation/menu/docs/api.mdx
  src/website/src/pages/eu/components/navigation/tabs/docs/api.mdx
  src/website/src/pages/eu/components/news-ticker/docs/api.mdx
  src/website/src/pages/eu/components/notification/docs/api.mdx
  src/website/src/pages/eu/components/popover/docs/api.mdx
  src/website/src/pages/eu/components/site-wide/site-header/docs/api.mdx
  src/website/src/pages/eu/components/table/docs/api.mdx
  src/website/src/pages/eu/components/timeline/docs/api.mdx
Labels: tag: bug fix

#3219 fix(select): fix multi select width - FRONT-4244
  src/implementations/vanilla/components/select/select.scss
Labels: tag: bug fix

#3225 fix(apis): fixing code highlight and paths to the apis for nested components - FRONT-4248
  src/website/src/components/DocPage/DocPage.jsx
  src/website/src/pages/ec/components/forms/datepicker/docs/api.mdx
  src/website/src/pages/ec/components/forms/file-upload/docs/api.mdx
  src/website/src/pages/ec/components/forms/range/docs/api.mdx
  src/website/src/pages/ec/components/forms/select/docs/api.mdx
  src/website/src/pages/ec/components/media/gallery/docs/api.mdx
  src/website/src/pages/ec/components/navigation/breadcrumb/docs/api.mdx
  src/website/src/pages/ec/components/navigation/inpage-navigation/docs/api.mdx
  src/website/src/pages/ec/components/navigation/menu/docs/api.mdx
  src/website/src/pages/ec/components/navigation/tabs/docs/api.mdx
  src/website/src/pages/ec/components/site-wide/site-header/docs/api.mdx
  src/website/src/pages/eu/components/expandable/docs/api.mdx
  src/website/src/pages/eu/components/forms/datepicker/docs/api.mdx
  src/website/src/pages/eu/components/forms/file-upload/docs/api.mdx
  src/website/src/pages/eu/components/forms/range/docs/api.mdx
  src/website/src/pages/eu/components/forms/select/docs/api.mdx
  src/website/src/pages/eu/components/media/gallery/docs/api.mdx
  src/website/src/pages/eu/components/navigation/breadcrumb/docs/api.mdx
  src/website/src/pages/eu/components/navigation/inpage-navigation/docs/api.mdx
  src/website/src/pages/eu/components/navigation/menu/docs/api.mdx
  src/website/src/pages/eu/components/navigation/tabs/docs/api.mdx
  src/website/src/pages/eu/components/notification/docs/api.mdx
  src/website/src/pages/eu/components/site-wide/site-header/docs/api.mdx
Labels: tag: bug fix

#3222 fix(page-titles): Fixing page titles in the website - FRONT-4246
  src/website/src/App.jsx
  src/website/src/pages/ec/components/forms/file-upload/docs/usage.md
  src/website/src/pages/eu/components/forms/file-upload/docs/usage.md
Labels: tag: bug fix

#3227 fix(notification): Colouring the exclamation mark in the warning icon in EC - FRONT-4249
  src/implementations/twig/components/notification/__snapshots__/notification.test.js.snap
  src/implementations/twig/components/notification/notification.html.twig
  src/implementations/twig/compositions/etrans/__snapshots__/etrans.test.js.snap
  src/implementations/vanilla/components/notification/notification.scss
  src/themes/ec/variables/_notification.scss
  src/themes/eu/variables/_notification.scss
Labels: tag: enhancement, process: review needed

#3210 feat(menu): dark variant and mobile display update - FRONT-4236
  docs/Migrating-v4.md
  src/implementations/twig/components/menu/README.md
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/ec-menu.story.js
  src/implementations/twig/components/menu/eu-menu.story.js
  src/implementations/twig/components/menu/menu.html.twig
  src/implementations/twig/components/menu/menu.test.js
  src/implementations/twig/components/site-header/README.md
  src/implementations/twig/components/site-header/ec-site-header.story.js
  src/implementations/twig/components/site-header/site-header.html.twig
  src/implementations/vanilla/components/menu/menu.js
  src/implementations/vanilla/components/menu/menu.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/presets/rtl/src/rtl.scss
  src/specs/components/menu/demo/data--eu-long.js
  src/specs/components/menu/demo/data--eu.js
  src/themes/ec/_custom-properties.scss
  src/themes/ec/variables/_menu.scss
  src/themes/ec/variables/_site-header.scss
  src/themes/eu/_custom-properties.scss
  src/themes/eu/variables/_menu.scss
  src/website/src/pages/ec/components/navigation/menu/docs/code.mdx
Labels: tag: new feature

#3229 fix(banner): remove extra margin - FRONT-4524
  src/implementations/vanilla/components/banner/banner.scss
Labels: tag: enhancement

#3226 feat(social-media-follow): add monochrome icons - FRONT-4250
  docs/Migrating-v4.md
  src/implementations/twig/components/social-media-follow/__snapshots__/social-media-follow.test.js.snap
  src/implementations/twig/components/social-media-follow/social-media-follow.story.js
  src/implementations/twig/components/social-media-follow/social-media-follow.test.js
  src/implementations/vanilla/components/social-media-follow/social-media-follow.scss
  src/specs/components/social-media-follow/demo/data--color.js
  src/specs/components/social-media-follow/demo/data--monochrome.js
  src/website/src/pages/ec/components/social-media-follow/demo/index.js
  src/website/src/pages/ec/components/social-media-follow/docs/code.mdx
  src/website/src/pages/eu/components/social-media-follow/demo/index.js
  src/website/src/pages/eu/components/social-media-follow/docs/code.mdx
Labels: tag: enhancement

#3236 chore(deps): Updates 14-02-24
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3238 fix(timeline): fixing styles for border and toggle aligment - FRONT-4264
  src/implementations/vanilla/components/timeline/timeline.scss
  src/themes/ec/variables/_timeline.scss
Labels: tag: bug fix, process: review needed

#3239 chore(deps): Updates 14-02-24 v3
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3240 feat(menu): use dark as default - FRONT-4236
  src/implementations/twig/components/menu/README.md
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/ec-menu.story.js
  src/implementations/twig/components/menu/menu.html.twig
  src/implementations/twig/components/menu/menu.test.js
  src/implementations/twig/components/site-header/ec-site-header.story.js
  src/implementations/vanilla/components/menu/menu.scss
  src/themes/ec/variables/_menu.scss
  src/website/src/pages/ec/components/navigation/menu/docs/code.mdx
Labels: tag: enhancement

#3234 fix(icons): using the newly introduced play-outline icon - FRONT-4255
  src/implementations/twig/components/carousel/__snapshots__/carousel.test.js.snap
  src/implementations/twig/components/carousel/carousel.html.twig
  src/implementations/twig/components/news-ticker/__snapshots__/news-ticker.test.js.snap
  src/implementations/twig/components/news-ticker/news-ticker.html.twig
Labels: tag: bug fix

#3241 feat(icons): Renaming basket, gear and back icons - FRONT-4266
  docs/Migrating-v4.md
  src/implementations/twig/components/icon/__snapshots__/icon.test.js.snap
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/menu-item.html.twig
  src/resources/icons-ec/src/all/arrow-left.svg
  src/resources/icons-ec/src/all/settings.svg
  src/resources/icons-ec/src/all/shopping-bag.svg
  src/resources/icons-eu/src/all/arrow-left.svg
  src/resources/icons-eu/src/all/settings.svg
  src/resources/icons-eu/src/all/shopping-bag.svg
  src/website/public/settings.svg
  src/website/scripts/docs.js
Labels: tag: enhancement

#3232 feat(menu): add dynamic label - FRONT-4251
  src/implementations/twig/components/menu/__snapshots__/menu.test.js.snap
  src/implementations/twig/components/menu/menu.html.twig
  src/implementations/vanilla/components/menu/menu.js
Labels: tag: enhancement

#3243 fix(clickable-images): Limiting the number of iterations, adding card expection - FRONT-4267
  src/implementations/vanilla/components/content-block/content-block.js
Labels: tag: bug fix, process: review needed

#3237 feat(news-ticker): add text for external icon - FRONT-4258
  docs/Migrating-v4.md
  src/implementations/twig/components/link/link.html.twig
  src/implementations/twig/components/link/link.test.js
  src/implementations/twig/components/news-ticker/README.md
  src/implementations/twig/components/news-ticker/__snapshots__/news-ticker.test.js.snap
  src/implementations/twig/components/news-ticker/news-ticker.html.twig
  src/implementations/vanilla/components/news-ticker/news-ticker.scss
  src/specs/components/news-ticker/demo/data.js
Labels: tag: enhancement, process: review needed

#3245 feat(notification): Updating styles - FRONT-4270
  src/implementations/vanilla/components/notification/notification.scss
  src/themes/ec/variables/_notification.scss
  src/themes/eu/variables/_notification.scss
Labels: tag: enhancement

#3231 feat(tag): fix accessibility text - FRONT-4261
  src/implementations/twig/components/tag/__snapshots__/tag.test.js.snap
  src/implementations/twig/components/tag/tag.html.twig
Labels: tag: bug fix, process: review needed

#3242 feat(notification): add screen reader label - FRONT-4257
  docs/Migrating-v4.md
  src/implementations/twig/components/notification/README.md
  src/implementations/twig/components/notification/__snapshots__/notification.test.js.snap
  src/implementations/twig/components/notification/notification.html.twig
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/compositions/etrans/__snapshots__/etrans.test.js.snap
  src/specs/components/notification/demo/data--error-ec.js
  src/specs/components/notification/demo/data--error-eu.js
  src/specs/components/notification/demo/data--info-ec.js
  src/specs/components/notification/demo/data--info-eu.js
  src/specs/components/notification/demo/data--success-ec.js
  src/specs/components/notification/demo/data--success-eu.js
  src/specs/components/notification/demo/data--warning-ec.js
  src/specs/components/notification/demo/data--warning-eu.js
Labels: tag: enhancement

#3248 chore(deps): Updates 20-02-24
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3249 feat(icons): Adding camera icon - FRONT-4272
  src/implementations/twig/components/icon/__snapshots__/icon.test.js.snap
  src/resources/icons-ec/src/all/camera.svg
  src/resources/icons-eu/src/all/camera.svg
Labels: tag: new feature, process: business approval needed

#3254 feat(icons): Updating three icons in EU - FRONT-4275
  src/resources/icons-eu/src/all/document.svg
  src/resources/icons-eu/src/all/email.svg
  src/resources/icons-eu/src/all/folder.svg
Labels: tag: enhancement

#3161 feat(popover): Four directions, scroll and resize detection - FRONT-4159
  .size-limit.json
  src/implementations/twig/components/popover/README.md
  src/implementations/twig/components/popover/__snapshots__/popover.test.js.snap
  src/implementations/twig/components/popover/popover.html.twig
  src/implementations/twig/components/popover/popover.story.js
  src/implementations/twig/components/social-media-share/__snapshots__/social-media-share.test.js.snap
  src/implementations/vanilla/components/popover/popover.js
  src/implementations/vanilla/components/popover/popover.scss
  src/implementations/vanilla/components/social-media-share/social-media-share.scss
  src/presets/rtl/src/rtl.scss
  src/specs/components/popover/demo/data.js
  src/specs/components/social-media-share/demo/data.js
Labels: tag: enhancement

#3256 feat(multi-select): fix disabled cursor - FRONT-4278
  src/implementations/vanilla/components/select/select.js
Labels: tag: bug fix

#3258 feat(featured-item): Setting white background in EC and EU - FRONT-4280
  src/implementations/vanilla/components/featured-item/featured-item.scss
Labels: tag: enhancement

#3259 feat(page-header): Adding wrapper to better handling the spacing - FRONT-4284
  src/implementations/twig/components/page-header/__snapshots__/page-header.test.js.snap
  src/implementations/twig/components/page-header/page-header.html.twig
  src/implementations/twig/components/page-header/page-header.test.js
  src/implementations/vanilla/components/page-header/page-header-ec.scss
  src/website/src/pages/ec/components/site-wide/page-header/index.md
  src/website/src/pages/eu/components/site-wide/page-header/index.md
Labels: tag: enhancement

#3260 feat(list): Changing dash in unordered list - FRONT-4285
  src/themes/ec/variables/_list.scss
Labels: tag: enhancement
