Repository ec-europa/europa-component-library, pull requests merged in 2025-09, with the labels that each got.

#4110 feat(tokens): update status tokens - FRONT-5034
  src/themes/ec/_custom-properties.scss
  src/themes/ec/maps/color.scss
Labels: tag: enhancement

#4112 fix(site-header): fix menu button overlap - FRONT-5044
  src/components/site-header/site-header-ec.scss
Labels: tag: bug fix

#4116 chore(deps): Updates 08-09-25
  .github/workflows/ci.yml
  .github/workflows/production.yml
  .nvmrc
  README.md
  docs/developers-start-here.md
  package.json
  pnpm-lock.yaml
  src/components/blockquote/__snapshots__/blockquote.test.js.snap
  src/components/date-block/__snapshots__/date-block.test.js.snap
  src/components/label/__snapshots__/label.test.js.snap
  src/components/mega-menu/package.json
  src/components/menu/package.json
  src/components/ordered-list/__snapshots__/ordered-list.test.js.snap
  src/components/picture/__snapshots__/picture.test.js.snap
  src/components/range/__snapshots__/range.test.js.snap
  src/components/separator/__snapshots__/separator.test.js.snap
  src/components/skip-link/__snapshots__/skip-link.test.js.snap
  src/components/spinner/__snapshots__/spinner.test.js.snap
  src/components/splash-page/__snapshots__/splash-page.test.js.snap
  src/components/table/__snapshots__/table.test.js.snap
  src/components/text-area/__snapshots__/text-area.test.js.snap
  src/components/text-input/__snapshots__/text-input.test.js.snap
  src/components/unordered-list/__snapshots__/unordered-list.test.js.snap
  src/components/video/__snapshots__/video.test.js.snap
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
Labels: tag: internal

#4109 fix(timeline): fix label only display - FRONT-5037
  src/components/timeline/__snapshots__/timeline.test.js.snap
  src/components/timeline/demo/data--set.js
  src/components/timeline/timeline-print.scss
  src/components/timeline/timeline.js
  src/components/timeline/timeline.scss
Labels: tag: bug fix

#4118 chore(scss): Refactoring form width mixin and its usage - FRONT-5035
  src/components/datepicker/datepicker.scss
  src/components/form-group/mixins.scss
  src/components/range/range.scss
  src/components/select/select.scss
  src/components/text-area/text-area.scss
  src/components/text-input/text-input.scss
  src/layout/form/mixins.scss
Labels: tag: internal

#4119 feat(token): update border token - FRONT-5063
  src/themes/ec/_custom-properties.scss
  src/themes/ec/variables/_select.scss
Labels: tag: enhancement

#4123 feat(video): update demo video - FRONT-5051
  src/components/banner/__snapshots__/banner.test.js.snap
  src/components/banner/demo/data--video.js
  src/components/carousel/__snapshots__/carousel.test.js.snap
  src/components/carousel/demo/data.js
  src/components/media-container/__snapshots__/media-container.test.js.snap
  src/components/media-container/demo/data--video.js
Labels: tag: internal

#4124 feat(list-illustration): Adding icon-list and number-list variants - FRONT-5062
  .size-limit.json
  docs/Migrating-v5.md
  pnpm-lock.yaml
  src/components/list-illustration/README.md
  src/components/list-illustration/__snapshots__/list-illustration.test.js.snap
  src/components/list-illustration/demo/data--icon-list.js
  src/components/list-illustration/demo/data--number-list.js
  src/components/list-illustration/list-illustration-item.html.twig
  src/components/list-illustration/list-illustration-print.scss
  src/components/list-illustration/list-illustration.html.twig
  src/components/list-illustration/list-illustration.scss
  src/components/list-illustration/list-illustration.story.js
  src/components/list-illustration/list-illustration.test.js
  src/components/list-illustration/package.json
  src/themes/ec/variables/_list-illustration.scss
  src/themes/ec/variables/_typography.scss
  src/themes/eu/variables/_list-illustration.scss
  src/website/src/pages/ec/components/list-illustration/docs/code.mdx
  src/website/src/pages/eu/components/list-illustration/docs/code.mdx
Labels: tag: new feature

#4132 feat(banner): add aria-describedby on button - FRONT-5071
  src/components/banner/README.md
  src/components/banner/__snapshots__/banner.test.js.snap
  src/components/banner/banner.html.twig
  src/components/banner/demo/data--image.js
  src/components/banner/demo/data--video.js
  src/components/carousel/__snapshots__/carousel.test.js.snap
  src/components/carousel/demo/data.js
Labels: tag: enhancement
