Repository ec-europa/europa-component-library, pull requests merged in 2025-04, with the labels that each got.

#3924 fix(banner): fix aspect for small banner - FRONT-4857
  src/components/banner/banner.scss
Labels: tag: bug fix

#3916 feat(color): update component A-C - FRONT-4844
  src/components/accordion/README.md
  src/components/accordion/accordion.html.twig
  src/components/accordion/accordion.scss
  src/components/accordion/accordion.story.js
  src/components/banner/banner-print.scss
  src/components/checkbox/checkbox.scss
  src/components/content-block/content-block-print.scss
  src/components/content-block/content-block.scss
  src/themes/ec/variables/_accordion.scss
  src/themes/ec/variables/_banner.scss
  src/themes/ec/variables/_breadcrumb.scss
  src/themes/ec/variables/_checkbox.scss
Labels: tag: enhancement

#3918 feat(header): Added custom-action V4. - FRONT-4819
  .size-limit.json
  src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
  src/implementations/twig/components/site-header/ec-site-header.story.js
  src/implementations/twig/components/site-header/eu-site-header.story.js
  src/implementations/twig/components/site-header/site-header.html.twig
  src/implementations/vanilla/components/site-header/_site-header-dropdown.scss
  src/implementations/vanilla/components/site-header/site-header-ec.scss
  src/implementations/vanilla/components/site-header/site-header-eu.scss
  src/implementations/vanilla/components/site-header/site-header.js
  src/specs/components/site-header/demo/data--ec.js
  src/specs/components/site-header/demo/data--eu.js
  yarn.lock
Labels: tag: new feature

#3904 feat(site-header): Custom action. - FRONT-4819
  src/components/site-header/README.md
  src/components/site-header/__snapshots__/site-header.test.js.snap
  src/components/site-header/_site-header-dropdown.scss
  src/components/site-header/demo/data--ec.js
  src/components/site-header/demo/data--eu.js
  src/components/site-header/ec-site-header.story.js
  src/components/site-header/eu-site-header.story.js
  src/components/site-header/site-header-ec.scss
  src/components/site-header/site-header-eu.scss
  src/components/site-header/site-header.html.twig
  src/components/site-header/site-header.js
Labels: tag: new feature

#3923 feat(color): update component G-M - FRONT-4846
  src/components/category-filter/README.md
  src/components/category-filter/category-filter.html.twig
  src/components/category-filter/category-filter.scss
  src/components/category-filter/category-filter.story.js
  src/components/gallery/gallery-print.scss
  src/components/gallery/gallery.scss
  src/components/icon/icon.scss
  src/components/indicator/indicator.scss
  src/components/inpage-navigation/README.md
  src/components/inpage-navigation/inpage-navigation.html.twig
  src/components/inpage-navigation/inpage-navigation.scss
  src/components/inpage-navigation/inpage-navigation.story.js
  src/components/list-illustration/README.md
  src/components/list-illustration/list-illustration.html.twig
  src/components/list-illustration/list-illustration.story.js
  src/components/media-container/media-container-print.scss
  src/components/media-container/media-container.scss
  src/components/mega-menu/mega-menu.scss
  src/components/menu/menu.scss
  src/components/modal/modal.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/src/eu.scss
  src/themes/ec/_variables.scss
  src/themes/ec/variables/_category-filter.scss
  src/themes/ec/variables/_gallery.scss
  src/themes/ec/variables/_icon.scss
  src/themes/ec/variables/_inpage-navigation.scss
  src/themes/ec/variables/_label.scss
  src/themes/ec/variables/_link.scss
  src/themes/ec/variables/_list-illustration.scss
  src/themes/ec/variables/_mega-menu.scss
  src/themes/ec/variables/_menu.scss
  src/themes/ec/variables/_modal.scss
  src/themes/ec/variables/_typography.scss
  src/themes/eu/_variables.scss
  src/themes/eu/variables/_icon.scss
  src/themes/eu/variables/_mega-menu.scss
  src/themes/eu/variables/_menu.scss
Labels: tag: enhancement

#3907 feat(mega-menu): Featured links, revisited - FRONT-4842
  docs/Migrating-v5.md
  pnpm-lock.yaml
  src/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/components/mega-menu/demo/data.js
  src/components/mega-menu/mega-menu-featured-item.html.twig
  src/components/mega-menu/mega-menu-item.html.twig
  src/components/mega-menu/mega-menu.js
  src/components/mega-menu/mega-menu.scss
  src/components/mega-menu/package.json
Labels: tag: enhancement

#3930 chore(deps): Updates - v4 - 02-04-25
  package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3913 feat(grid): Different columns gutter based on breakpoints - FRONT-4849
  src/components/banner/banner-print.scss
  src/components/banner/banner.scss
  src/components/mega-menu/mega-menu.scss
  src/components/navigation-list/navigation-list-print.scss
  src/components/navigation-list/navigation-list.scss
  src/layout/grid/mixins/_grid.scss
  src/themes/ec/maps/layout.scss
  src/themes/ec/theme.scss
  src/themes/ec/variables/_banner.scss
  src/themes/ec/variables/_mega-menu.scss
  src/themes/ec/variables/_site-footer.scss
  src/themes/eu/maps/layout.scss
  src/themes/eu/theme.scss
  src/themes/eu/variables/_banner.scss
  src/themes/eu/variables/_mega-menu.scss
Labels: tag: enhancement

#3921 feat(site-header): Style updates - FRONT-4854
  src/components/site-header/__snapshots__/site-header.test.js.snap
  src/components/site-header/demo/data--ec.js
  src/components/site-header/ec-site-header.story.js
  src/components/site-header/site-header-ec.scss
  src/components/site-header/site-header.html.twig
  src/themes/ec/variables/_site-header.scss
Labels: tag: enhancement

#3926 feat(site-header): site name on mobile only - FRONT-4856
  docs/Migrating-v5.md
  src/components/site-header/README.md
  src/components/site-header/__snapshots__/site-header.test.js.snap
  src/components/site-header/demo/data--eu.js
  src/components/site-header/ec-site-header.story.js
  src/components/site-header/eu-site-header.story.js
  src/components/site-header/site-header-ec.scss
  src/components/site-header/site-header-eu.scss
  src/components/site-header/site-header.html.twig
Labels: tag: enhancement

#3925 feat(social-media): Removed social-media-share and color variants from social media follow. - FRONT-4853
  pnpm-lock.yaml
  src/components/social-media-follow/README.md
  src/components/social-media-follow/__snapshots__/social-media-follow.test.js.snap
  src/components/social-media-follow/demo/data--color.js
  src/components/social-media-follow/social-media-follow.story.js
  src/components/social-media-follow/social-media-follow.test.js
  src/components/social-media-share/.npmignore
  src/components/social-media-share/README.md
  src/components/social-media-share/__snapshots__/social-media-share.test.js.snap
  src/components/social-media-share/demo/data.js
  src/components/social-media-share/package.json
  src/components/social-media-share/social-media-share-print.scss
  src/components/social-media-share/social-media-share.html.twig
  src/components/social-media-share/social-media-share.scss
  src/components/social-media-share/social-media-share.story.js
  src/components/social-media-share/social-media-share.test.js
  src/presets/ec/package.json
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec.scss
  src/presets/eu/package.json
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu.scss
  src/themes/ec/_variables.scss
  src/themes/ec/variables/_social-media-follow.scss
  src/themes/ec/variables/_social-media-share.scss
  src/themes/eu/_variables.scss
  src/themes/eu/variables/_social-media-share.scss
  src/twig-templates/package.json
  src/website/package.json
  src/website/public/admin/config.yml
  src/website/src/pages/ec/components/index.mdx
  src/website/src/pages/ec/components/social-media-follow/demo/index.js
  src/website/src/pages/ec/components/social-media-follow/docs/code.mdx
  src/website/src/pages/ec/components/social-media-share/demo/index.js
  src/website/src/pages/ec/components/social-media-share/docs/code.mdx
  src/website/src/pages/ec/components/social-media-share/docs/usage.md
  src/website/src/pages/ec/components/social-media-share/ec_comp_social_media_share.svg
  src/website/src/pages/ec/components/social-media-share/index.md
  src/website/src/pages/eu/components/index.mdx
  src/website/src/pages/eu/components/social-media-follow/demo/index.js
  src/website/src/pages/eu/components/social-media-follow/docs/code.mdx
  src/website/src/pages/eu/components/social-media-share/demo/index.js
  src/website/src/pages/eu/components/social-media-share/docs/code.mdx
  src/website/src/pages/eu/components/social-media-share/docs/usage.md
  src/website/src/pages/eu/components/social-media-share/eu_comp_social_media_share.svg
  src/website/src/pages/eu/components/social-media-share/index.md
Labels: tag: enhancement

#3932 feat(color): remove old EC color, small fixes - FRONT-4830
  src/components/accordion/accordion.scss
  src/components/card/card.scss
  src/components/checkbox/checkbox.scss
  src/components/datepicker/datepicker.scss
  src/components/file/file-print.scss
  src/components/file/file.scss
  src/components/icon/icon-print.scss
  src/components/media-container/media-container.scss
  src/components/navigation-list/navigation-list.scss
  src/components/news-ticker/news-ticker.scss
  src/components/page-header/page-header-ec.scss
  src/components/page-header/page-header-print-ec.scss
  src/components/popover/popover.scss
  src/components/range/range.scss
  src/components/select/select.scss
  src/components/spinner/spinner.scss
  src/components/table/table-print.scss
  src/components/table/table.scss
  src/components/tag/tag-print.scss
  src/components/text-area/text-area.scss
  src/components/timeline/timeline-print.scss
  src/themes/ec/_custom-properties.scss
  src/themes/ec/maps/color.scss
  src/themes/ec/theme.scss
  src/themes/ec/variables/_accordion.scss
  src/themes/ec/variables/_checkbox.scss
  src/themes/ec/variables/_featured-item.scss
  src/themes/ec/variables/_file.scss
  src/themes/ec/variables/_news-ticker.scss
  src/themes/ec/variables/_notification.scss
  src/themes/ec/variables/_radio.scss
  src/themes/ec/variables/_range.scss
  src/themes/ec/variables/_rating-field.scss
  src/themes/eu/variables/_accordion.scss
  src/themes/eu/variables/_range.scss
  src/utilities/border/border.scss
  src/website/src/components/DocPage/Header.scss
  src/website/src/components/Navigation/Navigation.scss
  src/website/src/styles/_custom-properties.scss
  src/website/src/styles/markdown.scss
  src/website/src/website-components/Anatomy/Anatomy.scss
  src/website/src/website-components/Icon/IconCard.scss
  src/website/src/website-components/Link/Link.scss
  src/website/src/website-components/Logo/LogoCard.scss
  src/website/src/website-components/Playground.scss
  src/website/src/website-components/Spacing/Spacing.scss
  src/website/src/website-components/Thumbnail/Thumbnail.scss
Labels: tag: enhancement

#3934 feat(mega-menu): Extra attributes for the info link - FRONT-4862
  src/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/components/mega-menu/mega-menu-item.html.twig
  src/components/mega-menu/mega-menu.test.js
Labels: tag: enhancement

#3937 chore(deps): Updates - 07-04-25
  package.json
  pnpm-lock.yaml
  src/components/gallery/gallery-print.scss
  src/components/inpage-navigation/inpage-navigation.scss
  src/components/mega-menu/mega-menu.scss
  src/components/page-header/page-header-ec.scss
  src/components/site-header/_site-header-dropdown.scss
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/themes/eu/variables/_banner.scss
  src/themes/eu/variables/_menu.scss
  src/themes/eu/variables/_site-header.scss
  src/tools/builder/package.json
  src/website/package.json
  src/website/src/website-components/Color/PaletteItem.scss
Labels: tag: internal

#3936 feat(featured-item): Removed description margin first-child. - FRONT-4860
  src/implementations/vanilla/components/featured-item/featured-item.scss
  src/themes/ec/variables/_featured-item.scss
  src/themes/eu/variables/_featured-item.scss
Labels: tag: bug fix

#3942 chore(deps): Fixing audit report - v4
  package.json
  yarn.lock
Labels: tag: internal

#3914 feat(spacing): New spacing scale in EC - FRONT-4850
  .size-limit.json
  docs/Migrating-v5.md
  src/components/list-illustration/list-illustration.scss
  src/components/mega-menu/mega-menu.scss
  src/components/menu/menu.scss
  src/components/modal/modal.scss
  src/components/navigation-list/navigation-list.scss
  src/components/news-ticker/news-ticker.scss
  src/components/site-header/site-header-ec.scss
  src/themes/ec/_custom-properties.scss
  src/themes/ec/maps/spacing.scss
  src/themes/ec/variables/_blockquote.scss
  src/themes/ec/variables/_fact-figures.scss
  src/themes/ec/variables/_featured-item.scss
  src/themes/ec/variables/_language-list.scss
  src/themes/ec/variables/_list-illustration.scss
  src/themes/ec/variables/_list.scss
  src/themes/ec/variables/_mega-menu.scss
  src/themes/ec/variables/_menu.scss
  src/themes/ec/variables/_modal.scss
  src/themes/ec/variables/_navigation-list.scss
  src/themes/ec/variables/_popover.scss
  src/themes/ec/variables/_splash-page.scss
  src/themes/ec/variables/_tabs.scss
  src/themes/ec/variables/_typography.scss
  src/themes/eu/variables/_list-illustration.scss
  src/themes/eu/variables/_mega-menu.scss
  src/themes/eu/variables/_menu.scss
  src/themes/eu/variables/_modal.scss
  src/themes/eu/variables/_navigation-list.scss
  src/utilities/spacing/index.story.js
  src/website/src/pages/ec/guidelines/spacing/index.mdx
  src/website/src/pages/ec/utilities/spacing/docs/code.mdx
  src/website/src/pages/ec/utilities/spacing/docs/usage.mdx
Labels: tag: enhancement

#3948 fix(menu): fix current item - FRONT-4868
  pnpm-lock.yaml
  src/components/menu/menu.scss
Labels: tag: bug fix

#3949 chore(deps): Updates 15-04-25
  package.json
  pnpm-lock.yaml
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
Labels: tag: internal

#3938 feat(typography): Responsive font. - FRONT-4861
  src/components/featured-item/featured-item.scss
  src/themes/ec/_mixins.scss
  src/themes/ec/mixins/_typography.scss
  src/themes/ec/variables/_featured-item.scss
  src/themes/eu/_mixins.scss
  src/themes/eu/mixins/_typography.scss
  src/themes/eu/variables/_featured-item.scss
Labels: tag: enhancement, process: review needed

#3954 fix(safari): Icon size in navigation list - FRONT-4877
  src/components/navigation-list/navigation-list.scss
Labels: tag: bug fix, process: review needed

#3952 fix(fonts): Fixing fallback on local font for Inter family - FRONT-4875
  src/presets/ec/src/ec.scss
Labels: tag: bug fix

#3953 chore(deps): Updates - 22-04-25
  .eslintignore
  package.json
  pnpm-lock.yaml
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
Labels: tag: internal

#3957 feat(social-media-follow): update spacing - FRONT-4873
  src/components/social-media-follow/social-media-follow.scss
Labels: tag: enhancement

#3962 feat(video): Always plays inline - FRONT-4880
  src/components/gallery/__snapshots__/gallery.test.js.snap
  src/components/media-container/__snapshots__/media-container.test.js.snap
  src/components/video/__snapshots__/video.test.js.snap
  src/components/video/video.html.twig
Labels: tag: enhancement

#3958 feat(cleanup): Removing patch-package and patches - FRONT-4879
  package.json
  patches/@storybook+addon-cssresources+6.2.9.patch
  pnpm-lock.yaml
Labels: tag: internal, process: review needed

#3964 chore(deps): Updates - 28-04-25
  package.json
  pnpm-lock.yaml
  src/tools/builder/package.json
Labels: tag: internal

#3966 fix(featured-item): Fixing text color when using the default css and markup inside the description - FRONT-4887
  src/components/featured-item/featured-item.scss
Labels: tag: bug fix

#3960 fix(website): String replacement in getting started page - FRONT-4871
  src/website/scripts/mdx-replace.js
  src/website/vite.config.js
Labels: tag: internal

#3969 chore(pnpm): Updating to 10.9.0 - FRONT-4891
  .github/workflows/ci.yml
  .github/workflows/production.yml
  docs/developers-start-here.md
  package.json
  pnpm-lock.yaml
Labels: tag: internal

#3959 feat(content-block): update font - FRONT-4872
  src/components/content-block/content-block.scss
  src/components/description-list/description-list.scss
  src/themes/ec/variables/_content-block.scss
  src/themes/ec/variables/_description-list.scss
  src/themes/eu/variables/_content-block.scss
  src/themes/eu/variables/_description-list.scss
Labels: tag: enhancement
