Repository ec-europa/europa-component-library, pull requests merged in 2025-01, with the labels that each got.

#3753 feat(website): Showing custom properties hovering on color name in website showcase - FRONT-4703
  src/themes/ec/_custom-properties.scss
  src/website/package.json
  src/website/src/pages/ec/guidelines/colours/index.mdx
  src/website/src/pages/eu/guidelines/colours/index.mdx
  src/website/src/website-components/Color/Card.jsx
  src/website/src/website-components/Color/Card.scss
  src/website/src/website-components/Color/PaletteItem.jsx
  src/website/src/website-components/Color/PaletteItem.scss
  src/website/src/website-components/index.js
  yarn.lock
Labels: tag: enhancement

#3758 fix(navigation-list): fix image size on safari - FRONT-4705
  src/implementations/vanilla/components/navigation-list/navigation-list.scss
Labels: tag: bug fix

#3760 chore(v5): Adding npm-check-updates to perform deps updates
  package.json
  pnpm-lock.yaml
  src/tools/builder/package.json
  src/website/package.json
Labels: tag: internal

#3761 chore(deps): Updates 07-01-25
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3762 chore(docs): Replacing yarn with pnpm in the docs - FRONT-4708
  .prettierignore
  README.md
  docs/Migrating-v5.md
  docs/developers-start-here.md
  package.json
  src/website/README.md
  src/website/public/admin/README.md
  src/website/src/pages/ec/getting-started/index.mdx
  src/website/src/pages/eu/getting-started/index.mdx
Labels: tag: internal

#3765 chore(v5): Creating new fs structure - FRONT-4712
  pnpm-workspace.yaml
  src/components/README.md
  src/compositions/README.md
  src/layout/README.md
  src/page-example/README.md
  src/playground/ec/.storybook/main.js
  src/playground/eu/.storybook/main.js
  src/utilities/README.md
Labels: tag: internal

#3774 chore: Less deps - v5
  pnpm-lock.yaml
  src/components/accordion/package.json
  src/components/banner/package.json
  src/components/blockquote/package.json
  src/components/breadcrumb/package.json
  src/components/button/package.json
  src/components/card/package.json
  src/components/carousel/package.json
  src/components/category-filter/package.json
  src/components/checkbox/package.json
  src/components/content-block/package.json
  src/components/content-item/package.json
  src/components/date-block/package.json
  src/components/datepicker/package.json
  src/components/description-list/package.json
  src/components/expandable/package.json
  src/components/fact-figures/package.json
  src/components/featured-item/package.json
  src/components/file-upload/package.json
  src/components/file/package.json
  src/components/form-group/package.json
Labels: tag: internal

#3767 feat(color): add color modes - FRONT-4710
  .size-limit.json
  docs/Migrating-v5.md
  pnpm-lock.yaml
  src/implementations/twig/components/tag/README-tag-set.md
  src/implementations/twig/components/tag/README.md
  src/implementations/twig/components/tag/tag-set.html.twig
  src/implementations/twig/components/tag/tag-set.story.js
  src/implementations/twig/components/tag/tag.html.twig
  src/implementations/twig/components/tag/tag.story.js
  src/implementations/vanilla/color-modes/color-modes.scss
  src/implementations/vanilla/color-modes/package.json
  src/implementations/vanilla/components/tag/tag.scss
  src/playground/addons/story-utils/index.js
  src/playground/ec/.storybook/preview-head.html
  src/playground/ec/.storybook/preview.js
  src/presets/ec/ecl-builder.config.js
  src/presets/ec/package.json
  src/presets/ec/src/ec-color-modes.scss
  src/themes/ec/_custom-properties.scss
  src/themes/ec/maps/color.scss
  src/themes/ec/theme.scss
Labels: tag: new feature

#3778 chore(deps): Updates - 16-01-25
  package.json
  pnpm-lock.yaml
  src/components/gallery/package.json
  src/components/inpage-navigation/package.json
  src/components/mega-menu/package.json
  src/components/menu/package.json
  src/components/modal/package.json
  src/implementations/vanilla/components/site-header/package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
Labels: tag: internal

#3779 chore(deps): Updates 16-01-25
  package.json
  src/implementations/vanilla/components/gallery/package.json
  src/implementations/vanilla/components/inpage-navigation/package.json
  src/implementations/vanilla/components/modal/package.json
  src/implementations/vanilla/components/site-header/package.json
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#3783 chore(website): Fixing copy of the hex value - FRONT-4748
  src/website/src/website-components/Color/PaletteItem.jsx
Labels: tag: bug fix

#3771 feat(button): color mode button
  src/themes/ec/variables/_button.scss
Labels: tag: enhancement

#3780 feat(date-block): color mode - FRONT-4737
  src/components/date-block/date-block-print.scss
  src/components/date-block/date-block.scss
  src/themes/ec/variables/_date-block.scss
Labels: tag: enhancement

#3786 feat(link): color mode - FRONT-4734
  src/components/link/link-print.scss
  src/themes/ec/variables/_link.scss
Labels: tag: enhancement

#3787 feat(fact-figures): color mode - FRONT-4741
  src/components/fact-figures/README.md
  src/components/fact-figures/fact-figures-print.scss
  src/components/fact-figures/fact-figures.html.twig
  src/components/fact-figures/fact-figures.scss
  src/components/fact-figures/fact-figures.story.js
  src/themes/ec/variables/_fact-figures.scss
  src/themes/eu/variables/_fact-figures.scss
Labels: tag: enhancement

#3790 feat(timeline): color mode - FRONT-4740
  src/components/timeline/timeline-print.scss
  src/components/timeline/timeline.scss
  src/themes/ec/_custom-properties.scss
  src/themes/ec/variables/_timeline.scss
Labels: tag: enhancement

#3791 feat(expandable): color mode - FRONT-4750
  src/components/expandable/expandable.scss
  src/themes/ec/variables/_expandable.scss
  src/themes/eu/variables/_expandable.scss
Labels: tag: enhancement

#3785 chore(node): Using node 22.11.0 (LTS)
  .github/workflows/ci.yml
  .github/workflows/production.yml
  .nvmrc
  README.md
  docs/developers-start-here.md
  package.json
  pnpm-lock.yaml
  src/tools/builder/package.json
  src/website/src/pages/ec/whats-new/index.md
Labels: tag: internal

#3792 feat(list): color mode - FRONT-4735
  src/components/ordered-list/ordered-list.scss
  src/components/unordered-list/unordered-list.scss
  src/themes/ec/variables/_list.scss
Labels: tag: enhancement

#3793 feat(blockquote): color modes - FRONT-4745
  src/components/blockquote/README.md
  src/components/blockquote/blockquote.html.twig
  src/components/blockquote/blockquote.scss
  src/components/blockquote/blockquote.story.js
  src/themes/ec/variables/_blockquote.scss
  src/themes/eu/variables/_blockquote.scss
Labels: tag: enhancement

#3797 feat(v5): Adding package to distribute all the twig templates - FRONT-4752
  .gitignore
  docs/Migrating-v5.md
  pnpm-lock.yaml
  pnpm-workspace.yaml
  src/twig-templates/package.json
Labels: tag: new feature

#3784 feat(label): color mode - FRONT-4732
  src/themes/ec/variables/_label.scss
  src/themes/eu/variables/_label.scss
Labels: tag: enhancement

#3794 feat(description-list): color mode - FRONT-4736
  src/components/description-list/description-list.story.js
  src/themes/ec/variables/_description-list.scss
Labels: tag: enhancement

#3751 chore(js): Exporting an esm bundle of the ECL js and logos - FRONT-4701
  .eslintrc.js
  .size-limit.json
  package.json
  pnpm-lock.yaml
  src/components/select/select.js
  src/components/table/table.js
  src/playground/ec/.storybook/preview-head.html
  src/playground/eu/.storybook/preview-head.html
  src/presets/ec/ecl-builder.config.js
  src/presets/ec/package.json
  src/presets/ec/src/ec-esm.js
  src/presets/eu/ecl-builder.config.js
  src/presets/eu/package.json
  src/presets/eu/src/eu-esm.js
  src/resources/logo-ec/package.json
  src/resources/logo-ec/scripts/esm-export.js
  src/resources/logo-eu/package.json
  src/resources/logo-eu/scripts/esm-export.js
  src/tools/builder/package.json
  src/tools/builder/scripts/scripts.js
  src/website/src/components/SplashPage/LogoLink.jsx
  src/website/src/components/SplashPage/SplashPage.jsx
  src/website/src/pages/ec/getting-started/index.mdx
  src/website/src/pages/eu/getting-started/index.mdx
  src/website/webpack.config.prod.js
Labels: tag: new feature

#3800 feat(banner): color modes - FRONT-4743
  src/components/banner/README.md
  src/components/banner/banner.html.twig
  src/components/banner/banner.scss
  src/components/banner/banner.story.js
  src/themes/ec/_custom-properties.scss
  src/themes/ec/variables/_banner.scss
Labels: tag: enhancement

#3801 chore(deps): Updates 23-01-25
  package.json
  pnpm-lock.yaml
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
Labels: tag: internal

#3804 feat(content-block): color modes - FRONT-4728
  src/components/content-block/content-block.scss
  src/themes/ec/variables/_content-block.scss
Labels: tag: enhancement, process: review needed

#3808 chore(deps): updates 27 01 25
  package.json
  pnpm-lock.yaml
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
Labels: tag: internal

#3803 feat(navigation-list): Color mode. - FRONT-4731
  src/components/navigation-list/README.md
  src/components/navigation-list/navigation-list.html.twig
  src/components/navigation-list/navigation-list.scss
  src/components/navigation-list/navigation-list.story.js
  src/themes/ec/variables/_navigation-list.scss
  src/themes/eu/variables/_navigation-list.scss
Labels: tag: enhancement

#3806 feat(carousel): color modes - FRONT-4744
  src/components/carousel/carousel.html.twig
  src/components/carousel/carousel.scss
  src/components/carousel/carousel.story.js
  src/themes/ec/variables/_carousel.scss
  src/themes/eu/variables/_carousel.scss
Labels: tag: enhancement

#3795 feat(media container): color modes - FRONT-4738
  pnpm-lock.yaml
  src/components/media-container/media-container.scss
  src/components/media-container/media-container.story.js
  src/themes/ec/variables/_media-container.scss
  src/themes/eu/variables/_media-container.scss
Labels: tag: enhancement, process: review needed

#3802 feat(featured-item): color modes - FRONT-4739
  src/components/featured-item/README.md
  src/components/featured-item/featured-item.html.twig
  src/components/featured-item/featured-item.scss
  src/components/featured-item/featured-item.story.js
  src/themes/ec/variables/_featured-item.scss
Labels: tag: enhancement, process: review needed

#3807 feat(card): Card color mode. - FRONT-4730
  src/components/card/card.html.twig
  src/components/card/card.scss
  src/components/card/card.story.js
  src/themes/ec/variables/_card.scss
  src/themes/eu/variables/_card.scss
Labels: tag: enhancement

#3805 feat(content-item): Color mode. - FRONT-4729
  src/components/card/README.md
  src/components/card/card.html.twig
  src/components/card/card.scss
  src/components/card/card.story.js
  src/components/content-item/README.md
  src/components/content-item/content-item.html.twig
  src/components/content-item/content-item.story.js
  src/themes/ec/variables/_card.scss
  src/themes/ec/variables/_content-item.scss
  src/themes/eu/variables/_card.scss
Labels: tag: enhancement

#3810 fix(carousel): Better handling banner equal heights including the footer - FRONT-4757
  src/components/carousel/__snapshots__/carousel.test.js.snap
  src/components/carousel/carousel.js
  src/components/carousel/carousel.test.js
  src/components/carousel/demo/data.js
Labels: tag: enhancement

#3811 feat(select): Improved placeholder color. - FRONT-4758
  src/themes/ec/variables/_select.scss
Labels: tag: enhancement

#3813 feat(print): ECL 5 - improve print for fact pages - FRONT-4648
  pnpm-lock.yaml
  src/components/banner/banner-print.scss
  src/components/blockquote/blockquote-print.scss
  src/components/content-block/content-block-print.scss
  src/components/fact-figures/fact-figures-print.scss
  src/components/featured-item/featured-item-print.scss
  src/components/link/link-print.scss
  src/components/list-illustration/list-illustration-print.scss
  src/components/media-container/media-container-print.scss
  src/components/page-header/page-header-print-ec.scss
  src/components/page-header/page-header-print-eu.scss
  src/components/site-header/site-header-print.scss
  src/components/social-media-follow/social-media-follow-print.scss
  src/components/timeline/timeline-print.scss
  src/components/unordered-list/unordered-list-print.scss
  src/page-example/page-fact-sheet/.npmignore
  src/page-example/page-fact-sheet/README.md
  src/page-example/page-fact-sheet/demo/data.js
  src/page-example/page-fact-sheet/package.json
  src/page-example/page-fact-sheet/page-fact.html.twig
  src/page-example/page-fact-sheet/page-fact.story.js
  src/page-example/page-inner/demo/data.js
  src/playground/ec/.storybook/preview-head.html
  src/playground/ec/.storybook/preview.js
  src/playground/eu/.storybook/preview-head.html
  src/playground/eu/.storybook/preview.js
  src/presets/ec/src/ec-print.scss
  src/presets/eu/src/eu-print.scss
  src/themes/ec/maps/layout.scss
  src/themes/ec/maps/typography.scss
  src/themes/ec/variables/_banner.scss
  src/themes/ec/variables/_blockquote.scss
  src/themes/ec/variables/_featured-item.scss
  src/themes/ec/variables/_list-illustration.scss
  src/themes/ec/variables/_timeline.scss
  src/themes/ec/variables/_typography.scss
  src/themes/eu/maps/layout.scss
  src/themes/eu/variables/_banner.scss
  src/themes/eu/variables/_featured-item.scss
  src/themes/eu/variables/_list-illustration.scss
  src/themes/eu/variables/_timeline.scss
  src/themes/eu/variables/_typography.scss
  src/utilities/typography/typography-print.scss
Labels: tag: enhancement

#3812 feat(tabs): Tabs extra classes on items. - FRONT-4758
  src/components/tabs/README.md
  src/components/tabs/__snapshots__/tabs.test.js.snap
  src/components/tabs/tabs.html.twig
  src/components/tabs/tabs.test.js
Labels: tag: enhancement

#3809 feat(site header, menu): color mode - FRONT-4755
  pnpm-lock.yaml
  src/components/site-header/site-header-print.scss
  src/presets/ec/src/ec-print.scss
  src/presets/eu/src/eu-print.scss
  src/themes/ec/variables/_mega-menu.scss
  src/themes/ec/variables/_menu.scss
  src/themes/ec/variables/_site-header.scss
Labels: tag: enhancement

#3815 chore(page-examples): fixing alignment, fix search page template
  src/page-example/page-inner/page-inner.html.twig
  src/page-example/page-search/page-search.html.twig
Labels: tag: internal

#3814 feat(timeline): apply color mode to bullets - FRONT-4762
  src/components/timeline/README.md
  src/components/timeline/timeline.html.twig
  src/components/timeline/timeline.story.js
  src/themes/ec/_custom-properties.scss
  src/themes/ec/maps/color.scss
Labels: tag: enhancement

#3821 feat(color): token updates - FRONT-4770
  src/components/fact-figures/fact-figures.scss
  src/themes/ec/_custom-properties.scss
  src/themes/ec/maps/color.scss
Labels: tag: enhancement

#3819 fix(etrans): Fixing button's hover styles - FRONT-4746
  src/compositions/etrans/__snapshots__/etrans.test.js.snap
  src/compositions/etrans/etrans-ec.html.twig
Labels: tag: bug fix

#3818 chore(menu): Removing unneeded stickyfilljs - FRONT-4764
  pnpm-lock.yaml
  src/components/menu/menu.js
  src/components/menu/package.json
Labels: tag: internal

#3817 feat(button, link): update focus display - FRONT-4765
  src/components/link/link.scss
  src/themes/ec/variables/_button.scss
  src/themes/ec/variables/_link.scss
  src/themes/eu/variables/_link.scss
Labels: tag: enhancement

#3823 feat(color): small fixes - FRONT-4773
  src/components/navigation-list/navigation-list.scss
  src/components/tag/tag.scss
  src/themes/ec/_custom-properties.scss
  src/themes/ec/variables/_content-item.scss
  src/themes/ec/variables/_expandable.scss
  src/themes/ec/variables/_tag.scss
Labels: tag: enhancement, process: review needed
