Repository ec-europa/europa-component-library, pull requests merged in 2025-05, with the labels that each got.

#3973 chore(deps): Updates 02-05-25
  package.json
  pnpm-lock.yaml
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
Labels: tag: internal

#3975 chore(deps): Updates 05-05-25
  package.json
  pnpm-lock.yaml
  src/tools/builder/package.json
  src/website/package.json
Labels: tag: internal

#3970 feat(colors): Changed surface color. - FRONT-4885
  src/themes/ec/_custom-properties.scss
Labels: tag: enhancement

#3977 feat(typography): Added new tokens - FRONT-4894
  src/themes/ec/_custom-properties.scss
  src/themes/ec/maps/typography.scss
Labels: tag: enhancement

#3978 feat(typography): Adding values for tablet font styles - FRONT-4895
  .size-limit.json
  src/themes/ec/_custom-properties.scss
  src/themes/ec/maps/typography.scss
  src/themes/ec/variables/_typography.scss
  src/themes/eu/_custom-properties.scss
  src/themes/eu/variables/_typography.scss
  src/utilities/typography/typography.scss
Labels: tag: enhancement

#3979 chore(deps): Updates 07-05-25
  package.json
  pnpm-lock.yaml
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
Labels: tag: internal

#3980 feat(typography): Updating letter spacing scale in EC - FRONT-4896
  src/themes/ec/maps/typography.scss
  src/themes/ec/mixins/_typography.scss
  src/themes/ec/theme.scss
  src/themes/ec/variables/_banner.scss
  src/themes/ec/variables/_inpage-navigation.scss
  src/themes/ec/variables/_page-header.scss
  src/themes/ec/variables/_typography.scss
  src/themes/eu/mixins/_typography.scss
  src/utilities/typography/typography-print.scss
  src/utilities/typography/typography.scss
Labels: tag: enhancement

#3967 feat(footer): new EC footer standardised/harmonised - FRONT-4851
  docs/Migrating-v5.md
  pnpm-lock.yaml
  src/components/site-footer/README.md
  src/components/site-footer/__snapshots__/site-footer.test.js.snap
  src/components/site-footer/demo/data-core--ec.js
  src/components/site-footer/demo/data-harmonised--ec.js
  src/components/site-footer/demo/data-standardised--ec.js
  src/components/site-footer/ec-site-footer.story.js
  src/components/site-footer/eu-site-footer.story.js
  src/components/site-footer/package.json
  src/components/site-footer/site-footer-ec-section.html.twig
  src/components/site-footer/site-footer-ec.html.twig
  src/components/site-footer/site-footer-ec.scss
  src/components/site-footer/site-footer-eu.html.twig
  src/components/site-footer/site-footer.test.js
  src/components/social-media-follow/README.md
  src/components/social-media-follow/__snapshots__/social-media-follow.test.js.snap
  src/components/social-media-follow/social-media-follow.html.twig
  src/components/social-media-follow/social-media-follow.scss
  src/components/social-media-follow/social-media-follow.story.js
  src/components/social-media-follow/social-media-follow.test.js
  src/playground/addons/story-utils/index.js
  src/playground/addons/story-utils/package.json
  src/themes/ec/variables/_site-footer.scss
  src/themes/ec/variables/_social-media-follow.scss
Labels: tag: enhancement

#3976 feat(banner): mobile and tablet display - FRONT-4892
  docs/Migrating-v5.md
  src/components/banner/README.md
  src/components/banner/__snapshots__/banner.test.js.snap
  src/components/banner/banner-print.scss
  src/components/banner/banner.html.twig
  src/components/banner/banner.scss
  src/components/banner/banner.story.js
  src/components/carousel/carousel.js
  src/components/carousel/carousel.scss
  src/components/link/link.scss
  src/themes/ec/_custom-properties.scss
  src/themes/ec/variables/_banner.scss
  src/themes/eu/variables/_banner.scss
Labels: tag: enhancement

#3983 feat(typography): remove negative letter spacing - FRONT-4874
  docs/Migrating-v5.md
  src/components/page-header/page-header-ec.scss
  src/themes/ec/maps/typography.scss
  src/themes/ec/variables/_label.scss
  src/themes/ec/variables/_page-header.scss
  src/themes/ec/variables/_typography.scss
  src/utilities/typography/typography.scss
  src/website/src/pages/ec/guidelines/typography/index.mdx
Labels: tag: enhancement

#3987 chore(deps): Updates 16-05-25
  pnpm-lock.yaml
  src/playground/addons/storybook-addon-code/package.json
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/addons/storybook-addon-styles/package.json
  src/playground/addons/storybook-addon-system-switcher/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
Labels: tag: internal

#3984 feat(website): update container size - FRONT-4898
  src/website/src/components/DocPage/Header.module.scss
  src/website/src/components/Grid/grid.module.scss
  src/website/src/components/MainContainer/MainContainer.module.scss
  src/website/src/components/SimplePage/SimplePage.jsx
  src/website/src/routes/Skeleton.jsx
  src/website/src/styles/utilities.module.scss
Labels: tag: enhancement

#3991 feat(language-switcher): add translate=no - FRONT-4903
  src/components/site-header/__snapshots__/site-header.test.js.snap
  src/components/site-header/site-header-language-switcher.html.twig
  src/components/splash-page/__snapshots__/splash-page.test.js.snap
  src/components/splash-page/splash-page.html.twig
Labels: tag: enhancement

#3998 chore(deps): Updates 27-05-25
  package.json
  pnpm-lock.yaml
  src/tools/builder/package.json
  src/website/package.json
Labels: tag: internal

#3996 feat(typography): update microcopy token and utilities - FRONT-4905
  pnpm-lock.yaml
  src/mixins/README.md
  src/mixins/typography/mixins.scss
  src/presets/ec/src/ec-default-print.scss
  src/presets/ec/src/ec-default.scss
  src/presets/ec/src/ec-print.scss
  src/presets/ec/src/ec-utilities.scss
  src/presets/eu/src/eu-default-print.scss
  src/presets/eu/src/eu-default.scss
  src/presets/eu/src/eu-print.scss
  src/presets/eu/src/eu-utilities.scss
  src/themes/ec/variables/_typography.scss
  src/utilities/typography/index.story.js
  src/utilities/typography/package.json
  src/utilities/typography/typography-print.scss
  src/utilities/typography/typography.scss
  src/website/src/pages/ec/guidelines/typography/index.mdx
  src/website/src/pages/ec/utilities/typography/docs/code.mdx
  src/website/src/pages/ec/utilities/typography/docs/usage.mdx
Labels: tag: enhancement

#3992 feat(footer): add custom sections - FRONT-4904
  src/components/site-footer/README.md
  src/components/site-footer/__snapshots__/site-footer.test.js.snap
  src/components/site-footer/demo/data-harmonised--ec.js
  src/components/site-footer/demo/data-standardised--ec.js
  src/components/site-footer/ec-site-footer.story.js
  src/components/site-footer/site-footer-ec.html.twig
Labels: tag: new feature

#3999 chore(page-examples): Fixing rendering - FRONT-4912
  src/page-example/page-fact-sheet/demo/data.js
  src/page-example/page-fact-sheet/page-fact.html.twig
  src/page-example/page-fact-sheet/page-fact.story.js
  src/page-example/page-home/demo/data.js
  src/page-example/page-home/page-home.html.twig
  src/page-example/page-home/page-home.story.js
  src/page-example/page-inner/demo/data.js
  src/page-example/page-inner/page-inner.html.twig
  src/page-example/page-inner/page-inner.story.js
  src/page-example/page-search/demo/data.js
  src/page-example/page-search/page-search.html.twig
  src/page-example/page-search/page-search.story.js
Labels: tag: internal
