Repository ec-europa/europa-component-library, pull requests merged in 2025-07, with the labels that each got.

#4036 chore(deps): v4 - Updates 01-07-25
  package.json
  src/implementations/vanilla/components/featured-item/featured-item.scss
  src/implementations/vanilla/components/list-illustration/list-illustration.scss
  src/implementations/vanilla/components/mega-menu/mega-menu.scss
  src/implementations/vanilla/components/site-header/_site-header-dropdown.scss
  src/implementations/vanilla/components/splash-page/splash-page.scss
  src/playground/addons/storybook-addon-notes/package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#4030 feat(inpage): Styles iteration - FRONT-4948
  src/components/inpage-navigation/__snapshots__/inpage-navigation.test.js.snap
  src/components/inpage-navigation/demo/data.js
  src/components/inpage-navigation/inpage-navigation.html.twig
  src/components/inpage-navigation/inpage-navigation.scss
  src/components/inpage-navigation/inpage-navigation.story.js
  src/themes/ec/variables/_inpage-navigation.scss
  src/themes/eu/variables/_inpage-navigation.scss
Labels: tag: enhancement

#4038 fix(site-header): fix search form height - FRONT-4960
  src/components/site-header/site-header-eu.scss
Labels: tag: bug fix

#4039 chore(deps): Updates 07-07-25
  package.json
  pnpm-lock.yaml
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
Labels: tag: internal

#4001 feat(timeline): headline and timeline set - FRONT-4908
  .size-limit.json
  docs/Migrating-v5.md
  pnpm-lock.yaml
  src/components/timeline/README.md
  src/components/timeline/__snapshots__/timeline.test.js.snap
  src/components/timeline/demo/data--set.js
  src/components/timeline/demo/data.js
  src/components/timeline/package.json
  src/components/timeline/timeline-print.scss
  src/components/timeline/timeline-set.html.twig
  src/components/timeline/timeline.html.twig
  src/components/timeline/timeline.scss
  src/components/timeline/timeline.story.js
  src/components/timeline/timeline.test.js
  src/presets/rtl/src/rtl.scss
  src/themes/ec/variables/_timeline.scss
  src/themes/eu/variables/_timeline.scss
  src/website/src/pages/ec/components/timeline/docs/code.mdx
  src/website/src/pages/eu/components/timeline/docs/code.mdx
Labels: tag: new feature

#4040 fix(accordion): Setting by default aria-expanded to false - FRONT-4965
  src/components/accordion/__snapshots__/accordion.test.js.snap
  src/components/accordion/accordion.html.twig
Labels: tag: enhancement

#4041 fix(menu): Fixing background for prev arrow in overflow menu - FRONT-4911
  src/components/menu/menu.scss
Labels: tag: bug fix

#4050 chore(deps): Updates 14-07-25
  package.json
  pnpm-lock.yaml
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
Labels: tag: internal

#4048 feat(form): update color - FRONT-4964
  src/components/text-area/text-area.scss
  src/themes/ec/variables/_form-group.scss
  src/themes/ec/variables/_select.scss
  src/themes/ec/variables/_text-area.scss
  src/themes/ec/variables/_text-input.scss
Labels: tag: enhancement

#4055 fix(example-page): Making packages private - FRONT-4974
  pnpm-lock.yaml
  src/page-example/page-fact-sheet/package.json
  src/page-example/page-home/package.json
  src/page-example/page-inner/package.json
  src/page-example/page-search/package.json
Labels: tag: internal

#4058 feat(description-list): update spacing - FRONT-4975
  src/components/description-list/description-list.scss
  src/themes/ec/variables/_description-list.scss
  src/themes/eu/variables/_description-list.scss
Labels: tag: enhancement

#4062 chore(deps): Updates -22-07-25 - v4
  package.json
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
  yarn.lock
Labels: tag: internal

#4063 chore(deps): Updates 22-07-25 - v5
  package.json
  pnpm-lock.yaml
  src/playground/ec/package.json
  src/playground/eu/package.json
  src/tools/builder/package.json
  src/website/package.json
Labels: tag: internal

#4064 feat(select): rotate select icon - FRONT-4977
  docs/Migrating-v5.md
  src/components/select/select.scss
  src/website/src/pages/ec/getting-started/index.mdx
  src/website/src/pages/eu/getting-started/index.mdx
Labels: tag: enhancement

#4067 feat(site-header): update class font size - FRONT-4981
  src/themes/ec/variables/_site-header.scss
Labels: tag: enhancement

#3988 feat(typography): Changed to responsive font approach in components. - FRONT-4900
  package.json
  pnpm-lock.yaml
  src/components/banner/banner.scss
  src/components/banner/package.json
  src/components/breadcrumb/breadcrumb.scss
  src/components/breadcrumb/package.json
  src/components/site-header/_site-header-dropdown.scss
  src/components/site-header/package.json
  src/components/splash-page/package.json
  src/components/splash-page/splash-page.scss
  src/mixins/typography/mixins.scss
  src/themes/ec/variables/_banner.scss
  src/themes/ec/variables/_breadcrumb.scss
  src/themes/ec/variables/_language-list.scss
  src/themes/eu/variables/_banner.scss
  src/themes/eu/variables/_breadcrumb.scss
  src/themes/eu/variables/_language-list.scss
Labels: tag: enhancement

#4070 fix(demo): fix inverted demo - FRONT-4994
  src/components/button/button.story.js
  src/components/icon/icon.story.js
  src/components/link/link.story.js
  src/components/spinner/spinner.story.js
Labels: tag: bug fix, process: review needed

#4069 feat(search-form): make button label accessible - FRONT-4992
  src/components/search-form/search-form.scss
Labels: tag: enhancement

#4065 fix(icon): add aria-hidden - FRONT-4979
  src/components/accordion/__snapshots__/accordion.test.js.snap
  src/components/banner/__snapshots__/banner.test.js.snap
  src/components/breadcrumb/__snapshots__/breadcrumb.test.js.snap
  src/components/button/__snapshots__/button.test.js.snap
  src/components/card/__snapshots__/card.test.js.snap
  src/components/carousel/__snapshots__/carousel.test.js.snap
  src/components/category-filter/__snapshots__/category-filter.test.js.snap
  src/components/checkbox/__snapshots__/checkbox.test.js.snap
  src/components/content-block/__snapshots__/content-block.test.js.snap
  src/components/content-item/__snapshots__/content-item.test.js.snap
  src/components/datepicker/__snapshots__/datepicker.test.js.snap
  src/components/description-list/__snapshots__/description-list.test.js.snap
  src/components/expandable/__snapshots__/expandable.test.js.snap
  src/components/fact-figures/__snapshots__/fact-figures.test.js.snap
  src/components/featured-item/__snapshots__/featured-item.test.js.snap
  src/components/file/__snapshots__/file.test.js.snap
  src/components/form-group/__snapshots__/form-group.test.js.snap
  src/components/gallery/__snapshots__/gallery.test.js.snap
  src/components/icon/__snapshots__/icon.test.js.snap
  src/components/icon/icon.html.twig
  src/components/inpage-navigation/__snapshots__/inpage-navigation.test.js.snap
  src/components/link/__snapshots__/link.test.js.snap
  src/components/list-illustration/__snapshots__/list-illustration.test.js.snap
  src/components/media-container/__snapshots__/media-container.test.js.snap
  src/components/mega-menu/__snapshots__/mega-menu.test.js.snap
  src/components/menu/__snapshots__/menu.test.js.snap
  src/components/modal/__snapshots__/modal.test.js.snap
  src/components/news-ticker/__snapshots__/news-ticker.test.js.snap
  src/components/notification/__snapshots__/notification.test.js.snap
  src/components/page-header/__snapshots__/page-header.test.js.snap
  src/components/pagination/__snapshots__/pagination.test.js.snap
  src/components/popover/__snapshots__/popover.test.js.snap
  src/components/rating-field/__snapshots__/rating-field.test.js.snap
  src/components/search-form/__snapshots__/search-form.test.js.snap
  src/components/select/__snapshots__/select.test.js.snap
  src/components/site-footer/__snapshots__/site-footer.test.js.snap
  src/components/site-header/__snapshots__/site-header.test.js.snap
  src/components/social-media-follow/__snapshots__/social-media-follow.test.js.snap
  src/components/tabs/__snapshots__/tabs.test.js.snap
  src/components/tag/__snapshots__/tag.test.js.snap
  src/components/timeline/__snapshots__/timeline.test.js.snap
  src/compositions/etrans/__snapshots__/etrans.test.js.snap
  src/compositions/file-upload-status/__snapshots__/file-upload-status.test.js.snap
Labels: tag: bug fix

#4056 fix(carousel): Fixing some visual bug - FRONT-4970
  src/components/carousel/carousel.js
  src/components/carousel/carousel.scss
Labels: tag: bug fix

#4075 fix(news-ticker): fix padding on EU - FRONT-4996
  src/components/news-ticker/news-ticker.js
  src/components/news-ticker/news-ticker.scss
  src/themes/ec/variables/_news-ticker.scss
  src/themes/eu/variables/_news-ticker.scss
Labels: tag: bug fix

#4078 feat(border): add grey tokens - FRONT-5002
  src/themes/ec/_custom-properties.scss
  src/utilities/border/border.scss
  src/utilities/border/index.story.js
  src/website/src/pages/ec/guidelines/colours/index.mdx
Labels: tag: enhancement
